### ISSUE TITLE
Mapbox GL Image Transformation Issue

### ISSUE THREAD

**Issue by zo0m** [mapbox/mapbox-gl-js#9957] opened 2020-08-27 07:07 UTC
Mapbox breaks the image rendering when coordinates are not square. 

[check codepen](
https://codepen.io/zo0m/pen/xxVdRYP)

![mapbox-raster-source-transformation-issue](https://user-images.githubusercontent.com/1734953/91408046-ddd2ea80-e84b-11ea-927c-42f442ced378.jpg)

"Expect" version for comparison was made in Photoshop.

[original test image](https://img1.goodfon.com/wallpaper/nbig/9/25/textures-tekstura-polosy.jpg)

**Comment by mourner** [comment] 2021-11-17 18:33
Duplicate of #9158 and will be fixed shorly by #11292.

**Closed by mourner** 2021-11-17 18:33 UTC
Labels: bug :lady_beetle:
