### ISSUE TITLE
Weird map behaviour when zooming in after deleting markers

### ISSUE THREAD

**Issue by technowar** [mapbox/mapbox-gl-js#9867] opened 2020-07-10 12:58 UTC
I have lots (around 25) markers that are updated regularly.

The problem is that, when I try to remove the markers after adding new updated markers, it'll also remove (?) almost everything on the map.

I followed this answer from SO when updating the marker, https://stackoverflow.com/a/55634103

<img width="1440" alt="Screenshot 2020-07-10 at 8 54 31 PM" src="https://user-images.githubusercontent.com/2110456/87156908-029cee00-c2f0-11ea-8099-59d7250a06f2.png">

**Comment by mourner** [comment] 2020-07-10 14:14
Unfortunately it's impossible for us to tell what the issue is without a minimal live test case which was prompted by the issue template. So I have to close the issue, but will reopen if there's enough information to triage.

**Closed by mourner** 2020-07-10 14:14 UTC
