### ISSUE TITLE
Modify Map#fitBounds to delegate to Map#setCenter when only one point is provided as bounds.

### ISSUE THREAD

**Issue by bbodien** [mapbox/mapbox-gl-js#3307] opened 2016-10-06 17:02 UTC
**mapbox-gl-js version**: 0.25.1

**Example code**: http://codepen.io/bbodien/pen/ORQVkd?editors=0110
### Steps to Trigger Behavior
1. Create a `LngLatBounds` object and `extend()` it with a single LngLat point.
2. Call `fitBounds()` on the map using the `LngLatBounds` object created in `1`
3. If you uncomment JS line 49 in the Codepen example which expands the bounding box by 0.00001 in Longitude and Lattitude, giving the bounding box some dimensions, the error is not thrown.
### Expected Behavior

Despite the fact that the bounding box is just a single point and has no dimensions (SW and NE coordinates are identical), I'd expect the map to still fit around that point. 

To explain my use case, I'm receiving geojson data for locations on a trip. These could be Lines or Points. If the geojson contains Points, the number of Points is 1..n. I'm using `fitBounds()` to handle fitting my map to the data area regardless of what data I have, and I'm experiencing this error when I have 1 Point.
### Actual Behavior

An error is thrown after calling `fitBounds()`: `Error: Invalid LngLat object: (NaN, NaN)`.

**Comment by mollymerp** [comment] 2016-10-07 00:57
Calling [`new mapboxgl.LngLatBounds()`](https://www.mapbox.com/mapbox-gl-js/api/#LngLatBounds) without arguments should fire an error, bc `sw` and `ne` are required arguments. 

For your use case I would recommend using `map.setCenter()` when you only have one point, and only initializing the `LngLatBounds` when you have two or more points.

**Comment by mollymerp** [comment] 2016-10-07 02:01
Sorry, I misread our docs! There is also a typo in the docs where the parameters are not listed as optional. 

Yes, we have stated that `new mapboxgl.LngLatBounds()` should work without arguments. We should modify `Map#fitBounds` to delegate to `Map#setCenter` for unitary `LngLatBounds` objects. 

Thanks for reporting @bbodien !!

**Comment by stepankuzmin** [comment] 2016-12-20 20:32
It seems to be working with the master branch. At least it wouldn't reproduce with 519004151fbb724439fe8ee15470d1e3a6ce89a6

**Comment by lucaswoj** [comment] 2016-12-20 22:34
Yes indeed! This was fixed by #3683

**Closed by lucaswoj** 2016-12-20 22:34 UTC
Labels: starter task
