### ISSUE TITLE
Clarify, rename or remove map.loaded() method

### ISSUE THREAD

**Issue by gpbmike** [mapbox/mapbox-gl-js#5052] opened 2017-07-26 22:45 UTC
**mapbox-gl-js version**: 39.1

### Steps to Trigger Behavior

Add a canvas source / layer to the map.

### Expected Behavior

`map.loaded()` eventually returns true.

### Actual Behavior

`map.loaded()` never returns true.

### Additional Details

I have created a codepen to demonstrate.

https://codepen.io/gpbmike/pen/NvqaZm

We're using `map.loaded()` to determine when certain actions can be performed that require the map to be loaded, see [mapbox-gl-draw](mapbox-gl-draw). We noticed that if you add a canvas source to the map, the `map.loaded()` will never change to `true`.

**Comment by mollymerp** [comment] 2017-07-26 23:13
Thanks for the report @gpbmike – I have confirmed that this is a bug, and `map.loaded()` isn't returning `true` because the source kicks off an infinite render loop.

**Comment by lbud** [comment] 2017-07-26 23:16
Oo 🕵️‍♀️ @mollymerp I would guess this applies to video sources too, then.

**Comment by mollymerp** [comment] 2017-07-26 23:33
@gpbmike `map.loaded()` checks that there are no pending source, tile, or style loads or updates and that the animation loop (triggered by any user interaction or programmatic map change) has finished. Because the animation loop never stops with animated canvas sources and video sources, that is blocking `map.loaded()` from returning `true`.

**Comment by mourner** [comment] 2018-07-25 12:18
This seems to be more of an API naming/documentation issue that an actual bug, so I renamed/labeled it accordingly.

**Comment by mourner** [comment] 2018-07-25 16:47
Closing in favor of #6708 to centralize the discussion there.

**Closed by mourner** 2018-07-25 16:47 UTC
Labels: api :memo:, docs :scroll:
