### ISSUE TITLE
CORS issue when accessing Mapbox default map

### ISSUE THREAD

**Issue by dmitrykinakh** [mapbox/mapbox-gl-js#7605] opened 2018-11-16 11:02 UTC
Hello!

Guys,  do you know why the example provided by this link is leading to the CORS issues? 
LINK - https://www.mapbox.com/mapbox-gl-js/example/simple-map/

My team is building a map-based app and we faced exactly with the same issue. 
I was thinking that is our issue but seems it's something Mapbox team need to take a look.

![image](https://user-images.githubusercontent.com/8025637/48617453-2f73f300-e99f-11e8-8323-25c33efb84b6.png)

**Comment by chloekraw** [comment] 2018-11-21 07:44
@dmitrykinakh - if you have other examples, that would be great. our team is digging into this. thanks!

**Comment by mourner** [comment] 2018-11-21 17:41
@dmitrykinakh I can reproduce the warnings in Firefox, but it doesn't affect how the map works in any way. It looks like the warnings are output whenever the tile requests are aborted (e.g. you zoomed to an area, it started loading tiles, but you zoomed away before requests were completed, so they were aborted). My best guess is that it's a harmless Firefox bug that makes it output a console warning when it shouldn't, so I'm inclined to close the issue. 

@kkaefer anything to add here? This is probably related to the recent switch to the Fetch API.

**Closed by mourner** 2018-11-21 17:41 UTC
