### ISSUE TITLE
webpack version of 0.45.0 crashes on load

### ISSUE THREAD

**Issue by jliebrand** [mapbox/mapbox-gl-js#6780] opened 2018-06-05 18:59 UTC
Sorry in advance for the lack of detail on this bug report - I'll continue to dig, but it's a bit of a mystery to me....

Basically I use es6 import to load mapbox as follows:
```
  componentDidMount () {
    import('mapbox-gl/dist/mapbox-gl.js')
      .then(this.setupMapbox.bind(this));
  }

```

This has worked fine but now that i've upgraded to 0.45.0 this stopped working in my production version (it works fine in dev). I use this inside a preact (not react) app, and dynamic imports like the above get compiled in to separate chunks (for better loading/caching).

But just after constructing mapbox (even before any load event comes back), there are two errors in the console: 
blob:https://localhost:8080/4be8ed96-9f12-467f-81e0-36e039bc4138:1 Uncaught ReferenceError: e is not defined
(anonymous) @ blob:https://localhost:8080/4be8ed96-9f12-467f-81e0-36e039bc4138:1
(anonymous) @ blob:https://localhost:8080/4be8ed96-9f12-467f-81e0-36e039bc4138:1
blob:https://localhost:8080/4be8ed96-9f12-467f-81e0-36e039bc4138:formatted:2230 Uncaught ReferenceError: e is not defined

I *believe* (?) mapbox loads some workers as blobs? Could this be inside that code?

Here's the formatted blob where the error is thrown
![image](https://user-images.githubusercontent.com/23407884/40996806-ad716934-68fa-11e8-99fb-5ac36465a683.png)

**Comment by jfirebaugh** [comment] 2018-06-05 19:34
Duplicate of #4359. See https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-303880888 for the root cause analysis and https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-286277540 or https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-288001933 for workarounds.

**Closed by jfirebaugh** 2018-06-05 19:34 UTC
