### ISSUE TITLE
GeoJSON marker text glyphs ignore text-allow-overlap

### ISSUE THREAD

**Issue by AlanPew** [mapbox/mapbox-gl-js#1374] opened 2015-07-15 22:43 UTC
This issue can be seen in the Mapbox GL example for loading a geojson marker layer:
https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/ 

When rotating the map, the glyphs from the mapbox vector layer avoid collisions and do not have any issues with text overlap.  However, the geojson text does not avoid collisions with other text on the same layer or the text from the other layers (Mapbox vector tile source).

**Comment by AlanPew** [comment] 2015-09-14 08:03
This issue is not limited to just geojson layers, but seems to be prevalent whenever the sources are not shared.  An example of the collisions when using multiple sources: http://maps.mobilecartography.com/gl/birding/ 

Not trying to nag, you all are doing an amazing job with WebGL/OpenGL!!  I am having so much fun with the new APIs/SDKs.  Mapbox is revolutionizing maps.

**Comment by jfirebaugh** [comment] 2015-09-14 19:59
You are correct, there's no ability to perform collision calculations across different sources right now. Implementing that is tracked in #1042.

**Comment by lyzidiamond** [comment] 2015-10-12 19:30
tagging @mapbox/support for known issue

**Comment by ansis** [comment] 2016-03-31 17:16
duplicate of #1042

**Closed by ansis** 2016-03-31 17:16 UTC
