### ISSUE TITLE
Add click handler on marker clusters

### ISSUE THREAD

**Issue by hdrdavies** [mapbox/mapbox-gl-js#3555] opened 2016-11-07 17:14 UTC
Apologies if this is already in the API, but I couldn't seem to find it.

### Steps to Trigger Behavior

 1. Adding a click handler on a clustered point of markers

### Expected Behavior

This may provide a 'cluster object' which would contain the features within the cluster.

**Comment by jfirebaugh** [comment] 2016-11-17 00:07
Duplicate of #3318.

**Closed by jfirebaugh** 2016-11-17 00:07 UTC
