### ISSUE TITLE
Markers disappear when crossing the antimeridian

### ISSUE THREAD

**Issue by msl-kabo** [mapbox/mapbox-gl-js#6323] opened 2018-03-13 21:20 UTC
**mapbox-gl-js version 0.44**:

### Steps to Trigger Behavior

 1. Use [react-map-gl](https://github.com/uber/react-map-gl), set up a map with markers
 2. Pan across the antimeridian

![2018-03-14-10_03_04 507624](https://user-images.githubusercontent.com/21163915/37370494-4748e2d8-2771-11e8-8877-3d8c1bd8df9d.gif)

### Expected Behavior
The markers on both sides of the antimeridian to be visible

### Actual Behavior
Only see markers on one side of the antimeridian at a time

I'm posting here because I think it may be related to #6315

**Comment by jfirebaugh** [comment] 2018-03-13 21:30
Those are markers as in [`Marker`](https://www.mapbox.com/mapbox-gl-js/api#marker) (as opposed to [symbol layers](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol))?

If so, this is expected behavior. The `Marker` API is implemented in terms of a single DOM element, which can't be in two places at once.

**Comment by msl-kabo** [comment] 2018-03-13 22:26
OK, yeah those are Markers. Quite annoying if you're trying to make a map and you live in New Zealand, thus crossing the antimeridian a lot.

I tried using the Scatterplot-overlay which uses canvas, but got the same result.
https://github.com/uber/react-map-gl/tree/master/examples/additional-overlays

**Comment by jfirebaugh** [comment] 2018-03-13 22:41
I think I might have misdiagnosed the issue. What I was referring to only matters when you're zoomed far enough out that multiple copies of the world are visible, which isn't the case here. When only one copy is visible Mapbox GL JS _will_ preserve the visual location of markers even when panning back and forth across the antimeridian. Here's an example: http://jsbin.com/bofonivaza/edit?html,output

So it looks to me like this is an issue with react-map-gl.

**Comment by jfirebaugh** [comment] 2018-03-14 22:38
Closing here since this seems to be a downstream issue.

**Closed by jfirebaugh** 2018-03-14 22:38 UTC
