### ISSUE TITLE
Add offset to new mapboxgl.Map() options

### ISSUE THREAD

**Issue by ntilwalli** [mapbox/mapbox-gl-js#3322] opened 2016-10-07 18:05 UTC
~~I'm porting a map from mapbox.js to mapbox-gl-js.  The `project` and `unproject` methods in that lib offer an optional zoom attribute which is not available in mapbox-gl (confirmed here: https://github.com/mapbox/mapbox-gl-js/blob/1d373b0596af42a6a5c5f7a5cc89ccc1e6076d95/js/ui/map.js#L428)~~

~~Can this be added?  Is this PR-able?~~

In mapbox.js I was using `project` and `unproject` to center the map with an offset to allow for an overlay div on the side of the map container.  What is the appropriate way to do this in mapbox-gl?  I ask because mapbox-gl does not offer a `zoom` argument for those methods and I feel it is important (especially for easing to a new location in one pass)...

**Comment by ntilwalli** [comment] 2016-10-07 18:55
Offering the zoom argument is also useful for initial paint with an offset.  I'm currently shifting the map after it has been loaded and this causes an initial paint with a non-offset center (since the project/unproject methods must be called on the map which has not been created yet) which then blips over to the new center...

**Comment by mollymerp** [comment] 2016-10-07 21:57
The map initialization does have a zoom argument (https://www.mapbox.com/mapbox-gl-js/api/#Map), but at the moment there is no offset option so you'll have to adjust your `center` LngLat coordinates to offset the position at initial paint. You can call `Map#fitBounds` after initialization with an `offset` option to get your desired positioning once the map is initialized. 

It might be worth considering adding an offset option to map initialization...

**Comment by ntilwalli** [comment] 2016-10-07 23:26
@mollymerp whey can't `project` and `unproject` in mapbox-gl have the same method signature as mapbox.js?  Those methods take a `zoom` parameter, mapbox-gl should do the same

 If they take a zoom argument I can call the those functions to give me the initial lngLat which corresponds to my offset.  As it stands I need the map to already be initialized to get access to the `project` and `unproject` functions which internally use the zoom information to calculate the return vals for `project` and `unproject`.  Having access to `zoom` directly as args to those methods means I can inject the appropriate center upon initialization instead of doing it on a second pass...

**Comment by lucaswoj** [comment] 2016-10-11 17:24
The primary feature request being discussed in this ticket is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/1740. Please open separate issues for separate feature requests.

**Closed by lucaswoj** 2016-10-11 17:24 UTC
Labels: enhancement

**Comment by benjaminhon** [comment] 2016-12-08 08:46
i am having the same issue, whats the point of calling project, if i don't know what zoom its projecting?
