### ISSUE TITLE
[Chrome] Cannot hold down arrow keys to pan

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-js#1721] opened 2015-11-13 19:30 UTC
In Chrome, holding down an arrow key does not continuously pan the map. It does one panning motion and stops. The user is then required to repeatedly press an arrow key to continue in that direction.

**Comment by jfirebaugh** [comment] 2015-11-13 19:34
Duplicate of #1661.

**Closed by jfirebaugh** 2015-11-13 19:34 UTC
Labels: enhancement
