### ISSUE TITLE
Display the good tiles at maxzoom

### ISSUE THREAD

**Issue by Madumo** [mapbox/mapbox-gl-js#2179] opened 2016-02-24 15:38 UTC
### Context

* **mapbox-gl-js version**: master at 81f7959 (post v0.14.2)

### Report

**Expected behavior**: Display the good rastered tiles at the maximum zoom level

**Actual behavior**: When you zoom to the maximum and you drag the map, it display the tiles at the good zoom level. When you release, it sometime display the tiles at the parent zoom level. I am currently using ratered tiles. 

**UPDATE**: it only happen if there is a parent tile in the cache. 

**Steps to reproduce the behavior**:

1. Use this style setting: 
```javascript
{
	version: 8,
	minZoom: 10,
	maxZoom: 15,
	sources: {
		tiles: {
			type: 'raster',
			tileSize: 256,
			url: 'mapbox://mapbox.streets'
		}
	},
	layers: [{
		id: 'tiles',
		type: 'raster',
		source: 'tiles',
		minzoom: 10,
		maxzoom: 16
	}]
}
```
2. Increase the zoom level to the maximum
3. Pan around the map.

### Optional

It may be because of e6cb15c or 4f99e94 ? I didn't investigate much but there was some change recently in the tile cache and tile ordering etc.

![image](http://g.recordit.co/4MvgzARBi5.gif)

**Comment by lucaswoj** [comment] 2016-03-03 19:01
Thank you very much for the thorough bug report @Madumo! I apologize for not getting back to you sooner. 

This looks like a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2208, which was fixed in https://github.com/mapbox/mapbox-gl-js/commit/69f01898692225e4739fe3c4d9a0fc5b4c4d7bdc and released as `v0.15.0`. Please re-open if you still see this behavior in `v0.15.0`. :rocket:

**Closed** 2016-03-03 19:16 UTC
