### ISSUE TITLE
declutter (padding) of symbols across different layers / sources

### ISSUE THREAD

**Issue by isimonescu** [mapbox/mapbox-gl-js#3168] opened 2016-09-09 12:17 UTC
I am having trouble getting a reasonable declutter to work across different layers.

I have a geojson of POIs which I want on top of my map. I do not want any other labels overlap with them underneath. As I understand your API, text-padding and icon-padding works for a layer / source only. Could it be possible to make it work across different sources?

Currently my workaround is to make a querySourceFeatures on labels, calculate and remove any overlapping with POIs. But this is an ugly workaround as I get a lot of "flickering" (appearing and dissapearing) labels on the map.

Any suggestions?

**Comment by kristfal** [comment] 2016-09-09 13:04
If the data is static, for now, your best bet is to create a composite of the geoJSON and the map data that you serve. 

This can either be done on your own map server or via mapbox's service iirc.

This issue will be resolved when #2703 lands.

**Comment by mourner** [comment] 2016-09-09 13:21
Yep, closing as duplicate of #2703. For now, I'd recommend uploading the GeoJSON to Mapbox Studio — it will do the compositing on the server side for you.

**Closed by mourner** 2016-09-09 13:21 UTC
