### ISSUE TITLE
Video layer doesn't show up on mobile browsers

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox-gl-js#7443] opened 2018-10-18 20:54 UTC
I'e got a video layer, that uses a H.264 yuv420p encoded mp4 file as a source. All shows up as expected on desktop browsers. But I don't see video on both mobile safari and chrome on ios. 
Didn't check android yet.
Mapbox video example doesn't work either.

Should I use different encoding?

**Comment by asheemmamoowala** [comment] 2018-10-18 21:16
Duplicate of #6443

**Closed by asheemmamoowala** 2018-10-18 21:16 UTC
