### ISSUE TITLE
Map Canvas larger than half of gl.MAX_RENDERBUFFER_SIZE(2048)

### ISSUE THREAD

**Issue by stackTom** [mapbox/mapbox-gl-js#3935] opened 2017-01-10 04:03 UTC
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. create wkwebview app on ios
 2.
 3.

### Expected Behavior
map loads
### Actual Behavior
map doesn't load

My mapbox web application doesn't load with the latest 0.30 on iOS. In Safari on iOS, it loads fine, but on chrome for iOS, the map never loads. I made a simple wkwebview app to diagnose the problem, and opened up safari on my mac to see the output of the console. The error I get is:

[Error] Error: Map canvas (1568x2440) is larger than half of gl.MAX_RENDERBUFFER_SIZE (2048)
	_setupPainter (mapbox-gl.js:207:10914)
	e (mapbox-gl.js:207:1847)
	addMapToPage (mainMap.js:757)
	(anonymous function) (mainPage.js:618)
What is wrong? If I browse the mapbox API site and view examples, everything works fine. My map takes up a div that is almost 100% width and height, could this be a clue?

**Comment by stackTom** [comment] 2017-01-10 04:20
The page renders fine on gl js 0.28.0.

**Comment by gkostyanikov** [comment] 2017-01-10 11:14
Same issue in firefox 50.1. Works normally in chrome and safari.
0.28 version worked in all three.

**Comment by jfirebaugh** [comment] 2017-01-10 16:30
Duplicate of #3915.

**Closed by jfirebaugh** 2017-01-10 16:30 UTC
