### ISSUE TITLE
Tamil characters rendered wrongly

### ISSUE THREAD

**Issue by cheeaun** [mapbox/mapbox-gl-js#9894] opened 2020-07-24 02:03 UTC
**mapbox-gl-js version**: 1.11.1
**browser**: Chrome, Safari, Firefox

### Link to Demonstration

https://jsfiddle.net/cheeaun/adrzysk7/1/ or https://jsbin.com/tojinod/edit?html,css,js,output

It's rendering (some of) the Tamil characters wrongly. I personally don't know how to read Tamil, but it's obviously rendered differently compared to how browsers render them.

<img width="383" alt="Screenshot 2020-07-24 at 9 58 34 AM" src="https://user-images.githubusercontent.com/2296/88354669-471a9600-cd94-11ea-965a-5321cd240904.png">

I've tried few ways to "fix" it:
1. Set `localIdeographFontFamily:
    '"InaiMathi", "Tamil Sangam MN", "Nirmala UI", Latha, Bamini ,Roboto, Noto, "Noto Sans Tamil", sans-serif'`.
2. Upload [Noto Sans Tamil](https://www.google.com/get/noto/#sans-taml) to Mapbox studio and set them as symbol layer style.

Here's another screenshot of a web site I'm working on (using Noto Sans Tamil Medium):

<img width="244" alt="Screenshot 2020-07-24 at 9 28 21 AM" src="https://user-images.githubusercontent.com/2296/88354809-bd1efd00-cd94-11ea-9526-00b7d58393f2.png">

The text is `சைனாடவுன்`.

**Comment by planemad** [comment] 2020-07-28 15:20
Issue lies upstream in Mapbox GL: https://github.com/mapbox/mapbox-gl-native/issues/7774

**Comment by 1ec5** [comment] 2020-07-28 16:45
Also tracked in this repository in #4009.

**Comment by asheemmamoowala** [comment] 2020-07-28 17:14
@cheeaun Thank you for reporting this issue. As mentioned, this is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/4009, let's focus the discussion in that ticket.

**Closed by asheemmamoowala** 2020-07-28 17:14 UTC
Labels: bug :beetle:
