### ISSUE TITLE
Issues using a 1x1 icon for `icon-text-fit` 

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#8347] opened 2019-06-12 20:40 UTC
I'm using a 1x1 icon that looks like this

```svg
<svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1" height="1" width="1" version="1.1">
 <path d="M1 0 0 0 0 1 1 1Z" fill="#63A076"/>
</svg>
```

on a layer that looks like this that uses the `icon-text-fit` property:

```json
{
    "id": "housenum-label",
    "type": "symbol",
    "source": "composite",
    "source-layer": "housenum_label",
    "layout": {
        "text-field": ["to-string", ["get", "house_num"]],
        "icon-text-fit": "both",
        "icon-image": "fill-green"
    },
    "paint": {"text-color": "hsl(0, 100%, 100%)"}
}
```

I'm noticing a couple behaviours:

1. The icon is not completely filling up the space on longer labels

<img width="170" alt="Screen Shot 2019-06-12 at 4 36 09 PM" src="https://user-images.githubusercontent.com/61150/59384484-478ed380-8d30-11e9-9c9e-980de07dbae3.png">

2. There's quite a noticeable blur when you zoom in/out. 

![blur](https://user-images.githubusercontent.com/61150/59384672-b835f000-8d30-11e9-9c28-b9ab64a3f57d.gif)

---

**mapbox-gl-js version**: `v1.0.0`
**browser**: `Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)`

### Expected behvaviour

For 1. I would expect the icon to fill the entire length of the label.
For 2. I would expect the icon to not blur and recalculate its size on `moveend`.

### Link to Demonstration

https://jsfiddle.net/e7gvdzLr/13/embedded/result/?username=tristen

**Comment by kkaefer** [comment] 2019-09-16 14:54
This will be fixed by https://github.com/mapbox/mapbox-gl-js/pull/8741

**Closed** 2019-09-24 08:52 UTC
Labels: bug :beetle:

**Comment by tristen** [comment] 2019-11-14 14:43
@kkaefer has this made it into a version? I'm still seeing this issue when applying a 1px to labels to create underlines:

![underlines](https://user-images.githubusercontent.com/61150/68866925-222d3980-06c3-11ea-8d9a-fd8289461aa5.gif)

**Comment by kkaefer** [comment] 2019-11-14 15:02
Are you referring to the "blur"? If so, this is intended behavior since we're using linear scaling while the map is being zoomed/rotated. This will become the default state once https://github.com/mapbox/mapbox-gl-js/pull/8738 lands so there's no switchover. 1&times;1 stretching icons without https://github.com/mapbox/mapbox-gl-js/issues/8917 will continue to look like this. You can achieve the desired effect once https://github.com/mapbox/mapbox-gl-js/issues/8917 lands, and then use a 3&times;1px icon with a stretch zone.

**Comment by tristen** [comment] 2020-03-11 15:02
@kkaefer I'm testing out the new stretchable icon feature and I'm seeing similar behaviour using this icon: [default.svg.zip](https://github.com/mapbox/mapbox-gl-js/files/4318963/default.svg.zip)

![blurring](https://user-images.githubusercontent.com/61150/76431176-a2b92980-6387-11ea-9faf-d2e4cb3dc5ac.gif)

**Comment by kkaefer** [comment] 2020-03-12 10:11
Icons being blurry while zooming is by design: when you're zooming, the position of the icon changes by fractional pixels (unlike when you're panning). so we decided to disable pixel grid snapping because otherwise they would appear to jiggle.
