### ISSUE TITLE
Add Polygon to evaluable geometry for `within` expression 

### ISSUE THREAD

**Issue by markusand** [mapbox/mapbox-gl-js#10479] opened 2021-03-17 11:17 UTC
## Motivation
The `within` expression simplified a lot the visualization of features depending on their geometry, but only Point and LineString are supported (according to docs). I would find very useful to support Polygon as well, specially as I'm working with polygon cells.

It may be a discussion of what whitin means for polygon (fully contained, some intersection, ...) but that is the same case with LineString, isn't it? I would consider a Polygon intersecting another one as within

### Implementation
Polygon contour can be considered a LineString, so I guess it would be quite straightforward to perform the operation.
This change would not affect the public API of MapboxGL.

**Comment by asheemmamoowala** [comment] 2021-04-07 22:21
Closing as duplicate of #9795 to keep the discussion in one place. @markusand Thanks for also commenting there.

**Closed by asheemmamoowala** 2021-04-07 22:21 UTC
Labels: feature :green_apple:
