### ISSUE TITLE
video on map broken in Safari

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-js#940] opened 2015-01-17 00:26 UTC
https://www.mapbox.com/mapbox-gl-js/example/video-on-a-map/

Works in Chrome, but not Safari.

**Comment by tmcw** [comment] 2015-05-26 16:35
The ajax.getVideo call is failing. Looking into this.

**Comment by tmcw** [comment] 2015-05-26 18:09
Upstream: Safari doesn't support CORS on HTML5 Video elements. Marking as upstream, removing bug classification. Apple is aware of the issue but afaict there is no public issue tracker for Safari, so no upstream link.

**Comment by incanus** [comment] 2015-05-26 18:17
> Apple is aware of the issue but afaict there is no public issue tracker for Safari, so no upstream link.

Typical practice is to file at http://bugreport.apple.com ("file a Radar") and get back an issue number, duplicate-file it to http://openradar.appspot.com, and in public forums refer to it as `rdar://xxxxxxxx`.

**Comment by 1ec5** [comment] 2015-05-26 18:52
@tmcw @incanus If the issue is in WebKit proper, rather than Safari’s UI, the proper channel is to file a bug in [WebKit’s public Bugzilla instance](https://bugs.webkit.org/).

**Comment by friedbunny** [comment] 2015-05-26 18:54
Per @1ec5's helpful link [here is the upstream WebKit issue](https://bugs.webkit.org/show_bug.cgi?id=135379).

**Comment by ansis** [comment] 2016-03-24 19:29
There isn't anything actionable on our side. closing

**Closed by ansis** 2016-03-24 19:29 UTC
Labels: blocked externally, machine-dependent bug
