### ISSUE TITLE
When I use Mapbox GL to render heatmap with PBF WMTS point layer I can not get the desired result

### ISSUE THREAD

**Issue by chaoboma** [mapbox/mapbox-gl-js#12106] opened 2022-07-22 05:14 UTC
I have a POINT SHP layer then I want to render heatmap using Mapbox GL like this:

![image](https://user-images.githubusercontent.com/3273285/180367295-10dcd259-4796-4d09-a857-13492aed700a.png)

But I can not get my desired result. I use GeoServer to publish a PBF WMTS and this service is normal. When I use a single Geojson data to test in Mapboxgl ,it is normal too. My Mapbox style is like this:

source:

"sources": {

    "pbf_point": {
      "type": "vector",
      "tiles": [
       
        "http://192.168.60.2:8080/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=shp_10&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/vnd.mapbox-vector-tile&TILECOL={x}&TILEROW={y}"
      ],
      "minzoom": 6,
      "maxzoom": 12
    }
  }

layer:

"layers": [
    {
      "id": "pbf_point",
      "type": "heatmap",
      "source": "pbf_point",
      "source-layer": "shp_10",
      "minzoom": 6,
      "maxzoom": 11,
      "paint": {
         "heatmap-radius": 10,
         "heatmap-weight":[
            "interpolate",
            ["linear"],
            ["get", "value"],
            400,0,
            1950,1
            ],
          "heatmap-intensity": [
            "interpolate",
            ["linear"],
            ["zoom"],
            0,
            1,
            11,
            5
        ],
          "heatmap-color": [
            "interpolate",
            ["linear"],
            ["heatmap-density"],
            0,
            "rgba(33,102,172,0)",
            0.1,
            "#4169e1",
            0.3,
            "#00ffff",
            0.5,
            "#00ff00",
            0.7,
            "#ffff00",
            1,
            "#ff0000"
          ],
          "heatmap-opacity": 1
        }
    }
    
  ]

I can get heatmap in brower:

![image](https://user-images.githubusercontent.com/3273285/180367440-e184ccb4-05fd-44d2-851c-dd1cbf817e9d.png)

but:

["get", "value"] in "heatmap-weight" did not work. I can not configure color in this way. The "value" string is a column in my PBF tile. I test this configuration in GeoJSON and it can work well. Mapbox GL does not surpport GeoJSON wmts tile. Data is so large and level needs zoom to 15 , so I can not use GeoJSON.

I'm so confused, can you give me some clue? Thank you.

**Comment by mourner** [comment] 2022-07-26 17:23
It's very hard to help with cases like this because you there's no minimal reproducible live test case, so we can't determine if this is an issue with your code, the data your loading, etc. So I'd have to close this.

Are there any warnings in the console? Is `value` a properly encoded number in vector tile properties? Maybe worth adding a [to-number](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#types-to-number) to the expression? Not sure.

**Closed by mourner** 2022-07-26 17:23 UTC
