### ISSUE TITLE
Icons along a line behaving strangely at tile boundaries

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#1467] opened 2015-09-08 19:00 UTC
Icons appear to be rendering along some tile boundaries:

![icon-at-tile-boundary](https://cloud.githubusercontent.com/assets/5607844/9744222/8836f184-5638-11e5-81ad-cb5fa2157494.png)

These are the oneway arrows on the published Mapbox Street style. I'm not sure what other information is necessary to debug this. Please let me know if I can provide more info.

**Comment by bhousel** [comment] 2015-09-08 19:24
see #1461, upstream bug..

**Comment by 1ec5** [comment] 2015-09-30 22:26
Duplicate of #1461.

**Closed by 1ec5** 2015-09-30 22:26 UTC
Labels: bug, upstream
