### ISSUE TITLE
Incorrect replaceState using hash param: path stripped from URL in SPA

### ISSUE THREAD

**Issue by Badg** [mapbox/mapbox-gl-js#9917] opened 2020-08-07 07:03 UTC
**mapbox-gl-js version**: 1.11.0

**browser**: firefox

### Steps to Trigger Behavior

 1. Have svelte/sapper app with map on a non-root-path page
 2. set hash to anything other than false
 3. URL path is stripped

### Link to Demonstration

I tried really hard to get a minimal repo in something I could link to but I couldn't :/

### Expected Behavior

Url shows as ``/foo/#bar=<map location>``

### Actual Behavior

Url shows as ``/#bar=<map location>``

-----

First off, apologies about not getting a demoable repro. It always happens in my application, but I couldn't get it to happen outside of it. I tried, but I had to time-box myself at two hours. If you can't repro and want to close, my feelings won't be hurt! But I poked around at the relevant code in hash.js and it seems like someone more familiar with it might spot the issue right-off, so I thought I would report what I ran into. Or maybe some future traveler with the same problem can use this to help them repro. At any rate:

I have a sapper app structured with routes like this:

```
/index.svelte
/map.svelte
```

In the relevant component for the map on the map page, I have this:

```js
    onMount(() => {
        console.log(`window location ${window.location}`);
        let slippyMap = new mapboxgl.Map({
            container: 'map',
            center: center,
            zoom: zoom,
            zoomControl: false,
            style: '/path/to/style.json',
            // workaround to support relative URLs
            transformRequest: (url, resourceType) => {
                return {
                    url: `${window.location.origin}${url}`
                }
            },
            hash: 'mapPosition',
            attribution,
        });
        console.log(`window location ${window.location}`);
    });
```

You can see that I added two extra console logging statements for debugging here. When onMount runs, you can see that it starts with the correct window location, pointing to ``/map``. But after the Map constructor is done, the second log statement gives a window location of the root path: ``/``. So I'm pretty sure somehow mapbox-gl is getting more than just the URL fragment / hash out of Hash.getHashString.

I tried removing the transformRequest. Now (as expected), requests to my local OSM stack fail, but the errant path behavior remains.

I tried both going straight to the relevant page (ie, entering in ``/map`` to my URL bar) and navigating there from the index. Both have the same behavior, so it doesn't appear to be a weird interaction because of some previous use of replaceState or pushState (I also tried both of those on navigation).

I tried ``hash: true`` instead of the custom parameter, and the errant path behavior persisted.

While trying to get my demoable repro, because this needs to be able to play with paths, I couldn't do a jsfiddle/jsbin/etc. I just ran a quick and dirty python ``http.server``. I set up the absolute bare minimum needed to get a map, and then tried various paths: ``/index.html``, ``/foo.html``, ``/bar``, etc. Nothing would repro.

I'm stumped!

**Comment by Badg** [comment] 2020-08-07 07:05
Oh, side note, if someone follows in my footsteps and for some strange reason wants to abuse python's http.server to force html mimetypes for files without an extension, you can do this:

```python
from http.server import SimpleHTTPRequestHandler
from http.server import HTTPServer


class AlwaysHtmlServer(SimpleHTTPRequestHandler):

    def guess_type(self, path):
        return 'text/html'


def run(server_class=HTTPServer, handler_class=AlwaysHtmlServer):
    server_address = ('', 8000)
    httpd = server_class(server_address, handler_class)
    httpd.serve_forever()


if __name__ == '__main__':
    run()
```

**Comment by mourner** [comment] 2020-08-17 11:13
You could play with the code responsible for the hash replacement here (e.g. making a custom build with `console.log`'s spread around):

https://github.com/mapbox/mapbox-gl-js/blob/45242e75447aeb3dc2b61ecf3cdfa622fc4c39bc/src/ui/hash.js#L135-L137

I don't see anything in `hash.js` that could strip the URL incorrectly, and given that you're not able reproduce outside of the app, it seems that the issue is likely not on GL JS side. So I'm closing the issue for now, but if you do get to the bottom of it and it turns out to be something we can fix, I'll reopen it and welcome a PR for it too.

**Closed by mourner** 2020-08-17 11:13 UTC
