### ISSUE TITLE
style-spec in published package cannot run in Node due to missing "use strict"s

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-js#5522] opened 2017-10-25 20:01 UTC
We need to be able to run the style-spec in Node. But `src/style-spec` files fail because they use `let` and `const` without specifying `"use strict"`. Here's a representative error:

```
/home/travis/build/.../node_modules/mapbox-gl/src/style-spec/migrate.js:16
    let migrated = false;
    ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

**Comment by anandthakker** [comment] 2017-10-26 12:52
@davidtheclark We dropped support for node < v6 in https://github.com/mapbox/mapbox-gl-js/commit/cb84e679857eb41edf4fd068261d0c82a663f600.  I believe this requirement isn't necessary in Node v6 and beyond.

**Comment by davidtheclark** [comment] 2017-10-26 15:19
@anandthakker Hm, let's chat about the private module that's running this on Node 4.

When I run in Node 6, though, I get a different SyntaxError: 

```
/home/travis/build/.../node_modules/mapbox-gl/src/style-spec/expression/index.js:15
import type {Type} from './types';
^^^^^^
SyntaxError: Unexpected token import
```

**Comment by jfirebaugh** [comment] 2017-10-26 15:55
This is essentially a duplicate of #5502, right?

**Comment by davidtheclark** [comment] 2017-10-26 15:58
@jfirebaugh: Internally it looked to me like we've been treating `src/style-spec` as a safe fallback when the `@mapbox/mapbox-gl-style-spec` package could not be used. It seems that we can't use *either* right now. But that's separate from the Node 4 issue, which I guess is also internal, so we can chat about that.

**Comment by anandthakker** [comment] 2017-10-26 16:08
Added these requirements into #5502, since it is very likely that we'll be solving them all with the same fix.  Closing here.

**Closed by anandthakker** 2017-10-26 16:08 UTC
