### ISSUE TITLE
High memory usage on mouse enter event in vector tile layer

### ISSUE THREAD

**Issue by vibindhas** [mapbox/mapbox-gl-js#8471] opened 2019-07-12 13:53 UTC
I am loading a route as a vector tile in mapbox and added a mouseenter event to map to load a popup. Whenever I hover the route the browser memory keeps on increasing. If I keep on Zoom in and out hovering the route the browser crashes within 15 sec. If I remove the mouseenter event listener from the map it works perfect.

**mapbox-gl-js version**: In All Versions till 1.0.0 (I am unable to check this in 1.1.0, I am only seeing black screen)

**browser**: Chrome Version 75.0.3770.100

### Steps to Trigger Behavior

 1. Load a route file as vector tile 
 2. Add mouseenter event listener
 3. Load the map and move the mouse over the route to see the popup.
 4. Check the browser tab memory, it keeps on increasing.

### Link to Demonstration

https://drive.google.com/open?id=18xPLDzraogTEsD2yQXCQ1dwfz78q_NBc

### Expected Behavior

The browser memory should have a minor variation and it should increase(on hover) and decrease(on mouse leave)

### Actual Behavior
The Browser memory keeps on increasing and crashes the browser

**Comment by ryanhamley** [comment] 2019-07-12 18:38
@vibindhas thanks for reporting this. are you able to create a minimal reproduction of the setup that's causing this bug? we recommend using sites like JSBin. that would help us out a lot in figuring out what's going on

**Comment by vibindhas** [comment] 2019-07-15 09:51
@ryanhamley Below is the JSBin link

**Comment by ahk** [comment] 2019-08-20 18:55
I don't have a fix for this but I do have some notes:
- This tileset is pretty large uncompressed, eye-balling several of these tiles they appear to be 10x the size of some of our examples and tests that use lines. I believe this is due to the embedding of full HTML documents in the `description` field on features.
- This isn't a regression in GL-JS, it's a side-effect of fancy string implementations within browser engines choosing to create reference-based concatenated strings that retain (rather than copy from) their arguments. These intermediate strings build up in the heap due to our PBF deserialization and essentially we pay for the overhead of millions of intermediate concatenated strings (~1 per UTF8 character in the input strings). There is a loop in `Pbf#readUtf8` that concatenates strings character by character and seems to be the origin of these allocations.
- Memory usage is extremely high for this tileset in Firefox and Chrome. Chrome only crashes because it has a lower threshold for tab memory usage before it chooses to kill a tab. Firefox will go up to 3gb while remaining mostly interactive (and not crash).
- This issue is unrelated to the body of the listeners, and this tileset still uses a considerable amount of memory without the listeners attached at all. The listeners do appear to cause retention of the amount of memory that crashes Chrome tabs (~1.5gb). Current suspicion is that the event listeners (which are targeted to a layer) trigger retention of a larger layer object that retains all these intermediate strings.

I'm working on bisecting this with Chrome (and maybe Firefox) to see if previous versions of the engines show different behavior with strings. Potentially we can invent a workaround that allows for tiles to have large strings embedded with features.

In the meantime can I suggest reworking your tiles to contain just the keys and values you need, and write a small amount of client side JS to construct the Popup HTML contents per mousevent?

**Comment by ahk** [comment] 2019-08-20 22:30
Explaining why listeners trigger this behavior:

`Map#queryRenderedFeatures(...)` is called whenever a mouse or touch listener triggers. PBF data is deserialized lazily, but querying features causes the entire thing to be read. Results of this forced read are stored in the source cache, and because the Map is never GCed (being a root object) neither are the fully read contents of the PBF. With large strings in feature properties we trigger [this PBF bug](https://github.com/mapbox/pbf/issues/106) on read, resulting in the extreme memory use.

**Comment by asheemmamoowala** [comment] 2019-09-10 19:00
No next actions here

**Comment by mourner** [comment] 2019-10-11 15:08
Great news — we found a solution to this that seems to completely eliminate the problem. See https://github.com/mapbox/pbf/pull/109 and https://github.com/mapbox/mapbox-gl-js/pull/8863

**Comment by vibindhas** [comment] 2019-10-11 15:17
Great! When will this be released?

**Comment by mourner** [comment] 2019-10-11 15:22
@vibindhas likely in a beta next Wednesday and final v1.5.0 release the week after that. Meanwhile, you can make a custom build with the PR applied to take advantage.

**Closed** 2019-10-11 19:21 UTC
Labels: performance :zap:
