### ISSUE TITLE
Newest version 0.42.1 has tile rendering issues for Mapbox satellite style

### ISSUE THREAD

**Issue by alaurenz** [mapbox/mapbox-gl-js#5732] opened 2017-11-21 14:41 UTC
**mapbox-gl-js version**: 0.42.1

### Steps to Trigger Behavior

 1. View a satellite map (e.g. https://www.mapbox.com/mapbox-gl-js/example/setstyle/ and select Satellite bubble at the top)
 2. Zoom in and out quickly around the map

The previous release (0.42.0) does not show this behavior.

### Expected Behavior

Should show Satellite images as expected

### Actual Behavior

You end up with jumbled tiles, here is an example:
![screen shot 2017-11-21 at 9 40 38 am](https://user-images.githubusercontent.com/303765/33078260-1f28e98a-cea0-11e7-8ac3-c8a074482562.png)

**Comment by jfirebaugh** [comment] 2017-11-21 14:51
Duplicate of #5713.

**Closed by jfirebaugh** 2017-11-21 14:51 UTC
