### ISSUE TITLE
The labels on the map are standing weirdly 

### ISSUE THREAD

**Issue by relbraun** [mapbox/mapbox-gl-js#9342] opened 2020-02-25 13:20 UTC
![image](https://user-images.githubusercontent.com/6196995/75250834-f5201500-57e1-11ea-8c5c-b27d82f8eee1.png)

This picture has taken from the mapbox example page: 
[https://docs.mapbox.com/mapbox-gl-js/example/add-image/](https://docs.mapbox.com/mapbox-gl-js/example/add-image/)

The same behavior is when I try to develop it on my computer.

PC
Windows 10
Google Chrome | 79.0.3945.130 (Official Build) (64-bit) (cohort: Stable)

**Comment by mourner** [comment] 2020-02-25 13:22
Duplicate of #9327.

**Closed by mourner** 2020-02-25 13:22 UTC
