### ISSUE TITLE
Fix subtle layer flash/flicker when tiles are loading

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2500] opened 2016-04-26 22:33 UTC
I've noticed this behaviour when using layers with large blurry circles to achieve heatmap-like visualizations. It might be that the same thing is happening when not styling like this but then the effect might be subtle enough to go unnoticed.

**mapbox-gl-js version**: 0.17.0 (tested on Chrome, Firefox and Safari)

### Steps to Trigger Behavior

 1. Go to http://firefly.ibk.se/~racer/tile_flash/
 2. Zoom in slowly and notice how the layers give off a flash as new tiles are loaded
 3. When the tiles are cached you can hit reload on the page to repeat the inspection
 4. After reload repeat the procedure but with fast zooming to see the effect even more clearly

If the full screen mode is too demanding just make the browser window a bit smaller, the effect is most evident when zooming is smooth.

### Expected Behavior
No flashing of layers when new tiles are loaded.

### Actual Behavior
Flashing!

**Comment by lucaswoj** [comment] 2016-07-29 21:11
This is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2418

**Closed by lucaswoj** 2016-07-29 21:11 UTC
Labels: bug
