### ISSUE TITLE
Disabling compass in navigation controls ?

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#1929] opened 2016-01-13 22:47 UTC
Is there a way to disable the compass in the navigation controls ? I don't think the addControl() function has an option that does this.

**Comment by bhousel** [comment] 2016-01-14 14:12
related #1554 
We are planning to make it possible to enable/disable the different navigation controls.

**Comment by roblav96** [comment] 2016-01-16 00:15
I've been able to resize the control elements like so:
```
.mapboxgl-ctrl-group {
    height: 90pt;
    width: 30pt;
    margin: 0 10pt 20pt 0 !important;
}

.mapboxgl-ctrl-group > .mapboxgl-ctrl-icon {
    width: 30pt;
    height: 30pt;
}

.mapboxgl-ctrl-group > .mapboxgl-ctrl-icon > .arrow {
    width: 25pt !important;
    height: 25pt !important;
}
```

If you change the height on the ctrl-group you can hide the compass.

**Comment by uhuru-be** [comment] 2016-01-16 00:42
Thanks ; I will do it that way for now... but an extra option to the mapboxgl.Navigation() function would be desirable.

**Comment by diogofigueiredo** [comment] 2016-01-26 16:45
i use this on the JS:
map.addControl(new mapboxgl.Navigation({position:'top-left' }));
// Disable map rotation using right click + drag
map.dragRotate.disable();

// Disable map rotation using touch rotation gesture
map.touchZoomRotate.disableRotation();

and on the CSS:
.mapboxgl-ctrl-compass {
	display: none !important; 
}

**Comment by lucaswoj** [comment] 2016-07-29 14:50
Duplicate of #1554

**Closed by lucaswoj** 2016-07-29 14:50 UTC

**Comment by feerglas** [comment] 2017-08-17 06:40
The solution from @diogofigueiredo works well. But a have a little note on the css part. We try to not use "!important" whenever possible. In this case, it is just a matter of the specificity of the selector. If you use the following selector, the "!important" statement is not necessary: 

.mapboxgl-ctrl-group .mapboxgl-ctrl-compass {
	display: none;
}

**Comment by casssapir** [comment] 2018-02-27 14:59
Hi all, wanted to share that this is now possible with the [NavigationControl option](https://www.mapbox.com/mapbox-gl-js/api/#navigationcontrol) `showCompass: false`.

Here's an example:
```javascript
// Add zoom and rotation controls to the map.
map.addControl(new mapboxgl.NavigationControl({
    // Hide rotation control.
    showCompass: false
}), 'bottom-right');
```
