### ISSUE TITLE
Ability to refetch tiles given a feature id

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#3715] opened 2016-11-29 19:45 UTC
I would like to add a vector tile source and a style layer to a map, then manually refetch tiles for that layer containing features of certain ids.

The reason I need this is that my app enables the user to post changes to the backend that update the data for future tile requests. It would be nice if I didn't have to remove/reapply the source and layer to do this.

I'm picturing something like this:

```js
map.on('load', function() {
  map.addSource('city_data_source', {
    type: 'vector',
    url: 'http://mytileservice.com/{z}/{x}/{y}'
  });
  
  map.addLayer({
    id: 'city_data_layer',
    type: 'fill',
    source: 'city_data_source',
    'source-layer': 'city_data',
    paint: {
      'fill-color': {
         property: 'building_type',
         type: 'categorical',
         stops: [
           ['House', '#FF0'],
           ['Store', '#F00'], 
         ],
      }
    }
  });
});

map.on('render', function() {
  if (map.loaded()) {
    /**
     * Post a request to the server that will
     * change the data for future tile requests.
     * 
     * For example, painting a feature from House to Store
     * might update other data in the backend about the feature,
     * such as energy_usage, num_employees, etc.. 
     */
    post('/api/paint', { featureId: 1, building_type: 'Store' })
      .then(function() {
        /**
         * One way to update the map now is to remove the source and layer,
         * then reapply them. This seems heavy-handed.
         * 
         * Instead, is it possible to refetch the tile(s) that contain our 
         * feature of ID 1? Is something like this possible?
         */
         const affectedTiles = findTilesByFeatureId(map, 1);
         map.reloadTiles(affectedTiles);
      });
  }
});
```

It looks like something similar can be done with GeoJSON layers in the [Add live realtime data](https://www.mapbox.com/mapbox-gl-js/example/live-geojson/) example. What about for vector tiles?

**Comment by lucaswoj** [comment] 2016-11-30 18:27
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2633

**Closed by lucaswoj** 2016-11-30 18:27 UTC
Labels: enhancement
