### ISSUE TITLE
Fix memory leak caused by "GeoJSONSource#setData"

### ISSUE THREAD

**Issue by Pipoupi** [mapbox/mapbox-gl-js#2607] opened 2016-05-23 09:00 UTC
**mapbox-gl-js version**: 0.18.0

### Steps to Trigger Behavior

 1. Go to https://afternoon-refuge-60269.herokuapp.com/
 2. Open a task manager (on Chrome : maj+esc) : App is ~ 430mb
 3. Hit refresh data button, App is ~630mb

### Expected Behavior
Memory should stay around 430mb (I guess? At least that's what is done with a smaller geojson)

### Actual Behavior
Memory increases every time `map.getSource('earthquakes').setData(data);` is called (same with removeSource and _updateSource), application crashes after 3-4 refresh, depends on the ram available.

**Comment by nrathi** [comment] 2016-06-09 19:19
This is happening to me, too.

**Comment by lucaswoj** [comment] 2016-07-29 21:22
Duplicate of #2266

**Comment by wandergis** [comment] 2016-08-27 05:46
I also have this problem, and my chrome will crash when run setData() several times.

**Comment by Pipoupi** [comment] 2016-09-13 07:46
Hi, just an update 

It seems that the memory leak thing is only happening on Google Chrome. Everything works fine on FF

**Comment by polokobe** [comment] 2016-09-13 12:53
@Pipoupi  HI, I doubt the reason which caused the memory leak is the difference between chrome and FF. Is it fine to explain the reason in detail? And, chrome has been used widely, may fix it recently?

**Comment by mourner** [comment] 2016-09-13 13:19
I just profiled memory on the test page provided by @Pipoupi — the worker that retains the data doesn't change its retained memory size after a "refresh"; same for the main thread:

![image](https://cloud.githubusercontent.com/assets/25395/18475040/9726336c-79cd-11e6-84e6-9b336664c2d3.png)

Combined with the hint above, I'm concluding that this must be a Chrome bug, not an issue with Mapbox GL JS code. 

Until it's fixed, I'd recommend avoiding `setData` on such huge amounts of data, and loading GeoJSON by URL whenever possible. Closing as not actionable.

**Closed by mourner** 2016-09-13 13:19 UTC
Labels: performance

**Comment by wandergis** [comment] 2016-09-13 16:30
# As it below( with Firefox)
### before
![image](https://cloud.githubusercontent.com/assets/5799374/18482204/cb1a37f6-7a11-11e6-849b-51b2bd949cd5.png)
### after `setData` four times
![image](https://cloud.githubusercontent.com/assets/5799374/18482279/16ec3378-7a12-11e6-81e8-1d11d807c176.png)

**Comment by mourner** [comment] 2016-09-13 16:44
@wandergis can you confirm this with DevTools memory profiler?

**Comment by wandergis** [comment] 2016-09-13 16:54
Memory profiler is in right way. But acturely the Firefox's memory increase so much, i don't know why.
![image](https://cloud.githubusercontent.com/assets/5799374/18483105/63606410-7a15-11e6-8134-0f2ea0f3c616.png)

**Comment by mourner** [comment] 2016-09-13 16:56
@wandergis most memory should be retained in one of the worker threads, is the screenshot for such a worker or for the main thread?

**Comment by wandergis** [comment] 2016-09-13 17:01
I'm sorry, i don't know which one is the screenshot for. I just open my FF's Devtools,and click the screenshot button.
![image](https://cloud.githubusercontent.com/assets/5799374/18483431/8e6b12bc-7a16-11e6-99f0-e0101c52b912.png)

**Comment by wandergis** [comment] 2016-09-13 17:05
The test case is http://wandergis.com/memory-leak-test-case/ ,you can profiled memory on the  test page.

**Comment by x9xjdzz9** [comment] 2016-10-18 15:52
This bug is a major problem for me also. If this is indeed a Chrome & Firefox bug, has a bug report been opened with Chrome or Firefox?

**Comment by x9xjdzz9** [comment] 2016-10-21 20:05
If the problem is that the workers do not release their memory in both Firefox and Chrome, would it be possible to terminate workers to guarantee that they release their resources?

**Comment by wandergis** [comment] 2017-01-11 08:22
https://www.mapbox.com/bites/00318/  This demo also have a memory leak problem.

**Comment by justinlewis** [comment] 2017-02-01 22:32
I'm looking for some clarification?  

@mourner mentioned this above - 

> Until it's fixed, I'd recommend avoiding setData on such huge amounts of data, and loading GeoJSON by URL whenever possible. Closing as not actionable.

This appears to be an issue with my team as well using Mapbox-gl 0.29 when adding plain GeoJSON featureCollections to setData().  If we change our back-end to provide URL's for our data rather than GeoJSON can I expect this to avoid the memory leak issue?  I can take this to StackExchange but I'm guessing no one knows about this issue more than the people on this ticket.

**Comment by mourner** [comment] 2017-02-01 23:18
@justinlewis I'm not sure, can you try the latest version to make sure it's still an issue?

**Comment by justinlewis** [comment] 2017-02-01 23:55
Thanks for getting back to me.  I tried the 0.32.1 version with the same memory leak issue when using plain GeoJSON.

**Comment by x9xjdzz9** [comment] 2017-02-02 14:33
I moved most of my data to vector tiles, but it seemed like the remaining memory problems went away with 0.29.0. I guess if you're still having a leak, that was wishful thinking on my part. At the time I was dealing with this issue, loading GeoJson with a URL did not help.

**Comment by jfirebaugh** [comment] 2017-02-02 16:17
> This happens even when loading only 2 polygons and then letting the page sit idle. After about 6 - 10 minutes of sitting idle the page tends to crash.

Can you please open a fresh issue, and include a self-contained demo that shows this issue?

**Comment by justinlewis** [comment] 2017-02-02 17:07
Ok. I'll try to reproduce this outside of our platform.  Thanks for responding!

**Comment by x9xjdzz9** [comment] 2017-02-02 17:44
@justinlewis Yes, you understood me correctly.
