### ISSUE TITLE
"CONTEXT_LOST_WEBGL: loseContext: context lost" on iPad Air 2

### ISSUE THREAD

**Issue by kk12837** [mapbox/mapbox-gl-js#9903] opened 2020-07-29 08:40 UTC
**mapbox-gl-js version**: 1.11.1

**browser**: safari (ipad air 2 , ios 14 beta 3) - not working
                     safari (ipad prod, ios 14 beta 3) - working

### Steps to Trigger Behavior

 1. just go to https://dev.hkep.com/chistdev/demo?dynasty=tong&access_token=WGx2ekhSNkdWa3c2MkREVW04djIzb2M1MG01Z0lCb1YveFEvb2VXb2w0bjBpQXdsNk1HbFdBdjVOVkpzWWE1bA%3D%3D

### Link to Demonstration

https://dev.hkep.com/chistdev/demo?dynasty=tong&access_token=WGx2ekhSNkdWa3c2MkREVW04djIzb2M1MG01Z0lCb1YveFEvb2VXb2w0bjBpQXdsNk1HbFdBdjVOVkpzWWE1bA%3D%3D

### Expected Behavior

show normal map

### Actual Behavior

blank page with js error - CONTEXT_LOST_WEBGL: loseContext: context lost

**Comment by ryanhamley** [comment] 2020-07-29 15:06
I can't open your link but in either case, this is a duplicate of #9691 even though the environment is different. Let's keep the discussion focused in the original ticket.

**Closed by ryanhamley** 2020-07-29 15:06 UTC

**Comment by kk12837** [comment] 2020-08-26 04:54
how about this one, https://dev.hkep.com/mpms3/api/link/cm1demo?access_token=WGx2ekhSNkdWa3c2MkREVW04djIzb2M1MG01Z0lCb1YveFEvb2VXb2w0bjBpQXdsNk1HbFdBdjVOVkpzWWE1bA==
