### ISSUE TITLE
Bug: custom markers lose exact position after moving map

### ISSUE THREAD

**Issue by ivanakimov** [mapbox/mapbox-gl-js#5151] opened 2017-08-16 06:15 UTC
**mapbox-gl-js version**: `0.39.1`

### Steps to Trigger Behavior

1. Visit <https://codepen.io/anon/pen/JyOvRN> in latest FF or Chrome.
2. You'll see 2 markers. Click on one of the markers.
3. Move the map.
4. Select another marker. Move the map again.

### Expected Behavior

The markers don't lose the coordinates to which they're anchored.

### Actual Behavior

The markers move a little bit and don't point to the original position.

### Notes

This does not happen on `v0.34.0`.

**Comment by jfirebaugh** [comment] 2017-08-16 16:22
Duplicate of #5133.

**Closed by jfirebaugh** 2017-08-16 16:22 UTC

**Comment by ivanakimov** [comment] 2017-08-19 17:33
@jfirebaugh I am not sure what your suggestion is -- is it to set `transform: translate(-50%, -50%);` on the marker `<div>` itself? Because `mapboxgl` applies its own calculations as the map moves:

![sn](https://user-images.githubusercontent.com/1404596/29488927-b1d0909c-84c9-11e7-8cf6-5f561150e881.png)

Could you maybe show the fix on the codepen above?

**Comment by jfirebaugh** [comment] 2017-08-19 17:52
It's a duplicate of a bug that was already reported -- #5133 -- and has been fixed for the next release. If you need the fix immediately and are prepared to build Mapbox GL JS from source, it's in #5139.

**Comment by ivanakimov** [comment] 2017-08-19 17:55
@jfirebaugh Ahhh, got ya! I totally missed that it's fixed for the upcoming release. Thank you for the quick reply.
