### ISSUE TITLE
1.1.0 release tile load tiems performs poorly compared to 0.54 

### ISSUE THREAD

**Issue by arthur-clifford** [mapbox/mapbox-gl-js#8431] opened 2019-07-05 08:46 UTC
I had been using the v0.54 release and have a version of a map I'd been deving here:
https://app-dev.simplelayers.com/~staging/apps/public/simple_map/8406

The same map using 1.1.0
https://app-dev.simplelayers.com/~art/apps/public/simple_map/8406

I know you prefer a simple example, but hopefully the same complex environment with minor differences can show the performance hit.

I know you are switching up the token scheme in the new version so I don't know if there is added latency in that process or what, but the performance difference is uncomfortably noticable.

**mapbox-gl-js version**:
0.54. vs. 1.1.0
**browser**:
I have been testing in Chrome on Windows 10
### Steps to Trigger Behavior
It really shows if you pitch and rotate the map so new tiles have to load. The 0.54 link will render them zippily but the 1.1.0 will take what seem-like a second per new tile.

 1. Load the map you'll see the roads+sat map and then a image with different polygons will appear
 2. Right-click pitch and rotate the map
Note the speed at which tiles fill in the view.

Do that for both links provided and note the performance difference.
The 1.1.0 performance is non-viable., the .54 performance was excellent.

**Comment by mourner** [comment] 2019-07-05 10:29
Since you haven't provided any details and didn't fill the issue template, we have to close this without consideration.

**Comment by arthur-clifford** [comment] 2019-07-05 11:18
Sorry, had left a comment tag at beginning of my original post

**Comment by mourner** [comment] 2019-07-05 11:35
Thanks, now I see the issue. The first link is v1.0.0 though, not v0.54.0. This is likely caused by #8363, where the overhead isn't noticeable much with vector tiles, but becomes pronounced with the much smaller satellite tiles and pitched views.

**Comment by mourner** [comment] 2019-07-05 12:40
Upon further investigation, this appears to be a [known issue in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=682677) — `cache.match` has abysmal performance (`O(n)` where `n` is the number of stored items) if you use `ignoreSearch: true`.

I'll see if I can hack around this... cc @asheemmamoowala

**Comment by mourner** [comment] 2019-07-05 13:00
@arthur-clifford I've put a quick fix for this in #8434 — can you help test it out? And thanks again for the report — great that we caught such an issue relatively early!

**Comment by arthur-clifford** [comment] 2019-07-06 03:09
Vladimir, I’ve updated the link with ~art which should be using mapbox-gl.js  built from your branch.

 

It is much improved.

 

You can still try the two links and determine if any performance differences are within tolerance. 

 

The performance hit didn’t seem like something in attunement to what the mapbox team tends to produce so I figured it was good to bring it to your attention.

 

Thanks for jumping on the issue, hopefully we can get it out to a release soon so I/we can do a proper npm update.

 

Let me know if you need anything else,

 

Art

**Closed** 2019-07-09 17:17 UTC
Labels: performance :zap:, release blocker :no_entry:

**Comment by cCTwc** [comment] 2019-09-05 18:28
I just updated to the mapbox-gl 1.3.0 build.  Now seeing an error in 'tile_request_cache.js'/ 'mapbox-gl-dev.js'
Uncaught (in promise) TypeError: Cannot read property 'match' of undefined
    at 2e1a17fd-2a06-4b23-a416-93130fa7a9e9:3069

The callback value 'cache' is coming in as undefined from 'window.caches.open(CACHE_NAME)...

what am i missing???

**Comment by mourner** [comment] 2019-09-05 20:08
@cCTwc can you set up a minimal reproducible test case on JSFiddle?
