### ISSUE TITLE
Click on cluster points to get all contained points properties

### ISSUE THREAD

**Issue by TZTony** [mapbox/mapbox-gl-js#2661] opened 2016-06-03 00:37 UTC
**mapbox-gl-js version**:0.18.0

### Steps to Trigger Behavior
Hi 
I am new to mapboxgl, I have a question about how I can get all points belong to a certain cluster point?  based on the example, I am able to generate a cluster markers and when mouse click on cluster circle, using following code only be able to get total points. so it will be good to have a properties with a array of points in the resource.

```javascript
var features = mapBox.queryRenderedFeatures(e.point, { layers: ['cluster'] });
if (!features.length) {
 return;
}			    
var feature = features[0];
var totalNum = feature['point_count'];
```
### Expected Behavior
I hope it can return value from geoJsonSource list this.
```javascript
{
   cluster : 1,
   point_count : integer,
   point_count_abbreviated : integer,
   **points_properties : included points properties array,**
}
```
Or if there is another solution can solve my problem, it will be great

Thanks

**Comment by karlguillotte** [comment] 2016-06-09 00:13
Looking for a similar *Expected Behavior*. I need those points to compute bounds that I will use to call `fitBounds` on my map object.

**Comment by karlguillotte** [comment] 2016-06-09 00:20
#2385

**Comment by lucaswoj** [comment] 2016-06-09 16:11
This issue is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2358. Sorry! This functionality would be nice but it is not practical.

**Closed by lucaswoj** 2016-06-09 16:11 UTC

**Comment by TZTony** [comment] 2016-06-16 03:55
I understand the way for store all those points in cluster point's properties is ambition. But I wonder is there another way to get those points by a method or calculation from the source. I can see the index process is using kdbush, but i don't know is it possible to generate those points again when click on a cluster point.

**Comment by barrylachapelle** [comment] 2017-04-17 19:39
https://jsfiddle.net/aznkw784/

**Comment by schellenbergk** [comment] 2020-01-20 22:13
bump!
