### ISSUE TITLE
mapbox-gl-js crashes on ipad

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/mapbox-gl-js#1308] opened 2015-06-23 07:46 UTC
mapbox-gl-js (https://github.com/mapbox/mapbox-gl-js/commit/001c7b9a91bfa58e798cfd5bb26b1904aec8d969) crashes on both safari and chrome on ipad

![mov3](https://cloud.githubusercontent.com/assets/533564/8301157/05bc3f9a-19a5-11e5-922f-beff533c7f3a.gif)

```javascript
var map = new mapboxgl.Map({
  container: 'map',
  style: '/data/mapbox-streets-v7.json',
  center: [43.116667, 131.9],
  zoom: 8
})

mapboxgl.util.getJSON('/data/10000-points.geojson', function(error, data) {
  if (error) throw error

  var points = new mapboxgl.GeoJSONSource({'data': data})

  map.addSource('points', points)
  map.addLayer({
    'id': 'points',
    'source': 'points',
    'type': 'symbol',
    "layout": {
      "icon-image": "default_marker",
    }
  })
})
```

iPad MD793RU/A, iOS 8.3

**Comment by mourner** [comment] 2015-06-23 08:05
Can you try doing the same but passing the url in the GeoJSONSource constructor rather than the data itself?

**Comment by StepanKuzmin** [comment] 2015-06-23 08:12
I changed code like that

```javascript
var map = window.map = new mapboxgl.Map({
  container: 'map',
  style: '/data/mapbox-streets-v7.json',
  center: [43.116667, 131.9],
  zoom: 8
})

var points = new mapboxgl.GeoJSONSource({'data': '/data/10000-points.geojson'})
map.addSource('points', points)
map.addLayer({
  'id': 'points',
  'source': 'points',
  'type': 'symbol',
  "layout": {
    "icon-image": "default_marker",
  }
})
```

And now I'm getting this error `Uncaught TypeError: Cannot read property 'constants' of undefined`, that occures here https://github.com/mapbox/mapbox-gl-js/blob/fd338a13cd8d1dfcb4f15e3f315e7c3c823d11fd/js/style/style.js#L289

**Comment by StepanKuzmin** [comment] 2015-06-23 08:54
I've set delay for adding layer, and now layer displays correctly. But issue with crashing is still there.

![mov4](https://cloud.githubusercontent.com/assets/533564/8302340/211054c0-19af-11e5-8e7c-edeb09742db8.gif)

My code looks like this now:
```javascript
var map = new mapboxgl.Map({
  container: 'map',
  style: '/data/mapbox-streets-v7.json',
  center: [43.116667, 131.9],
  zoom: 8
})

var points = new mapboxgl.GeoJSONSource({'data': '/data/10000-points.geojson'})
map.addSource('points', points)
setTimeout(function() {
  map.addLayer({
    'id': 'points',
    'source': 'points',
    'type': 'symbol',
    "layout": {
      "icon-image": "secondary_marker",
    }
  })}, 10000)
```

Btw, @mourner, I've 10 000 point, and it is GeoJSON Source, so maybe it can be geojson-vt issue?

**Comment by mourner** [comment] 2015-06-23 09:13
Not sure, — the crash needs further investigation. Can you try reproducing the same kind of load purely with geojson-vt and see if it crashes? Also, did you try other platforms? Does it crash on iPhone, Android, Desktop machine?

The error you had is because you need to add a GeoJSONSource after style has loaded — you can see this on the GeoJSON example code.

**Comment by AbrahamArun** [comment] 2015-07-13 10:03
Even I am facing when I started doing it in the React way. 

``` javascript
React.createClass({
  
  componentDidMount: function(){
    
    mapboxgl.accessToken = this.props.accessToken;
    var map = new mapboxgl.Map({
      container: 'map',
      style: this.props.mapStyle,
      center: [45.49967092406,-73.57636285993],
      zoom: 22,
      interactive: true
    });
  
    map = map.addSource(this.source.id, this.source.sourceObj);

    var fillLayer = {
      "id": "layer-style",
      "type": "fill",
      "source": this.source.id,
      "layout": {
        "line-join": "round",
        "line-cap": "round"
      },
      "paint": {
        "fill-color": "#888"
      },
      "interactive" : "true"  
    }
    map.addLayer(fillLayer);
  },

  render: function(){

    var self = this;

    return (
        <div id='map' ref='map'></div>```
    );
  }

});
```

Adding style needs a delay for some reason (timeout). Else I get an error '<b>Uncaught TypeError: Cannot read property 'constants' of undefined</b>'

**Comment by AbrahamArun** [comment] 2015-07-14 09:04
@StepanKuzmin Your issue should be resolved by adding source layers and styles in 'load' callback, like this.
``` javascript
    map.on('load', function(){
        // Do everything here
    });    
```
Worked for me.

**Comment by jfirebaugh** [comment] 2015-08-12 00:02
@StepanKuzmin Does the above resolve your issue? If not, can you create a self-contained JSFiddle that demonstrates the issue?

**Closed** 2015-09-18 21:12 UTC
Labels: needs more info
