### ISSUE TITLE
overlapping polygons with opacity going funky on pitch

### ISSUE THREAD

**Issue by juliangums** [mapbox/mapbox-gl-js#4944] opened 2017-07-06 14:44 UTC
![screenshot from 2017-07-06 15-37-54](https://user-images.githubusercontent.com/22907521/27916759-f8d8d092-6261-11e7-8e66-d29b69dae0f2.png)

**Comment by lbud** [comment] 2017-07-06 18:27
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/3320.

**Closed by lbud** 2017-07-06 18:27 UTC
