### ISSUE TITLE
Street labels not rendering when default zoom level is between 5 and 16

### ISSUE THREAD

**Issue by chasenicholl** [mapbox/mapbox-gl-js#4674] opened 2017-05-03 18:19 UTC
**v0.37.0**:

### Steps to Trigger Behavior

EDIT: Bug appears to be Safari specific. I am using Safari 10.0.3.

Use basic example. https://www.mapbox.com/mapbox-gl-js/example/custom-style-id/

 1. Change `zoom` property to any number between 5,16. Street labels do not render using dark-v9 or light-v9

### Expected Behavior
I'd expect street labels to render at any zoom level.

### Actual Behavior
Street labels do not render using dark-v9 or light-v9 when default, starting zoom level is between 5 and 16.

**Comment by jfirebaugh** [comment] 2017-05-03 18:27
Duplicate of #4607.

**Closed by jfirebaugh** 2017-05-03 18:27 UTC
