### ISSUE TITLE
Map screenshot from another tab gives me a blank image

### ISSUE THREAD

**Issue by dimitrilahaye** [mapbox/mapbox-gl-js#8991] opened 2019-11-19 09:19 UTC
**mapbox-gl-js version**: 0.54.0

### Question
I think it is a problem with WebGL but I would need your opinion.
On my current project, I have an asynchronous task which initialize a map with settings from backend, in order to generate an image file from map's container.
The issue happens during the process, if the user navigate into another tab in his browser, the generated final image is blank.
In order to have a right screenshot, he needs to let the application's tab active.

Have you ever faced this kind of problem?

**Comment by mourner** [comment] 2019-11-19 14:28
Unfortunately I don't recall any issues like this. Do you use `preserveDrawingBuffer: true` in Map options? Anyway, let's close this as something we don't have control over with GL JS.

**Closed by mourner** 2019-11-19 14:28 UTC

**Comment by ryanhamley** [comment] 2019-11-19 19:35
This sort of thing has come up before. See https://github.com/mapbox/mapbox-gl-js/issues/7721 for some potential solutions

**Comment by anurasin** [comment] 2020-01-21 16:58
Any update on this thread: The issue is still coming for "puppeteer": "^2.0.0".
With headless mode, on taking the screenshot of a canvas element it's getting the blank output, but on running the same code with headlfull mode it's working just fine.
