### ISSUE TITLE
mapboxgl not defined after dynamically loading

### ISSUE THREAD

**Issue by seccode** [mapbox/mapbox-gl-js#9987] opened 2020-09-18 01:43 UTC
**mapbox-gl-js version**: v1.12.0

**browser**: Google Chrome

### Steps to Trigger Behavior
```
var script = document.createElement("script");                                                           
script.type = "text/javascript";                                                                         
script.src = "https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js";                                 
script.onload = function() {                                                                             
  console.log(mapboxgl);                                                                                 
}                                                                                                        
document.head.appendChild(script);
```

### Expected Behavior
```
{version: "1.12.0", supported: ƒ, setRTLTextPlugin: ƒ, getRTLTextPluginStatus: ƒ, Map: ƒ, …}
```
### Actual Behavior
```
resourceLoader.js:5 Uncaught ReferenceError: mapboxgl is not defined
    at HTMLScriptElement.script.onload (resourceLoader.js:5)
```

**Comment by ryanhamley** [comment] 2020-09-18 18:26
This seems to work fine when I try it. Best practice is generally to set `src` after you set `onload` so you could try that if you continue experiencing an issue. This is a general Javascript issue though and not a bug in the library, so I'm going to close this issue. If you need further help, please contact [Mapbox Support](http://support.mapbox.com/).

**Closed by ryanhamley** 2020-09-18 18:26 UTC
