### ISSUE TITLE
Weird font problem

### ISSUE THREAD

**Issue by cie** [mapbox/mapbox-gl-js#3213] opened 2016-09-19 07:40 UTC
Hello,

**mapbox-gl-js version**: v0.23.0

### Minimal test case

Random. Do you have any ideas what I could do to help diagnose it? 

### Expected behavior

http://jsbin.com/hukuwasaga/1/edit?html,js,output
![image](https://cloud.githubusercontent.com/assets/243342/18625151/e61b2be8-7e4c-11e6-8457-8c9f938db789.png) ![image](https://cloud.githubusercontent.com/assets/243342/18625128/ce53888e-7e4c-11e6-9c08-ea269a0b8f6d.png) 

### Actual behavior

Sometimes, after somewhat event in my app (I don't know what), all titles get messed up:
![image](https://cloud.githubusercontent.com/assets/243342/18624551/e66ae31c-7e48-11e6-8039-593f580f278f.png)

and icons are also rendered incorrectly:

![image](https://cloud.githubusercontent.com/assets/243342/18624589/3f6db26e-7e49-11e6-81fa-a50b1c0d155b.png)

A page reload then solves the problem.

Any ideas? Thanks!

**Comment by rsc-rchristensen** [comment] 2016-09-19 13:18
I am also seeing the same issue with 0.23.0
Initially looks like this:
![mapbox_expected](https://cloud.githubusercontent.com/assets/22243653/18633342/d93a523a-7e49-11e6-81ec-f1157148739d.png)

Navigating to another ember screen, then coming back the map then looks like this:
![mapbox_font_error](https://cloud.githubusercontent.com/assets/22243653/18633299/9d926b46-7e49-11e6-9007-52756eec62b2.png)

In order to fix I have to restart my ember electron application.  I don't see any console logs about missing resources or 404 errors or anything.  The maps do render correctly the first time all the time.

**Comment by jfirebaugh** [comment] 2016-09-19 16:29
Duplicate of #3086.

**Closed by jfirebaugh** 2016-09-19 16:29 UTC

**Comment by cie** [comment] 2016-09-19 19:16
Thanks!
