### ISSUE TITLE
Style.js function addLayer()  is there any problem ? 

### ISSUE THREAD

**Issue by Niumeng1** [mapbox/mapbox-gl-js#7489] opened 2018-10-26 08:59 UTC
Hi,all.
**mapbox-gl-js version**:0.50.0

**browser**:chrome 70.0.3538.67

### Steps to Trigger Behavior

 1. When I quote the mapboxgl version: 0.20.0, it is my expected behavior.
 2.When I quote the mapboxgl version: 0.50.0, it is my Actual behavior.
 3.to f12 ,find Style.js addLayer,the method has changed.
 4.If the loading on the same layer, why not go to the cache, but re request.

### Link to Demonstration

![image](https://user-images.githubusercontent.com/21193895/47555891-945ba080-d93f-11e8-8d85-c7d6e155e8f2.png)

> 

    <style>
        body {
            margin: 0;
            padding: 0;
        }

        #map {
            position: absolute;
            top: 0;
            bottom: 0;
            width: 100%;
        }

        #remover {
            margin: 0 auto;
            background-color: #fb5b3f;
            color: #fff;
            font-weight: bold;
            padding: 0.5em;
            border: 2px solid #fff;
            border-radius: 0.5em;
            box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
            cursor: pointer;
            position: absolute;
            left: 0.7em;
            top: 11em;
        }

        #remover:hover {
            background-color: salmon;
        }

        #remover1 {
            margin: 0 auto;
            background-color: #fb5b3f;
            color: #fff;
            font-weight: bold;
            padding: 0.5em;
            border: 2px solid #fff;
            border-radius: 0.5em;
            box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);
            cursor: pointer;
            position: absolute;
            left: 0.7em;
            top: 14em;
        }

        #remover1:hover {
            background-color: salmon;
        }
    </style>
</head>

<body>

    <div id='map'></div>
    <div id='remover'>Add satellite</div>
    <div id='remover1'>Add traffic</div>
    <script>
        mapboxgl.accessToken =
            'pk.eyJ1IjoiZGFuc3dpY2siLCJhIjoiY2l1dTUzcmgxMDJ0djJ0b2VhY2sxNXBiMyJ9.25Qs4HNEkHubd4_Awbd8Og';
        var map = new mapboxgl.Map({
            container: 'map', // container id
            style: 'mapbox://styles/danswick/cilnegnzr00439gkf7urxz0xk', //stylesheet location
            center: [-80.39388527107522, 25.153111227331067], // starting position
            zoom: 6.5 // starting zoom
        });

        map.on('load', function () {
            removeA("mapbox-mapbox-satellite");
            var switchy = document.getElementById('remover');
            switchy.addEventListener("click", function () {
                switchy = document.getElementById('remover');
                if (switchy.className === 'on') {
                    switchy.setAttribute('class', 'off');
                    removeA("mapbox-mapbox-satellite")
                    map.setLayoutProperty('mapbox-mapbox-satellite', 'visibility', 'none');
                    switchy.innerHTML = 'Add satellite';
                } else {
                    switchy.setAttribute('class', 'on');
                    if (switchy1.className == 'on') {
                        addA("state-label")
                    } else {
                        addA("");
                    }

                    map.setLayoutProperty('mapbox-mapbox-satellite', 'visibility', 'visible');
                    switchy.innerHTML = 'Remove satellite';
                }
            });
            var switchy1 = document.getElementById('remover1');
            switchy1.addEventListener("click", function () {
                switchy1 = document.getElementById('remover1');
                if (switchy1.className === 'on') {
                    switchy1.setAttribute('class', 'off');
                    removeA("mapbox-mapbox-satellite");
                    addA("");
                    switchy1.innerHTML = 'Add traffic';
                } else {
                    switchy1.setAttribute('class', 'on');
                    removeA("mapbox-mapbox-satellite");
                    addA("state-label")

                    switchy1.innerHTML = 'Remove traffic';
                }
            });
        });

        function removeA(layerID) {
            if (map.getLayer(layerID)) {
                map.removeLayer(layerID);
            }
        }

        function addA(beforeLayer) {
            map.addLayer({
                "type": "raster",
                "paint": {},
                "layout": {
                    "visibility": "visible"
                },
                "id": "mapbox-mapbox-satellite",
                "source": "mapbox://mapbox.satellite",
                "interactive": true,
                "metadata": {}
            }, beforeLayer)
        }
    </script>

</body>

</html>

### Expected Behavior
![expected](https://user-images.githubusercontent.com/21193895/47555647-eea83180-d93e-11e8-99a2-08f760107180.gif)

### Actual Behavior
![actual](https://user-images.githubusercontent.com/21193895/47555481-80fc0580-d93e-11e8-85a5-6fd374d74fd8.gif)

thanks.

**Comment by Niumeng1** [comment] 2018-10-26 10:13
[https://jsfiddle.net/snowflake1/Lgdm9bq2/](url)

**Comment by Niumeng1** [comment] 2018-10-26 10:13
Demo
[https://jsfiddle.net/snowflake1/Lgdm9bq2/](url)

**Comment by ryanhamley** [comment] 2018-10-26 18:15
I believe this is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/7459. I'm going to close this to concentrate discussion there.

**Closed by ryanhamley** 2018-10-26 18:15 UTC

**Comment by Niumeng1** [comment] 2018-10-27 02:39
thanks

**Comment by Niumeng1** [comment] 2018-10-27 02:40
thanks. @ryanhamley
