### ISSUE TITLE
Add GeoBuf support for GeoJSONSource#setData()

### ISSUE THREAD

**Issue by DaZzz** [mapbox/mapbox-gl-js#2289] opened 2016-03-18 13:33 UTC
**mapbox-gl-js v0.15.0**:

I have a 90k of lines in my GeoJSON and I have a server which encodes it in GeoBuf which results in 1.6 Mb, if I used GeoJSON it would be 14Mb. Now I decode my GeoBuf to JS object and set it using `GeoJSONSource#setData()` which blocks my UI for ~4s.

As I understand, the fastest way for me to render this stuff is if `GeoJSONSource#setData()` with provided URL could support GeoBuf data. Which would be blazingly fast, wouldn't it?

**Comment by mourner** [comment] 2016-03-18 13:39
If you specify GeoJSON as a url, it will be loaded off the main thread, not blocking anything. Since any browser can accept gzipped resources, loading times shouldn't be a big problem if it's just 14Mb gzipped.

Geobuf support may be introduced at some point, but for now, I'll close this as duplicate of #1504.

**Closed by mourner** 2016-03-18 13:39 UTC
Labels: duplicate
