### ISSUE TITLE
Case expression throws error

### ISSUE THREAD

**Issue by jaapster** [mapbox/mapbox-gl-js#5962] opened 2018-01-08 11:14 UTC
In a layer style we have the following expression:

`{
    id: 'testLine',
    type: 'line',
    source: 'testSource',
    paint: {
      'line-color': 'red',
      'line-width': [
      	'case',
        ['==', ['string', ['get', 'foo']], 'a'], 1,
        ['==', ['string', ['get', 'foo']], 'b'], 2,
        3
      ]
    }
  }`

This worked fine in version 0.42.2 but breaks in 0.43.0.

In the console this error is shown: Uncaught Error: can't serialize object of type function

I would expect this to still work in 0.43.0.

I have created a fiddle to demonstrate the issue.

[fiddle](https://jsfiddle.net/jaapl/tkw12Lvz/)

**mapbox-gl-js version**: 0.43.0

**Comment by andest01** [comment] 2018-01-08 16:23
Likely related to https://github.com/mapbox/mapbox-gl-js/issues/5947

**Comment by jfirebaugh** [comment] 2018-01-08 17:58
Yes, duplicate of #5947.

**Closed by jfirebaugh** 2018-01-08 17:58 UTC
