### ISSUE TITLE
Background layer prevents preceding layers from rendering (except labels)

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#2910] opened 2016-07-26 00:53 UTC
Possibly related to https://github.com/mapbox/mapbox-gl-js/issues/2909? although this is slightly different. When the [`Background layer`](https://www.mapbox.com/mapbox-gl-style-spec/#layers-background) is the last layer styled, the preceding layers are not drawn _except_ if they are labels (and regardless of whether layer opacity is set as per #2909).

See https://api.mapbox.com/styles/v1/tristen/cir2leknf001hbnnedvf90u52.html?fresh=true&title=true&access_token=pk.eyJ1IjoidHJpc3RlbiIsImEiOiJiUzBYOEJzIn0.VyXs9qNWgTfABLzSI3YcrQ#3.6/42.30/-97.68 for example.

**Comment by lucaswoj** [comment] 2016-07-28 16:53
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2074

**Closed by lucaswoj** 2016-07-28 16:53 UTC
Labels: bug
