### ISSUE TITLE
Place labels cutoff at tile seams

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-gl-js#1365] opened 2015-07-08 19:03 UTC
Did not notice this behavior at other tile seams in /app, so struck me as odd:

![untitled](https://cloud.githubusercontent.com/assets/126868/8579293/59936f8e-25d1-11e5-9d8b-ce97eabc9b1b.gif)

Map location: Mumbai, India

**Comment by ansis** [comment] 2015-07-08 19:39
Yep. This is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/757 which will be solved by https://github.com/mapbox/mapbox-gl-js/pull/1197

**Closed by ansis** 2015-07-08 19:39 UTC
