### ISSUE TITLE
text-offset data driven styling fails

### ISSUE THREAD

**Issue by tsuz** [mapbox/mapbox-gl-js#11442] opened 2022-01-26 07:25 UTC
**mapbox-gl-js version**: any version (including latest v2.6.1)

**browser**:

### Steps to Trigger Behavior

 1. Implement data driven styling for text-offset
 2. Run the demo below and notice this errors

### Link to Demonstration

https://jsfiddle.net/tsuzk/f2pxr7z8/

### Expected Behavior

Since [`text-offset` is implemented][1], this data-driven styling should move the text offset.

[1]: https://github.com/mapbox/mapbox-gl-js/issues/4434

### Actual Behavior

The text does not offset and the console errors.

![Screen Shot 2022-01-26 at 16 19 54](https://user-images.githubusercontent.com/6927131/151119870-d2c1e57a-b179-473b-ae3d-370ffe46ef1e.png)

`Error: layers.country-label.layout.text-offset[0]: number expected, array found`

Related: 
https://github.com/mapbox/mapbox-gl-js/issues/9303#issuecomment-698270677

**Does this also occur in Studio?**

Yes, this also occurs in Studio.

![Screen Shot 2022-01-26 at 16 22 30](https://user-images.githubusercontent.com/6927131/151120179-35a82906-31a4-4942-bd25-cc2b288ba926.png)

**Comment by mourner** [comment] 2022-01-26 14:06
This is a duplicate of #6155. `text-offset` supports data-driven styling but only if you can provide static literals as possible outputs, e.g.:

```
[
  "case",
  ["<=", "symbol-rank", 2],
  ["literal", [1, 1]],
  ["literal", [2, 2]]
]
```

It's an issue with Expressions in general, and would be great to solve this (and it'd be useful for other properties too).

**Closed by mourner** 2022-01-26 14:06 UTC
Labels: bug :lady_beetle:

**Comment by tsuz** [comment] 2022-01-26 14:24
@mourner 
Thanks for checking.
That's the workaround that I ended up doing, also.
