### ISSUE TITLE
BoxZoom Does Not Zoom to Rectangle

### ISSUE THREAD

**Issue by x9xjdzz9** [mapbox/mapbox-gl-js#3961] opened 2017-01-12 13:51 UTC
If I have a map where boxzoom is enabled, and I hold down shift, drag my rectangle, and release, the map either zooms in a tiny bit or not at all. But it definitely does not zoom to the rectangle I drew. 
There are no messages in the console. I've seen this in 0.31, as well as some of the previous releases, so it is not brand new. You can see this in the MapBox examples: https://www.mapbox.com/mapbox-gl-js/examples/.

**Comment by mourner** [comment] 2017-01-12 14:20
Hmm, I can't reproduce — everything works fine for me. Can you share more details? What's your OS? Is this happening in a specific browser, and did you try other browsers? Does it always zoom incorrectly, or only sporadically?

**Comment by x9xjdzz9** [comment] 2017-01-12 14:28
It always zooms incorrectly.

It fails on Windows 8.1 with Chrome Version 55.0.2883.87 m (64-bit), IE 11.0.9600.18538, and Firefox 50.1.0.

It works on a Mac OS X El Capitan 10.11.6 running Chrome 55.0.2883.95 (64-bit) and Safari 10.0.2.

**Comment by mourner** [comment] 2017-01-12 14:33
Looks like this is the same as this issue: #3334. Let's close this one to keep the discussion centralized. Commented there.

**Closed by mourner** 2017-01-12 14:33 UTC
Labels: needs clarification
