### ISSUE TITLE
The oblique view of the map will cause the buildings in the distant view to disappear

### ISSUE THREAD

**Issue by liulianfan** [mapbox/mapbox-gl-js#10214] opened 2020-12-16 06:14 UTC
**mapbox-gl-js version**:
v2.0.0
**browser**:
chrome
### Steps to Trigger Behavior

 1. 
![image](https://user-images.githubusercontent.com/20163701/102311922-b0e84600-3fa8-11eb-810f-07b26d800876.png)

 2.
![image](https://user-images.githubusercontent.com/20163701/102311960-bd6c9e80-3fa8-11eb-8e9b-99957863fad7.png)

 3.
Tilt the map, the distant buildings disappear

### Link to Demonstration
https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/

**Comment by mourner** [comment] 2020-12-16 09:16
It works like that by design — on highly pitched views, we use a level-of-detail tile loading system where we load bigger, lower zoom tiles for distance areas to keep the amount of loaded data reasonable, otherwise we would have to load hundreds of tiles for a single view. On lower zoom levels, the data is simplified to compensate its density.

While we're considering adjusting building layer simplification on lower zoom levels in Mapbox Streets tiles to make the experience better, but we can't really address the issue on the GL JS side, nor can we solve it fully given the level-of-detail design, so I'd have to close the issue.

**Closed by mourner** 2020-12-16 09:16 UTC
