### ISSUE TITLE
Weird geojson behavior

### ISSUE THREAD

**Issue by korria** [mapbox/mapbox-gl-js#9201] opened 2020-01-17 19:28 UTC
I have had some interesting behavior with geojson shape files. Particulary the shapefile from Avalanche.org: (https://avalanche.org/wp-admin/admin-ajax.php?action=map_layer)  Not sure if this is a geojson problem or a mapbox problem.

**mapbox-gl-js version**: 1.6.1

**browser**: Chrome

### Link to Demonstration

```
       var layers = map.getStyle().layers;
        var lastSymbolId;
        for (var i = 0; i < layers.length; i++) {
          if (layers[i].type === 'hillshade') {
            lastSymbolId = layers[i].id;
            break;
          }
        }
```

 ```
map.addSource('Avalanche', {
          type: 'geojson',
          data: 'https://avalanche.org/wp-admin/admin-ajax.php?action=map_layer',
          tolerance: .4,
        });
```
```
 map.addLayer({
          'id': 'Avalanche',
          'type': 'fill',
          'source':'Avalanche',
          'layout': {},
          'paint': {
            'fill-color': ['get', 'color'],
            'fill-opacity': ['get', 'fillOpacity'],
            //'fill-outline-color': ['get', 'stroke'],
          },
          },lastSymbolId);
          map.addLayer({
            'id': 'AvalanchePulse',
            'type': 'fill',
            'source':'Avalanche',
            'layout': {},
            'paint': {
              'fill-color': ['get', 'color'],
              'fill-opacity': 1,
              //'fill-outline-color': ['get', 'stroke'],
            },
            'filter': ['==', ['get', 'product', ['get', 'warning']], 'warning'],
            },lastSymbolId); 
```

### Expected Behavior
![image](https://user-images.githubusercontent.com/34187363/72639813-b44ff900-3923-11ea-841c-f9f044722e7a.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/34187363/72639667-53c0bc00-3923-11ea-97b7-37a088c2c074.png)
Notice how some of the polygons do not fill correctly.  When you zoom in it causes weird behavior.
![image](https://user-images.githubusercontent.com/34187363/72640214-9f279a00-3924-11ea-96a0-03f772213631.png)
![image](https://user-images.githubusercontent.com/34187363/72640246-b797b480-3924-11ea-860b-0156f8820d33.png)

**Comment by stevage** [comment] 2020-01-21 02:01
Probably a known issue - #7023. Nice screenshots!

**Comment by mourner** [comment] 2020-01-29 18:00
Yes, duplicate of #7023.

**Closed by mourner** 2020-01-29 18:00 UTC
Labels: needs investigation :mag:
