### ISSUE TITLE
Filter Spec: Add 'like' operator and wildcards for strings

### ISSUE THREAD

**Issue by brambow** [mapbox/mapbox-gl-js#5215] opened 2017-08-31 12:34 UTC
## Motivation
Want to be able to filter on string comparisons that don't require exact text, but do allow for positioning of a string, unlike the "has" operator.  This would let me filter with operations like 'starts with' ('ABC%') or 'ends with ('%ABC')

## Design Alternatives
You could specifically add 'starts with', 'ends with', and 'contains'  operators, but 'like' + wildcards would be more flexible.

### Implementation
`filter: ['like', 'key', 'value']`

e.g.: `map.setFilter('states', ['like', 'statename', 'A%'])`

This would return all the states that begin with 'A'.

**Comment by jfirebaugh** [comment] 2017-08-31 14:50
Duplicate of #4113 / #4089.

**Closed by jfirebaugh** 2017-08-31 14:50 UTC
