### ISSUE TITLE
The tiles request still be sent  when i setLayoutProperty('layerId', 'visibility', 'none')  why ？

### ISSUE THREAD

**Issue by Eric-wh-007** [mapbox/mapbox-gl-js#7458] opened 2018-10-22 08:07 UTC
**mapbox-gl-js version**:v0.50.0

### Question
mapbox still send tiles requests when i  ``` setLayoutProperty('layerId', 'visibility', 'none' )  ```
it's bug or feature?

test case :  
```  


<div id='map'></div>

<div class='map-overlay top'>
    <div style="background:#fff;">
        <button onclick="showLayer()">show</button>
        <button onclick="hideLayer()">hide</button>
        <p>layer visibility: <span id="visibility"></span></p>
    </div>
</div>

<script>
mapboxgl.accessToken = 'pk.eyJ1IjoiODA3NTczNTE1IiwiYSI6ImNqZmJ5bXZ6ODBtdnMzM21zZGFwMW9kMncifQ.qVjod6pfoKs35WrQ7zmnLA';

var visibleTextEl = document.getElementById('visibility');
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/light-v9',
    center: [-87.6321, 41.8362],
    minZoom: 9.5,
    maxZoom: 13,
    zoom: 9.5
});

var slider = document.getElementById('slider');
var sliderValue = document.getElementById('slider-value');

map.on('load', function() {

    map.addLayer({
        "id": "chicago",
        "source": {
            "type": "raster",
            "url": "mapbox://mapbox.u8yyzaor"
        },
        "type": "raster"
    });

});

function showLayer() {
    map.setLayoutProperty('chicago', 'visibility', 'visible');
    visibleTextEl.innerText = 'show'
}

function hideLayer() {
    map.setLayoutProperty('chicago', 'visibility', 'none');
    visibleTextEl.innerText = 'hide'
}
</script>



### Links to related documentation

<!-- Include links to the specific section(s) of the documentation where you would have expected to find an answer to this question. -->

**Comment by mourner** [comment] 2018-10-22 08:51
Closing as duplicate of #7457. Please stop reporting new issues.

**Closed by mourner** 2018-10-22 08:51 UTC
