### ISSUE TITLE
Add a stretchable image to the map. Not Looks Right.

### ISSUE THREAD

**Issue by sslnwyl** [mapbox/mapbox-gl-js#9183] opened 2020-01-15 02:56 UTC
**mapbox-gl-js version**: the last version.  mapbox-gl@1.61

**browser**: google's chrome explorer.

### Steps to Trigger Behavior

 1.The Example named "Add a stretchable image to the map".
 2. When our map zoom to the level  featrues  get together, words overlaped,we can't  distinguish any of them.
 3. Wish someone to help me . Thanks.

**Comment by sslnwyl** [comment] 2020-01-15 03:04
I use the code  copy from the example. the red box selection place is what I puzzle about .

![image](https://user-images.githubusercontent.com/27253644/72401192-4c17e080-3786-11ea-9ebf-a1395f426bc3.png)

**Comment by alexshalamov** [comment] 2020-01-15 20:41
@kkaefer Look like duplicate of https://github.com/mapbox/mapbox-gl-js/issues/4064

**Comment by mourner** [comment] 2020-01-15 21:00
Right — let's track it there.

**Closed by mourner** 2020-01-15 21:00 UTC
Labels: bug :beetle:

**Comment by sslnwyl** [comment] 2020-01-16 02:01
thanks !!!
