### ISSUE TITLE
[Bug] Symbol rendering broken in overzoomed pitched and rotated maps

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#5465] opened 2017-10-16 11:17 UTC
Rendering of symbols in overzoomed maps breaks when pitch and rotation is applied. See attached gif for simple example with collision boxes.

It should also be noted that even if you set `icon-allow-overlap` to true, high pitch with rotate between certain degrees makes symbols disappear.

![ezgif-4-03535144ac](https://user-images.githubusercontent.com/5638107/31609141-42ec81c2-b273-11e7-8a01-3ce0c40dc688.gif)

**mapbox-gl-js version**: 0.41.0 and older versions

### Steps to Trigger Behavior

 1. Zoom into the given map (ensure you overzoom)
 2. Pitch the map
 3. Rotate as illustrated in the GIF

### Expected Behavior

Symbols show as expected.

### Actual Behavior

Symbols disappear during rotate and pitch.

**Comment by ChrisLoer** [comment] 2017-10-17 17:45
Thanks for the report, this is definitely a bug! Duplicate of #5095.

This should be fixed by PR #5150.

**Closed by ChrisLoer** 2017-10-17 17:45 UTC
Labels: bug

**Comment by kristfal** [comment] 2017-10-18 06:53
Hey Chris,

thanks for the reply. I haven’t tested that branch, but i’ll give it a spin later. I’d just like to make you aware that with the current bug, symbols with icon-allow-overlap also stop rendering, so this might not solely be a collision related issue. You’ll also notice in the example above that symbols don’t render even when their collision box is green (non-colliding) after the collision boxes are distorted. 

I’ll hit the viewport branch with the same tests and get back here if I find any similar issues.
