### ISSUE TITLE
inverted ( mirrored ) map on Raspbian bullseye 

### ISSUE THREAD

**Issue by serbyxp** [mapbox/mapbox-gl-js#11383] opened 2022-01-08 20:04 UTC
Not sure why but on my laptop and on my phone the map is normal, but on all my raspberry pis the map is inverted or mirrored. The locations are accurate but everything is reversed including the map. I can spin the map around but it still stays inverted or mirrored. Is there a button or combination of buttons that can reset the map to " normal " or out of " inverted". Besides that the letters and everything is inverted. The "paning" or moving around the map is also inverted.. On normal mouse setup pushing / pulling the map up moves it down left goes right.. vice versa . I am using the map as part of another program that utilises the repository.

**Comment by ryanhamley** [comment] 2022-01-10 19:07
Are you using a Chromium-based browser? This appears to be a [known issue](https://forums.raspberrypi.com/viewtopic.php?f=28&t=270113) and there appears to be a potential solution in [this thread](https://forums.raspberrypi.com/viewtopic.php?f=91&t=274315). It seems to be an issue with Chromium and is highly environment-specific. I doubt there's anything you can do within GL JS to solve this. Since it's not a bug in GL JS, I'm going to close the issue but if you need some more assistance, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).

**Closed by ryanhamley** 2022-01-10 19:07 UTC
