### ISSUE TITLE
NavigationControl - Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by psyrendust** [mapbox/mapbox-gl-js#5260] opened 2017-09-08 17:56 UTC
**mapbox-gl-js version**: 0.39.1
**OS**: Mac OS Sierra v10.12.6
**Browser**: Chrome Version 60.0.3112.113 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Load example page: https://www.mapbox.com/mapbox-gl-js/example/navigation/
 2. Rotate the map
 3. Repeated click the compass button

### Expected Behavior
To not throw an Uncaught Range Error.

### Actual Behavior
As the map nears a cardinal north orientation, repeated clicks (quick succession) on the compass button will cause the following uncaught error to occur.

```
navigation_control.js:76 Uncaught RangeError: Maximum call stack size exceeded.
    at NavigationControl._onCompassMove (navigation_control.js:76)
    at NavigationControl._onCompassMove (navigation_control.js:76)
    at NavigationControl._onCompassMove (navigation_control.js:76)
    at NavigationControl._onCompassMove (navigation_control.js:76)
    at NavigationControl._onCompassMove (navigation_control.js:76)
    at NavigationControl._onCompassMove (navigation_control.js:76)
    at NavigationControl._onCompassMove (navigation_control.js:76)
    at NavigationControl._onCompassMove (navigation_control.js:76)
    at NavigationControl._onCompassMove (navigation_control.js:76)
    at NavigationControl._onCompassMove (navigation_control.js:76)
```

**Comment by jfirebaugh** [comment] 2017-09-08 18:09
Duplicate of #5212.

**Closed by jfirebaugh** 2017-09-08 18:09 UTC
