### ISSUE TITLE
Unable to install from npm due to missing dependencies or wrong package names

### ISSUE THREAD

**Issue by cubodehelio** [mapbox/mapbox-gl-js#4613] opened 2017-04-19 18:33 UTC
**0.35.1**:

### Steps to Trigger Behavior

 1. `npm install mapbox-gl --save`

### Expected Behavior

```bash
└── mapbox-gl@0.35.1
```

### Actual Behavior

```
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/home/***/local/bin/node" "/home/***/local/bin/npm" "install" "mapbox-gl" "--save"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! Invalid name: "@mapbox/shelf-pack"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/***/.npm/_logs/2017-04-19T18_26_15_079Z-debug.log
```

When I try to install an earlier version like `0.34.0` the message is:

```
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/home/***/local/bin/node" "/home/***/local/bin/npm" "install" "mapbox-gl@0.34.0" "--save"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! Invalid name: "@mapbox/unitbezier"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/***/.npm/_logs/2017-04-19T18_30_29_487Z-debug.log
```

**Comment by jfirebaugh** [comment] 2017-04-19 18:50
I can't reproduce this with the same version of node and npm. The error looks like you have an outdated version of npm installed that doesn't understand scoped packages. I suggest you try cleaning and reinstalling npm.

Closing here since this is a local installation or configuration issue, and not a bug in mapbox-gl-js.

**Closed by jfirebaugh** 2017-04-19 18:50 UTC

**Comment by cubodehelio** [comment] 2017-04-21 15:17
thanks for your time. It was a wrong installation of `node+npm` in my home. I'm used to install node directly dropping the content of the official `tar` files in a local folder in my home, overriding the previous files.. witch turns out is very problematic.
