### ISSUE TITLE
Maps not rendering correctly in Safari

### ISSUE THREAD

**Issue by jaapster** [mapbox/mapbox-gl-js#5718] opened 2017-11-20 15:38 UTC
**mapbox-gl-js version**: 0.42.1

### Steps to Trigger Behavior

1. Open any mapbox example in Safari (macOS High Sierra)

### Expected Behavior
I would expect to see all layers in the map

### Actual Behavior
Only point geometries (and background layer?) are visible.

**Comment by jfirebaugh** [comment] 2017-11-20 16:17
Duplicate of #5712.

**Closed by jfirebaugh** 2017-11-20 16:17 UTC
