### ISSUE TITLE
Scrolling on responsive website(2 finger interaction on mobile devices) ??

### ISSUE THREAD

**Issue by TruLLi** [mapbox/mapbox-gl-js#10618] opened 2021-04-27 08:09 UTC
**mapbox-gl-js version**:
  "mapbox-gl": "^1.13.1"
### Question
Hello all,
I have question regarding scrolling. I have built responsive website in nuxt.js and I have a problem when I'm scrolling the site on mobile devices. Current behavior is when you scrolling and you came to point where map is located and you point finger on map and try to continue scrolling the site you will end up interacting with map.

Expected behavior is to continue scrolling the site. But to interact with map on example only with 2 fingers I don't know something like that.

I have read the official documentation and I couldn't found anything helpful, I also searched for possible solutions and what I found seems to complicated for that one simple stuff.

Is there any option like scrollZoom or dragPan maybe for that 2 finger map interaction?

Best regards!!

### Links to related documentation

https://docs.mapbox.com/ios/maps/guides/interacting-with-the-map/
https://docs.mapbox.com/mapbox-gl-js/api/properties/
https://github.com/mapbox/mapbox-gl-js/issues/2618

**Comment by karimnaaji** [comment] 2021-05-11 22:19
I'll close this issue as duplicate of #2618 to keep the conversation centralized since at this point there is no support for that.

**Closed by karimnaaji** 2021-05-11 22:19 UTC
