### ISSUE TITLE
querySourceFeatures returns incorrect geometries after a certain zoom level

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-gl-js#4677] opened 2017-05-03 20:56 UTC
Using version `0.37.0` and recreated with [this fiddle](https://jsfiddle.net/t3puox9a/5/) (click on the top box to recalculate those values)

<img width="323" alt="screen shot 2017-05-03 at 4 54 22 pm" src="https://cloud.githubusercontent.com/assets/7108211/25681124/373a3d4e-3021-11e7-965f-af43f6d7e595.png">

`querySourceFeatures` should return features from loaded/nearby source tiles. It's unclear if it returning the wrong features or if only the geometry getter is affected but the returned geometries don't appear to be within (or nearby) the map bounds. It only happens after a certain zoom level (in this example, 9). A little more investigation revealed that the `feature.tile` was sometimes returning twice the x and y values I expected but this was difficult to recreate and not always present.

**Comment by mollymerp** [comment] 2017-05-04 19:29
Hi @drewbo – thanks for the report. This has to do with the `source`'s `maxzoom`(which in your example is `8`) and I believe is related to the ticket you cut previously #2868. I also think this is a duplicate of #3722. closing here to move discussion over there.

**Closed by mollymerp** 2017-05-04 19:29 UTC

**Comment by drewbo** [comment] 2017-05-04 19:45
Thanks @mollymerp and sorry for duplicating!
