### ISSUE TITLE
0.12.3 drawCircles error?

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-gl-js#1936] opened 2016-01-15 09:29 UTC
My map that was working fine with 0.12.2 is now freezing and throwing the attached error in both Safari and Chrome.
![0 12 3 drawcircles error](https://cloud.githubusercontent.com/assets/912721/12349777/3b3c2cb8-bb6a-11e5-932f-786ef8d136a4.png)

Working 0.12.2 version here: http://parallel.co.uk/os-openmap-gl/

**Comment by bhousel** [comment] 2016-01-15 14:51
Maybe related to 5739dd09a1216770984d512a390074046fa2c7d9, which may contain a fix?

cc @mourner @lucaswoj

**Comment by mourner** [comment] 2016-01-15 14:53
Yes, very likely a duplicate of #1933. @lucaswoj is on it.

**Closed by mourner** 2016-01-15 14:53 UTC
Labels: bug
