### ISSUE TITLE
fill-extrusion-height property function not working with float

### ISSUE THREAD

**Issue by juliangums** [mapbox/mapbox-gl-js#4924] opened 2017-06-30 18:55 UTC
fill-extrusion-height seems to work with floating points when applied to the entire layer. but if I use a property function it only take the whole number. ie. 0.1 will result in 0 with property function while it does work when applied globally. not sure if this applies to fill-extrusion-base as well

**Comment by lbud** [comment] 2017-06-30 18:56
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/4438.

**Closed by lbud** 2017-06-30 18:56 UTC
