### ISSUE TITLE
Cannot set conditionally a fill-pattern in expressions

### ISSUE THREAD

**Issue by marcofugaro** [mapbox/mapbox-gl-js#9776] opened 2020-06-10 15:46 UTC
Hey! I'm trying to achieve something like this:

![](https://user-images.githubusercontent.com/7217420/84287889-c7689d00-ab40-11ea-96f6-dcdf94d5fa13.png)

I am trying to do this with expressions in the `fill-color` and the `fill-pattern`:

```js
'paint': {
  'fill-color': [
    'match',
    getValue(), // returns a ['get' , ...]
    'value1', 'red',
    'value2', 'green',
    'value3', 'blue',
    'transparent',
  ],
  'fill-pattern': [
      'case', 
      ['==', getValue(), null], // the value is null means there's no data in my case
      'pattern',
      null,
  ],
}
```

However I'm seeing this error in the console, and nothing on the map:
<img width="556" alt="Screenshot 2020-06-10 at 17 42 39" src="https://user-images.githubusercontent.com/7217420/84288686-ca17c200-ab41-11ea-80c5-80ee92c4fd96.png">

### Steps to Trigger Behavior

 1. Open provided jsbin
 2. check console

### Link to Demonstration

I've replaced my `['==', getValue(), null]` expression with `['boolean', IS_THERE_DATA]` for simplicity

https://jsbin.com/haqeyevige/edit?html,output

### Expected Behavior
Should show the pattern if the constant `IS_THERE_DATA` is `false`, otherwise should show the red color.

### Actual Behavior
Error happens.

**mapbox-gl-js version**: 1.10.1

**browser**: Chrome, but really any

**Comment by ryanhamley** [comment] 2020-06-10 23:17
Hi @marcofugaro thanks for the report. I think there's a couple different issues at play here. If I understand correctly, what you're expecting is that if `fill-pattern: null` then you should fall back to `fill-color`. Is that correct? If so, unfortunately, that's not possible at this time. `fill-pattern` will always take precedence over `fill-color` so you'll just see a blank space, not the color.

The other issue is that  `null`, `undefined` and `''` are not valid values for expressions right now. There's actually a number of similar open tickets but I think https://github.com/mapbox/mapbox-gl-js/issues/8331 is almost exactly the same albeit for `line-pattern` and `line-color`. As described there, I believe the most effective workaround right now is to use a [`filter`](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#filter) to show layers with `fill-color` and layers with `fill-pattern` depending on a particular value. See https://jsbin.com/ruhiremeza/1/edit?html,output for an example of this.

I'm going to close this issue as being a duplicate of #8331. Thanks for using GL-JS!

**Closed by ryanhamley** 2020-06-10 23:17 UTC

**Comment by marcofugaro** [comment] 2020-06-11 10:19
Thanks for the example @ryanhamley! I was able to make it work using another layer!

Regarding the usage of `null` in expressions, that's a bummer. I was able to make it work with a match expression and just get away with some warnings of `"Image #fbb03b could not be found"` because of course it's not a loaded pattern.

```js
'paint': {
  'fill-pattern': [
      'match',
      getValue(), // returns a ['get' , ...]
      'value1', '#fbb03b',
      'value2', '#223b53',
      'value3', '#e55e5e',
      'pattern',
  ],
}
```
