### ISSUE TITLE
Cluster layer showing fault

### ISSUE THREAD

**Issue by q869939686** [mapbox/mapbox-gl-js#7201] opened 2018-08-27 08:23 UTC
There are 145 points in this area, but only 9 are shown.Is this a bug?Point grows with amplification untils all in!
![image](https://user-images.githubusercontent.com/29123332/44648877-00d82300-aa15-11e8-99ee-660bb62474ab.png)
![image](https://user-images.githubusercontent.com/29123332/44648905-13525c80-aa15-11e8-9a8e-1e6c1e0916e8.png)
![image](https://user-images.githubusercontent.com/29123332/44649069-72b06c80-aa15-11e8-9b60-9173c2d56f14.png)

**Comment by jfirebaugh** [comment] 2018-08-27 14:15
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?

**Comment by mollymerp** [comment] 2018-09-05 20:08
Closing because we cannot diagnose this issue without a minimal reproduction. Please open a new issue if you can provide a demonstration on jsbin.com. Thanks!

**Closed by mollymerp** 2018-09-05 20:08 UTC
Labels: needs information :pray:
