### ISSUE TITLE
Problem re-initialising map in Microsoft browsers

### ISSUE THREAD

**Issue by Zev19** [mapbox/mapbox-gl-js#3040] opened 2016-08-20 11:12 UTC
**mapbox-gl-js version**: v0.22.1
### Steps to Trigger Behavior
1. Refresh page/redirect back to map from another page. Test case on example page https://www.mapbox.com/mapbox-gl-js/examples/
### Expected Behavior

Map loading normally
### Actual Behavior

Map does not load, 404 error returning under F12, script not found. Seems to only occur with Internet Explorer and Microsoft Edge

**Comment by tgecho** [comment] 2016-09-09 18:16
I can confirm this specific page  in Edge and IE11. I've also had a lot of sporadic issues in IE that seem to most commonly come and go on every alternate page refresh.

**Comment by tgecho** [comment] 2016-09-12 14:03
I did a little manual bisecting and I think I've narrowed it down to something in this commit:  https://github.com/mapbox/mapbox-gl-js/commit/def9cb5165e06f2a225e2df5854a0a14f50ad53f (Refactor Source interface to allow/prepare for extensibility).

If I use the commit before this one, everything seems to work fine. With this commit, every other time I reload the page, the map doesn't load/update in IE11/Edge.

This commit is a bit involved, but I'll keep digging to see if I can find the precise culprit.

**Comment by tgecho** [comment] 2016-09-12 14:11
It seems to primarily affect to vector tile and/or geojson layer change made after initialization.

**Comment by tobinbradley** [comment] 2016-09-20 15:45
Can confirm. Only thing to add is it looks like the map style.load event fires but the map load event never fires when the map doesn't draw. Reverting back to 0.21 fixes the problem.

**Comment by hellkama** [comment] 2016-09-27 12:06
Is there any known workaround for this issue other than using old versions of the library? This is quite critical bug for me as large portion of my users use the affected browsers.

**Comment by ivanakimov** [comment] 2016-09-27 19:57
Is there an ETA on this bug fix? Same problem, have users that can't use the map.

**Comment by mourner** [comment] 2016-09-27 20:54
@anandthakker any chance you could look into this?

**Comment by anandthakker** [comment] 2016-09-27 21:31
I definitely plan look into it (this browser tab has been open for a while now!) -- but I'm scrambling towards a deadline right now, so it might still be a few days / next week before I can dig into this.

**Comment by ivanakimov** [comment] 2016-09-27 23:25
@anandthakker not to get too greedy, but is there any chance this might make it into 0.25.0? 😓

**Comment by anandthakker** [comment] 2016-09-27 23:43
@ivanakimov I think the next release is tracked by [this milestone](https://github.com/mapbox/mapbox-gl-js/milestone/20) -- but if the fix doesn't make it in before that that gets shipped, perhaps it could go into a patch release (0.25.1 or something).  I definitely want to resolve this ASAP... but my "day job" is in crunch time.

**Comment by ivanakimov** [comment] 2016-09-27 23:48
@anandthakker Ah, got ya. Makes sense. Yeah, bummer about this issue, cause it's quiet noticeable at the moment. Ok, will wait. Thank you.

**Comment by mollymerp** [comment] 2016-10-06 23:50
@anandthakker any update here? I've added it as a release blocker to make sure we get this fixed before [Edinburgh](https://github.com/mapbox/mapbox-gl-js/milestone/21). Happy to take a look if you're swamped but I'll need to get my hands on a windows machine 😅

**Comment by anandthakker** [comment] 2016-10-07 09:50
@mollymerp oof, I'm really sorry 😞 - I'd really hoped to get into it this week, but I've been behind and still trying to catch up.

Looks like Edinburgh is meant to go out on the 12th.  I do think I'd be able to jump into this by Tues, but that's pretty close to the 🚢 date.  If you're able to get a head start before then, I'd be happy to team up or take over next week.

(Btw, re: windows machine: I was going to try using Browserstack to debug, which is going to be... tons of fun. Heh.)

**Comment by mollymerp** [comment] 2016-10-07 20:37
@anandthakker thanks for the update and no worries! I know you're busy!

I just tried to reproduce this bug on IE11 and I wasn't able to see the bug described here. Removing as a release blocker for now until we are able to reproduce and therefore debug + fix. Apologies for the delay on this one.

**Comment by ivanakimov** [comment] 2016-10-08 17:00
It's reproducible on Edge (and in IE11 mode on Edge) if you refresh a few times. Sometimes it loads fine, and sometimes it does not. For us, it was about 50%.

**Comment by hellkama** [comment] 2016-10-08 17:15
Yep I don't think this should be hard to reproduce as it happens on every second page load at least on my Win 10 machine. Haven't had chance to test other systems. Language / regional settings is one possibility if it works normally on some systems?

Video of the bug happening: https://gfycat.com/EasygoingLegitimateBluet

**Comment by tgecho** [comment] 2016-10-08 17:47
For what it's worth, my IE testing machine is a vanilla Modern.ie VM in Parallels

**Comment by ivanakimov** [comment] 2016-10-13 01:02
@lucaswoj I actually have customers leaving because of these Windows/IE bugs ([#3040](https://github.com/mapbox/mapbox-gl-js/issues/3040), [#2942](https://github.com/mapbox/mapbox-gl-js/issues/2942)). Was so looking forward to these fixes and now they're not even in [Edinburgh](https://github.com/mapbox/mapbox-gl-js/milestone/21) release...

Is there an ETA for them? Aren't they release blockers if the map is not showing?

**Comment by lucaswoj** [comment] 2016-10-13 18:53
@ivanakimov We hear you 😞. Unfortunately we have been unable to reproduce these bugs in our in-house windows machine. Without the ability to repro the bug, there's little hope of a fix, and with little hope of a fix, it seems foolish to indefinately delay the next release. This is high on my priority list.

**Comment by ivanakimov** [comment] 2016-10-13 19:22
Let me know how I can help you reproduce.

I realize tracking down bugs like these is a pain in the a, but looks like there are quite a few people that are noticing this, not just us. Also, if you'd like to see the map we're using, just [ping me](mailto:ivan@barreleye.com).

For #3040 we reproduced it on:
```
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393
Windows 10
```

For #2942, it was exactly what was reported: Chrome + Windows 7. Also applying pitch (of 20 degrees) helped avoid the issue.

**Comment by ivanakimov** [comment] 2016-10-17 17:27
@anandthakker any luck on fixing this?

**Comment by hellkama** [comment] 2016-10-26 07:41
I don't understand how this issue doesn't get any love. 

25% of my (enterprise) users have IE11 or Edge. We cannot dictate the browsers that are deployed to their machines.

This should help you if you don't have Windows boxes:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

I tested with the "Microsoft Edge on Windows 10 Stable (14.14393)" and the bug is there. It should be easily reproducible with these VM images.

**Comment by jfirebaugh** [comment] 2016-10-26 19:33
I can reproduce the issue in the "Microsoft Edge on Windows 10 Stable (14.14393)"  VM that @hellkama suggested. The symptom that I saw was that when loading the debug page (`npm start`, then open `http://localhost:9966/debug/` -- or in my case, within the VM `http://10.0.2.2:9966/debug/`), the first refresh results in a blank map, and then subsequent refreshes alternate between a working map and a blank map.

I added some tracing to the code, and what I saw is that in the cases where the map is not working,  it's because the Web Workers simply never receive any messages that are posted to them from the main thread. I can't see any reason why they shouldn't, or why this would happen on every second refresh. I think it must be an IE bug.

@csuwildcat, is this something you can have someone on your team look at?

**Comment by csuwildcat** [comment] 2016-10-26 20:52
If I had to guess, I would say it's probably an issue with Workers being created/accessed/cached on localhost/IP-based URLs. Many browsers have security enforcement that cause issues when using certain APIs (Web Workers, Service Worker, File, etc) with local origins.

**Comment by jfirebaugh** [comment] 2016-10-26 22:14
@csuwildcat Here's a minimized test case. I think it demonstrates pretty conclusively that this is an IE bug. Load it up, open developer tools, and hit refresh -- you'll see that after the first load, the worker doesn't receive any messages. If you comment out the `var xhr = new XMLHttpRequest();` line, it works as expected.

```
<script id="worker" type="worker">
    console.log('worker created', self);

    self.addEventListener('message', function(e) {
        console.log('worker received message', e.data);
    }, false);

    var xhr = new XMLHttpRequest();
</script>
<script>
    var src = document.getElementById('worker').innerText;
    var blob = new Blob([src], { type: 'text/javascript' });
    var workerURL = URL.createObjectURL(blob);
    var worker = new Worker(workerURL);
    setTimeout(function () {
        console.log('posting messages to worker');
        worker.postMessage(1);
        worker.postMessage(2);
        worker.postMessage(3);
        worker.postMessage(4);
    }, 10);
</script>
```

**Comment by mourner** [comment] 2016-10-26 22:33
@jfirebaugh I'm puzzled about this comment then https://github.com/mapbox/mapbox-gl-js/issues/3040#issuecomment-246357133, which says the bug did not trigger in an earlier GL JS version but started happening after @anandthakker's changes. Is this actually the case?

**Comment by jfirebaugh** [comment] 2016-10-26 22:42
Opened an issue: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9545866/

**Comment by jfirebaugh** [comment] 2016-10-26 22:45
@mourner Given how simple the reduced test case is, I think it's probably not related to @anandthakker's changes -- or if it's is, it's related only in that his changes changed the timing in a way that triggered the bug where it wasn't triggered before.

**Comment by anandthakker** [comment] 2016-10-26 22:45
@mourner I have been puzzled about that as well -- there were certainly a lot of changes in #2667, but not ones that (at least on the surface) would seem to affect main-thread/worker communication like this. (If the offending change had been, say, the global worker pool one, that would be less surprising.)

In any case, for anyone watching: this is causing a compatibility bug in a project of ours whose Nov 8th  ship date is about as inflexible as they come... so I definitely have to work on it very, very soon -- I'll post back here if I come up with any kind of workaround.

@jfirebaugh kudos for isolating XmlHttpRequest

**Comment by tgecho** [comment] 2016-10-26 22:49
@csuwildcat I happens for me on the official examples, so I don't think it's (only) a localhost/ip thing. 

@mourner I'll try do another pass to confirm my earlier observation about that commit as soon as I can.

**Comment by jfirebaugh** [comment] 2016-10-26 22:52
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9243268/ looks likely to be related.

**Comment by tgecho** [comment] 2016-10-27 00:35
I just ran through those two commits again using the "Display a map" example. The bug occurs reliably on def9cb5 and not at all on 302aadd. However... from what the others have show I think @jfirebaugh is likely right that it's only the distantly triggered race condition.

**Comment by tgecho** [comment] 2016-10-27 00:57
To add to the weird race condition smell, I found that if I modify the example to initialize the map with an empty style and `setStyle` immediately after the bug seems to go away.

```
var map = new mapboxgl.Map({
    container: 'map',
    style: {version: 8, sources: {}, layers: []},
    // style: 'mapbox://styles/mapbox/streets-v9',
    center: [-74.50, 40],
    zoom: 9
});
map.setStyle('mapbox://styles/mapbox/streets-v9');
```

Hope that's worth *something* ¯\\\_(ツ)\_/¯

**Comment by jfirebaugh** [comment] 2016-10-31 20:45
Got a reply on the issue I filed:

> Ibrahim O. commented: <p>Thank you for your feedback. We would like to inform you that this issue has been previously identified and the fix is currently available in the insider preview which will be also available in the public stable version in upcoming updates soon.  </p> <p>Best regards,<br> The MS Edge Team </p>

**Comment by ivanakimov** [comment] 2016-11-01 23:07
> will be also available in the public stable version in upcoming updates soon

@jfirebaugh Good to hear they're fixing this. Does this mean that only the new Edge versions will have the patch? (as in IE11 will still have these issues?)

**Comment by twelch** [comment] 2017-03-21 03:59
This issue appears to be fixed by Microsoft as of Edge developer preview 15.15014, released 1-19-17, but not yet in the public release.  I tested the GL JS examples with the Windows 10 Preview VM here - https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/.  None of the load issue I see with the stable release.

**Comment by jfirebaugh** [comment] 2017-03-21 16:31
Thanks for checking @twelch! When I looked into this, I didn't see a feasible workaround, so I think we have to rely on the Edge bugfix alone to resolve the issue. I'll close here.

**Closed by jfirebaugh** 2017-03-21 16:31 UTC
Labels: bug, environment-specific bug

**Comment by strech345** [comment] 2017-04-26 10:38
@tgecho 
if i init with a empty style and set the style later, the bug comes more then as default.

**Comment by BBaysinger** [comment] 2018-04-27 21:13
I just started encountering the behavior that some people were saying they observed. The first time I load a map on the page (single page app), there's about a 50% chance it wont render all the layers. But I used @tgecho trick:

> To add to the weird race condition smell, I found that if I modify the example to initialize the map with an empty style and setStyle immediately after the bug seems to go away.

 ...and it appears to work after about 30 page refreshes, so far.

I'm using v`~0.44.x`, and I tested all the way back to v`~0.38.0`, and still had the same issue.

**Comment by Rajavelu** [comment] 2018-09-19 09:55
> To add to the weird race condition smell, I found that if I modify the example to initialize the map with an empty style and `setStyle` immediately after the bug seems to go away.
> 
> ```
> var map = new mapboxgl.Map({
>     container: 'map',
>     style: {version: 8, sources: {}, layers: []},
>     // style: 'mapbox://styles/mapbox/streets-v9',
>     center: [-74.50, 40],
>     zoom: 9
> });
> map.setStyle('mapbox://styles/mapbox/streets-v9');
> ```
> Hope that's worth _something_ ¯_(ツ)_/¯

Still, Not working for me.
