### ISSUE TITLE
GeoJSON feature properties as nested array returned as String literal of "object Object" on map click event

### ISSUE THREAD

**Issue by antonhalim** [mapbox/mapbox-gl-js#2866] opened 2016-07-14 04:21 UTC
Hi! I am currently using mapbox-gl with GeoJSON feature property as an array of objects, eg:
```
{
	geometry: {
		type: "Point",
		coordinates: [-120.613731, 35.115046]
	},
	properties: [
		{report_id: 1},
		{user: 1},
		{age: 42]
	]
}
```

The reason I'm doing this is to get an ordered tooltip data from the properties.
```
this.map.on("click", (event)=>{
				const features = this.map.queryRenderedFeatures(event.point, {layers: ['metrics-points']})
				if(_.isEmpty(features)) return

				const feature = features[0]
				console.log(feature.properties)
			})
```

I'm getting a result of `Feature Object` with properties of 
```
Object
0: "[object Object]"
1: "[object Object]"
2: "[object Object]"
```
instead of what I expect, which is 
```
properties: [
		{report_id: 1},
		{user: 1},
		{age: 42]
	]
```
My guess, map feature layers doesn's support nested feature properties.
Any idea how can I get get the string object literal being converted as object instead of string? 
I shared a jsbin how my code should looks like here https://jsbin.com/migoqanoga/1/edit?html,js,output
Thank You!

**Comment by jfirebaugh** [comment] 2016-07-14 16:53
Duplicate of #2434.

**Closed by jfirebaugh** 2016-07-14 16:53 UTC
