### ISSUE TITLE
Marking event handler passive

### ISSUE THREAD

**Issue by martinrisseeuw** [mapbox/mapbox-gl-js#4277] opened 2017-02-15 15:51 UTC
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Get a android device or simulator
 2. Browse to http://secrid.martinr.nl/stores/
 3. Type a location to flyTo in the geocoder field
 4. Select the location by clicking (touching it)
 5. Map starts to fly but stops before reaching the location

### Expected Behavior

FlyTo the select location without stopping before

### Actual Behavior

When you select a location through the geocoder the map stops when you press one of the items in the list. My simulator returns this warning: 
`Handling of 'touchmove' input event was delayed for 164 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.`

When you use enter instead of pressing the selection the behaviour works as expected.

**Comment by lucaswoj** [comment] 2017-02-16 19:18
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/3720

**Closed by lucaswoj** 2017-02-16 19:18 UTC
