### ISSUE TITLE
Add webpack support

### ISSUE THREAD

**Issue by twelch** [mapbox/mapbox-gl-js#1649] opened 2015-10-26 20:27 UTC
I'm able to bundle gl-js using webpack, but I'm getting a runtime error (in glify) with Chrome 46 on OSX.  @tmcw mentioned this has been reported before and that a webpack alternative to glify may be needed.  Adding an issue for reference and noting workaround.

```
Uncaught TypeError: Cannot read property 'match' of undefined
```
at https://github.com/mapbox/glify/blob/master/index.js#L13

Simple example showing my work -- https://github.com/twelch/react-mapbox-gl-js/tree/webpack-test
One workaround is to shim with the pre-built gl-js library using the webpack script-loader module.
```
require("script!mapbox-gl/dist/mapbox-gl.js");
```
instead of
```
import mapboxgl from 'mapbox-gl';
```

**Comment by tmcw** [comment] 2015-11-03 21:50
My PR at https://github.com/mapbox/glify/pull/7 avoids the browserify check, and combined with a section in the webpack config like

```js
{
  node: {
   fs: "empty"
  }
}
```

(people [recommend this](https://github.com/josephsavona/valuable/issues/9) but [nobody knows what it does](https://github.com/webpack/jade-loader/issues/8#issuecomment-103087171))

That said, that only gets us to the point where it appears that the transform doesn't work. Hands-on testing and development of this compatibility layer might be better left to someone with more knowledge of webpack internals.

**Comment by Madumo** [comment] 2015-11-05 16:15
I putted an alias in my webpack config: `'mapbox-gl': path.resolve('./vendor/mapbox-gl/mapbox-gl.js')` so i can still use the es6 module syntax. But it would be great if the lib could be bundled by webpack.

**Comment by hannesj** [comment] 2015-11-13 11:05
It is not just the glify that is the problem. I tried manually compiling the shaders and using the result to build with webpack but it still fails, as [dispatcher.js](https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/browser/dispatcher.js) uses webworkify to generate the worker files/blobs with browserify. I tried to change those to webpack's worker-loader but failed in getting that to work.

**Comment by yuvadm** [comment] 2015-11-30 13:01
Curious how far we are on getting gl-js + react + webpack to work. Is this a problem that requires a long term architectural-level solution?

**Comment by lucaswoj** [comment] 2015-11-30 18:41
@hannesj Could you elaborate on why webpack's worker-loader didn't work?

 >  I tried to change those to webpack's worker-loader but failed in getting that to work.

**Comment by hannesj** [comment] 2015-11-30 20:49
@lucaswoj, Sorry, I didn't debug it very thoroughly, as it works to just bundle in the pre-packaged js. It seemed that the individual workers were spun up correctly, but for some reason the event listeners in the worker didn't get executed when messages were sent from the main thread.

**Comment by yuvadm** [comment] 2015-11-30 20:51
@hannesj can you explain a bit more about your solution? Did you just use a prebundled shim same way as in https://github.com/twelch/react-mapbox-gl-seed/blob/master/src/components/GLMap.js#L3-L4 ?

**Comment by hannesj** [comment] 2015-11-30 20:59
@yuvadm, basically yes, except that we don't use the script-loader as mapbox-gl is exposed ad a commonJS module. You can see our usage [here](https://github.com/HSLdevcom/digitransit-ui/blob/master/app/component/map/navigation-map.cjsx#L17)

**Comment by yuvadm** [comment] 2015-12-15 21:49
Permalink for @hannesj previous link: https://github.com/HSLdevcom/digitransit-ui/blob/8fab2aa06f96715832d45ddc76e34c168fa1d178/app/component/map/navigation-map.cjsx#L17

**Comment by Aourin** [comment] 2015-12-22 16:48
Even if you are building with webpack (I have been doing so), minifyify is also regular dep. Because it is a regular dep, it has a peerDep of Browserify. That might also cause some issues at some point (npm shrinkwrap issue for us).

**Comment by cezary** [comment] 2015-12-25 19:47
I was running into problems bundling mapbox-gl-js into a webpack package (ridiculously long production build times when using dist/mapbox-gl-dev, dist/mapbox-gl was not working), so I made a [webpack-compatible branch](https://github.com/cezary/mapbox-gl-js/tree/webpack).

The main changes were using loaders to package the shaders and worker files. This might break a few things (first thing I noticed is documentation generation no longer works because of non-js dependencies).

**Comment by jingsam** [comment] 2016-01-23 14:30
Is there any progress to support webpack？

**Comment by lucaswoj** [comment] 2016-01-25 19:36
Any progress updates will be posted to this ticket. We would be thrilled to review a PR adding Webpack support by someone who uses and understands the platform.

**Comment by lafin** [comment] 2016-02-06 23:42
In related project I was able use mapbox-gl-js with webpack https://github.com/uber/react-map-gl/issues/21#issuecomment-180885489

**Comment by jingsam** [comment] 2016-02-25 12:29
I found a blog about it.
https://mikewilliamson.wordpress.com/2016/02/24/using-mapbox-gl-and-webpack-together/

It just works.
Thx Mike Williamson

**Comment by DenisCarriere** [comment] 2016-03-01 01:20
Thanks @sleepycat (Mike) for making this blog post!

**Comment by misterfresh** [comment] 2016-03-28 23:44
If you're having trouble getting it to work with the latest version (0.16 as of writing this) you can use [mapbox-gl-js-webpack](https://github.com/misterfresh/mapbox-gl-js-webpack) . I made small modifications to 3 source files though (shader loading and worker)...

**Comment by bensleveritt** [comment] 2016-03-29 14:51
@misterfresh This is very helpful.

Might want to consider setting up a way to inform users of your lib when/if your lib becomes deprecated.

**Comment by misterfresh** [comment] 2016-03-29 17:14
I'm using it for my project at the moment so I will probably update it
shortly after mapbox master is updated. I just made it a bit cleaner by
putting modified files in a separate folder using webpack aliases.

**Comment by eltoro** [comment] 2016-04-21 18:27
This finally worked for me for anyone using react 0.15, map box-gl-js 0.17 and ES6 import:

webpack.config.js

`module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'react-hot!babel',
        exclude: /node_modules/,
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      }
    ],
    postLoaders: [
      {
        include: /node_modules\/mapbox-gl/,
        loader: 'transform',
        query: 'brfs'
      }
    ]
  }`

**Comment by DenisCarriere** [comment] 2016-04-21 19:48
@eltoro I'm pretty sure this is a typo `son-loader` should be >> `json-loader`

**Comment by eltoro** [comment] 2016-04-22 11:15
Yep, thanks. I also added the resolve alias for webworkify-webpack. Without it the styles don't work. I can confirm that this setup is working for me.

**Comment by DenisCarriere** [comment] 2016-05-01 19:28
@eltoro Still having issues when using **mapbox-gl 0.18.0**. 

Google Chrome **Runtime Error**
```
use_program.js?6fd0:11Uncaught TypeError: fs.readFileSync is not a function
```

I've fixed it by adding another loader for `use_program.js`.

```js
loaders: [
  {
    test: /\.js$/,
    include: path.resolve(__dirname, 'node_modules/mapbox-gl/js/render/painter/use_program.js'),
    loader: 'transform/cacheable?brfs'
  }
...
```

**Comment by kislovskij** [comment] 2016-05-06 10:24
In my case webpack had trouble to resolve to mapboxgl using mapbox-gl **0.18.0**. I changed the import statement and now it works.

`import * as mapboxgl from 'mapbox-gl';`

Also I added a post loader in my webpack config.

`postLoaders: [
      {
        include: /node_modules\/mapbox-gl/,
        loader: 'transform',
        query: 'brfs'
      }
    ]`

**Comment by leontyr** [comment] 2016-05-16 00:37
Tried everything suggested but still getting the **Cannot find module 'mapbox-gl'** error. Could anyone please help?

`import * as mapboxgl from 'mapbox-gl';`

webpack.config.js

```
var path = require('path');
var webpack = require('webpack');
var merge = require('extendify')({
    isDeep: true,
    arrays: 'concat'
});
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var extractCSS = new ExtractTextPlugin('styles.css');
var devConfig = require('./webpack.config.dev');
var prodConfig = require('./webpack.config.prod');
var isDevelopment = process.env.ASPNET_ENV === 'Development';

module.exports = merge({
    resolve: {
        extensions: ['', '.js', '.ts'],
        alias: {
            webworkify: 'webworkify-webpack'
        }
    },
    module: {
        loaders: [{
            test: /\.ts$/,
            include: /ClientApp/,
            loader: 'ts-loader'
        }, {
            test: /\.html$/,
            loader: 'raw-loader'
        }, {
            test: /\.css/,
            loader: extractCSS.extract(['css'])
        }, {
            test: /\.json$/,
            loader: 'json-loader'
        }, {
            test: /\.js$/,
            include: path.resolve(__dirname, 'node_modules/mapbox-gl/js/render/painter/use_program.js'),
            loader: 'transform/cacheable?brfs'
        }, {
            test: /\.js$/,
            include: path.resolve(__dirname, 'node_modules/webworkify/index.js'),
            loader: 'worker'
        }],
        postLoaders: [{
            include: /node_modules\/mapbox-gl/,
            loader: 'transform',
            query: 'brfs'
        }]
    },
    entry: {
        main: ['./ClientApp/boot-client.ts']
    },
    output: {
        path: path.join(__dirname, 'wwwroot', 'dist'),
        filename: '[name].js',
        publicPath: '/dist/'
    },
    plugins: [
        extractCSS,
        new webpack.DllReferencePlugin({
            context: __dirname,
            manifest: require('./wwwroot/dist/vendor-manifest.json')
        })
    ]
}, isDevelopment ? devConfig : prodConfig);
```

**Comment by leontyr** [comment] 2016-05-16 19:41
I've figured out the problem. It's that I'm using Typescript and mapbox-gl doesn't support it...

**Comment by aidanlister** [comment] 2016-05-17 03:55
I can't get this working either, I've got the "fs" set to "empty" and the postLoaders ... I'm getting ```Uncaught TypeError: Cannot convert undefined or null to object```

In this chunk of mapbox code:

```
	var stringify = JSON.stringify;

	module.exports = function (fn) {
	    var keys = [];
	    var wkey;
	    var cacheKeys = Object.keys(cache);

	    for (var i = 0, l = cacheKeys.length; i < l; i++) {
	        var key = cacheKeys[i];
	        var exp = cache[key].exports;
```

**Comment by tmcw** [comment] 2016-05-17 15:53
Dear subscribed - I think I've crafted a webpack configuration / documentation for how you need to tweak webpack configuration that will work. I've tested it with v0.18.0 and it works correctly. Can you confirm or report specific errors, and then we'll get this integrated into our documentation so we can close this issue out?

https://gist.github.com/tmcw/405086f853560f8a017fefdcb949cb49

**Comment by leontyr** [comment] 2016-05-17 17:21
I also need to add the following for it to work.
```
node: {
    fs: "empty"
},
```
The problem for me now is that it only works (map showing) in the entry file of the webpack.config.js. It might due to the other settings in my project. Am I the only one having this problem?

**Comment by tmcw** [comment] 2016-05-17 17:24
@leontyr do you have the transform loader configured to use `brfs`? This configuration works without `fs: empty` for me, I'd assume because it's correctly using brfs. This is with webpack 1.13.0 and Mapbox GL JS 0.18.0

**Comment by leontyr** [comment] 2016-05-17 17:43
My bad. You are right, it doesn't need it. It's my other settings messed it up. 

I am trying to import mapbox-gl into a project generated by yeoman generator-aspnetcore-spa but can't get it to work properly...

**Closed** 2016-05-17 23:46 UTC
Labels: enhancement, seeking external contributions, testing & release process

**Comment by tsemerad** [comment] 2016-05-24 21:34
I'm getting `cannot resolve module 'gl'` after adding the settings laid out in the [example webpack config](https://github.com/mapbox/mapbox-gl-js/blob/master/webpack.config.example.js). Would this error be caused by the `postLoaders` entry not working, or the `'transform/cacheable?brfs'` loader not working? I updated the path to point to the proper location of `use_program.js`. I'm using Mapbox GL JS 0.18.0 and webpack 1.13.1.

**Comment by shanecav** [comment] 2016-05-25 00:15
@tsemerad I'm also using Mapbox GL JS 0.18.0 and webpack 1.13.1, but I am not having any issues building with webpack. Here's my webpack.config (only the relevant parts):


    module.exports = {
      resolve: {
        alias: {
          'webworkify': 'webworkify-webpack'
        }
      },
      module: {
        loaders: [
          {
            test: /\.jsx?$/,
            loaders: ['babel'],
            exclude: /node_modules/,
            include: __dirname
          },
          {
            test: /\.json$/,
            loaders: ['json']
          },
          {
            test: /\.js$/,
            include: path.resolve(__dirname, 'node_modules/mapbox-gl/js/render/painter/use_program.js'),
            loaders: ['transform/cacheable?brfs']
          }
        ],
        postLoaders: [
          {
            include: /node_modules\/mapbox-gl/,
            loader: 'transform',
            query: 'brfs'
          }
        ]
      },
    }

**Comment by ongle2** [comment] 2016-05-25 03:05
@leontyr There is a typed definition for mapbox-gl.js called [typed-mapbox-gl](https://github.com/dobrud/typed-mapbox-gl/tree/e5bdcf6a7bb28ae7d165384cc519d0fc5f6f0297)

**Comment by primozs** [comment] 2016-05-31 21:00
The published webpack config works but problem might be with the last version of webworkify-webpack. I had to downgrade from "webworkify-webpack": "1.1.0" to "webworkify-webpack": "1.0.6" to make it work again.

**Comment by tsemerad** [comment] 2016-05-31 22:16
I solved the `Cannot resolve module 'gl'` issue. It turns out my webpack config was setting some of the dependencies that Mapbox GL cares about as `externals`. Updating my `externals` to just a few explicit packages (rather than a function that was auto-generating a list of packages to add to `externals`) fixed it. Sorry for the confusion.

**Comment by infacq** [comment] 2016-06-03 08:49
if anyone can help me with this problem, I post a question here http://stackoverflow.com/questions/37608118/uncaught-typeerror-fs-readfilesync-is-not-a-function

**Comment by zhuang-hao-ming** [comment] 2016-06-04 05:09
i have tried all of the solutions above but not one works. i got the result 
`fs.readFileSync is not a function` and 
```
ERROR in ./~/.npminstall/mapbox-gl/0.18.0/mapbox-gl/js/render/painter/use_program.js
Module not found: Error: Cannot resolve module 'fs' in E:\test\05_18\map\bobomap\trunk\public\mapbox_textst_1\node_modules\.npminstall\mapbox-gl\0.18.0\mapbox-gl\js\render\painter
 @ ./~/.npminstall/mapbox-gl/0.18.0/mapbox-gl/js/render/painter/use_program.js 3:9-22
```
in the end.
can any one help me ?

my `webpack.config.js` shows that

```
module.exports = {    
    entry: './main.js',
    output: {
        path: './',
        filename: 'bundle.js',
    },
    resolve: {
        alias: {
            'webworkify': 'webworkify-webpack'
        }
    },
    module: {
        loaders: [{
            test: /\.json$/,
            loader: 'json-loader'
        }, {
            test: /\.js$/,
            include: path.resolve(__dirname, 'node_modules/mapbox-gl/js/render/painter/use_program.js'),
            loader: 'transform/cacheable?brfs'
        }],
        postLoaders: [{
            include: /node_modules\/mapbox-gl/,
            loader: 'transform',
            query: 'brfs'
        }]
    }
}
```

and my package.json shows that

```
{
  "dependencies": {
    "brfs": "^1.4.3",
    "json-loader": "^0.5.4",
    "mapbox-gl": "0.18.0",
    "transform-loader": "^0.2.3",
    "webpack": "1.13.1",
    "webworkify-webpack": "1.0.6"
  }
}
```

thanks

**Comment by jingsam** [comment] 2016-06-04 08:45
Add this：
```
node: {
    console: true,
    fs: 'empty'
  }
```

**Comment by zhuang-hao-ming** [comment] 2016-06-04 09:16
@jingsam if i add the code snippet you supply , a error `fs.readFileSync is not a function` shown in the browser console

**Comment by infacq** [comment] 2016-06-05 01:22
it also happen to me

**Comment by KendallPark** [comment] 2016-06-07 01:51
I am in the same boat as @zhuang-hao-ming and @infacq.

**Comment by jingsam** [comment] 2016-06-07 02:30
Webpack example was updated, check out this: https://github.com/mapbox/mapbox-gl-js/blob/master/webpack.config.example.js

**Comment by yuvadm** [comment] 2016-06-16 19:52
Things were working well for me, but after purging my `node_modules` directory and reinstalling all my dependencies (welcome to JS), I'm now getting this error https://github.com/borisirota/webworkify-webpack/issues/10

**Comment by dnlsandiego** [comment] 2016-07-08 14:45
@primozs Do you mind sharing the reason why downgrading "webworkify-webpack" to 1.0.6 worked with the published webpack config? I ran into the same issue and your comment fixed it. Maybe so it could be noted in the published webpack guide and config.

**Comment by primozs** [comment] 2016-07-08 20:26
Hi @dnlsandiego,
I did not go and check what was new, for now I just stayed at 1.0.6
Cheers

**Comment by jodo4x** [comment] 2016-07-21 03:45
@jingsam  I updated my `webpack.config.babel.js`. but the error persists.

my `webpack.config.babel.js` shows:
```js
import path from "path"

export default {
    context: `${__dirname}/src`,

    entry: "./client.js",

    output: {
        path: `${__dirname}/build`,
        filename: "./bundle.js"
    },

    resolve: {
        alias: {
            "webworkify": "webworkify-webpack"
        }
    },

    module: {
        loaders: [{
            test: /\.json$/,
            loader: "json"
        }, {
            test: /\.js$/,
            exclude: /node_modules/,
            loader: "babel"
        }, {
            test: /\.js$/,
            include: path.resolve('node_modules/mapbox-gl-shaders/index.js'),
            loader: "transform/cacheable?brfs"
        }],

        postLoaders: [{
            include: /node_modules\/mapbox-gl-shaders/,
            loader: "transform",
            query: "brfs"
        }]
    }
}
```

the error shows:

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'gl'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/jodo4x/ruli/mapbox-test-app/node_modules/mapbox-gl/js/util/canvas.js:6:10)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jodo4x/ruli/chain.blockmeta.com/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
[nodemon] app crashed - waiting for file changes before starting...
^C
```

and here is my `package.json`:
```json
{
  "name": "mapbox-test-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "watch": "webpack --progress --colors --watch",
    "serve": "nodemon --debug ./src/server.js --exec ./node_modules/.bin/babel-node",
    "start": "npm run watch & npm run serve"
  },
  "author": "ruli <jodo4x@gmail.com>",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.13.1",
    "echarts": "^3.2.2",
    "express": "^4.14.0",
    "mapbox-gl": "^0.21.0",
    "react": "^15.2.1",
    "react-dom": "^15.2.1",
    "react-redux": "^4.4.5",
    "react-router": "^2.6.0",
    "react-router-redux": "^4.0.5",
    "redux": "^3.5.2",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "babel-cli": "^6.11.4",
    "babel-core": "^6.11.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "json-loader": "^0.5.4",
    "transform-loader": "^0.2.3",
    "webpack": "^1.13.1",
    "webworkify-webpack": "^1.1.4"
  }
}
```

**Comment by dvreed77** [comment] 2016-08-04 01:02
I am having a little bit of a different issue.  I have a webpack-mapboxgl implementation that compiles and works, but there are **HUGE** blobs that are being generated and downloaded directly related to the number of maps I am creating.  Example is here: http://test.dvreed.com/fhr/.  I have 5 maps, and there are 15 huge blobs that are downloaded. They are each the same exact size at about 1MB, which match the size of the bundle.js.  Any help would be greatly appreciated.

```bash
->webpack --config webpack-production.config.js -p
Hash: b80ca238b8521f64996f
Version: webpack 1.13.1
Time: 49332ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  1.11 MB       0  [emitted]  main
bundle.js.map  9.15 MB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 896 hidden modules
```

Here is my production version of my webpack config
```javascript
// TO RUN:
// export NODE_ENV=production
// webpack --config webpack-production.config.js -p

var path = require('path');
var webpack = require('webpack');

module.exports = {
  devtool: 'source-map',
  entry: [
    './index'
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/'
  },
  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('production')
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      compressor: {
        warnings: false
      }
    })
  ],
  resolve: {
    alias: {
      'webworkify': 'webworkify-webpack'
    }
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        loaders: [ 'babel' ],
        exclude: /node_modules/,
        include: __dirname
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.js$/,
        include: path.resolve('node_modules/mapbox-gl-shaders/index.js'),
        loader: 'transform/cacheable?brfs'
      }
    ],
    postLoaders: [{
      include: /node_modules\/mapbox-gl-shaders/,
      loader: 'transform',
      query: 'brfs'
    }]
  }
};
```

**Comment by mike-marcacci** [comment] 2016-08-05 04:24
I've been meaning to post this here for a couple weeks now, but for anyone who forgot to shrinkwrap your deps or is adding `mapbox-gl-js` to a new project, the [`webworkify-webpack`](https://github.com/borisirota/webworkify-webpack) project has made some recent changes that break mapbox somehow (and like most people didn't actually follow semver).

I haven't had a chance to dive in yet, but *can* say that mapbox continues to work in webpack using `webworkify-webpack` version `1.0.6`, but fails in `1.1.x`.

**Comment by bensleveritt** [comment] 2016-08-05 04:32
@mike-marcacci I've actually found `webworkify-webpack@1.1.3` still works, but I too haven't had a chance to really delve into the details of why it stopped working.

This is the issue I raised here: https://github.com/mapbox/mapbox-gl-js/issues/2933
but ultimately it's probably more a webworkify-webpack issue.

**Comment by ReLrO** [comment] 2016-08-14 09:33
@dvreed77 This happens to me as well. I have similar settings to yours. Any luck finding the solution?

**Comment by dvreed77** [comment] 2016-08-14 11:18
@ReLrO No, I ended up using standard mapbox.js and everything works great now.  Mapbox GL was a little overkill for what I was trying to do, so it didn't bother me too much.

**Comment by ReLrO** [comment] 2016-08-14 11:29
@dvreed77 Ok thanks. I might take a look at it as well then. Do you think the problem is with Mapbox GL or with webpack?

**Comment by dvreed77** [comment] 2016-08-14 11:38
@ReLrO Not enough of an expert in either to say, sorry.  I think it might just be a config mistake I have.

**Comment by ReLrO** [comment] 2016-08-15 06:26
@dvreed77  I found a solution to the bug if you are interested. There is a memory leak in mabox-gl and its connection with webworkify. My solution involves modifying code both in mapbox-gl and in webworkify-webpack. 

Basically in webworkify-webpack you need to change the last lines of index.js to:

```
var objectUrl = URL.createObjectURL(
        new Blob([src], { type: 'text/javascript' })
    );
    var w = new Worker(objectUrl);
    w.objectUrl = objectUrl;
    return w;
```

Then in mapbox-gl/js/util/actor.js add 
`this.first = true;`
to the Actor constructor (lines 15 - 22) and in Actor.prototype.receive function add the following lines: 

```
if (this.first) {
        // revoke the Object URL that was used to create this worker, so as
        // not to leak it
        URL.revokeObjectURL(this.target.objectUrl);
        this.first = false;
    }
```
This removes the blob instead of keeping it in memory, which causes a memory leak. 

I also added this line:
`this.actors[i].target.removeEventListener('message', this.actors[i].receive);`
to the for loop in the remove function in mapbox-gl/js/util/dispatcher.js
to ensure the event listener is also removed once the map is removed. 

Hope this helps.

**Comment by dvreed77** [comment] 2016-08-15 13:03
@ReLrO Wow, great find!  Does anyone else know of this memory leak?  Should definitely do a pull a request in this case

**Comment by ReLrO** [comment] 2016-08-15 13:39
@dvreed77 I thought of it, but the fix depends on the modification of webworkify-webpack and until webworkify-webpack will change, the fix for mapbox-gl-js wont work...

**Comment by steinbachr** [comment] 2016-09-13 08:27
Weird error happening over here. Everything compiles just fine and is working great in all environments (Recent versions of Chrome + Firefox + Safari tested) EXCEPT for Safari v.8.0 (tested on 8.0.8 on desktop + iOS 8). When running on Safari v.8.x, the following error is surfaced:

`[Error] Error: webworkify-webpack: Could not locate module containing worker function! Make sure you aren't using eval sourcemaps and that you pass named functions to webworkify-webpack!`

*stacktrace*
```
perform (core.js, line 5)
batchedUpdates (core.js, line 5)
s (core.js, line 5)
r (core.js, line 5)
enqueueCallback (core.js, line 5)
setState (core.js, line 5)
(anonymous function) (2.6aa3fec414b8cd3371d7.bundle.js, line 9)
(anonymous function) ([native code], line 0)
s (core.js, line 2)
fireWith (core.js, line 2)
r (core.js, line 3)
(anonymous function) (core.js, line 3)
```

**Comment by steinbachr** [comment] 2016-09-15 06:39
in other browsers (this time chrome 34.0.1847.116) getting a different runtime error. Here's a better stacktrace from an un-minified bundle:

```
Uncaught TypeError: undefined is not a function 
5.chunk.js:27473
module.exports 5.chunk.js:27473
module.exports 5.chunk.js:27384
Dispatcher 5.chunk.js:27244
Style 5.chunk.js:17050
util.extend.setStyle 5.chunk.js:14942
module.exports 5.chunk.js:14503
VenueMapMapbox.createMap
```

the offending line being:
```
// find the first moduleId from the above list that contains fnString
var key = potentialFnModuleIds.find(function (moduleId) {
```

**Comment by WAHeisenberg** [comment] 2016-10-04 05:57
@aidanlister Hi there, I am facing the same issue, but didn't figure it out. Is yours resolved? Thanks!

**Comment by henningko** [comment] 2017-03-02 19:38
Has anyone gotten it to work with Webpack 2? → https://webpack.js.org/configuration/

Here's my non-working configuration
```javascript
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}
module.exports = {
  entry: {
    app: './src/main.js'
  },
  output: {
  ...
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'mapbox-gl': resolve('node_modules/mapbox-gl/dist/mapbox-gl.js'),
      'webworkify': 'webworkify-webpack'
    }
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        include: path.resolve(__dirname, 'node_modules/mapbox-gl/js/render/painter/use_program.js'),
        loader: 'transform/cacheable?brfs'
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /node_modules\/mapbox-gl/,
        loader: 'transform',
        enforce: 'post',
        query: 'brfs'
      }
    ],
  }
}```


Results in
```This dependency was not found:

* mapbox-gl in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Mapbox.vue```

**Comment by henningko** [comment] 2017-03-02 22:01
Solved it by removing the two loaders (just not in conjunction with UglifyJS, see below)

```javascript
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}
module.exports = {
  entry: {
    app: './src/main.js'
  },
  output: {
  ...
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'mapbox-gl': resolve('node_modules/mapbox-gl/dist/mapbox-gl.js'),
      'webworkify': 'webworkify-webpack'
    }
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      }
    ],
  }
}
```

However, building it with `UglifyJsPlugin` results in `Uncaught ReferenceError: n is not defined
` for the Mapbox component. Thoughts?

**Comment by stereobooster** [comment] 2017-04-30 10:14
In `create-react-app` project

```js
import mapboxgl from 'mapbox-gl';
```

I'm getting `Critical dependencies: 1:481-488 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results. @ ./~/mapbox-gl/dist/mapbox-gl.js 1:481-488`

**Comment by Paradzayi** [comment] 2017-05-02 06:52
I am using the default webpack configuration that comes with the [vuejs](https://github.com/vuejs/vue) project scaffolded using the [vue-cli](https://github.com/vuejs/vue-cli) together with the [webpack template](https://github.com/vuejs-templates/webpack). Mapbox works perfectly during development but when I build the project mapbox throws this error:
```Uncaught ReferenceError: e is not defined```.

My webpack file looks like this

```javascript
var path = require('path')
var utils = require('./utils')
var config = require('../config')
var vueLoaderConfig = require('./vue-loader.conf')

function resolve (dir) {
  return path.join(__dirname, '..', dir)
}

module.exports = {
  entry: {
    app: './src/main.js'
  },
  output: {
    path: config.build.assetsRoot,
    filename: '[name].js',
    publicPath: process.env.NODE_ENV === 'production'
      ? config.build.assetsPublicPath
      : config.dev.assetsPublicPath
  },
  resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
    }
  },
  module: {
    rules: [
      {
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        enforce: "pre",
        include: [resolve('src'), resolve('test')],
        options: {
          formatter: require('eslint-friendly-formatter')
        }
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test')]
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }
    ]
  }
}
```

Someone help please

**Comment by onehorsetown** [comment] 2017-05-02 23:30
@Paradzayi 

Try doing what @zezhipeng mentions here:

https://github.com/mapbox/mapbox-gl-js/issues/4359

```
module: {
     ...
     noParse: /(mapbox-gl)\.js$/,
     ...
}
```

It fixed the exact same problem for me:

**Comment by Paradzayi** [comment] 2017-05-03 12:13
@onehorsetown your solution works like charm. Thanks a lot 👍 👏 .

I had come up with a not so elegant work around. I added 

```javascript
module.exports = {
  ...
  externals: {
      "mapbox-gl": 'mapboxgl'
   }
  ...
}
```
to the webpack config file. I did this to prevent the mapbox-gl package from being bundled with webpack but I had to require it  in the index.html file using ```<script>``` tags.

**Comment by Nepomuceno** [comment] 2017-05-04 02:34
I end up doing just adding 
```
module.exports = {
  ...
  node: {
    fs: 'empty'
  },
  module: {
    rules: [
      {
        test: /node_modules.+js$/,
        loader: 'ify-loader'
      }
    ]
  }
  ...
}
```
and it woks using web pack 2.0 you need to add

**Comment by mitulgolakiya** [comment] 2018-05-25 10:42
We are using it with Angular 6 and getting an error. I'm not sure where should I added this. Any idea in which file(probably tsconfig.json) and in which block I should add it?

**Comment by eggp** [comment] 2018-07-03 21:17
@mitulgolakiya add angular json =>         "scripts": ["node_modules/mapbox-gl/dist/mapbox-gl.js"]

**Comment by bujoralexandru** [comment] 2023-12-05 08:57
Why is this issue marked as closed? There is not clear way of using this lib with, maybe, the most used js bundler out there.

**Comment by stepankuzmin** [comment] 2023-12-05 10:02
Hi @bujoralexandru,

We've outlined the possible solutions in the transpiling section of GL JS docs here https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling

We also have a test application that uses webpack, which loads and transpiles the Web Worker separately: https://github.com/mapbox/mapbox-gl-js/tree/main/test/build/transpilation

**Comment by bujoralexandru** [comment] 2023-12-05 10:21
Hi @stepankuzmin,

Thank you for the fast response 💯 !
I managed to make my project correctly build, using this approach 
![image](https://github.com/mapbox/mapbox-gl-js/assets/17970235/ab943f7f-68df-4768-a45d-2ba82c0acd2a)

One issue still remains: we lose the magic of typescript for the `mapboxgl` default import. Do you happen to know if there is a way to still obtain those types?
