### ISSUE TITLE
Layering glitches

### ISSUE THREAD

**Issue by severak** [mapbox/mapbox-gl-js#1994] opened 2016-01-26 14:54 UTC
It seems some labels are rendered in bad position.

See example ("Karlín" in upper right corner):

![screenshot176](https://cloud.githubusercontent.com/assets/615685/12583747/8434f7f0-c444-11e5-8398-bdbd73fe186c.png)

Used rendering style: [piknik_style.zip](https://github.com/mapbox/mapbox-gl-js/files/105058/piknik_style.zip)

**Comment by jfirebaugh** [comment] 2016-01-26 17:57
What version of mapbox-gl-js? This looks like #757, which was fixed in 0.12.3.

**Comment by lucaswoj** [comment] 2016-01-28 18:21
I was not able to reproduce this bug (using the provided style) using the latest version, v0.13.1. 

@severak if upgrading to v0.13.1 does not solve your issue, please create a demo page using jsfiddle or similar that demonstrates the bug.

**Closed by lucaswoj** 2016-01-28 18:21 UTC
