### ISSUE TITLE
Mapbox network request fails on zoom in/out

### ISSUE THREAD

**Issue by ali1059** [mapbox/mapbox-gl-js#12553] opened 2023-02-03 13:07 UTC
**mapbox-gl-js version**:
  "mapbox-gl": "^2.12.0",
  "@mapbox/mapbox-gl-draw": "^1.3.0",
  "@mapbox/mapbox-gl-geocoder": "^5.0.1",

**browser**:
    Chrome
### Steps to Trigger Behavior

 1.Once the map is loaded on the screen zoom in or zoom out
 2.On zoom it gives console error of Uncaught (in promise) DOMException: The user aborted a request.

### Link to Demonstration
<img width="1707" alt="Screenshot 2023-02-03 at 5 52 23 PM" src="https://user-images.githubusercontent.com/36314122/216610161-3a52e4d9-e669-475b-a9c3-8f8dfb5b7592.png">

<img width="1707" alt="Screenshot 2023-02-03 at 6 06 34 PM" src="https://user-images.githubusercontent.com/36314122/216610848-fe3b4932-ed3a-4cc6-ba73-3700eac5864f.png">

### Expected Behavior
Network requests fails on zoom in and out (Not on all requests but randomly)
### Actual Behavior
Network requests should not fail for any request and thre shold not be any console errors

**Comment by stepankuzmin** [comment] 2023-05-16 11:16
Hi @ali1059,

This is expected behavior since the Mapbox GL JS map aborts requests for the tiles that no longer need to be rendered. So, I will close the issue but feel free to reopen it if you have any questions.

**Closed by stepankuzmin** 2023-05-16 11:16 UTC
