### ISSUE TITLE
Strange error when initiating Mapbox GL in Webpack/Laravel Mix compiled as "npm run production"

### ISSUE THREAD

**Issue by mseymour** [mapbox/mapbox-gl-js#5795] opened 2017-12-04 03:33 UTC
I tried compiling my project's JS into minified production code today, and came across a strange error in multiple browsers: "Exception with thrown value: ReferenceError: Can't find variable: e"

There's no line numbers or filenames, it appears to be in a blob. From what I can gather, the line (from just looking at the formatted blob in Safari) is:

    }).call(this, t("_process"), void 0 !== e ? e : "undefined" != typeof self ? self : "undefined" != typeof window ? window : {})

This line appears to be from [Node Util](https://github.com/defunctzombie/node-util) from what I can figure out. So far, I have only traced the error back to constructing a `mapboxgl.Map` object. The constructor that I've used is:

    const map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v9',
      attributionControl: false,
      center: [-63.571389, 44.647778],
      zoom: 13,
    });

It is worth to note that when running `npm run dev`, the (un-minified) development code generated by Webpack works; when Webpack is used to minify code, that is when it breaks.

**Comment by jfirebaugh** [comment] 2017-12-04 22:08
Duplicate of #4359. See https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-303880888 for exact reason. Workarounds in https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-286277540 and https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-288001933.

**Closed by jfirebaugh** 2017-12-04 22:08 UTC

**Comment by mseymour** [comment] 2017-12-04 22:58
Oh, good. I searched and nothing came up since I didn’t think of looking for Uglify and Webpack. Thanks.
