### ISSUE TITLE
Font render error when recreate map

### ISSUE THREAD

**Issue by Buminta** [mapbox/mapbox-gl-js#3144] opened 2016-09-05 09:23 UTC
**mapbox-gl-js version**: v0.23.0.

Hi everybody, I'm had a problem with render styles map.
I'm using code:
```
mapboxgl.accessToken = '... My token';
var map = new mapboxgl.Map({
        container: 'map-container',
        style: '...My Style'
    });
```

For create a popup map view.
However, when i closed popup and re create new popup map view then all text for position label of map can't render font.
U can see it with image:

```The first create popup map view```
![screen shot 2016-09-05 at 4 13 25 pm](https://cloud.githubusercontent.com/assets/5722956/18243238/68fa9432-7384-11e6-8bd9-ca8a5797dee3.png)

```Re create popup map view```

![screen shot](https://cloud.githubusercontent.com/assets/5722956/18243747/c87fdc58-7386-11e6-85b9-5b18ae5c2a44.png)

Thanks for care that!!!

**Comment by jfirebaugh** [comment] 2016-09-05 20:26
Duplicate of #3086.

**Closed by jfirebaugh** 2016-09-05 20:26 UTC
