### ISSUE TITLE
Performance degradation from v0.27.0 in Chrome?

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#3856] opened 2016-12-23 00:59 UTC
**mapbox-gl-js v0.[27,28,29].0**:

### Steps to Trigger Behavior

 1. Go to http://codepen.io/anon/pen/ZBZrVK (using Chrome)
 2. Right click the map and start moving around bearing/pitch rapidly 

![rapid_movement](https://cloud.githubusercontent.com/assets/1205805/21444881/da31ab58-c8b2-11e6-923b-60003289e3c5.gif)

 3. Change version to v0.27.0, v0.28.0 or v0.29.0
 4. Repeat the same thing
 5. Try zooming in over a dense city, like New York, and repeat the same test - even more evident

### Expected Behavior
Roughly the same performance.

### Actual Behavior
In the higher versions the interaction starts to lag after a couple of seconds and then starts to freeze occasionally.

This happens on latest Chrome in OSX. I did not see the same behaviour in Safari or Firefox. It's also much more evident on more complex maps (like my own) where things become sluggish almost immediately after I pitch the map and start to move around. If I downgrade to v0.26.0 things get a lot better.

**Comment by mourner** [comment] 2016-12-23 12:16
Thanks for the report! This will need some deeper investigation... 

- Is the regression only apparent when changing pitch, but OK if you just pan/rotate/zoom on pitch=0?
- Does it help if you set `mapboxgl.workerCount = 7` before creating the map?

0.27 had a lot of rendering performance optimizations, but this looks more like a workerside regression (since label placement reruns on pitch/bearing changes). Maybe something related to #3404? I'll try to do some profiling and see if there are any evident patterns.

**Comment by averas** [comment] 2016-12-23 12:56
It's hard to get clear objective conclusions from interaction tests, but these are my subjective assessments:

- [X] Zooming in/out continuously with pitch=0 seems unaffected 
- [X] Rotating continuously with pitch=0 also seems affected (but perhaps less so)
- [X] Setting <code>mapboxgl.workerCount = 7</code> seems to have no effect
- [X] Setting <code>mapboxgl.workerCount = 1</code> seems to increase the performance of v0.29.0 significantly, but still not to the level of v0.26.0, and I steel get occasional freezes

I've created a new codepen with unnecessary elements removed and centered over manhattan. The differences are (for me) pretty obvious when rotating/pitching the map at that location when switching back and fourth between v0.26.0 and v0.29.0 (simply change version number in the script URL).

http://codepen.io/anon/pen/WoBeyN

**Comment by mourner** [comment] 2016-12-23 14:49
Thanks! Yeah, that looks like a regression of the `redoPlacement` routine. Investigating.

**Comment by mourner** [comment] 2016-12-23 16:31
Can't manage to find anything suspicious when profiling — results in both the main thread and the worker are very similar (except for much faster drawing in 0.27+). 

Could one of the refactorings possibly trigger more redoPlacement requests than were done previously? Should we throttle those requests? I know we avoided throttling before but this may be a valid use case. cc @ansis @jfirebaugh

**Comment by averas** [comment] 2016-12-23 18:03
> Can't manage to find anything suspicious when profiling

But you are able to reproduce the behaviour?

The more I fiddle around with this, the more it feels like something rather low level, perhaps even related to Chrome on OSX (Sierra in my case) specifically. When I rotate back and fourth over Manhattan I am able to freeze my entire MBP (my clock in the action bar stops updating) for up to several seconds (mouse pointer still moving).

**Comment by jfirebaugh** [comment] 2016-12-23 18:06
I'm not able to reproduce the behavior you're describing. Chrome 55.0.2883.95, MacBook Pro (Retina, 13-inch, Early 2015), Intel Iris Graphics 6100.

**Comment by averas** [comment] 2016-12-23 18:11
> I'm not able to reproduce the behavior you're describing.

That's disturbing...

 I'm on:
MacBook Pro (Retina, 15-inch, Late 2013) 2.3GHz i7 / 16GB
NVIDIA GeForce GT 750M 2048 MB
Intel Iris Pro 1536 MB

MacOS 10.12.2
Chrome 55.0.2883.95

**Comment by jfirebaugh** [comment] 2016-12-23 18:25
Oh, sorry, didn't notice that the codepen was the "before". Yes, I think I see what you're referring to. It has the feel of GC-related pauses.

**Comment by mourner** [comment] 2016-12-23 21:39
Yes, I'm seeing the increased stutter too, although it never reaches the complete "freeze" state @averas is describing.

@jfirebaugh could it be too much transferring going on, clogging the main thread? I'll try to make a custom 0.26 build with some console.logs to measure.

**Comment by averas** [comment] 2016-12-24 08:55
Some more observations..

I get the impression that occasional stutter and short freezes happen more often on v0.27.0-> during "regular interaction" as well, including 0 pitch zooming and panning. >0 pitch just seems to make it much more evident.

I am not able to provoke this behaviour on a fairly complex map without symbols: 

http://codepen.io/anon/pen/LbobeO

**Comment by averas** [comment] 2017-01-10 00:10
@mourner Any luck with your investigations? For me this issue has turned out to be seveer

**Comment by mourner** [comment] 2017-01-10 13:53
@averas I seem to have traced it down to reloading symbol data on the main thread after redoing placement in the workers. If you `return` at the beginning of `Tile` `reloadSymbolData` in master version, the performance seems to get back on par with 0.26. Now I'm trying to understand what exactly changed between 0.26 and 0.27 in terms of reloading symbol data.

**Comment by mourner** [comment] 2017-01-10 16:24
The bottleneck is somewhere on the GPU side and somehow related to the symbol drawing routine. When doing timeline profiling, 0.26 GPU frame duration is consistently 0-2ms while in master, it often reaches 100-200ms in many frames. I'll try to dig deeper with chrome://tracing.

**Comment by mourner** [comment] 2017-01-10 17:05
FINALLY FOUND IT! You won't believe how silly the fix is. Submitting a PR now.

**Comment by averas** [comment] 2017-01-10 17:14
@mourner Haha! As we say in Sweden "A small tuft often tumbles a big load..." .. ;-) Great work!

**Closed** 2017-01-10 17:47 UTC
Labels: performance
