### ISSUE TITLE
Fails to pan or zoom map in a touch enabled desktop device

### ISSUE THREAD

**Issue by shf123** [mapbox/mapbox-gl-js#4400] opened 2017-03-10 10:09 UTC
**mapbox-gl-js version**: 0.33.0

### Steps to Trigger Behavior

 1. Go to a mapboxgl map, for instance https://www.mapbox.com/mapbox-gl-js/examples/
 2. Try to pan or zoom the map by using touch

### Expected Behavior
The map pans and zooms, not the whole page

### Actual Behavior
The whole page scrolls or zooms.  I used an touch enabled Asus with Windows 10, and tested with the browsers IE11, Edge and Chrome.  In Chrome it worked a little better since the map also panned, in addition the the whole page.

When I tested the same in leaflet, I noticed that it has been fixed there. It worked like I wanted in Leaflet version 1.0.3, but not in the older 0.7.3.

**Comment by andrewharvey** [comment] 2017-03-10 21:10
Is this the same as #4349?

**Comment by shf123** [comment] 2017-03-13 08:28
@andrewharvey It looks like it is the same zoom issue, but that bug does not mention the panning issue.

When the map uses the whole page, the panning works better in Chrome (except when I pan left. It causes the browser to go back to the last page in the browser history).

**Comment by jfirebaugh** [comment] 2017-03-23 00:42
Closing as duplicate of #4259.

**Closed by jfirebaugh** 2017-03-23 00:42 UTC
