### ISSUE TITLE
oldTransition.declaration.json undefined

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#2529] opened 2016-05-04 21:37 UTC
**mapbox-gl-js version**: 0.17.0

### Steps to Trigger Behavior

1. Run a series of setStyles that update fill-pattern property 

### Expected Behavior

GL JS doesn't crash

### Actual Behavior

GL JS crashes with the error:  `Uncaught TypeError: Cannot read property 'json' of undefined`

On this line: https://github.com/mapbox/mapbox-gl-js/blob/71641ec32d37584c95b42e809815bfaa137afb82/js/style/style_layer.js#L290

**Comment by samanpwbb** [comment] 2016-05-04 21:45
Possibly the same as / related to https://github.com/mapbox/mapbox-gl-js/pull/2464, which was fixed in 0.18.0?

**Comment by lucaswoj** [comment] 2016-05-05 00:23
@samanpwbb Yes, this looks like #2464. Closing for now but please re-open if you can reproduce with v0.18.0

**Closed by lucaswoj** 2016-05-05 00:23 UTC
Labels: bug
