### ISSUE TITLE
[Feature Request] Provide Support for BigInt or string Ids in setFeatureState()

### ISSUE THREAD

**Issue by douglasg14b** [mapbox/mapbox-gl-js#10323] opened 2021-01-24 04:56 UTC
## Motivation

When working with a 64-bit key, such as that associated with a [H3 ](https://github.com/uber/h3) [index](https://h3geo.org/docs/core-library/h3indexing) you cannot guarantee `id` uniqueness as javascript only provides 53 bits of precision. In this case a BigInt or a string key needs to be used.

## Design Alternatives

Provide support for either `BigInt` types or for string keys (ie.  a hex string that represents a 64 bit number).

Alternatively new indexes could be formed that do not rely on the 64-bit keys, though this introduces extra memory & processing load on the client as a lookup table needs to be formed.

## Other

Currently using a `BigInt` results in:

> TypeError: Do not know how to serialize a BigInt

Using a hex string like: `8d28ae2088e3d3f` results in the function not actually changing anything

## Related Issues:

* https://github.com/mapbox/mapbox-gl-js/issues/10105
* https://github.com/mapbox/mapbox-gl-js/issues/7986

**Comment by mourner** [comment] 2021-01-25 16:21
Currently the workaround for this is to use a feature property together with a [`promoteId` source option](https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#vector-promoteId).

It should work with BigInt as reported in #9788, with the only known issue that it doesn't work with negative BigInt's, but that can be easily fixed.

**Comment by mourner** [comment] 2021-01-25 16:22
Closing as essentially a duplicate of #7020.

**Closed by mourner** 2021-01-25 16:22 UTC
