### ISSUE TITLE
use stackgl/headless-gl

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1447] opened 2015-08-31 17:01 UTC
Switch to https://github.com/stackgl/headless-gl for render tests

**Comment by mourner** [comment] 2015-08-31 17:05
Yes, was going to switch but let's wait until node-pre-gyp binaries are there. https://github.com/stackgl/headless-gl/issues/19

**Comment by jfirebaugh** [comment] 2015-08-31 17:08
We don't have node-pre-gyp binaries currently, and this probably unblocks #1197, so I think we should do it ASAP.

**Comment by mourner** [comment] 2015-08-31 17:25
We don't have binaries but it's compiled much faster. ANGLE takes a while to compile, but if it's fine, let's switch. Not sure if it fixes the layer-by-layer stuff though, I thought someone said it's probably not?

**Comment by ansis** [comment] 2015-09-01 05:28
I started working on this today: https://github.com/mapbox/mapbox-gl-js/commit/1f6299289ee3da1e39ff16988b64ed3c0c551029

A lot of render tests are failing.

I spent most of the day trying to figure out https://github.com/mapbox/mapbox-gl-js/issues/1449 but didn't have any luck.

**Comment by ansis** [comment] 2015-09-01 21:31
It looks like a lot of the other failing render tests could have the same cause as  https://github.com/mapbox/mapbox-gl-js/issues/1449

I extracted a test case and opened https://github.com/stackgl/headless-gl/issues/21

**Comment by mikolalysenko** [comment] 2015-09-04 19:22
Fixed that weird attribute bug, next step is getting prebuild modules up.

**Comment by mourner** [comment] 2015-09-07 10:56
Finally works for me! Pushed a branch with a working render suite to https://github.com/mapbox/mapbox-gl-js/tree/stacklgl-headless-gl-2.

```
91 failed, 123 passed assertions.
```

Pretty good! Some noticeable outstanding issues:

1. One of the `line-join` tests breaks the whole suite with "Abort trap 6" error, so had to disable them for now.
2. Some weirdness with line-caps as well: ![image](https://cloud.githubusercontent.com/assets/25395/9715280/842d60f4-5567-11e5-990b-532e89bee549.png)
3. All the text is rendered as black rectangles: 
![image](https://cloud.githubusercontent.com/assets/25395/9715313/bcb47d4a-5567-11e5-873b-757857bba27d.png)
4. All dashes don't render at all.

**Comment by mikolalysenko** [comment] 2015-09-21 18:40
Ok, I ran these test cases locally and everything passes on the [nan-v2 branch of headless-gl](https://github.com/stackgl/headless-gl/tree/nan-v2).  Unfortunately, I can't publish this yet since I am currently blocked by the following issue in nodejs/nan:

https://github.com/nodejs/nan/pull/459

**Comment by jfirebaugh** [comment] 2015-09-30 20:33
Current status: tests and test-suite pass locally (albeit with some missing fill antialiasing) but [fail in CI](https://circleci.com/gh/mapbox/mapbox-gl-js/1015) trying to compile the shaders:

```
/home/ubuntu/mapbox-gl-js/js/render/gl_util.js:31
            throw new Error(this.getShaderInfoLog(shader));
                  ^
Error: 0:2(1): error: syntax error, unexpected NEW_IDENTIFIER

    at WebGLRenderingContext.context.getShader (/home/ubuntu/mapbox-gl-js/js/render/gl_util.js:31:19)
    at WebGLRenderingContext.context.initializeShader (/home/ubuntu/mapbox-gl-js/js/render/gl_util.js:39:28)
    at Painter.setup (/home/ubuntu/mapbox-gl-js/js/render/painter.js:53:27)
    at new Painter (/home/ubuntu/mapbox-gl-js/js/render/painter.js:23:10)
    at util.extend._setupPainter (/home/ubuntu/mapbox-gl-js/js/ui/map.js:672:24)
    at new module.exports (/home/ubuntu/mapbox-gl-js/js/ui/map.js:91:10)
    at createMap (/home/ubuntu/mapbox-gl-js/test/js/ui/map.test.js:11:16)
    at Test.<anonymous> (/home/ubuntu/mapbox-gl-js/test/js/ui/map.test.js:25:19)
    at Test.bound [as _cb] (/home/ubuntu/mapbox-gl-js/node_modules/prova/node_modules/tape/lib/test.js:62:32)
    at Test.run (/home/ubuntu/mapbox-gl-js/node_modules/prova/node_modules/tape/lib/test.js:75:10)
```

**Comment by mikolalysenko** [comment] 2015-09-30 22:31
@jfirebaugh That is super weird, it might be an ANGLE bug.  I'll ping some of the devs on IRC and see if they know what is going on.

**Comment by mikolalysenko** [comment] 2015-09-30 22:33
Also, can you try pushing an instrumented version of the test case to CI so that it logs the contents of the shader program?  Having this information would help solve this problem.

**Comment by jfirebaugh** [comment] 2015-09-30 23:09
https://circleci.com/gh/mapbox/mapbox-gl-js/1022

It's failing on the first shader to be compiled, the debug fragment shader. The source being compiled is:

```
precision mediump float;uniform vec4 u_color;void main(){gl_FragColor=u_color;}
```

**Comment by jfirebaugh** [comment] 2015-10-06 16:35
https://github.com/stackgl/headless-gl/issues/26

**Comment by jfirebaugh** [comment] 2015-11-10 03:09
Status update: work here is happening in the `stacklgl-headless-gl-2` branch. The last version of headless-gl that I tried was `2.1.5`. Instead of the "error: syntax error, unexpected NEW_IDENTIFIER", there's an earlier error, when attempting to create the context:

```
/home/ubuntu/mapbox-gl-js/node_modules/gl/index.js:36
  var gl = new webgl.WebGLRenderingContext(
           ^
Error: Error creating WebGLContext
    at createContext (/home/ubuntu/mapbox-gl-js/node_modules/gl/index.js:36:12)
    at new Canvas (/home/ubuntu/mapbox-gl-js/js/util/canvas.js:20:20)
    at util.extend._setupContainer (/home/ubuntu/mapbox-gl-js/js/ui/map.js:658:24)
    at new module.exports (/home/ubuntu/mapbox-gl-js/js/ui/map.js:90:10)
    at /home/ubuntu/mapbox-gl-js/test/render.test.js:16:15
    at /home/ubuntu/mapbox-gl-js/node_modules/mapbox-gl-test-suite/lib/render.js:60:9
    at runOne (/home/ubuntu/mapbox-gl-js/node_modules/mapbox-gl-test-suite/lib/harness.js:64:13)
    at pop (/home/ubuntu/mapbox-gl-js/node_modules/mapbox-gl-test-suite/node_modules/queue-async/queue.js:24:14)
    at Server.<anonymous> (/home/ubuntu/mapbox-gl-js/node_modules/mapbox-gl-test-suite/node_modules/queue-async/queue.js:38:39)
    at Server.g (events.js:180:16)
```

https://circleci.com/gh/mapbox/mapbox-gl-js/1230

Digging in here will likely require either reproducing the error in a VM and debugging into native code to obtain more information about the failure, or instrumentation / better error reporting to headless-gl and rerunning on CircleCI.

**Comment by mikolalysenko** [comment] 2015-11-10 03:34
I wasn't able to get this to reproduce in circleCI when I tried it.  One thing to check is that if you are destroying contexts when you are done with them, since relying on the GC to pick them up could cause problems.

**Comment by jfirebaugh** [comment] 2015-11-10 18:17
The error occurs on the first attempt to create a context, so leaking contexts is probably not the issue.

I tried [not updating the mesa version](https://github.com/mapbox/mapbox-gl-js/commit/8881d0ee701a654fdf47c0b2d1f977e935c69f6b) and the build got a lot further:

https://circleci.com/gh/mapbox/mapbox-gl-js/1348

**Comment by jfirebaugh** [comment] 2015-11-10 18:21
Output from that last run looks really good. A lot of the discrepancies we saw between CI and OS X rendering are gone. There's just one failure, a tiny difference on circle-blur/literal:

![image](https://cloud.githubusercontent.com/assets/98601/11071268/c42aabe4-8794-11e5-8717-ffd4d4295b87.png)

**Comment by jfirebaugh** [comment] 2015-11-12 00:46
Merged in 9bbc3164cd080897b3184a168f15c3e3a56131d8. Filed some followup issues:

* https://github.com/mapbox/mapbox-gl-js/issues/1702
* https://github.com/mapbox/mapbox-gl-js/issues/1703
* https://github.com/mapbox/mapbox-gl-js/issues/1704

Thanks for headless-gl @mikolalysenko!

**Closed by jfirebaugh** 2015-11-12 00:46 UTC

**Comment by lucaswoj** [comment] 2015-11-12 00:53
This is huge! :tada:

**Comment by mourner** [comment] 2015-11-12 07:26
Amazing, finally!!! Was https://github.com/stackgl/headless-gl/issues/26 resolved or is it just not reproducible without mesa version upgrade?

**Comment by mikolalysenko** [comment] 2015-11-12 16:51
I think the issue was related to the mesa version.  I couldn't get it to reproduce on my CircleCI instance, so the downgrade must've fixed it.
