### ISSUE TITLE
Add loading animation for large layers

### ISSUE THREAD

**Issue by yoursweater** [mapbox/mapbox-gl-js#6178] opened 2018-02-15 21:50 UTC
Hi, I was wondering if there was a way to add some sort of loading animation to signal to users that a large layer is loading.

When I tried doing this the traditional way, it seemed that the addLayer function executes immediately (thus causing my .addClass('isLoaded') action to run instantly), without regard to how long it takes the actual layer to load. Is there some sort of callback method I can use on addLayer completion?

**Comment by bcartmell** [comment] 2018-02-16 17:39
I'm having a similar issue.

Listening for the 'data' event and checking event.isSourceLoaded works fairly well, but after removing and re-adding layers, event.isSourceLoaded doesn't seem to reset to false so it only works the first time.

Map.areTilesLoaded() also mostly works.  But if a tile fails for some reason, it never returns true.

It would be nice to have something to effect of areTilesLodedorFailed() to indicate that Mapbox is done trying to load the tiles, regardless of success or failure.

**Comment by mollymerp** [comment] 2018-02-17 00:10
@yoursweater depending on the exact behavior you want, you can add a listener to `data` or `render` and check if the map / source is loaded to turn off the animation.

for example: 
http://jsbin.com/taqexahefu/1/edit?html,output
 
> Map.areTilesLoaded() also mostly works. But if a tile fails for some reason, it never returns true.

@bcartmell this shouldn't be the case: `areTilesLoaded` should only return `false` if a tile has a state that is not `loaded` or `errored`

https://github.com/mapbox/mapbox-gl-js/blob/8a19f6079933817fd73eed71159130b8ac53a00f/src/ui/map.js#L1018

closing here because this is not a bug or a feature request. in the future please direct 'how do I...?' questions to [StackOverflow](stackoverflow.com/tags/mapbox-gl-js) or Mapbox support

**Closed by mollymerp** 2018-02-17 00:10 UTC
