### ISSUE TITLE
Rendering issues when antialias is enabled with terrain in iOS devices with 15.4 and M1 Macs with latest Safari

### ISSUE THREAD

**Issue by avpeery** [mapbox/mapbox-gl-js#11609] opened 2022-03-15 19:07 UTC
**mapbox-gl-js version**: Latest on main branch

**browser**: Safari 15.4, FireFox and Chrome on iPhone 12 Pro with 15.4 iOS

### Steps to Trigger Behavior

 1. Download iOS 15.4
 2. open debug/threejs-antenna.html
 3. Note immediate flickering of sky layer and severe performance issues with zooming or panning the map.

### Expected Behavior
No severe rendering issues should be noted. No flickering. Tested also with iPhone 11 with 14.6 iOS and iPhone 12 with 15.1 iOS, and MacBook Pro with Monterey 12.3 and they did not exhibit any issues. 

### Actual Behavior
When tested with iOS 15.4 on iPhone 12 Pro, severe rendering issues were noted on this testing page. See screen recording.

https://user-images.githubusercontent.com/42715836/158452806-c17361c9-b9ad-4c5f-b948-d7395fb8f37b.MP4

**Comment by rreusser** [comment] 2022-03-16 00:58
For reference, here was a previous issue containing a very similar issue: https://github.com/mapbox/mapbox-gl-js/issues/10372

Three.js and Mapbox both manage the same underlying WebGL state, and both maintain their own representation of that state in order to minimize actual WebGL state changes. This means as soon as either of them modify WebGL state, the other's representation will be incorrect.

That's why this line resets threejs's representation of state:

**Comment by rreusser** [comment] 2022-03-16 01:06
For reference, here was a previous issue containing a very similar issue: https://github.com/mapbox/mapbox-gl-js/issues/10372

Three.js and Mapbox both manage the same underlying WebGL state, and both maintain their own representation of that state in order to minimize actual WebGL state changes. This means as soon as either of them modify WebGL state, the other's representation will be incorrect.

That's why this line resets threejs's representation of state:

https://github.com/mapbox/mapbox-gl-js/blob/7e22ebffeee764c9ced805e84febe4e24b186851/debug/threejs-antenna.html#L126

and why this line sets Mapbox's representation to dirty after custom content is rendered: 
https://github.com/mapbox/mapbox-gl-js/blob/c9cd5d903499d3d9226f1e775a42ed937c2ae8de/src/render/draw_custom.js#L51

The result of the above was this PR which added a couple state resets which were missing: https://github.com/mapbox/mapbox-gl-js/pull/10412/files

I haven't tracked down a current reproduction of the above issue, but I just wanted to get some references linked since it looks quite similar. Didn't Safari switch their WebGL back end to metal recently-ish? Maybe that exposed a faulty assumption about default state values when transitioning back and forth between Three.js's and Mapbox's state maintenance.

**Comment by ryanhamley** [comment] 2022-03-16 20:00
To keep everything in one place, here's the [Webkit bug](https://bugs.webkit.org/show_bug.cgi?id=237918#c3) we filed and here's the [JSBin example](https://jsbin.com/mojuyosenu/edit?html,js,output) of the issue.

**Closed** 2022-03-18 20:41 UTC
Labels: bug :lady_beetle:, performance :zap:, environment-specific :desktop_computer:, release blocker :no_entry:, 3d :triangular_ruler:

**Comment by avpeery** [comment] 2022-05-26 22:07
Confirmed this issue is resolved in the latest 15.5 Safari release. https://bugs.webkit.org/show_bug.cgi?id=237918#c10
