### ISSUE TITLE
Archive (and host) previous versions of GL JS and style-spec docs

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5309] opened 2017-09-15 13:29 UTC
As @1ec5 puts it:
> We’ve done that for the iOS and macOS SDKs, so that people who are stuck on the previous version aren’t totally lost until they upgrade.
> Archived documentation is also helpful internally for finding out when a particular feature landed in the API

**Comment by andrewharvey** [comment] 2017-09-16 22:39
See https://github.com/mapbox/mapbox-gl-js/issues/2398

**Comment by jfirebaugh** [comment] 2017-09-18 17:50
Yeah, duplicate of #2398.

**Closed by jfirebaugh** 2017-09-18 17:50 UTC
Labels: docs
