### ISSUE TITLE
Camera movements along linestring

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#2441] opened 2016-04-14 07:53 UTC
`.flyTo` and `.easeTo` are totally my jam, though I've been seeing more frequent use cases for doing so to follow a moving marker-- usually in-car nav, or tracking some moving thing from just-above-the-driver's eye view.

It would be cool to feed in a linestring geometry --commonly provided by a routing query-- and

- automatically follow it at some configurable speed (would it be sacrilege if this were measured in mph/kph? the physical distance of a pixel is variable with zoom level)

- pivot the view to the proper bearing, to stay over (and behind) the driver's shoulder

- bonus: accept zoom/pitch/speed as geojson properties at certain junctures along the route, and interpolate between them. This might require geojson points instead of one linestring, as each feature can have only one set of props.

**Comment by mourner** [comment] 2016-04-14 08:17
I've been thinking about this too, also looking at camera flight algorithms that would make the movement smooth (without fast turns). I may take a stab at this later, likely involving [Centripetal Catmull-Rom Spline](https://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline).

**Comment by lucaswoj** [comment] 2016-04-14 19:27
What primitives would we need to expose to implement this feature as a plugin?

**Comment by lucaswoj** [comment] 2016-07-29 18:18
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/981

Related to #2801

**Closed by lucaswoj** 2016-07-29 18:18 UTC
Labels: enhancement
