### ISSUE TITLE
mapbox-gl v0.39.0 install error (mapbox-gl/src/style-spec)

### ISSUE THREAD

**Issue by CmdrShepardsPie** [mapbox/mapbox-gl-js#5033] opened 2017-07-24 15:34 UTC
Using Node 8.2.1, NPM 5.3.0. Installing mapbox-gl from official source:

```
"dependencies": {
    "mapbox-gl": "~0.39.0"
}
```

npm install fails with the following error:

> npm ERR! code ENOLOCAL
> npm ERR! Could not install from "node_modules/mapbox-gl/src/style-spec" as it does not contain a package.json file.

Rolling back to mapbox-gl 0.38.0 does not have this problem.

**Comment by mourner** [comment] 2017-07-24 15:44
Yep, duplicate of #5032

**Closed by mourner** 2017-07-24 15:44 UTC
