### ISSUE TITLE
Symbols on polygon sources are duplicated on high zoom levels

### ISSUE THREAD

**Issue by sroettering** [mapbox/mapbox-gl-js#6249] opened 2018-02-28 09:31 UTC
**mapbox-gl-js version**: 0.44.1

### Steps to Trigger Behavior

 1. Visit https://jsfiddle.net/9mdor1cu/6/ and click Run
 2. Zoom in to the white polygon
 3. Beyond a certain zoom level the "cat" image is duplicated

### Expected Behavior
Only one cat should be visible on the map as it is the case using a point source.

### Actual Behavior
The image/symbol seems to be duplicated when the zoom level is high enough.

Is this an intended behaviour? Is there a way to prevent this behaviour other than adding a multipoint source containing the centroids of my polygons?

**Comment by jfirebaugh** [comment] 2018-02-28 16:28
Hi @sroettering! Thank you for using GL JS. This issue is a duplicate of #5583, so I'm going to close this issue in favor of consolidating discussion on that ticket. There is more context on why this is happening in https://github.com/mapbox/mapbox-gl-js/issues/5583#issuecomment-341840524.

The suggested workaround is as you suggested, adding point data with the desired label placement.

**Closed by jfirebaugh** 2018-02-28 16:28 UTC
