### ISSUE TITLE
fill geojson source rendering breaks when we are too near from the shape

### ISSUE THREAD

**Issue by KevinGervais** [mapbox/mapbox-gl-js#9109] opened 2019-12-13 22:00 UTC
**mapbox-gl-js version**: latest

**browser**: all

### Steps to Trigger Behavior
 1. add a polygon source to a layer that has type fill (the polygon can be closed or opened doesn't matter)
 2. zoom near from the shape

When we are not too near from the shape, there is no problem:
<img width="815" alt="Capture d’écran, le 2019-12-13 à 16 51 42" src="https://user-images.githubusercontent.com/39884567/70834638-ddcbb100-1dc8-11ea-9f1d-a36349c88616.png">

Here There are holes in the shape when we zoom a little bit
<img width="922" alt="Capture d’écran, le 2019-12-13 à 16 54 39" src="https://user-images.githubusercontent.com/39884567/70834784-431fa200-1dc9-11ea-982b-75d8958bef11.png">

### Expected Behavior
No hole in the shape at any zoom level
### Actual Behavior
chape contains holes when we are too near from it

**Comment by ryanhamley** [comment] 2019-12-13 23:21
This looks similar to https://github.com/mapbox/mapbox-gl-js/issues/9085. I'm going to close this as a duplicate since there's no reproducible example and it looks like the same problem. If you can provide us with a reproducible example, that would be helpful.

**Closed by ryanhamley** 2019-12-13 23:21 UTC
