### ISSUE TITLE
Cannot read property 'transition' of undefined for GL JS 0.43 and 0.44

### ISSUE THREAD

**Issue by nbulaj** [mapbox/mapbox-gl-js#6080] opened 2018-01-29 14:06 UTC
Hi. We have a problem with Mapbox GL JS v **0.43** and **0.44**.

Sometimes (randomly or after browser cache invalidation) on page load we have next error:

> Uncaught TypeError: Cannot read property 'transition' of undefined
>    at Map._render (map.js:1484)
>    at map.js:1569

I take a look at the source code related to Exception:

> transition: util.extend({ duration: 300, delay: 0 }, this.style.stylesheet.transition)

So it seems to be a problem with the style, or what?

 ```js
mapboxgl.accessToken = 'token';

var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v9',
      center: [-73.985130, 40.758896],
      zoom: 17,
      minZoom: 8
 });

// disable map rotation using right click + drag
map.dragRotate.disable();

// disable map rotation using touch rotation gesture
map.touchZoomRotate.disableRotation();

map.addControl(new mapboxgl.NavigationControl());
```

Don't sure you can reproduce the problem through the JSBin, but if it can be helpful: https://jsbin.com/bemumefago/edit?html,css,js,output

**Comment by pmazamartin** [comment] 2018-02-06 13:59
I have the same issue. This error appeared after upgrade from 0.42 to 0.43 version.

**Comment by jliebrand** [comment] 2018-02-07 08:57
+1

**Comment by nbulaj** [comment] 2018-02-07 09:04
We made a small research and now we think that this issue is connected with map parent container `width` property. It it isn't defined or has some percentage value (not exact values in `px`), then this problem occurred.

@jliebrand @pmazamartin can you check it please?

**Comment by jliebrand** [comment] 2018-02-07 09:20
Not really, I've also been unable to reproduce this myself; it shows up in our client side exception logging though...

**Comment by jfirebaugh** [comment] 2018-02-13 00:23
Duplicate of #6043.

**Closed by jfirebaugh** 2018-02-13 00:23 UTC
