### ISSUE TITLE
map.transformRequest cannot set custom headers

### ISSUE THREAD

**Issue by jonseppanen** [mapbox/mapbox-gl-js#7365] opened 2018-10-05 01:28 UTC
Using postman I can send, e.g a jwt token in the header to my API.

I have a Slim 3 PHP 7 backend API and javascript web app front end.
I am pulling in the latest mapbox 0.49.0 script in the html front end.

This works perfectly in all instances.

Using mapbox transformRequest, I can set the keyname for the request but the value is always null.

As an example, if I set the following:

```
transformRequest: (url, resourceType)=> {
            return {
                url: url,
                headers: { 'jwt': id_token }
            }
        }
```

And I dump the received request to JSON on the server, this is what I get:

```
{"HTTP_HOST":["localhost"],"HTTP_CONNECTION":["keep-alive"],"HTTP_PRAGMA":["no-cache"],"HTTP_CACHE_CONTROL":["no-cache"],"HTTP_ACCESS_CONTROL_REQUEST_METHOD":["GET"],"HTTP_ORIGIN":["http:\/\/localhost:8080"],"HTTP_USER_AGENT":["Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3569.0 Safari\/537.36"],"HTTP_ACCESS_CONTROL_REQUEST_HEADERS":["jwt"],"HTTP_ACCEPT":["*\/*"],"HTTP_ACCEPT_ENCODING":["gzip, deflate, br"],"HTTP_ACCEPT_LANGUAGE":["en-GB,en-US;q=0.9,en;q=0.8"]}
```

The header should instead look something like this:

```
{"HTTP_JWT":["LONG_JWT_TOKEN_STRING"],"HTTP_CACHE_CONTROL":["no-cache"],"HTTP_POSTMAN_TOKEN":["7a1891d2-6c4d-4d47-b854-58738909c73b"],"HTTP_USER_AGENT":["PostmanRuntime\/7.3.0"],"HTTP_ACCEPT":["*\/*"],"HTTP_HOST":["localhost"],"HTTP_ACCEPT_ENCODING":["gzip, deflate"],"HTTP_CONNECTION":["keep-alive"]}
```

Is there some better documentation on how to do this somewhere? Am I not understanding the use case?

**Comment by mourner** [comment] 2018-10-05 13:35
@jonseppanen can you try the same but without Mapbox, using pure XmlHTTPRequest? With `xhr.setRequestHeader('jwt', id_token)`. I'm not sure what's wrong but may be some edge case with the way client/server is set up — Mapbox `transformRequest` doesn't do anything special beyond deferring to browser XHR implementation.

**Comment by mourner** [comment] 2018-10-08 10:59
Closing for now but will reopen if we can get an indication that this is on Mapbox side.

**Closed by mourner** 2018-10-08 10:59 UTC
Labels: needs information :pray:

**Comment by jonseppanen** [comment] 2018-10-09 23:57
I did as you requested, and the resource comes through perfectly.

It is 100% the transformrequest function. If I just set the 'url' portion the request works, but as soon as I put in a header value of any kind, mapbox itself wont send me the data for the map and gives a 403 error.

I have a feeling this is because the request is coming through as an OPTIONS request first (preflight) and mapbox is failing as a preflight request doesnt have the headers it is looking for.

Does mapbox actually handle preflight requests on their API?

**Comment by roman-HS** [comment] 2022-02-14 11:05
@jonseppanen I'm having this same issue when trying to add my header (with an `authorizationToken`) to a non-mapbox server. I'm using mapboxGL in the front-end. Somehow the header is sent without the token (even though Im consoling log the header just before the return)

Did you find any documentation on this issue? Something you can point me out to?

Thanks!

**Comment by miholzi** [comment] 2022-05-18 07:25
@roman-HS did you found a solution? I'am struggling with the same issue ... thanks

**Comment by ivan-palatov** [comment] 2022-10-17 06:14
@roman-HS have you figured it out? Having the same problem here, as I understand it, the issue is that transforRequest cannot change during runtime and only the very "instance" of it is used
