### ISSUE TITLE
Mapbox Studio: Data driven fill patterns trigger "Invalid GL JSON" Error.

### ISSUE THREAD

**Issue by SnailBones** [mapbox/mapbox-gl-js#7925] opened 2019-02-19 04:24 UTC
With code, it's possible to make data-driven fill patterns.
Example:
https://codepen.io/snailbones/pen/Nojxej

The same at first appears to be possible in the style editor however, it is not possible to publish the map, and this error messages repeatedly appears.

**browser**:
![screenshot_2019-02-18 studio](https://user-images.githubusercontent.com/14878684/52989786-378a6700-33c2-11e9-87c4-3f587a3932e7.png)

### Steps to Trigger Behavior

 1. Create a new style.
 2. Create tileset from GeoJson.
 3. Add tileset to style.
 4. Click "Pattern," then "Style across data range", and select some icons.
 5. Error message appears.
 6. Sometimes upon saving and returning to the map, the data-driven styles are gone.

**Comment by ryanhamley** [comment] 2019-02-19 19:22
cc @mapbox/studio

**Comment by dasulit** [comment] 2019-02-19 21:36
Thanks @SnailBones @ryanhamley— I cut a ticket in Studio's bug queue to track internally. Closing here as this is outside of gl-js's purview.

**Closed by dasulit** 2019-02-19 21:36 UTC

**Comment by pathmapper** [comment] 2019-02-20 18:14
@SnailBones you are using `"fill-opacity": .9` in your example. 

[gl-style-validate](https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec#gl-style-validate) fails for this fraction number without a leading `0`.

You could try `0.9` instead of `.9`, maybe this is the cause of the Studio error.
