### ISSUE TITLE
addLayer can add layers with same id 

### ISSUE THREAD

**Issue by yangdonglai** [mapbox/mapbox-gl-js#6099] opened 2018-02-06 02:59 UTC
**mapbox-gl-js version**: current master

### Steps to Trigger Behavior

 1. edit debug/image.html add code
```
var imageStyle = {
    "version": 8,
    "sources": {
        "image": {
            "type": "image",
            "url": "/test/integration/image/0.png",
            "coordinates": [
                [-122.51596391201019, 37.56238816766053],
                [-122.51467645168304, 37.56410183312965],
                [-122.51309394836426, 37.563391708549425],
                [-122.51423120498657, 37.56161849366671]
            ]
        }
    },
    "layers": [{
        "id": "background",
        "type": "background",
        "paint": {
            "background-color": "rgb(4,7,14)"
        }
    }, {
        "id": "image",
        "type": "raster",
        "source": "image"
    }]
};

var map = new mapboxgl.Map({
    container: 'map',
    minZoom: 14,
    zoom: 17,
    center: [-122.514426, 37.562984],
    bearing: -96,
    style: imageStyle,
    hash: false
});
// add below line
window._map = map;
```
 2. open image.html in browser.
 3.  open cosole and run below code 
```
_map.addLayer({
        "id": "image",
        "type": "raster",
        "source": "image"
    })
```

### Expected Behavior
error: duplicate layer id  image
### Actual Behavior
no error
![image](https://user-images.githubusercontent.com/17786362/35839757-2c8876ee-0b2d-11e8-86d3-ce456ef9d85c.png)

**Comment by yangdonglai** [comment] 2018-02-06 03:23
the problem cause of some code  where i am confused 
```
// file: src/style/style.js    
// function: addLayer()
//line: 534
        if (this._validate(validateStyle.layer,
            `layers.${id}`, layerObject, {arrayIndex: -1}, options)) return;
```
the arrayIndex is always -1 which cause the next code is useless
```
// file: src/style-spec/validate/validate_layer.js
// function: validateLayer()
// line: 27
    if (layer.id) {
        const layerId = unbundle(layer.id);
        for (let i = 0; i < options.arrayIndex; i++) {
            const otherLayer = style.layers[i];
            if (unbundle(otherLayer.id) === layerId) {
                errors.push(new ValidationError(key, layer.id, `duplicate layer id "${layer.id}", previously used at line ${otherLayer.id.__line__}`));
            }
        }
    }
```
i am confused of why the arrayIndex is an const value.

photo like below:
![image](https://user-images.githubusercontent.com/17786362/35840271-1efc0812-0b30-11e8-857f-72648f2f67a2.png)

**Comment by yangdonglai** [comment] 2018-02-06 03:38
@jfirebaugh

**Comment by yangdonglai** [comment] 2018-02-06 09:57
#5989 find same problem

**Comment by lbud** [comment] 2018-02-06 17:17
Thanks for your report @yangdonglai. Closing as duplicate of #5989.

**Closed by lbud** 2018-02-06 17:17 UTC
