### ISSUE TITLE
Using accumulation buffer

### ISSUE THREAD

**Issue by liebrand** [mapbox/mapbox-gl-js#1961] opened 2016-01-21 04:31 UTC
Slightly bizarre left field question this. But I'm trying to add a "wind layer" to my map. At the moment I've implemented this rather crudely by adding a canvas on top of my map. Whilst this "works", it's far from efficient. It also makes interaction with the map very difficult, as panning/zooming/etc would just be a nightmare.

Furthermore, the idea of using particles to show the wind practically begs for a webGL implementation. So I've been looking at the shaders and the various drawXXX painters.  This would obviously be a very custom fork of that code, but I was wondering if you think this is the right place to look for adding this?

Ie does it make sense to add a new drawer that (if possible??) uses the accumulation buffer to achieve nice particle trails?

Here's an example of my current canvas based solution:

http://savvy-navvy.com/s/images/wind.mp4

**Comment by averas** [comment] 2016-01-21 06:34
Not really based on Mapbox GL JS, but perhaps you can draw inspiration from https://github.com/cambecc/earth which looks quite similar to what you're doing. If you want inspiration for how to do it with WebGL a similar project can be found at https://github.com/blendmaster/geoid/tree/master/webgl

**Comment by lucaswoj** [comment] 2016-01-21 20:11
This is a duplicate of #281

**Closed by lucaswoj** 2016-01-21 20:11 UTC
