### ISSUE TITLE
Wrapping around globe - Missing Popup

### ISSUE THREAD

**Issue by stackTom** [mapbox/mapbox-gl-js#2780] opened 2016-06-23 04:59 UTC
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. create a popup
 2. pan the map around the world, until you are back at the starting position
 3. the popup is gone, until you pan back around the world an equal number of times in the opposite direction

### Expected Behavior
Popup remains on map
### Actual Behavior
Popup disappears until one "undos" the panning around the world by panning in the opposite direction.

The above causes issues with my popups after I use the flyTo method. Is this by design, or is this a bug?

**Comment by indus** [comment] 2016-06-23 06:17
@stackTom what I did to make this less annoying, is to reset the map *after* a move, like so
``` JS
map.on('moveend', (evt) => {
  var cntr = this.map.getCenter();
  if (cntr.lng < -180 || cntr.lng > 180)
    map.setCenter([(cntr.lng + 540) % 360 - 180, cntr.lat]);
  })
```
but that is *not* a real fix.

**Comment by stackTom** [comment] 2016-06-26 18:51
I will have to use that fix until this is fixed in mapbox gl. Is this confirmed to be a bug? I will leave this open in case it is, but someone with greater knowledge feel free to close it if it's not a bug.

**Comment by jfirebaugh** [comment] 2016-07-07 23:31
Duplicate of #2071.

**Closed by jfirebaugh** 2016-07-07 23:31 UTC
