### ISSUE TITLE
icons rendered incorrectly with non integer devicePixelRatio

### ISSUE THREAD

**Issue by jdeboer-geoplan** [mapbox/mapbox-gl-js#4986] opened 2017-07-17 15:00 UTC
Hi,

If you set the window device pixel ratio to a non integer number then the icon rendering is broken, looks like they get very squashed, sometime down to nothing.  This worked in 0.37.0 and is broken in release 0.38.0

window.devicePixelRatio = 1.3

mapboxgl.accessToken = 'pk.eyJ1IjoiZGliczQ4NyIsImEiOiJjaXh2eWFwbDMwMDF4MzJvNzRiYnN3c3d1In0.VmNU9iayNVgjca2o7B7PhQ';
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/dark-v9',
    center: [-103.59179687498357, 40.66995747013945],
    zoom: 3
});

strangely it works for 1.5 and 2.5

**Comment by jfirebaugh** [comment] 2017-07-17 16:09
Duplicate of #4928.

**Closed by jfirebaugh** 2017-07-17 16:09 UTC
