### ISSUE TITLE
Markers "jiggle" when panning the map in Safari.

### ISSUE THREAD

**Issue by ajfickas** [mapbox/mapbox-gl-js#3392] opened 2016-10-17 21:06 UTC
**mapbox-gl-js version**: 0.26.0
### Steps to Trigger Behavior

I see the issue using Safari Version 10.0 (11602.1.50.0.10).
I don't see the issue using Chrome Version 53.0.2785.143 (64-bit).
1. Pan a map with markers. I'm able to reproduce the issue here: https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/.
### Expected Behavior

Markers should pan smoothly with the map.
### Actual Behavior

Markers "jiggle" as the map is panned.

(I'm migrating an existing site from Mapbox Leaflet to GL, getting ready to release, and this looks to be a potential blocker for us, so interested in when a fix will be available and/or possible workarounds.)

**Comment by mourner** [comment] 2016-10-17 21:09
@mollymerp I remember us dealing with the issue of rounding on move, could we have regressed on this?

**Comment by jfirebaugh** [comment] 2016-10-17 21:15
I suspect this is a duplicate of #3273.

**Comment by ajfickas** [comment] 2016-11-10 23:58
Indeed, this looks like a duplicate of #3273. FWIW we decided to release as is and are planning to migrate to symbol layers. I'm good with closing unless you guys see anything further to investigate here.

**Closed** 2016-11-11 00:00 UTC
Labels: bug
