### ISSUE TITLE
Vector tile - line dash rendering issue

### ISSUE THREAD

**Issue by zsoooc** [mapbox/mapbox-gl-js#10436] opened 2021-03-08 12:34 UTC
I'm developing a MapBox GL-JS application (v1.13, but I triad also with v2) and I faced with a problem regarding line styles. I want to display railway lines in high zoom level (20-22). I have one source, with two layers. The first is a black line, the second one is a white, dashed line. It's important that the line geometries are long, so on the pictures, there are no connecting points.

The problem is the rendering quality. See the images below. The first is a view with pitch:60, the pitch of the second one is 0.

The source is vector tile published by GeoServer v2.18.0 but I tried with pg_tileserv too. The rendering quality is the same.

What do you think? Do you have any suggestions how to fix it? Or is it a bug?

This is my code:

map.addLayer({
  'id': 'railways',
  'type': 'line',
  'source': 'railways','source-layer': 'railways_osm',
  "paint": {
  'line-width':20,
  'line-color':   '#000000'
    }
});

map.addLayer({
  'id': 'railways2',
  'type': 'line',
  'source': 'railways','source-layer': 'railways_osm',
  "paint": {
  'line-width':15,
  'line-dasharray':[5,10],
  'line-color':   '#ffffff'
    }
});
![HwGWn](https://user-images.githubusercontent.com/19270270/110351871-8d77e900-8035-11eb-8607-bd7fa92f2173.png)
![YMrJD](https://user-images.githubusercontent.com/19270270/110351875-8e107f80-8035-11eb-835b-111a95e51333.png)

**Comment by asheemmamoowala** [comment] 2021-03-09 00:43
To help us diagnose this issue, could you take these same screenshots with tile boundaries enabled? . This can be done by setting `map.showTileBoundaries = true`

**Comment by mourner** [comment] 2021-03-15 14:34
Looks like this is a duplicate of #5395.

**Closed by mourner** 2021-03-15 14:34 UTC
Labels: needs information :pray:
