### ISSUE TITLE
Error with mapbox API /static/geojson showing extra contours.

### ISSUE THREAD

**Issue by AlbertCoca** [mapbox/mapbox-gl-js#9942] opened 2020-08-19 10:38 UTC
Hello,

First of all sorry for posting this error here I know it is not the most appropriate place but I did not find the right place to report an error for the mapbox API.

We are facing an error with the mapbox API `/static/geojson` since some days ago. The contours that the api show are not the ones expected, visualizing the same contours with others tools such as geojson.io we get the expected behavior. 

With other products from mapbox we also get the expected behavior but not with `static/geojson` endpoint.

We did even try with different accounts and the problem persists

**mapbox-gl-js version**:
unkown
**browser**:
firefox

### Steps to Trigger Behavior

 1. Follow the link with your access token and user name.

### Link to Demonstration
```
https://api.mapbox.com/styles/v1/[your username url]/static/geojson(%7B%22type%22:%20%22FeatureCollection%22,%20%22features%22:%20[%7B%22type%22:%20%22Feature%22,%20%22properties%22:%20%7B%22fill%22:%22DarkOrange%22,%22stroke-width%22:%221%22,%22fill-opacity%22:0.3%7D,%20%22geometry%22:%20%7B%22type%22:%20%22MultiPolygon%22,%20%22coordinates%22:%20[[[[15.97,%2037.0796],%20[15.9552,%2037.09],%20[15.93,%2037.0965],%20[15.9104,%2037.11],%20[15.89,%2037.1151],%20[15.8668,%2037.13],%20[15.85,%2037.1338],%20[15.83,%2037.1435],%20[15.7904,%2037.17],%20[15.77,%2037.1761],%20[15.7233,%2037.21],%20[15.71,%2037.2162],%20[15.63,%2037.277],%20[15.5948,%2037.31],%20[15.5781,%2037.33],%20[15.5653,%2037.37],%20[15.569856876061122,%2037.390713073005095],%20[15.55,%2037.398],%20[15.5106,%2037.43],%20[15.49,%2037.4381],%20[15.473718171091443,%2037.45223088495575],%20[15.47,%2037.4527],%20[15.4509,%2037.47],%20[15.43,%2037.4725],%20[15.4104,%2037.49],%20[15.408688928359975,%2037.49018452733373],%20[15.4087,%2037.49],%20[15.39,%2037.4707],%20[15.35,%2037.4738],%20[15.33,%2037.4819],%20[15.3207,%2037.49],%20[15.29,%2037.4994],%20[15.2792,%2037.51],%20[15.27,%2037.5139],%20[15.2325,%2037.55],%20[15.224787945658921,%2037.56977449831046],%20[15.211854728186374,%2037.578892416628605],%20[15.21,%2037.5795],%20[15.1994,%2037.59],%20[15.17,%2037.5975],%20[15.1574,%2037.61],%20[15.13,%2037.6165],%20[15.1164,%2037.63],%20[15.09,%2037.6357],%20[15.0757,%2037.65],%20[15.05,%2037.6555],%20[15.0096,%2037.69],%20[14.99,%2037.6929],%20[14.973,%2037.71],%20[14.972,%2037.75],%20[14.99,%2037.768],%20[15.07,%2037.7695],%20[15.09,%2037.7686],%20[15.11,%2037.7619],%20[15.1224,%2037.75],%20[15.15,%2037.7473],%20[15.169,%2037.73],%20[15.19,%2037.7287],%20[15.21,%2037.7177],%20[15.216202196137825,%2037.711577319197275],%20[15.227012162876782,%2037.7082262295082],%20[15.25,%2037.7038],%20[15.2639,%2037.69],%20[15.29,%2037.6862],%20[15.3064,%2037.67],%20[15.33,%2037.6671],%20[15.3481,%2037.65],%20[15.37,%2037.6475],%20[15.3896,%2037.63],%20[15.41,%2037.6281],%20[15.4349,%2037.61],%20[15.45,%2037.6085],%20[15.47,%2037.6],%20[15.48,%2037.59],%20[15.51,%2037.5821],%20[15.5221,%2037.57],%20[15.55,%2037.5628],%20[15.5629,%2037.55],%20[15.59,%2037.5426],%20[15.6026,%2037.53],%20[15.63,%2037.5226],%20[15.6426,%2037.51],%20[15.67,%2037.5031],%20[15.6831,%2037.49],%20[15.71,%2037.483],%20[15.7231,%2037.47],%20[15.75,%2037.4637],%20[15.7638,%2037.45],%20[15.79,%2037.443],%20[15.8031,%2037.43],%20[15.83,%2037.4222],%20[15.8423,%2037.41],%20[15.87,%2037.4018],%20[15.882,%2037.39],%20[15.91,%2037.3832],%20[15.9236,%2037.37],%20[15.95,%2037.3644],%20[15.9652,%2037.35],%20[15.99,%2037.3456],%20[16.0066,%2037.33],%20[16.03,%2037.3264],%20[16.0481,%2037.31],%20[16.07,%2037.307],%20[16.0891,%2037.29],%20[16.11,%2037.2875],%20[16.1331,%2037.27],%20[16.15,%2037.2679],%20[16.1778,%2037.25],%20[16.21,%2037.2402],%20[16.2209,%2037.23],%20[16.25,%2037.2236],%20[16.25,%2037.1899],%20[16.25,%2037.0714],%20[16.25,%2037.0539],%20[16.23,%2037.0584],%20[16.2187,%2037.07],%20[16.21,%2037.0903],%20[16.19,%2037.0976],%20[16.171368305324332,%2037.11187108528349],%20[16.15,%2037.1179],%20[16.1362,%2037.13],%20[16.11,%2037.1364],%20[16.0944,%2037.15],%20[16.07,%2037.1554],%20[16.0533,%2037.17],%20[16.03,%2037.175],%20[16.013,%2037.19],%20[15.99,%2037.1944],%20[15.9722,%2037.21],%20[15.96219864991882,%2037.21175699393318],%20[15.9835,%2037.19],%20[16.0159,%2037.15],%20[16.0423,%2037.11],%20[16.0485,%2037.09],%20[16.03,%2037.0705],%20[15.99,%2037.0733],%20[15.97,%2037.0796]]]]%7D%7D,%7B%22type%22:%20%22Feature%22,%22geometry%22:%20%7B%22type%22:%20%22Point%22,%22coordinates%22:%20[15.0663,37.4704]%7D,%22properties%22:%20%7B%22marker-size%22:%20%22small%22,%22marker-symbol%22:%20%22airport%22,%22fill-opacity%22:%200.2%7D%7D]%7D)/15,37.55,7.5,0,0/600x600?access_token=[your acess token]=false&attribution=false
```

https://jsbin.com/

### Expected Behavior
![image](https://user-images.githubusercontent.com/20433529/90620220-72b56280-e212-11ea-9390-d2b0bba8ac16.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/20433529/90620250-7e088e00-e212-11ea-817f-19f6e4aae5ea.png)

**Comment by mourner** [comment] 2020-08-19 15:26
@AlbertCoca thanks for the report! I've forwarded it to the Static API team and we can't seem to reproduce the issue with the URL provided, at least with the Streets style:

![image](https://user-images.githubusercontent.com/25395/90654202-cb075700-e248-11ea-9bf6-fe8fec588ed1.png)

Can you provide us with the style ID that was used to get the bugged version? If you can't mention it publicly, you can submit your issue through Tech Support (https://support.mapbox.com), which is the best place to report SDK issues like this.

I'm going to close the issue because it's not related to GL JS, but feel free to add more comments and I'll try to forward them.

**Closed by mourner** 2020-08-19 15:26 UTC
