### ISSUE TITLE
Map-wide variables

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#8404] opened 2019-06-28 01:02 UTC
## Motivation

Expressions can respond to three things (afaik): properties of the data, zoom, and temporary feature state of the data. But sometimes it would be helpful to respond to something map-wide, like a "dark mode" or whether a satellite basemap is present, or whether the user has requested large fonts.

## Design Alternatives

Currently, the way to handle this is to call `map.setPaintProperty` on each specific layer when that map-wide property changes. But that's not ideal, because it often means defining layer properties twice: once as initially shown, and then later when reset:

```
map.addLayer({ ... "line-color": "dark-green") })
...
on("basemapchange", () => map.setPaintProperty("my-lines", "line-color", "light-green")
```

## Design

Something like:

```
"line-color": ["case", ["variable", "dark-mode"], "dark-green", "green"]

map.setVariable("dark-mode", true)
```

**Comment by peterqliu** [comment] 2019-06-28 15:21
We used to have style classes, but removed them because they were hard to design for in Studio and the use case was perceived to be obscure. I've found them useful.

**Comment by asheemmamoowala** [comment] 2019-07-01 21:38
Duplicate of #7946

**Closed by asheemmamoowala** 2019-07-01 21:38 UTC
