### ISSUE TITLE
(156) TypeError: g.feature is undefined

### ISSUE THREAD

**Issue by Ccantey** [mapbox/mapbox-gl-js#3262] opened 2016-09-27 22:01 UTC
I have breaking changes when updating to 0.22.0 and beyond. It occurs on 'mousemove' when I try to use queryRenderedFeatures().  I think this only occurs when we pass the layers parameter into qRF().

It looks like you do to, as the following examples break down: 
https://www.mapbox.com/mapbox-gl-js/example/query-similar-features/
https://www.mapbox.com/mapbox-gl-js/example/using-box-queryrenderedfeatures/

However, this qRF() example works with geojson, so ?:
https://www.mapbox.com/mapbox-gl-js/example/hover-styles/

## Behavior
**0.21.0**:
Pass an array of many layers (some not yet added to map) into the query ->
```
map.on('mousemove', function (e) {
    map.queryRenderedFeatures(e.point, { layers: layersArray });
    map.getCanvas().style.cursor = (features.length) ? 'pointer' : '';
});
```
Result: If the `e.point` fell on any layer in layersArray everything works as expected 

**0.22.0**:
Pass an array of layers (some not yet added to map) into the query ->
```
map.on('mousemove', function (e) {
    map.queryRenderedFeatures(e.point, { layers: layersArray });
    map.getCanvas().style.cursor = (features.length) ? 'pointer' : '';
});
```
Result: !!Breaking!! 
**Fix**: make our layersArray a 1:1 match with rendered layers - just push layers to array as added

**0.23.0**:
Pass an array of many layers (only those added to map at init per 0.22.0 fix) into the query ->
```
map.on('mousemove', function (e) {
    map.queryRenderedFeatures(e.point, { layers: layersArray });
    map.getCanvas().style.cursor = (features.length) ? 'pointer' : '';
});
```
Result: This seems to work, then use map.on('click') to select a geography which calls map.setFilter()
Secondary Result: mousemove now !!breaking!! returning the same TypeError: g is undefined.

## error messages
It throws 100's of `TypeError: g is undefined` errors per mousemove (to the point of crashing FireFox). 

I didn't see anything glaring in the changelog, except maybe following `breaking changes` to 0.22.0 :

- Map#onError has been removed. You may catch errors by listening for the error event. If no listeners are bound to error, error messages will be printed to the console. #2852 

It is pretty low hanging fruit to change the cursor, but if its a larger issue with qRF() - that is a pretty important method - if this is the new expected behaivior could you please update your examples?

**Comment by lucaswoj** [comment] 2016-09-27 22:35
This looks like a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/3167. Please re-open with a demonstration if `master` still exhibits the bug.

**Closed by lucaswoj** 2016-09-27 22:35 UTC

**Comment by Ccantey** [comment] 2016-09-28 15:08
Agreed. This is nearly a word-for-wood duplicate of that thread.
