### ISSUE TITLE
symbol layer icon image repeated

### ISSUE THREAD

**Issue by hamzahaddougui** [mapbox/mapbox-gl-js#10725] opened 2021-05-28 16:26 UTC
Hi Community,

When i add symbol layer, the icon image get repeated over a polygon when zoom in like shown in picture below.
Thanks.
![icon_image_repetition](https://user-images.githubusercontent.com/58179098/120014307-305f5400-bfe2-11eb-874c-edc708817ac7.PNG)

**Comment by rreusser** [comment] 2021-06-01 16:31
@hamzahaddougui It's difficult to diagnose an issue from a single screenshot. Could you describe the details of the configuration or set up a minimal [JSFiddle](https://jsfiddle.net/) to demonstrate how the output differs from the expected result? Thank you!

**Comment by hamzahaddougui** [comment] 2021-06-01 18:32
@rreusser So first i created map sources, and to display this data i used a layer of type symbol as shown in image below.
![draw_scores](https://user-images.githubusercontent.com/58179098/120372915-0c6c7d00-c318-11eb-8c83-3f23d812c29d.PNG)
This layer loads an image and set scores based on some conditions based on some layer filters.
Finally to create this layer i used a function exported from a file like described in picture below.
![symbol_layer](https://user-images.githubusercontent.com/58179098/120373214-5ead9e00-c318-11eb-94c9-9d76c8ca9800.PNG)

**Comment by hamzahaddougui** [comment] 2021-06-01 18:37
@rreusser For every element for given source it adds score as expected, that means one icon image. But when you zoom in on respective polygon, meaning move from level x to level y, icon image gets repeated over that polygon like there's different elements.
Thanks.

**Comment by mourner** [comment] 2021-10-06 18:56
Closing since you didn't provide a reproducible live test case.

**Closed by mourner** 2021-10-06 18:56 UTC
Labels: needs information :pray:

**Comment by palhal** [comment] 2024-06-19 11:27
I'm having the same problem, but it is expected according to [this](https://github.com/mapbox/mapbox-gl-js/pull/2678#issuecomment-246721646) comment.

It seems that the only way is to pre-calculate the centroid on the server side, and add symbols (labels) to these points instead.
