### ISSUE TITLE
GeoJSON Sources with non-numeric IDs are missing their IDs in queryRenderedFeatures

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#6931] opened 2018-07-08 06:09 UTC
**mapbox-gl-js version**: 0.46.0

### Steps to Trigger Behavior
1. Create a GeoJSON Source with a Feature id which can't be converted to a number.
2. querySourceFeatures

### Link to Demonstration

http://jsbin.com/popijel/edit?html,console,output

Click on each marker and see how feature `1a` has no ID returned.

### Expected Behavior

Return Feature ID

### Actual Behavior

Only returns Feature ID's which can be converted into a number.

I tested this in http://mapbox.github.io/geojson-vt/debug/ and `geojson-vt` seems to be keeping the ids.

![selection_961](https://user-images.githubusercontent.com/117278/42417266-32812faa-82c9-11e8-9d79-63e52a4aab8c.png)

**Comment by mourner** [comment] 2018-07-08 20:59
Duplicate of #2716

**Closed by mourner** 2018-07-08 20:59 UTC
