### ISSUE TITLE
how to detect feature visibility when icon-allow-overlap is false?

### ISSUE THREAD

**Issue by rvijgen** [mapbox/mapbox-gl-js#2207] opened 2016-03-01 10:08 UTC
In the popup on click example https://www.mapbox.com/mapbox-gl-js/example/popup-on-click/
when I set "icon-allow-overlap": false, features disappear when you zoom out, as expected. However, they are still clickable. I would like to disable this to avoid popups appearing when a user accidentally clicks on an invisible feature.
Can this be done?

**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1.
 2.
 3.

**Comment by lucaswoj** [comment] 2016-03-01 18:35
Thanks for the bug report @rvijgen! This looks like a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2177.

**Closed by lucaswoj** 2016-03-01 18:35 UTC
