### ISSUE TITLE
Accessing webgl context in canvas source breaks map raster in specific hardware setup

### ISSUE THREAD

**Issue by gpbmike** [mapbox/mapbox-gl-js#5081] opened 2017-08-02 03:02 UTC
**mapbox-gl-js version**: 39.1

### Steps to Trigger Behavior

 1. Be on a very specific hardware setup (see notes)
 2. Add canvas source / layer
 3. Access webgl context of added canvas

### Expected Behavior

Canvas layer is added to map.

### Actual Behavior

Mapbox raster layers vanish.

### Notes

I built a nice [plotty](https://github.com/santilland/plotty) layer to throw on the map and it worked everywhere except on my product manager's laptop. 😢 Older hardware worked. Newer hardware worked. His specific hardware failed.

Specific hardware:
![image](https://user-images.githubusercontent.com/8754/28855478-d328d758-76f1-11e7-8a25-66116c657059.png)

I was able to procure a laptop with the same specs from IT to do some testing. Accessing the `webgl` context of the canvas layer being added to the map triggers the weird behavior.

Reduced test: https://codepen.io/gpbmike/pen/qXNPOM

![aug-01-2017 19-56-38](https://user-images.githubusercontent.com/8754/28855756-9a1028f2-76f3-11e7-96ae-182f120a1072.gif)

[Other webgl applications](https://www.chromeexperiments.com/webgl) run as expected.

I'm hoping that there's an another developer out there with this specific setup that can help out.

**Comment by jfirebaugh** [comment] 2017-08-02 14:02
Duplicate of #4262.

**Closed by jfirebaugh** 2017-08-02 14:02 UTC
