### ISSUE TITLE
Performance of style mutations not good enough for hover interactivity

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#2492] opened 2016-04-26 09:59 UTC
### Issue

Style mutations are expensive, and can be quite slow on mobile devices. When applying _new_ style mutations _faster_ than the worker is able to process an ongoing mutation, the _new_ mutation is queued and applied after the previous one has completed. 

This happens even when the same style `property` in the same `layer` is changed multiple times such as `setFilter('foo', [==, 'bar', 5])` followed by `setFilter('foo', [==, 'bar', 3])` followed by  `setFilter('foo', [==, 'bar', 11])` and so on...

If this process is repeated too quickly for an ongoing period in a performance constrained environment (mobile devices), browsers start freezing and crashing due to memory issues.

**Proposal:** New style mutations should be debounced, and only the latest change should be applied for a given layer and property.

**mapbox-gl-js version**: `earcut final` rebase 20th of April

### Steps to Trigger Behavior

1. Add layer `foo` to the map,
2. Run the map in a performance constrained environment (We're experiencing this on a range of devices around the performance level of iPhone5, Moto G2, Samsung S3)
3. Repeat style mutations quickly, for instance ` setFilter('foo', [==, 'bar', 5])` followed by `setFilter('foo', [==, 'bar', 3])` followed by  `setFilter('foo', [==, 'bar', 11])`..

### Expected Behavior

The map should apply the latest style mutation for a given mutation type and layer, and skip any previous queued mutations for the given layer and type to prevent the buildup of a "mutation backlog".

### Actual Behavior

The map queues and applies all mutations, quickly degrading the performance of the map and if mutations are continued, the browser crashes.

![skjermbilde 2016-04-26 11 55 03](https://cloud.githubusercontent.com/assets/5638107/14814269/e8a6bf4a-0ba5-11e6-9837-1efdafda180a.png)

**Comment by jfirebaugh** [comment] 2016-04-26 17:24
This is related to automatic batching. cc @mourner

**Comment by mourner** [comment] 2016-04-26 17:28
Hmm, this is actually pretty surprising since the current code is batching style mutations to happen once per frame — you can see how that works in [style.js](https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style.js).

Can you set up a minimal JSFiddle test case that reproduces the slowdown? That would make it easier to see what's going on in your case.

**Comment by lucaswoj** [comment] 2016-04-26 17:53
@kristfal, are you asking for mutations to be deduplicated such that if 10 calls to `setFilter` are made during one batch, only the final `setFilter` call is executed?

**Comment by mourner** [comment] 2016-04-26 18:05
@lucaswoj this is how it works currently, so there most be some catch here...

**Comment by filiphhh** [comment] 2016-04-26 20:07
Here is a JSFiddle that should illustrate the problem.
[JSFiddle](https://jsfiddle.net/filiphhh/9gtx5zds/4/). Try moving you mouse through the boxes and you'll see it leaving a long trail where it will retrace your mouse movements with highlighted graticule boxes. Furthermore if you'd listen to the mouse events you'll see that the callbacks execute directly clearly showing that the style updates are pushed to a queue.

**Comment by mourner** [comment] 2016-04-27 09:55
Thanks for a great test case!

> Furthermore if you'd listen to the mouse events you'll see that the callbacks execute directly clearly showing that the style updates are pushed to a queue.

They're not queued — they happen exactly once when you move from one cell to the other, and you can confirm this by putting `console.log` statements in key places such as `style.js` `setFilter` and `worker` `update layers`.

I found that the underlying problem is not batching updates, it's that even with proper batching, updating layers is too slow — on each such update, workers have to _reparse all GeoJSON tiles in view_ and repopulate all buffers.

@ansis @lucaswoj @jfirebaugh I'm not sure how to approach this. It's looking like `setFilter` paradigm for hover interactivity just can't be made fast by design. What are the alternatives?

**Comment by mourner** [comment] 2016-04-27 10:04
Here's how the worker profiler looks after a few hovers:

![image](https://cloud.githubusercontent.com/assets/25395/14848739/cfb8c6a4-0c77-11e6-957f-300bcc7a1e81.png)

The perf warning is "not optimized: optimized too many times" ([more info](https://github.com/GoogleChrome/devtools-docs/issues/53#issuecomment-145192013)).

**Comment by filiphhh** [comment] 2016-04-27 11:22
@mourner Not to push some other framework, but for the use cases where I've had problems with setFilter being too slow I've personally resorted to projecting the coords to pixel coords and creating an SVG layer for the feature on the fly in my mousemove callback with D3, a la [https://bl.ocks.org/shimizu/5f4cee0fddc7a64b55a9](https://bl.ocks.org/shimizu/5f4cee0fddc7a64b55a9). This is fast enough to be able to hover over the features without a noticable delay. While I am not recommending that as a solution, doing something similar may be an acceptable workaround (Drawing the feature to a canvas). If it would be possible to fire an event when the setFilter has finished updating all the layers one could choose not doing any new setFilters until the first one is finished which would at least prohibit the "queue" effect.

**Comment by averas** [comment] 2016-04-27 16:58
@filiphhh I sometimes also fallback to d3/SVG, but in the case of mapbox-gl that has so far mostly been related to dynamic styling. Couldn't you achieve a setup similar to what you describe with two separate sources? One for the backdrop and one that you update with only the features shown when hovering? In that case the expensive parsing @mourner mentions does not have to happen and you make full use of geospatial indexes for the hovering. The most expensive bit is the setData() call on the second source, especially if the GeoJSON is large/complex, but I've used this approach with up to tens of thousands of features with reasonable performance.

I have several use cases involving filtering where I use this technique instead of setFilter(), such as:

![filters](https://cloud.githubusercontent.com/assets/1205805/14860578/ca0160b8-0ca9-11e6-867e-6d6aee6d1d60.gif)

**Comment by averas** [comment] 2016-04-27 17:19
I forked your example and updated it with the approach I suggested.. and yes.. the performance gain is huge..

https://jsfiddle.net/oyjLzfq4/1/

**Comment by mourner** [comment] 2016-04-27 17:24
@averas whoa, that looks fantastic — thank you for chiming in!

It seems that there's nothing immediately actionable in this ticket besides general optimizations of tile parsing, so I'm going to close this while keeping a very similar ticket open: #2443

**Closed by mourner** 2016-04-27 17:24 UTC
Labels: needs clarification, performance

**Comment by andrewharvey** [comment] 2016-06-22 11:18
I ran into this issue today originally using the setFilter approach but now swapping this out with the approach from @averas at https://github.com/mapbox/mapbox-gl-js/issues/2492#issuecomment-215156593. It's still not perfect (the hovered feature lags behind the cursor on slow machines or if you move the cursor really fast, or with many tiny polygons), but it seems better than the setFilter approach.

Perhaps the example at https://www.mapbox.com/mapbox-gl-js/example/hover-styles/ should be changed?

**Comment by andrewharvey** [comment] 2016-07-05 09:38
> EDIT: I think I spoke too soon. The GeoJSON setData approach doesn't really work at tile boundaries because queryRenderedFeatures geometry objects are clipped to tile boundaries.

The can be worked around using map.querySourceFeatures to try to collect all the tile clipped geometries for the feature and using turf.union to join them back together. A bit of a hack, but it mostly works.

**Comment by Scarysize** [comment] 2016-09-29 13:42
Would be nice to add a section into the docs for @averas solution. This issue is buried pretty deep here, though this is a relatively common problem.

**Comment by lucaswoj** [comment] 2016-09-29 17:22
@Scarysize What do you think the best way to surface this would be? We've got the docs, examples, and [guides](https://www.mapbox.com/help/mapbox-gl-js-fundamentals/)

**Comment by Scarysize** [comment] 2016-09-30 07:52
We did have the issue in an situation exactly like this: https://www.mapbox.com/mapbox-gl-js/example/hover-styles/ and additionally with a point overlay (geojson) with ~5k points. I guess the latter one is the more extreme, so I would recommend an **example** with a lot of point features which can be hovered.
