### ISSUE TITLE
Warping and tearing along tile boundaries

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#1575] opened 2015-09-30 22:31 UTC
In Safari on iOS 9.0 (and presumably any other browser on iOS), there’s a lot of warping and tearing at tile boundaries:

![n1st](https://cloud.githubusercontent.com/assets/1231218/10207699/e6594a18-6782-11e5-9e09-aa09bab46bf9.PNG)  
_Between 18/5288/12713 and 18/5288/12714_

![hedding](https://cloud.githubusercontent.com/assets/1231218/10207821/afb5954c-6783-11e5-88b0-e371bf0feb3c.PNG)  
_Between 18/5287/12713 and 18/5287/12714_

![mcentee](https://cloud.githubusercontent.com/assets/1231218/10207875/1d86c2c6-6784-11e5-9d37-bd0bdd9b1226.PNG)
_Between 18/5287/12714 and 18/5288/12714_

Often, after zooming in and out, the nearby park morphs into a different shape in a slow animation.

This issue does not affect GL JS in either Firefox 43 or Safari 9.0 on OS X 10.10. However, GL JS in all browsers (as well as the Mapbox iOS SDK) all show one-way arrows pointing in the wrong direction along the tile boundaries, due to very slight offsets at the tile seams: mapbox/mapbox-gl-js#1461 mapbox/mapbox-gl-native#2474.

/cc @jfirebaugh @kkaefer @mourner

**Comment by 1ec5** [comment] 2015-10-07 19:54
I’m seeing pretty much the same tearing in Firefox Developer Edition 43.0a2 (2015-10-06) on OS X 10.10.5, and it’s exacerbating #1461 because the road actually does go the wrong way:

![20/39.09719/-84.51781](https://cloud.githubusercontent.com/assets/1231218/10349174/09a65c44-6cf2-11e5-8d3d-f49e137d227c.png)

![20/39.09603/-84.50683](https://cloud.githubusercontent.com/assets/1231218/10349202/26e5685e-6cf2-11e5-8978-ccaa71548d4e.png)

Notice also how debug mode’s red lines don’t line up. Labels placed along lines also have some warping, but not nearly as bad as in MobileSafari:

![20/39.09603/-84.50709](https://cloud.githubusercontent.com/assets/1231218/10349247/54efa5ca-6cf2-11e5-8645-adb509d67f5f.png)

![20/39.09607/-84.50663](https://cloud.githubusercontent.com/assets/1231218/10349260/669cf5ac-6cf2-11e5-813e-10e8e6dfdd61.png)

**Comment by lucaswoj** [comment] 2015-12-18 20:15
The actual gap in the road does not exist anymore but the shearing sometimes does. There exists a good test case at `19.01/39.09703/-84.51780/-33.4`. 

![image](https://cloud.githubusercontent.com/assets/281306/11906259/0caac620-a580-11e5-82e4-4e87336ac983.png)

**Comment by 1ec5** [comment] 2015-12-18 20:24
Note also the warping in road labels (such as “2nd St”) around those shears.

**Comment by lucaswoj** [comment] 2015-12-19 00:04
This problem seems to be specific to highly overzoomed tiles.

**Comment by mourner** [comment] 2015-12-19 01:24
> This problem seems to be specific to highly overzoomed tiles.

Well this explains everything. What actually happens is that because we have buffered tiles, the same line has different endpoints in both tiles due to clipping, but you only start to actually see this on high overzooms when the coordinate rounding becomes more prominent.

The only way to fix this is switching to bufferless tiles with corresponding rendering changes, but it will take a while before we can tackle this.

**Comment by lucaswoj** [comment] 2016-02-04 22:20
@ansis has suggested that #1980 might fix this bug :+1:

**Comment by ansis** [comment] 2016-03-21 23:24
I think this should be fixed between https://github.com/mapbox/mapbox-gl-js/pull/2117 and https://github.com/mapbox/mapbox-gl-js/pull/1980

@1ec5 can you reproduce any of these bugs with the latest release version?

**Closed** 2016-03-31 17:15 UTC
Labels: bug
