### ISSUE TITLE
Only partial rendering on older hardware?

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1057] opened 2015-03-05 13:25 UTC
https://www.mapbox.com/mapbox-gl-js/examples/ "A simple map" displays fine on my home computer, latest core i7. At work on an old Core 2 Duo I see this : 

![mapbox_issue](https://cloud.githubusercontent.com/assets/2299642/6505535/82e5a4f6-c343-11e4-96b6-aa5b5c150cf5.jpg)

**Comment by ansis** [comment] 2015-03-05 18:55
hmm, could you paste all the information from https://www.browserleaks.com/webgl on your older machine?

**Comment by misterfresh** [comment] 2015-03-06 09:37
browserleaks info :
![webgl1](https://cloud.githubusercontent.com/assets/2299642/6523091/b2eadc94-c3ec-11e4-8808-3dbf47293bb2.gif)
![webgl2](https://cloud.githubusercontent.com/assets/2299642/6523101/c50e147c-c3ec-11e4-9599-d194e4266176.gif)

**Comment by willylambert** [comment] 2015-04-21 09:03
Got exactly the same issue on a HP EliteBook with a core i5.
![image](https://cloud.githubusercontent.com/assets/216868/7248791/f4ba67f0-e815-11e4-8dc4-7d4526ce5965.png)


My browserleaks info :
![image](https://cloud.githubusercontent.com/assets/216868/7248758/b3612ad2-e815-11e4-844b-221ee4a553fd.png)

![image](https://cloud.githubusercontent.com/assets/216868/7248768/c2b52dbc-e815-11e4-9b2a-0b7e02798862.png)

**Comment by jfirebaugh** [comment] 2015-10-17 00:48
Likely duplicate of #930.

**Closed by jfirebaugh** 2015-10-17 00:48 UTC
