### ISSUE TITLE
There is transformation issue when using 3857/web_mercator format

### ISSUE THREAD

**Issue by sabit990928** [mapbox/mapbox-gl-js#10969] opened 2021-08-27 11:04 UTC
Let me explain what problem I'm currently facing

On the server we have wkb_geometry data in epsg 3857 format. In the front we have mapbox config as below:
```
const mapConfig = {
  minzoom: 0,
  maxzoom: 22,
  tileSize: 256,
  style: {
    version: 8,
    sources: {
      'carto-light': {
        type: 'raster',
        tiles: [
          'https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}@2x.png',
          'https://b.basemaps.cartocdn.com/light_all/{z}/{x}/{y}@2x.png',
          'https://c.basemaps.cartocdn.com/light_all/{z}/{x}/{y}@2x.png',
          'https://d.basemaps.cartocdn.com/light_all/{z}/{x}/{y}@2x.png',
        ],
      },
    },
    layers: [
      {
        id: 'carto-light-layer',
        source: 'carto-light',
        type: 'raster',
      },
    ],
  },
}
```
For some reason there some translation/transformation issue as in the screen below:
<img width="815" alt="Screen Shot 2021-08-26 at 16 48 58" src="https://user-images.githubusercontent.com/37778327/131117563-cfb92ecc-0d3b-40d6-9fb6-e6ff8f58da0c.png">

In the docs I read that to straightly use 3857 format you should use source type as a vector. Could setting of source type as raster be a reason? As you can see the data is showing fine. It's better when you zoom in and getting worse when you zoom out
Is there someone who faced to such an issue?

**Comment by karimnaaji** [comment] 2021-08-30 15:55
The link you provided require me to create an account on your platform, is there any way to reproduce this in a self-contained environment and simplified version of what you are experiencing? [https://jsfiddle.net/](https://jsfiddle.net/) works well for bug report examples.

**Comment by sabit990928** [comment] 2021-08-30 16:01
> The link you provided require me to create an account on your platform, is there any way to reproduce this in a self-contained environment and simplified version of what you are experiencing? https://jsfiddle.net/ works well for bug report examples.
@karimnaaji 
Okay, I'll try to represent it in jsfiddle or smth else
For now I want to change base layer to another source to make sure that not matching there too. I'll give you information after that. Also I just transformed data in the backend to 4326 format

**Comment by karimnaaji** [comment] 2021-09-23 18:08
Closing this ticket due to lack of information.

**Closed by karimnaaji** 2021-09-23 18:08 UTC
Labels: needs information :pray:
