### ISSUE TITLE
When ignoring collision boxes outside of visible screen map panning can get ugly

### ISSUE THREAD

**Issue by watbywbarif** [mapbox/mapbox-gl-js#6489] opened 2018-04-10 09:33 UTC
**0.44.2 but then reproduced this with official streets-v9 and older 0.43.0**:

### Steps to Trigger Behavior

 1. Use https://api.mapbox.com/styles/v1/mapbox/streets-v9.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#12.1/37.85635/-122.31402
 2. Pan map up and down between Oakland and Albany.
 3. You can get too many labels drawn that quickly disappear in fraction of second, but it looks ugly

### Expected Behavior
I will not post images, as number of labels thins out obviously when tried.
### Actual Behavior
![image](https://user-images.githubusercontent.com/2914274/38548238-92c61cf8-3cb1-11e8-9603-cf7399588d53.png)
![image](https://user-images.githubusercontent.com/2914274/38548310-c008cf4e-3cb1-11e8-9548-a45e5bc11f65.png)

I have achieved even worse results with my own data and style:
![image](https://user-images.githubusercontent.com/2914274/38548506-440bc486-3cb2-11e8-8180-d7f8f196c3de.png)

I guess this is example is overblown because data in .mvt contains too much data for that zoom level, but as this can be reproduced in streets-v9 i am posting it.

When used `map.showCollisionBoxes = true` it seams to me that collisions are ignored while labels are outside of visible rectangle, but then when panning occurs labels are drawn before collisions are reevaluated.

**Comment by anandthakker** [comment] 2018-04-13 14:01
This is due to an intentional tradeoff we made as part of [this major overhaul of symbol placement](https://github.com/mapbox/mapbox-gl-js/pull/5150):

https://github.com/mapbox/mapbox-gl-js/blob/13ea16df5eabc4c8867d69e81da180cdcd6cc6b2/src/symbol/placement.js#L51-L54

https://github.com/mapbox/mapbox-gl-js/blob/13ea16df5eabc4c8867d69e81da180cdcd6cc6b2/src/symbol/placement.js#L200

@nickidlugash @ChrisLoer @ansis am I right in understanding that this behavior is essentially "works as intended"?

**Comment by ChrisLoer** [comment] 2018-04-13 17:03
> @nickidlugash @ChrisLoer @ansis am I right in understanding that this behavior is essentially "works as intended"?

The "skip fade" logic is actually for items that _have_ been placed/collided, just while they were offscreen. It looks like what @watbywbarif is seeing is features entirely outside the collision index range getting placed, and then sticking around until the next placement happens (it'll happen as they get pulled on screen, but it takes time for them to fade out so you can still see all the overlap for a bit). That's actually a known issue (#5654) that we hadn't gotten around to fixing yet just because it didn't seem like it was too big a problem. Getting this report is a good incentive to re-evaluate that. 😅 

Closing as duplicate.

**Closed by ChrisLoer** 2018-04-13 17:03 UTC
Labels: needs discussion :speech_balloon:
