### ISSUE TITLE
Feature Request : Aggregate geojson clustered source properties

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapbox-gl-js#3972] opened 2017-01-13 02:24 UTC
# Aggregate geojson sources

## Problem

Large geojson sources are expensive to render vector tiles on the client.

## Proposal

Expose a `clusterAggregateFunction=avg` option on a geojson source.  Cluster property values of clustered points in the source with the given function (average, maximum, minimum).  

Similar to https://github.com/mapbox/tippecanoe/issues/324

Precursor feature: https://github.com/mapbox/mapbox-gl-js/issues/3971

**Comment by mourner** [comment] 2017-01-13 10:36
Closing as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2412. Also see https://github.com/mapbox/mapbox-gl/issues/26

**Closed by mourner** 2017-01-13 10:36 UTC
Labels: enhancement
