### ISSUE TITLE
Support upright iconic hexagonal fill patterns

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4109] opened 2017-02-01 22:26 UTC
_From @ajashton on March 14, 2016 18:33_

@ansis made this demo way back in 2013. I still want it to be part of Mapbox GL:

![](https://camo.githubusercontent.com/2dc8196f8f457811a52f84cc899c4248d5537c57/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313432313635322f313231303137322f30663936623538302d323566362d313165332d386132652d3330653465383135323862352e676966)

I don't know what to call this type of pattern fill, but the important aspects are:
- The pattern is always upright to the viewer.
- The pattern is not so much a texture, but an icon arranged in a hexagonal grid. The hex arrangement looks great on rotated maps and seems like a more comfortable layout for natural feature patterns.
- The pattern image itself never scales, but gets spread out as you zoom in. New copies of the pattern fade in to fill in space as the gaps get larger.

This kind of feature would be fantastic for styling pretty much any area of natural landcover (forest, wetland, meadow, water).

There are some similarities with https://github.com/mapbox/mapbox-gl-style-spec/issues/398 but I think there are enough differences that this is a separate mode/feature.

_Copied from original issue: mapbox/mapbox-gl-style-spec#427_

**Comment by jfirebaugh** [comment] 2017-11-22 00:48
Duplicate of #1831.

**Closed by jfirebaugh** 2017-11-22 00:48 UTC
Labels: cross-platform, feature
