### ISSUE TITLE
Tooltips for navigation controls are exclusively in English

### ISSUE THREAD

**Issue by interDist** [mapbox/mapbox-gl-js#8943] opened 2019-11-05 08:40 UTC
**mapbox-gl-js version**: 0.51.0, 1.4.0

**browser**: any

**refs**: https://github.com/mapbox/mapbox-gl-js/pull/7373/commits/03f552e9a45f7d824f7f118c41393655fb2cbcba , https://github.com/mapbox/mapbox-gl-js/pull/8735/commits/bfddb3308961d4ebfe9665e83d4438f6e63e61b8

### Expected Behavior

The map owner has the ability to configure the language the tooltips appear in. Or at the very least, provide their own texts for all navigation controls.

### Actual Behavior

The tooltips are locked into English and cannot be shown to the end users in a language they understand.

**Comment by andrewharvey** [comment] 2019-11-05 08:48
There's some discussion of this in #8010 and a proposal at #8095.

**Comment by mourner** [comment] 2019-11-05 13:31
Let's keep the discussion in the previous ticket. Closing as duplicate of #8010.

**Closed by mourner** 2019-11-05 13:31 UTC
