### ISSUE TITLE
Using `fill-image` and `background-image` creates visible borders

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#972] opened 2015-01-30 22:01 UTC
There are white borders around images when `fill-image` is used:

![screen shot 2015-01-30 at 4 52 57 pm](https://cloud.githubusercontent.com/assets/5607844/5984159/7b6405ea-a8a1-11e4-99a9-8018336795a2.png)

**Comment by fnicollet** [comment] 2015-02-01 11:31
This issue only happens between "integer" zoom levels. If you use mapbox-gl-leaflet, which restrict the mapbox-gl layer to only integer zoom layers, you can't see the issue. But when you zoom in and out, you can see the borders appear during the animation.

Probably just a rounding pixel issue somewhere :)

**Comment by fnicollet** [comment] 2015-02-03 22:15
Hello,
Just updated and rebuilt. The issue still happens during the animation between integer zoom levels (say when zooming from zoom 8 to 7 or 7 to 8). Maybe a little less than before, but still.
Reproduced on Windows (not retina), on IE11

Fabien

**Comment by ansis** [comment] 2015-02-03 22:30
@fnicollet could you take a screenshot? thanks

**Comment by fnicollet** [comment] 2015-02-03 22:36
It happens during the animation so I had to take the screenshot during the short time of the zoom animation:

![scr](https://cloud.githubusercontent.com/assets/1240481/6031181/7cf6b25e-abfd-11e4-913d-bdd47a67d1a3.jpg)

**Comment by fnicollet** [comment] 2015-03-14 18:04
Nevermind, I didn't update mapbox-gl-js properly (was on mb-pages, not master) and the issue is actually fixed in master, thanks for your help!

This issue can be closed

**Comment by mourner** [comment] 2015-03-14 18:33
Yay!

**Comment by mourner** [comment] 2015-03-14 18:34
@fnicollet or was your comment related to #974?

**Closed by mourner** 2015-03-14 18:33 UTC
Labels: bug, rendering, style

**Comment by fnicollet** [comment] 2015-03-14 18:35
Issue #972 can be closed but #974 is still there :)
