### ISSUE TITLE
Marker separation based on zoom / spreading on click

### ISSUE THREAD

**Issue by hdrdavies** [mapbox/mapbox-gl-js#3556] opened 2016-11-07 17:27 UTC
I really like the marker clustering already within the mapbox-gl-js. One thing I've found however, with the data I'm using, several markers might be plotted on the same point so accessing the different ones via a pop up click handler is not possible.

One solution to this could be to spiderify on click of a cluster as follows:

![image](https://cloud.githubusercontent.com/assets/13098199/20068059/45043eea-a50f-11e6-8007-2a0b4cc10efa.png)

Or, markers could be offset slightly if markers already have the same long / lat

Is this functionality already available in the API ? Apologies if so.

**Comment by jfirebaugh** [comment] 2016-11-17 00:07
Duplicate of #2723.

**Closed by jfirebaugh** 2016-11-17 00:07 UTC
