### ISSUE TITLE
Set heatmap layer below fill type layer doesn't work

### ISSUE THREAD

**Issue by BranZhang** [mapbox/mapbox-gl-js#8726] opened 2019-09-05 04:46 UTC
**mapbox-gl-js version**: v1.3.0

**browser**: Chrome 76

### Steps to Trigger Behavior

 1. Copy this example [Create a heatmap layer](https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/) code.
 2. Set "earthquakes-heat" layer below "water" layer.
 3. Run.

### Link to Demonstration

https://jsbin.com/sofuvamoya/edit?html,output

### Expected Behavior

"earthquakes-heat" layer is covered by "water" layer.

### Actual Behavior

"earthquakes-heat" layer isn't covered by "water" layer.

**Comment by mourner** [comment] 2019-09-11 06:24
Duplicate of #5831

**Closed by mourner** 2019-09-11 06:24 UTC
Labels: bug :beetle:
