### ISSUE TITLE
mapbox-gl-js doesn't work after being minified with uglifyjs

### ISSUE THREAD

**Issue by CmdrShepardsPie** [mapbox/mapbox-gl-js#5084] opened 2017-08-02 16:11 UTC
I'm using mapbox-gl-js in our Due, TypeScript, WebPack project, 'importing' it in the one module that uses it. Everything works unless I enable uglifyjs to minify it, then I get this error:

blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1 Uncaught ReferenceError: e is not defined
43../support/isBuffer @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
i @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
(anonymous) @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
114.util @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
i @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
(anonymous) @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
131.../error/validation_error @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
i @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
(anonymous) @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
145../reference/latest @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
i @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
(anonymous) @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
159.../style-spec/validate_style.min @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
i @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
(anonymous) @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
151.../style-spec/reference/latest @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
i @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
(anonymous) @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
157.../style-spec/feature_filter @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
i @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
(anonymous) @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
110.../style/style_layer_index @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
i @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
(anonymous) @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
anonymous @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:3
i @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
t @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1
(anonymous) @ blob:http://localhost:9000/763d41eb-8258-41ee-88df-0afca8aab49f:1

My guess is the minification messes with the web worker code. Is there a way around this on my end, or can a fix be implemented?

**Comment by jfirebaugh** [comment] 2017-08-04 17:26
Duplicate of #4359. See https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-303880888 for exact reason. Workarounds in https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-286277540 and https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-288001933.

**Closed by jfirebaugh** 2017-08-04 17:26 UTC
