### ISSUE TITLE
Markers superposition

### ISSUE THREAD

**Issue by Emixam23** [mapbox/mapbox-gl-js#9086] opened 2019-12-07 23:45 UTC
Hi!

I would like to know if it's possible to superpose markers? I have certain cases where I can have multiple data at the same lat/lng

Thanks

**Comment by arindam1993** [comment] 2019-12-09 19:42
Hello @Emixam23 ,

Do you have a visual indication of how the superimposed markers should look, currently the markers should superimpose just fine, but one will get hidden underneath the other.

**Comment by Emixam23** [comment] 2019-12-10 04:35
Hey!

Yes it gives something like this:

<img width="413" alt="Screenshot 2019-12-09 at 23 30 03" src="https://user-images.githubusercontent.com/6987848/70495635-2db22b80-1adc-11ea-8286-de0218592890.png">

Another weird behavior

<img width="251" alt="Screenshot 2019-12-09 at 23 30 13" src="https://user-images.githubusercontent.com/6987848/70495682-50444480-1adc-11ea-8cd2-6ec5abe236ae.png">
 is when I haven't zoom yet and then I zoom, look at the next images:

<img width="847" alt="Screenshot 2019-12-09 at 23 30 39" src="https://user-images.githubusercontent.com/6987848/70495690-56d2bc00-1adc-11ea-8436-b3b170c1af9a.png">

<img width="858" alt="Screenshot 2019-12-09 at 23 30 49" src="https://user-images.githubusercontent.com/6987848/70495702-5cc89d00-1adc-11ea-97be-e25f6566f50a.png">

<img width="844" alt="Screenshot 2019-12-09 at 23 30 58" src="https://user-images.githubusercontent.com/6987848/70495707-60f4ba80-1adc-11ea-99f5-715c5e0468b6.png">

The more you zoom, the more the markers get spreads out.. It's pretty weird to me

Thanks

**Comment by arindam1993** [comment] 2019-12-10 19:09
Thanks for the screenshot @Emixam23 , but I'm unable to reproduce your issue in this fiddle http://jsfiddle.net/8ozhe3ck/ I'm adding two markers for every point.

This could be a css issue, are you adding `mapbox-gl.css` to your project? The markers rely on some of our css classes inorder to be positioned properly.

**Comment by arindam1993** [comment] 2019-12-12 21:05
hey @Emixam23 , I'm closing this issue for now. If you could provide a reproducible testcase it would be really helpful.

Thanks!

**Closed by arindam1993** 2019-12-12 21:05 UTC
Labels: needs information :pray:

**Comment by Emixam23** [comment] 2019-12-15 04:40
Hey @arindam1993 

Hmmm where is that class? sorry for the long reply, I follow this until I found out the issue don't worry, I really need to fix this :)

Thanks!

**Comment by Emixam23** [comment] 2019-12-15 05:12
Alright so I was just trying to look around based on your message and I am using https://docs.mapbox.com/help/tutorials/custom-markers-gl-js/#style-markers

This is my component (using react js)

```
import * as React from 'react';
import {Location} from "app/models/location";
// @ts-ignore
import * as style from './style.css'
import mapboxgl, {LngLat} from "mapbox-gl";

export interface LocationMapboxProps {
    locations: Location[];
}

export interface LocationMapboxState {
    lng: number;
    lat: number;
    zoom: number
    selectedLocation: Location
}

const mapboxStyleUrl = "----";
mapboxgl.accessToken = "my-token";

export class LocationMapbox extends React.Component<LocationMapboxProps, LocationMapboxState> {
    mapContainer: HTMLDivElement = null;

    constructor(props: LocationMapboxProps, context: any) {
        super(props, context);
        this.state = {
            lng: 5,
            lat: 34,
            zoom: 2,
            selectedPlace: null
        };
    }

    componentDidMount() {
        let map = new mapboxgl.Map({
            container: this.mapContainer,
            style: mapboxStyleUrl,
            center: [this.state.lng, this.state.lat],
            zoom: this.state.zoom,
        });

        map.on('move', () => {
            this.setState({
                lng: parseFloat(map.getCenter().lng.toFixed(4)),
                lat: parseFloat(map.getCenter().lat.toFixed(4)),
                zoom: parseFloat(map.getZoom().toFixed(2))
            });
        });

        this.props.locations.map(function(location) {
            console.log(location);

            // create a HTML element for each feature
            let el = document.createElement('div');
            el.className = style["marker"];

            el.onclick = () => {
                map.flyTo({
                    center: new LngLat(location.longitude, location.latitude),
                    zoom: 15,
                    speed: .75
                });
            };

            // make a marker for each feature and add to the map
            new mapboxgl.Marker(el, {
                    anchor: "bottom"
                })
                .setLngLat(new LngLat(location.longitude,location.latitude))
                .addTo(map);
        });
    }

    render() {
        return (
            <div className={style["container"]}>
                <div className={`${style["sidebarStyle"]}`}>
                    <div>Longitude: {this.state.lng} | Latitude: {this.state.lat} | Zoom: {this.state.zoom}</div>
                </div>
                <div ref={el => this.mapContainer = el} className={style["container"]}/>
            </div>
        )
    }
}

export default LocationMapbox
```

and its css:

```
.container {
    height: 100%;
    width: 100%;
}

.sidebarStyle {
    display: inline-block;
    position: absolute;
    top: 0;
    left: 0;
    margin: 12px;
    background-color: #404040;
    color: #ffffff;
    z-index: 1 !important;
    padding: 6px;
    font-weight: bold;
}

.marker {
    background-image: url('../../../assets/pins/green.png');
  background-size: cover;
  width: 50px;
  height: 50px;
  border-radius: 50%;
  cursor: pointer;
}
```

**Comment by amidnikmal** [comment] 2020-02-05 08:20
It's probably because you override `position: absolute` of your marker el.

https://github.com/mapbox/mapbox-gl-js/issues/3073

**Comment by Emixam23** [comment] 2020-02-05 17:11
let me check
