### ISSUE TITLE
Panning during pinch zoom gestures on Android Devices since version 1.4.0

### ISSUE THREAD

**Issue by igu-tech** [mapbox/mapbox-gl-js#8889] opened 2019-10-23 08:25 UTC
**mapbox-gl-js version**:
 v.1.4.0 and newer
**browser**:
Android Chrome v. 78
### Steps to Trigger Behavior

 1. Open [Demo Page](https://storage.googleapis.com/my-test-env/mapbox.1.4.0.html) (v.1.4.0) in Android Chrome
 2. Quickly zoom in and out with "pinch gestures"
 3. Map moves away randomly

### Link to Demonstration
BUG in v.1.4.0
https://storage.googleapis.com/my-test-env/mapbox.1.4.0.html

OK in v.1.3.2
https://storage.googleapis.com/my-test-env/mapbox.1.3.2.html

### Expected Behavior
No move during zooming
### Actual Behavior
Randomly moves the map while zooming with two fingers

**Comment by kkaefer** [comment] 2019-10-23 09:39
Linking https://github.com/mapbox/mapbox-gl-js/pull/8100, which might have introduced this regression.

**Comment by vakila** [comment] 2019-10-23 12:42
Thanks for the thorough report & demo pages @igu-tech ! 

So far I'm not really able to reproduce the issue with the map "moving away randomly" (on Android Chrome & Firefox on Samsung smartphone). I do notice some slight wandering as a I zoom in and out (because the center of my fingers/the map is gradually moving, and it's expected behavior that the map center will move to match the users' gesture, so that the user can pan and zoom the map at the same time), but that doesn't seem to match the behavior you're reporting. 

I do, however, notice my 2-finger touch occasionally being perceived as a 1-finger touch by the map which pans rather than zooms as a result (similar to https://github.com/mapbox/mapbox-gl-js/issues/8375), so I wonder if that could have something to do with what you're seeing. Possibly in combination with another small bug we're aware of where the map jumps from one finger to another in certain transitions from 2 fingers to 1, I could imagine that jump being a possible culprit for what seems like a "random" move.

In any case we'll investigate further and see what we can reproduce on other Android device(s). @igu-tech Do you notice this behavior when you have both fingers still firmly touching the screen? Or just as you're lifting your fingers? or both?

cc @arindam1993

**Comment by igu-tech** [comment] 2019-10-24 13:27
@vakila 
When i have both fingers firmly touching the screen it work's - but when i quickly zoom in and out    i can not guarantee that both fingers stay on then touch screen simultaneously (see [example](https://storage.googleapis.com/my-test-env/2019-10-24%2013_12_25%20%2B0000.mp4)).

**Comment by vakila** [comment] 2019-10-24 14:11
@igu-tech Great, thanks for the clarification and the video - this seems to support my hunch that the culprit is interaction between two-finger-zooming and single-finger dragging. I'll look into reproducing what you experience in the video and see if we can find a way to mitigate that.

**Comment by ansis** [comment] 2020-04-07 22:10
@igu-tech I think this has been fixed by https://github.com/mapbox/mapbox-gl-js/pull/9365. If you have a chance to test and confirm, that would be great! The fix is in `master` and will be released in a beta release tomorrow.

**Comment by igu-tech** [comment] 2020-04-14 14:37
@ansis 
I just tried v1.10.0-beta.1 and it works as expected. 
Great Work!

**Comment by ansis** [comment] 2020-04-14 15:09
Thanks for testing!

**Closed by ansis** 2020-04-14 15:09 UTC
Labels: bug :beetle:, needs information :pray:
