### ISSUE TITLE
Suggest Example Point Moving on Tablet / Ipad

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#6159] opened 2018-02-14 09:11 UTC
Hello,

the example [https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/](https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/) for me is not working on ipad. It would be nice to know how to draw, move a geometry on tablet / ipad.

Best
Stephan

**Comment by jfirebaugh** [comment] 2018-02-14 16:45
Duplicate of #3017.

**Closed by jfirebaugh** 2018-02-14 16:45 UTC
