### ISSUE TITLE
The resulting polygon has a disorder

### ISSUE THREAD

**Issue by xiaofsu** [mapbox/mapbox-gl-js#8216] opened 2019-05-05 02:24 UTC
[bug.txt](https://github.com/mapbox/mapbox-gl-js/files/3145057/bug.txt)
**Change txt to html to show the effect.**
![image](https://user-images.githubusercontent.com/46067472/57187348-8fdff800-6f1f-11e9-8239-c35b736e3431.png)

![image](https://user-images.githubusercontent.com/46067472/57187351-97070600-6f1f-11e9-8617-2982e264d67b.png)
**The resulting polygon has a disorder.**

How is this problem generated?
How can I solve this problem?
Thanks.

**Comment by xiaofsu** [comment] 2019-05-05 02:28
The concave polygon does not look normal.
When rendering this concave polygon into a face, the effect displayed at different levels is different.

**Comment by mourner** [comment] 2019-05-06 12:41
Closing as duplicate of #7023

**Closed by mourner** 2019-05-06 12:41 UTC
