### ISSUE TITLE
Code documentation for 'geolocate' event

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#2825] opened 2016-07-06 18:29 UTC
With reference to https://github.com/mapbox/mapbox-gl-js/issues/2824 it would be good to document `geolocator` event in a code example.

- Click on the geolocate button
- on `geolocate` add a marker to the location with a popup detailing its location.

**Comment by lucaswoj** [comment] 2016-07-07 17:13
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2692

**Closed by lucaswoj** 2016-07-07 17:13 UTC
Labels: examples
