### ISSUE TITLE
Moving label fading in and out

### ISSUE THREAD

**Issue by jaapster** [mapbox/mapbox-gl-js#5730] opened 2017-11-21 10:11 UTC
We use a symbol layer to show measurements on a map.
The measurement data is updated when the geometry is updated.

Previous to version 0.42 of mapbox, the text would stay visible while it was moving around.
Since 0.42 the text keeps fading in and out when moving.

I created a [fiddle](https://jsfiddle.net/jaapl/tkw12Lvz/)

In the HTML pane you can change the mapbox version to 0.41 and 0.42 to see the different behavior.

Is this a bug, or should I change layer styles somehow to keep the text visible?

**Comment by jfirebaugh** [comment] 2017-11-21 14:50
Duplicate of #5716.

**Closed by jfirebaugh** 2017-11-21 14:50 UTC
