### ISSUE TITLE
Rendering issues in Chrome + FF on PC

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#1074] opened 2015-03-11 18:13 UTC
Version `40.0.2214.115 m`of Chrome and `35.0.1` on Firefox

To the left, a square only renders labels. If I pan to the left the square renders all the details and the next square towards to the left loses everything but its labels.

![mapboxgl-chrome](https://cloud.githubusercontent.com/assets/61150/6603427/763a2bc8-c7f8-11e4-80a4-ffaf13a74ff7.png)

There also appears to be a pinkish hue when panning over certain areas.

![mapboxgl-chrome2](https://cloud.githubusercontent.com/assets/61150/6603426/76395a54-c7f8-11e4-95d8-1654b80ff7c6.png)

cc @ansis

**Comment by fnicollet** [comment] 2015-03-16 23:20
I can reproduce this issue on FF 33.1.1 but Chrome 41.0.2272.89 m and IE11 are working fine

Reproduced with mapbox-gl v0.7.0 from https://api.tiles.mapbox.com/mapbox-gl-js/ on Windows 8

**Comment by rotoglup** [comment] 2015-07-04 15:03
I can reproduce the issue using :
* Windows 7
* Optimus-enabled laptop using NVidia GeForce 650M + drivers v310.90
* Chrome Version 43.0.2357.130 m

On the same machine, Firefox 39.0 seems to render fine - but I'm able to reproduce the issues by setting `webgl.angle.try-d3d11` to false in `about:config`.

**Comment by minikarma** [comment] 2015-07-15 13:59
Hi threre 

I have the same bug from the user (Win 7, Chrome 43.0.2357.132)

Screenshots:
https://dl.dropboxusercontent.com/u/26463539/walkstreets%20bug%202.png
https://dl.dropboxusercontent.com/u/26463539/walkstreets%20bug.png

Reproducing here: http://walkstreets.org/#l=en&mode=sidewalks

Thanks

**Comment by phiphou** [comment] 2015-08-17 19:12
I experience same kind of bugs, but Chrome is maybe not the only problem : 
I've tested on two machines, all Win7 with same Chrome version : the first machine (PC) renders everything well, bugs appears on the second one (Asus ZenBook UX31A) 
But also tried on FF last version, same version on the two machines, and bugs are not there, for both mahines.

**Comment by jfirebaugh** [comment] 2015-10-17 00:49
Likely duplicate of #930.

**Closed by jfirebaugh** 2015-10-17 00:49 UTC
Labels: bug, rendering
