### ISSUE TITLE
setMaxBounds flickering bug

### ISSUE THREAD

**Issue by ovidiucp** [mapbox/mapbox-gl-js#11365] opened 2021-12-28 17:30 UTC
**mapbox-gl-js version**: 2.5.1

**browser**: Google Chrome

### Steps to Trigger Behavior

 1. Create a MapboxGL with mapbox-dem
 2. Call `map.setMaxBounds([[-179, -89], [179, 89]])`
 3.

### Link to Demonstration

Sorry for not being able to provide a minimal example.

The non-flickering site, with no setMaxBounds call:

https://jollyturns.com/resort/united-states-of-america/heavenly/skirun/round-a-bout?b=125.58&p=0.5

The flickering site, with the setMaxBounds call mentioned above:

https://next.jollyturns.com/resort/united-states-of-america/heavenly/skirun/round-a-bout?b=125.58&p=0.5

To see the problem manifesting itself, try clicking between different ski runs, like Round-A-Bout and Advanced Roundabout.

**Comment by stepankuzmin** [comment] 2022-01-04 11:17
Hi @ovidiucp,

I can confirm the flickering on your map, but unfortunately, I could not reproduce this issue in an isolated example based on your steps to trigger behavior. Could you please provide a minimal example for this?

```js
const map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/satellite-streets-v11',
    center: [-120.03, 39.10],
    zoom: 10,
    bearing: 180
});

map.on('load', () => {
  map.addSource('mapbox-dem', {
    'type': 'raster-dem',
    'url': 'mapbox://mapbox.mapbox-terrain-dem-v1',
    'tileSize': 512,
    'maxzoom': 14
  });

  map.setTerrain({ 'source': 'mapbox-dem', 'exaggeration': 1.5 });
});

document.getElementById('button').addEventListener('click', () => {
  map.setMaxBounds([[-179, -89], [179, 89]]);
});
```

**Comment by mourner** [comment] 2022-09-08 11:23
Closing as there's no minimal test case provided, so we can't diagnose the issue in GL JS.

**Closed by mourner** 2022-09-08 11:23 UTC
Labels: needs information :pray:
