### ISSUE TITLE
Canvas icon image does not render properly

### ISSUE THREAD

**Issue by pomm0** [mapbox/mapbox-gl-js#10938] opened 2021-08-17 05:45 UTC
**mapbox-gl-js version**: 2.4.0

**browser**:
- Chrome Linux Version 92.0.4515.131 (Official Build) (64-bit)
- iOS 14.5 Safari

### Steps to Trigger Behavior

 1. Open provided link one and zoom your browser to something like 500%. You'll see that the drawn canvas icon is not circular, it has some flat edges on each side (top, right, bottom, left), like it's one or two pixel smaller as the real canvas and strips parts of the canvas away (you can see that it does not render it properly).
 2. Open provided link two and zoom just like you did at step one. It somehow gets renderd properly, the only thing that is different, is that the canvas has a blue filled rectangle of the whole size.
 3. Open provided link three to prove, that the actual code to draw the canvas does work properly and would render a proper circular circle (or at least looks circular).

### Link to Demonstration

- Link one (wrong render): https://jsfiddle.net/1bLf2mye/
- Link two (proper render with "hack"): https://jsfiddle.net/3s1tfmeo/
- Link three (plain canvas proper render): https://jsfiddle.net/8pxbf2ke/

### Expected Behavior
Mapbox draws the canvas accurate to its original source.

### Actual Behavior
Mapbox draws the canvas not accurate to its original source.

Link one screenshot:
![Selection_343](https://user-images.githubusercontent.com/6084030/129669684-c7499edf-be11-4d25-a67c-9989ae45cd98.png)

Link two screenshot:
![Selection_344](https://user-images.githubusercontent.com/6084030/129669697-194d71ca-24d1-4129-b466-e244422d1103.png)

I used this example site as base https://docs.mapbox.com/mapbox-gl-js/example/add-image-animated/

**Comment by arindam1993** [comment] 2021-08-17 23:55
Thanks for the detailed report @pomm0 , it was really helpful in figuring out the root cause.
The sharp edges occur because we intentionally upscale icons using `NEAREST` filtering, along with snapping them to the pixel grid so that they always appear crisp. 
The best way to handle this in your code is to not hardcode `pixelRatio` to 2 in the `render` function instead use `window.devicePixelRatio` that will scale up the icon resolution along with the zoom of the browser.
Eg. https://jsfiddle.net/kxjy2r8e/

The reason the blue background appears to fix the is is because it switches the responsibility of blending with the background over to canvas(instead of gl-js) which seems to use `LINEAR` blending, which creates some bluriness.
This issue is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/8730, so I'm closing this one so we can continue discussion in that issue.

**Closed by arindam1993** 2021-08-17 23:55 UTC
