### ISSUE TITLE
3D Buildings in GL JS V3

### ISSUE THREAD

**Issue by rivindubandara** [mapbox/mapbox-gl-js#12905] opened 2023-09-24 23:11 UTC
**mapbox-gl-js version**: 3

### Question

How do I access the 3D buildings layer in V3? I am trying to add 3D buildings as a layer with a toggle on top of a map, but this old method of doing it with v2 doesnt work anymore, I get the error 'evented.js:151  Error: layers.3d-buildings: source "composite" not found'.

`map.addLayer({
          id: "3d-buildings",
          source: "composite",
          "source-layer": "building",
          filter: ["==", "extrude", "true"],
          type: "fill-extrusion",
          minzoom: 15,
          paint: {
            "fill-extrusion-color": "#aaa",
            "fill-extrusion-height": ["get", "height"],
            "fill-extrusion-base": ["get", "min_height"],
            "fill-extrusion-opacity": 1.0,
          },
          layout: {
            visibility: "visible",
          },
        });`

**Comment by mourner** [comment] 2023-09-25 08:47
Can you provide the full example with e.g. a JSFiddle? This should still work if you're using the older Mapbox Streets style with the map, but not if you use the [default Standard style](https://github.com/mapbox/mapbox-gl-js/blob/main/MIGRATION_GUIDE_v3.md), which hides its internal layer details and only allows configuration through config options (but instead already provides 3D buildings by default).

**Comment by rivindubandara** [comment] 2023-09-27 00:21
This is the full code
`    <div id="buildingsToggle" class="toggle">
            <div class="toggle-button" onclick="Animatedtoggle(this)">
              <div class="toggle-text">Buildings</div>
            </div>
          </div>


        </div>

   
      </nav>
    </div>

    <section id="container">
      <div id="map"></div>
    </section>

    <script>
      let toggle = document.querySelector(".toggle");
      let text = document.querySelector(".text");

      function Animatedtoggle(clickedElement) {
        const toggle = clickedElement.parentNode;
        const text = toggle.nextElementSibling;

        toggle.classList.toggle("active");
      }
    </script>


    <script>
      mapboxgl.accessToken =
        "pk.eyJ1Ijoicml2aW5kdWIiLCJhIjoiY2xmYThkcXNjMHRkdDQzcGU4Mmh2a3Q3MSJ9.dXlhamKyYyGusL3PWqDD9Q";
      var lat = "{{ lat }}";
      var lon = "{{ lon }}";

      const map = new mapboxgl.Map({
        container: "map",
        // style: "mapbox://styles/mapbox/dark-v10",
        center: [lon, lat],
        zoom: 10,
      });

      map.on('style.load', () => {
        map.setConfigProperty('basemap', 'lightPreset', 'dawn');
        });

      map.on("load", function () {

        map.addLayer({
          id: "3d-buildings",
          source: "composite",
          "source-layer": "building",
          filter: ["==", "extrude", "true"],
          type: "fill-extrusion",
          minzoom: 15,
          paint: {
            "fill-extrusion-color": "#aaa",
            "fill-extrusion-height": ["get", "height"],
            "fill-extrusion-base": ["get", "min_height"],
            "fill-extrusion-opacity": 1.0,
          },
          layout: {
            visibility: "visible",
          },
        });

        buildingsToggleBtn.classList.add("active");

      });

      const geocoder = new MapboxGeocoder({
        accessToken: mapboxgl.accessToken,
        mapboxgl: mapboxgl,
        marker: true,
      });

      map.addControl(geocoder);

      map.addControl(new mapboxgl.NavigationControl());

      }

      map.on("click", function (e) {
        if (marker) {
          marker.remove();
        }

        marker = new mapboxgl.Marker({
          color: "#FFD700",
          circleRadius: 8,
          draggable: false,
        })
          .setLngLat(e.lngLat)
          .addTo(map);

        mapClickFn(e.lngLat, "address_planning");
        mapClickFn(e.lngLat, "address_geometry");
        mapClickFn(e.lngLat, "address_elevated");
      });

      const buildingsToggleBtn = document.getElementById("buildingsToggle");

      buildingsToggleBtn.addEventListener("click", function () {
        const layerId = "3d-buildings";
        toggleLayerVisibility(layerId, buildingsToggleBtn);
      });

      function toggleLayerVisibility(layerId, toggleBtn) {
        const visibility = map.getLayoutProperty(layerId, "visibility");
        if (visibility === "visible") {
          map.setLayoutProperty(layerId, "visibility", "none");
          toggleBtn.classList.remove("active");
        } else {
          map.setLayoutProperty(layerId, "visibility", "visible");
          toggleBtn.classList.add("active");
        }
      }
    </script>`

**Comment by rivindubandara** [comment] 2023-09-27 06:17
I want to basically turn of the buildings with the toggle with the new V3 buildings.

**Comment by rivindubandara** [comment] 2023-09-27 06:19
![image](https://github.com/mapbox/mapbox-gl-js/assets/54240628/293c2f94-8836-4b96-94ee-7f2be0862ee3)

**Comment by ricardoweiss** [comment] 2023-10-02 13:27
Would be very helpful to know how we can interact with the new 3d buildings. Change color on clicl, or on hover and so on

**Comment by rivindubandara** [comment] 2023-11-02 05:49
Can we get some fixes or advice for this issue?

**Comment by astojilj** [comment] 2023-11-02 07:22
@rivindubandara 

Following @mourner's clarification at https://github.com/mapbox/mapbox-gl-js/issues/12905#issuecomment-1733194674,   
 the code example requires some clarification:


`
map.addLayer({
      id: "3d-buildings",
`

Your code fails when adding new fill extrusion layer.

> but not if you use the [default Standard style](https://github.com/mapbox/mapbox-gl-js/blob/main/MIGRATION_GUIDE_v3.md), which hides its internal layer details and only allows configuration through config options (but instead already provides 3D buildings by default).

If you use [default Standard style](https://github.com/mapbox/mapbox-gl-js/blob/main/MIGRATION_GUIDE_v3.md) and try to  toggle the buildings layer there, it is not available.

**Comment by rivindubandara** [comment] 2023-11-07 01:35
I am still not too sure about what's going on. In map box v2 I was able to use this code to basically create a 'building' layer toggle and it would turn the buildings on and off. I just need the corresponding code for v3 because I am using the v3 map now and want to toggle the buildings off. The problem is it says 3d-buildings layer doesn't exist. Does that mean that functionality is not in here yet or its under a different layer name.

**Comment by HealthyPizza** [comment] 2023-12-08 16:48
> @rivindubandara
> 
> Following @mourner's clarification at [#12905 (comment)](https://github.com/mapbox/mapbox-gl-js/issues/12905#issuecomment-1733194674), the code example requires some clarification:
> 
> `map.addLayer({ id: "3d-buildings",`
> 
> Your code fails when adding new fill extrusion layer.
> 
> > but not if you use the [default Standard style](https://github.com/mapbox/mapbox-gl-js/blob/main/MIGRATION_GUIDE_v3.md), which hides its internal layer details and only allows configuration through config options (but instead already provides 3D buildings by default).
> 
> If you use [default Standard style](https://github.com/mapbox/mapbox-gl-js/blob/main/MIGRATION_GUIDE_v3.md) it already has buildings layer, no need to add new. If you try to toggle the buildings layer there, it is not available.

So basically setting color or opacity on buildings with the new default standard style is impossible ?
Accessing terrains / landcover informations to know if user clicked on water' is also impossible ?

**Comment by stepankuzmin** [comment] 2024-01-16 15:17
Hi all,

Unfortunately, turning off 3D Buildings and trees in the Standard Style is not currently supported. Closing this issue as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/13009 so we can track it in one place.

**Closed by stepankuzmin** 2024-01-16 15:17 UTC
Labels: feature :green_apple:, needs information :pray:
