### ISSUE TITLE
Using transform:scale in css causes mapbox mouse events to be offset

### ISSUE THREAD

**Issue by xiangyin1987** [mapbox/mapbox-gl-js#13166] opened 2024-05-06 09:08 UTC
Using transform:scale in css causes mapbox mouse events to be offset
![Snipaste_2024-05-06_17-04-58](https://github.com/mapbox/mapbox-gl-js/assets/9527142/abe1487f-c5c9-4e61-8bb8-d70976397116)

**Comment by xiangyin1987** [comment] 2024-05-07 14:28
![Snipaste_2024-05-07_22-22-46](https://github.com/mapbox/mapbox-gl-js/assets/9527142/6a33daa2-2c69-4a88-a3ac-ae137f5a14be)
The result returned by the getScaledPoint function does not take into account transform:scale

**Comment by stepankuzmin** [comment] 2024-05-14 16:05
Closing as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/13169

**Closed by stepankuzmin** 2024-05-14 16:05 UTC
