### ISSUE TITLE
setStyle updates `text-variable-anchor` inconsistently

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#8397] opened 2019-06-26 00:31 UTC
**mapbox-gl-js version**: 1.0.0

**browser**: any

### Steps to Trigger Behavior

 1. Render a mapbox gl map with a text-variable-anchor value
 2. Use setStyle to apply new text-variable-anchor values 

The result is that Studio cannot provide a realistic preview of the user's style as the user changes the `text-variable-anchor` value.

### Link to Demonstration

https://jsbin.com/riwasomula/1/edit?html,output

### Expected Behavior

 Expect label placement to change when preferred text anchor changes.

### Actual Behavior

text placement does not change.

**Comment by samanpwbb** [comment] 2019-06-26 00:44
Note that `{ diff: false }` does properly update text position – but this shouldn't be necessary.

**Comment by peterqliu** [comment] 2019-07-05 23:34
@samanpwbb I can't reproduce the bug in the linked test case 🤔 changes are subtle, but if we disable the color change and bump the interval to 1000, labels are clearly updating:

<img src='https://media.giphy.com/media/KDbWMslRUv4sXz5oQy/giphy.gif'>

**Comment by samanpwbb** [comment] 2019-07-08 17:16
> @samanpwbb I can't reproduce the bug in the linked test case 🤔 changes are subtle, but if we disable the color change and bump the interval to 1000, labels are clearly updating:

Yes, there are some subtle changes. I would expect label placement after a setStyle to be deterministic though. Right now, results of setStyle vary based on past label placement calculations. It appears as though once a given label finds a position that works, it will "prefer" that position in the future. Would it be possible to reset the "memory" of past positions after setStyle calls that effect `text-variable-anchor`?

**Comment by dereklieu** [comment] 2019-07-10 00:24
This is a pretty simplistic example, but I think it helps illustrate why someone using this property in Studio might think the current behavior is buggy. I made the screengrab on `0.54.x` but confirmed it on `1.1.0` as well.

**Regular text-anchor**
![text-anchor](https://user-images.githubusercontent.com/1590802/60931376-4210a480-a26e-11e9-9a02-764555ae0fe0.gif)

**text-variable-anchor**
![text-variable-anchor](https://user-images.githubusercontent.com/1590802/60931385-489f1c00-a26e-11e9-9da0-3d968ca70040.gif)

**Comment by asheemmamoowala** [comment] 2019-07-12 18:31
The `styleDiff` is working correctly. It generates the correct `setLayoutProperty` change operation in the jsbin provided.

The problem (I think) stems from preferring previous placement in: 

https://github.com/mapbox/mapbox-gl-js/blob/2ce452d4286dbce581a69b5b79fc77bac259eee2/src/symbol/placement.js#L342-L350

If the previous placement anchor is not in the current set of `anchors` it should not be preferred. Currently it is added as long as it is not the first value in `anchors`.

**Comment by dereklieu** [comment] 2019-07-12 20:16
@asheemmamoowala ah thanks for that reference. This would validate the experience of labels seeming to bias the current anchor, when the current anchor is among the list of selected anchors.

However, I'm having trouble understanding why setting a single anchor for `text-variable-anchor`, and then changing that anchor, does not cause the placement to change without zooming or panning the map.

```
text-variable-anchor: [ "center" ] -> [ "top-right" ]
```

**Comment by dereklieu** [comment] 2019-07-12 20:18
Oops, just re-read it. Am I right in understanding that any anchor with a previous placement will always bias for that previous placement, even if it's no longer a favored placement? If so, that seems like unexpected behavior.

**Comment by asheemmamoowala** [comment] 2019-07-15 18:33
> Am I right in understanding that any anchor with a previous placement will always bias for that previous placement, even if it's no longer a favored placement? If so, that seems like unexpected behavior.

That's correct, this behavior is a bug. The previous placement should only be preferred if the chosen anchor continues to be in the `text-variable-anchor` property.

**Comment by asheemmamoowala** [comment] 2019-07-16 21:52
Closed by #8473

**Closed by asheemmamoowala** 2019-07-16 21:52 UTC
Labels: bug :beetle:, high priority
