### ISSUE TITLE
Clip tiles to raster source's bounds ?

### ISSUE THREAD

**Issue by iamvdo** [mapbox/mapbox-gl-js#10608] opened 2021-04-22 12:42 UTC
Hello! 

When using a `raster` or `raster-dem` source, one can set a `bounds` property to load tiles only for that specific area. The point is, tiles are not clipped to these bounds, and I find it a bit confusing.

Say if I'm wrong, but it seems that tiles that intersect bounds will load, and aren't clipped. The point is that, given any zoom, tiles are not covering the same area on map, thus giving unexpected result.

To say it from another point of view, is there a way to do that specific effect from Mapbox's blog, with a consistent zoom (eg, if I zoom, the colored area remains the same)?

![image](https://user-images.githubusercontent.com/1260529/115715572-90763100-a378-11eb-911b-889a2f0e9aba.png)

Thanks!

**Comment by rreusser** [comment] 2021-04-23 17:02
Hi @iamvdo. I think what you've found is indeed correct. Bounds affect loading of tiles but does not precisely clip to those bounds. For my own satisfaction, I tested out a workaround, which is to use two rectangles and adjust the winding to accomplish something like this:

https://codepen.io/rsreusser/pen/xxgmmjb

![Screen Shot 2021-04-23 at 9 58 07 AM copy](https://user-images.githubusercontent.com/572717/115905229-a9cfb980-a41a-11eb-8cb8-31ac7526fe65.jpg)

If it's alright, I'll close the issue as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/7018.

**Closed by rreusser** 2021-04-23 17:02 UTC
