### ISSUE TITLE
"Empty Style" with single Null Island source; 404s on tile load

### ISSUE THREAD

**Issue by andest01** [mapbox/mapbox-gl-js#3760] opened 2016-12-07 19:53 UTC
**mapbox-gl-js version**:
Using Mapbox Studio; I assume the latest version.

### Steps to Trigger Behavior

 1. **In Mapbox Studio, create a new style by copying the "Empty Style".**

<img width="251" alt="screen shot 2016-12-07 at 1 29 47 pm" src="https://cloud.githubusercontent.com/assets/1424223/20983303/8d3a8302-bc81-11e6-8cfd-9f8ffb36be6e.png">

<img width="716" alt="screen shot 2016-12-07 at 1 33 36 pm" src="https://cloud.githubusercontent.com/assets/1424223/20983364/d2868c1c-bc81-11e6-9a12-7917c64b1b2b.png">

 2. **Set the background to 50% transparent red.**
<img width="710" alt="screen shot 2016-12-07 at 1 36 03 pm" src="https://cloud.githubusercontent.com/assets/1424223/20983445/21733348-bc82-11e6-88e8-e8824f06fac2.png">

 3. **Add a Null Island source as a point.**
<img width="710" alt="screen shot 2016-12-07 at 1 36 59 pm" src="https://cloud.githubusercontent.com/assets/1424223/20983482/449c2ed8-bc82-11e6-89d8-ef463b8da14d.png">

4. **Hit the Publish button**

5. **Open the "Share URL" link in a new tab and open Inspector Panel**
<img width="271" alt="screen shot 2016-12-07 at 1 38 29 pm" src="https://cloud.githubusercontent.com/assets/1424223/20983533/784bc536-bc82-11e6-9e11-4f750ba57388.png">
 

### Expected Behavior
The user is lost in a sanguinary sea of pink, adrift in their own thoughts. Also, there are no 404 errors in the network tab of the inspector panel.

### Actual Behavior
There are several 404 errors while moving around the map. The user is too anxious to enjoy the map.
<img width="994" alt="screen shot 2016-12-07 at 1 45 10 pm" src="https://cloud.githubusercontent.com/assets/1424223/20983800/716982a2-bc83-11e6-89b9-1a52cbc4d706.png">

### Additional Context
I'm trying to make an offline map - a default empty style that can be loaded when the user is offline. I decided to create placeholder layers with empty sources to load my local cached GeoJSON files. Attempting to create an empty style in Mapbox Studio led me to this problem.

Copying the "Empty Style" style and viewing the pristine, untouched copy causes no 404s for tile loads. However, BOTH the pink and pristine styles 404 over fonts not loading.

**Comment by lucaswoj** [comment] 2016-12-07 21:10
The contract between vector tile sources and GL JS, as things are implemented, is that vector tile sources provide tiles to cover the whole planet. 

The Mapbox API returns a 404 when a vector tile is empty. 404 is considered the correct semantic HTTP status code for "no data."

We are considering allowing vector and raster sources to specify a bounding box in https://github.com/mapbox/mapbox-gl-js/issues/1775. This will reduce the # of 404 errors but not eliminate them in all cases.

I am not aware of any other feasible approaches to reduce the number of 404 errors.

 - changing the response code to a 200 would require we send an empty vector tile payload and may have some implications for our CDN
 - providing adding richer TileJSON bounds functionality may result in a cure that's worse than the disease

Closing as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/1775 until anything more actionable comes up.

**Closed by lucaswoj** 2016-12-07 21:10 UTC

**Comment by lucaswoj** [comment] 2016-12-07 21:14
You may find the behaviour you get using a [GeoJSON source](https://www.mapbox.com/mapbox-gl-style-spec/#sources-geojson) more desirable (though this is not available in Studio)

**Comment by sylspren** [comment] 2017-04-04 16:16
Thanks for the explanation @lucaswoj.  

As per something more actionable - what do you think of having vector_tile_source at least not throw an error when receiving these 404s since these are "expected" for most maps? Looks like it's coming from this line: https://github.com/mapbox/mapbox-gl-js/blob/master/src/source/vector_tile_source.js#L90

Our application has safeguards to warn us of spikes of console errors and we load this map on most pages so we haven't yet moved to this newer api due to this issue. We can simply whitelist the error (which is probably what we'll do) but it seems like this would be an issue for most apps.

**Comment by jfirebaugh** [comment] 2017-04-04 16:41
@sylspren We were thinking along the same lines, and changed that in 9e3397ab2281daddb2f071ef7ce35bb425801550, which will be in the next release.

**Comment by sylspren** [comment] 2017-04-04 18:08
awesome! thank you! :)
