### ISSUE TITLE
Get the information when mouse hover a 3D bar

### ISSUE THREAD

**Issue by camillalo** [mapbox/mapbox-gl-js#7217] opened 2018-08-29 13:00 UTC
## Description
When i need to add some 3d bars in the map, how to get the information of these bars when the mouse hover on one bar ! 
I can't find some method to complete this operation!

**Comment by andrewharvey** [comment] 2018-08-29 13:45
Do you mean #3122?

**Comment by jfirebaugh** [comment] 2018-08-29 16:18
Sounds like a probable duplicate of #3122. @camillalo, in the future, when opening an issue, please fill out the provided issue template completely -- we need all this data in order to provide an answer.

**Closed by jfirebaugh** 2018-08-29 16:18 UTC

**Comment by camillalo** [comment] 2018-08-30 01:08
@Andrewharvey @jfirebaugh yes,it is. Thanks a lot
