### ISSUE TITLE
AnimationOptions in docs doesn't link anywhere

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4176] opened 2017-02-02 01:34 UTC
https://www.mapbox.com/mapbox-gl-js/api/#Map#zoomTo

The word "AnimationOptions" is a link that doesn't go anywhere.

**Comment by jfirebaugh** [comment] 2017-02-02 01:46
Duplicate of #3680

**Closed by jfirebaugh** 2017-02-02 01:46 UTC
