### ISSUE TITLE
popup addClassName has no effect before the popup is on the map

### ISSUE THREAD

**Issue by JeffesJiang** [mapbox/mapbox-gl-js#9677] opened 2020-05-11 10:29 UTC
popup addClassName  invalid

**mapbox-gl-js version**:1.10.0

**browser**: chrome v81.0.4044.122

### Expected Behavior

No classname I added when checking DOM elements

### Actual Behavior

When checking the DOM element, I added the classname, and the style changed

**Comment by ryanhamley** [comment] 2020-05-11 17:59
Can you please provide a minimal reproduction of the bug using a site like JSBin?

**Comment by JeffesJiang** [comment] 2020-05-12 02:22
https://jsfiddle.net/sharer/9f82brz1/
This is bug demo. When you check the popup element, you find that classname has not been added.

https://jsfiddle.net/sharer/9f82brz1/2/
However, when initializing the popup instance, the configuration option configuration can take effect》


All the APIs that have been tested to operate classname in the pop operation do not work properly

**Comment by mourner** [comment] 2020-05-25 07:51
Looking at the code, `addClassName`, `removeClassName` and `toggleClassName` have no effect unless the popup has already been added to the map. We should either handle cases like this (maintaining a list of classes and then adding on initialization), or fix the documentation which currently shows an incorrect example:

```js
let popup = new mapboxgl.Popup()
popup.addClassName('some-class')
```

**Comment by ansis** [comment] 2021-07-09 20:43
I think this could be fixed by creating the container as soon as Popup is created.

**Comment by SnailBones** [comment] 2021-07-21 17:00
@ansis Great idea, but unfortunately I'm not seeing a way to create the container immediately, since the popup isn't tied to a map instance at creation, and I think that changing that would be a breaking change?

@JeffesJiang I'm glad you noticed that the constructor argument works!

That's because the `popup` class stores `options.className` before the container is created. `addClassName` currently only adds a classname if the container is already created, and does not modify the variable. But that can be changed with the following fix (the function currently ends after the `if` statement):

```
    addClassName(className: string) {
        if (this._container) {
            this._container.classList.add(className);
        } else if (this.options.className && this.options.className !== ``) {
            this.options.className += ` ${className}`;
        } else { this.options.className = className; }
    }
```

As @mourner mentioned, `removeClassName` and `toggleClassName` also have no effect when before the popup is placed on the map. Adding these would be a slightly larger lift (effectively reimplementing JavaScript's classList). I can't think of an example where it would be necessary to use them instead of the `className` configuration property. To be consistent, perhaps we should clarify the documentation that the latter is the correct way to do this.

**Comment by SnailBones** [comment] 2021-07-21 20:47
> I think this could be fixed by creating the container as soon as Popup is created.

@ansis Actually this can be done through a separate DOM element and it looks like we already have a [pull request ](https://github.com/mapbox/mapbox-gl-js/pull/10143) for it. (The creator seems to be an independent contributor who closed it on the same day as our licensing change. 😢 )

**Closed** 2021-08-02 23:09 UTC
Labels: api :memo:, bug :beetle:, good first issue
