### ISSUE TITLE
raster tile source  shaking

### ISSUE THREAD

**Issue by wandergis** [mapbox/mapbox-gl-js#7399] opened 2018-10-11 02:29 UTC
**mapbox-gl-js version**: v0.49.0

**browser**: chrome 70

### Steps to Trigger Behavior

 1. open https://www.mapbox.com/mapbox-gl-js/example/map-tiles/

### Expected Behavior
zoom the map  no shaking.

### Actual Behavior
shaking.

**Comment by mollymerp** [comment] 2018-10-11 22:04
Thanks for using Mapbox. I believe this is a duplicate of #6150. Closing here to focus conversation on that ticket.

**Closed by mollymerp** 2018-10-11 22:04 UTC
