### ISSUE TITLE
API: fitBounds without an animation

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#1473] opened 2015-09-10 21:25 UTC
Hei!

fitBounds fires off either easeTo or FlyTo. Both are animated. Would be great if we could pass along a param to trigger jumpTo.

**Comment by 1ec5** [comment] 2015-09-10 21:31
`jumpTo()` is the equivalent of `easeTo()` with a `duration` of 0. Try setting `duration: 0` in the options object you pass in.

**Comment by kristfal** [comment] 2015-09-10 21:55
@1ec5 Ah, makes sense. Just one thing, fitBounds does a check for a linear option. This isn't documented nor used in any other public methods, just internally. Makes it slightly tricky to follow. Anyway, feel free to close this issue unless you want to keep it open as an doc-improvement issue.

````javascript

fitBounds: function(options) {

(...)
 return options.linear ?
            this.easeTo(options) :
            this.flyTo(options);

```

**Comment by tmcw** [comment] 2015-10-12 15:45
I think we should add sync API methods and clear ways to use them: setting a duration of 0 is not a very good way to express this.

**Comment by peckjon** [comment] 2016-01-22 07:05
Request for clarification: the docs on jumpTo indicate there's no transition, but easeTo with duration:0 still shows a (very fast) animation.  Is this the expected behavior?  If so, we still do need a way to fitBounds() with no transition.

**Comment by bhousel** [comment] 2016-01-22 14:24
> @1ec5 Request for clarification: the docs on jumpTo indicate there's no transition, but easeTo with duration:0 (or linear: true) still shows a (very fast) animation. Is this the expected behavior? 

In my opinion, this is wrong - we should special case `duration:0` and have it call `jumpTo`, instead of triggering a very fast animation.

Thoughts, @1ec5 ?

**Comment by 1ec5** [comment] 2016-01-22 15:19
I agree. gl-native runs zero-second transitions atomically and synchronously. Should the change take place in `_ease()`, to benefit all the camera methods, or would that introduce unexpected behavior? I see there's already an `animated` option that would become redundant.

**Comment by mourner** [comment] 2016-01-22 15:29
[It is in fact special-cased](https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/browser/browser.js#L24-L27) already. So the 0-duration @peckjon describes is definitely a bug.

**Comment by peckjon** [comment] 2016-01-22 16:56
Can someone else verify the bug please?  Want to be sure it's not just my codebase.

**Comment by 1ec5** [comment] 2016-01-22 17:23
`fitBounds()` with `duration: 0` does run synchronously without animation in GL JS 0.12.4. Are you setting any other options?

**Comment by peckjon** [comment] 2016-01-22 18:06
@mourner @1ec5 thank you for your help!  I've been able to confirm it was a bug in my local code.

Presumably, then, the best way to create a Map with specific bounds (and no other side effects) is to call fitBounds with {duration: 0} **immediately** after creation?

**Comment by jfirebaugh** [comment] 2016-01-22 18:58
@peckjon Yes, that's correct.

In terms of API here, I think we should add `jumpToBounds`, `easeToBounds`, and `flyToBounds` and remove `fitBounds`. Internally the new methods would call a common method to calculate the effective zoom and center for the bounds, then delegate to `jumpTo`/`easeTo`/`flyTo`.

**Comment by 1ec5** [comment] 2016-01-22 19:24
gl-native publicly exposes a `cameraForBounds()` method that can be passed into `*to()` or used for any other purpose.

**Comment by mourner** [comment] 2016-01-25 14:29
> In terms of API here, I think we should add jumpToBounds, easeToBounds, and flyToBounds and remove fitBounds

I'm :+1: on this, and also adding `map.getBoundsZoom` or something like this.

**Comment by 1ec5** [comment] 2016-01-25 15:36
Before `fitBounds` can be subsumed by the `*to()` methods, the `padding` camera option needs to be ported from mapbox/mapbox-gl-native#3583.

`.getBoundsZoom()` is a somewhat confusing name, since it wouldnt get the current bounds or zoom level. How about `.toCameraOptions()`?

**Comment by lucaswoj** [comment] 2016-07-28 23:02
Merged into #2801

**Closed by lucaswoj** 2016-07-28 23:02 UTC
Labels: enhancement

**Comment by cyrilchapon** [comment] 2017-09-19 10:12
I might be stupid, but here, *how to fit bounds without an animation ?*

jumpTo with duration 0, or stuff like panTo and panBy are all about a combination of center and zoom, while a bound is like a rectangle.

I know best zoom / center combination can be calculated from a bounds, but the purpose of `firBounds` seems to be to auto-calculate that, beyond the fact of centering / zooming the map.

**Comment by Erutan409** [comment] 2017-10-10 14:59
@cyrilchapon Did you find one?

**Comment by tempranova** [comment] 2018-08-18 03:16
Has this been addressed yet?

**Comment by mollymerp** [comment] 2018-08-20 18:31
@cyrilchapon @Erutan409 you can use `duration: 0` in the `fitBounds` options

```js

    map.fitBounds([[
        32.958984,
        -5.353521
    ], [
        43.50585,
        5.615985
    ]], {duration: 0});
```

The documentation for this method is not generating correctly. I'm working on a fix.

**Comment by thebearjew** [comment] 2018-09-01 14:15
@mollymerp Thank you for this! I didn't connect that `duration` was available in `CameraOptions` on `fitBounds`

**Comment by vedmant** [comment] 2020-06-23 04:42
This doesn't work for me
```
this.map.fitBounds(this.bounds, {padding: 30, duration: 0})
```

**Comment by cs09g** [comment] 2020-06-23 04:57
@vedmant could you create working fiddle which is reproducing the issue? For the fitBounds end event, you can try to use `moveend` event with `once`.

**Comment by vedmant** [comment] 2020-06-24 11:03
@cs09g It works actually, it was my mistake. `you can try to use moveend event with once.` - thanks, I'll try this.

**Comment by malihe1991** [comment] 2023-02-08 13:40
It's easy. You must add `animate: false` to your fitbounds() method options :))

```js
map.fitBounds(bounds, {
     padding: {
         top: 150, bottom: 150, left: 30, right: 30,
     },
     maxZoom: 13,
     animate: false,
});
```
