### ISSUE TITLE
Can't build v2 with create-react-app

### ISSUE THREAD

**Issue by 800147** [mapbox/mapbox-gl-js#10242] opened 2020-12-25 07:50 UTC
Hello, when I use mapbox-gl v2.0.1 with create-react-app everything is ok when i run ```npm run start``` but when I build the app with ```npm run build``` and then try to run the builded site, map is not showing up and there is an error in console
```
ReferenceError: y is not defined
```

Looks like there is some issue with webpack used in create-react-app and mapbox-gl package.

**mapbox-gl-js version**: 2.0.1

**browser**: Firefox 84.0, Chrome 87.0.4280.88

### Steps to Trigger Behavior

 1. Make an app using create-react-app (I made it with typescript template)
 2. Install mapbox-gl v2 package and add map to page
 3. Build the app using ```npm run build``` and try to run the build

### Link to Demonstration

[screenshot](https://github.com/800147/mapbox-2-test/blob/master/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202020-12-25%2010-26-47.png)

github: https://github.com/800147/mapbox-2-test

### Expected Behavior
Map is showing up

### Actual Behavior
Map is not showing up, error in console

**Comment by mourner** [comment] 2020-12-25 11:51
Duplicate of #10173

**Closed by mourner** 2020-12-25 11:51 UTC
