### ISSUE TITLE
TypeError when dragging map and scroll zooming

### ISSUE THREAD

**Issue by tjhelmuth** [mapbox/mapbox-gl-js#6385] opened 2018-03-23 14:33 UTC
When panning around the map and attempting to zoom at the same time a TypeError is thrown in mapbox gl js code. This is ok in Chrome but in IE 11 there are side effects. This is reproducible with no interaction on the map other than loading a style and was fine in v0.41. 

Seems to be caused by DragPanHandler::_onDragFrame

Test case: http://jsfiddle.net/dg6sey1t/3/

**mapbox-gl-js version**:    v0.44

### Steps to Trigger Behavior

 1. Pan the map around with left click drag
 2. While continuing to pan the map, attempt to scroll with the mouse wheel

### Expected Behavior
There shouldn't be any javascript errors caused by this. There were no issues in v0.41.

### Actual Behavior
TypeError in Transform.pointCoordinate:128

Stack trace as follows:
`Uncaught TypeError: Cannot read property 'x' of undefined
    at Transform.pointCoordinate (VM273 mapbox-gl.js:128)
    at Transform.pointLocation (VM273 mapbox-gl.js:128)
    at DragPanHandler._onDragFrame (VM273 mapbox-gl.js:483)
    at e.i._updateCamera (VM273 mapbox-gl.js:463)
    at e._render (VM273 mapbox-gl.js:495)
    at VM273 mapbox-gl.js:495`

**Comment by jfirebaugh** [comment] 2018-03-23 17:58
Duplicate of #6106. Upgrade to 0.44.1 for the fix.

**Closed by jfirebaugh** 2018-03-23 17:58 UTC
