### ISSUE TITLE
Navigation controls contain unwanted artifacts

### ISSUE THREAD

**Issue by captainbarbosa** [mapbox/mapbox-gl-js#4735] opened 2017-05-22 18:42 UTC
**mapbox-gl-js version**: 0.37.0
**browser version**: Chrome 58.0.3029.110 (unable to replicate in Safari 10.1)

When viewing a map containing navigation controls, strange artifacts are displayed when hovering over the controls:

![screenshot 2017-05-22 10 54 34](https://cloud.githubusercontent.com/assets/10850812/26323087/67943e16-3ee2-11e7-853a-4a04160a9cc1.png)

### Steps to Trigger Behavior

 1. Open [example map](https://www.mapbox.com/mapbox-gl-js/example/navigation/) containing navigation controls.
2.  Hover the mouse over the controls to see the artifacts

### Expected Behavior

Map navigation controls should not have artifacts.

### Actual Behavior

Map navigation controls contain artifacts.

**Comment by kkaefer** [comment] 2017-05-23 08:34
I suspect that this is an issue with Chrome/your computer. The zoom controls aren't rendered with WebGL (they're regular DOM elements), so it looks like there's undefined behavior in Chrome's compositor, or possibly corrupted memory, or a corrupted texture on your GPU.

**Comment by mollymerp** [comment] 2017-05-23 10:33
@captainbarbosa does this happen when you quit / re-open chrome? I can't reproduce either.

**Comment by captainbarbosa** [comment] 2017-05-23 16:10
@mollymerp Yeah, I've seen it happen after restarting Chrome, but it doesn't happen every time. I believe @geografa has observed this behavior on his machine as well.

**Comment by stephenson** [comment] 2017-05-23 17:02
I was the original reporter of this and I often too experience it in chrome, but not every time. I have reproduced the bug on multiple machines.

To reproduce for me dont require to hover the controls, it also happens right after load. It appears to me that its always taking content from facebook that I have open in another tab... Its quit strange.

**Comment by jfirebaugh** [comment] 2017-08-17 00:44
Closing; this is a browser bug and nothing something we're able to control.

**Closed by jfirebaugh** 2017-08-17 00:44 UTC
Labels: bug
