### ISSUE TITLE
Fix bug causing queryRenderedFeatures to crash on polygon features that have an `id` field.

### ISSUE THREAD

**Issue by gmaclennan** [mapbox/mapbox-gl-js#4494] opened 2017-03-24 21:40 UTC
**mapbox-gl-js version**: v0.34.0

### Steps to Trigger Behavior

 1. Add a GeoJSON polygon source with non-integer (string) ids
 2. Call `map.queryRenderedFeatures()` on `mousemove`

### Expected Behavior

`map.queryRenderedFeatures()` should return an array of features under the mouse pointer

### Actual Behavior

`Uncaught Error: Unimplemented type: 7`

I have created a JSFiddle of the failing code: https://jsfiddle.net/p78o8exf/6/

This code works fine with v0.32.1 but since v0.33 it is broken. This is valid GeoJSON (checked with `@mapbox/geojsonhint`).

**Comment by jfirebaugh** [comment] 2017-03-25 00:09
@gmaclennan I'm seeing "Uncaught ReferenceError: dataIndex is not defined" when loading that JSFiddle, which seems to be preventing it from getting to the subsequent error. Can you take a look?

**Comment by gmaclennan** [comment] 2017-03-25 06:03
@jfirebaugh thanks for following up, my apologies, I forgot to save changes as I was removing unrelated code. try here: https://jsfiddle.net/p78o8exf/3/

**Comment by gmaclennan** [comment] 2017-03-25 06:04
Here is the data source: https://github.com/digidem/alianza-ceibo-maps/blob/gh-pages/data.json

**Comment by gmaclennan** [comment] 2017-03-25 06:08
One more piece of information: I tried filtering the geojson to only show features with `geometry.type === 'Polygon'` or `MultiPolygon` and I get the same error with each, well, I get a different unimplemented type: 4

**Comment by indus** [comment] 2017-03-27 06:11
Maybe the array properties? https://www.mapbox.com/vector-tiles/specification/#how-to-encode-attributes-that-arent-strings-or-numbers

**Comment by jfirebaugh** [comment] 2017-03-27 23:06
Can you reduce the test case further, e.g. remove everything that's not essential to triggering the bug from the GeoJSON?

**Comment by gmaclennan** [comment] 2017-03-27 23:12
Ok, more pairing down done now, and I found the cause of the bug:

**Comment by anandthakker** [comment] 2017-03-28 12:38
@gmaclennan thanks for isolating it!

Looks like the problem is that the `feature.id`s are strings here, which we currently don't handle correctly (it's a vestige of the fact that the vector tile spec only allows integer IDs, and GeoJSON sources share some implementation details with vector tile sources).  Changing `id` to, e.g., `Math.floor(Math.random() * 1000)` prevents the crash.

This is being tracked at https://github.com/mapbox/mapbox-gl-js/issues/2716, although the test case here demonstrates that (polygon) layers manifest the bug more severely -- crashing rather than simply stripping out the id.

Closing in favor of 2716

**Comment by anandthakker** [comment] 2017-03-29 15:52
Reopening here to track the _crashing_ bug, which @gmaclennan rightly pointed out is distinct from  #2716, which is an enhancement.

**Closed** 2017-04-12 19:19 UTC
Labels: bug, medium priority
