### ISSUE TITLE
await for getClusterLeaves

### ISSUE THREAD

**Issue by transfluxus** [mapbox/mapbox-gl-js#9739] opened 2020-05-29 10:35 UTC
## Motivation

basically described here:
https://github.com/mapbox/mapbox-gl-js/issues/8613

I want to run over a  bunch of clusters make some calculation over their leaves and then set the data of a source. Having a callback in the middle for all clusters makes the whole procedure hard

## Design Alternatives

have an await for getClusterLeaves

## Design

getClusterLeaves with Promise a basically because Callbacks should be dead
 
### Mock-Up

source_layer.getClusterLeaves(cluster_id, cluster.properties.point_count, 0).then(leaves => {}).catch(err => {}) ....

leaves = await source_layer.getClusterLeaves(cluster_id, cluster.properties.point_count, 0)

### Concepts

Promises, many JS developer know promises by now

**Comment by mourner** [comment] 2020-05-29 11:43
Duplicate of #3964

**Closed by mourner** 2020-05-29 11:43 UTC

**Comment by hmendezm** [comment] 2020-11-04 15:55
I am not able to await getClusterleaves. Can someone give an example of how I can wait for the getClusterLeaves? I need to have the leaves before continue running the next code

 await clusterSource.getClusterLeaves(clusterId, total, 0, function (err, aFeatures) {
        that._clusterLeaves = aFeatures;
      });
console.log(that._clusterLeaves );

**Comment by vchrisb** [comment] 2021-06-30 19:56
In my case I created a vue method to wrap the callback based function with a Promise:
```
getClusterLeaves(cluster_id, limit, offset) {
  return new Promise((resolve, reject) => {
    this.map.getSource('locations').getClusterLeaves(cluster_id, limit, offset, (err, features) => {
      if (err) reject(err);
      else resolve(features);
    });
  });
};
```

this could then be used by:
```
await this.getClusterLeaves(feature.properties.cluster_id, feature.properties.point_count, 0);
```
