### ISSUE TITLE
About the layers of lines

### ISSUE THREAD

**Issue by li-0813** [mapbox/mapbox-gl-js#10572] opened 2021-04-14 08:58 UTC
Hello, why can't line layers also have height settings？

**Comment by mourner** [comment] 2021-04-17 16:14
Duplicate of #3993.

**Closed by mourner** 2021-04-17 16:14 UTC

**Comment by li-0813** [comment] 2021-04-20 11:04
_this.map.addLayer({ type: "line",...}) But the line type does not have the property extrusion-height

**Comment by li-0813** [comment] 2021-04-20 11:05
> [＃3993的](https://github.com/mapbox/mapbox-gl-js/issues/3993)重复项。

_this.map.addLayer（{type：“ line”，...}）但是，该线型不具有属性trusion-height
