### ISSUE TITLE
Square Box is appearing around Sdf-Icons

### ISSUE THREAD

**Issue by dollysingh3192** [mapbox/mapbox-gl-js#9961] opened 2020-08-29 19:31 UTC
Hi mapbox-team!

I am creating a symbol Layer in Mapbox having "sdf" attribute true and on zoom level(5-12) i am changing icon-size using Mapbox Expression.

```
const layer: mapboxgl.Layer = {
        "id": accessible,
        "type": "symbol",
        "source": seatSourceName,
        'source-layer': appConfiguration.api.seatSourceLayerName,
        "paint": {
            "icon-color": expression, //This is expression where i am changing color
            "icon-opacity": 1
        },
        "layout": {
            "icon-image": this.iconId,
            "icon-ignore-placement": true,
            "icon-padding": 0,
            "icon-size": [
                'interpolate',
                ['exponential', 2],
                ['zoom'],
                5, 0,
                12, 0.09
            ],
            'icon-allow-overlap': true,
            "icon-rotation-alignment": "viewport",
            "icon-rotate": 0,
            "icon-anchor": "center"
        }
    };
```
The problem is that i can see square background(box) around icon's on smaller zoom level(6 to 10) but on higher zoom level background disappears. This is happening only when I interpolate icon-size between zoom levels'. 

**Replicated** on CodePen as well: https://codepen.io/dollysingh3192/pen/xxVLwWz?editors=0010
(Need to enable **CORS** please before checking)

Try to zoom-in/zoom-out around icon.

If I provide fix "icon-size" everything works fine but this not what I want.

Attaching zoom level around 9 image(Magnified)(In-correct):

<img width="539" alt="Magnifiedzoomlevel5" src="https://user-images.githubusercontent.com/8565108/91644615-5b207a00-ea5b-11ea-85a6-cc520dc378de.png">

Another screenshot:(Incorrect)(Look closer, we can see light color black box)
<img width="545" alt="Screen Shot 2020-08-30 at 1 23 10 AM" src="https://user-images.githubusercontent.com/8565108/91645058-8d33db00-ea5f-11ea-8fee-aa602948ccf3.png">

Attaching zoom level 12(Correct):

<img width="487" alt="zoomlevel12" src="https://user-images.githubusercontent.com/8565108/91644617-68d5ff80-ea5b-11ea-9418-66381ec24744.png">

I am creating sdf icon's using image-sdf npm command (as per: [Stackoverflow Link](https://stackoverflow.com/questions/63299999/how-can-i-create-sdf-icons-used-in-mapbox-from-png))

Attaching sdf icon:
![wheelchairsdf](https://user-images.githubusercontent.com/8565108/91644750-b3a44700-ea5c-11ea-91ae-5ad9df5892b1.png)

I have no idea, what is happening here?  Is there anything wrong with sdf icon created?

@mourner @stevage Any suggestion would be helpful..

**Comment by dollysingh3192** [comment] 2020-08-31 05:12
I want to add more detail on above question.

I am creating sdf using below command:

convert in.png -filter Jinc -resize 400% -threshold 30% \( +clone -negate -morphology Distance Euclidean -level 50%,-50% \) -morphology Distance Euclidean -compose Plus -composite -level 45%,55% -resize 25% out.png


in.png
<img width="117" alt="wheelchair" src="https://user-images.githubusercontent.com/8565108/91684886-5ac8d180-eb76-11ea-8f1e-c22df059b34b.png">

out.png
<img width="117" alt="out" src="https://user-images.githubusercontent.com/8565108/91684900-66b49380-eb76-11ea-8de1-d9a5ede59d5c.png">

Just a guess, is it that the final out.png which is being created is not correct. Need suggestion here!

**Comment by ansis** [comment] 2020-09-02 15:25
Using the `image-sdf` command I would suggest using `--spread 32` and if that doesn't help enough then adding `--downscale 2`.

The issue is that the "blurred edge" of the sdf is not large enough. I think one of these ^ arguments might fix that.

**Comment by dollysingh3192** [comment] 2020-09-03 08:35
Hi @ansis ,

Thanks for the response.

This is correct that the final sdf(out.png) that's been created is not correct. 

**What doesn't work for me.**

1. I tried with the command of image-sdf you suggested.  I am attaching the in.png, out.png and a gif as well. But nothing seems to work!

```
image-sdf in.png --spread 32 --downscale 2 --color black > out.png
```

<img width="113" alt="in" src="https://user-images.githubusercontent.com/8565108/92085200-1c394e00-ede6-11ea-9ef3-8f49e5974064.png">

![out](https://user-images.githubusercontent.com/8565108/92085220-222f2f00-ede6-11ea-8b14-d0d49d5db974.png)

![demo](https://user-images.githubusercontent.com/8565108/92085225-265b4c80-ede6-11ea-95ff-72c5b5af1e10.gif)

2. I refer the issue link https://github.com/elastic/kibana/issues/39715 and suggested imageMagick command, again no luck here!

```
convert in.png -filter Jinc -resize 400% -threshold 30% \( +clone -negate -morphology Distance Euclidean -level 50%,-50% \) -morphology Distance Euclidean -compose Plus -composite -level 45%,55% -resize 25% out.png
```

**What works for me is below:**

I checkout v0.5.0 older tag of Maki https://github.com/mapbox/maki/tree/v0.5.0 and since it is using older version of jsdom and on npm install it gives me lot of error's in terminal. Attaching screenshot:
<img width="639" alt="Errors" src="https://user-images.githubusercontent.com/8565108/92090239-d2a03180-edec-11ea-89d1-e7c8a25a5135.png">

I had to convert complete sdf-render.js file code using @svgdotjs/svg.js and svgdom (as jsdom was not creating svg element) and keep the in.svg in src folder and use the "node sdf-render.js" command and it output the out.png in sdf folder. Using this out.png in my application. It works like magic for me and problem is solved. Attaching screenshot of zoom level 9:

<img width="279" alt="zoom-level-9" src="https://user-images.githubusercontent.com/8565108/92088206-31b07700-edea-11ea-864f-d08de075a271.png">

I have no idea why the sdf creation from image-sdf command wasn't working on lower zoom level.

But Mapbox team I have a humble plea is to please and please add a page on official documentation of mapbox-gl-js on topic **How to create sdf icon** and provide a tool or a standard/official npm module that took's an svg as an input and output as sdf icon just like we have https://labs.mapbox.com/maki-icons/ Maki Icon Editor. 

Mapbox is awesome, no second thoughts. But for this I have to do lot of R&D  and couldn't find anything on a single place regarding sdf creation or if there are already some github links or documentation pages I missed. Please provide me that would be very supportive.

Thank you!

**Comment by dollysingh3192** [comment] 2020-09-09 05:20
Hi Mapbox Team,

I am eagerly waiting for your response!

**Comment by ryanhamley** [comment] 2020-09-09 18:42
> But Mapbox team I have a humble plea is to please and please add a page on official documentation of mapbox-gl-js on topic How to create sdf icon and provide a tool or a standard/official npm module that took's an svg as an input and output as sdf icon just like we have https://labs.mapbox.com/maki-icons/ Maki Icon Editor

Hi @dollysingh3192 we do have some [documentation on using SDFs with Mapbox](https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/)! 

I think creating the SDF is beyond the scope of what we do at Mapbox though and certainly beyond the scope of the GL JS team. Our library consumes SDFs but we have no particular opinion on how they are created. Creating and maintaining a tool to create SDFs would require significant maintenance overhead that our team likely doesn't have the resources for. Plus, tools like this do exist, i.e. `image-sdf` as mentioned above.

Thanks for the kind words. I'm going to close this issue as it seems like you've solved the problem you were facing. If that's not true or you encounter other problems, you can comment and re-open the issue.

**Closed by ryanhamley** 2020-09-09 18:42 UTC

**Comment by assemblethis** [comment] 2020-12-11 16:59
I had this same issue in DEV with a halo appearing around all my SDF icons (I used image-sdf to create them). The issue did not occur when using the Mapbox SDK for Android but it did occur when using the Mapbox SDK for web apps. The issue went away when I created smaller SDF icons that didn't need to be resized. I was using icons that were 500 px by 500 px and reducing them to 25 px by 25 px.

```
map.addLayer({
          .....
            layout: {
              'icon-image': symbol,
              'icon-size': 0.05,
              'icon-allow-overlap': true,
            },
      ............

```
So for me the issue seemed to be related to the extreme resizing of the icons, e.g. resizing icons to 1/20 of their original size.

**Comment by alexandermorgan** [comment] 2022-01-06 22:31
> > But Mapbox team I have a humble plea is to please and please add a page on official documentation of mapbox-gl-js on topic How to create sdf icon and provide a tool or a standard/official npm module that took's an svg as an input and output as sdf icon just like we have https://labs.mapbox.com/maki-icons/ Maki Icon Editor
> 
> Hi @dollysingh3192 we do have some [documentation on using SDFs with Mapbox](https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/)!
> 
> I think creating the SDF is beyond the scope of what we do at Mapbox though and certainly beyond the scope of the GL JS team. Our library consumes SDFs but we have no particular opinion on how they are created. Creating and maintaining a tool to create SDFs would require significant maintenance overhead that our team likely doesn't have the resources for. Plus, tools like this do exist, i.e. `image-sdf` as mentioned above.
> 
> Thanks for the kind words. I'm going to close this issue as it seems like you've solved the problem you were facing. If that's not true or you encounter other problems, you can comment and re-open the issue.

I would ask you to please reconsider adding sdf image documentation. The page you have linked does not show how to get a regular .png file into the right sdf format, whereas that is the stumbling block for everyone. It just explains how to apply paint properties and that's no different than any other part of the mapbox style api. Getting workable sdf icons continues to be by far the most difficult thing using mapbox. I've spent days trying to generate basic icons and my end result is mediocre and buggy. Other people somehow manage to do it well so I must not be generating the images properly, but there's no example of how to do this. There's no need to have an officially supported and maintained solution, but at least have one example of a non-maki icon, normal png or svg that gets changed into an sdf image, and then manipulated. This could be just a codepen/codesandbox or something like, something very simple and straight-forward. This would be a game changer!

**Comment by dollysingh3192** [comment] 2022-01-07 03:48
Hey @alexandermorgan ,

I also struggled a lot on SDF creation and I added everything on single place after doing lot of R&D on stack-overflow(Link added below):

https://stackoverflow.com/questions/63299999/how-can-i-create-sdf-icons-used-in-mapbox-from-png/63314688#63314688

Hope this will help!

**Comment by matonga** [comment] 2022-12-05 17:33
I think the issue is with Mapbox not publishing the required parameters for proper SDF generation. Those can be found in TinySDF documentation:

radius: 8 pixels
cutoff: 25% (0..191 = outside, 192..255 = inside)

[Here is the file](https://github.com/mapbox/mapbox-gl-js/files/10156508/test2.zip) I'm using just in case it helps anyone else. It is an .html file that borrows Javascript code from TinySDF but converts .svg instead (or .png or anything with transparency btw). Edit the source (svg.src = ...), run in a browser, right click and save.
