### ISSUE TITLE
icon-offset and icon-translate has icons rendered behind other layers

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#1882] opened 2016-01-03 03:30 UTC
I'm trying to realise a point layer with multiple symbol icons per point. To achieve this I've tried using the layout/paint properties icon-offset and icon-translate and while both do the trick, they both suffer from the fact that the adjusted icons are overpainted by other layers occasionally (tile edges?). Is this a bug or is it not meant to be used like this?

![icon-offset](https://cloud.githubusercontent.com/assets/1205805/12077141/9d2cec2e-b1d2-11e5-9640-0faae6c2c056.gif)

**Comment by peterqliu** [comment] 2016-01-03 05:26
#757

**Comment by peterqliu** [comment] 2016-01-04 09:22
This seems like a dupe of 757, so I will close for now. Feel free to reopen if it is distinct.

**Comment by averas** [comment] 2016-01-15 14:46
This was supposedly fixed as part of #757 and released with v0.12.3 but still occurs, so it was not the same issue. Please reopen or confirm that icon offset/translate is not meant to be used this way.

To reproduce, have a symbol layer with:

<code>
"paint": {
	"icon-translate": [25, 0]
}
</code>

**Comment by averas** [comment] 2016-01-15 15:31
http://codepen.io/anon/pen/yezaGy

**Comment by averas** [comment] 2016-01-15 15:35
This may somehow be related to the GeoJSON source and perhaps <code>geojson-vt</code> because even though I got the impression I saw similar behaviour when restyling symbols in the regular streets vector tiles I had a hard time reproducing the exact same behaviour there.

@mourner ?

**Comment by averas** [comment] 2016-01-15 17:42
Okay, perhaps the problem was quite obvious.. just setting <code>icon-allow-overlap</code> and <code>icon-ignore-placement</code> to false mitigates the problem. The reason I had one if these set to true was however that I wanted to have the symbols in this particular layer to be able to rendered on top of each other, but it seems I have to choose.

I've updated the codepen. It seems there is no way to have the symbols being able to overlap each other without having the symbols sliding in under tile edges..

http://codepen.io/anon/pen/VeMPyL

**Comment by lucaswoj** [comment] 2016-01-15 21:12
This behavior was not fixed by #757. 

The relevant bit of code is in [`draw_symbol`](https://github.com/mapbox/mapbox-gl-js/blob/master/js/render/draw_symbol.js#L18)

There's no easy way to prevent drawing the symbols twice (once in each overlapped tile).

**Comment by ansis** [comment] 2016-01-20 02:33
The real solution will be to make your style possible without `-ignore-placement` or `-allow-overlap`, but a temporary workaround is to increase the buffer size of the geojson tiles created internally.

Maybe try setting "buffer" to 500 or even bigger:

```
 map.addSource("markers", {
        "type": "geojson",
        "buffer": 500,
        "data": {
```

**Comment by averas** [comment] 2016-01-20 07:10
@ansis Ah, thanks for that!

Am I then right in the assumption that this is related to the GeoJSON source itself? I took my data and served it with vector tiles instead and did not see traces of the same behaviour (although I didn't really test it thoroughly)..

**Comment by ansis** [comment] 2016-01-20 19:27
Yes, it's mostly a geojson issue. The equivalent `buffer` parameter in vectortiles is much larger by default.

**Comment by ansis** [comment] 2016-03-31 17:25
The default buffer size was increased in https://github.com/mapbox/mapbox-gl-js/pull/2026

**Closed by ansis** 2016-03-31 17:25 UTC
