### ISSUE TITLE
incorrect layer rendering when the map is tilted

### ISSUE THREAD

**Issue by ZhenanH** [mapbox/mapbox-gl-js#1965] opened 2016-01-21 22:34 UTC
before 0.12.3, the layer was rendered correctly as below

![screen shot 2016-01-21 at 5 33 54 pm](https://cloud.githubusercontent.com/assets/2914157/12496681/304a05dc-c065-11e5-8ed6-0a1b688a6f2b.png)

but in both 0.12.3 and 0.12.4, the layer was not rendered correctly when the map is tilted
![screen shot 2016-01-21 at 5 30 18 pm](https://cloud.githubusercontent.com/assets/2914157/12496608/ce82fc3c-c064-11e5-8ebc-5f69ba2843ec.png)

**Comment by ansis** [comment] 2016-01-21 22:55
thanks for reporting the bug @ZhenanH 

Can you share the example style that this issue can be reproduce with?
What browser are you using?
What is the value for `Depth / Stencil Bits` listed at https://www.browserleaks.com/webgl? (open the page in the same browser you see the bug in)

**Comment by ZhenanH** [comment] 2016-01-22 15:34
I am using Chrome Version 47.0.2526.111 (64-bit)
Depth / Stencil Bits:	[24, 8]

Here is the example style:

var  simple = {
                "version": 8,
                "sources": {
                    "osm": {
                        "type": "vector",               
                        "tiles": ["http://152.144.97.202:3000/na/{z}/{x}/{y}.mvt"]
                    }
                },
                "layers": [
                    {
                        "id": "background",
                        "type": "background",
                        "paint": {
                            "background-color": "lightgray"
                        }
                    }, {
                        "id": "water",
                        "type": "fill",
                        "source": "osm",
                        "source-layer": "water",
                        "filter": ["==", "$type", "Polygon"],
                        "paint": {
                            "fill-color": "#3887be"
                        }
                    },
                    {
                        "id": "places",
                        "type": "fill",
                        "source": "osm",
                        "source-layer": "places",
                        //"filter": ["==", "$type", "Point"],
                        "paint": {
                            "fill-color": "black"
                        }
                    },
                    {
                      "id": "city-label",
                      "source": "osm",
                      "source-layer": "places",
                      "min-zoom": 10,
                      "max-zoom": 14,
                      "type": "symbol",
                      "layout": {
                        "text-field": "{name}",
                        "text-max-width": 10,
                        "text-letter-spacing": 0.1,
                      },
                      "paint": {
                        "text-color": "black",
                        "text-halo-color": "rgba(255,255,255,0.5)"
                      }
                    }
]};
var map = new mapboxgl.Map({
                container: 'map',
                style: simple, 
                center: [-73.983807,40.749540], // starting position
                zoom: 12,// starting zoom
                minZoom:3
            });


   map.addLayer({
                            "interactive":true,
                            "id":id,
                            "type":"fill",
                            "source":"osm",
                            "source-layer":id,
                            "paint": {
                                "fill-color": "rgba(255, 255, 0, 0.5)",
                                "fill-outline-color":"rgba(145, 145, 0, 0.8)"
                                }
                    
                        });

**Comment by lucaswoj** [comment] 2016-01-22 15:35
_Maybe_ related to #1952

**Comment by ansis** [comment] 2016-01-26 01:16
@ZhenanH I'm unable to connect to the source in you're example. When I substituted the source with another one I couldn't reproduce the problem.

If you have another computer, can you see if you can reproduce the error there?
Could you paste the full contents of https://www.browserleaks.com/webgl in a [gist](https://gist.github.com/)?

**Comment by ZhenanH** [comment] 2016-01-26 16:53
@ansis 
here is the [gist](https://gist.github.com/ZhenanH/4e54c748b7ee67468452)

You can also use this source: "http://vector.mapzen.com/osm/all/{z}/{x}/{y}.mvt?api_key=vector-tiles-LM25tq4" from Mapzen
![screen shot 2016-01-26 at 11 39 46 am]
(https://cloud.githubusercontent.com/assets/2914157/12587414/3b0207f2-c422-11e5-8262-dae941f1d0f4.png)

I also found another bug: first zoom in enough to see the buildings, and when I start moving the map with mouse, the map will stick with the mouse and wouldn't let go.

**Comment by ZhenanH** [comment] 2016-01-27 15:38
oh, the layer example here is like
"layers":[
{
                        "interactive":true,
                        "id":"buildings_tall0",
                        "type":"fill",
                        "source":"osm",
                        "source-layer":"buildings",
                         "filter": [">=", "height", 200],
                        "paint": {
                            "fill-color": "rgba(0, 125, 250, 1)"
                            }
                    },
                    {
                        "interactive":true,
                        "id":"buildings_tall1",
                        "type":"fill",
                        "source":"osm",
                        "source-layer":"buildings",
                         "filter": [">=", "height", 150],
                        "paint": {
                           "fill-color": "rgba(0, 125, 250, 0.8)"
                            }
                    },
                    {
                        "interactive":true,
                        "id":"buildings_tall2",
                        "type":"fill",
                        "source":"osm",
                        "source-layer":"buildings",
                         "filter": [">=", "height", 50],
                        "paint": {
                            "fill-color": "rgba(0, 125, 250, 0.6)"
                            }
                    },
                     {
                        "interactive":true,
                        "id":"buildings_tall3",
                        "type":"fill",
                        "source":"osm",
                        "source-layer":"buildings",
                         "filter": [">=", "height", 30],
                        "paint": {
                            "fill-color": "rgba(0, 125, 250, 0.4)"
                            }
                    },
                     {
                        "interactive":true,
                        "id":"buildings_tall4",
                        "type":"fill",
                        "source":"osm",
                        "source-layer":"buildings",
                         "filter": [">=", "height", 20],
                        "paint": {
                            "fill-color": "rgba(0, 125, 250, 0.3)"
                            }
                    }, {
                        "interactive":true,
                        "id":"buildings_tall5",
                        "type":"fill",
                        "source":"osm",
                        "source-layer":"buildings",
                         "filter": [">=", "height", 10],
                        "paint": {
                            "fill-color": "rgba(0, 125, 250, 0.2)"
                            }
                    },
                     {
                        "interactive":true,
                        "id":"buildings_tall2",
                        "type":"fill",
                        "source":"osm",
                        "source-layer":"buildings",
                         "filter": [">=", "height", 0],
                        "paint": {
                            "fill-color": "rgba(0, 125, 250, 0.1)"
                            }
                    }]

**Comment by ansis** [comment] 2016-03-31 17:23
This was fixed by https://github.com/mapbox/mapbox-gl-js/pull/2319 and released in v0.16.0

**Closed by ansis** 2016-03-31 17:23 UTC
