### ISSUE TITLE
queryRenderedFeatures returning 3d features after 2d features, regardless of appearance

### ISSUE THREAD

**Issue by danvk** [mapbox/mapbox-gl-js#7883] opened 2019-02-06 22:47 UTC
**mapbox-gl-js version**: 0.53-beta1

**browser**: Chrome 71

### Steps to Trigger Behavior

 1. Open the new [`extrusion-query.html`](https://github.com/mapbox/mapbox-gl-js/blob/d074dd47be3c834b7e802dd9647aa824851cba49/debug/extrusion-query.html) demo page.
 2. Remove the second parameter to `queryRenderedFeatures` on [line 55](https://github.com/mapbox/mapbox-gl-js/blob/d074dd47be3c834b7e802dd9647aa824851cba49/debug/extrusion-query.html#L55), which restricts the layers being queried.
 3. Observe that the order of features returned from `queryRenderedFeatures` no longer matches the appearance in the map rendering.

### Link to Demonstration

Here's a GIF demonstrating the issue:

![3d hover bug](https://user-images.githubusercontent.com/98301/52378618-2a6e8f00-2a36-11e9-9d29-2e24a114e0cd.gif)

The red feature is the first returned by `queryRenderedFeature`, the green one is the second and blue is third or later. The extruded building (which is always on top visually) is not always returned first. Depending on what's underneath it, it might be returned second.

I realize this is a new feature in a beta release, but I'm very excited to start using it and this might be a showstopper for us.

### Expected Behavior

With a mix of 2d and 3d layers, the order of features returned by `queryRenderedFeatures` doesn't necessarily match the order of appearance.

### Actual Behavior

The first feature returned by `queryRenderedFeatures` should always the the one on top, even in a mix of 2d and 3d layers.

**Comment by danvk** [comment] 2019-02-07 20:27
Conceptually is seems like a `fill` layer should be treated the same as a `fill-extrusion` layer with `fill-extrusion-base = fill-extrusion-height = 0`.

**Comment by peterqliu** [comment] 2019-02-15 23:17
I actually don't quite see this as a bug -- as a rule, `queryRenderedFeatures` queries **first** in order of layers in the layer stack, and only within an extrusion layer does it return in order of 3D space. `qRF` wasn't built to be a 3D raycaster.

>I'm very excited to start using it and this might be a showstopper for us.

this *seems* easily resolved by either taking the list of features and sorting extrusions to be first, or limiting the query to the extrusion layer

**Comment by andycalder** [comment] 2019-02-18 14:56
I just had a look at this and I was able to reproduce this issue. The `fill-extrusion` layer is indeed "on top" according to the layer order so this does appear to be a bug.

**Comment by andycalder** [comment] 2019-02-18 18:22
I've had a look at the implementation and currently `fill-extrusion` features are always returned _last_ regardless of layer order. Perhaps the easiest solution would be to always return `fill-extrusion` features _first_ (since those layers will always be on top anyway).

The the sorting logic is located [here](https://github.com/mapbox/mapbox-gl-js/blob/6d529c74ac3524749bfb50a4e6f5c991f4d058c7/src/style/style.js#L944).

**Comment by danvk** [comment] 2019-02-19 17:09
Thanks for looking into this @peterqliu and @andycalder. From the perspective of a user of this API, ordering `fill-extrusion` features first makes a lot more sense, especially when I haven't provided an explicit list of layers to `queryRenderedFeatures`.

**Comment by ansis** [comment] 2019-02-26 19:27
@danvk and @andycalder thanks for report and digging into this!

It is a bug. The query order should match the render order. I've opened a pull request to fix this here in case you are interested in testing: https://github.com/mapbox/mapbox-gl-js/pull/7953

**Closed** 2019-02-27 15:35 UTC
Labels: bug :beetle:
