### ISSUE TITLE
Pinch & Zoom is off center on touch devices (v0.45.0)

### ISSUE THREAD

**Issue by dave11mj** [mapbox/mapbox-gl-js#6722] opened 2018-05-23 20:00 UTC
**mapbox-gl-js version**: `v0.45.0`

**browser**:
- Chrome (Windows 10) with a touch monitor (Dell S2240T)
- Safari (iPhone 7)
- Safari (iPad)
- Any other touch enabled device (specially large screen displays)

### Steps to Trigger Behavior

 1. Place your fingers around the intended target to initiate zoom
 2. Expand your fingers in a pinch & zooming gesture
 3. Observe target moves away from the center of your fingers

### Link to Demonstration

![v0-45-0-demo](https://user-images.githubusercontent.com/6619371/40448684-39133d2a-5ea4-11e8-8dfb-bd7552f4b065.gif)

[Demo Github Page Using v0.45.0](https://dave11mj.github.io/github-issues-demos/mapbox/zooming-out-of-center-v0-45-0.html)
[Demo Source](https://github.com/dave11mj/github-issues-demos/blob/master/mapbox/zooming-out-of-center-v0-45-0.html)

Note that in the demo above when you try to pinch and zoom on the "Capitol Hill Fountain"
it goes off center instead of remaining between the fingers.

![v0-44-2-demo](https://user-images.githubusercontent.com/6619371/40447887-f4623fc0-5ea1-11e8-9f26-689dfc5eff95.gif)

[Demo Github Page Using v0.42.2](https://dave11mj.github.io/github-issues-demos/mapbox/zooming-out-of-center-v0-42-2.html)
[Demo Source](https://github.com/dave11mj/github-issues-demos/blob/master/mapbox/zooming-out-of-center-v0-42-2.html)

Note that in the demo above when you try to pinch and zoom on the "Capitol Hill Fountain"
it stays between fingers. However, you are unable to pan with more than one finger.

### Expected Behavior

Target should remain centered between the user's fingers without removing the ability to pan using more than one finger.

### Actual Behavior

Target moves off center as the user zooms into it.

**Comment by andest01** [comment] 2018-05-23 20:08
I am able to reproduce this error on my setup as well.
- Chrome Version 66.0.3359.181 (Official Build) (64-bit)
- (Windows 10) 
- Dell P2418HT touch device

**Comment by jliebrand** [comment] 2018-08-08 08:06
This makes using pinch zoom pretty crappy on mobile. Any update on a potential fix here?

**Comment by jliebrand** [comment] 2018-08-17 11:01
Friendly ping. Any plans for a fix?

**Comment by pakastin** [comment] 2018-08-24 05:10
I have a simple solution waiting for a pull request which fixes this nicely 😎

**Comment by pakastin** [comment] 2018-08-24 05:17
You can try it out here: https://beta.ilmailukartta.fi/
(https://beta.ilmailukartta.fi/js/mapbox-gl.js)

**Comment by jliebrand** [comment] 2018-08-24 07:32
Awesome!

**Comment by ryanhamley** [comment] 2018-08-24 19:02
closed by #7191

**Closed by ryanhamley** 2018-08-24 19:02 UTC
Labels: bug :beetle:

**Comment by jliebrand** [comment] 2018-09-17 08:37
This is now much improved! Thanks! There's still a little glitch at the start of the pinch gesture... it seems to first move the map for a certain threshold of pixels, and then it computes the correct centre, jumps a little, and from there on in the pinch works fine.

Any thoughts on that initially little "jump"

**Comment by pakastin** [comment] 2018-09-17 09:47
Yeah, it's basically because of this: https://github.com/mapbox/mapbox-gl-js/issues/7196

If you move the map with one finger and then add a second finger, multitouch event overlaps with the single touch event and creates the glitch..

**Comment by msbarry** [comment] 2018-09-17 10:35
Also might be related to a fix I made https://github.com/mapbox/mapbox-gl-js/issues/1832 - try setting  setting `clickTolerance` option when you create the map to 0.

**Comment by Mindcraft1** [comment] 2018-10-06 21:11
Hello
I'm encountering exactly this issue when using mapbox-gl as node_module import. 

`npm i mapbox-gl`
`import mapboxgl from 'mapbox-gl'` 

Updated package today for double check.

Does this require a new issue to be opened?

**Comment by pakastin** [comment] 2018-10-07 04:17
You mean the original issue? How to reproduce?

**Comment by ryanhamley** [comment] 2018-10-08 18:29
Hi @Mindcraft1 this was fixed as of v0.49.0 so if you have that installed, it should work as expected. You haven't really given enough information for us to help you out here. If you can confirm that you have the correct version installed and are still seeing a bug, you can open a new ticket with all the information in the template filled out and a minimal reproduction of the bug (in JSBin for example) so that we can diagnose what is going on.

**Comment by Mindcraft1** [comment] 2018-10-10 21:44
Hi I opened #7397
