### ISSUE TITLE
fix featuresIn when map is rotated or tilted

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2050] opened 2016-02-04 00:11 UTC
`featuresIn` does not return the correct features when the map is rotated or tilted.

`featuresIn` accepts a bounding box in screen points. When the map is rotated the same bounding box in tile coordinates is not axis-aligned. The bounding box needs to be represented with four corners, not just a minX,maxX,minY,maxY.

**Comment by lucaswoj** [comment] 2016-02-04 01:41
Duplicate of #1822

**Closed by lucaswoj** 2016-02-04 01:41 UTC
