### ISSUE TITLE
Official example "Display a satellite map" crashes

### ISSUE THREAD

**Issue by knutole** [mapbox/mapbox-gl-js#2180] opened 2016-02-24 16:39 UTC
### Context

* **mapbox-gl-js version**: `v0.14.2`

* **Chrome Browser version:** `Version 48.0.2564.116 (64-bit)`
* **Hardware:** 

![screen shot 2016-02-24 at 5 36 04 pm](https://cloud.githubusercontent.com/assets/2197944/13292708/2413ccda-db1d-11e5-9727-2256e664da22.png)

### Report

The official _"Display a satellite map"_ [example](https://www.mapbox.com/mapbox-gl-js/example/satellite-map/) throws an error after zooming, and the map turns completely black (or is just stuck on last tileset, with no interaction possible):

![screen shot 2016-02-24 at 5 34 33 pm](https://cloud.githubusercontent.com/assets/2197944/13292655/e5189be6-db1c-11e5-80fa-44f064419789.png)

![screen shot 2016-02-24 at 5 37 21 pm](https://cloud.githubusercontent.com/assets/2197944/13292762/50931a9a-db1d-11e5-9ccf-c8fcb597fc22.png)

**Getting this error in the console:**
![screen shot 2016-02-24 at 5 31 05 pm](https://cloud.githubusercontent.com/assets/2197944/13292640/d948ec76-db1c-11e5-81f2-25eda6c58230.png)

**Link to example**:
https://www.mapbox.com/mapbox-gl-js/example/satellite-map/

**Comment by lucaswoj** [comment] 2016-02-24 16:42
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2167

**Closed by lucaswoj** 2016-02-24 16:42 UTC
