### ISSUE TITLE
Fix DataCloneError in Firefox and IE11

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#2559] opened 2016-05-11 16:19 UTC
On firefox we get:

> DataCloneError: The object could not be cloned.

This error is encountered reliably on Firefox 43-46, hitting 217 users and 1.1k times so far. Occurs within the Actor object.

**Comment by mourner** [comment] 2016-05-18 14:03
Do you have a longer stack trace?

**Comment by mattp88** [comment] 2016-06-30 15:57
I've encountered this issue on Firefox 47 as well as IE 11.

**Comment by mourner** [comment] 2016-08-03 13:33
This is a race condition that happens when `reload tile` is called on a new tile that is still in a `loading` state. `reload tile` assumes that a tile was already loaded and keeps its `rawTileData`, which is then transferred back to the main thread to reparse, but if it's still loading, `rawTileData` will be `undefined`, and will get to the list of transferables as `undefined` in `WorkerTile.parse`. 

I'm looking into a good way to fix this while not introducing any new race conditions — the tile loading workflow is very complicated currently... cc @lucaswoj @anandthakker

**Comment by mourner** [comment] 2016-08-03 13:55
Here's the timeline of the race condition:

1. Main thread requests a tile load.
2. Main thread requests a tile reload.
3. Worker is done loading the tile.
4. Worker receives the tile reload request and proceeds since the tile is loaded, but `rawTileData` is undefined because tile was not loaded at the time reload request was made.

A possible solution would be to defer all tile reload requests on tiles with `loading` state until the tile is loaded. This gets tricky though — you have to manage a tile state consistently even if it receives multiple load/reload/unload requests in quick succession.

**Comment by mourner** [comment] 2016-08-03 13:57
Somewhat flaky way to reproduce on the debug page (both 0.21.0 and master): open the devtools console in Chrome and start zooming the map back and forth while constantly calling `map.style.sources.composite.reload()`. In about 10-30s, you will get the error.

**Comment by anandthakker** [comment] 2016-08-03 15:57
As an alternative to deferring/queuing `load`/`reload`/`unload` requests, what about making `reload`'s semantics into something like:

```js
if (tile.state === 'loading') {
  abort()
  load()
}
else { /* normal reload */ }
```

**Comment by mourner** [comment] 2016-08-03 20:12
@anandthakker that's an idea too! But note that `abortTile` is async as well so there can be a race condition when trying to abort and then load.

**Comment by anandthakker** [comment] 2016-08-03 20:19
> But note that abortTile is async as well so there can be a race condition when trying to abort and then load.

Yeah, true -- and I think abortTile currently doesn't even accept a callback, although that's easy enough to change.

FWIW, I _think_ that the actual messages send by `postMessage` do arrive in order, and on the worker side, the abort task doesn't actually do anything async... but that's not to say we should actually bake those assumptions into the code, since one or more of these things could change

**Closed** 2016-08-10 16:30 UTC
Labels: high priority, platform-specific bug
