### ISSUE TITLE
Mouseover event does not fire where polygons within a Multipolygon feature overlap

### ISSUE THREAD

**Issue by malwoodsantoro** [mapbox/mapbox-gl-js#10020] opened 2020-10-06 17:26 UTC
**mapbox-gl-js version**: v1.12.0

**browser**: Chrome 85.0.4183.121

### Steps to Trigger Behavior
![Kapture 2020-10-06 at 10 22 21](https://user-images.githubusercontent.com/19801577/95238093-e0671f00-07bd-11eb-875b-553457d779b0.gif)

 1. Create a Multipolygon feature with polygons that overlap
 2. Add it to the map as a GeoJSON source
 3. Try to trigger some type of event when mousing over the Multipolygon feature and see that the event does not fire where the polygons overlap

### Link to Demonstration

https://jsfiddle.net/moyLtc7q/

### Expected Behavior

The event for the layer still fires where the polygons overlap

### Actual Behavior

The event does not fire where the polygons overlap

Related to https://github.com/mapbox/mapbox-gl-js/issues/9964

cc @mourner

**Comment by mourner** [comment] 2020-10-06 17:28
I think this is not just related but a duplicate of #9964, since the underlying issue is the same.

**Closed** 2020-10-06 17:56 UTC
