### ISSUE TITLE
'load' event is delayed if window not in focus

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#7780] opened 2019-01-16 22:11 UTC
I believe this has been reported a few times [before](https://github.com/mapbox/mapbox-gl-js/issues/6076) but not with easily reproducible steps. 

So the `load` event does fire but only when the tab/window is in focus. If the window/tab is not in focus, the execution is delayed.

Example:
https://jsfiddle.net/iaezzy/5bzymapg/3/

1. Visit the page
2. Wait for the alert
3. Visit the page again (or just 'Run')
4. Immediately move to a different tab or window
5. There's no alert until you return to the window.

**Comment by 3zzy** [comment] 2019-01-16 23:10
@ryanbaumann Tested on Mac (Safari, Chrome, Firefox) and Windows (Chrome, IE11).

**Comment by mourner** [comment] 2019-01-22 15:15
This is expected behavior, so I'm inclined to close the issue. From the documentation:

> Fired immediately after all necessary resources have been downloaded and the first visually complete rendering of the map has occurred.

The "first visually complete rendering" does not occur until the map is in focus because the browser knows you won't see the result while it's in background, and saves resources this way.

**Closed by mourner** 2019-01-22 15:15 UTC
Labels: needs information :pray:
