### ISSUE TITLE
403 Forbidden (from ServiceWorker) when loading tiles

### ISSUE THREAD

**Issue by tiotdev** [mapbox/mapbox-gl-js#8859] opened 2019-10-11 05:48 UTC
**mapbox-gl-js version**: 1.4.0

**browser**: Chrome/any

### Steps to Trigger Behavior

 1. Implement mapbox-gl and a service worker
 2. Visit the site - the tiles load
 3. Revisit from the same browser a few days later - the tiles are blank, the network request to `https://api.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7.json...` returns `403 Forbidden (from ServiceWorker)` and `403 Forbidden (from disk cache)`

### Link to Demonstration
https://travelfeed.io/map

### Expected Behavior
The tiles load, even when loading from cache/service worker (works for Google maps)

### Actual Behavior
The tiles don't load when revisiting the site

**Comment by mourner** [comment] 2019-10-11 06:50
Hard to say what's going on, is it possible that the 403 response was cached from network before you requested it?

**Comment by asheemmamoowala** [comment] 2019-10-11 17:53
This is not reproducing any longer. It's possible that there was a temporary issue with the service, but that seems to have been resolved now. 

Closing since there doesn't seem to be any actionable change for this project.

**Closed by asheemmamoowala** 2019-10-11 17:53 UTC
Labels: needs investigation :mag:

**Comment by tiotdev** [comment] 2019-10-19 15:43
This is still reproducing, not a temporary issue

**Comment by tiotdev** [comment] 2019-11-13 07:11
The problem seems to only occurs in Brave Browser

**Comment by ryanhamley** [comment] 2019-11-13 20:36
I can reproduce this behavior in Brave. What's actually getting the 403 Forbidden error is downloading the style from `api.mapbox.com`. The first time that a style is downloaded it works as expected but on all subsequent attempts to get the style, a 403 is returned. You can confirm this directly by going to the style URL in the browser. You'll see the JSON on the first try and the error after that. Since you can replicate this outside the map, that suggests to me that it's not a problem with GL JS. I'm not sure if this is an issue with something `api.mapbox.com` is doing or a bug in Brave.

**Comment by tiotdev** [comment] 2019-12-19 12:34
When analysing the requests in Chrome vs Brave, I found that Brave spoofs the referrer, changing it to "api.mapbox.com". Adding this to the whitelisted domains for my mapbox API key did the trick.

**Comment by nk9** [comment] 2020-06-18 20:22
Just ran into this, was driving me crazy. Once I saw this spelled out, I realized that this solution was hinted at in [the documentation](https://docs.mapbox.com/accounts/overview/tokens/#add-url-restrictions-to-access-tokens):

> If no allowed URLs are provided, the token will work for requests originating from any URL. Depending on your use case, you might need to add `api.mapbox.com` to your access token's allowed list.

**Comment by gazpachu** [comment] 2021-11-17 23:47
I'm getting also the 403 when trying to use Mapbox GL JS in a Cordova app. Adding `api.mapbox.com` didn't fix it
