### ISSUE TITLE
Dropped tiles in Windows 7

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#1380] opened 2015-07-20 18:35 UTC
I'm seeing tiles dropped as in the screen shots below in Chrome 43.0.2357, FF 33.1, but *not* IE 11.   I can't discern any pattern.

![bug1](https://cloud.githubusercontent.com/assets/4974151/8783741/bcd22f18-2eeb-11e5-9a18-7bca1690354b.PNG)

![bug3](https://cloud.githubusercontent.com/assets/4974151/8783768/e91c689a-2eeb-11e5-8450-f663a90fc769.PNG)

In the console, as soon as I set `myMap.debug = true`, the missing features appear:

![bug2](https://cloud.githubusercontent.com/assets/4974151/8783757/dc15a8fa-2eeb-11e5-95dd-98730e2beb41.PNG)

Also, this is pretty weird--just panning the map back and forth brings tiles in and out:

![bug5](https://cloud.githubusercontent.com/assets/4974151/8783778/fb736d86-2eeb-11e5-9be9-f22a7bff558c.gif)

Other info:
 - No console errors.
 - The boundaries that are missing in the screen shots above are from a vector tile source, but in other cases I've also seen this happen with a geojson source, and also for the vector tile source backing the yellow dots.

**Comment by anandthakker** [comment] 2015-07-20 18:37
Possible duplicate of #930 

Also: I've got this happening on 03b02a3b06f2b3462c5be6fd2e319a9c0f657dce (latest commit at the time of this report), but also back at 37145b8b9bb0de022811ad46f3e89a2714896b18.

**Comment by anandthakker** [comment] 2015-07-20 20:00
I have a minimal(ish) repro of the problem, but it's got some (annoyingly) proprietary data so I shouldn't post it here.  DM me on twitter/slack/email and I can send it.

This minimal case has two sources -- district boundaries, and a bunch of village points.  The latter were generated with tippecanoe (post @tmcw's recent fix re: custom extents).  Each source is referenced in just one style.  The village points style includes a `filter`; weirdly, if I remove the filter, the issue ceases to happen.

**Comment by lucaswoj** [comment] 2015-10-06 20:59
@anandthakker Are you still seeing this bug? Taking a look at this and #930 now.

**Comment by lucaswoj** [comment] 2015-10-06 22:06
Closing as a duplicate of #930 until we have reason to believe otherwise.

**Closed by lucaswoj** 2015-10-06 22:06 UTC
