### ISSUE TITLE
Can't set state on desired feature

### ISSUE THREAD

**Issue by cazzer** [mapbox/mapbox-gl-js#9400] opened 2020-03-10 16:07 UTC
**mapbox-gl-js version**: 1.8.1, (via [react-map-gl@5.2.3](https://github.com/uber/react-map-gl))

### Question
In short, I'd like to set the feature state on a specific feature, (in this case a building). In [mapbox-streets-v8](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/) buildings do not have unique IDs, leaving me with few other options.

An approach that seemed obvious is to use `queryRenderedFeatures` to get the specific building of interest, followed by using `setFeatureState` to add a property such as `{highlight: true}`. Since `setFeatureState` only uses IDs when updating features, this ends up being applied to countless features and results in many buildings being highlighted.

I can see a few solutions:
1. Somehow generate a new vector layer with unique IDs, (but I'm not sure how to approach that)
2. Extend `setFeatureState` to support an interface more similar to `queryRenderedFeatures`

My, (hopeful), workaround is copying feature data to a new data structure and rendering a new source/layer when I want to highlight features, but this feels heavy considering how close the library gets to my exact use case. I would appreciate any guidance on the problem.

### Links to related documentation
Others have asked this question on [Stackoverflow](https://stackoverflow.com/questions/56493095/mapbox-layer-features-duplicate-ids) and [GIS Stackexchange](https://gis.stackexchange.com/questions/327657/mapbox-gl-filter-features-by-id-no-unique-ids). It would appear this is possible in [Mapbox for Unity](https://docs.mapbox.com/unity/maps/overview/map-features/) but I've found no references for Mapbox Studio yet.

**Comment by cazzer** [comment] 2020-03-10 16:10
This may be a duplicate of #8284.

**Comment by sgolbabaei** [comment] 2020-03-10 16:52
Thank you @cazzer for opening this issue. It looks like it is a duplicate of #8284. Some workarounds have been discussed in #8284. If you feel the issue reported here is different, please share more details and we can reopen.

**Closed by sgolbabaei** 2020-03-10 16:52 UTC
Labels: needs discussion :speech_balloon:
