### ISSUE TITLE
Calling map.setStyle() removes all layers and sources

### ISSUE THREAD

**Issue by Japjappedulap** [mapbox/mapbox-gl-js#8660] opened 2019-08-20 12:13 UTC
**mapbox-gl-js version**: 1.2.1

**browser**: Chrome(_76.0.3809.100_) and Firefox(_68.0.2_)

### Steps to Trigger Behavior

1. Initialise map
2. Add multiple sources, layers
3. Call `setStyle()`
4. All added sources and layers get removed

### Link to Demonstration

This can be seen in this [official example](https://docs.mapbox.com/mapbox-gl-js/example/setstyle/).

I've also added a basic example derived from the _setStyle_ example which only adds another layer to the map. If you change the map style, this layer will be removed.

https://jsbin.com/yekisosehe/1/edit?html,console,output

### Expected Behavior

Change the map style and do NOT remove all the existing layers. This is critical, as in my case, I have a great deal of layers, sources and markers on the map and removing them when switching styles is a deal breaker.

### Actual Behavior

Changes the map style and generates a warning in the console.

```
Unable to perform style diff: Unimplemented: setSprite..  Rebuilding the style from scratch.
```

Any known way to work around this and not rerender all the layers? Maybe I'm missing something obvious, but I don't think this should be the behaviour. I know there are some related issues such as [8241](https://github.com/mapbox/mapbox-gl-js/issues/8241), [2058](https://github.com/mapbox/mapbox-gl-js/issues/2058) or [2059](https://github.com/mapbox/mapbox-gl-js/issues/2059) but with no conclusive answers.

**Comment by andrewharvey** [comment] 2019-08-20 14:12
I believe this is #4006. That thread has some discussion on possible solutions, but generally the expectation is with you to either re-add those sources/layers after setStyle or even better integrate them into your Style JSON you pass to setStyle so that the smart diff which powers setStyle can retain them.

**Comment by mourner** [comment] 2019-08-20 15:02
@andrewharvey thanks for chiming in, seconded. Closing as a duplicate of #4006.

**Closed by mourner** 2019-08-20 15:02 UTC

**Comment by BlackHandguy** [comment] 2022-02-28 08:53
do you solve the question?

**Comment by InfoseedDeveloper** [comment] 2022-12-04 09:49
sds

**Comment by InfoseedDeveloper** [comment] 2022-12-04 09:55
Create one function that adds an existing layer and source again.
Import the style into map.setStyle() and then access sources and layers to add it again.

The function execution must use setTimeout. Otherwise not applicable
In my case, I gave 200

**Comment by itanka9** [comment] 2022-12-04 11:14
@InfoseedDeveloper 

Sometimes `setTimeout()` may become flaky, e.g. in case of slow network device. AFAIR a little bit more correct way is wait for [styledata](https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:styledata) event which fired after map completes style loading.

**Comment by mixaadev** [comment] 2022-12-07 16:14
> 
Can you explain when is it flaky?  
Just tested your suggestion with styledata, and that triggers way to many callbacks not sure why but does not work me.

**Comment by NessinM** [comment] 2023-08-09 23:37
Here I leave a possible solution, I hope it can help you.  [dev.to](https://dev.to/dqunbp/effectively-switching-mapbox-gl-styles-1a3i)
