### ISSUE TITLE
mapbox gl version 51. The user aborted a request

### ISSUE THREAD

**Issue by pmaza** [mapbox/mapbox-gl-js#7614] opened 2018-11-22 15:03 UTC
**mapbox-gl-js version**: 51

**browser**: Firefox,Edge and Chrome

### Steps to Trigger Behavior

 1. Loading the map on view init

### Link to Demonstration
![image](https://user-images.githubusercontent.com/18632339/48910391-21771400-ee70-11e8-84a6-e5cac6794f57.png)

### Expected Behavior

the map should load without any error

### Actual Behavior

When the map is created, it cancel one of the request to get the style. It happens after update to version 51

**Comment by mourner** [comment] 2018-11-22 15:11
A screenshot is not a link to demonstration. Unless this can be reproduced on a live minimal example (like [this one](https://www.mapbox.com/mapbox-gl-js/example/simple-map/)), we won't be able to diagnose the issue.

Also, are you seeing anything wrong with the map behavior, or is it just about developer tools network tab indications?

**Comment by pmaza** [comment] 2018-11-22 15:18
Hi @mourner. 
The map load correctly, the problem is that the engine try to get the style two times. One always fail, and the other works fine.
This is the console error message shown:

![image](https://user-images.githubusercontent.com/18632339/48911031-ea096700-ee71-11e8-8153-69242e9a7b93.png)

I can't give you more information. Before the update it worked fine, without any error.

**Comment by mourner** [comment] 2018-11-22 15:35
Since I'm not able to reproduce this on public examples, and you're refusing to provide a minimal test case, I'll have to close the issue because it's impossible to diagnose. Will reopen if there's enough information provided in the comments.

**Comment by Eldrac** [comment] 2019-01-02 22:22
Noting that I received this same error in the console when I set a style in the map constructor then immediately changed the style with a call to map.setStyle. Clearly user error though and if anything it could just use a different error message :)

```javascript
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9'
});

map.setStyle("mapbox://styles/mapbox/satellite-v9");
```

**Comment by pmaza** [comment] 2019-01-16 13:22
> Noting that I received this same error in the console when I set a style in the map constructor then immediately changed the style with a call to map.setStyle. Clearly user error though and if anything it could just use a different error message :)
> 
> ```js
> var map = new mapboxgl.Map({
>     container: 'map',
>     style: 'mapbox://styles/mapbox/streets-v9'
> });
> 
> map.setStyle("mapbox://styles/mapbox/satellite-v9");
> ```

Thank you @Eldrac!

**Comment by samfader** [comment] 2019-03-28 23:01
@mourner Here's a minimal test case: https://jsfiddle.net/p48q0mvd/1/

What's interesting is that sometimes you need to click `Run` a few times in a row to get the error to trigger. Other times, it seems to happen when the map loads for the first time. The error:

`Error: The user aborted a request.
    at mapbox-gl.js:29`

Let me know if this helps for reproducing this issue.

**Comment by cs09g** [comment] 2019-11-25 06:20
using `styledata` event, it's okay though.
```javascript
map.once("styledata", () => {
  map.setStyle("mapbox://styles/mapbox/satellite-v9");
});
```

**Comment by samfader** [comment] 2019-11-25 17:58
@cs09g I still can hit the `User aborted a request` error when using that code - https://jsfiddle.net/L3rchnge/.

**Comment by chloekraw** [comment] 2019-11-25 18:47
cc @asheemmamoowala

**Closed** 2019-11-26 00:39 UTC
Labels: bug :beetle:
