### ISSUE TITLE
Eliminate seams in blurred circles

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1702] opened 2015-11-12 00:30 UTC
With headless-gl 2.0, the circle-blur/literal test is showing a slight artifact across the seam of the quad used to draw the circle.

Diff to expected rendering:

![image](https://cloud.githubusercontent.com/assets/98601/11107275/2bdf9888-8891-11e5-8df4-0fb5c4651e04.png)

Enlarged detail:

![image](https://cloud.githubusercontent.com/assets/98601/11107295/5c6c73f4-8891-11e5-8350-aa7bf87ad86b.png)

I will mark this test as an expected failure for now. We need to investigate whether this appears in browser rendering. If so, it's a gl-js bug. If not, it's probably a bug in headless-gl.

**Comment by lucaswoj** [comment] 2015-11-12 19:13
I recreated the circle-blur/literal style in the browser and didn't see any evidence of these seams in Chrome, FF, or Safari 

<img width="1016" alt="screen shot 2015-11-12 at 11 09 11 am" src="https://cloud.githubusercontent.com/assets/281306/11128330/025bc8e0-892e-11e5-84b0-69b36d4931e2.png">

<img width="1307" alt="screen shot 2015-11-12 at 11 10 47 am" src="https://cloud.githubusercontent.com/assets/281306/11128342/163ad5ae-892e-11e5-8473-45cf4d69ba5b.png">

**Comment by lucaswoj** [comment] 2015-11-12 19:13
Anything else I should try or can we close this ticket?

**Comment by lucaswoj** [comment] 2016-06-09 21:25
Seeing this again for circle-opacity and circle-blur functions

**Comment by lucaswoj** [comment] 2016-06-16 22:13
We suspect that the fill-opacity tests are failing because of the same root cause. 

![161deebc-3234-11e6-8771-bafe67bd764c](https://cloud.githubusercontent.com/assets/281306/16134886/cf464712-33d4-11e6-96ef-fac6b1b37dba.png)

**Comment by mourner** [comment] 2016-11-03 01:24
No longer fails. I expect this got fixed by switching Circle to OS X.

**Closed by mourner** 2016-11-03 01:24 UTC
Labels: bug, medium priority

**Comment by jfirebaugh** [comment] 2016-11-03 01:26
Did you remove the ignores from the test suite?
