### ISSUE TITLE
Markers are still clipping 

### ISSUE THREAD

**Issue by kohesion** [mapbox/mapbox-gl-js#5553] opened 2017-10-30 16:54 UTC
0.41.0

### Steps to Trigger Behavior

 1. Place 100 markers where some overlap
 2. Zoom
 3.

Markers do not clip

Markers do clip

![image](https://user-images.githubusercontent.com/1246027/32184048-69c9799a-bd71-11e7-8ce2-f5d72520a6b0.png)

**Comment by jfirebaugh** [comment] 2017-10-30 17:29
Duplicate of #5447. Note that this is fixed for the release _after_ 0.41.0. It's not expected to be working in 0.41.0.

**Closed by jfirebaugh** 2017-10-30 17:29 UTC
