### ISSUE TITLE
Display better message + emit error when bad args are passed to map camera events

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#4385] opened 2017-03-09 00:08 UTC
Right now if you call `map.zoomTo([0,0])` we get the 'failed to invert matrix' and the map breaks. We should emit a syntax error with a clear message. 

Similarly, when you pass a coordinate pair to `map.flyTo` the map doesn't break, it just doesn't do anything. We should emit an error there as well and investigate other potentially affected methods.

cc @geografa

**Comment by ryanhamley** [comment] 2018-05-24 21:34
Seems to happen on scroll zoom as well as seen here #6486

**Comment by HarelM** [comment] 2019-04-16 06:19
I had the same issue when calling `flyTo` with `zoom: null`. since the stack trace doesn't reveal the origin of this error message I had to comment out pieces of my code until I found the root cause.
A good error message would've saved me a few hours.
I was migrating from openlayers where zoom is optional and thus was not aware this function can cause this error...

**Comment by Sugarlust** [comment] 2022-07-10 19:34
As a beginner in opensource, I would like to work on this. Can you tell me where I should start looking?

**Comment by SnailBones** [comment] 2022-07-11 17:48
Thank you @Sugarlust!

Just to make sure there's no confusion on this front, Mapbox GL JS is no longer fully [open source](https://en.wikipedia.org/wiki/Open-source_software). Here's the [current license](https://github.com/mapbox/mapbox-gl-js/blob/main/LICENSE.txt). You'll need to sign a contributor's agreement to submit a pull request.

The functions in question are in `camera.js`:
https://github.com/mapbox/mapbox-gl-js/blob/2bc4599ef93de4f9b937bb0118672807a0c7eefb/src/ui/camera.js#L319
https://github.com/mapbox/mapbox-gl-js/blob/2bc4599ef93de4f9b937bb0118672807a0c7eefb/src/ui/camera.js#L1448

You can look in `map.js` for examples of throwing error events:
https://github.com/mapbox/mapbox-gl-js/blob/2bc4599ef93de4f9b937bb0118672807a0c7eefb/src/ui/map.js#L2195-L2198

Lastly, we need a unit test for this behavior, probably in [`map.test.js`](https://github.com/mapbox/mapbox-gl-js/blob/main/test/unit/ui/map.test.js)

The [contributor guide ](https://github.com/mapbox/mapbox-gl-js/blob/main/CONTRIBUTING.md) will get you set up to develop the library, feel free to ping me with any questions not covered there and to tag me for review on your PR.

**Comment by Sugarlust** [comment] 2022-07-12 10:52
Hey, @SnailBones I checked out the snippets of code you mentioned. Can you tell me what criteria I need to check to fire up the error message in those functions? Also what actually is OBJECT in https://github.com/mapbox/mapbox-gl-js/blob/2bc4599ef93de4f9b937bb0118672807a0c7eefb/src/ui/camera.js#L1448

**Comment by Sugarlust** [comment] 2022-07-12 19:58
@SnailBones thanks for letting me know about flow. Please let me know what should be the data type that has to be passed in flyTo (object) so that it works accordingly. 
Thanks.

**Comment by Sugarlust** [comment] 2022-07-17 07:55
Hey, @SnailBones Can you check this out. Does this sound correct? 

https://github.com/mapbox/mapbox-gl-js/blob/2bc4599ef93de4f9b937bb0118672807a0c7eefb/src/ui/map.js#L2194-L2200

Please let me know where to find the contributor's license.
Is there a discussion channel or IRC for contributors working on it? Thanks.

**Comment by Sugarlust** [comment] 2022-07-17 08:17
Hey, @SnailBones Can you check this out. Does this sound correct? 

https://github.com/mapbox/mapbox-gl-js/blob/2bc4599ef93de4f9b937bb0118672807a0c7eefb/src/ui/map.js#L2194-L2200

https://github.com/Sugarlust/mapbox-gl-js/blob/febd320d180aeaa0a3e2f20c3778dac7b8f5ad2c/src/ui/camera.js#L1454-L1460

Please let me know where to find the contributor's license.
Is there a discussion channel or IRC for contributors working on it? Thanks.

**Comment by Sugarlust** [comment] 2022-07-20 06:45
Hey, @SnailBones I made the error messages a bit more specific. Check these out 

https://github.com/Sugarlust/mapbox-gl-js/blob/e4c22f4a8639d72f42b8d78dc85b142fce621048/src/ui/camera.js#L1454-L1460

https://github.com/Sugarlust/mapbox-gl-js/blob/e4c22f4a8639d72f42b8d78dc85b142fce621048/src/ui/camera.js#L320-L329

Also, should I make a PR now?

**Comment by SnailBones** [comment] 2022-07-22 20:14
Closing this ticket as fixing it in isolation goes against our usage of Flow for type checking.

From https://github.com/mapbox/mapbox-gl-js/pull/12098#issuecomment-1192846934:

> While this is a useful exception on developer errors, we don't have precedent of type safety errors on other APIs. Type safety is done with static type annotations, and while I imagine that not all external developer adopt the same type checking as part of their tooling, it's not trivial to exhaust every possible type checks at runtime as this is better suited for static analysis. If we introduce this, we would start to be inconsistent with other APIs and probably be asked to adopt similar patterns elsewhere.

This issue is still tracked in https://github.com/mapbox/mapbox-gl-js/issues/9485 and should be considered in the context of broader improvements to error handling.

Thank you for your time and contribution @Sugarlust!

**Closed by SnailBones** 2022-07-22 20:14 UTC
Labels: good first issue
