### ISSUE TITLE
when use in js class, the map style will change very strange

### ISSUE THREAD

**Issue by leungMr** [mapbox/mapbox-gl-js#10586] opened 2021-04-16 14:26 UTC
**mapbox-gl-js version**:

### Question

when i use mapbox Object instance in a js class，the map style will change very strange。
the line feature chang to white otted line，and the polygon feature not render
![image](https://user-images.githubusercontent.com/37567413/115038954-96948980-9f02-11eb-89f9-735bcd45c89a.png)

**Comment by mourner** [comment] 2021-04-17 16:16
Thanks for the report! Can you please set up a minimal [JSFiddle](http://jsfiddle.net/) test case that reproduces the issue? This will make it much easier for us to identify and fix it.

**Comment by andrewharvey** [comment] 2021-04-20 10:08
That looks eerily similar to #9874

**Comment by mourner** [comment] 2021-05-17 15:50
Closing as a duplicate of #9874 — seems to be the same issue indeed.

**Closed by mourner** 2021-05-17 15:50 UTC
Labels: needs information :pray:
