### ISSUE TITLE
Events for 3D buildings (fill-extrusion) are not triggered for height

### ISSUE THREAD

**Issue by bravecow** [mapbox/mapbox-gl-js#5031] opened 2017-07-24 12:19 UTC
**mapbox-gl-js version**: 0.38.0

### Steps to Trigger Behavior

```
map.addLayer({
    'id': 'buildings',
    'type': 'fill-extrusion',
    'source': {
      'type': 'vector',
      'url': '...',
    },
    'minzoom': 14,
    'source-layer': 'buildings',
    'paint': {
      'fill-extrusion-color': '#ff9800',
      'fill-extrusion-height': {
        'property': 'height',
        'type': 'identity',
      },
      'fill-extrusion-opacity': 0.8,
    }
  });
```

### Expected Behavior

Events on height are triggered for 

`map.on('click', 'buildings', (event) => {`

### Actual Behavior

Events are triggered only for base polygon

**Comment by jfirebaugh** [comment] 2017-07-24 15:54
Duplicate of #3122.

**Closed by jfirebaugh** 2017-07-24 15:54 UTC
