### ISSUE TITLE
['image'] doesn't return null

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#10466] opened 2021-03-15 01:18 UTC
**mapbox-gl-js version**: 1.13.0

According to the documentation:

> [`['image']`] Returns an image type for use in icon-image, *-pattern entries and as a section in the format expression. If set, the image argument will check that the requested image exists in the style and will return either the resolved image name or null, depending on whether or not the image is currently in the style. This validation process is synchronous and requires the image to have been added to the style before requesting it in the image argument.

It's not clear what "if set, the image argument" means - argument to what? But I interpreted this to mean, the `['image']` function should return `null` if there is no image of that name.

Instead, it always evaluates to the string of the image name, never to null.

### Link to Demonstration

https://codepen.io/stevebennett/pen/XWNGVGe?editors=0010

### Expected Behavior

There should be no special labels shown, because `['image', 'not-an-icon']` should evaluate to null, and hence display as an empty string.

### Actual Behavior

'not-an-icon' is shown everywhere.

**Comment by SnailBones** [comment] 2021-08-19 23:56
This is a documentation issue. Missing images only evaluate to null when wrapped in `coalesce` The docs should be changed to read something more like:

> Returns an image type for use in icon-image, *-pattern entries and as a section in the format expression. A `coalesce` expression containing images will evaluate to the first listed image that is currently in the style. This validation process is synchronous and requires the image to have been added to the style before requesting it in the image argument.

The docs may also benefit to add further clarification about `to-string`:

> If the input is an image, `to-string` returns the image name.

@stevage Would the functionality you describe be useful besides consistency with docs? I  _think_ the current behavior is intended but I could see a case for `[' to-string', ['image, 'not-an-icon']]` to return an empty string.

**Comment by stevage** [comment] 2021-08-20 06:26
@SnailBones Yes, one use case is when you have data with an `icon` field but for some reason there's a chance that you don't actually have a matching icon. You want to use an expression to test if that icon exists, and if it doesn't, fallback to something different, like a different icon or a `circle` layer.

**Comment by SnailBones** [comment] 2021-08-23 20:23
I think this can be accomplished with `coalesce` like this: 
```js
'to-string',
      [
      'coalesce',
          [ 'image', ' '],
          ['image', 'not-an-icon'],
      ]
```
Here's an [edit](https://codepen.io/snailbones/pen/JjJjJGM?editors=0010) to your pen.

**Comment by stevage** [comment] 2021-08-24 10:04
Ok, thanks. This is maybe a more complete demonstration of how `['image', ...]` can indeed be used to render a fallback option if a given icon doesn't in the stylesheet:


```
const icon = 'airport-15'
map.on('load', () => {
  map.addLayer({
    id: 'no-icon',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'place_label',
    layout: {
      'text-font': [
        'DIN Offc Pro Regular',
        'Arial Unicode MS Regular',
      ],
      'text-allow-overlap': true,
      'text-field': [
        'to-string', [
             'coalesce',
                    ['image', icon],
                     'No icon available'
                ],
      ],
      'text-anchor': 'left',
        'icon-image': icon,
      'icon-anchor': 'right'
    },
  });
});
```

Change the value of `icon` to something invalid and the fallback text is shown instead.

https://codepen.io/stevebennett/pen/qBjBMpe?editors=0010

**Comment by stevage** [comment] 2021-08-24 10:08
FWIW, I do think there there is something very unintuitive, and perhaps wrong about this:

`['image', 'not-an-icon']` returns null, except if the expression happens to be evaluated inside a `['to-string', ...]` expression, in which case, it returns `not-an-icon`. 

Someone with a deeper knowledge of computer science might be able to explain which principle of programming language design this is breaking - something about context-free grammars perhaps. I can only say that it feels "off" to me.

**Comment by SnailBones** [comment] 2021-08-24 18:27
Well done, the fallback string after the image is a nice improvement.

I agree that it's less-than intuitive. The issue is that `coalesce` is really not just one function, but does different things depending on its input types. The documentation needs to be updated to better reflect that. Maybe this:

> Evaluates each expression in turn until the first valid value is obtained. Invalid values are `null` and images that are not available in the style. If all values are invalid, coalesce returns the first value listed.

Does that make the behavior clearer to you?

I'd like to close this issue upon fixing the docs, but if you have any specific ideas about how to improve the behavior, feel free to open a new feature request.

**Comment by stevage** [comment] 2021-08-31 01:40
Seems I have made my points, and not convinced you, so bowing out. Hopefully I'll be able to find this thread and hence my codepen next time I need to do this.

**Closed** 2021-09-08 20:16 UTC
Labels: docs :scroll:
