### ISSUE TITLE
panning with markers on IE11/Edge, performance issues

### ISSUE THREAD

**Issue by Shikakka** [mapbox/mapbox-gl-js#5149] opened 2017-08-15 14:00 UTC
**mapbox-gl-js version**: tested with v0.38+

### Steps to Trigger Behavior

 1. add +-15 markers on the map
 2. pan

### Expected Behavior
Smooth panning on both IE11 and Edge.

### Actual Behavior
IE11 (11.540.15063) and Edge (40.15063.0.0) both have huge performance issues. Edge completely freezes the map if I use 20 markers, until  I stop panning. 
Both Chrome ( 60.0.3112.90 ) and Firefox (54.0.1) run perfectly with 120-220 markers.

When using fitBounds, both IE11 and Edge look perfectly smooth. Even when I use arround 100 markers it looks relativaly smooth.

A demo with 19 markers:
https://jsfiddle.net/sz5rgfzp/

### tested on: 
win10 creators update, i7-7700HQ, 32GB ram, 1TB SSD
win10 creators update, i3-6100H, 8GB ram, 256GB SSD

**Comment by jfirebaugh** [comment] 2017-08-24 23:20
Duplicate of #5041; fixed for the next release in #5139.

**Closed by jfirebaugh** 2017-08-24 23:20 UTC
