### ISSUE TITLE
3D Light Documentation

### ISSUE THREAD

**Issue by ErEXON** [mapbox/mapbox-gl-js#3407] opened 2016-10-19 05:04 UTC
Hi there,
It's awesome that Mapbox GL JS now support 3D Buildings (a much awaited feature).
But, according to the Style Specification There is no documentation available for Light.

![untitled](https://cloud.githubusercontent.com/assets/8279954/19506223/540317c2-95e7-11e6-98cd-5d4ba8f1f655.png)

Hope, It will available soon.

**Comment by lbud** [comment] 2016-10-19 06:21
Closing as duplicate of https://github.com/mapbox/mapbox-gl-style-spec/issues/522.

**Closed by lbud** 2016-10-19 06:21 UTC
