### ISSUE TITLE
Terrain renders with scattered extreme-height distortions in Firefox

### ISSUE THREAD

**Issue by hiebj** [mapbox/mapbox-gl-js#13016] opened 2023-12-20 21:00 UTC
**mapbox-gl-js version**: Latest on examples website; v3.0.1

**browser**: Firefox 121.0

### Steps to Trigger Behavior

 1. Open Firefox (this does not appear in Chrome or Safari)
 2. Go to https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/
 3. See strange terrain columns of infinite height

### Link to Demonstration
https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/

### Expected Behavior
Do not have strange terrain columns of extreme height

### Actual Behavior
Strange terrain columns of extreme height

https://github.com/mapbox/mapbox-gl-js/assets/4262078/c076855e-76b3-42bb-a660-6a5b642b9a35

**Comment by stepankuzmin** [comment] 2023-12-21 09:44
Might be related to https://github.com/mapbox/mapbox-gl-js/issues/12997

**Comment by mourner** [comment] 2023-12-22 09:40
Let's close to keep the discussion in one ticket — duplicate of #12997

**Closed by mourner** 2023-12-22 09:40 UTC
Labels: bug :lady_beetle:
