### ISSUE TITLE
Locate the user behavior with WebKit & Blink

### ISSUE THREAD

**Issue by gkiosov** [mapbox/mapbox-gl-js#8214] opened 2019-05-03 20:12 UTC
**mapbox-gl-js version**: 0.54.0

**browser**: Mac OS (10.14.4) Safari (12.1) & Chrome (73.0.3683.103)

We have Angular 7 SPA with the Mabpox map and we noticed the strange behavior of the standard Mapbox locate user button.

### Steps to Trigger Behavior

1. Load a page with the map.
1. Press locate user button. It works fine — we are flying to our position on the map.
1. Change page to another (any) in the current browser tab (change route).
1. Turn back to the page with the map in the current browser tab.
1. Press locate user button again. Here is the bug: the locate user button is spinning endlessly and we are not flying to our position on the map.
1. Change browser tab without reloading the page with the map.
1. Turn back to the tab with the page with the map and the locate user button stops spinning and we start flying to our position on the map.

The bug exists only on the WebKit (Safari) and Blink (Chrome) browsers.

### Link to Demonstration

I can’t reproduce this bug with jsbin.

**Comment by mourner** [comment] 2019-05-03 21:09
> I can’t reproduce this bug with jsbin.

I'm afraid we can't help with this unless there's a reproducible minimal live test case.

**Comment by ryanhamley** [comment] 2019-05-03 21:15
I can't replicate this either but it sounds like it's related to routing in your Angular app. Perhaps navigating away from the map is interfering with the geolocation attempt.

**Comment by gkiosov** [comment] 2019-05-04 17:53
> > I can’t reproduce this bug with jsbin.
> 
> I'm afraid we can't help with this unless there's a reproducible minimal live test case.

Here is the vanilla js example — https://kiosov.pro/tmp/mapbox/locateuser.html

### Steps to Trigger Behavior

1. Click «show map 1» link.
1. Click the locate user button on the map 1.
1. Click «show map 2» link.
1. Click the locate user button on the map 2. You will see the bug I wrote above.
1. Change the browser tab and then return back on the tab with the example.

**Comment by ryanhamley** [comment] 2019-05-06 19:56
I can replicate the issue with that example. Thanks for putting that together!

**Comment by gkiosov** [comment] 2019-05-07 17:52
> I can replicate the issue with that example.

Sweet. Is there any chance to know how fast it will be fixed? Kinda critical for us. Thank you anyway!

**Comment by ryanhamley** [comment] 2019-05-07 17:57
No, there's no timeline for a fix on our end. We'd welcome a PR if you want to try fixing it yourself.

**Comment by gkiosov** [comment] 2019-08-16 17:54
Hello, @asheemmamoowala! I just find out that you put a new tag to this issue. Is it means you get it into the job or you need some additional info about this issue from us?

**Comment by asheemmamoowala** [comment] 2019-08-16 23:10
@gkiosov This issue is not currently on our roadmap to be fixed. I only changed the label to `needs investigation` to indicate that the information to reproduce and debug the issue is available.

**Comment by sometime** [comment] 2019-08-17 05:09
@asheemmamoowala We faced this issue too in our SPA project. We are thinking about swapping Mabpox with Google Maps now. It is a very critical bug when a user can not use user geolocation more than once — bad UX.

**Comment by ryanhamley** [comment] 2019-11-23 00:45
I can confirm what the issue is but I'm still exploring potential fixes. This bug is exhibited when `trackUserLocation` is `true` for the `GeolocationControl`. What's happening in this case is that instead of calling `geolocation.getCurrentPosition()`, we're actually calling `geolocation.watchPosition()`. This appears to immediately get the current position the first time it's called, but on each subsequent call it's just setting up a listener that waits for the position to change. This usually happens eventually as more refined methods are used to get the user's location over time, but it also happens when the tab is navigated back to and the process starts back up.

In the context of a SPA, I assume what is happening is that the map component is not being destroyed when the route changes, so when the user navigates back to the map, it's registering a second listener on `watchPosition`. I haven't verified this by creating a SPA but a potential workaround until this is fixed might be to call [`{GeolocationControl}.trigger()`](https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol#trigger) when the button is clicked.

**Comment by ryanhamley** [comment] 2019-12-11 01:47
I've submitted a potential fix for this with https://github.com/mapbox/mapbox-gl-js/pull/9092

**Comment by andrewharvey** [comment] 2019-12-11 09:35
> @asheemmamoowala We faced this issue too in our SPA project. We are thinking about swapping Mabpox with Google Maps now. It is a very critical bug when a user can not use user geolocation more than once — bad UX.

@sometime based on @ryanhamley findings, setting `trackUserLocation` to `false` might be a subtitle workaround.

Alternatively it sounds like removing the geolocate control from your map in your SPA component lifecycle might also work. In vue that would be in [beforeDestroy](https://vuejs.org/v2/api/#beforeDestroy).

Regardless the issue is still present even without fancy SPAs by just having multiple maps on one page, so glad to see @ryanhamley's PR to fix this bug, and thank you @gkiosov for reporting the issue.

**Comment by ryanhamley** [comment] 2019-12-11 19:19
Yeah, I considered exposing the `clearWatch` method on the control to help with situations like SPA routing, but I think the better way to do it is to clean up the Geolocate control (or even the entire map) in the relevant lifecycle method.

**Closed** 2020-01-06 18:39 UTC
Labels: bug :beetle:
