### ISSUE TITLE
Permission denied to access property "clientX"

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6717] opened 2018-05-23 12:07 UTC
**mapbox-gl-js version**: 0.45.0
**browser**: Firefox Mobile 60.0 / Android 8.0

This is from a Sentry report, I cannot reproduce it or even have access to the device which triggered this error.

Sentry stacktrace:
https://sentry.io/share/issue/0cb7266900e642a4819941b4fb2a7c87/

The event which triggered this was a click or touch on the map canvas.

**Comment by jfirebaugh** [comment] 2018-05-23 19:35
Thanks for the report. Is this all the information you have available? It's probably not enough for us to determine the cause, and I'm not coming up with any results when searching for this error message, so  unfortunately we might have to close this as not reproducible.

**Comment by ryanhamley** [comment] 2018-05-23 19:55
Typically this `Permission denied to access property "x"` error arises from an iframe that's violating the same-origin property. MDN has [more info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied). If you're using iframes in your application, that might be a good place to begin debugging.

**Comment by hyperknot** [comment] 2018-05-24 10:41
OK, this happened only once out of thousands of views, so it might even be a bug in Firefox Mobile or something similar. @ryanhamley yes, it's an iframe on a different domain, but everything should be configured correctly.

I just wanted to report it so at least Google can find it now, as well as we can see if there will be any patterns in these events.

**Closed** 2018-05-24 10:43 UTC
Labels: needs information :pray:
