### ISSUE TITLE
Projection `naturalEarth` supports pacific view or other projection center

### ISSUE THREAD

**Issue by zxj5470** [mapbox/mapbox-gl-js#12010] opened 2022-06-17 09:01 UTC
## Motivation

I found that the projection `naturalEarth` uses the code by `d3-geo`. But current view is only centered by [0, 0] .

And d3 has other center view like `pacific` by using `.rotate([200, 0])`， by offset
（This API named `rotate`  is an Ambiguous name, and `200` means `-160` means `160°E`，wtf）

The features what I want is add an API named like `offset` in `natural_earth.js` to set longitude 160°E as center when changing projection.

```js
map.setProjection({
  name: "naturalEarth", 
  offset: [160, 0], //  pacific as center
})
```

## Design
https://observablehq.com/@d3/natural-earth
![image](https://user-images.githubusercontent.com/20026798/174263630-bfe186cf-e3a2-4319-a44b-f3ec6d6fecac.png)

### Mock-Up
```js
map.setProjection({
  name: "naturalEarth", 
  offset: [160, 0], //  pacific as center
})
```

### Implementation
d3-geo code:
https://github.com/d3/d3-geo/blob/0c27527d4f9f500698b28d33289ee1104ee22990/src/projection/index.js#L157-L165

```js
// code usage
projection = d3.geoNaturalEarth1().rotate([200, 0])


  projection.rotate = function(_) {
    return arguments.length ? (deltaLambda = _[0] % 360 * radians, 
deltaPhi = _[1] % 360 * radians, 
deltaGamma = _.length > 2 ? _[2] % 360 * radians : 0, 
recenter()) : [deltaLambda * degrees, deltaPhi * degrees, deltaGamma * degrees];
  };

  function recenter() {
    var center = scaleTranslateRotate(k, 0, 0, sx, sy, alpha).apply(null, project(lambda, phi)),
        transform = scaleTranslateRotate(k, x - center[0], y - center[1], sx, sy, alpha);
    rotate = rotateRadians(deltaLambda, deltaPhi, deltaGamma);
    projectTransform = compose(project, transform);
    projectRotateTransform = compose(rotate, projectTransform);
    projectResample = resample(projectTransform, delta2);
    return reset();
  }
```

**Comment by mourner** [comment] 2022-06-17 11:05
Yeah, we would like to implement this eventually, although it's not trivial for GL JS. Closing as duplicate of #11180

**Closed by mourner** 2022-06-17 11:05 UTC
