### ISSUE TITLE
0.29 data driven styling changed rendering?

### ISSUE THREAD

**Issue by stackTom** [mapbox/mapbox-gl-js#3865] opened 2016-12-27 04:14 UTC
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. 0.29 uses different stops
 2. color interpolation seems broken
 3.

### Actual Behavior
I just updated to 0.29. I load a large number of points in a layer utilizing mbtiles on a server. I have a jet color scale implemented with the appropriate stops and utilize data-driven styles. With the latest 0.29 update, the stops for circle radius seem to have changed. Now, my circles look smaller than with the same stops in previous versions of gl js. Also, I am getting some points to randomly be colored in black. The stops for the circle-color property contain no black values (just from red to blue as per a jet color scale). Any ideas as to how to fix this? Did something change in 0.29 with how data driven styles are rendered?

**Comment by averas** [comment] 2016-12-27 20:58
Probably a dupe of #3838 and #3851. If you want to confirm you can try with <code>master</code>.

**Comment by stackTom** [comment] 2016-12-27 23:37
Thanks, I'm not sure how to install master as I am using simple script tags, but this seems like the issue. I can change my script tags to use 0.28, and it begins to work fine as usual.
Since I see the bug has been fixed, can I expect 0.30.0 to have these fixes included?

**Comment by averas** [comment] 2016-12-28 02:36
>  can I expect 0.30.0 to have these fixes included

Correct.

**Closed** 2016-12-28 05:07 UTC
