### ISSUE TITLE
Map canvas sizing broken when contained in a transform scale container in v2.5.0

### ISSUE THREAD

**Issue by jrohland** [mapbox/mapbox-gl-js#11085] opened 2021-10-05 16:04 UTC
After updating to v2.5.0 we've noticed that maps we have contained inside of a container that has a transform scale css set are no longer updating their canvas height and width to fill the container size properly.

**mapbox-gl-js version**: 2.5.0

**browser**: Firefox

### Steps to Trigger Behavior

 1. Place map inside of a div with a css property of transform(scale: 0.5);

### Link to Demonstration

I've created a jsfiddle to showcase this issue: https://jsfiddle.net/jesserohland/hLkoys52/5/

This is a regression from v2.4.1 where this previously worked. https://jsfiddle.net/jesserohland/hLkoys52/6/

**Comment by SnailBones** [comment] 2021-10-05 17:06
Might be introduced by #10936

**Comment by SnailBones** [comment] 2021-10-05 21:15
Confirmed that this is caused by  #1093, this occurs after that PR was merged but not before.

**Comment by avpeery** [comment] 2021-10-05 21:42
@SnailBones  .getBoundingClientRect() replaced clientWidth and clientHeight  in favor of getting more precise calculations. However, .getBoundingClientRect() takes in CSS transforms before returning its values. Replacing getBoundingClientRect [here](https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/map.js#L2530) to clientWidth and clientHeight or offsetWidth and offsetHeight would fix the transform issue.

**Comment by chrisgervang** [comment] 2021-10-14 00:35
Thank you for reporting this issue and working on a fix. It's very convenient to be able to apply `transform: scale()` when building resizable UI panels and keep a fixed map viewport. We couldn't find a way to directly set the viewport size since they are internally set (prior to 2.5) by clientWidth/Height, so instead css scaling was the way we achieved this.

**Closed** 2021-12-14 00:16 UTC
Labels: bug :lady_beetle:

**Comment by felix-ht** [comment] 2021-12-15 20:37
@avpeery any idea when this will be released? Feels like this should be cherry-picked into a 2.6.2 release (and 2.5.2)

**Comment by treehousetim** [comment] 2022-01-11 22:20
> @avpeery any idea when this will be released? Feels like this should be cherry-picked into a 2.6.2 release (and 2.5.2)

I also am wondering when we might be able to see this fixed.

Thank you.

**Comment by avpeery** [comment] 2022-02-03 05:15
@treehousetim @felix-ht @chrisgervang @jrohland 

> @avpeery any idea when this will be released? Feels like this should be cherry-picked into a 2.6.2 release (and 2.5.2)

The fix is included in the recent [2.7.0](https://github.com/mapbox/mapbox-gl-js/releases/tag/v2.7.0) release!

**Comment by jrohland** [comment] 2022-02-08 19:28
@avpeery I just tried out 2.7.0 and while it looks like the sizing is fixed when using a single container with a transform: scale() style, I'm still seeing sizing issues when scaling is used in conjunction with transform: translate(). We have a use case where we have an outer container which is scaled down and our map container is positioned via translate(). I have created a jsfiddle using 2.7.0 to showcase this bug.

https://jsfiddle.net/jesserohland/40kzeg7x/2/

This use case was previous working with 2.4.1 as visible here: https://jsfiddle.net/jesserohland/40kzeg7x/1/

Thanks for the initial fix!

**Comment by ryanhamley** [comment] 2022-02-08 21:13
@avpeery This appears to be caused by [this line](https://github.com/mapbox/mapbox-gl-js/pull/11310/files#diff-f62d8d42ec7424781f2e987a61684959e1bc794c67f75cd33548bd4a62c73028R2633) which prevents the map container from having more than one transformed parent element. It seems to work as expected if you make it `while (el)`. Do you remember why this line checks for `!transformValues`?

**Comment by jrohland** [comment] 2022-02-09 14:55
@ryanhamley @avpeery Should I open up a new issue to track this since this original issue was resolved?

**Comment by ryanhamley** [comment] 2022-02-09 18:43
I opened a new bug ticket https://github.com/mapbox/mapbox-gl-js/issues/11492
