### ISSUE TITLE
Error when requiring mapbox-gl-js in Node

### ISSUE THREAD

**Issue by ahk** [mapbox/mapbox-gl-js#8442] opened 2019-07-08 18:30 UTC
```
when I import mapbox-gl 12.x by nodejs (V=12.x) that gives me a error which is " nodejsReferenceError: self is not defined.What can I do the next can help me.thanks
```

_Originally posted by @lf1991 in https://github.com/mapbox/mapbox-gl-js/issues/8424#issuecomment-508624302_

Hi @lf1991, I started a new thread for your issue (I don't think you were having an issue with benchmarks on Firefox). You are using `nodejs 12.x` with the newest `mapbox-gl-js` correct? If you are using `mapbox-gl` and having an issue this might not be the correct project.

I can tell you that `mapbox-gl-js` (this project) doesn't support `nodejs` higher than `10.x`, so if you try with `nodejs` `8` or `10` that may solve your issue.

**Comment by mourner** [comment] 2019-07-08 18:36
Older nodes will still have a problem: https://github.com/mapbox/mapbox-gl-js/issues/4593

**Comment by bradjonesca** [comment] 2019-07-08 18:48
It sure would be nice to see some testing for Nodejs 12 soon ;)

**Comment by ahk** [comment] 2019-07-09 00:19
> Older nodes will still have a problem: #4593

Sorry I misunderstood what @lf1991 was trying to do, thanks @mourner. This was informative.

**Comment by samkelleher** [comment] 2019-09-06 16:19
I don't believe this is a Node issue, as far as I can tell, this libary doesn't work in Node at all. The error above is because the library is executing on import and trying to access browser specific APIs.

I.e., this code **should not** do any execution. The library has side effects, meaning it is executing and trying to access browser specific APIs.

```
import mapbox from "mapbox-gl";
```
See https://github.com/mapbox/mapbox-gl-js/issues/4593#issuecomment-512566380

**Comment by aendrew** [comment] 2019-09-13 11:35
This is effectively a duplicate of #4593 — the issue isn't a Node version issue, it's an "eagerly accesses browser globals on module import" issue. 

My suggestion is to close this issue and reopen #4593 where there's been a fair bit more discussion recently.

**Comment by mourner** [comment] 2019-09-13 11:54
@aendrew good call — reopened #4593, closing this issue in favor of that one.

**Closed by mourner** 2019-09-13 11:54 UTC
Labels: needs discussion :speech_balloon:
