### ISSUE TITLE
Raster Flicker

### ISSUE THREAD

**Issue by dflynn15** [mapbox/mapbox-gl-js#2467] opened 2016-04-19 17:42 UTC
This is more or less just a question. I have been trying to track down a raster "flickering" that happens whenever the Map is animated using `pitch` and noticed that there was a [previous issue](https://github.com/mapbox/mapbox-gl-js/issues/2212) and [PR](https://github.com/mapbox/mapbox-gl-js/pull/2282) that in theory should have fixed this. Is there a possibility this has been re-introduced by the upgrades to `0.17.0`

If there is anything else I need to provide let me know!

**mapbox-gl-js version**: `0.17.0`
### Steps to Trigger Behavior
1. Go to this CodePen [here](http://codepen.io/dflynn15/full/aNKBKp/)
2. Click the "Fly In" button
3. Click the "Fly out" button after animation
4. You should notice the raster flickering on the top of the map

**Comment by ansis** [comment] 2016-04-19 18:04
I'm not seeing any raster layers in the codepen so I think this is different than https://github.com/mapbox/mapbox-gl-js/issues/2212

Which layers are flickering? lines? fills? text?

**Comment by dflynn15** [comment] 2016-04-19 18:36
Ah, I was wrong in the terminology. My bad :sob:

It appears to be the map tiles (?). I do want to emphasize this is intermittent and best "found" on Chrome. Firefox seems to be quick clean :grimacing: You can de-prioritize this until I can get a consistent or reproducible screen capture for you :disappointed:

**Comment by lucaswoj** [comment] 2016-04-25 22:28
Thanks for reporting @dflynn15!

In the name of keeping our issue queue lean and mean, I'm going to close this until we can get a consistent or reproducible screen capture. Please re-open once you have one!

**Comment by mtirwin** [comment] 2016-05-05 17:57
I'm able to reproduce a raster flicker using production mapbox.mapbox-satellite, mapbox-gl 0.18.0, Chrome 50.0.2661.86, on current OSX. 

Flicker behavior happens consistently on [fly-to events with with pitch 0 and > 0 in this demo](https://www.mapbox.com/labs/digitalglobe-rio/#), and [this screen vid catches the issue](https://www.dropbox.com/s/12mna61vaghx4mm/flicker.mp4?dl=0) (can't get a gif with high enough frame rate) in the upper left after the initial fly-to event.

**Comment by mtirwin** [comment] 2016-05-09 18:39
Much better capture with this video:

https://www.dropbox.com/s/efywvcw1594zs1r/flicker2.mov?dl=0

**Comment by kkaefer** [comment] 2016-05-18 08:56
I'm seeing this as well, and it's pretty jarring.

**Comment by mapsam** [comment] 2016-11-10 22:19
Seeing this as well, it's not _jarring_ per se, but definitely there.

![mapbox-gl-js-satellite-flicker](https://cloud.githubusercontent.com/assets/1943001/20196672/9c4dbdf0-a750-11e6-9a3d-5b88629991f6.gif)

**Comment by mourner** [comment] 2016-11-29 20:41
When parent tile fades over child tile, we retain both through `_coveredTiles` set, but then we exclude covered tiles so that they’re not rendered for vector tile sources; however we need to render both for raster tile sources. Not sure at what point this broke, but we need to make logic differences between tile retention for raster  tiles and for vector tiles more explicit for a proper fix.

**Comment by andrewharvey** [comment] 2017-01-06 09:33
Is the flicker and the fade from black when zooming out the same issue?

Looking at https://github.com/mapbox/mapbox-gl-js/blob/master/js/render/draw_raster.js#L51 it looks like the tile fading will fade from the parent tile if it exists but doesn't fade from the child tiles when zooming out. It seems like the fix is to include the 4 child tiles if they exist in the fade.

**Comment by scottgerring** [comment] 2017-01-18 16:04
Any movement on this?

**Comment by lucaswoj** [comment] 2017-01-18 18:30
Not yet @scottgerring. We will be sure to hit this before our February release.

**Closed** 2017-01-24 14:09 UTC
Labels: bug, high priority
