### ISSUE TITLE
Documentation entries aren't sorted alphabetically

### ISSUE THREAD

**Issue by SupremumLimit** [mapbox/mapbox-gl-js#4758] opened 2017-05-26 02:57 UTC
It's hard to find things in the documentation. Could the entries for objects, functions, options and so on be sorted alphabetically please? 

Also, is the documentation available as a Dash docset by any chance?

**Comment by anandthakker** [comment] 2017-05-26 05:06
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/4312

**Closed by anandthakker** 2017-05-26 05:06 UTC
