### ISSUE TITLE
Inconsistent pitch change speed with Shift+up-arrow

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-gl-js#1735] opened 2015-11-19 16:06 UTC
Is the Shift+up-arrow shortcut meant to be held down or tapped repeatedly?

Pressing Shift+up starts the pitch animation at a good speed, but then immediately slows down to a crawl as I hold down the keys. Releasing the keys causes a final jump before stopping.

![gifrecord_2015-11-19_110410](https://cloud.githubusercontent.com/assets/126952/11275824/74c061aa-8ead-11e5-88b9-44296f63550c.gif)

**Comment by tmcw** [comment] 2015-11-19 16:08
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/1661

**Closed by tmcw** 2015-11-19 16:08 UTC
