### ISSUE TITLE
Smooth scrolling 

### ISSUE THREAD

**Issue by ekelleyv** [mapbox/mapbox-gl-js#1820] opened 2015-12-09 17:06 UTC
It would be really nice if the input from the scroll wheel was very slightly smoothed before performing the zoom action. Zooming feels incredibly smooth and fluid on something like an apple trackpad, which has a much higher frequency/smaller scroll event.

However, on a normal mouse, the "ticks" between the zooms are very noticeable. It makes it feel like there is a lower framerate than there actually is (since the apparent framerate is at most the mousewheel event rate). When comparing mapbox gl to google maps side by side, this is probably the biggest difference in how the maps "feel."

This may be as straightforward as calculating a reasonable non-zero number for duration here:
https://github.com/mapbox/mapbox-gl-js/blob/b7032636206448e16eb681836f97e79f0587fd7e/js/ui/handler/scroll_zoom.js#L110

**Comment by mourner** [comment] 2015-12-09 17:16
Yes, this is a regression and a duplicate of #1730.

**Closed by mourner** 2015-12-09 17:16 UTC

**Comment by ekelleyv** [comment] 2015-12-09 17:25
Ah oops. Searched "scroll" but not "zoom."

Thanks!
