### ISSUE TITLE
Camera "look at" with adjustable height

### ISSUE THREAD

**Issue by Bulisor** [mapbox/mapbox-gl-js#12563] opened 2023-02-09 09:08 UTC
## Motivation

Hi,
I am using Mapbox with babylonjs to display 3d buildings on map. It is working very well so far. 
I was wondering if there is a way to set the camera "look at" position at a different height, or to change the height of the camera target. Currently, it seems that the camera always looks at the target at 0 height

The ability to set the camera height for the "look at" feature would provide more flexibility and enhance the user experience for all who are using 3d on mapbox.

[https://prnt.sc/ql8hlW1CMFAU](https://prnt.sc/ql8hlW1CMFAU)

Thanks

**Comment by Bulisor** [comment] 2023-05-17 06:55
Hi @stepankuzmin , thank you for your response. Unfortunately, this is not what I'm seeking. When using this option, the camera simply zooms out on the target, and I do not desire that. Instead, I would like the same zoom level, but positioned at a specific distance above the ground along the Y-axis. I hope I have explained it more accurately.

**Comment by artu-ole** [comment] 2023-06-21 11:51
Hi there, this looks like a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/3552 to me?

**Comment by stepankuzmin** [comment] 2023-06-26 09:40
Yes, this is a duplicate of #3552.

**Closed by stepankuzmin** 2023-06-26 09:40 UTC
Labels: feature :green_apple:
