### ISSUE TITLE
I must reload the page to see the markers.

### ISSUE THREAD

**Issue by juliovich** [mapbox/mapbox-gl-js#10292] opened 2021-01-14 17:22 UTC
I have four types of markers but I want to see only one of those at same time.

![github](https://user-images.githubusercontent.com/34285820/104625055-99c67200-5694-11eb-9dbc-419a8f55bb5f.png)

 When I change to see another type of marker; all is working fine (the url, the map, the control div...) but I can not see the new markers until I refresh the page manually.

This is my code in init_mapbox.js:

        `import mapboxgl from 'mapbox-gl';
        
        const mapElement = document.getElementById('map');
        const markers = JSON.parse(mapElement.dataset.markers);
        
        const fitMapToMarkers = (map, markers) => {
            const bounds = new mapboxgl.LngLatBounds();
            markers.forEach(marker => bounds.extend([ marker.lng, marker.lat ]));
            map.fitBounds(bounds, { padding: 30, maxZoom: 15, duration: 0 });
        };
        
        const initMapbox = () => {
            mapboxgl.accessToken = mapElement.dataset.mapboxApiKey;
        
            const map = new mapboxgl.Map({
              container: 'map',
              style: 'mapbox://styles/juliovich/ckjq84pys5hr819k9jm3btnof'
            });
        
        
            markers.forEach((marker) => {
                const popup = new mapboxgl.Popup().setHTML(marker.infoWindow);
        
                const element = document.createElement('div');
                element.className = 'marker';
                element.style.backgroundImage = `url('${marker.image_url}')`;
                element.style.backgroundSize = 'contain';
                element.style.width = '25px';
                element.style.height = '25px';      
        
                new mapboxgl.Marker(element)
                .setLngLat([ marker.lng, marker.lat ])
                .setPopup(popup) 
                .addTo(map);
            });
        
            fitMapToMarkers(map, markers);
        
        };
        
        export { initMapbox };`

I'm using turbolinks, so in application.js I added this;

        `import { initMapbox } from '../plugins/init_mapbox';
        
        
        document.addEventListener('turbolinks:load', () => {
          initMapbox();
        });` 

Mapbox is working fine, very fine, but I don't know how to fix this little issue. I need to allways manually refresh the page in the browser. If not I can not see the selected markers.

I don't want to insert a reload button in the control div because I want to learn how to do this in the correct way.  

Thanks in advance for your help.

**Comment by ryanhamley** [comment] 2021-01-14 18:32
It's hard to say what the issue is without a minimal example of the behavior but my guess is that you're only adding the markers on page load which isn't happening when you change the marker type. You may need a different event, but I'm not familiar with Turbolinks. I'm pretty sure this isn't a bug in GL JS so I'm going to close this issue, but if you need more help, you can reach out to [Mapbox Support](https://support.mapbox.com/hc/en-us).

**Closed by ryanhamley** 2021-01-14 18:32 UTC
