### ISSUE TITLE
Isochrone map is not displaying the full area at certain zoom levels

### ISSUE THREAD

**Issue by ellismanellisplan** [mapbox/mapbox-gl-js#9913] opened 2020-08-05 19:00 UTC
**Steps to replicate**
1. GET https://api.mapbox.com/isochrone/v1/mapbox/driving (replicated with a few different coordinates and driving distances)
2. The mapbox will load
3. Zoom out the the furthest zoom level and the isochrone will display ok
4. Zoom in and at certain random threshholds the isochrone map will change to not show the full area (see screenshots for multiple zoom levels)

**mapbox-gl-js version**:
v1.11.1

**browser**:
Desktop
Chrome Version 84.0.4147.105
or
Safari Version 13.1.2 (13609.3.5.1.5)

![image](https://user-images.githubusercontent.com/39313620/89451797-97d5ab80-d711-11ea-9f54-7eb7ae089a68.png)

![image](https://user-images.githubusercontent.com/39313620/89451777-90160700-d711-11ea-8716-481be86706e3.png)

![image](https://user-images.githubusercontent.com/39313620/89451815-9efcb980-d711-11ea-9eae-9ae0b852946b.png)

![image](https://user-images.githubusercontent.com/39313620/89451829-a58b3100-d711-11ea-971d-d1679d24d7fc.png)

![image](https://user-images.githubusercontent.com/39313620/89451848-ac19a880-d711-11ea-9a1e-2341bc443341.png)

**Comment by karimnaaji** [comment] 2020-08-05 23:52
>GET https://api.mapbox.com/isochrone/v1/mapbox/driving (replicated with a few different coordinates and driving distances)

@ellismanellisplan , can you provide the result of this step or a full example on https://jsfiddle.net/ to reproduce the issue?

**Comment by mourner** [comment] 2020-08-17 11:38
We can't know for sure because a live test case wasn't provided here, but I'm going to assume this is a duplicate of #7023.

**Closed by mourner** 2020-08-17 11:38 UTC
Labels: needs information :pray:
