### ISSUE TITLE
panning animation doesn't stop once zoom in or out

### ISSUE THREAD

**Issue by mapsgeek** [mapbox/mapbox-gl-js#6827] opened 2018-06-17 15:14 UTC
**mapbox-gl-js version**:

**browser**:

### Steps to Trigger Behavior

 1. pan the map 
 2. zoom in or out

### Link to Demonstration

https://jsbin.com/cuxiyuyori/edit?html,output  v 0.45
![0 45](https://user-images.githubusercontent.com/10188264/41509201-ce4209fc-7250-11e8-8272-75a17c58f246.gif)

v 0.44
![0 44](https://user-images.githubusercontent.com/10188264/41509276-a32a5868-7251-11e8-8234-648b7feaa6fe.gif)

### Expected Behavior

panning should stop at the point the user zoomed in or out.

### Actual Behavior
zooming happens but then panning continue and the map ends up somewhere else.

i'm not sure if this is a bug or not but before 0.45.0, i was working with 0.44.1 and the map was stopping once you zoom in/out, and the map becomes kinda glitchy on larger zoom

**Comment by jfirebaugh** [comment] 2018-06-18 15:25
Duplicate of #6668.

**Closed by jfirebaugh** 2018-06-18 15:25 UTC
