### ISSUE TITLE
3D Buildings Layer Toggle in V3

### ISSUE THREAD

**Issue by rivindubandara** [mapbox/mapbox-gl-js#13036] opened 2024-01-08 23:09 UTC
Hi all,

I want to request a feature to be able to turn off the 3D buildings layer. I understand this is not possible with the way V3 was built but would like the functionality as it is very useful not just for me but also for others who have had similar issues as seen.

This was a code snippet I used in V2 to edit the buildings layer.

`'map.addLayer({
        id: "3d-buildings",
        source: "composite",
        "source-layer": "building",
        filter: ["==", "extrude", "true"],
        type: "fill-extrusion",
        minzoom: 15,
        paint: {
          "fill-extrusion-color": "#aaa",
          "fill-extrusion-height": ["get", "height"],
          "fill-extrusion-base": ["get", "min_height"],
          "fill-extrusion-opacity": 1.0,
        },
        layout: {
          visibility: "visible",
        },
      });'`

This is what it looks like in V2 when I turn off the buildings and I can see the layer below at any zoom level.
![image](https://github.com/mapbox/mapbox-gl-js/assets/54240628/550bf31b-6865-4f79-a41d-bb409e08ca33)

This is what it looks like in V3 where the building layer can't be turned off and it obstructs the layers below at a certain zoom level.
![image](https://github.com/mapbox/mapbox-gl-js/assets/54240628/ac4e93e7-e3ef-4093-8fcb-943ff9b719e7)

Thanks

**Comment by palhal** [comment] 2024-01-09 20:05
I am facing a similar problem. My line layer is hidden under buildings. While this makes sense when the map is tilted, I would like to be able to show the lines above the buildings when the pitch is zero.

This is a polygon that is only partially visible with the new Standard style:

![image](https://github.com/mapbox/mapbox-gl-js/assets/56862114/007d2c53-987e-46c2-88a1-937d43f81bed) ![image](https://github.com/mapbox/mapbox-gl-js/assets/56862114/07805621-d8e6-4863-9487-37cc638a9b26)

Layer is added like this:

```js
map.addLayer({
    // Non-relevant properties removed for brevity
    type: 'line',
    paint: {
        'line-color': '#198754',
        'line-emissive-strength': 1,
        'line-width': 3
    }
})
```

**Comment by rivindubandara** [comment] 2024-01-09 21:44
Hi @palhal,

V3 has a new 'slot' property which you can move the layer above and below the existing features.

` map.addLayer({
          id: "cadastre-raster-layer",
          **slot: 'middle',**
          type: "raster",
          source: "cadastre-raster-tiles",
          minzoom: 0,
          maxzoom: 22,
          layout: {
            visibility: "none",
          },
          paint: {
            'raster-emissive-strength': 1.0
          }
        });`

This might be what you're looking for, but having the ability to toggle off buildings in your case would also be a beneficial feature.

**Comment by palhal** [comment] 2024-01-11 18:09
Thanks for the suggestion, but it doesn't help in this case. When you add a layer without specifying _slot_ and _beforeId_, it is added above everything else. Nevertheless, the lines are still hidden under the 3D buildings. I agree that having a toggle for 3D buildings would be great.

As a side note, the _top_ slot is actually [not at the very top](https://docs.mapbox.com/help/tutorials/aa-standard-in-studio/#place-layer-in-a-slot).

**Comment by stepankuzmin** [comment] 2024-01-16 15:16
Hi all,

Unfortunately, turning off 3D Buildings and trees in the Standard Style is not currently supported. Closing this issue as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/13009 so we can track it in one place.

**Closed by stepankuzmin** 2024-01-16 15:16 UTC
Labels: feature :green_apple:

**Comment by JuanIrache** [comment] 2024-01-17 19:51
I'm not sure this issue is a duplicate. While the other one seems to be strictly about hiding 3D objects, this one is rather about being able to see the shapes we added on 'top'. In other words, shouldn't the top slot draw over everything instead of hiding shapes under buildings?

**Comment by astojilj** [comment] 2024-01-20 05:54
@JuanIrache, If you're using image source for shapes, new property [raster-elevation](https://github.com/mapbox/mapbox-gl-js/blob/d8827408c6f4c4ceecba517931c96dda8bb261a1/src/style-spec/reference/v8.json#L7628) might be useful.

**Comment by JuanIrache** [comment] 2024-01-21 00:06
> @JuanIrache, If you're using image source for shapes, new property [raster-elevation](https://github.com/mapbox/mapbox-gl-js/blob/d8827408c6f4c4ceecba517931c96dda8bb261a1/src/style-spec/reference/v8.json#L7628) might be useful.

Thanks, no. I'm just drawing lines based on a geoJSON source.

For example, the Frank style in this gallery shows added layers on top of 3D buildings: https://www.mapbox.com/gallery
<img width="932" alt="Screenshot 2024-01-21 at 00 55 42" src="https://github.com/mapbox/mapbox-gl-js/assets/5341183/4370de77-d819-4f20-bfbe-9189b619a18b">

While Standard does not:
<img width="938" alt="Screenshot 2024-01-21 at 00 55 23" src="https://github.com/mapbox/mapbox-gl-js/assets/5341183/46ca12b8-6b06-4284-a6c1-c84a1598cca4">

**Comment by astojilj** [comment] 2024-01-30 15:10
@palhal @JuanIrache @rivindubandara 

@stepankuzmin has just shared that disabling the terrain (`setTerrain(null)`) and adding layers to the "top" slot should overlay the 3D buildings layer, and a gist for the reference: [https://gist.github.com/stepankuzmin/5858e404d1c382460179707543fdce77]

Please try it and comment if the issue gets resolved.

**Comment by palhal** [comment] 2024-01-30 19:47
Thanks @astojilj. I can confirm that `setTerrain(null)` solves the problem. Unfortunately, I want to have terrain enabled, so I guess the question is, are there any plans to fix this another way? In the meantime, I can probably make something work by setting/resetting terrain depending on the current pitch.

**Comment by JuanIrache** [comment] 2024-01-30 20:31
> Thanks @astojilj. I can confirm that `setTerrain(null)` solves the problem. Unfortunately, I want to have terrain enabled, so I guess the question is, are there any plans to fix this another way? In the meantime, I can probably make something work by setting/resetting terrain depending on the current pitch.

Same. It works in some cases, but it's only a partial solution because:
1) In many cases, I want to use terrain (other styles can draw on the top layer even when terrain and 3D buildings are enabled. See my previous post)
2) For some reason this is only working for me if I call setTerrain(null) a few seconds after the 'style.load' event. If I do it within the 'style.load' function like in the gist, this has no effect
