### ISSUE TITLE
Add marker in source

### ISSUE THREAD

**Issue by JSMap** [mapbox/mapbox-gl-js#2552] opened 2016-05-10 02:16 UTC
Hi,

How to replicate the same code with Mapbox GL ? I would like to add some dynamic marker in one Source.

```
var markers = new L.MarkerClusterGroup();

    for (var i = 0; i < 10; i++) {
        var title = 'test1';
        var marker = L.marker(new L.LatLng(a[0], a[1]), {
            icon: L.mapbox.marker.icon({'marker-symbol': 'post', 'marker-color': '0044FF'}),
            title: title
        });
        marker.bindPopup(title);
        markers.addLayer(marker);
    }
    map.addLayer(markers);
```

Thank you

**Comment by lucaswoj** [comment] 2016-05-10 16:12
Hi @JSMap! 

Fundamentally, "markers" are an idea from image tiled maps that don't make as much sense for vector maps. In a vector map, you can create "markers" with a [GeoJSON source](https://www.mapbox.com/mapbox-gl-style-spec/#sources-geojson) and a [symbol layer](https://www.mapbox.com/mapbox-gl-style-spec/#layers-symbol). 

Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/656

**Closed** 2016-05-10 16:18 UTC

**Comment by JSMap** [comment] 2016-05-10 21:01
OK but do you have a solution to add a geojson feature to the source?

**Comment by lucaswoj** [comment] 2016-05-11 16:51
see [`GeoJSONSource#setData`](https://www.mapbox.com/mapbox-gl-js/api/#GeoJSONSource#setData)

**Comment by kylebebak** [comment] 2017-12-28 19:59
@lucaswoj 
This link is broken.

Adding markers to a map is really basic functionality. I put it to you that most people, if they knew how difficult it was to render a few hundred markers with custom styles and images on a map, wouldn't even consider using Mapbox for a project.

The attitude I've seen in these issues regarding markers is really disconcerting, and will ensure that a lot of users migrate to Google Maps.

**Comment by mollymerp** [comment] 2018-01-04 18:12
I've fixed the link above, and here are two more examples of how to add markers (both DOM elements, and symbol layers) in gl-js
https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/
https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/
