### ISSUE TITLE
Links to cross-origin destinations are unsafe - Lighthouse best practices report

### ISSUE THREAD

**Issue by Berava** [mapbox/mapbox-gl-js#10728] opened 2021-06-01 06:10 UTC
**mapbox-gl-js version**: v2.2.0

**browser**: Chrome Version 90.0.4430.212 

When i perform an audit in Chrome DevTools, Lighthouse reports me this (which decrease the best practices score) : 

<img width="636" alt="Capture d’écran 2021-06-01 à 08 05 18" src="https://user-images.githubusercontent.com/37666273/120274419-1c507680-c2b0-11eb-8f5c-f2f8108a67c5.png">

Any way to improve this result ?

**Comment by mourner** [comment] 2021-06-02 08:07
Currently not, but we're tracking this — closing as a duplicate of #9269

**Closed by mourner** 2021-06-02 08:07 UTC
