### ISSUE TITLE
minZoom issue on some displays/browsers

### ISSUE THREAD

**Issue by jordanbommelje** [mapbox/mapbox-gl-js#2842] opened 2016-07-08 13:53 UTC
### Steps to trigger behavior

 1. Set minZoom in map attributes
 2. Visit map 

### Expected behavior
Zoom level should be limited to what's set in the JS attributes.
### Actual behavior
On larger/hi-res screens, the minZoom value isn't followed. I thought this was a Chrome specific issue, however one of my maps it happens in Safari as well. All seem to yield different looking maps, however.

### Environment
15" Retina MacBook Pro with 27" 4k Monitor running Mac OS 10.11.5
12" Retina MacBook running Mac OS 10.11.5

### Example outputs
**15" MacBook Pro on 4k**
http://weareroberts.com/maps/chrome-15.png
http://weareroberts.com/maps/safari-15.png
http://weareroberts.com/maps/firefox-15.png

**12" MacBook**
http://weareroberts.com/maps/chrome-12.png
http://weareroberts.com/maps/safari-12.png
http://weareroberts.com/maps/firefox-12.png

### Link for testing
http://weareroberts.com/maps/satellite-test.html

**Comment by lucaswoj** [comment] 2016-07-29 22:21
Are you seeing the map use a zoom that is less than `minZoom` when necessary to avoid drawing outside the range of "real" longitudes and latitudes? If so, this is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/835

**Closed** 2016-08-02 21:19 UTC
Labels: bug, needs clarification
