### ISSUE TITLE
Overlapping polygons in the same source/layer renders odd when camera is pitched

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#3702] opened 2016-11-26 14:25 UTC
**mapbox-gl-js 0.28.0**:

I'm not sure whether this is a bug or expected behaviour.

### Steps to Trigger Behavior

 1. Add a source with two overlapping polygons
 2. Style them with different colors using data-driven fill-color
 3. Change the camera pitch 

### Expected Behavior
With zero pitch one of the overlapping polygons is always drawn on top of the other, I would expect this to also be the case when pitch is changed.

### Actual Behavior
Rendering starts to flicker (especially if there are many overlapping polygons) and the result looks like a drawing race condition between the polygons.

Example available at http://codepen.io/anon/pen/BQdQzJ (pitch the camera to provoke issue).

<img width="455" alt="screen shot 2016-11-26 at 15 22 00" src="https://cloud.githubusercontent.com/assets/1205805/20640904/45646a0e-b3ec-11e6-9ea0-3a2af80dafef.png">

**Comment by lbud** [comment] 2016-11-26 14:33
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/3320.

**Closed by lbud** 2016-11-26 14:33 UTC
