### ISSUE TITLE
Benchmarks server is broken on master and publisher-production

### ISSUE THREAD

**Issue by ryanhamley** [mapbox/mapbox-gl-js#8419] opened 2019-07-02 01:16 UTC
**mapbox-gl-js version**:
current `master` and `publisher-production`

**browser**:
n/a

### Steps to Trigger Behavior

 1. run `yarn run start-bench`

### Link to Demonstration
n/a

### Expected Behavior
The benchmarks server should run without error

### Actual Behavior
on `master`, the server will often fail while complaining that the Javascript heap is out of memory
<img width="2990" alt="Screen Shot 2019-07-01 at 6 12 20 PM" src="https://user-images.githubusercontent.com/4523080/60475378-de61f800-9c2b-11e9-89b6-9557e587f84e.png">

on `publisher-production`, the server will die with a React DOM error
<img width="920" alt="Screen Shot 2019-07-01 at 6 13 26 PM" src="https://user-images.githubusercontent.com/4523080/60475396-f9346c80-9c2b-11e9-9312-10dab1055d0c.png">

**Comment by ryanhamley** [comment] 2019-07-02 01:18
cc @mapbox/docs I believe the `publisher-production` issue is related to the update to React DOM in https://github.com/mapbox/mapbox-gl-js/pull/8362

**Comment by mourner** [comment] 2019-07-02 09:57
While I'm investigating the out of memory issue, for us to fix the React-DOM-related update, I'll need to push for a new release of `buble` and `rollup-plugin-buble` that include my fix in https://github.com/bublejs/buble/pull/194 — afterwards we'll be able to update deps freely without build issues.

**Comment by mourner** [comment] 2019-07-02 10:00
@ryanhamley can you say more about the out-of-memory issue — e.g. provide your version of Node, a full log of the error, make sure Yarn was run, etc.? I can't reproduce on my machine with Node v10.16.0.

**Comment by ryanhamley** [comment] 2019-07-02 18:16
@mourner I can produce it on Node 8.11.4 with Yarn 1.16.0 when running `yarn run start-bench` or `yarn run watch-benchmarks`. It doesn't happen with `yarn run build-benchmarks` so it's obviously something with the view.

Full stack trace
<img width="3004" alt="Screen Shot 2019-07-02 at 11 05 19 AM" src="https://user-images.githubusercontent.com/4523080/60535630-6e9a4e80-9cb9-11e9-9108-3aa3ac75b523.png">

**Comment by mourner** [comment] 2019-07-02 18:43
@ryanhamley yeah, I managed to reproduce after switching to Node v8. Can you try https://github.com/mapbox/mapbox-gl-js/pull/8422?

**Comment by ryanhamley** [comment] 2019-07-02 18:57
I'm not getting the memory error anymore but I do get errors in the console that prevent the benchmarks from running @mourner 

<img width="373" alt="Screen Shot 2019-07-02 at 11 48 30 AM" src="https://user-images.githubusercontent.com/4523080/60538991-9640e500-9cc0-11e9-8e50-771a1b37b96f.png">

**Comment by mourner** [comment] 2019-07-02 19:27
@ryanhamley oops, just pushed a fix — can you try again?

**Comment by ahk** [comment] 2019-07-02 22:08
FYI I received this crash and stack trace running `yarn start-docs` on node 10:

```
C02YH4XHJHD2:mapbox-gl-js andrewkurtz$ 
<--- Last few GCs --->

[13374:0x10264e000]    27780 ms: Mark-sweep 1394.0 (1447.1) -> 1390.7 (1433.1) MB, 1456.6 / 0.0 ms  (+ 43.6 ms in 200 steps since start of marking, biggest step 8.0 ms, walltime since start of marking 1551 ms) (average mu = 0.197, current mu = 0.104) fina[13374:0x10264e000]    28851 ms: Mark-sweep 1397.2 (1433.1) -> 1395.1 (1437.1) MB, 1043.2 / 0.0 ms  (+ 0.1 ms in 103 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1069 ms) (average mu = 0.133, current mu = 0.026) alloc

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1e2babc5be3d]
Security context: 0x2ce1e909e6e9 <JSObject>
    1: formatError(aka formatError) [0x2ce17e476141] [/Users/andrewkurtz/Code/mbox/mapbox-gl-js/node_modules/webpack/lib/Stats.js:~186] [pc=0x1e2bac419537](this=0x2ce1236026f1 <undefined>,e=0x2ce12a6c1b69 <Error map = 0x2ce19f987691>)
    2: arguments adaptor frame: 3->1
    3: map [0x2ce1e9086e61](this=0x2ce12a6bf0c9 <JSArray[1]>,0x2ce17e476141 <JSFunction ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003c597 node::Abort() [/Users/andrewkurtz/.nvm/versions/node/v10.15.3/bin/node]
 2: 0x10003c7a1 node::OnFatalError(char const*, char const*) [/Users/andrewkurtz/.nvm/versions/node/v10.15.3/bin/node]
 3: 0x1001ad575 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/andrewkurtz/.nvm/versions/node/v10.15.3/bin/node]
 4: 0x100579242 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/andrewkurtz/.nvm/versions/node/v10.15.3/bin/node]
 5: 0x10057bd15 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/andrewkurtz/.nvm/versions/node/v10.15.3/bin/node]
 6: 0x100577bbf v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/andrewkurtz/.nvm/versions/node/v10.15.3/bin/node]
 7: 0x100575d94 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/andrewkurtz/.nvm/versions/node/v10.15.3/bin/node]
 8: 0x100574998 v8::internal::Heap::HandleGCRequest() [/Users/andrewkurtz/.nvm/versions/node/v10.15.3/bin/node]
 9: 0x10052a1c8 v8::internal::StackGuard::HandleInterrupts() [/Users/andrewkurtz/.nvm/versions/node/v10.15.3/bin/node]
10: 0x1007d9bb1 v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/andrewkurtz/.nvm/versions/node/v10.15.3/bin/node]
11: 0x1e2babc5be3d 
12: 0x1e2bac419537 
/bin/sh: line 1: 13374 Abort trap: 6           DEPLOY_ENV=local batfish start
```

**Closed** 2019-07-03 20:21 UTC
Labels: bug :beetle:, needs information :pray:
