### ISSUE TITLE
Marker clustering

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1211] opened 2015-05-20 20:04 UTC
A GL equivalent of https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-markercluster/

How this works in my mind: symbols get a `cluster-distance` property (default 0px). All symbols that fall under this distance from one another will automatically get lumped into one symbol. In order to get lumped, every symbol must be within this distance to every other member. 

The lumping result might differ, depending on what order the renderer iterates through the symbols.

**Comment by peterqliu** [comment] 2015-05-20 20:05
Writing a spec for how to style this lumped symbol is a whole nother ball of wax, but this is a start.

**Comment by mourner** [comment] 2015-05-20 20:59
Duplicate of #837

**Closed by mourner** 2015-05-20 20:59 UTC
Labels: enhancement

**Comment by liampmccabe** [comment] 2017-10-05 13:31
I've checked out the other issues but they seem to deviate from actual marker clustering (but rather point clustering). Is this feature still in development? Or is it possible with other aspects of the API?

Currently I'd like to cluster these markers, or as a compromise only show the avatars at a particular zoom level.
![image](https://user-images.githubusercontent.com/3018957/31229649-58a63b9a-a9d9-11e7-9025-054d2a89720b.png)

**Comment by mollymerp** [comment] 2017-10-06 23:31
@liampmccabe clustering is supported for geojson sources https://www.mapbox.com/mapbox-gl-js/example/cluster/
the ticket tracking clustering HTML `Marker`s, which I believe is what you're looking for, is here https://github.com/mapbox/mapbox-gl-js/issues/4491

**Comment by thuanmb** [comment] 2018-03-22 10:31
For ReactJS lover, here is a solution for clustering in mapbox-gl:
https://github.com/thuanmb/react-mapbox-gl-cluster
