### ISSUE TITLE
Custom images into points

### ISSUE THREAD

**Issue by fran320** [mapbox/mapbox-gl-js#2522] opened 2016-05-02 09:06 UTC
Hi, I have a collection points defined into a database. Each icon is defined by a name and a the server file path.
I need to use this images as icon-image into the map.
I read about the sprite document, but I can't use this solution.
There is a way to show custom icon-image icons, defined by a server path?

**Comment by mourner** [comment] 2016-05-03 07:59
Duplicate of #358.

**Closed by mourner** 2016-05-03 07:59 UTC
