### ISSUE TITLE
Markers in mapbox-gl for react

### ISSUE THREAD

**Issue by pedroignacio13** [mapbox/mapbox-gl-js#11021] opened 2021-09-15 14:40 UTC
**2.2.0**:

### Question
I've been using react to build my PWA and mapbox-gl to display a beautiful map in my page. Whenever i try to add a marker to my app it throws me a "t.getcanvascontainer is not a function" error. I'm using react functional components and haven't been able to solve this problem. How can i add the marker to my map?

**Comment by rreusser** [comment] 2021-09-15 16:56
Hmm… it's a bit tricky to diagnose without code or a fully reproducible example. The above would seem to suggest a problem with this line

https://github.com/mapbox/mapbox-gl-js/blob/7dc8df6ca4df6d7e70475e21435244b7d4b8b31e/src/ui/marker.js#L258

which suggests it's a problem with the map reference received by the marker. Using [the example from the docs](https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker-example), this would mean that in this code:

```js
// Create a new marker.
const marker = new mapboxgl.Marker()
.setLngLat([30.5, 50.5])
.addTo(map);
```

`map` undefined may trigger the error you're seeing.

That's just a guess though. To fully diagnose will require some additional information. Strictly speaking, we don't develop or support react+mapbox interfaces directly so that [Mapbox Support](https://www.mapbox.com/support) may be the best channel, though we're glad to diagnose some basic usage issues and get people pointed in the right direction.

**Comment by rreusser** [comment] 2021-09-15 22:04
If it's alright, I'm going to close this issue since we use this issue tracker to focus on bug reports and feature requests for the GL JS library itself, and since I think the error indicates an undefined reference to the `map` which originates in the react component, but please reopen if I'm mistaken about what's going on here.

**Closed by rreusser** 2021-09-15 22:04 UTC
