### ISSUE TITLE
Visibility as a property on the Features for a GeoJSON source

### ISSUE THREAD

**Issue by steinbachr** [mapbox/mapbox-gl-js#1786] opened 2015-12-02 17:22 UTC
Given a GeoJSON source with a bunch of features we want to render as symbols, it would be good to have a property appended to each feature, `isVIsible`, designating whether that feature is currently visible or not. The issue is especially important for cases when trying to select features within a given boundary by using `featuresAt` or `featuresWithin`. Without this identifier, it's impossible to tell whether the features selected are visible or currently being hidden without doing the extra and - seemingly unnecessary - steps of:

1) checking which of the selected features intersect each other at the current zoom
2) for those that intersect, comparing drawing order and only selecting the feature drawn first

See fiddle <a href="https://jsfiddle.net/rrmzoxr9/1/">here</a> for example of issue.

Note: This all assumes  `icon-allow-overlap: false` on the layer, otherwise this is a non-issue

**Comment by jfirebaugh** [comment] 2015-12-04 22:49
Duplicate of #582.

**Closed by jfirebaugh** 2015-12-04 22:49 UTC
