### ISSUE TITLE
By default, snap back to "w=0" world after panning operation (i.e. "worldCopyJump")

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-gl-js#2071] opened 2016-02-05 21:42 UTC
Because certain methods like `flyTo` send the user on to world copies, it would be great if there were an option to duplicate data/overlays to the other world copies as well.

**Comment by 1ec5** [comment] 2016-02-05 21:48
Only `flyTo` goes to a world copy at the moment (#1853). It probably should go back to the original world on the last frame, though.

**Comment by drewbo** [comment] 2016-02-05 22:00
I think the only issue with that would be that it precludes setting `maxBounds` to prevent people from scrolling off the data as well (it interrupts the `flyTo` animation)

**Comment by jfirebaugh** [comment] 2016-02-05 22:18
I think `worldCopyJump` behavior should be the only behavior (no option), and `flyTo` should wrap on the first frame that crosses the antimeridian.

**Comment by lucaswoj** [comment] 2016-07-29 15:08
Duplicate of #2879

**Comment by jfirebaugh** [comment] 2016-08-21 21:19
I preferred the old implementation proposal, "Create Leaflet-like `worldCopyJump` option". That seems much more tractable than duplicating arbitrary DOM elements, which is what "Add option to copy markers and popups when panning across dateline" would require.

**Comment by lucaswoj** [comment] 2016-08-22 18:54
Ah! I misunderstood the behaviour of `worldCopyJump`. Changing the title now.

**Comment by lucaswoj** [comment] 2016-09-09 18:00
This feature is very easy to implement downstream. 

```js
map.on('moveend', function() {
  map.setCenter(map.getCenter().wrap());
});
```

cc @geografa

**Comment by jjb867** [comment] 2016-12-13 00:09
Any ideas with this?  I have been striuggling to accomplish the same behavior as described in this thread.

**Comment by jfirebaugh** [comment] 2016-12-13 00:14
@jjb867 Did you try the code snippet from https://github.com/mapbox/mapbox-gl-js/issues/2071#issuecomment-245990952?

**Comment by jjb867** [comment] 2016-12-13 00:28
Sorry but I'm not sure what you are referring to specifically.  I have a 'zoomend' event that I'm using to trigger a popup after flying to a location.  The basic idea is displaying fake transactions around the world in a popup.  The popup is displayed properly unless I'm displaying one in Hong Kong for example, it appears in Hong Kong, but in one world to the right of where I need it.

I tried 

`map.setCenter(map.getCenter().wrap());`

inside my zoomend function which does work but it creates a flash and a jarring user experience.

Is this what you are referring to?

**Comment by jfirebaugh** [comment] 2016-12-13 00:40
Yes. Can you create a JSFiddle that shows the issue you're talking about with that approach?

**Comment by jjb867** [comment] 2016-12-13 00:43
Actually just got it to work to my liking using the above snippet inside of 'zoomend' (no flash, no issue), thanks for pointing out that snippet for a second time!

**Comment by jjb867** [comment] 2016-12-13 18:54
`map.setCenter(map.getCenter().wrap());`

This line actually does work to bring the map to the world copy which the popup is rendered.  Since the map needs to instantly be re-rendered it DOES create a quick flash which is less than desirable.  I would create an example but I have too many php datapoints being read onto the page.

This works for now but it would be nice to have an option to either have the popup render on ALL world copies, or only limit the world to one instance.

**Comment by andrewharvey** [comment] 2016-12-20 07:43
>```
>map.on('moveend', function() {
>  map.setCenter(map.getCenter().wrap());
>});
>```

I found this creates an infinite loop and needed something like

```
map.on('moveend', function(e) {
   if (!e.snapWorldMove) {
      map.setCenter(map.getCenter().wrap(), { snapWorldMove: true });
   }
});
```

I still notice though that the second world does flash white for a fraction of a second on the moveend when the map.setCenter moves back to world zero.

**Comment by magiccccat** [comment] 2017-02-28 17:39
Hi guys,

Inspired by the code you provided. Newbie here. I think I found a way to address the `flyto` world zero problem.

I need to fly from locations in Asia to USA, but problem is that the `flyto` method automatically select the shortest route, in my case it is through pacific ocean to world +1 or -1, instead of sticking with original copy of world zero and going through Europe. 

So the solution is to add a mechanism to calculate if the 2 locations are in different semi-sphere. If yes, then that will be the longer rough, which `flyto` will not select by itself.  So you need to add a middle point, so that `flyto` can select the longer route and keep in world map zero by flying **from start location to middle point, then from middle point to final destination**. 

Here is my code, hope it is useful to you guys:D
````
//Prevent find the closet route and miss the markers
        var currentLocation = map.getCenter();
        var nextLocation = locationObjectArray[index].geometry.coordinates; //load the next location from geojson
        var productLng = currentLocation.lng * nextLocation[0]; 
        var productLat = currentLocation.lat * nextLocation[1];
        var midLocationCam;

// check if current location and next location are on different semi-spheres, east and west. if yes, then one of  currentLocation.lng and nextLocation[0] should be negative, so their product should be negative.

        if(productLng<0){
            var midLng = currentLocation.lng + nextLocation[0];
            var midLat;
            var currentZoom = map.getZoom();
            var currentPitch = map.getPitch();
            var currentBearing = map.getBearing();
// calculate a middle point between those locations which is in the original cope, in my case of flying from asia to USA, roughly the middle point will be in Europe.
            if (productLat <0){
                midLat = currentLocation.lat + nextLocation[1]
            }else{
                midLat = (currentLocation.lat + nextLocation[1])/2
            }
//prepare the camera object for flyto method
            midLocationCam = {
                center: [midLng,midLat],
                zoom: 1,
                pitch: currentPitch,
                bearing: currentBearing
            }
            
        };

// if the location in the middle exists, then ... 
        if(midLocationCam){
// go to the location in the middle
            map.flyTo(midLocationCam);
            midLocationCam = "";
// once movement ended then go to the final destination.
            map.once('moveend', function() {
                map.flyTo(locationObjectArray[index].properties.camera);//this is a destination loaded from geojson
            });
        }else{
//if the location in the middle does not exist, then go to the final destination directly.
               map.flyTo(locationObjectArray[index].properties.camera);

        };
````

A bump of this solution is the animation is not as smooth as directly `flyto` since the camera needs to stop at the middle point with ease and then start to fly to the final destination. 


Let me know where I can improve:D

**Comment by andrewharvey** [comment] 2017-03-20 04:12
I've submitted #4451 which will ensure a flyTo always stays in world 0. Are there any cases where you wouldn't want this to happen? Since I haven't implemented an option for it.

`easeTo`, `panTo` and `jumpTo` don't cross worlds.

This still leaves:

- [ ] while panning manually
- [ ] after panning manually but moving with inertia

**Closed** 2017-03-22 22:18 UTC
Labels: new feature
