### ISSUE TITLE
The addImage API causes a warning in web console.

### ISSUE THREAD

**Issue by joshkautz** [mapbox/mapbox-gl-js#12434] opened 2022-12-04 19:29 UTC
**mapbox-gl-js version**: 2.11.0

**browser** Google Chrome - Version 108.0.5359.95 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Use the exact code that is provided in the Mapbox Documentation example to [**Add an icon to the map**](https://docs.mapbox.com/mapbox-gl-js/example/add-image/).

### Link to Demonstration

https://jsbin.com/juxeyefaye/edit?html,output

### Expected Behavior

No warning in the web console.

### Actual Behavior

I receive a warning in the web console that reads: _"Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently"_

**Comment by CptHolzschnauz** [comment] 2022-12-16 15:59
This is IMHO a chrome triggered warning on the canvas image. I already ask the MapBox Team to check that code in the example. I use several of these pulsing dots in different variations and the render function is called every time as well the

`map.triggerRepaint(); `

I changed it to:
` this.context = canvas.getContext('2d', {willReadFrequently: true});`
but the perfomance question is still on the table. I noticed that the snapchat snapmap is using these pulsing dots.
Maybe a mapbox team member can comment the perfomance question and provide some canvas examples as well?
Thx
PS: @stepankuzmin : i think that's not a bug

**Comment by SnailBones** [comment] 2022-12-16 22:55
Possibly resolved by https://github.com/mapbox/mapbox-gl-js/pull/12397

**Comment by mourner** [comment] 2022-12-16 23:02
Yep, should be fixed in v2.12-beta.1.

**Closed by mourner** 2022-12-16 23:02 UTC
Labels: bug :lady_beetle:

**Comment by joshkautz** [comment] 2022-12-17 02:36
Incredible. Thank you. Great communication and progress!! ✨
