### ISSUE TITLE
padding option in flyTo not working on v3.3.0

### ISSUE THREAD

**Issue by ricardoweiss** [mapbox/mapbox-gl-js#13158] opened 2024-04-19 07:48 UTC
Ive updated my mapbox gl version from 3.0.0 to 3.3.0, and the padding of the flyTo property stopped being applied, ive always used this padding values alongside a center coordinates, but now the map stays in the same  position, regardless the padding

**mapbox-gl-js version**: v3.3.0

**browser**: chrome version 124.0.6367.61 (Official Build) (arm64)

### Steps to Trigger Behavior

 1. call flyTo with a specific padding

### Link to Demonstration

https://jsbin.com/cedunubake/edit?html,output

### Expected Behavior

- the left padding should be applied 

### Actual Behavior

- the center of the map still is the coordinates provided, no padding applied

**Comment by mourner** [comment] 2024-04-22 17:41
Closing as a duplicate of #13152.

**Closed by mourner** 2024-04-22 17:41 UTC
