### ISSUE TITLE
Fix output of Map#project during drag pan inertia

### ISSUE THREAD

**Issue by yunluyl** [mapbox/mapbox-gl-js#2901] opened 2016-07-22 02:52 UTC
The pixel position returned from the map.project(lnglat) function drift from the real lnglat position on the map during drag pan inertia animation (the slow down effect after drag stops with speed).

**Comment by mourner** [comment] 2016-07-29 08:37
Can you set up a JSFiddle test case to demonstrate the issue?

**Comment by yunluyl** [comment] 2016-07-29 13:57
I set up a jsfiddle, and found out the problem is actually caused by the map.project(lnglat) function. I was using map.getCenter and map.project at the same time in my project. Somehow it made me thought the problem was caused by getCetner. I was wrong. I'll update the issue title and description.

The problem is when I use map.project to project a div to a lnglat position on the map, it drifts form the real position during drag pan inertia animation.

JSFiddle is here:
https://jsfiddle.net/3wxrt7nu/2/

**Comment by mourner** [comment] 2016-07-29 14:28
Yeah, it looks like the same problem that causes `mapboxgl.Marker` elements to drift on inertia... Also reproducible when panning using keyboard.

**Comment by songyumeng** [comment] 2017-08-31 07:20
Hi,how about this problem?Is there any way to fix?

**Comment by jfirebaugh** [comment] 2018-02-22 02:14
This was fixed by either #6005 or #4670.

**Closed by jfirebaugh** 2018-02-22 02:14 UTC
Labels: bug, medium priority
