### ISSUE TITLE
Allow control over what controls are added in NavigationControl()

### ISSUE THREAD

**Issue by Jakobud** [mapbox/mapbox-gl-js#5046] opened 2017-07-25 23:00 UTC
## Motivation

It's nice that you can optionally add navigation controls to a map using NavigationControl(). But the control has no customization options. You either have to have all the controls or none. It would be nice to have the ability to have ONLY the zoom in and zoom out buttons but NOT the compass control. Currently you cannot do this.

There are already ways to disable changing the bearing and pitch interactively via the mouse:

```
// disable map rotation using right click + drag
map.dragRotate.disable();

// disable map rotation using touch rotation gesture
map.touchZoomRotate.disableRotation();
```

But if you need to have zoom in/out controls on your page, you are now also forced to have the compass. And when you click that compass, it resets the rotation of the map. So now, even though you disabled rotation interactively, the user reset the rotation and they cannot get the map back to it's original state.

## Design

Allow options to be passed to the NavigationControl() constructor where you specify which controls you want to appear. Something like:

```
var nav = new mapboxgl.NavigationControl({
  zoomIn: true,
  zoomOut: true,
  compass: false
})
```

There are no drawbacks to this as far as I can see. Make the defaults `true` for the above options and this would ensure backwards compatibility.

**Comment by jfirebaugh** [comment] 2017-07-25 23:07
Duplicate of #1554.

**Closed by jfirebaugh** 2017-07-25 23:07 UTC

**Comment by Jakobud** [comment] 2017-07-26 17:07
Ah I couldn't find that. Thanks
