### ISSUE TITLE
Unexpected token issue after upgrading to mapbox-gl 2.6.0

### ISSUE THREAD

**Issue by ghc20** [mapbox/mapbox-gl-js#11288] opened 2021-11-16 16:56 UTC
We have set up a script to compile the mapbox-gl library with our Angular 7+ app on production. The script worked correctly with any mapbox-gl version before 2.6.0. 

### Steps to Trigger Behavior

 1. Upgraded mapbox-gl from 2.5.1 to 2.6.0
 2. Compiled mapbox-gl 2.6.0 with our Angular app using systemjs-builder
 3. The following error was thrown:
 
![image](https://user-images.githubusercontent.com/1156770/142028522-1ac67080-cbfb-403e-a2f3-3cb22f2c0ef4.png)
 
 4. Rolling back mapbox-gl to 2.5.1 resolved the issue

**Comment by ryanhamley** [comment] 2021-11-16 22:09
Do you use a browserslist in your setup?

**Comment by ghc20** [comment] 2021-11-16 23:13
@ryanhamley, no, we did not use browserslist.

**Comment by ryanhamley** [comment] 2021-11-17 02:28
Out of curiosity, what version of SystemJS are you using? I'm not very familiar with the project, but when I look up systemjs-builder, I find an archived project that doesn't appear set up for handling Object spread syntax (`{...foo}`). The newer versions of SystemJS however do seem to be able to handle this syntax. I'm just trying to understand what's causing this issue so we can address it to the best of our ability.

The issue seems to be the introduction of the Object spread notation in v2.6's projection code. This is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/11266 so I'm going to close this to consolidate discussion in that earlier ticket.

**Closed by ryanhamley** 2021-11-17 02:28 UTC

**Comment by ghc20** [comment] 2021-11-18 17:34
@ryanhamley, thank you very much for the hint. We are using an old version of SystemJS since the new one does not take System.config function which is used in our compiling program. I need to investigate if we can upgrade to the new SystemJS.
