### ISSUE TITLE
can't use mapbox-gl.js built from source

### ISSUE THREAD

**Issue by buriwoy** [mapbox/mapbox-gl-js#4492] opened 2017-03-24 15:33 UTC
Hi guys,

I'm building a js file using this command:

```bash
user$ npm run build-min

> mapbox-gl@0.34.0 build-min /home/user/Downloads/mapbox-lib
> browserify src/index.js --debug --plugin [minifyify --map mapbox-gl.js.map --output dist/mapbox-gl.js.map] --standalone mapboxgl > dist/mapbox-gl.js && tap --no-coverage test/build/min.test.js

test/build/min.test.js ................................ 6/6
total ................................................. 6/6

  6 passing (323.583ms)

  ok
```

I'm trying to use `dist/mapbox-gl.js` inside an app:

```javascript
var mapboxgl = require('dist/mapbox-gl');
```

But I'm getting a bunch of "Cannot find module..." errors like this:

```bash
[15:29:53] Browserify Error { Error: Cannot find module './feature' from '/home/user/mapbox/lib'
```
 
It's throwing 30,000+ lines of errors.

What am I doing wrong?

thanks!

**Comment by jfirebaugh** [comment] 2017-03-24 15:35
Thanks for the report. This is a duplicate of #4453, which has been fixed for the next release.

**Closed by jfirebaugh** 2017-03-24 15:35 UTC
