### ISSUE TITLE
Better error handling around unknown source value

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#2047] opened 2016-02-03 04:41 UTC
If a source name doesn't exist like in this example:

```js
map.addLayer({
  type: 'circle',
  source: 'foo'
});
```

the error logged is

    Cannot read property 'reload' of undefined

It would be swell if the error message was more descriptive like: 

    Cannot read property. Source 'foo' is undefined

See http://bl.ocks.org/tristen/89a363ed22545ce09315 for example.

**Comment by tmcw** [comment] 2016-02-03 15:58
:+1: I think we could do a better job with dev ux, potentially using the invariant pattern. I'll look into this today.

**Comment by mourner** [comment] 2016-02-03 16:01
This looks like a duplicate of #1632 (see also comment https://github.com/mapbox/mapbox-gl-js/issues/1632#issuecomment-149659554)

**Comment by tmcw** [comment] 2016-02-03 16:06
Yep, merging into  #1632 - the validation strategy wasn't what I was thinking but seems like a cool idea, so I'll just see where it goes.

**Closed by tmcw** 2016-02-03 16:06 UTC
