### ISSUE TITLE
When the parent element is scaled, the canvas width and height calculation is not full screen  

### ISSUE THREAD

**Issue by yueyanshaosun** [mapbox/mapbox-gl-js#11261] opened 2021-11-09 06:37 UTC
When the parent element is scaled, the canvas width and height calculation is not full screen  

.map {
 transform: scale(0.5)
}
<div class="map" id="map"></div>

when the dom(map) css is scaled， the canvas width and height calculation is not full screen

**Comment by ryanhamley** [comment] 2021-11-09 16:55
Please fill out the issue template completely when opening a new issue. There's not enough information here for us to help. Can you at least provide an example of the code (use a site like JSBin or CodePen) and let us know what browser this is in? My hunch is this is expected behavior since the container is scaled but that's just a guess. I'm going to close this as non-actionable for now but if you provide an example, I can re-open if necessary.

**Closed by ryanhamley** 2021-11-09 16:55 UTC

**Comment by yueyanshaosun** [comment] 2021-11-10 03:19
https://codesandbox.io/s/cocky-dirac-7fsbi?file=/index.html

This is the example address
