### ISSUE TITLE
Weird truncating with icon-allow-overlap enabled and large icons

### ISSUE THREAD

**Issue by mbullington** [mapbox/mapbox-gl-js#3798] opened 2016-12-14 02:45 UTC
Hello! We're using large icons to achieve a certain aesthetic that we want, but we ran into a problem that when we have `icon-allow-overlap` enabled (which it needs to be for us), sometimes the bounding boxes for certain icons affect how other icons render. Image is attached below.

Reproducible on latest Mapbox version, recent Chrome versions, and the bug was found on macOS (although I doubt it's platform specific).

### Steps to Trigger Behavior

 1. Have two points close together with a symbol icon of a large size and icon-allow-overlap enabled.

### Expected Behavior

Both icons display perfectly.

### Actual Behavior

One icon is displayed perfectly, but the other one is weirdly truncated.

![pasted image at 2016_12_13 03_40 pm](https://cloud.githubusercontent.com/assets/6068785/21167828/3602a3ac-c17d-11e6-9ad2-397b3f94ca47.png)

**Comment by mollymerp** [comment] 2016-12-14 03:22
Hi @mbullington, 
Thank you for submitting your issue. I believe this is a duplicate of #2706, but its hard for me to be sure without a jsfiddle or other simple test case reproducing the issue. Closing here, but please 👍 the linked issue (we track our top user requested fixes [here](https://mapbox.github.io/top-issues/#!mapbox/mapbox-gl-js) if you think its a duplicate, or post a test case and re-open if you think its a separate issue.

**Closed by mollymerp** 2016-12-14 03:22 UTC
