### ISSUE TITLE
When I load terrain and 3D building, the height of 3D building is abnormal. (mapbox-gl 2.2.0)

### ISSUE THREAD

**Issue by ShareQiu1994** [mapbox/mapbox-gl-js#10535] opened 2021-04-02 02:23 UTC
**mapbox-gl-js version**: 2.2.0

**browser**: chrome

### Steps to Trigger Behavior

 question:When I load terrain and 3D building, the height of 3D building is abnormal

 1.  Add terrain layer
 2.  Add 3D builds layer
 
`        this.map.addLayer({
            'id': 'terrain-data',
            'source': {
                type: 'vector',
                'scheme': 'tms',
                'tiles': ['http://192.168.0.209:8097/geoserver/gwc/service/tms/1.0.0/ilng%3Ailng@EPSG%3A900913@pbf/{z}/{x}/{y}.pbf']
            },
            'source-layer': 'a_zhuhai_building',
            'type': 'fill-extrusion',
            'minzoom': 11,
            'paint': {
                'fill-extrusion-color': [
                    'interpolate',
                    ['exponential', 0.99],     // ['exponential', 0.99]
                    ['*', ['get', 'floor'], 3.5],
                    0,
                    '#52e5e7',
                    50,
                    '#130cb7'
                ],
                'fill-extrusion-height': ['*', ['get', 'floor'], 3.5],
                'fill-extrusion-base': 0,
                'fill-extrusion-opacity': 0.6
            }
        })`

![QOTNL7_8`FRHH1NK@4N1WH9](https://user-images.githubusercontent.com/19948086/113373447-68109d80-939d-11eb-889e-68eecc0c2374.png)

 PS: This problem will not occur in versions before 2.2.0

**Comment by ShareQiu1994** [comment] 2021-04-02 02:27
#10532

**Comment by mourner** [comment] 2021-04-02 10:12
Yep, let's close as a duplicate of #10532. Definitely a bug.

**Closed by mourner** 2021-04-02 10:12 UTC
