### ISSUE TITLE
React.js Choropleth Hover Speed

### ISSUE THREAD

**Issue by danielberkompas** [mapbox/mapbox-gl-js#2303] opened 2016-03-21 20:34 UTC
**mapbox-gl-js version**: 0.15.0

### Steps to Trigger Behavior

 1. Visit this JSFiddle: http://jsfiddle.net/vad3d1h5/8/
 2. Click through the Babel warning alert (it isn't relevant)
 3. Move your mouse over the map, observe hover effect
 4. Leave the tab open and return to it after a while
 5. Move your mouse over the map, observe hover effect even slower

### Expected Behavior

When I wrap a MapboxGL map in a React component, I expect that the hover effect will occur quickly when I hover over a country or province. I also expect that the hover effect performance will remain constant.

### Actual Behavior

When I wrap a MapboxGL map in a React component as shown in [this JSFiddle](http://jsfiddle.net/vad3d1h5/8/), the hover effect starts off snappy, but degrades in performance over time.

This is particularly odd because very similar code works as expected: 
https://jsfiddle.net/0Lk8awwp/1/ (Broken, shows code)
https://jsfiddle.net/Mourner/0Lk8awwp/3/ (Fixed by a Mapbox employee)

See also #2174, #2082 for earlier reports and fixes for this problem.

**Comment by lucaswoj** [comment] 2016-03-22 18:17
I regret that I am unable to help you with this question on our GitHub issue tracker because this is neither a feature request nor a bug report. 

I am unable to reproduce the hover effect slowdown using your provided example. You have linked to a similar, more minimal example that _does_ work as expected, leading me to believe this is a problem with your implementation. 

I encourage you to post this [question on StackOverflow if you need more help](http://stackoverflow.com/questions/tagged/mapbox-gl-js).

Your issues may be resolved by #2224.

**Closed by lucaswoj** 2016-03-22 18:17 UTC
Labels: support request

**Comment by mourner** [comment] 2016-03-22 18:22
@danielberkompas try the master version. If it doesn't fix the issue, try `query-rendered-features-continued` branch.

**Comment by jamonholmgren** [comment] 2016-03-22 23:07
@lucaswoj Have you tried it in Chrome? It's very slow for me.

**Comment by lucaswoj** [comment] 2016-03-23 20:52
We have two big initiatives underway to speed up interactions like this one: #2224 and #1504. 

I :heart: appreciate :heart: you creating this pull request and clearly articulating your difficulties but I don't see anything  actionable here that isn't captured by #2224 and #1504.

**Comment by danielberkompas** [comment] 2016-03-23 20:55
@lucaswoj Fair enough. Any ETA on those initiatives?

**Comment by lucaswoj** [comment] 2016-03-23 22:09
#2224 and a first pass on #1504 will go out in a release in the next couple days :rocket:
