### ISSUE TITLE
MBTiles generated by ogr2ogr does not render in vector source

### ISSUE THREAD

**Issue by nahidpervez** [mapbox/mapbox-gl-js#10316] opened 2021-01-22 09:00 UTC
**mapbox-gl-js version**: 2.0.1

**browser**:Chrome,Safari

### Steps to Trigger Behavior

 1. convert a spatialite db to mbtiles using ogr2ogr
 2. serve the tiles using flask [note: compression is enabled and response.headers['Content-Encoding'] = 'gzip']
 3. another note: I have verified the tiles are valid using vtzero
 4. one more note: the mbtiles works fine with tileserver-gl
 5. however, converting spatialite -> geojson -> mbtiles using tippecanoe works fine

### Link to Demonstration

https://jsbin.com/

### Expected Behavior
vector layer should work as long as it meets the spec and passes the vtzero checks

### Actual Behavior
vector layers doesnot render with ogr2ogr converted tiles

**Comment by asheemmamoowala** [comment] 2021-01-22 16:21
Thank you for your opening this ticket. To help the maintainers and community understand and address the problem accurately can you please provide a minimal, complete, verifiable demonstration of the issue. A sample MBTile that doesn't work, console errors or exceptions all would help diagnose the underlying issue

**Comment by nahidpervez** [comment] 2021-01-22 17:35
Hello @asheemmamoowala , thanks for the quick response. Please find the attached zip file with two pbf files. Their names are the x,y,z tile index. The working file is generated by ```tippecanoe``` and the other one is by ```ogr2ogr```. Please note that their data might be a little different.
I dont get any console errors with the non-working file.
Please let me know if you need any further information on this.

PS: Awesome job with mapboxgljs! Eager to see what more to come from you guys!
[Archive.zip](https://github.com/mapbox/mapbox-gl-js/files/5857511/Archive.zip)

**Comment by mourner** [comment] 2021-05-17 15:48
Have to close this since there's no reproducible test case, but I'd expect this to be an issue on the ogr2ogr side.

**Closed by mourner** 2021-05-17 15:48 UTC
Labels: needs information :pray:
