### ISSUE TITLE
map.getLayer() returns undocumented private type

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#11263] opened 2021-11-09 18:52 UTC
`map.getLayer(id)` returns an undocumented internal type. This exposes private methods and also doesn't expose all the data of the layer. We need decide whether to:
- return something compatible with the style-spec
- return a documented class that exposes all necessary info

We also need to think about whether changing this would break any users using the undocumented interfaces.

https://docs.mapbox.com/mapbox-gl-js/api/map/#map#getlayer

--- 

**mapbox-gl-js version**: v1.0.0 - v2.6.0 (maybe even earlier)

**browser**: all

### Steps to Trigger Behavior

 1. open http://localhost:9966/debug/
 2. map.getLayer('land')

### Expected Behavior

The return value follows the style spec interface OR is at least documented.

```{
    "id": "land",
    "type": "background",
    "metadata": {},
    "paint": {
        "background-color": ...
    }
}
````

### Actual Behavior

![Screen Shot 2021-11-09 at 1 48 51 PM](https://user-images.githubusercontent.com/1421652/140985973-e78593a4-bbf3-4946-b965-e5a5dc531e44.png)

**Comment by asheemmamoowala** [comment] 2021-12-08 22:32
Closing as duplicate of #3713

**Closed by asheemmamoowala** 2021-12-08 22:32 UTC
Labels: bug :lady_beetle:, needs discussion :speech_balloon:
