### ISSUE TITLE
Contour geojson layers disappear at high zoom

### ISSUE THREAD

**Issue by stefmarais** [mapbox/mapbox-gl-js#7857] opened 2019-01-31 02:20 UTC
**Version**: 0.52.0

I have a geojson representing contours of interpolated weather data. Certain portions of the contour layer disappear at higher zoom levels as seen in following screengrab:
![image](https://user-images.githubusercontent.com/42791138/52025694-478bf500-2540-11e9-9644-8665f0f07bb3.png)
Using the same geojson file on http://geojson.io shows the expected outcome (See below), with all contours visible at all zoom levels. 
![image](https://user-images.githubusercontent.com/42791138/52026157-cd5c7000-2541-11e9-9104-ba14324e86c4.png)

Issue is replicated in the following Fiddle:
https://jsfiddle.net/stefmarais/ae9nzmrt/12/

I want all contours to be present all the time, regardless of the zoom level. How can I fix this?

**Comment by mourner** [comment] 2019-01-31 14:52
This is likely a duplicate of #7023.

**Closed by mourner** 2019-01-31 14:52 UTC
