### ISSUE TITLE
Pull down initiates page refresh on Android Chrome

### ISSUE THREAD

**Issue by reyemtm** [mapbox/mapbox-gl-js#4472] opened 2017-03-22 00:48 UTC
Example - Any of the current Mapbox GL JS examples on the Mapbox website, so version 0.34. The user must pull straight down. Moving the finger in another other movement first, then down does not make the page refresh. So...

Pull down on the map initiates the refresh of the browser. Tested in Android 4 & 5 on chrome. This should not happen, the map should be moved only. I feel like this is a new issue but cannot be sure.

**Comment by Scarysize** [comment] 2017-03-22 07:15
Setting `touch-action: none` on the map container might just resolve this ( [touch-action MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) )

**Comment by jfirebaugh** [comment] 2017-03-23 00:42
Yes, closing as duplicate of #4259.

**Closed by jfirebaugh** 2017-03-23 00:42 UTC
