### ISSUE TITLE
Support "nested" styles

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4000] opened 2017-01-17 21:26 UTC
migrated from https://github.com/mapbox/DEPRECATED-mapbox-gl/issues/25 by @lucaswoj

> - mapbox/mapbox-gl-js#2267
> - mapbox/mapbox-gl-js#2144
> - mapbox/mapbox-gl-js#1878
> 
> ...
> 
> Users **don't expect setStyle to overwrite everything**, and consider the current behavior a bug. This is a bummer, and something that we could document around, saying "setStyle will wipe out the current state of the map". I'm fine with the documentation approach, but it needs a workaround, because "switching the map style" is a common usecase that is a hard expectation - it's easy to do in Leaflet and all similar tile-based libraries. -- @tmcw, 2016

Injecting custom layers into Mapbox core styles is a common use case and confusing to our users, especially when the user wants to swap out the core style and keep the custom layers. 

Have we considered supporting "nested styles"? These would help our users build a solid mental model of their stylesheet, encapsulate core style implementation details, allow new kinds of style modularity, and fit nicely into Studio.

``` js
map.setStyle({
    version: 9,
    layers: [{
        type: 'style',
        layout: { url: 'mapbox://styles/mapbox/streets-v9-bottom' }
    }, ..., {
        type: 'style',
        layout: { url: 'mapbox://styles/mapbox/streets-v9-top' }
    }]
});
```

**Comment by mb12** [comment] 2017-01-18 01:14
An alternative option would be to add a separate API to add points, lines and polygons. These could be internally persisted by GL JS automatically via an implicit source. GL native already supports this for feature  parity with Mapkit.

**Comment by jaapster** [comment] 2017-09-08 12:17
This would be very helpful! In our product we have a base "meta-layer", typically something like "streets-v9",  containing multiple "mapbox layers" and on top of that we add our own dynamically generated "meta-layers" (containing tile sources and "mapbox layers") and GeoJSON layers for rendering of selection, drawing etc.

**Comment by miguelleitevieira** [comment] 2018-01-24 15:24
Hi all, exist some developments on this feature?

**Comment by santinogue** [comment] 2018-01-29 17:11
Hi, any updates on this???

**Comment by stevage** [comment] 2019-07-12 05:26
Is this essentially a duplicate of #4225?

**Comment by kkaefer** [comment] 2024-03-08 11:07
We support [style imports](https://github.com/mapbox/mapbox-gl-js-internal/pull/583) now.

**Closed by kkaefer** 2024-03-08 11:07 UTC
Labels: feature :green_apple:, cross-platform :tv:

**Comment by JamesChevalier** [comment] 2024-03-08 15:15
Your link goes to an internal repository. Is this the feature you’re referring to?
https://docs.mapbox.com/style-spec/reference/imports/
