### ISSUE TITLE
Dragging sample is extreeeemely slow (even on desktop browsers -MACs with 8 GB Ram etc.).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#3085] opened 2016-08-27 18:06 UTC
**mapbox-gl-js version**: v0.23.0 and Master

### Steps to Trigger Behavior

The following sample is unacceptably slow (to the point of being unusable) on desktop chrome for Mac. (My chrome is Version 52.0.2743.116 (64-bit)

https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/

More details:

1. Performance is good/acceptable on safari on the same machine.
2. Chrome performance for this sample is still too slow for me (tried restarting browser etc as well).

### Expected Behavior
Dragging   a single point should be smooth. The blue dot should follow the mouse cursor.

### Actual Behavior
Draggin is superrrr slow. The blue dot lags wayyyy behind the mouse cursor.

**Comment by andrewharvey** [comment] 2016-08-28 00:32
See https://github.com/mapbox/mapbox-gl-js/issues/2334

**Comment by mb12** [comment] 2016-08-28 17:23
The root issue here is that Geojsonsources aren't able to mutate fast enough to handle data that changes as frequently as the mouse event. Currently it goes through a web worker to index data every time setData is called? How does 'geojson-vt' handle repeated/frequent calls to setData? Does it support delta updates / optimize use cases like this by aborting calls which have become redundant (cc @mourner )?

For small number of markers, it might be much more performant if dragging were modeled using a regular html div marker.

**Comment by mourner** [comment] 2016-08-29 16:45
@mb12 `geojson-vt` is not the bottleneck here. It's the main thread + worker communication that somehow clogs the browser and causes Chrome to deoptimize worker events heavily. We haven't been able to identify the exact cause or a workaround, and it happens sporadically (e.g. I just tried and couldn't reproduce, but sometimes after a few minutes of dragging it suddenly starts to stutter heavily). The workaround for now would be #3087.

**Comment by mb12** [comment] 2016-08-29 16:57
@mourner  It reproduces consistently  on Chrome in Mac. It also reproduces consistently on IE in Windows.

**Comment by bsudekum** [comment] 2016-08-29 17:06
As additional symptom point, I've noticed that the performance starts to degrade only after 5th or 6th click + drag event. The first couple of complete dragging events (mouse down, mouse move, mouse up) seem to work fine. I only notice poor performance after a few cycles.

Mac osx 10.12
Chrome 52.0.2743.116 (64-bit)

**Comment by lucaswoj** [comment] 2016-08-29 19:06
This could be a symptom of #2266.

**Comment by lucaswoj** [comment] 2016-09-02 21:36
I am closing this issue because it does not represent a bug in GL JS, rather a desire for better performance. We are always striving to improve performance and open to specific proposal. Without a specific proposal, this ticket is not directly actionable.

**Closed by lucaswoj** 2016-09-02 21:36 UTC
