### ISSUE TITLE
circle-radius-transition does not function for property change

### ISSUE THREAD

**Issue by gagecarto** [mapbox/mapbox-gl-js#7319] opened 2018-09-21 15:29 UTC
**mapbox-gl-js version**:
49.0

### Steps to Trigger Behavior
Circle-radius-transitions work great when feature have static radius. For example, if circle-radius is hard coded 
`"circle-radius": 10`

and circle-radius-transition is 
```
"circle-radius-transition": {
   duration: 1000
 }
```
changing the paint property triggers an animated transition of 1000
`map.setPaintProperty('myCircleLayer','circle-radius',25)`

Alternatively, if circle radius is set to a property such as
`"circle-radius": ['get','radiusProperty1']`

with the same transition
```
"circle-radius-transition": {
   duration: 1000
 }
```
changing the paint property does not trigger an animation
`map.setPaintProperty('myCircleLayer','circle-radius',['get','radiusProperty2'])`

### Expected Behavior
Animation on circle-radius when setting paint property

### Actual Behavior
Static change without animation

**Comment by mourner** [comment] 2018-09-24 09:42
This is a known limitation which is technically very difficult to overcome — closing as a duplicate of #3170.

**Closed by mourner** 2018-09-24 09:42 UTC
