### ISSUE TITLE
Fill layers don't render on some devices

### ISSUE THREAD

**Issue by ljbade** [mapbox/mapbox-gl-js#930] opened 2015-01-13 01:36 UTC
I just noticed today that on my Windows 8.1 machine random tiles are rendered blank.

The tiles jump around a bit as I zoom in and out.

I am using Chrome 39.0.2171.95 m

My machine has both Intel and NVIDIA graphics (not sure which one is used by Chrome).

**Comment by ansis** [comment] 2015-01-14 00:50
Any errors in the console?

My guess would be network errors. If it fails to download a tile it just doesn't show anything. Should it do something different when downloads fail?

**Comment by ljbade** [comment] 2015-01-14 01:35
@ansis no console errors.

Also I don't think it is download error as native has no issue on this computer and is very repeatable.

**Comment by ljbade** [comment] 2015-01-14 01:50
Tested Windows Firefox, same problem.

Can't test on IE.

Doesn't happen with either Chrome or Firefox on my Windows machine.

**Comment by jfirebaugh** [comment] 2015-06-26 00:47
@ljbade Is this still reproducible with 0.8.1?

**Comment by glennerichall** [comment] 2015-06-30 13:24
I don't know if this is the same error, mapbox-gl works correctly with Chrome and Firefox on Linux but seems to be broken on Chrome and Firefox on Windows 7. Internet Explorer seems ok on Windows 7. Looks like only certain layers not visible, on the Mapbox example page and on my application.
Note my app uses ver. 8.1:

Here are some screenshots
Internet Explorer:
![image](https://cloud.githubusercontent.com/assets/2382170/8431740/89af5df0-1f09-11e5-84a0-a3186897cc18.png)

Chrome, Firefox:
![image](https://cloud.githubusercontent.com/assets/2382170/8431752/99dad6e6-1f09-11e5-99c1-21581983c632.png)

**Comment by ansis** [comment] 2015-06-30 13:27
@glennerichall are there any errors logged in the firefox and chrome consoles?

**Comment by glennerichall** [comment] 2015-06-30 13:31
Chrome and Firefox: 
https://www.mapbox.com/core/api/session?_=1435670953287 Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by lsimkins** [comment] 2015-08-28 14:43
+1 on this issue. Several of our clients are experiencing the same thing. We currently embed Mapbox inside a .NET client app using Chromium Embedded Framework v39.0.1 which uses Chromium 39.0 under the hood. Every client using Windows 7 is experiencing the same issue.

Windows 7 using CEFv39.0.1 & Chromium 39.0
![screen shot 2015-08-28 at 9 35 34 am](https://cloud.githubusercontent.com/assets/1006600/9548860/7cb1ada0-4d68-11e5-97f3-9a096abe0064.png)

Chrome on OSX (No embed, just in browser)
![screen shot 2015-08-28 at 9 37 31 am](https://cloud.githubusercontent.com/assets/1006600/9548941/fe3b5a92-4d68-11e5-9ac3-a2d65300e3e0.png)

I haven't seen this issue first-hand yet and only have screenshots. I'll take a look in the console to try and get more information.

**Comment by lsimkins** [comment] 2015-09-30 16:10
Just to add additional information that may be relevant to troubleshooting this issue.

Initially the problem was sporadic and we were not able to replicate the issue in-house using CEFv39.0.1 on Windows 7. (CEF being Chromium Embedded Framework) MapboxGL worked perfectly.

Recently we updated CEF to v43 and suddenly we could reproduce the bug. I also noticed dropped tiles in the GL examples at https://www.mapbox.com/mapbox-gl-js/examples/.

We were only able to reproduce the issues in the more recent version of Chromium.

**Comment by Phrogz** [comment] 2015-09-30 22:41
Not sure if this is the same core issue or a different one. I've been seeing problems where some of the the background colors of various styles is different per tile. For example, from ["A simple map"](https://www.mapbox.com/mapbox-gl-js/examples/) (make sure you click on "A simple map") I see this:

![Four tiles shown with different colors for each](https://cloud.githubusercontent.com/assets/14778/10208469/cb51c02a-6790-11e5-961b-a4cb62b00c75.png)

This broken result is consistent for me across Chrome (v45.0.2454.101m), Firefox (v41.0) and IE (v11) on Windows 7x64 with a GeForce GTX 670 graphics card and the current driver (v355.82, released 2015-Aug-31).

**Comment by ljbade** [comment] 2015-10-01 04:01
@jfirebaugh Do we have a Windows 7 machine we can repro this on?

**Comment by jfirebaugh** [comment] 2015-10-01 04:32
At one point we had a floating Windows laptop in SF. Not sure if we still
do.

My first step for Windows or IE specific issues is
https://github.com/xdissent/ievms.

**Comment by Phrogz** [comment] 2015-10-01 14:27
I don't know if you updated code on the back-end, or if the Windows 7 SP1 update that I applied yesterday changed something (I suspect the former) but this morning the "simple map" works correctly across all browsers.

**Comment by lucaswoj** [comment] 2015-10-06 19:02
I am unable to reproduce this bug in any combination of (Firefox, Chrome, IE) x (`master`, `v0.11`) on a Dell XPS 9Q33 running Windows 8.1. I will try to get a Windows 7 test environment set up next.

**Comment by lucaswoj** [comment] 2015-10-06 20:45
I am further unable to reproduce this bug in a Windows 7 VM running on OS X in any of (Firefox, Chrome, IE).

**Comment by lucaswoj** [comment] 2015-10-06 22:01
@ljbade @lsimkins @glennerichall Are you seeing this issue resolved, like @phrogz in https://github.com/mapbox/mapbox-gl-js/issues/930#issuecomment-144744711? Also, what type of graphics card are you using?

**Comment by lucaswoj** [comment] 2015-10-06 22:07
@fnicollet Have you ever seen this bug?

**Comment by fnicollet** [comment] 2015-10-06 22:15
It reminds me of https://github.com/mapbox/mapbox-gl-js/issues/1074, which I reproduced in Firefox a long time ago. I don't have Firefox installed anymore but I can give it a go if you want

**Comment by BergWerkGIS** [comment] 2015-10-07 01:01
I checked https://www.mapbox.com/mapbox-gl-js/examples/ 

#### W7, FF 41.0.1 :white_check_mark: looks good, no missing tiles

-----
#### W7, Chrome 45.0.2454.101m :white_check_mark: looks good, no missing tiles

----

#### W8.1, Chrome 45.0.2454.101m, but I see the spinning cube, when I go to `get.webgl.org`:
![image](https://cloud.githubusercontent.com/assets/4549888/10326555/fd72eef6-6c9c-11e5-81ed-f7b4e8b9b397.png)

----

#### W10: Chrome 45.0.2454.101m (don't see the cube) no `Rats!` message, just:
![image](https://cloud.githubusercontent.com/assets/4549888/10326646/f55e24f0-6c9d-11e5-9814-d1822ee127bc.png)

----

#### W10,  Edge 20.10240.16384.0 (I see spinning cube):
![image](https://cloud.githubusercontent.com/assets/4549888/10326612/a0334ba4-6c9d-11e5-9e83-107815c1a301.png)

**Comment by lucaswoj** [comment] 2015-10-07 17:30
Thanks @BergWerkGIS! 

Were "W8.1, Chrome 45.0.2454.101m" and "W10: Chrome 45.0.2454.101m" in a VM?

Unfortunately, Edge is *quite* broken right now. As I understand it, this is due to bugs in Edge's WebGL implementation and will be fixed in a future release. Tracking at #1437.

**Comment by BergWerkGIS** [comment] 2015-10-07 18:13
@lucaswoj 
W8.1: MacBook Pro 13"
W10: VmWare Workstation Pro 12

**Comment by lucaswoj** [comment] 2015-10-07 19:54
@BergWerkGIS There's a separate bug here which is that some systems, including "W8.1 + Chrome 45.0.2454.101m" and "W10 + Chrome 45.0.2454.101m" incorrectly indicate that WebGL is not supported. I will ticket that out. 

Nobody is seeing **random blank tiles** as of GL JS `v0.11.1`?

**Comment by ljbade** [comment] 2015-10-08 00:16
I no longer have a Windows 7 laptop, but this laptop had an NVIDIA GPU.

**Comment by BergWerkGIS** [comment] 2015-10-08 07:33
Tried again with "W8.1 + Chrome 45.0.2454.101m":

* now it works, no error message
* don't see any blank tiles
* but see things like these:

![image](https://cloud.githubusercontent.com/assets/4549888/10360256/9683cf40-6d9f-11e5-9441-931fd1a302d6.png)

![image](https://cloud.githubusercontent.com/assets/4549888/10360260/9c271b5a-6d9f-11e5-9e45-c22db14f0dac.png)

**Comment by fnicollet** [comment] 2015-10-08 07:36
Hello @BergWerkGIS , this is a known issue of mapbox-gl-js:
https://github.com/mapbox/mapbox-gl-js/issues/757
Been there since the beginning of mapbox-gl-js but the fix is blocked by some other issues in other projects

Fabien

**Comment by lucaswoj** [comment] 2015-10-09 20:15
Based on the screenshots posted in this thread, it looks like there are a few different bugs being discussed. The main issue, as screenshot-ed in https://github.com/mapbox/mapbox-gl-js/issues/930#issuecomment-117182900, is that our fill shaders do not work on some systems. There is an effort underway to refactor how our fill shaders work in #1606.

I can confirm that this bug can be reproduced on a Nexus 6 and that #1606 resolves the issue.

**Comment by lsimkins** [comment] 2015-11-11 20:49
Just tested #1606 today and can confirm that it fixes all rendering issues we saw.

Any news on when #1606 will be merged? We're releasing a new version of our product next week that fully replaces Google Earth with mb-gl, and a few of our clients are running into the rendering issue.

Also - thank you!

**Comment by appgeodata** [comment] 2016-04-15 21:40
![mapboxgooglever50onwindows](https://cloud.githubusercontent.com/assets/18491387/14575647/f4a44042-0317-11e6-972d-d57a7961148f.jpg)

**Comment by appgeodata** [comment] 2016-04-15 21:45
I am in a MapBox workshop and using Google on Windows and getting totally hosed on getting started.  Dane Springmeier giving me direction on how to report this problem:
Version 50.0.2661.75 m - Windows 7 Service Pack 1.

**Comment by mourner** [comment] 2016-05-17 16:30
Should be fixed by #1606 which was merged to master, to be included in the next release.

**Closed by mourner** 2016-05-17 16:30 UTC
Labels: bug
