### ISSUE TITLE
Related to #1488

### ISSUE THREAD

**Issue by Iam-jegan** [mapbox/mapbox-gl-js#2288] opened 2016-03-18 05:38 UTC
Please go throught the Issue no:1488. I haev a question related to that,

as Wouter125 stated I'm too facing the same problem as vertical panning when maxBounds are set. Adn best way to best fit the map completely inside the container?

**Comment by mourner** [comment] 2016-03-18 13:26
This is a place to report issues, not for support. Closing as duplicate of #1488.

**Closed by mourner** 2016-03-18 13:26 UTC

**Comment by lucaswoj** [comment] 2016-03-18 16:27
> Adn best way to best fit the map completely inside the container?

Feel free to ask support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/mapbox-gl-js)!
