### ISSUE TITLE
Rats! chrome hit a snag issue?

### ISSUE THREAD

**Issue by KfirShainholtz** [mapbox/mapbox-gl-js#4309] opened 2017-02-21 08:54 UTC
Hey,
in the past half year, chrome has been not-so-fond with web-gl.

I've created a manual to fix the web-gl isn't supported, for our clients, (many
of them need to go to chrome://flags and manually un-blacklist themselves from the web-gl
not-supported GPU's), and created a leaflet fallback to those who just-can't display the mapbox-gl map.

But, for some reason, lately i've encountered Rats! chrome hit a snag, (using V29 right now),
which didn't happen before.

any suggestions why could this be happening? (I know about web-gl and
their web-gl components overhead)

it doesn't even happen when the map is displayed (but it is the only web-gl product we're using)

thanks!

**Comment by mourner** [comment] 2017-02-21 10:23
Can you reproduce the crash consistently? If so, it would be wonderful if you could bisect it to a specific commit, or at least the exact version it started happening with.

**Comment by mourner** [comment] 2017-02-21 10:24
Also, please make sure the crash is still present in 0.32.1 — we had some possibly related fixes between 0.29 and the latest.

**Comment by KfirShainholtz** [comment] 2017-02-21 10:29
I will try upgrading the version first, if the crashes will continue occuring, I'll let you know.

**Comment by jfirebaugh** [comment] 2017-02-21 17:04
When Chrome blacklists a GPU, it's usually for a good reason -- e.g., the drivers for that GPU cause crashes. If you're manually un-blacklisting them, and then you see application instability, that could well be the cause.

**Comment by jfirebaugh** [comment] 2017-02-27 18:00
Closing; likely not something we can fix.

**Closed by jfirebaugh** 2017-02-27 18:00 UTC
Labels: needs clarification
