### ISSUE TITLE
Animating heatmaps puts a heavy load on the CPU

### ISSUE THREAD

**Issue by pyttroll** [mapbox/mapbox-gl-js#7213] opened 2018-08-28 14:42 UTC
**mapbox-gl-js version**: 0.48.0

**browser**: Chrome 68.0.3440.106

### Steps to Trigger Behavior

 1. Setup mapbox with a datasource and a heatmap layer bound to it.
 2. Repeatedly call setData() on the datasource to animate the heatmap.

### Link to Demonstration

https://jsfiddle.net/pyttroll/xpvt214o/694598/

### Expected Behavior
Low CPU usage and faster frame rate.

### Actual Behavior
CPU usage goes through the roof and the frame rate drops.

Considering most of the work should happen on the GPU, I would expect a lower CPU usage.
I previously used webgl-heatmap (https://github.com/pyalot/webgl-heatmap) and had very good result with the same data.

**Comment by mourner** [comment] 2018-08-28 15:07
This is not specific to heatmaps — the CPU usage happens because on each update, GL JS needs to send the data to the worker, slice it into tiles, prepare the new buffers for GL, send them back and update them on the main thread. We're looking into improving this use case for animations, but I'm going to close this one as a duplicate of #2275.

**Closed by mourner** 2018-08-28 15:07 UTC
Labels: performance :zap:

**Comment by mourner** [comment] 2018-08-28 15:08
You might get better performance by using the new `setFeatureState` API instead of `setData` — I wonder how that will look.
