### ISSUE TITLE
mapbox GL Initialize the map too slowly

### ISSUE THREAD

**Issue by JunYanchan** [mapbox/mapbox-gl-js#4857] opened 2017-06-21 04:16 UTC
I used the official  mapbox://styles/mapbox/light-v9  to set the map style and found that initialization was too slow to load the map. **I found that I had been requesting multiple fonts API, which led to slowing down**, and how to solve it. Thank you for your help. Thank you

**Comment by jfirebaugh** [comment] 2017-06-21 16:22
Duplicate of #4858.

**Closed by jfirebaugh** 2017-06-21 16:22 UTC
