### ISSUE TITLE
Map clusters missing on Chrome for Android

### ISSUE THREAD

**Issue by robinpalicka** [mapbox/mapbox-gl-js#4985] opened 2017-07-15 17:29 UTC
**mapbox-gl-js version**: 0.38

### Steps to Trigger Behavior

 1. Use Android phone with Chrome
 2. Open example URL https://www.mapbox.com/mapbox-gl-js/example/cluster/ 

### Expected Behavior
Same look like in other desktop browsers.

### Actual Behavior
Clusters circles missing. Only numbers are visible. Look carefully on image, because numbers are black on black background (screenshot1). In version 0.37 (screenshot2) is everything alright, but since 0.38 (screenshot3) circles are missing.

![screenshot1_2017-07-15-18-23-01_com android chrome](https://user-images.githubusercontent.com/20530138/28241365-76a68cfc-6993-11e7-8c96-3fcc8f38bed3.png)

![screenshot2_2017-07-15-18-46-03_com android chrome1](https://user-images.githubusercontent.com/20530138/28241367-80278c86-6993-11e7-86c6-50d3d9f4bf78.png)

![screenshot3_2017-07-15-18-46-03_com android chrome2](https://user-images.githubusercontent.com/20530138/28241368-84273714-6993-11e7-9c88-6da97c2431c8.png)

**Comment by jdeboer-geoplan** [comment] 2017-07-17 15:15
what is your device pixel ratio?  I suspect you might be seeing the same thing I am with non standard device pixel ratios

**Comment by jfirebaugh** [comment] 2017-07-17 16:10
Good call @jdeboer-geoplan, I'm pretty sure this is a duplicate of #4928.

**Closed by jfirebaugh** 2017-07-17 16:10 UTC
