### ISSUE TITLE
Zoom levels 1 less in GL than raster?

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-gl-js#685] opened 2014-08-11 15:38 UTC
It appears that the zoom levels reported in GL are 1 less than the same data source rendered as raster tiles. See the attached images of the same area as GL and in the Mapbox project view:

![gl zoom 12](https://cloud.githubusercontent.com/assets/912721/3878222/70bd0882-216d-11e4-8419-3d9abc3d5a07.png)
![raster zoom 13](https://cloud.githubusercontent.com/assets/912721/3878221/70b7b65c-216d-11e4-98d8-c574a75c8ae6.png)

**Comment by rouen-sk** [comment] 2016-06-23 12:44
Just found about this issue and I am really surprised. This is not a "minor documentation issue" - you practically decided that Mapbox GL **is not** slippy map, and **it is not compatible** with other standardized slippy map things - for example any server side code using standard zoom-to-scale-denominator (13 = 1:100000). You cant use one common datasource-level filtering based on zoom for both raster and vector tiles, you need different styling rules, etc. What a huge standard-breaker... This should be like first thing mentioned in the documentation - in big bold font.

**Comment by timiyay** [comment] 2016-06-23 13:43
Hmmmm, is there any chance this explains why I get incorrect results from `mapbox/geo-viewport`? https://github.com/mapbox/geo-viewport/issues/3

I use Mapbox's Static Image API, and I need to compute the bounding box of those images. Mapbox Support advised me that `geo-viewport` was written for this very purpose.

If I request a static image at MapboxGL zoom 17, and then ask `geo-viewport` to compute this bounding box, it gives the bbox for zoom 16 instead. I have to +1 to get the right answer.

I'm trying to learn enough about the underlying `mapbox/node-spherical-mercator` library to make a fix, but it sounds like it's mostly a misunderstanding on my part.

I'm honestly not fussed about the zoom matching with raster-based zooms. I just need a way to compute the bbox of a Mapbox Static Map API image.

**Comment by lucaswoj** [comment] 2016-07-28 21:40
I am closing this issue because the GL team feels 👍  about this decision and does not plan to revisit.

**Closed by lucaswoj** 2016-07-28 21:40 UTC
Labels: documentation, v1

**Comment by timiyay** [comment] 2016-07-31 23:41
For posterity, the answer to my comment was:

Yes, the 512x512px tile size was the cause of my issue in https://github.com/mapbox/geo-viewport/issues/3

**Comment by nrenner** [comment] 2016-10-15 10:35
Documenting this in [Mapbox GL JS fundamentals](https://www.mapbox.com/help/mapbox-gl-js-fundamentals/) would be helpful.
