### ISSUE TITLE
Rendering Error ( mapbox-gl-draw in android webview)

### ISSUE THREAD

**Issue by Changgf** [mapbox/mapbox-gl-js#13305] opened 2024-10-21 03:53 UTC
Steps:
1、load mapbox instance in H5
2、embed H5 page in android webview
3、Slide map dot often happen rendering Error ，lead to android activity finish

Logs:
10:24:35.986 4629-4699 MiuiPerfServiceClient W interceptAndQueuing:25355|142|44|912111753817|Slow handle animation|12
10:24:36.290 1072-1289 ANDR-PERF-OPTSHANDLER E Perflock resource /sys/class/devfreq/soc:qcom,cpu-llcc-ddr-bw/min_freq not supported
10:24:36.290 1072-1289 ANDR-PERF-RESOURCEQS E Failed to apply optimization [12, 4]
10:24:36.552 1072-1289 ANDR-PERF-OPTSHANDLER E Perflock resource /sys/class/devfreq/soc:qcom,cpu-llcc-ddr-bw/min_freq not supported
10:24:36.552 1072-1289 ANDR-PERF-RESOURCEQS E Failed to apply optimization [12, 4]
10:24:36.558 25355-25557 Adreno-GSL W <gsl_linux_syncobj_merge_multiple:795>: sync_merge(MergeFD 430 & 377 Count 48080, 430, 377) failed
10:24:36.558 25355-25557 chromium E [ERROR:gl_fence_egl.cc(108)] Failed to wait for EGLSync. error:EGL_BAD_PARAMETER
10:24:36.589 28057-28057 linker64 W type=1400 audit(0.0:3568): avc: denied { search } for name="tests" dev="dm-39" ino=16020 scontext=u:r:untrusted_app:s0:c172,c258,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=yy
10:24:36.589 28057-28057 linker64 W type=1400 audit(0.0:3569): avc: denied { search } for name="tests" dev="dm-39" ino=16020 scontext=u:r:untrusted_app:s0:c172,c258,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=yy
10:24:36.589 28057-28057 linker64 W type=1400 audit(0.0:3570): avc: denied { search } for name="tests" dev="dm-39" ino=16020 scontext=u:r:untrusted_app:s0:c172,c258,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=yy
10:24:36.589 28057-28057 linker64 W type=1400 audit(0.0:3571): avc: denied { search } for name="tests" dev="dm-39" ino=16020 scontext=u:r:untrusted_app:s0:c172,c258,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=yy
10:24:36.598 28057-28057 libc W Access denied finding property "persist.vendor.track.malloc.enable"
10:24:36.690 28057-28057 chromium E [1021/102436.689772:ERROR:process_memory_linux.cc(49)] pread64: I/O error (5)
10:24:36.690 28057-28057 chromium E [1021/102436.690584:ERROR:process_memory_linux.cc(49)] pread64: I/O error (5)
10:24:36.690 28057-28057 chromium E [1021/102436.690745:ERROR:process_memory_linux.cc(49)] pread64: I/O error (5)
10:24:36.701 28057-28057 chromium E [1021/102436.701324:ERROR:elf_image_reader.cc(407)] Incorrect ELF magic number
10:24:36.701 28057-28057 chromium E [1021/102436.701368:ERROR:process_reader_linux.cc(540)] no module mappings 0x7a27d23000
10:24:36.740 28057-28057 chromium E [1021/102436.740464:ERROR:elf_dynamic_array_reader.h(64)] tag not found
10:24:36.740 28057-28057 chromium E [1021/102436.740650:ERROR:elf_dynamic_array_reader.h(64)] tag not found
10:24:36.740 28057-28057 chromium E [1021/102436.740836:ERROR:elf_dynamic_array_reader.h(64)] tag not found
10:24:36.745 28057-28057 chromium E [1021/102436.745058:ERROR:elf_dynamic_array_reader.h(64)] tag not found
10:24:36.816 28057-28057 chromium E [1021/102436.816577:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: Permission denied (13)

10:24:37.451 1072-1289 ANDR-PERF-OPTSHANDLER E Perflock resource /sys/class/devfreq/soc:qcom,cpu-llcc-ddr-bw/min_freq not supported
10:24:37.451 1072-1289 ANDR-PERF-RESOURCEQS E Failed to apply optimization [12, 4]
10:24:37.483 1965-2353 WifiScoreReportInjector E current network is in roaming environment
10:24:37.499 28062-28062 MIUINDBG E miui_native_debug_process_O
10:24:37.499 28062-28062 MIUINDBG E unable to connect to mqsas native socket
10:24:37.501 707-714 TombstoneMonitor W Detected deletd file: tombstone_17
10:24:37.501 1965-2125 RescuePartyPlus W This device support and enable RescuePartyPlus! (Via cloud control)
10:24:37.501 773-773 tombstoned E Tombstone written to: tombstone_17

**Comment by stepankuzmin** [comment] 2024-10-21 09:40
Hi @Changgf, does this only happen with GL Draw? Closing this as a duplicate of https://github.com/mapbox/mapbox-gl-draw/issues/1303

**Closed by stepankuzmin** 2024-10-21 09:40 UTC
Labels: environment-specific :desktop_computer:
