### ISSUE TITLE
RFC: Style specification, mark layer

### ISSUE THREAD

**Issue by tmpsantos** [mapbox/mapbox-gl-js#4223] opened 2017-02-07 12:51 UTC
I would like to suggest the addition of a new layer type to the style specification, that doesn't really map to any visual element, but is merely a `mark` to be used as reference for adding new layers at runtime before/after the mark.

For instance all Mapbox styles could have a properly documented `mark` layer where the labels start, so when adding a route line you would always add it before/after (doesn't really matter because `mark` doesn't get rendered) this particular mark.

```
{
    "id": "road-mortorway",
    "type": "line"
},
{
    "id": "road-labels-start",
    "type": "mark"
},
{
    "id": "road-label-small",
    "type": "symbol"
},
{
    "id": "road-label",
    "type": "symbol"
},
...
```

/cc @kkaefer, which originally suggested something on these lines.
/cc @brunoabinader

**Comment by kkaefer** [comment] 2017-02-07 13:04
duplicate of https://github.com/mapbox/mapbox-gl-js/issues/4173

**Closed by kkaefer** 2017-02-07 13:04 UTC
Labels: cross-platform, needs discussion
