### ISSUE TITLE
'moveend' fires during multi-touch gesture input

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#3435] opened 2016-10-21 15:35 UTC
### Issue

The [moveend](https://www.mapbox.com/mapbox-gl-js/api/#Map.event:moveend) event behaves differently during single-touch and multi-touch input.

During single touch, the `moveend` event is fired when the gesture finishes (finger is no longer touching the screen). During multi-touch, eg. two fingers touching the screen at the same time, `moveend` is fired on every single animation frame for the duration of the gesture.

**mapbox-gl-js version**: Master

### Steps to Trigger Behavior

 1. Bind an event listener to 'moveend' 
 2. Two finger rotate / pinch on a mobile device
 3. The event listener will now fire during the pinch / rotate gesture

### Expected Behavior

'moveend' fires when user gesture is finished and any optional inertia have stopped playing during both multi-touch and single-touch gestures.

### Actual Behavior

'moveend' fires constantly during multi-touch user gestures and at the end of single-touch gestures.

Tested in iOS10 Safari and Android Chrome.

Kinda related to #1104

**Comment by lucaswoj** [comment] 2016-10-24 18:12
This is effectively a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/3357. "move" has to do with `Camera` state changes, not necessarily interaction handler state changes.

**Closed by lucaswoj** 2016-10-24 18:12 UTC
Labels: bug, starter task

**Comment by lucaswoj** [comment] 2016-10-24 18:15
Added a bullet point to #3357 to explicitly capture the essence of this ticket

 >  prevent interaction handlers with inertia from firing multiple moveend events within an individual interaction
