### ISSUE TITLE
[.Offscreen-For-WebGL-0x7fae76876600]RENDER WARNING: there is no texture bound to the unit 0

### ISSUE THREAD

**Issue by evejweinberg** [mapbox/mapbox-gl-js#3312] opened 2016-10-06 22:32 UTC
I'm loading an image layer and a video layer and they both generate the warning:
[.Offscreen-For-WebGL-0x7fae76876600]RENDER WARNING: there is no texture bound to the unit 0

I've seen this posted related to Three.js and someone said it was a Chrome bug, but that it was fixed. Any ideas why this is still happening? It nearly crashes my browser.

Thanks,
Eve

**Comment by jfirebaugh** [comment] 2016-11-17 23:29
This was fixed in #3522.

**Comment by jaapster** [comment] 2017-04-12 08:16
I still get this warning in v0.35.0

**Comment by denistsoi** [comment] 2017-04-21 10:23
Also seeing this on v0.36.0

**Comment by lbud** [comment] 2017-04-21 18:11
Thanks for the reports! If someone is able to provide a minimal [JSFiddle](https://jsfiddle.net/) that reproduces this issue, that would be helpful.

**Comment by jaapster** [comment] 2017-04-23 16:15
I'll give it a shot

**Comment by denistsoi** [comment] 2017-05-08 04:54
one thing i need to mention - not sure if @jaapster has this as well - I'm currently embedding `mapbox-gl-js` inside `ng 1.4.8` using `material-design` - it may be that: 

- warning is being thrown by initiating mapbox inside a directive
- or initiating mapbox within a div with column flexbox may be throwing this error

Haven't been able to reproduce the error within a blank jsfiddle - will continue to attempt

**Comment by jfirebaugh** [comment] 2017-07-25 19:36
If this is reproducible in 0.39.1 or later, please open a fresh issue with a JSFiddle that demonstrates the issue.

**Closed by jfirebaugh** 2017-07-25 19:36 UTC
Labels: bug

**Comment by denistsoi** [comment] 2017-07-26 02:41
Thanks for closing this @jfirebaugh - I don't think I'm able to reproduce since the original post.

**Comment by drewbo** [comment] 2018-04-02 14:12
@jfirebaugh seeing this in `0.44.1`. Reproduction on a WMS layer here: https://jsfiddle.net/m77nkgme/1/
