### ISSUE TITLE
New installs of 0.16 are broken

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#2433] opened 2016-04-13 03:49 UTC
The 8.5.0 release of the mapbox-gl-style-spec breaks mapbox-gl-js. The style validation logic now requires the style object to be passed in. I'm unsure if this is a breaking change in the style spec, or a bug that mapbox-gl-js never passed in the style object.

<img width="517" alt="screen shot 2016-04-12 at 8 44 44 pm" src="https://cloud.githubusercontent.com/assets/302992/14482227/6e724eda-00ef-11e6-8cc9-305d11ffe30c.png">

To reproduce:
- `git checkout v0.16.0`
- `rm -rf node_modules`
- `npm install`
- `npm start`
- `open http://localhost:9966/?access_token=[access_token]`

cc @lucaswoj

**Comment by lucaswoj** [comment] 2016-04-13 05:20
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2407.

This'll be fixed when we publish v0.17.0 (tomorrow?)

I regretfully did not consider the implications of publishing a "stricter" style spec, once again. Funny how semver is such a bad fit for increasingly good validators.

**Comment by lucaswoj** [comment] 2016-04-13 05:20
This is also a signal that we should reconsider using shrinkwrap

**Closed by lucaswoj** 2016-04-13 05:20 UTC

**Comment by scothis** [comment] 2016-04-13 05:27
We shrinkwrap studio releases, unfortunately we find a lot of issues while updating the shrinkwrap (like this one), which makes creating a release more painful.

Greenkeeper could be interesting to explore. https://greenkeeper.io/
