### ISSUE TITLE
Uncaught TypeError: Cannot read property 'x' of null

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#3892] opened 2017-01-04 20:37 UTC
When in Chrome I use (F12) 'Mobile' mode and refresh the browser. Every time I click the map I get following error:

```
mapbox-gl.js?31ef:395 Uncaught TypeError: Cannot read property 'x' of null
    at Point.equals (eval at <anonymous> (0.77b24fd….js:263), <anonymous>:395:661)
    at HTMLDivElement.s (eval at <anonymous> (0.77b24fd….js:263), <anonymous>:179:1098)
    at FastClick.sendClick (eval at <anonymous> (app.js:2164), <anonymous>:308:17)
    at FastClick.onTouchEnd (eval at <anonymous> (app.js:2164), <anonymous>:606:9)
    at HTMLBodyElement.eval (eval at <anonymous> (app.js:2164), <anonymous>:111:38)
equals @ mapbox-gl.js?31ef:395
s @ mapbox-gl.js?31ef:179
FastClick.sendClick @ fastclick.js?f1d9:308
FastClick.onTouchEnd @ fastclick.js?f1d9:606
(anonymous) @ fastclick.js?f1d9:111
```

which relates to the `return this.x === t.x && this.y === t.y` part of following mapbox-gl-js code:
  ```
          module.exports = Point,
            Point.prototype = {
                clone: function() {
                    return new Point(this.x,this.y)
                },
                add: function(t) {
                    return this.clone()._add(t)
                },
                sub: function(t) {
                    return this.clone()._sub(t)
                },
                mult: function(t) {
                    return this.clone()._mult(t)
                },
                div: function(t) {
                    return this.clone()._div(t)
                },
                rotate: function(t) {
                    return this.clone()._rotate(t)
                },
                matMult: function(t) {
                    return this.clone()._matMult(t)
                },
                unit: function() {
                    return this.clone()._unit()
                },
                perp: function() {
                    return this.clone()._perp()
                },
                round: function() {
                    return this.clone()._round()
                },
                mag: function() {
                    return Math.sqrt(this.x * this.x + this.y * this.y)
                },
                equals: function(t) {
                    return this.x === t.x && this.y === t.y
                },
```

In normal browser mode I do not get errors when clicking the map.
Any idea what is going on?

**Comment by mourner** [comment] 2017-01-04 21:54
I see that the trace points to the FastClick.js library in your app, could it be the culprit? Can you reproduce this issue in a minimal test case without fastclick?

**Comment by mollymerp** [comment] 2017-01-04 22:36
Also see https://github.com/mapbox/mapbox-gl-js/issues/2035 for previous context on FastClick.

**Comment by mourner** [comment] 2017-01-05 11:12
Let's refer to #2035 for possible workarounds, and close this issue here since it's not something that should be fixed on the GL JS side.

**Closed by mourner** 2017-01-05 11:12 UTC
Labels: needs clarification

**Comment by emailcln83** [comment] 2017-05-23 13:56
Uncaught TypeError: Cannot read property 'refresh' of null
    at eval (eval at <anonymous> (jquery.min.js:3), <anonymous>:12:15)
    at dispatch (jquery.min.js:3)
    at v.handle (jquery.min.js:3)
