### ISSUE TITLE
Same circle-radius clusters overlap and count is not displayed

### ISSUE THREAD

**Issue by leahwchang** [mapbox/mapbox-gl-js#7264] opened 2018-09-11 21:32 UTC
**mapbox-gl-js version**:
v0.47.0
### Question
Hello! We set up clusters for our maps with thousands + points following the example: https://www.mapbox.com/mapbox-gl-js/example/cluster/ 

We want all the clusters in the same size and we ran into a problem where the clusters are overlapping each other and thus the count within clusters are not always displayed, or the count displays but that cluster is not shown (partially hidden/overlapped by another cluster). I've tried different combinations of clusterRadius, (various steps of) circle-radius/circle-color. 

[screenshot of problem](https://imgur.com/a/MD9Yr1m)

Our code:
```
var map = makeMap({
  container: 'map',
  locationSearch: true,
  zoom: 10
});

map.addSource("scheduled", {
  type: "geojson",
  data: geojsonScheduled,
  cluster: true,
  clusterMaxZoom: 24, // Max zoom to cluster points on
  clusterRadius: 8 // Radius of each cluster when clustering points (defaults to 50)
});

map.addLayer({
  id: "scheduled-clusters",
  type: "circle",
  source: "scheduled",
  filter: ["has", "point_count"],
  paint: {
    "circle-color": [
      "step",
      ["get", "point_count"],
      "#f1733b",
      100,
      "#f1733b"
    ],
    "circle-radius": [
      "step",
      ["get", "point_count"],
      10,
      100,
      10
    ],
    "circle-stroke-width": 0.5,
    "circle-stroke-color": "#ffffff"
  }
});

map.addLayer({
  id: "scheduled-cluster-count",
  type: "symbol",
  source: "scheduled",
  filter: ["has", "point_count"],
  layout: {
    "text-field": "{point_count_abbreviated}",
    "text-font": ["DIN Offc Pro Medium", "Arial Unicode MS Bold"],
    "text-size": 9
  }
});

map.addLayer({
  id: "scheduled-unclustered-point",
  type: "circle",
  source: "scheduled",
  filter: ["!has", "point_count"],
  paint: {
    "circle-color": "#f1733b",
    "circle-radius": 4.5,
    "circle-stroke-width": 0.5,
    "circle-stroke-color": "#ffffff"
  }
});
```

Any help or pointers is appreciated. Thank you!

**Comment by jfirebaugh** [comment] 2018-09-12 00:07
Duplicate of #4064.

**Closed by jfirebaugh** 2018-09-12 00:07 UTC
