### ISSUE TITLE
Circles duplicated on zoom between zoom level cutoffs

### ISSUE THREAD

**Issue by pjsier** [mapbox/mapbox-gl-js#5829] opened 2017-12-08 15:02 UTC
**mapbox-gl-js version**: 0.42.1 (but also seen in 0.42.2)

### Steps to Trigger Behavior

 1. Create a circle layer with an opacity less than 1, or that changes size on zoom
 2. Zoom into the layer, and around breakpoints between zoom levels the circles are duplicated

### Expected Behavior

Circles should change gradually if there is a zoom function or expression applied

### Actual Behavior

Circles look like they're being duplicated between layers, but the duplicate is removed after zooming a bit further. Here are two examples:

From a [data-driven styling demo](https://www.mapbox.com/help/demos/heatmap-gljs-dds/demo-3.html) on 0.42.1 where you can see the opacity change where it looks like the circles are duplicated:
![circle-zoom](https://user-images.githubusercontent.com/8291663/33771091-635bce58-dbf5-11e7-958b-fef415a340d4.gif)

An example where the duplication is more clear with size and opacity change is more clear, on 0.42.2:
![duplicate-circles](https://user-images.githubusercontent.com/8291663/33771110-757ba978-dbf5-11e7-8a25-5ad324030a26.gif)

Whenever this appears, this error is logged in the console:
```
columnNumber: 765
fileName: "https://api.tiles.mapbox.com/mapbox-gl-js/v0.42.1/mapbox-gl.js"
lineNumber: 490
message: "Error"
stack: "[243]</Actor.prototype.receive@https://api.tiles.mapbox.com/mapbox-gl-js/v0.42.1/mapbox-gl.js:490:765\n"
```

**Comment by jfirebaugh** [comment] 2017-12-08 17:32
Duplicate of #4691. In this case, it looks like the response code is 404 instead of 200, but the result is the same.

**Closed by jfirebaugh** 2017-12-08 17:32 UTC

**Comment by pjsier** [comment] 2017-12-08 19:26
@jfirebaugh thanks for the quick reply, and sorry for missing that. In that issue a 200 code with empty content raises an exception, but based on #1800 shouldn't a 404 be handled the same way as a 204?

**Comment by jfirebaugh** [comment] 2017-12-08 21:49
A 200 with empty content and a 404 both trigger loading parent tiles, which is what causes overdrawing.

**Comment by pjsier** [comment] 2017-12-08 22:02
Great, thanks for the clarification!

**Comment by jfirebaugh** [comment] 2018-05-31 17:57
→ #6768
