### ISSUE TITLE
Custom layer(Three JS) objects getting disappeared with terrain basemap

### ISSUE THREAD

**Issue by gireeshbhogireddy** [mapbox/mapbox-gl-js#10484] opened 2021-03-18 09:03 UTC
How to make three js objects visible along with terrain basemap of mapbox GL.
Objects are working fine when there is no terrain

**Comment by astojilj** [comment] 2021-03-18 09:51
This is caused by missing getElevation API: https://github.com/mapbox/mapbox-gl-js/issues/10318. Code modification required to get the model elevated is there, too. Closing it in favor of #10318.

**Closed by astojilj** 2021-03-18 09:51 UTC

**Comment by Infl1ght** [comment] 2021-04-06 21:37
> This is caused by missing getElevation API: #10318. Code modification required to get the model elevated is there, too. Closing it in favor of #10318.

I'm not so sure about that.
I have a custom Deck.gl layer with 3d objects with elevations so they should be at their positions when I move the camera. But they behave very strangely: when I zoom and rotate the camera around the anchor point, it's ok. But when I move the camera (through dragging), my 3d objects are starting to 'jump'.
It happens only with terrain, its okay with 2d map.
![Peek 2021-04-07 00-34](https://user-images.githubusercontent.com/19838931/113781289-22efc100-9739-11eb-9b7c-1773340b4460.gif)
