### ISSUE TITLE
Point geometry gets shifted in conversion from dataset to tileset

### ISSUE THREAD

**Issue by resekartan** [mapbox/mapbox-gl-js#8572] opened 2019-07-29 17:30 UTC
**mapbox-gl-js version**:

### Question

Hi!

Why do close markers overlap each other? I attach an image file to show you. Is there a way to fix this?

Thanks
![sssssled](https://user-images.githubusercontent.com/53444724/62068851-427dd900-b237-11e9-80db-76566ba77088.png)

**Comment by mourner** [comment] 2019-07-29 19:24
Can you please share a live test case we could see this on (e.g. on JSFiddle)? Screenshots are not enough to understand what the issue is.

**Comment by resekartan** [comment] 2019-07-30 02:18
I don't know how to explain in a better way for you to understand... But I've create a DATASET with 16.000 markers. So fine so good...They work just fine as picture 1 show... Then I export to tileset. And when I go to "Styles" OR my shared map and zoom in to the example above, the three markers overlap each other. (picture 2)

Here you have a test map: 

https://api.mapbox.com/styles/v1/resekartan/cjuu8tsb10dkc1focyshet50b.html?fresh=true&title=true&access_token=pk.eyJ1IjoicmVzZWthcnRhbiIsImEiOiJjanVoYW5jdWkwNGF1M3ptb3hoYnJkbTkzIn0.Yt_FQx_n7KKwitn6cH487w#15.5/13.727474/100.53333

As you can see on the test map there are 3 markers overlapping each other, BUT they don't overlap under "datasets". Dataset id: cjvgbc1hb04x72ro4a0ts5drf.

**Comment by peterqliu** [comment] 2019-08-13 19:11
was able to reproduce this comparing user's tileset and dataset. Spatial data does get downsampled very slightly in the tiling process, which could cause snapping behavior like this, but not to this extent

**Comment by resekartan** [comment] 2019-08-13 23:02
> was able to reproduce this comparing user's tileset and dataset. Spatial data does get downsampled very slightly in the tiling process, which could cause snapping behavior like this, but not to this extent
> 
> tagging in @mapbox/studio

Thank you. Note that I have updated the dataset and the tileset a few days ago, and I removed some of the markers with the error/bug. This won't fix the problem/bug, but at least they don't overlapp anymore. I bet there's more markers on the map that have the same issue/bug.

**Comment by resekartan** [comment] 2019-09-09 12:12
Have anyone looked into this problem? Another thing I've notice is the exact position of some markers. Look at this image?

<img width="1112" alt="png" src="https://user-images.githubusercontent.com/53444724/64529669-af42c380-d30b-11e9-9191-934adfe7b614.png">

**Comment by peterqliu** [comment] 2019-09-09 16:00
cc/ @mapsam

**Comment by asheemmamoowala** [comment] 2020-04-04 00:01
Closing here as this is not actionable in this project. The data in the tileset is being rendered correctly on the map, and conversion of the data set to tileset is not within the scope of discussion here. 

We recommend you [contact support](https://www.mapbox.com/contact/) if this is still an issue for you. Thank you!

**Closed by asheemmamoowala** 2020-04-04 00:01 UTC
Labels: bug :beetle:, needs information :pray:
