### ISSUE TITLE
Mapbox Standard: Hide buildings between the camera and a location marker

### ISSUE THREAD

**Issue by BjoernRave** [mapbox/mapbox-gl-js#13040] opened 2024-01-13 21:29 UTC
Maybe it's already possible and I just couldnt find it.

I would like to use this for a navigation app, but currently when having the view follow my marker with a bearing = 60, there are sometimes buildings blocking the view of the marker. 

I would like to hide the 3D extrusions in my view, or maybe in a given radius so that I can always see where I am.

Creating a filtermask of some sort which can be movd around the map would maybe be a good idea

**Comment by stepankuzmin** [comment] 2024-01-16 15:16
Hi @BjoernRave,

Unfortunately, turning off 3D Buildings and trees in the Standard Style is not currently supported. Closing this issue as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/13009 so we can track it in one place.

**Closed by stepankuzmin** 2024-01-16 15:16 UTC
Labels: feature :green_apple:

**Comment by joshasbuilt** [comment] 2024-02-19 21:14
Mapbox Standard looks amazing but is actually unusable at higher zooms (> 16) because the buildings and trees block the view? In the CBDs it's almost useless, the slightest angle causes the view of the street to be blocked. We can't change the opacity of tall buildings?
