### ISSUE TITLE
Changing fill layer opacity affects whether labels are rendered above or below it

### ISSUE THREAD

**Issue by bfrengley** [mapbox/mapbox-gl-js#7107] opened 2018-08-10 04:23 UTC
**mapbox-gl-js version**: 0.47.0

**browser**: Chrome 68.0.3440.106 64-bit (Windows 10)

### Steps to Trigger Behavior

 1. Add a fill layer with a GeoJSON source as the topmost layer, with `"fill-opacity": 0.999`
 2. Change the fill layer opacity to 1

### Link to Demonstration

https://jsbin.com/xotuboximu/edit?html,output

### Expected Behavior

Labels are below the fill layer, as the fill layer is the topmost layer in the style.

### Actual Behavior

Labels are below the fill layer when it has opacity 0.999:
![image](https://user-images.githubusercontent.com/37278140/43938679-37ee1b1a-9cb9-11e8-97e5-e22ae48ab25e.png)

but they are above the fill layer when it has opacity 1:
![image](https://user-images.githubusercontent.com/37278140/43938697-4a3a36dc-9cb9-11e8-82fd-b3c994b18a8a.png)

**Comment by andrewharvey** [comment] 2018-08-10 05:54
Hi @bfrengley thanks for reporting this issue. It's a duplicate of #2074 so I'll close it here to keep the discussion together on the existing issue.

**Closed by andrewharvey** 2018-08-10 05:54 UTC
