### ISSUE TITLE
Map blink when zooming

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#5490] opened 2017-10-20 09:02 UTC
When I zoom the map, map became blinking.

**mapbox-gl-js version**:

Mapbox Studio version

MacBook Air 2017
macOS High Sierra
Chrome dev 63

### Steps to Trigger Behavior

 1. login Mapbox Studio
 2. Create a dark map
 3. Zooming

### Expected Behavior

Zooming would be smooth

### Actual Behavior
![qq20171020-165813-hd](https://user-images.githubusercontent.com/1522494/31813226-31900da2-b5b8-11e7-803d-e828a4660630.gif)

**Comment by anandthakker** [comment] 2017-10-20 12:09
Thanks @jingsam!  Is this happening on a specific page?  If so, could you share a link to it, or better yet, to a minimal example reproducing the issue?

**Comment by jingsam** [comment] 2017-10-20 13:57
This happens in Mapbox Studio, any newly created maps have this issue. And I test it with a standalone index.html, everything was OK.

**Comment by anandthakker** [comment] 2017-10-20 14:01
Ah, interesting -- thank you @jingsam!

**Comment by karlguillotte** [comment] 2017-10-21 19:50
Same is happening on our map. Started with the latest Chrome upgrade (from 61 to 62).

**Comment by dpieri** [comment] 2017-10-23 22:52
I'm seeing a similar thing on Chrome. We're using 0.40.1, but even on the share links from Studio I see the problem. Try zooming in and out on [this map](https://api.mapbox.com/styles/v1/arielseidman/cj94rvzzknwhk2qp9e3ols7bz.html?fresh=true&title=true&access_token=pk.eyJ1IjoiYXJpZWxzZWlkbWFuIiwiYSI6ImU5OWQ3M2Y1ZTVhNTI3YzMzOWNlNWM0ODY3Njg4ZDhiIn0.CYEvEz1c7qHDkFXCJhCwnA#12.5/33.8878/-118.2598), which is just the default Dark style.

I can't reproduce it in Safari, just Chrome. It's easier to trigger if you are using a trackpad and flick it so that inertial scrolling kicks in. In our app I'm also seeing the same symptoms in a `flyTo` animation.

I see flickering, but I also see the map zooming in and out like crazy as the inertial scrolling is loosing its inertia. Here's a [screen capture](https://www.dropbox.com/s/bs26o4u9ir4sxbu/Jittery%20Zoom.mov?dl=0).

**Comment by jfirebaugh** [comment] 2017-10-24 18:07
I believe this is a duplicate of #5333. Is this reproducible in Chrome 62?

**Comment by dpieri** [comment] 2017-10-24 18:57
The behavior I was seeing, which is better described in #5333 went away when I updated to Chrome 62. I'm still seeing some flashes of white like in @jingsam's GIF so I would wait to hear from him before closing this.

**Comment by dpieri** [comment] 2017-10-24 19:19
![ezgif-5-3c786712a1](https://user-images.githubusercontent.com/539310/31963241-e4b4abd2-b8b4-11e7-8326-d8fca41b56ec.gif)

While the crazy zoom thrashing is gone, the flickering seems to be worse on Chrome 62. On a style [share page](https://api.mapbox.com/styles/v1/arielseidman/cj5e32es310x02rnvcxyuofsz.html?fresh=true&title=true&access_token=pk.eyJ1IjoiYXJpZWxzZWlkbWFuIiwiYSI6ImU5OWQ3M2Y1ZTVhNTI3YzMzOWNlNWM0ODY3Njg4ZDhiIn0.CYEvEz1c7qHDkFXCJhCwnA#10.57/36.6928/-121.676), it's OK, but in the context of our [application](https://hivemapper.com/36.733867648456865/-121.65453050830484/zoom9.6/0/0) it's very severe. We haven't deployed any code today, so the only change has been upgrading from 61 to 62.

It's also possible to have the map stuck with a bunch of layers not rendering. As soon as you zoom in or out it resolves itself:

<img width="659" alt="screen shot 2017-10-24 at 12 18 21 pm" src="https://user-images.githubusercontent.com/539310/31963463-8df47074-b8b5-11e7-91ff-a84e0dbccb2f.png">

**Comment by nicooprat** [comment] 2017-11-01 15:40
Still experiencing these weird flashes with Chrome 62.0.3202.75 (Mac OS 10.12.6 ) and Mapboxgl 0.41.0. Tried the `overflow: hidden` trick described in https://github.com/mapbox/mapbox-gl-js/issues/5333 but without success.

**Comment by sheerun** [comment] 2017-11-04 15:54
for me it blinks with white on chrome 63

**Comment by ryanbaumann** [comment] 2017-11-06 02:17
If you've had this issue, please drop the make and model of your GPU along with the OS and your version of Chrome.  This info could help isolate the upstream Chrome issue that affects this bug.

Here's the setup I can produce this bug with:

**OS:** OSX 10.11.6
**Browser:** Chrome 62.0.3202.75 64-bit
**GPU:** Intel Iris Graphics 6100 1536MB

**Comment by sheerun** [comment] 2017-11-06 08:41
OS: 10.12.6
Browser: Chrome  63.0.3239.30 64-bit
GPU: Intel Iris Graphics 6100 1536 MB

**Comment by diogofigueiredo** [comment] 2017-11-06 09:42
OS: 10.12.6
Browser: Version 62.0.3202.75 (Official Build) (64-bit)
GPU: Intel Iris Graphics 6100 1536 MB

**Comment by nicooprat** [comment] 2017-11-06 10:13
Same here.

OS: 10.12.6
Browser: Chrome 62
GPU: Intel Iris Graphics 6100
(https://www.notebookcheck.net/Apple-MacBook-Pro-Retina-13-Early-2015-Notebook-Review.139621.0.html)

Confirm it works great on my iMac (mid-2011, GPU: AMD Radeon HD 6770M 512 Mo).

**Comment by zhali** [comment] 2017-11-06 12:28
i also meet this issue! the same with you, both on Chrome 61 and 62, who find the solution?

**Comment by zhali** [comment] 2017-11-06 12:31
OS: 10.12.6
Browser: Chrome 62 
GPU: Intel Iris Graphics 540 1536 MB

**Comment by dpieri** [comment] 2017-11-06 17:14
@ryanbaumann it looks like we have the same computer.

**OS**: OSX 10.11.6
**Browser**: Chrome 62.0.3202.75 64-bit
**GPU**: Intel Iris Graphics 6100 1536MB

**Comment by dpieri** [comment] 2017-11-06 22:54
I asked a few folks around the office and have a list of environments that can _not_ reproduce the bug:

**OS**: macOS Sierra 10.12.6
**GPU**: Intel Iris Pro 1536 MB
**Browser**: Chrome Version 62.0.3202.75

**OS**: macOS Sierra 10.12.6
**GPU**: Intel Iris Pro 1536 MB
**Browser**: Chrome Version 62.0.3202.75

**OS**: Ubuntu 16.04
**GPU**: GeForce GTX 960M
**Browser**: Chrome Version 62.0.3202.62 (Official Build) (64-bit)

**OS**: macOS Sierra 10.12.6
**GPU**: Intel Iris Pro 1536 MB
**Browser**: Chrome 56.0.2924.87 (64-bit)

**OS**: Ubuntu 14
**Browser**: chromium 62.0.3202.62.

**Comment by zhali** [comment] 2017-11-07 02:26
I m sure Chrome62+Graphics 6100 1536MB have this issue, and Chrome61+Graphics 6100 1536MB is fine, the bug is from Chrome or Mapbos GL ? 
does anyone from mapbox FT can foucs on this ?

**Comment by sheerun** [comment] 2017-11-07 03:43
I'd test it on chrome 61 on my machine but I cannot find official source of old releases to download. The only available versions are by 3rd party sites and I don't want a virus.

By the way, because of this issue I decided to use google maps instead, for now. Mapbox is currently terrible experience on OSX, very glitchy.

**Comment by 1wheel** [comment] 2017-11-07 19:50
**OS**: OSX 10.12.6 
**Browser**: 62.0.3202.75 
**GPU**: Intel Iris Graphics 6100 1536 MB

flickers for me on https://www.nytimes.com/elections/results/virginia-governor-election-gillespie-northam

**Comment by lbud** [comment] 2017-11-08 02:30
🤕 thanks for the reports everyone, we're looking into it.

**Comment by nicooprat** [comment] 2017-11-08 09:51
(It's happening in Opera too. I know it's the same engine but that may help anyway.)

**Comment by bryanculbertson** [comment] 2017-11-08 19:11
I am experiencing the blinking bug with:
**OS**: macOS Sierra 10.12.6
**GPU**: Intel Iris Graphics 6100 1536 MB
**Browser**: Chrome 62.0.3202.89 (Official Build) (64-bit)

**Comment by hujiulong** [comment] 2017-11-13 10:05
I encountered the same bug.
OS: OSX 10.11.6
Browser: 62.0.3202.89
GPU: Intel Iris Graphics 6100 1536 MB

however, there is no problem on Chrome 64.0.3265.0 canary.

**Comment by sheerun** [comment] 2017-11-13 13:07
I can experience this issue on chrome canary.

Browser: Chrome Canary 64.0.3265.0
OS: 10.12.6
GPU: Intel Iris Graphics 6100 1536 MB

**Comment by lbud** [comment] 2017-11-13 20:14
Reported upstream at https://bugs.chromium.org/p/chromium/issues/detail?id=784030. I can still reproduce in Canary 64.

**Comment by haibeeb** [comment] 2017-11-13 22:41
We are seeing the same issue here:

Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
OS: 10.12.6
GPU: Intel Iris Graphics 6100 1536 MB

This started with the latest Chrome upgrade from version 61.x to version 62.x and can be seen on:
https://ladata.myneighborhooddata.org

**Comment by zhali** [comment] 2017-11-14 06:27
Stay concerned
this is a serious problem

**Comment by NickWilderAP** [comment] 2017-11-16 18:29
This is very negatively affecting all our products using Mapbox.  Please consider this extremely urgent.

**Comment by alexgleith** [comment] 2017-11-16 21:42
I'm experiencing the same issues.

What happens is zooming or panning causes the map to flash. It's quite anoying and really impacts the experience of using the map.

mapbox-gl 0.40.1

macOS High Sierra 10.13
Intel graphics

Google Chrome is up to date
> Version 62.0.3202.94 (Official Build) (64-bit)

**Closed** 2017-11-17 22:33 UTC
Labels: environment-specific bug, high priority

**Comment by lbud** [comment] 2017-11-17 22:36
I think this is likely a problem with the shared depth/graphics buffer implementation of this specific line of Intel Iris graphics cards — I'm not sure what about depth/stencil reads/writes changed between Chrome versions, but I've reported this hunch upstream. The flicker happens sporadically when clearing the stencil buffer — somehow this interferes with (races or clears or blocks access to or something, I can't say) the depth buffer, and causes depth reads to fail on intermittent frames. We clear the stencil buffer every time we switch between sources, which explains why this effect is more prominent on some maps than others: the more sources on a map, the more frequently we clear the stencil buffer, and the more frequently this bug occurs (cc @dpieri).

Implemented a workaround in #5704; we'll get a patch release out now.

**Comment by lbud** [comment] 2017-11-18 03:15
Fixed in v0.42.1 — please upgrade, and open a new issue if you're still seeing something wrong.

**Comment by karlguillotte** [comment] 2017-11-18 07:41
Thanks for your work in that issue. 

Tried to install and file `dist/mapbox-gl.js` is not available. There is no JS files in the `dist` folder.

**Comment by zhali** [comment] 2017-11-20 07:09
@lbud thanks for mapbox FT, good job

**Comment by diogofigueiredo** [comment] 2017-11-20 11:31
Map blink when zooming is fixed but now the markers blink when updating their position.
as you can see in this example. 
https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-route/
Please zoom to the marker.

**Comment by lbud** [comment] 2017-11-20 21:05
Thanks @diogofigueiredo — looks like the bug you're describing is https://github.com/mapbox/mapbox-gl-js/issues/5716; please follow that issue for updates.

**Comment by dpieri** [comment] 2017-11-21 17:37
Thanks for all the investigation work and quick fix @lbud!

**Comment by nanoteilchen** [comment] 2018-01-03 09:27
Since the new version, the flickering is gone. But is it possible, to update the map editor as well? I'm like getting a stroke during editing a map... ;-)

**Comment by lbud** [comment] 2018-01-08 17:14
@nanoteilchen there are some internal issues blocking upgrading Studio temporarily, but we're working on it — thanks for your patience!

**Comment by EmmanuelTheCoder** [comment] 2021-01-02 00:57
This is 2021 and I still have the flickering on my app. How do I solve that?

**Comment by karimnaaji** [comment] 2021-07-12 21:57
We're trying to simplify a code path related to the fix of this issue in https://github.com/mapbox/mapbox-gl-js/pull/10813 (with the goal of removing the workaround).

I know this issue is fairly old and believe it should be safe to remove this workaround (as we're now on chrome >90 and it has been closed upstream since reported). But to be safe, would anyone with access to an Iris Graphics 6100 (macbook pro 2015) be able to access [this page](https://93094-8629417-gh.circle-artifacts.com/0/test/release/index.html#page=geojson-markers&access_token=pk.eyJ1IjoiY2xhcmV0cmFpbm9yIiwiYSI6ImNqdWJkd2VoMjBjaDEzeXA4ZjZoN2dsZ3UifQ.zt421MySeSY0veX_MZpLnA) and confirm whether the issue initially reported here is visible?

cc'ing @jingsam @dpieri @nicooprat @ryanbaumann @diogofigueiredo @zhali @alexgleith as you mentioned experiencing the issue in this thread.
