### ISSUE TITLE
Fill anti-aliasing does appear to be working

### ISSUE THREAD

**Issue by ekelleyv** [mapbox/mapbox-gl-js#4880] opened 2017-06-24 01:02 UTC
**mapbox-gl-js version**: 38.0
**browser version**: Chrome 60

Example of what is happening (make sure to view at full size, top box is just a fill, bottom box is fill + line):
![image](https://user-images.githubusercontent.com/1816394/27504331-8a38a9de-5855-11e7-9d53-4465c7c4dfb1.png)

We are currently having an issue where polygons with fills are not currently anti-aliasing (regardless of `fill-antialias` being set). Any time we have a high contrast polygon/background visible, the aliasing becomes very apparent.

However, lines are very nicely anti-aliased. So, currently in order to have a correctly anti-aliased shape, we need to have a fill + line layer of the same polygon with the same color.

Here is a JSFiddle showing the described behavior:
https://jsfiddle.net/jkzz4pqp/

Are we just misunderstanding what `fill-antialias` means? Or should the polygon be anti-aliased in a similar manner to the polygon + stroke?

If I am reading the source right, polygons _should_ be effectively drawing a line on top of the fill (like we are doing manually here):
https://github.com/mapbox/mapbox-gl-js/blob/3261d29b83b9268357ffed563bff184f68294a4f/src/render/draw_fill.js#L27-L28

Let me know if there is any other information I can provide.

**Comment by ekelleyv** [comment] 2017-06-24 01:12
Also, in case you are interested in how this is showing up on our MapboxGL venue maps at SeatGeek (left is fill only, right is fill + stroke):
![image](https://user-images.githubusercontent.com/1816394/27504480-4311a3f0-5858-11e7-9733-9a34bcbfbe17.png)

We definitely have more high-contrast lines than your average geo map :)

**Comment by jfirebaugh** [comment] 2017-06-26 02:21
This is probably an implementation where `ALIASED_LINE_WIDTH_RANGE` is [1, 1]. Refs #2080.

**Comment by ekelleyv** [comment] 2017-06-26 15:52
@jfirebaugh is there anything I can provide to confirm that?

**Comment by jfirebaugh** [comment] 2017-06-26 16:48
Can you go to https://browserleaks.com/webgl on affected browsers and see what "Aliased Line Width Range" reports?

**Comment by ekelleyv** [comment] 2017-06-26 16:53
```
Aliased Line Width Range	[1, 1]
```

**Comment by jfirebaugh** [comment] 2017-06-26 22:12
Okay, that's definitely the issue. Closing as duplicate of #2080.

**Closed by jfirebaugh** 2017-06-26 22:12 UTC
