### ISSUE TITLE
When fog is set and projection is not mercator, labels disappear

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11255] opened 2021-11-06 19:25 UTC
In `v2.6.0-beta.2`, [fog is removed entirely](https://github.com/mapbox/mapbox-gl-js/issues/11186) when projection is not mercator. However the other thing that's removed is labels!

| Mercator | Albers |
| --- | --- |
| <img width="837" alt="Screen Shot 2021-11-06 at 3 21 56 PM" src="https://user-images.githubusercontent.com/61150/140621490-baf03a7d-6103-4444-8c1e-92520caad18e.png"> | <img width="840" alt="Screen Shot 2021-11-06 at 3 21 44 PM" src="https://user-images.githubusercontent.com/61150/140621495-c4996d82-7fb5-4cab-99b3-c2a610b14f1c.png"> |

Ideally, fog is not rendered and there is no other visual impact.

**Comment by mourner** [comment] 2021-11-07 11:10
Duplicate of #11249.

**Closed by mourner** 2021-11-07 11:10 UTC
