### ISSUE TITLE
Fix bug preventing map from rendering on Chrome on Windows 10

### ISSUE THREAD

**Issue by calvinmetcalf** [mapbox/mapbox-gl-js#2942] opened 2016-08-04 13:40 UTC
Some of my co workers have been having issues viewing any webgl maps in chrome on windows
This is up to date chrome and windows 10, the map is blank white but opening up dev tools seems to suggest that stuff is loading as panning the whiteness causes more network traffic. Microsoft Edge _does_ work. 

![2016-08-04](https://cloud.githubusercontent.com/assets/1128607/17403829/64e44e68-5a27-11e6-8ffc-347b6ad234eb.png)

**Comment by mourner** [comment] 2016-08-16 16:09
Could you share what http://webglreport.com/ says on those machines?

**Comment by calvinmetcalf** [comment] 2016-08-16 16:30
pinging my coworker @ismyrnow who was the one who was experiencing this though he's on vacation this week so we might not get the report for a week or so

**Comment by wangtun** [comment] 2016-08-19 09:50
@calvinmetcalf  you could try set the pitch  a  value which is not zero！ @mourner  this issue may be  the   issue #2178 , it is closed. but the problem is still existing in some computer with version 0.20.0

**Comment by anandthakker** [comment] 2016-08-23 12:56
We've got a client reporting this in Firefox and Chrome on Windows.  I am asking him for the webglreport @mourner asked for and for any console errors, and to see if Edge works for him.

**Comment by anandthakker** [comment] 2016-08-23 13:10
Here's his webglreport:

![gltesttab1](https://cloud.githubusercontent.com/assets/4974151/17892827/31a97a2a-6911-11e6-9739-3ecdcca5a977.png)

Also
 - He's using Windows 7
 - No console errors on the check-for-support example page
 - Amazingly, the set-perspective example *does* work (https://www.mapbox.com/mapbox-gl-js/example/set-perspective/)

**Comment by TippyTipster** [comment] 2016-09-21 21:52
Ran into this error as well with a couple computers at the workplace. Setting the pitch to anything other than 0 made the map render for them though.

**Comment by ilyatrunov** [comment] 2016-10-31 14:12
The "pitch other than 0" trick is working.
I have a Win 7 machine (NVIDIA 210, latest drivers). IE 11 was rendering Mapbox GL, Chrome and FF was not.
Set the pitch to 1, рender was ok. But if I switch pitch back to 0 - the map disappears.

**Comment by ivanakimov** [comment] 2016-10-31 18:25
@ilyatrunov same thing, one of my customers applied pitch and it worked. Otherwise, just does not load.

**Comment by ilyatrunov** [comment] 2016-10-31 19:10
Yes, but now the map is pitched a little bit. I'm going to investigate a
little further

**Comment by TippyTipster** [comment] 2016-10-31 20:28
You are able to set the pitch to very small increments (such as .1) and it's quite negligible (no one I applied the pitch to at that level even noticed), until this issue is fixed.

**Comment by tgecho** [comment] 2016-12-06 20:36
This pitch hack/workaround appears to fix a few cases I've encountered, but it has the side effect of triggering a bit of z-fighting: https://github.com/mapbox/mapbox-gl-js/issues/3320

**Comment by mourner** [comment] 2016-12-06 21:06
This should have been fixed by #3740.

**Closed by mourner** 2016-12-06 21:06 UTC
Labels: platform-specific bug

**Comment by ivanakimov** [comment] 2017-01-18 16:54
One of my clients has just shared a screenshot where the map does not load only on Win 10 + latest Chrome. Could there be something else behind this? (Using v0.29.0)
