### ISSUE TITLE
Use bundled version instead of source files

### ISSUE THREAD

**Issue by alex3165** [mapbox/mapbox-gl-js#2344] opened 2016-03-27 12:13 UTC
**mapbox-gl-js version**: 0.15, 0.16

### Steps to Trigger Behavior

 1. Use the library in webpack environment.

### Expected Behavior

The library should work without any workaround when using webpack.

### Actual Behavior

- Cannot find module fs when it come to import shaders
- Cannot find module json when importing style, see : https://github.com/mapbox/mapbox-gl-style-spec/issues/435

### Questions :

- Why do you deprecate the use of the bundled file in `dist/mapbox-gl.js` ? 
- Otherwise can you consider using require to import shaders and webpack users could use https://github.com/grieve/webpack-glsl-loader / browserify users could maybe use : https://www.npmjs.com/package/browserify-shader ?

For me the best solution would be to expose a bundled UMD file.

**Comment by tmcw** [comment] 2016-03-27 19:10
Duplicate of existing issue #1649

**Closed by tmcw** 2016-03-27 19:10 UTC
