### ISSUE TITLE
Incorrect 'fill' layer rendering: labels on top when fill-opacity = 1

### ISSUE THREAD

**Issue by kmandov** [mapbox/mapbox-gl-js#3695] opened 2016-11-24 12:17 UTC
I ran into a bug in fill layers when trying to explain how to [create a mask layer](http://stackoverflow.com/questions/40772764/mask-mapbox-gl-map-with-arbitrary-polygon).

**mapbox-gl-js version**: v0.28.0

### Steps to Trigger Behavior

 1. Open the example: https://jsfiddle.net/kmandov/cr2rav7v/
 2. Change 'fill-opacity' to 1 or remove it  (as in [here](https://jsfiddle.net/kmandov/cr2rav7v/4/))
 3. The labels are drawn on top of the fill layer

### Expected Behavior
![mapboxgl-working](https://cloud.githubusercontent.com/assets/2805297/20598092/0c7aa462-b250-11e6-8a0e-000c471a8fbf.png)
https://jsfiddle.net/kmandov/cr2rav7v/

### Actual Behavior
![mapboxgl-broken](https://cloud.githubusercontent.com/assets/2805297/20598093/0c7c7382-b250-11e6-8971-30b7eb12b370.png)
https://jsfiddle.net/kmandov/cr2rav7v/4/

**Comment by andrewharvey** [comment] 2016-11-24 20:24
I think this is a duplicate of #2074. The workaround I've been using is to set the opacity to something like 0.999.

Other issues such as #2909 were closed as duplicates of #2074.

**Comment by lucaswoj** [comment] 2016-11-28 17:53
Closing as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2074

**Closed by lucaswoj** 2016-11-28 17:53 UTC
