### ISSUE TITLE
Let us create circles with a radius in distance instead of pixels

### ISSUE THREAD

**Issue by princeofnaxos** [mapbox/mapbox-gl-js#3432] opened 2016-10-21 12:53 UTC
**mapbox-gl-js version**: 0.26.0

Feature request:

Circle radii should be in kilometers (as in mapbox.js) and should grow and shrink when zooming.

**Comment by lucaswoj** [comment] 2016-10-24 18:04
duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2525

**Closed by lucaswoj** 2016-10-24 18:04 UTC
Labels: enhancement
