### ISSUE TITLE
Garbled text and sprites when loading multiple mapbox-gl instances in v0.23.0

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-js#3126] opened 2016-09-01 12:24 UTC
I am seeing some strange behaviour in mapbox v0.23.0.

When I first load a map and style, everything is ok.

If I then load another mapbox instance (e.g. using mapbox compare), the text appears garbled and the sprites are all mixed up and also displaying strangely (see screenshot).

Reverting back to v0.22.1 the behaviour doesn't occur.

In the console, I get a series of 'Error: Not Found' errors at evented.js:92 - this doesn't appear when I use v0.22.1 so I assume it's relevant to the issue.

Not sure if it's a bug or something I need to change in my styles with the new release? It seems unlikely it's to do with my styles, because if I load either of them individually they display correctly. In fact I can even load the exact same style in the second mapbox-gl instance and it appears fine in the first but garbled in the second (see second screenshot).

Note: I have custom sprites in the styles which may be relevant.

Thanks,
Joe

<img width="913" alt="screen shot 2016-09-01 at 16 14 39" src="https://cloud.githubusercontent.com/assets/13920398/18167057/93d88c5e-705f-11e6-962c-d70dc194ab17.png">

<img width="804" alt="screen shot 2016-09-01 at 16 23 29" src="https://cloud.githubusercontent.com/assets/13920398/18167228/764016e8-7060-11e6-841f-d88b03417758.png">

**Comment by jfirebaugh** [comment] 2016-09-01 14:54
Duplicate of #3086.

**Closed by jfirebaugh** 2016-09-01 14:54 UTC
