### ISSUE TITLE
Transparent Webm video frames are rendered cumulatively.

### ISSUE THREAD

**Issue by dpieri** [mapbox/mapbox-gl-js#2216] opened 2016-03-02 20:30 UTC
This bug prevents developers from using videos with an alpha channel. 

**mapbox-gl-js version**:1.15.0

https://jsbin.com/wequguzuge/1/edit?html,output
(Note, if your browser doesn't support Webm video then it will show up as a black box, or as nothing.
### Steps to Trigger Behavior
1. Replace the video URL in the "Add a Video" demo with one of the transparent videos from this page: http://simpl.info/videoalpha/
2. Wait a few seconds
### Expected Behavior

Video is rendered one frame at a time so you can see the map below the dancing person.
### Actual Behavior

Each frame of the video adds up until it obscures the map below the video.

**Suggestion:** What I'm trying to implement (an electricity animation that travels the length of a power line to make it more clear) would probably be easier and less resource intensive to do with an animated GIF. I would prefer transparent animated GIF support over transparent Webm support.

**Comment by mourner** [comment] 2016-03-03 13:40
Confirmed. That JSBin is hilarious! :laughing:

**Comment by ansis** [comment] 2016-03-04 01:03
In Firefox it renders with a grey background. It looks like Firefox doesn't support webm alpha: https://bugzilla.mozilla.org/show_bug.cgi?id=944117

In Chrome:

Changing this [texSubImage2D](https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/video_source.js#L163) to a `texImage2D` call makes it render correctly in Chrome but not Firefox. `texImage2D` allocates new memory. `texSubImage2D` should overwrite existing memory but it looks like it's being blended instead. I think this could be a browser bug.

**Comment by rofrol** [comment] 2017-09-14 16:39
Can we close this? Linked bug is fixed since Firefox 53

**Comment by ansis** [comment] 2017-09-14 17:04
Yep!

**Closed by ansis** 2017-09-14 17:04 UTC
Labels: bug, environment-specific
