### ISSUE TITLE
Please, please marker.on('click', () => {})

### ISSUE THREAD

**Issue by secretgspot** [mapbox/mapbox-gl-js#8787] opened 2019-09-20 21:03 UTC
## Motivation
For the love of all that's holy, please add Marker onClick event similar to Map.on('click')
it is so frustrating working with modern frameworks like webcomponents or custom elements and being able to click on the marker and get anything other than a popup.   Maybe add another method similar to .setPopup() like .setClick() or .dispatchEvent().

Please, please make it happen, I can't be the only one and I don't see why it's such an issue and not already have it implemented.

click on Marker and fire an event or display an alert() and not deal with popup.  It's possible with geojson and using map.on('click', 'layerId', function()) but how does one do it without using layers?

**Comment by mourner** [comment] 2019-09-20 21:15
Thanks for the feedback! Let's keep the discussion centralized in one ticket though. Closing as a duplicate of #7793.

**Closed by mourner** 2019-09-20 21:15 UTC
