### ISSUE TITLE
Location name is not getting the actual positions - all location name is getting absolute positioned

### ISSUE THREAD

**Issue by tareq0065** [mapbox/mapbox-gl-js#9344] opened 2020-02-26 09:27 UTC
**mapbox-gl-js version**: v1.8.0

**browser**: Chrome - 79.0.39
![image](https://user-images.githubusercontent.com/25137925/75331035-409ef580-58ac-11ea-8886-f534bbfe267a.png)

### Steps to Trigger Behavior

 1. Just create an example https://docs.mapbox.com/mapbox-gl-js/example/simple-map/
 2.
 3.

### Link to Demonstration

https://codesandbox.io/s/mapbox-location-name-gn79g

### Expected Behavior
The location names should get the actual position.
![image](https://user-images.githubusercontent.com/25137925/75330845-ebfb7a80-58ab-11ea-811d-2c9d056a25c7.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/25137925/75330357-29133d00-58ab-11ea-9377-3b48db859d79.png)

**Comment by mourner** [comment] 2020-02-26 14:21
Duplicate of #9327. Fixed in v1.8.1 release.

**Closed by mourner** 2020-02-26 14:21 UTC
