### ISSUE TITLE
Style property 'interactive' does not work

### ISSUE THREAD

**Issue by AbrahamArun** [mapbox/mapbox-gl-js#3727] opened 2016-12-01 09:01 UTC
**0.28.0**:

### Steps to Trigger Behavior

 1. Use a style  such as 
```javascript
{
    'id': 'foo',
    'type': 'symbol',
    'source':'foo-id',
    'layout': {
      'icon-image': 'current-location-marker',
      'icon-allow-overlap': true,
      'icon-ignore-placement': true
    },
    'interactive' : false,
    'minzoom': minZoom,
    'maxzoom': maxZoom
  };
}
```
 2. And then load the map, I get the following error
<img width="529" alt="screen shot 2016-12-01 at 2 23 15 pm" src="https://cloud.githubusercontent.com/assets/5391059/20787492/1198a0ac-b7d2-11e6-8fb3-eca10f023945.png">

The property `interactive` was working in the previous versions. Neither is it available in the docs now. If this has been removed, then why is it that I do not see it in the changelog either?

**Comment by indus** [comment] 2016-12-01 09:40
It is indeed deprecated https://github.com/mapbox/mapbox-gl-style-spec/pull/544

**Comment by jfirebaugh** [comment] 2016-12-01 16:54
Duplicate of #3710.

**Closed by jfirebaugh** 2016-12-01 16:54 UTC

**Comment by lucaswoj** [comment] 2016-12-01 22:52
Apologies @AbrahamArun. We deprecated this property with the intent that it would be a no-op and ignored by the validator. Unfortunately there was a regression that caused the validator to fail on this property. The regression will be fixed in the next release.

**Comment by AbrahamArun** [comment] 2016-12-02 03:58
@lucaswoj Gotcha !!
