### ISSUE TITLE
fill layer with multipolygons will merge like this follow

### ISSUE THREAD

**Issue by chinesejar** [mapbox/mapbox-gl-js#9072] opened 2019-12-05 07:12 UTC
I generate geojson data using d3.contounr, the data contains features of MultiPolygon. When I render it with fill layer, the small zoom it will merge, when I scale zoom, it will normal. Here is the example.
[example](https://codesandbox.io/s/happy-pascal-uhv5k?fontsize=14&hidenavigation=1&theme=dark)

**mapbox-gl-js version**: 1.6.0

**browser**: chrome

### Steps to Trigger Behavior

 1. Add GeoJSON data with array of MultiPolygon
 2. small zoom it will merged, but it is wrong.
![wrong](https://i.imgur.com/1vIDgkK.jpg)
 3. large zoom it shows normal
![right](https://i.imgur.com/QHevCZn.png)

**Comment by chinesejar** [comment] 2019-12-19 16:12
@mourner hey are you busy? Could you please help me.

**Comment by mourner** [comment] 2020-01-21 16:48
This is most likely a duplicate of #7023 — let's track it there.

**Closed by mourner** 2020-01-21 16:48 UTC
Labels: bug :beetle:
