### ISSUE TITLE
Feature: Filter null values

### ISSUE THREAD

**Issue by benstadin** [mapbox/mapbox-gl-js#4785] opened 2017-06-05 22:58 UTC
Hi,

it would be handy if it was possible to filter null objects. For example, this doesn't work at the moment:

`"filter": ["all", ["!=", "{name}", null]`

but this works - though I cannot ignore features having a "name" attribute with null:

`"filter": ["all", ["!=", "{name}", ""]`

Reference: https://www.mapbox.com/mapbox-gl-js/style-spec/#types-filter

**Comment by jfirebaugh** [comment] 2017-06-05 23:05
Duplicate of #4410.

**Closed by jfirebaugh** 2017-06-05 23:05 UTC
