### ISSUE TITLE
Pinch zoom scaling entire viewport iOS (11.3)

### ISSUE THREAD

**Issue by FredFunk** [mapbox/mapbox-gl-js#6447] opened 2018-04-03 11:50 UTC
Since the release of iOS 11.3 we've received numerous user inquiries related to scaling of the entire viewport when attempting to zoom in/out of the map area on iOS devices.

Try this example below on an iOS device:
https://www.mapbox.com/bites/00379/#10/38.8900/-77.0200

mapbox-gl.js v0.44.1

### Steps to Trigger Behavior 
1. Pinch zoom on the map area on iOS device (11.3)

### Expected Behavior
Only the map area zooms in/out

### Actual Behavior
Scales entire viewport

**Comment by anandthakker** [comment] 2018-04-03 11:56
Duplicate of #6095

**Closed by anandthakker** 2018-04-03 11:56 UTC
