### ISSUE TITLE
Is it possible to write elevation layer/plugin？

### ISSUE THREAD

**Issue by beginor** [mapbox/mapbox-gl-js#6662] opened 2018-05-14 00:13 UTC
Mapbox GL JS is rendering with webgl， the surface of the map view is flat， I want to know it is possible to write a plugin or layer， render the elevation of ground？

the hillshade layer with raster-dem source just use shadow and light， does not render elevation in 3d.

**Comment by jfirebaugh** [comment] 2018-05-14 15:44
Duplicate of #1489.

**Closed by jfirebaugh** 2018-05-14 15:44 UTC
