### ISSUE TITLE
Cannot change fill-pattern with feature state expression

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-gl-js#9733] opened 2020-05-28 16:07 UTC
**mapbox-gl-js version**:v1.10.1

**browser**:Chrome 81

### Steps to Trigger Behavior

 1. Set {hover:true} featureState of a polygon source on hover
 2. Set the fill-pattern of hovered features using an expression ` map.setPaintProperty('building', 'fill-pattern', ['case', ['==', ['feature-state', 'hover'], true], 'airport-11', 'dot-11'])`

### Link to Demonstration

https://jsfiddle.net/planemad/bvygh9om/60/

### Expected Behavior

Expecting fill-pattern will change to the airport symbol on hover, but it does not change. 

Changing fill-opacity or other paint properties with the same expression works, so was expecting fill-pattern to behave similiarly as per the [docs](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-fill-fill-pattern).

### Actual Behavior

![_Screen](https://user-images.githubusercontent.com/126868/83164936-d5e39d00-a0da-11ea-9862-db53e6ae7436.gif)

**Comment by mourner** [comment] 2020-05-28 16:52
Duplicate of #7207

**Closed by mourner** 2020-05-28 16:52 UTC
Labels: bug :beetle:

**Comment by hmendezm** [comment] 2022-01-31 16:27
Hi everyone,
I have "mapbox-gl": "^2.6.1" and I try to use feature-stare value to set patterns but it is not working.  According to the information above, we should be able to use ['feature-state', string] in fill-pattern, right? is this issue fixed? How can I implement fill-pattern at a feature level if this is not part of the geojson. IN my case I am using vector 

In the code below, 'pattern' has the pattern that should be used for the feature.
{
      id: 'layer1',
      type: 'fill',
      source: 'source1',
      paint: {
        'fill-pattern': ['feature-state', 'pattern']
      } 

Best
H. Mendez
