### ISSUE TITLE
GeoJson Feature property with null value becomes "null" as string literal when querying rendered features

### ISSUE THREAD

**Issue by Bernoulli-IT** [mapbox/mapbox-gl-js#9968] opened 2020-09-09 13:39 UTC
**mapbox-gl-js version**: 1.11.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. Set source data with a GeoJson FeatureCollection
 2. The collection contains at least one feature with a property with a null value
 3. Query rendered features and inspect the property, its value has become a literal "null" string

### Expected Behavior

The value should remain as null.

### Actual Behavior

The value became "null" as a literal string.

### Example

Start of a GeoJson file.

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "id": "NLWMO002360566200097",
      "properties": {
        **"bridgeDetails.vild": null**,
...

Property inspected with Chrome inspector:

**bridgeDetails.vild: "null"**

Is this behavior by design? It looks odd. And needs some additional client-side cumbersome handling when expecting feature properties to be possibly null instead of "null".

**Comment by ryanhamley** [comment] 2020-09-09 16:43
This is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/8497 Closing to focus discussion there

**Closed by ryanhamley** 2020-09-09 16:43 UTC
