### ISSUE TITLE
Marker position offset on Android browser

### ISSUE THREAD

**Issue by as299999** [mapbox/mapbox-gl-js#12141] opened 2022-08-08 06:54 UTC
mapbox-gl version：2.9.2

environment: Android Browser

After changing the width and height of the map container, call resize(), The marker is shifted.

Expected Behavior
marker be in the exact spot

Actual Behavior
The tag looks like it's drifting

**Comment by as299999** [comment] 2022-08-08 09:07
The width issue is the same as issue 12067

**Comment by SnailBones** [comment] 2022-08-10 20:39
Closing as a duplicate of #12067.

**Closed by SnailBones** 2022-08-10 20:39 UTC
Labels: environment-specific :desktop_computer:
