### ISSUE TITLE
Include feature id in the mouseleave event

### ISSUE THREAD

**Issue by sirmspencer** [mapbox/mapbox-gl-js#10943] opened 2021-08-18 17:36 UTC
## Motivation
The demo here https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/ uses a variable to save the feature id.  The problem is that when there are overlapping icons (ie from two different layers), it becomes messy trying to figure out which one caused the event.

## Design Alternatives
Include feature id in the mouseleave event

## Design
Include feature id in the mouseleave event

**Comment by arindam1993** [comment] 2021-08-19 20:07
This is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/9995
The current workaround is to attach a mouse handler directly to the container div, and perform `queryRenderedFeatures` to get all the features across all overlapping layers..

Closing this issue to continue discussion in #9995

**Closed by arindam1993** 2021-08-19 20:07 UTC
