### ISSUE TITLE
Uncaught ReferenceError: _typeof is not defined

### ISSUE THREAD

**Issue by camertron** [mapbox/mapbox-gl-js#8574] opened 2019-07-29 19:43 UTC
**mapbox-gl-js version**: 1.1.1

**browser**: Brave (Chromium 75.0.3770.100), Firefox 68.0.1

### Steps to Trigger Behavior

webpack ^4.37.0
@babel/core: ^7.5.5
@babel/plugin-proposal-class-properties: ^7.5.5
@babel/plugin-proposal-export-default-from: ^7.5.2
@babel/plugin-proposal-object-rest-spread: ^7.5.5
@babel/plugin-syntax-dynamic-import: ^7.2.0
@babel/plugin-transform-shorthand-properties: ^7.2.0
@babel/preset-env: ^7.5.5
@babel/preset-react: ^7.0.0

.babelrc:

```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false,
        "targets": {
          "browsers": ["> 5%", "last 2 versions", "ie 11"]
        },
        "forceAllTransforms": false,
        "loose": true,
        "exclude": ["transform-typeof-symbol"],
        "useBuiltIns": "usage",
        "corejs": 3
      }
    ],
    "@babel/preset-react"
  ],
  "env": {
    "test": {
      "presets": [["@babel/preset-env"], "@babel/preset-react"],
      "plugins": [
        [
          "@babel/proposal-class-properties",
          {
            "spec": true
          }
        ]
      ]
    }
  },
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/proposal-object-rest-spread",
    "@babel/transform-shorthand-properties",
    "@babel/proposal-class-properties",
    "@babel/plugin-proposal-export-default-from"
  ]
}
```

### Expected Behavior

I expect the map to load.

### Actual Behavior

Console contains 4 errors that say "Uncaught ReferenceError: _typeof is not defined"

I have googled around for answers and have found several issues filed against this repo with identical symptoms. I've tried all the solutions with absolutely no success. Any ideas? I'm at my absolute wit's end.

**Comment by mourner** [comment] 2019-07-29 20:09
Can you try excluding `mapbox-gl` from transpilation by Babel? If you're sure this doesn't work, we'd appreciate a full, self-contained reproduction of the issue, e.g. using a separate repository or a gist.

**Comment by Liquid-Zhangliquan** [comment] 2019-07-30 06:09
hello,I hava the same problem.
![image](https://user-images.githubusercontent.com/23397455/62104859-6131ad80-b2d3-11e9-9080-7c3f784ab7e2.png)
it looks like 'web worker' doesn`t work ?
![image](https://user-images.githubusercontent.com/23397455/62104899-83c3c680-b2d3-11e9-80d2-2e39a6940fed.png)
![image](https://user-images.githubusercontent.com/23397455/62104962-af46b100-b2d3-11e9-9fb8-8e92d6a06a3b.png)

**Comment by mourner** [comment] 2019-07-30 07:12
@Liquid-Zhangliquan this is because the `mapbox-gl-js` bundle (which is already transpiled) is being transpiled by Babel again in your configuration. You should exclude it from transpilation.

**Comment by camertron** [comment] 2019-07-30 22:17
@mourner the weird thing is all my node_modules are supposedly excluded from Babel transpilation, yet somehow I still see this problem. I tried every fix I could find online for excluding files from Babel but nothing worked. I finally ended up solving the problem by using a separate loader just for mapbox-gl. In my webpack config I now have:

```javascript
environment.loaders.insert(
  'mapbox-loader',
  {
    test: /mapbox.*\.js$/,
    use: 'script-loader'
  }
);
```

Then in my react component I have

```javascript
import 'mapbox-gl'
```

It's not ideal because the script loader evaluates the mapbox code directly in the component, but I couldn't fix it any other way :(

**Comment by mourner** [comment] 2019-08-20 15:04
> Can you try excluding mapbox-gl from transpilation by Babel? If you're sure this doesn't work, we'd appreciate a full, self-contained reproduction of the issue, e.g. using a separate repository or a gist.

Have to close the issue because it appears on the app config side, not a mapbox-gl-js fault, and there's no reproducible test case to prove otherwise.

**Closed by mourner** 2019-08-20 15:04 UTC
Labels: needs information :pray:

**Comment by yumindeckard** [comment] 2019-09-26 01:13
I am so disappointed.

Just google the error message and `mapbox`, tons of results would be displayed and yet, there is no solution. And you don't bother to test it. 

I am seriously concerned and disturbed. We won't pay for shit like this.

**Comment by camertron** [comment] 2019-09-26 01:28
@yumindeckard I know it's frustrating to wrestle with issues like this, but please remember the people who work on open-source projects like mapbox-gl often do so in their free time and without any compensation. The best thing to do to get this issue solved would be to create and share a reproducible test case. I would do so myself but I'm also time-limited right now. If you have time to help, please pitch in.

**Comment by dchersey** [comment] 2020-04-23 16:25
I had the same issue -- then saw this related issue with additional solutions. 
I am using react-rails, so adding 
```
environment.loaders.delete('nodeModules')
```
to my config/webpack/environment.js solved the problem. 

I expect this would also work for non-rails webpack.config.js.

I had tried using script-loader as suggested above, and it got me past the typeof issues but then I received an error calling 
```
new mapboxgl.Map({
      container: this.mapContainer,
...
```
-- said it was not a constructor.   Removing the nodeModules from the webpack loaders seems like a good idea anyway, and solved this for me.

**Comment by jordymeow** [comment] 2020-04-29 15:27
I am encountering the same issue. Using Parcel and Babel 7. It seems like none of the libraries wants really to give us a proper solution :( 

I have tried to exclude MapBox from the transpilation, but the Babel's doc is terribly obscure about how to do this. Is there an alternative way?

You guys, developing MapBox (and thank you for this), aren't you using Babel 7? How are you doing it? Of course, I can make it work with Babel 6, or with WebPack + workarounds, but I would like to feel like I am in 2020.

**Comment by gooin** [comment] 2020-12-07 06:59
`babel7` see: [https://github.com/mapbox/mapbox-gl-js/issues/3422](https://github.com/mapbox/mapbox-gl-js/issues/3422)
