### ISSUE TITLE
Favor typed definitions over generic ones in documentation

### ISSUE THREAD

**Issue by ryanhamley** [mapbox/mapbox-gl-js#7505] opened 2018-10-29 19:13 UTC
## Motivation

This is a consolidation ticket for the following issues:

- https://github.com/mapbox/mapbox-gl-js/issues/7500
- https://github.com/mapbox/mapbox-gl-js/issues/7501
- https://github.com/mapbox/mapbox-gl-js/issues/7502
- https://github.com/mapbox/mapbox-gl-js/issues/7503
- https://github.com/mapbox/mapbox-gl-js/issues/7504

Our documentation often makes vague references to generic Javascript types like `Object`, `callback` and `data` without offering any specifics on what they look like, in spite of the fact that we use Flow types to ensure the data flowing through the library conforms to certain expected parameters. It would be helpful to provide users with this typed context so they can better understand what the data they are receiving will look like.

## Design

We can update the documentation in most places to reference the typed values. If a method returns a Plain Old Javascript Object (POJO) because we lack a type, we can often link to the style spec. For example, `map.getLight` returns a POJO instead of a `Light` object, but we can still point the user to the [Light style specification](https://www.mapbox.com/mapbox-gl-js/style-spec/#light) like `setLight` does.

cc @bdirito

**Comment by ansis** [comment] 2021-07-09 22:07
Closing as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/5304

**Closed by ansis** 2021-07-09 22:07 UTC
Labels: docs :scroll:
