### ISSUE TITLE
Image overlay extent accuracy

### ISSUE THREAD

**Issue by dirkvdb** [mapbox/mapbox-gl-js#9396] opened 2020-03-10 10:05 UTC
mapbox-gl-js 1.8.1

browser: chrome/firefox

### Steps to Trigger Behavior

 1. Add an image layer
 2. Draw the image extent as a geojson polygon
 3. The extents do not match

### Link to Demonstration

https://jsbin.com/himimakesa/edit?html,output

Enable cross origin requests as it links to an external image

### Expected Behavior
I would expect the polygon and the image extent to match

### Actual Behavior
There is a minor offset
![image](https://user-images.githubusercontent.com/1011958/76301092-0545f300-62be-11ea-9807-edf8f7738cbe.png)

### QGIS Behavior
This is the same raster data loaded in QGIS
![image](https://user-images.githubusercontent.com/1011958/76301342-5c4bc800-62be-11ea-9deb-4023c70aabb2.png)

Here the extent is the same as the rendered geojson polygon. So it looks like there is some offset when rendering images.

**Comment by asheemmamoowala** [comment] 2020-04-08 00:30
Closing as a duplicate of #9158 .

**Closed by asheemmamoowala** 2020-04-08 00:30 UTC
Labels: bug :beetle:

**Comment by dirkvdb** [comment] 2022-05-10 08:05
Issue #9158 has been fixed in the mean while, but it does not solve this issue however
