### ISSUE TITLE
Support map zoom -1

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#8144] opened 2019-04-11 23:02 UTC
I have just run into an issue where a client wanted a full world map on the front page of a website. On desktop, it was fine, but on mobile (with a maximum width of 350px), the edges of the map are cut off.

Essentially, in order to display the full world at such a small physical scale, we'd need to go down to zoom -1.

I'm assuming there are many hard limits that would make this impossible. But, um, it doesn't hurt to ask? :)

**Comment by ryanhamley** [comment] 2019-04-12 00:18
This is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/3055 so I'm going to close to focus discussion there. Thanks!

**Closed by ryanhamley** 2019-04-12 00:18 UTC
