### ISSUE TITLE
map.getStyle() returns an undefined 'url' in sources

### ISSUE THREAD

**Issue by wanyanyan** [mapbox/mapbox-gl-js#4854] opened 2017-06-20 06:33 UTC
**mapbox-gl-js version**: The latest

### Steps to Trigger Behavior

 1. I rendered a map with the sources object like this:
![image](https://user-images.githubusercontent.com/12003895/27319547-9f2aab50-55c4-11e7-96bc-558e531e66fb.png)

 2.Then I use `map.getStyle()` to get the style and use this style rendering another map. But I get the following error:
![image](https://user-images.githubusercontent.com/12003895/27319594-d63825e6-55c4-11e7-81c9-b6e75dcc4737.png)

 3. The problem is in `RasterTileSource.prototype.serialize` , this function return an undefined 'url'.
![image](https://user-images.githubusercontent.com/12003895/27319690-37b9e3ae-55c5-11e7-83f0-8c915a3fbb97.png)

![image](https://user-images.githubusercontent.com/12003895/27319670-2b06688a-55c5-11e7-8ad0-9f0720e8c9ef.png)

### Expected Behavior
Use the style rendering a same map.

### Actual Behavior
![image](https://user-images.githubusercontent.com/12003895/27319594-d63825e6-55c4-11e7-81c9-b6e75dcc4737.png)

Sorry for my bad English, hope you can understand.

**Comment by jfirebaugh** [comment] 2017-06-20 17:23
Duplicate of #3893.

**Closed by jfirebaugh** 2017-06-20 17:23 UTC
