### ISSUE TITLE
It blinks too much

### ISSUE THREAD

**Issue by Jinkwon** [mapbox/mapbox-gl-js#6418] opened 2018-03-29 05:52 UTC
**mapbox-gl-js version**: Latest version

### Steps to Trigger Behavior

 1. no steps

### Expected Behavior
No more blink.

### Actual Behavior
Blink like my eyes.

![blink](https://user-images.githubusercontent.com/1798916/38072302-a098ed24-3360-11e8-849d-c8e0dd176c82.gif)

**Comment by mourner** [comment] 2018-03-29 07:54
Duplicate of #6315. The fix is in the works.

**Closed by mourner** 2018-03-29 07:54 UTC

**Comment by Jinkwon** [comment] 2018-05-28 14:57
Resolved at v0.45.0
