### ISSUE TITLE
dasharrays never terminate at 90 degrees 

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#1574] opened 2015-09-30 14:17 UTC
Dasharrays seem to always have angled or oddly cropped caps:

![screen shot 2015-09-30 at 10 16 18 am](https://cloud.githubusercontent.com/assets/108094/10195551/335c0048-675c-11e5-9b5f-a3de0e10fff9.png)

![screen shot 2015-09-30 at 10 17 54 am](https://cloud.githubusercontent.com/assets/108094/10195585/5f36713a-675c-11e5-9e87-e2954d8de9c0.png)

I would expect that the caps would be 90 degrees.

**Comment by ansis** [comment] 2016-01-07 00:14
This is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/967

**Closed by ansis** 2016-01-07 00:14 UTC
