### ISSUE TITLE
Return serialized style layer from map.getLayer() 

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#4742] opened 2017-05-23 15:14 UTC
Currently, `map.getLayer()` returns a `StyleLayer` object, which has methods like `setPaintProperty`, etc.  This is misleading, because `StyleLayer`'s setters are not intended to be user-facing: to work properly, they depend on being called as part of the batch updating flow that's managed by the `Style` object.

I think it would be clearer to just return a serialized version of the layer from `map.getLayer()`.

**Comment by anandthakker** [comment] 2017-05-23 15:14
Refs https://github.com/mapbox/mapbox-gl-js/issues/4738

**Comment by jfirebaugh** [comment] 2017-05-23 15:24
Duplicate of #3713.

**Closed by jfirebaugh** 2017-05-23 15:24 UTC
Labels: api, breaking change
