### ISSUE TITLE
Memory Leak after map.remove()

### ISSUE THREAD

**Issue by Mariusun** [mapbox/mapbox-gl-js#4862] opened 2017-06-21 20:58 UTC
**mapbox-gl-js version**:
v0.38.0

### Steps to Trigger Behavior

 1. Go to this html:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mapbox GL Memory Leak</title>
    <script src='https://api.mapbox.com/mapbox-gl-js/v0.38.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.38.0/mapbox-gl.css' rel='stylesheet' />
    <style>
      body { margin:0px; padding:0px; }
      #map { position:absolute; top:0px; bottom:0px; width:100%; }
      #addIt { background: green; position:absolute; top:0px; left: 0px; width:100px; line-height: 20px; display: block; }
      #removeIt { background: red; position:absolute; top:20px; left: 0px; width:100px; line-height: 20px; display: block; }
    </style>
  </head>
  <body>
    <div id="map"> </div>
    <div id="addIt">Add</div>
    <div id="removeIt">Remove</div>

    <script>
    mapboxgl.accessToken = 'YOUR_ACCESS_TOKEN';

    var map;

    document.getElementById('removeIt').addEventListener('click', function(e) {
      map.remove();
      map = null;
    });

    document.getElementById('addIt').addEventListener('click', function(e) {
       map = new mapboxgl.Map({ container: 'map', style: 'mapbox://styles/mapbox/streets-v10'});
    });

    </script>
  </body>
</html>

```

 2. Add your access token, then click Add, Remove, Add, Remove ... many times

### Expected Behavior

No memory leak.

### Actual Behavior

In Chrome, Safari and Firefox the following happens:

<img width="120" alt="mapbox_chrome_memory_leak" src="https://user-images.githubusercontent.com/22380010/27406004-ef49ee60-56d3-11e7-9f14-ea505471870c.png">

<img width="338" alt="mapbox_safari_memory_leak" src="https://user-images.githubusercontent.com/22380010/27406022-fd0530a0-56d3-11e7-8716-f18dadc6a250.png">

<img width="122" alt="mapbox_firefox_memory_leak" src="https://user-images.githubusercontent.com/22380010/27406059-11566ea2-56d4-11e7-8ef2-be8d06782300.png">

**Comment by jfirebaugh** [comment] 2017-06-21 21:02
Duplicate of #3264.

**Closed by jfirebaugh** 2017-06-21 21:02 UTC

**Comment by Mariusun** [comment] 2017-06-21 21:16
Thank you for the quick response.
Do you know whether this issue is going to be fixed anytime soon?
