### ISSUE TITLE
Dynamic loading of images in unclustered layer

### ISSUE THREAD

**Issue by danielsvane** [mapbox/mapbox-gl-js#6240] opened 2018-02-27 13:58 UTC
Based on the example from https://www.mapbox.com/mapbox-gl-js/example/cluster/, is it possible to dynamically load images as icons when the unclustered symbols are shown?

Currently I'm using one image that has previously been loaded like this:

```
map.addLayer({
  id: 'unclustered-point',
  type: 'symbol',
  source: 'assets',
  filter: ['!has', 'point_count'],
  layout: {
    'icon-image': 'cat',
  }
})
```

But we have 1000+ points with different images, and we can't possibly preload all the images. Is there a way to provide a url to `icon-image` or another workaround?

**Comment by jfirebaugh** [comment] 2018-02-27 15:47
Duplicate of #4816.

**Closed by jfirebaugh** 2018-02-27 15:47 UTC
