### ISSUE TITLE
API docs: Some links with number sign symbols are not correct

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#6897] opened 2018-07-01 05:27 UTC
Example: `mouseenter`
https://www.mapbox.com/mapbox-gl-js/api/#map.event:mouseenter

![image](https://user-images.githubusercontent.com/20856381/42131245-4493ce8a-7cfe-11e8-8292-5d1085699b64.png)

Currently the link is:
https://www.mapbox.com/mapbox-gl-js/api/#mapon

but it should be:
https://www.mapbox.com/mapbox-gl-js/api/#map#on

https://github.com/mapbox/mapbox-gl-js/blob/744adc7e4db29384c5ebe4e109657239dcb01b55/src/ui/events.js#L340

**Comment by andrewharvey** [comment] 2018-07-02 04:01
thanks @pathmapper this looks like a duplicate of #4568, so I'm closing this to keep the discussion together.

**Closed by andrewharvey** 2018-07-02 04:01 UTC
