### ISSUE TITLE
Style fill-pattern does not switch based on feature-state

### ISSUE THREAD

**Issue by justenPalmer** [mapbox/mapbox-gl-js#7526] opened 2018-10-31 21:11 UTC
When using fill-pattern expressions, the resulting fill does not correctly switch based on feature-state.

**mapbox-gl-js version**: 50.0

**browser**: Chrome  69.0.3497.100

### Steps to Trigger Behavior

 1. Create a layer with a fill-pattern expression which switches based on feature-state
 2. Set the feature-state for a visible feature
 3. Observe that the fill-pattern does not change for the feature

### Link to Demonstration

In the above example, there are two layers which switch style based on feature state from the same source-layer. The first has the expression in "line-color" which works as intended. The second has a "fill-pattern" with the exact same logic, but does not execute correctly.

https://jsbin.com/qidikopure/edit?html,output

### Expected Behavior

The feature with the set state should appear with a diagonal red line pattern

### Actual Behavior

The feature with the set state has the default dotted pattern

**Comment by asheemmamoowala** [comment] 2018-10-31 21:16
Duplicate of #7207

**Closed by asheemmamoowala** 2018-10-31 21:16 UTC
