### ISSUE TITLE
Support epsg:4326

### ISSUE THREAD

**Issue by KfirShainholtz** [mapbox/mapbox-gl-js#4296] opened 2017-02-19 08:35 UTC
Hey guys, 
I saw from earlier issues that you so support other projections, 
But didn't find its use at the api section, 
Is that feature enabled? Specifically for epsg:4326 

Thanks in advance

**Comment by KfirShainholtz** [comment] 2017-02-19 12:27
By projections, I meant coordinate systems (probably)

**Comment by jingsam** [comment] 2017-02-20 03:40
EPSG:4326 === WGS84

**Comment by lucaswoj** [comment] 2017-02-20 18:42
Duplicate of #3184

**Closed by lucaswoj** 2017-02-20 18:42 UTC

**Comment by KfirShainholtz** [comment] 2017-02-21 08:51
Let me put it another way,
for the raster tiles, i could (and do) use epsg:900913,
but for the actual data i'm projecting, i'm using epsg:4236

The reliability of the actual positions and area of the polygons
that are projected is very important, and is the core usage for my application;
I haven't checked it yet, but lets say, if I'm projecting a polygon on a mounty area,
which recieved at EPSG:4236, and projected in that ellipsoide manner, but on a 900913 raster tile,
does it make a difference? or that stuff is being thought-through at the rendering stage?

Thank you so much for everything guys

**Comment by kkaefer** [comment] 2017-02-22 11:30
Mapbox GL JS only supports Web Mercator/EPSG:900913, so you'll have to reproject other coordinate systems. When rendering EPSG:4326, you'll have a similar issue in that direct lines in that projection don't reflect the actual path as the crow flies. If you need these paths, you'll have to create intermediate points yourself, e.g. with something like [cheap ruler](https://www.mapbox.com/blog/cheap-ruler/) or [arc.js](https://github.com/springmeyer/arc.js/)

**Comment by exotfboy** [comment] 2017-06-08 00:48
I am not sure what's going on for this projection problem, I searched the issue, lots of people asked for this feature which is nicely supported in Openlayers, Leaflet and etc. As a mapping library with almost 2k stars, it is strange that some common concepts like `projection` `crs` are not supported.

I guess if this project is hosted by mapbox company whose most important assets are data with `3857` projection, they can not benefits from `mapbox-gl-js` unless the api and the data are bound together.

If true, I do not think `mapbox-gl-js` will support custom projection in the future. So people who need cusotm project may make a fork and customize it by yourself.

Anyway, `mapbox-gl-js` is a wonder library and `mapbox` is the most open geographic  company as far as I know.

**Comment by hy31337** [comment] 2021-04-30 06:47
> 我不确定这个投影问题是怎么回事，我搜索了这个问题，很多人都要求此功能，Openlayers，Leaflet等已很好地支持此功能。作为一个拥有近2k星的映射库，奇怪的是，一些常见的`projection` `crs`不支持类似的概念。
> 
> 我想如果该项目由mapbox公司托管，而该公司最重要的资产是带有`3857`投影的数据，`mapbox-gl-js`除非将api和数据绑定在一起，否则它们将无法从中受益。
> 
> 如果为真，我认为`mapbox-gl-js`将来将不支持自定义投影。因此，需要cusotm项目的人可以自己制作一个叉子并对其进行自定义。
> 
> 无论如何，这`mapbox-gl-js`是一个奇迹图书馆，`mapbox`据我所知是最开放的地理公司。



> I am not sure what's going on for this projection problem, I searched the issue, lots of people asked for this feature which is nicely supported in Openlayers, Leaflet and etc. As a mapping library with almost 2k stars, it is strange that some common concepts like `projection` `crs` are not supported.
> 
> I guess if this project is hosted by mapbox company whose most important assets are data with `3857` projection, they can not benefits from `mapbox-gl-js` unless the api and the data are bound together.
> 
> If true, I do not think `mapbox-gl-js` will support custom projection in the future. So people who need cusotm project may make a fork and customize it by yourself.
> 
> Anyway, `mapbox-gl-js` is a wonder library and `mapbox` is the most open geographic company as far as I know.

Hey, how did you solve the problem? Can you please share?
