### ISSUE TITLE
On demand images loading

### ISSUE THREAD

**Issue by NatonVanCliff** [mapbox/mapbox-gl-js#7206] opened 2018-08-27 17:48 UTC
Current Map API requires that all images should be loaded/added to the map before using them in style definitions. It works fine when all images that could potentially be encountered on particular layers are known in advance.

But in our case we don't known all images that might be required, so we cannot add them in advance. There are actually several complications in our case, as described below:
1.	There is a tile service that provides a set of tiles with image URLs specified in features metadata, like:
```
          'properties': {
            'icon': 'http://example.com/icon.png'
          }
``` 
Here already, we don’t know in advance all set of possible image URL’s that we could encounter and cannot add images beforehand.
2.	To make things worse, we need to modify icons depending on value of some other metadata, e.g. add colored background and/or badges to the images, depending on value of some other metadata. Again, we don’t know set of all possible values that we could encounter and could not generate and add all required images in advance. 

We have found a workaround that works by redefining the function `Style.getImages()` in Mapbox sources. Here’s a JSFiddle illustrating the approach: [On-demand loading of icons](https://jsfiddle.net/naton_van_cliff/hxzq129d/)

Could you please help us to understand:
1.	Are there any side effects for this solution (other than the obvious- that it is very fragile and could break on any future version of mapbox-gl-js)?
2.	Are there any plans to add ability to load/generate images on demand in the public API?

### Proposal for public API:
Here’s my take at how public API for on-demand image loading, that would allow covering our cases, could look like.
Add the ability to specify async callback for loading of pictures on demand in the map option:
```
ImageLoadingCallback {
load(imageId: string, map: mapboxgl.Map): Promise<void>;
}
```

**On initialization:**
```
var map = new mapboxgl.Map({
container: 'map',
style: {
    'version': 8,
    'sources': { },
    'layers': []
    'imageLoader ':  new ImageLoadingCallback(); // or default implementation
  }
});
```
 
**Implemetation of method getImages**:
```
// imageLoader - the callback, specified in map options

mapboxgl.Style.getImages = function(mapId, params, callback) {
const map = this.map;
constimagePromises = [];

    // makes loading for each icon
params.icons.forEach(function(imageId) {
imagePromises.push(imageLoader.load(imageId, map));
    });

constimageManager = this.imageManager;
    // waits all promises (all requests for loading images)
Promise.all(imagePromises).then(function() {
        // old implimentation of funcStyle.getImages
imageManager.getImages(params.icons, callback);
});
};
```

**Comment by mollymerp** [comment] 2018-08-27 20:49
Hi @NatonVanCliff, thank you for using Mapbox.
Is there a reason why you can't use the existing async API for loading images for this use case? `Map#loadImage` and `Map#addImage`

https://www.mapbox.com/mapbox-gl-js/example/add-image/

**Comment by NatonVanCliff** [comment] 2018-08-28 08:14
Hi,
In our project, we don’t know in advance all set of possible image URL’s that comes in set of tiles. Thats why, we cannot add images beforehand using `Map#loadImage`, `Map#addImage`.
It is most preferable for us to load images on demand via some IoC mechanism.

**Comment by NatonVanCliff** [comment] 2018-08-28 10:27
Just to be clear, our request is about on-demand loading of images, not about async loading.
True, images could be loaded using existing async API loadImage, but with existing API they should be loaded and added to the map before they could be used as part of layer style (https://www.mapbox.com/mapbox-gl-js/example/add-image/ illustrates this).
Using the example above, what we would like to do is specify "icon-image": "cat" in the style for the layer before adding image to the map and have Mapbox call some kind of image loader (registered on the map beforehand), asking for the image with id "cat" once the actual icon with icon-image "cat" is encountered for the first time. This of course looks silly for simple static style, but makes much more sense with data-driven styling.

**Comment by mollymerp** [comment] 2018-09-05 20:09
Ok, thanks for clarifying – can you confirm whether this is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/6231 ?

**Comment by NatonVanCliff** [comment] 2018-09-10 17:02
Yes, it’s the same problem

**Comment by mollymerp** [comment] 2018-09-10 21:37
Ok, thanks. I'm going to close this issue to concentrate discussion over there.

**Closed by mollymerp** 2018-09-10 21:37 UTC
Labels: needs information :pray:

**Comment by mjcc007** [comment] 2018-09-21 05:28
Has this problem been solved?
