### ISSUE TITLE
iOS 15 Safari tab bar interrupts map interactions

### ISSUE THREAD

**Issue by stephenheron** [mapbox/mapbox-gl-js#11048] opened 2021-09-22 19:30 UTC
Hi,

We are seeing some funny behaviour in iOS 15 when attempting to move the map vertically. It seems when attempting to pan vertically it triggers the address bar in iOS 15 to show/hide and it stops the map pan. I have attached a a video showing the issue. This is from a simulator but we are also seeing the issue on real devices. 

https://user-images.githubusercontent.com/142855/134409199-8027cd9e-dba8-4163-9d7e-a2ad6d0c36a7.mov

We are still debugging on this end so I am not 100% sure if it is a Mapbox issue or something we have done. Just flagging early in the hopes someone else may have seen something similar.

Thanks,
Stephen

**Comment by stephenheron** [comment] 2021-09-22 20:39
A wee update, I stripped back our site until it was basically just a a shell and it was still happening. I took that shell and popped it on a JSBin https://jsbin.com/tubitov/edit?html,output as it is still happening. 

Strangely when I look at your example site (https://docs.mapbox.com/mapbox-gl-js/example/simple-map/) it doesn't seem to happen. The address bar appears/disappears but it doesn't result in the sort of hitching I get on my site and in the bin.

**Comment by rreusser** [comment] 2021-09-22 22:30
Unless I'm mistaken, I think this is the same issue, and I think Apple has reverted the floating bottom bar since it's awful. Here's one person at least who spent a whole day debugging it, only to realize it's been removed for non-beta:

https://twitter.com/cmiller__/status/1427849922649407495

**Comment by ryanhamley** [comment] 2021-09-22 22:50
I believe the address bar is still at the bottom by default, it's just [no longer floating](https://techcrunch.com/2021/08/18/apple-walks-back-controversial-safari-changes-with-ios-15-beta-6-update/). That same Twitter thread [shows that the unexpected UX is still happening](https://twitter.com/cmiller__/status/1428513380441145344?s=20). iOS 15 appears to be generally available as of September 20th. I see an option on my phone to upgrade to it.

**Comment by avpeery** [comment] 2021-09-22 23:01
Hi all, I upgraded my phone to iOS15 and can confirm that the address bar is at the bottom, and not floating or hiding. @ryanhamley the twitter comment appears to be from August 19th, before the release September 20th, so possible changes since then in regards to not have the address bar floating anymore.

@stephenheron, thanks so much for submitting this issue and including a jsbin. I tested out panning and scrolling on your jsbin with my iOS device after updating to iOS15 this afternoon, and have not yet reproduced this problem. Though it seems to be an iOS15 update-wide issue across different applications.

**Comment by stephenheron** [comment] 2021-09-23 07:09
Hi @avpeery 

Thanks for having a look! I just had a look at the link I sent you and I couldn't replicate it either which was strange. Until I looked at the jsbin directly (Not in edit mode and it happened). 

Could. you try this link: https://jsbin.com/tubitov/ and see if you can replicate?

I am also wondering if screen size has an effect, I am on and iPhone 12. 

Thanks,
Stephen

**Comment by rreusser** [comment] 2021-09-23 22:10
I'm seeing the same behavior in public iOS 15. I modified Caleb Miller's codepen to add lots of stopPropagation and preventDefaults on touchstart, touchmove, touchend, and mousedown, but I'm still seeing the same issue. This is fairly surprising.

https://codepen.io/rsreusser/pen/RwgYjKV

**Comment by leigeber** [comment] 2021-10-03 17:52
In our version of this iOS 15 issue our map fills the viewport and the bottom placement isn't problematic but if you opt to have the bar up top then everything falls apart as you pan around with drawers constantly opening and closing. Seems like a fundamental issue with how Safari is propagating events from the Mapbox canvas.

Huge issue for us right now being a real estate application.

**Comment by stephenheron** [comment] 2021-10-04 08:40
@leigeber Yeah I just changed Safari to the top bar and it still feels very odd. Panning left/right even seems strange and sometimes it tries to take back a page. 

@avpeery is there any progress on someone having a look at this? I had a look at the code but I can't really figure our what is going on.

**Comment by rreusser** [comment] 2021-10-04 18:43
@stephenheron I do now see the issue you're talking about in your codepen, in which the map stops panning. I think it didn't immediately register because the [basic mapbox examples](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/) _do not_ exhibit this issue. The only difference I can see is that the examples are in an iframe. Wrapping your example in an iframe does seem to work around the panning being halted, though it doesn't stop the address bar from hiding/showing.

Here's where I'm at on the issue:
- The fact that it's impossible to prevent events from affecting the address bar seems like a significant bug on Apple's part. Here's a simple codepen that throws every prevent default, stop propagation, and pointer capture I can think of at the problem, with no effect: https://codepen.io/rsreusser/full/mdwYNNe
- The fact that maps without an iframe halt when panned may be an apple bug in which events stop arriving, or it may be a Mapbox bug for some yet-unknown reason. I haven't gotten to the bottom of this yet. One workaround is to place the map in an iframe, though this is obviously not ideal.

We are indeed looking into this, and I'll keep this ticket updated with any new information we find.

**Comment by rreusser** [comment] 2021-10-04 19:17
Here's a small update:

For debugging, here's a simple page for demonstrating the interrupted-pan issue within the mapbox-gl-js repo:

<details>
<summary>debug/issue-11048.html</summary>

    <!DOCTYPE html>
    <html>
    <head>
        <title>Mapbox GL JS debug page</title>
        <meta charset='utf-8'>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <link rel='stylesheet' href='../dist/mapbox-gl.css' />
        <style>
            body { margin: 0; padding: 0; }
            html, body, #map { height: 100%; }
        </style>
    </head>

    <body>
    <div style="min-height: 60vh"><div id="map" style="width: 300px; height: 300px"></div> <div>

    Lucas ipsum dolor sit amet obi-wan skywalker solo jango jade grievous jango organa darth obi-wan. Tatooine gamorrean droid dantooine darth moff. Greedo leia darth maul jar r2-d2 jar secura hutt. Jabba mace cade palpatine. Ventress luke zabrak yoda lando organa mon hutt. Padmé skywalker calrissian moff. Antilles moff hoth moff jinn yavin maul. Hutt baba skywalker moff kenobi leia calrissian skywalker. Wookiee mothma binks boba ewok leia. Antilles palpatine jade jade jinn bespin sebulba. Kashyyyk yavin skywalker endor ackbar wedge calamari calamari cade.

    Dagobah coruscant obi-wan moff ben kashyyyk antilles. C-3po yoda lars amidala mandalorians jabba antilles skywalker. Yoda dagobah amidala dantooine coruscant anakin. Utapau windu watto lando tatooine ben kenobi. Darth mandalore skywalker binks baba cade calrissian. Alderaan han maul anakin moff anakin. Vader naboo jinn moff aayla windu. Antilles secura ackbar hutt ackbar gonk. Organa moff jade skywalker r2-d2 wampa. Darth cade skywalker mandalore. Cade hutt maul calrissian. Tatooine jade organa yoda lando ackbar obi-wan coruscant obi-wan.

    Dantooine solo owen coruscant moff windu organa moff. Wedge biggs coruscant hutt hutt lando mothma. Biggs solo lars secura dagobah. Jinn antilles tatooine jawa padmé skywalker antilles. Skywalker greedo jawa mon k-3po. Yoda mace lando c-3p0 sidious hutt mara chewbacca dagobah. Mon solo naboo yoda kamino wedge gonk. Ahsoka bothan calamari calrissian gamorrean. Baba kamino mace sith mon kit antilles. Jabba antilles yoda c-3po maul hutt solo. Antilles coruscant biggs darth skywalker. Boba skywalker wedge mustafar organa.

    Mon mara luke fisto. Padmé grievous coruscant jango darth darth padmé hutt kessel. K-3po chewbacca k-3po moff cade tusken raider ahsoka palpatine. Moff vader moff jar bothan hutt. Obi-wan cade kenobi grievous skywalker hutt. Moff utapau kit darth owen wookiee kenobi jinn. Ben darth luuke ponda gamorrean hutt leia sebulba fett. Sidious organa twi'lek organa kessel. Tusken raider antilles boba jango dantooine. Binks antilles calrissian yavin mandalorians kessel ackbar. Hoth padmé antilles jango windu.

    Fett yavin aayla lando amidala. Grievous darth palpatine darth. Skywalker skywalker biggs jawa windu antilles jabba moff mon. Dagobah moff windu bothan. Skywalker moff padmé fisto jango darth ventress mothma. Organa moff moff yavin alderaan. Skywalker calrissian skywalker mustafar skywalker twi'lek. Jawa sith calamari solo moff moff ackbar. Ben endor kessel aayla. Solo lando thrawn amidala dooku qui-gonn binks. Skywalker hutt yoda dooku obi-wan sidious grievous coruscant jango. Skywalker aayla moff solo ewok anakin yoda dagobah dooku.

    <script src='../dist/mapbox-gl-dev.js'></script>
    <script src='../debug/access_token_generated.js'></script>
    <script>

    var map = window.map = new mapboxgl.Map({
        container: 'map',
        zoom: 12.5,
        center: [-122.4194, 37.7749],
        style: 'mapbox://styles/mapbox/streets-v11',
        hash: true
    });

    </script>

    </html>

</summary>

The behavior I'm seeing is that new in iOS 15, Safari fires _some not-yet-known event_ whenever the tab bar moves during hide/show. This event somehow invokes [`touchPanHandler.reset()`](https://github.com/mapbox/mapbox-gl-js/blob/f01ad55de2639532b4ee64d0c7aa1d54a2543c87/src/ui/handler/touch_pan.js#L21), which then interrupts the pan, even though subsequent touchmove events are still received (and discarded).

This means the interrupted-pan issue can be fixed, but I don't have a cord available to be able to use the Safari debugger, making fully nailing this down much more difficult. The goal at this point seems to be to determine what's invoking `touchPanHandler.reset()`.

**Comment by LowSociety** [comment] 2021-10-04 19:59
Isn't it simply the fact that iOS 15 now alters the hight of the viewport regardless of whether the touch event triggers scrolling (ie even if it's `preventDefault`) thus triggering a `resize` event on the window? The `resize` event then probably triggers a `reset` which in turn stops the panning. You can simulate this on a desktop by triggering a fake resize event while panning, with the exact same behavior:

```
window.setInterval(function() {
    window.dispatchEvent(new Event("resize", {"bubbles":true, "cancelable":false}));
}, 5000);
```

**Comment by rreusser** [comment] 2021-10-04 20:36
@LowSociety You're exactly correct. [`trackResize`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map-parameters) is a map constructor option and defaults to true. If you set this to `false`, then the halting of panning should go away. If your map uses up the whole viewport and _requires_ resizing on every window resize event, then things aren't quite as simple.

- If your map is a fixed size on a page and doesn't need to be resized every time the window resizes, setting `trackResize: false` will fix the issue.
- If your map needs to be resized when the window resizes, then it's not so simple. We're looking at caching the dimensions and more aggressively filtering resize events before they interrupt interactions. This would improve the situation.
- If your map is fixed (or absolute) positioned to the whole viewport size, then it may actually change size so that caching dimensions wouldn't help anything (because they're actually changing). I don't yet know a solution for this case.

**Comment by LowSociety** [comment] 2021-10-04 20:49
Thanks for the info @rreusser! As a workaround to other problems caused by this iOS update I've been deferring resize events to the end of user interaction. For example if the user is dragging something across the screen, I don't recalculate offsets on resize until after the user has stopped dragging. Of course, this only works if the calculations are not already inherently tied to the viewport size via something like css percentages/vh/vw but it makes me wonder if there really are times where a resize/reset needs to be triggered _during_ panning? Isn't it essentially the equivalent of rotating your screen while panning the map, which already would cause a reset before the iOS update anyway?

**Comment by rreusser** [comment] 2021-10-04 21:02
Yup, I think that's just it, @LowSociety. All previous resize events were either mutually exclusive with map interactions (e.g. resizing the window with the mouse), or you had no reasonable expectation to continue the map interaction uninterrupted (e.g. rotating the device during panning). This is the first time in which resize events arrive during completely normal map interactions.

I suspect that we might be able to simply skip halting of interactions on resize. It's might produce jumpy interactions for completely contrived cases (like panning during device rotation), but it would perhaps solve this for more cases than filtering resize events.

**Closed** 2021-10-05 21:56 UTC
Labels: bug :lady_beetle:, environment-specific :desktop_computer:
