### ISSUE TITLE
Transparent pixels of a raster source rendered as black in Safari

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#8186] opened 2019-04-24 17:38 UTC
**mapbox-gl-js version**: v0.53.0, master
**browser**: Safari 12.1 & TP / Mac

We did a fix for this in #7817 but apparently this has either regressed in a newer version of Safari, or in GL JS after the PR.

### Steps to Trigger Behavior

Use a raster source with transparent parts.

### Link to Demonstration

https://docs.mapbox.com/mapbox-gl-js/example/adjust-layer-opacity/

### Expected Behavior

Image rendered without issues.

### Actual Behavior

Transparent pixels are rendered as black.

**Comment by ryanhamley** [comment] 2019-04-24 19:29
This is unrelated to #7817 which was about mistakenly serving WebP files to browsers that don't support the format. In this case, the issue is that Safari does not support WebP and we're falling back to JPGs which don't support transparency. The format of the images is determined on the API side. Since we can't determine which requests need PNG for transparency, the only potential resolution on the client side is to always request PNG instead of JPG on the client side. This may incur unknown (at this time) costs and problems so any move towards this solution would need to be coordinated with the API team. In my opinion, for the foreseeable future, this is likely a `won't fix` and we'll hope Safari implements WebP support in the future.

**Closed by ryanhamley** 2019-04-24 19:29 UTC
Labels: bug :beetle:, environment-specific :desktop_computer:

**Comment by mourner** [comment] 2019-04-24 20:20
@ryanhamley thanks for looking into this! Can we manually set the example to always request `png`?

**Comment by ryanhamley** [comment] 2019-04-24 22:52
The source URL is just `mapbox://mapbox.u8yyzaor` which gets translated on the API side into a full URL with the `.jpg` extension. My understanding is that the API would either have to respond with a PNG or we'd have to change the source URL to point directly to a PNG. I think we could use an expanded URL but I'm not sure that's what we'd want to do for an example since it's not really what we'd expect out of normal usage.
