### ISSUE TITLE
Replacement of fast-stable-stringify causes IE11 error

### ISSUE THREAD

**Issue by sroettering** [mapbox/mapbox-gl-js#5590] opened 2017-11-03 07:22 UTC
Internet Explorer throws an error when I add layers to a map. The error comes from a call to Object.keys() which is implemented slightly different in IE. According to this [Stackoverflow](https://stackoverflow.com/questions/31917961/object-keys-behavior-in-chrome-and-ie-11#answer-31919087) thread the IE version of Object.keys() throws a type error if a non-object is passed as an argument.

**mapbox-gl-js version**: 0.40.0

### Steps to Trigger Behavior

 1. Open IE11
 2. Call the new stringify function in /src/style-spec/group_by_layout.js

### Expected Behavior
No error thrown

### Actual Behavior
Error thrown: Object.keys: argument is not an Object

**Comment by jfirebaugh** [comment] 2017-11-03 14:58
Duplicate of #5312. This was fixed in 0.40.1.

**Closed by jfirebaugh** 2017-11-03 14:58 UTC
Labels: bug, environment-specific bug
