### ISSUE TITLE
Baltic sea dries out on zoom

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2657] opened 2016-06-02 20:47 UTC
**mapbox-gl-js version**: 0.19.0 (tested on Chrome, Safari and Firefox on OSX)

### Steps to Trigger Behavior
 1. Goto https://www.mapbox.com/mapbox-gl-js/examples/ (Display a map)
 2. Zoom out and pan over to The Gulf of Bothnia (the sea between Sweden and Finland)
 3. Zoom in

### Expected Behavior
Normal rendering.

### Actual Behavior
At about zoom level 8-10 The Baltic sea polygon disappears and the background shows instead.

This might be an earcut issue since it does not seem to be present in 0.18.0.

**Comment by mourner** [comment] 2016-06-02 22:04
Oh no! Confirmed and investigating the issue.

**Comment by mourner** [comment] 2016-06-02 22:36
@averas should be fixed by https://github.com/mapbox/mapbox-gl-js/pull/2659. The bug is caused by a funny typo. 💩 I think we'll do a hotfix release with the patch.

**Closed** 2016-06-02 22:45 UTC
Labels: bug, release blocker
