### ISSUE TITLE
style, “match”,to set "fill-color" 

### ISSUE THREAD

**Issue by yangjnMapBox** [mapbox/mapbox-gl-js#8469] opened 2019-07-12 06:57 UTC
![image](https://user-images.githubusercontent.com/44802474/61108295-855c5480-a4b4-11e9-9d79-7173a4cb7fc5.png)
![image](https://user-images.githubusercontent.com/44802474/61108397-c8b6c300-a4b4-11e9-84e3-d9b2871c5b4d.png)
![image](https://user-images.githubusercontent.com/44802474/61108454-e5eb9180-a4b4-11e9-9190-34ea231d0c12.png)
![image](https://user-images.githubusercontent.com/44802474/61108592-47abfb80-a4b5-11e9-8f37-03ac97d29c27.png)

**Comment by ryanhamley** [comment] 2019-07-12 18:30
Unfortunately, there's not enough here for us to help. Please fill out the bug report template in its entirety. At the very least, a minimal reproduction of the issue you're facing would help a lot. It's also not 100% clear from your screen shots what the issue is. Is the first screen shot the way the map should look? A quick glance at your `fill-color` expression seems like it should work fine, so you may need to ensure that your source layer has a property `orderid` and everything is set up correctly. I'm going to close this for now but if you can create a minimal example that you think shows a bug, feel free to post it here and we can reopen the ticket. If you just need general support, you can contact Mapbox Support.

**Closed by ryanhamley** 2019-07-12 18:30 UTC

**Comment by yangjnMapBox** [comment] 2019-07-15 01:05
White polygon include green polygon,and they are from one source.when i use "match" to set them "fill-color",the green polygon only show green boundary.
