### ISSUE TITLE
raster tiles are not cached (This may be a cache issue !)

### ISSUE THREAD

**Issue by MostafaSh** [mapbox/mapbox-gl-js#10031] opened 2020-10-14 16:17 UTC
Hi !
I'll make it short

- I found some performance isuues loading my raster tiles, while I didn't faced such problems with openLayers.
- I checked mapbox-gl-js source and found out that:

  - in a method named **setExpiryData**  in **tile.js** there are some actions related to caching tiles. it has an entry named **data**. and data has no **cacheControl** or **expires** in its members ( while I have both of them in response headers).

  - I followed the code and found out there is a function named **getImage** in **ajax.js** that handles loading images. in line **352** there is a condition that chooses one of these functions : **arrayBufferToImageBitmap** or **arrayBufferToImage**.

  - in **arrayBufferToImage**, **cacheControl** and **expires** are passed into data, but this is not happening in **arrayBufferToImageBitmap**.

so I am not sure it's some issue with my raster tile images or it is a simple mistake in writing mapbox-gl-js code. so I decided to mention the problem there. i thought as a simple result I may be able to help this open source project, or even if i was wrong I can learn more.

so if I am wrong and this is not a bug, I apologize that wasted your time

**Comment by maihde** [comment] 2021-04-13 21:40
I believe this is a bug as well; in my case I want my raster tiles to expire and noticed that no matter what cache control headers I set the tile.expirationTime would never be correct.

Like @MostafaSh found, the issue is that `arrayBufferToImage` fails to use `cacheControl` and `expires`.  The fix was pretty simple:

```
-+arrayBufferToImageBitmap(data, callback);
+arrayBufferToImageBitmap(data, callback, cacheControl, expires);
```

And 
``` 
-function arrayBufferToImageBitmap(data, callback) {
+function arrayBufferToImageBitmap(data, callback, cacheControl, expires) {
    var blob = new window$1.Blob([new Uint8Array(data)], { type: 'image/png' });
    window$1.createImageBitmap(blob).then(function (imgBitmap) {
+        imgBitmap.cacheControl = cacheControl;
+        imgBitmap.expires = expires;
        callback(null, imgBitmap);
    }).catch(function (e) {
        callback(new Error('Could not load image because of ' + e.message + '. Please make sure to use a supported image type such as PNG or JPEG. Note that SVGs are not supported.'));
    });
}
```

**Comment by maihde** [comment] 2021-04-14 14:11
After further investigation, this appears to have been fixed in https://github.com/mapbox/mapbox-gl-js/pull/10494

**Closed** 2021-04-14 17:40 UTC
Labels: bug :beetle:
