### ISSUE TITLE
Mouse scroll to zoom does not work when pointer over popup

### ISSUE THREAD

**Issue by danpat** [mapbox/mapbox-gl-js#1299] opened 2015-06-19 17:39 UTC
Popups seem to be capturing mouse scroll events, map does not zoom when mouse wheel is scrolled and pointer is over the popup.  Feels non-intuitive.

Version 0.8.1
Browser: chrome 44.0.2403.39 beta on OSX

**Comment by jfirebaugh** [comment] 2015-06-19 17:50
Duplicate of #1280.

**Closed by jfirebaugh** 2015-06-19 17:50 UTC
