### ISSUE TITLE
"Expected an even number of arguments" message confusing

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#9307] opened 2020-02-19 01:26 UTC
I have been confused by this message many times.

`Error: "layers.points-circles.paint.circle-color: Expected an even number of arguments."`

This part of the style definition looks like this:

```
'circle-color': ['match', ['get', 'Category'],
  'Repair cafe', 'hsl(330,100%,40%)',
  'Tool library', 'hsl(210,100%,40%)']
```

The confusing part is I count the number of elements in the array that is the value for `circle-color`, and it's 6, which is even. I eventually realise that it's saying the number of arguments to the *match* expression must be even...but `match` doesn't appear anywhere in the error message.

So could I suggest either of these changes:

* `Error: "layers.points-circles.paint.circle-color.match: Expected an even number of arguments."`
* `Error: "layers.points-circles.paint.circle-color: Expected an even number of arguments to 'match'."`

(It's also somewhat confusing in that I don't really understand why `match` requires a fallback case. I'd be happy with it just returning `null` or something. My cases generally cover all the possibilities in my data, so it's just...annoying...having to think of a value for a situation which will never happen.)

**Comment by asheemmamoowala** [comment] 2020-02-21 23:15
Closing as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/6437

**Closed by asheemmamoowala** 2020-02-21 23:16 UTC
Labels: api :memo:
