### ISSUE TITLE
Loading local .pbf-Files in iOS

### ISSUE THREAD

**Issue by LaermTot** [mapbox/mapbox-gl-js#5014] opened 2017-07-21 09:46 UTC
I am trying to load local .pbf-Files in iOS but the Schema for the Tiles (see below) does not work. (Android & Browser work fine).

```
"mapbox-streets": {
  "type": "vector",
  "tiles": [
    "/var/foo/bar/..../{z}/{x}/{y}.pbf"
  ],
  "maxzoom": 14
}
```

It seems that iOS can "load" the corresponding files, but they seem to be empty .. I am not sure .. but it seems that the actual Files are being called  
**"/var/foo/bar/..../14/66/4444.pbf" - > 9349r534-3333-333-44-5-6** 
via window.resolveLocalFileSystemURL(...) ... 

Is there any way of making MapBoxGL-js to use  window.resolveLocalFileSystemURL to load the Tiles ?

Thanx in Advance

**Comment by anandthakker** [comment] 2017-07-21 12:11
Duplicate of #4917

**Closed by anandthakker** 2017-07-21 12:11 UTC
