### ISSUE TITLE
Unexpected behavior first time calling map.dragPan.disable() inside mousedown handler

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#2713] opened 2016-06-10 15:32 UTC
**mapbox-gl-js version**: 0.19.1

### Steps to Trigger Behavior

 1. Call `map.dragPan.disable()` inside `map.on(mousedown, ...)` event handler.
 2. Click + drag the map

Js fiddle here: https://jsfiddle.net/mzvhkLvs/

### Expected Behavior

Map doesn't drag.

### Actual Behavior

Map drags, but only the first time.

**Comment by kristfal** [comment] 2016-06-10 15:37
Hey, this is a dupe of #2419. There is a workaround in that bug-report as well.

**Comment by mourner** [comment] 2016-06-10 15:43
@kristfal you're right, thanks for noting this! Closing as duplicate.

**Closed by mourner** 2016-06-10 15:43 UTC
Labels: bug
