### ISSUE TITLE
Large polygon gets clipped at some zoom levels

### ISSUE THREAD

**Issue by gingemonster** [mapbox/mapbox-gl-js#7663] opened 2018-12-03 16:29 UTC
Hi

I am having issues drawing a polygon from geojson. At some zoom levels the polygon gets clipped (presumably along tile boundaries) for example:

![image](https://user-images.githubusercontent.com/703352/49386887-76404780-f718-11e8-8c31-67ef9fe8849a.png)

Here is a code example of this, super simplified. 

https://gist.github.com/gingemonster/3e7944825d2ae6588066d49136ff1ee1 

Obviously the JSON is large and should be optimised but equally this seems to be a bug?

**Comment by mourner** [comment] 2018-12-03 16:51
Yes, this is likely a duplicate of #7023

**Closed by mourner** 2018-12-03 16:51 UTC
