### ISSUE TITLE
Glyph overflow

### ISSUE THREAD

**Issue by haoshengfucn** [mapbox/mapbox-gl-js#2632] opened 2016-05-30 09:19 UTC
in the glyph_source.js, the glyph bitmap is 512X512，in the english languages countries, it is ok. but  if switch to china, 512X512 is not enought. "glyph bitmap overflow" happens.

**Comment by haoshengfucn** [comment] 2016-05-30 09:20
in the glyph_source.js, the glyph bitmap is 512X512，in the english languages countries, it is ok. but if switch to china, 512X512 is not enought. "glyph bitmap overflow" happens.

**Comment by jingsam** [comment] 2016-05-30 09:46
A glyph bitmap only have 255 glyph, so I think 512X512 is big enough to support 255 Chinese characters. One font will be split into multiple  glyph bitmaps, such as 0-255, 256-512...

**Comment by 1ec5** [comment] 2016-05-30 16:51
Duplicate of #1681.

**Comment by 1ec5** [comment] 2016-05-30 16:52
Whoops, I was thinking of mapbox/mapbox-gl-native#1681, which is the same issue in the Mapbox iOS and Android SDKs. Sorry for the confusion.

**Comment by jfirebaugh** [comment] 2016-05-31 15:55
Duplicate of #141.

**Closed by jfirebaugh** 2016-05-31 15:55 UTC
