### ISSUE TITLE
Fix bug causing clusters to disappear when "clusterRadius" is very small

### ISSUE THREAD

**Issue by icreatestuff** [mapbox/mapbox-gl-js#2898] opened 2016-07-20 09:40 UTC
**mapbox-gl-js version**: 0.21.0
### Steps to Trigger Behavior

Add a Map source with options ([https://www.mapbox.com/mapbox-gl-js/api/#GeoJSONSource](https://www.mapbox.com/mapbox-gl-js/api/#GeoJSONSource)):

```
{
type: 'geojson',
data: GeoJSONdata,
maxzoom: 20,
cluster: true,
clusterMaxZoom: 20,
clusterRadius: 1
}
```

doesn't produce the expected outcome.
### Expected Behavior

I would expect that cluster layers using that source remain visible up to and including zoom level 20 (i.e. they never disappear)

The documentation for `cluserMaxZoom` indicates that by default this property is set to 1 less than `maxzoom` but seems to imply that if set explicitly it'll honour that value. From what I can gather it is always returning the lower of the 2 between (`maxzoom` - 1) and what is set for `clusterMaxZoom`.
### Actual Behavior

What I actually see is that some layers disappear at zoom level 19, some at zoom level 18 and some at zoom level 17.

**Comment by mourner** [comment] 2016-07-20 11:02
Can you set up a minimal JSFiddle reproducing the behavior?

**Comment by icreatestuff** [comment] 2016-07-20 12:01
https://jsfiddle.net/vw2qbrxt/

**Comment by mourner** [comment] 2016-07-20 13:51
Yeah, it seems to be a bug and somehow related to small cluster radius — changing the value in JSFiddle to 10 seems to fix the behavior. Needs investigating.

**Comment by sdawson26** [comment] 2017-05-12 15:42
Here's another example relating to heat maps. 
https://jsfiddle.net/6rz6gt9u/3/

I just posted #4710 moments ago and realized this is basically the same issue.

**Comment by GLosch** [comment] 2017-08-10 13:44
Is there an ETA for this being resolved?

**Comment by GLosch** [comment] 2018-01-03 20:42
Got it working in my case, thanks to a tip from the mapbox team. I needed an extra layer for the _un_clustered markers. The problem was that once the clusters tried to separate into individual dots, there wasn't a layer to represent them. Adding a new layer with `filter: ['!has', 'point_count']` took care of it.

**Comment by stevew2511** [comment] 2018-03-26 08:04
mapbox-gl-js version: 0.44.1
chrome version 59.0.3071.86 (64 bit)

Hi, I am having trouble with the cluster function.  It doesn't appear to be adding the 'point_count' attribute to the geojson source that I have added via javascript. For testing purposes I am using the 'earthquakes.geojson' file. It seems that the filter option cannot see the 'point_count' attribute. If I remove the filter I can see the data and everything else works as intended i.e. 'on click' event. The javascript console shows no errors, so I'm not sure if IIS 6.0 is the problem and out of ideas on what to try next. Hope someone can help.

**Comment by GLosch** [comment] 2018-09-26 15:30
@jfhidakatsu see my comment right before yours. Are you having a different issue?

**Comment by jfhidakatsu** [comment] 2018-09-26 15:47
> @jfhidakatsu see my comment right before yours. Are you having a different issue?

Yes, I don't have any issue showing unclustered markers. The issue is showing clusters when zoomed in far. I solved it by setting max zoom to 17.9, as the clusters seem to disappear at 18.

**Comment by hadrienl** [comment] 2019-04-17 15:51
I have the same problem. Cluster breaks after 18 zoom. I have set my global maxzoom to 24, and my clusterMaxZoom to 24, but passed 18 zoom, my points are displayed as superposed single points instead of clusters.

**Comment by yulolimum** [comment] 2020-03-31 02:08
I noticed this as well. Zoom greater than 17.9 - unclusters. 

Related: https://github.com/mapbox/mapbox-gl-js/issues/6454#issuecomment-471313109

**Comment by tomdaniel0x01** [comment] 2020-08-04 00:59
Would be great if this was fixed sometime within the next decade.

**Comment by igal1c0de4n** [comment] 2020-11-17 13:28
+1 waiting on fix for this

**Comment by BellamyTrinette** [comment] 2020-12-09 00:22
+1 would be great to have a fix

**Comment by mourner** [comment] 2020-12-09 12:49
Sorry for the delay everyone, now I'll finally have the time to investigate this soon! Quite a weird issue.

**Comment by mourner** [comment] 2021-01-19 14:49
Finally got my hands on this — check out #10300 and let me know if there are any remaining issues with clustering. The fix should be included in v2.1.

**Closed** 2021-01-22 17:07 UTC
Labels: bug :beetle:, size: small

**Comment by ikhidebright** [comment] 2024-04-21 18:10
This is still an issue for me, when I zoom in I post items in the cluster, on zoom out a cluster would have 23 and then when you zoom it it shows just one item in that cluster

**Comment by barzack** [comment] 2025-03-16 23:46
⚠️ Important Note:
Mapbox's clustering feature does not support GeoJSON MultiPoint geometries directly. If your FeatureCollection includes MultiPoint features, points may unexpectedly disappear or clustering may fail silently.

It would be helpful if Mapbox documented this explicitly to avoid confusion.
