### ISSUE TITLE
[v3.0.0-beta.4] Unable to generate 3D polylines elevated in air 

### ISSUE THREAD

**Issue by sharvashish** [mapbox/mapbox-gl-js#12927] opened 2023-10-09 12:52 UTC
**mapbox-gl-js version**: v3

### Question
I can see many devs have already raised issues for v2, where you cannot draw a 3d polyline elevated from ground. Sadly, it has not been fixed yet. Is the same limitation present in v3 as well? if yes, will it be fixed?

**Comment by mourner** [comment] 2023-10-09 12:56
Yes, v3 doesn't yet implement elevated polylines, but we're still considering this for the future. Meanwhile, the only way to implement something like this is with a CustomLayer or a third-party library like Deck.gl. Closing as a duplicate of #10174

**Closed by mourner** 2023-10-09 12:56 UTC
