### ISSUE TITLE
Add zoom&property function to line-width property

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox-gl-js#4766] opened 2017-05-29 21:18 UTC
Please add zoom&property function to `line-width` property. 
This can help a lot when styling roads or other linear data. 
For now you have to break data down to layers and style with just zoom function, thus trading off ordering at feature level for layer level. This leads to inaccurate styling of overlapping bridges or multilevel tunnels. Main mapbox styles have this issue, which can be cured by adding zoom&property for `line-width` and other data-driven properties.

**Comment by jfirebaugh** [comment] 2017-05-29 21:20
Duplicate of #3045.

**Closed by jfirebaugh** 2017-05-29 21:20 UTC
