### ISSUE TITLE
Override sprites

### ISSUE THREAD

**Issue by JEVietti** [mapbox/mapbox-gl-js#7251] opened 2018-09-07 06:33 UTC
There is currently no way to override the sprite sheet used by the basic mapbox provided styles. Without creating a custom style for each predefined style in mapbox studio or hosting the style yourself. Both of which are cumbersome to keep up to date, especially when using multiple map styles per application.

A solution much like https://www.mapbox.com/mapbox-gl-js/example/local-ideographs/ for sprites where a URL/path is provided that overrides the default would be ideal.

But if there is a current way to dealing with this use case please let me know.

(Note: Why did you guys use a dot instead of the standard pin for marker in your sprite sheets for streets and satellite-streets, all I want is a basic marker shown in the maki general, that in a separate issue is claimed to be in all styles as a part of general?)

**Comment by andrewharvey** [comment] 2018-09-07 09:14
@JEVietti Did you see https://www.mapbox.com/mapbox-gl-js/api/#map#addimage ?

**Comment by JEVietti** [comment] 2018-09-07 15:51
@andrewharvey Are you suggesting that I can use loadimage on a sprites.png(sprite-sheet), and use addImage with an array of objects{width, height, and data}(sprite.json) to replicate the functionality of loading through the sprite property on the style object?

**Comment by jfirebaugh** [comment] 2018-09-07 16:02
This seems like a duplicate of #4804; an `updateImage` API (or allowing `addImage` to overwrite) would be the way we'd support this.

**Closed by jfirebaugh** 2018-09-07 16:02 UTC

**Comment by JEVietti** [comment] 2018-09-07 16:20
@jfirebaugh To be clear I am not requesting the ability to explicitly override sprite images by id, by the title I meant override the sprite sheets being used themselves (not the best choice of title). 

I am looking for a way to add sprites via an external sprite sheet that can have entirely different ids, without loading it through the [sprite property](https://www.mapbox.com/mapbox-gl-js/style-spec/#root-sprite) in the style object. The reason being I would have to host multiple map styles per application for the sake of using a single sprite sheet.
