### ISSUE TITLE
Label collisions

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#4823] opened 2017-06-12 03:32 UTC
I found the label (with text and icon) may collisions sometime once the text is long, see image below:

![image](https://user-images.githubusercontent.com/16457917/27018273-b4e83dcc-4f61-11e7-8a92-b65066984fc7.png)

Any way to fix that?

Furthermore, I found that there are some options for placing a text along with a feature:https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-anchor

However I wonder if it is possible to place the text automatically like google map does:

![image](https://user-images.githubusercontent.com/16457917/27019965-aaca1a5a-4f6f-11e7-9d18-84a864c98686.png)

As the above image shown, some text are placed at the left of the icon, some at the right,bottom,top.

**Comment by ChrisLoer** [comment] 2017-06-12 20:02
Hi @exotfboy, can you provide some sort of interactive example of where you're seeing collisions, like a JSFiddle? Making a label very long on its own shouldn't be enough to trigger label collisions, but there are definitely situations where label collisions can occur (for instance, near tile boundaries, we use an approximation to keep labels from two tiles from colliding with each other). With an interactive example, I might be able to tell what's causing the collisions in your case.

We don't have an "automatic" mode for the `text-anchor` property, although it would be a neat feature to add!

**Comment by exotfboy** [comment] 2017-06-13 01:40
@ChrisLoer I create a live example by [github page](https://exotfboy.github.io/mapbox/index.html)

**Comment by ChrisLoer** [comment] 2017-06-13 19:53
Thanks @exotfboy, that made it very clear what was going on!

I turned on tile debug in the console by executing `map.showTileBoundaries = true;`:

![screenshot 2017-06-13 12 48 00](https://user-images.githubusercontent.com/375121/27101446-a48b8328-5036-11e7-9853-d1734e587d5e.png)

Note that the collisions happen right along the tile boundaries (and in your data set, you have a lot of large labels right next to the boundary). This is tracked as issue #3599 -- it's something we want to fix in core GL JS, but for now using `symbol-avoid-edges: true` may be a workaround. I'm going to close this issue as a duplicate of #3599, but please feel free to file a feature request regarding an "automatic" `text-anchor` property.

**Closed by ChrisLoer** 2017-06-13 19:53 UTC

**Comment by exotfboy** [comment] 2017-06-14 00:04
Hi, thanks for your reply and I got that. Now when you say `symbol-avoid-edges: true` as a workaround, I am not sure where to setup this configuration.
