### ISSUE TITLE
Map#loaded and load event do not provide a reliable way to check if a map is ready for manipulation.  

### ISSUE THREAD

**Issue by facultymatt** [mapbox/mapbox-gl-js#2608] opened 2016-05-23 14:44 UTC
Here is a detailed example: 
https://jsbin.com/vadego/16/edit?js,output

**v0.18.0**:

### Steps to Trigger Behavior

1. Create a map, wait for map to render. 
2. Notice Map `load` event is fired. 
3. Do something which causes the map the reenter loading state such as load geoJson onto the map. 
4. Check if `Map#loaded === true`, it does not so bind function to the map `load` event. 
5. Function is never called 

### Possible solutions 

There are a few ways to address this, ordered roughly in order of disruptiveness:

1. Encourage clients to check `Map._loaded && Map.loaded()` because the `_loaded` property will remain true even when the map reenters loading state.
2. Add another method such as, `Map#hasEverLoaded()` which returns `_loaded` property.  
3. Change the behavior of `Map#loaded` and add a second method `Map#isLoading`.
4. Create a new event, `reloaded` which is fired on subsequent loads. 
5. Fire the map `load` event each time the map finishes loading.

**Comment by jfirebaugh** [comment] 2016-05-23 15:51
Duplicate of #1715 / #2471.

**Closed by jfirebaugh** 2016-05-23 15:51 UTC

**Comment by tkohr** [comment] 2017-10-26 13:32
I have a similar problem using v 40.1. 

Before applying operations (like setFilter, flyTo,... ) to the map where the app can crash I want to check if the map is loaded using map.loaded(), which works fine on initial load of my application, since my check is followed by the map.on('load') event.

Once my app is loaded though, the map can return into a state where map.loaded() returns false (e.g. when manipulating the map, data,...). My problem is, that my check is not followed by a map.on('load') event in this case and my conditional code never gets executed.

When I use the map._loaded attribute instead of the map.loaded() method however, the check if the map is loaded works during AND after initial load of the app. It does not seem to return into a state of returning false after initialization.

Is this supposed to be this way and the map._loaded attribute meant to be accessed directly?

**Comment by adamal** [comment] 2019-02-06 09:25
@jfirebaugh, I don't agree that this is a duplicate of the two others (being slightly pedantic: How could it be, since they are not duplicates of each other?). As a consumer, I think this should be reopened.

This issue is explicitly about the consumer having a "reliable way to check if a map is ready for manipulation". I.e. this is not about knowing whether data is being sent, or any rendering is taking place. This is about knowing when you can begin to manipulate the map in general. Add event handlers. Request changes. Execute queries. Etc.

An example, that doesn't work as intended (equivalent to steps 4 and 5 in original issue):
```
if (map.loaded()) {
    onLoad();
} else {
    map.once('load', onLoad);
}
```

To expand on the findings of the original poster, I tried `console.log`'ing `map.loaded()` and `map.isStyleLoaded()` every 200ms, and logging events `load` and `idle`. It turned out `loaded` and `isStyleLoaded` are both `false` for a while after the `load` event is emitted (perhaps .5s), they are then both `true` for a while (again about .5s) until `idle` is emitted. 

So it _seems_ that we could use `idle`, but it doesn't feel ideal:
In my testing, I'm waiting about a second longer than if I dump all my configuration stuff in the 'load' handler. It might take even longer on low-powered devices.

For future googlers: `'idle'` was added recently (I think version 0.51).

**Comment by TrulsLoug** [comment] 2019-02-21 11:42
Are you able to subscribe to the `isStyleLoaded` with `idle`? I'm currently running a very heavy map with several layers including bigdata. if i dump everything on the `load` handler it currently takes 2-4s on my desktop and closer to 10s on my phone.
