### ISSUE TITLE
Option to toggle the display of compass in navigation.js

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#2389] opened 2016-04-04 19:58 UTC
Particularly helpful when `dragRotate` is disabled but you still wish to have navigation controls. Something like:

```js
map.addControl(new mapboxgl.Navigation({
  compass: false
}));
```

**Comment by jfirebaugh** [comment] 2016-04-04 23:54
Duplicate of #1929.

**Closed by jfirebaugh** 2016-04-04 23:54 UTC
Labels: enhancement
