### ISSUE TITLE
Hash links are not clickable in documentation

### ISSUE THREAD

**Issue by bravecow** [mapbox/mapbox-gl-js#8108] opened 2019-04-02 09:17 UTC
Docs context: _In contrast to Map#queryRenderedFeatures, this function returns_

Where Map#queryRenderedFeatures points to **#mapqueryrenderedfeatures**:

![image](https://user-images.githubusercontent.com/988471/55391083-475ca580-5541-11e9-9e10-824a1fa9e845.png)

But real hash of `queryRenderedFeatures` is **#map#queryrenderedfeatures**:

![image](https://user-images.githubusercontent.com/988471/55391097-4fb4e080-5541-11e9-81ce-914ea3318c47.png)

**Comment by andrewharvey** [comment] 2019-04-02 12:57
I believe this is a duplicate of #4568

**Comment by andrewharvey** [comment] 2019-04-03 09:21
I'll close this to keep this discussion centralised around the existing ticket.

**Closed by andrewharvey** 2019-04-03 09:21 UTC
Labels: docs :scroll:

**Comment by bravecow** [comment] 2019-04-03 09:23
Sure. Thanks. 2 years old. Have never noticed this bug till yesterday 😱
