### ISSUE TITLE
Pinch Zoom in and out not working with Microsoft surface pro3

### ISSUE THREAD

**Issue by phanisnvs** [mapbox/mapbox-gl-js#7709] opened 2018-12-18 13:51 UTC
Hi,

In our application, we use mapbox gl/api for viewing contact pins in map. In Android and IOS devices, we can able to pinch (touch) to Zoom in and out pins in the map.But in Surface pro3 pinch in and out function is not working instead it is panning the map.

Any leads on how to check for the issue / provide guidance to get solution

**Comment by mourner** [comment] 2019-03-14 14:16
I believe this is a duplicate of #1928.

**Closed by mourner** 2019-03-14 14:16 UTC
Labels: environment-specific :desktop_computer:
