### ISSUE TITLE
Displaying marker icons from other styles disappears

### ISSUE THREAD

**Issue by roblav96** [mapbox/mapbox-gl-js#1930] opened 2016-01-14 03:57 UTC
I'd like to have a feature where the user can change the map style as they please.

Following this exact example: 
https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/
But changing the style, the markers disappear.

Maybe is it possible to import the Maki icons for all styles?
https://github.com/mapbox/maki

I'm trying to see how I can read the sprites being used in the streets-v8.json style and import them globally to the map somehow?

**Comment by nicooprat** [comment] 2016-01-30 16:58
+1 I'd like that behavior too. Changing styles should not "empty" existing layers. I'm not using Maki icons but only drawing shapes, but they also disappear.

**Comment by soffes** [comment] 2016-02-16 01:34
+1 I spent awhile trying to figure this out but didn't get anywhere.

**Comment by lucaswoj** [comment] 2016-02-16 18:43
duplicate of https://github.com/mapbox/mapbox-gl-styles/issues/241

**Closed by lucaswoj** 2016-02-16 18:43 UTC
Labels: support

**Comment by nicooprat** [comment] 2016-02-16 21:49
Sorry but I'm not sure if I misunderstood something or if I should create another issue? I'm not using any icons, I'm only drawing (lines and circles) on my map, and when I change its style, all shapes disappears and I have to reload my datas. Here's a video of my issue (not my website but was easier to show): streamable.com/3i0w

**Comment by roblav96** [comment] 2016-02-16 22:29
@nicooprat This is a separate issue. 

What I've done is stored all my popups and layer data separately then reload the data when I change styles.

**Comment by nicooprat** [comment] 2016-02-17 09:13
Yes of course but I think it's not the supposed behavior. I will open another issue, thanks.

**Comment by agusterodin** [comment] 2019-10-22 19:56
Did anybody ever find a solution?

**Comment by asheemmamoowala** [comment] 2019-10-22 21:02
>  I'm not using any icons, I'm only drawing (lines and circles) on my map, and when I change its style, all shapes disappears and I have to reload my datas.

This is a duplicate of of #4225.

**Comment by Aamir2000** [comment] 2020-09-15 20:46
+1 annoying super annoying for sure it should save its state automatically and handle styles, layers and other things that has anything to do with changing map in any way internally. It'll help abstract away some of that complexity of having to deal with map state and all. While using mapbox-directions it kinda make it disappear from map when styles and layers are updated.
