### ISSUE TITLE
minzoom property of layer only takes int (decimal just rounds up)

### ISSUE THREAD

**Issue by ralphking** [mapbox/mapbox-gl-js#5006] opened 2017-07-20 13:39 UTC
### Steps to Trigger Behavior

Create a layer, set min zoom property to 12.5, max zoom to 20, add to the map

### Expected Behavior

The layer disappears when zoom gets below 12.5

### Actual Behavior

The layer disappears at 13 (12.5 has rounded up). This seems to happen for any decimal.

Is this expected?

**Comment by jfirebaugh** [comment] 2017-07-20 15:13
Duplicate of #2929.

**Closed by jfirebaugh** 2017-07-20 15:13 UTC
