### ISSUE TITLE
Profiling tools for style performance, identifying bottlenecks

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1139] opened 2015-04-01 19:08 UTC
Map styling might not be the rate-limiting step in js or native performance right now, but certain styles do feel more responsive than others, especially on iOS. 

**How feasible is a profiling tool that tells me if something in the style is causing delays?** Whether it's too many layers, too many fonts, some line-blur that happens to be super expensive, etc I'm imagining a tool analogous to the Chrome devtools Timeline:

![screen shot 2015-04-01 at 12 04 46 pm](https://cloud.githubusercontent.com/assets/4551508/6949155/bcaa0c0c-d867-11e4-8eb3-d6ec76dc1d76.png)

cc/ @jfirebaugh @ansis @incanus @kkaefer @gundersen

**Comment by tristen** [comment] 2015-04-01 19:16
What about just that: a style performance tab for debugging [like React has](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en)?

**Comment by samanpwbb** [comment] 2015-04-01 19:20
This would be huge not just for our team and for developers, but for anyone designing maps in GL. Could we add profiling into the GL editor?

**Comment by mourner** [comment] 2015-04-02 10:04
Also see #954. Measuring WebGL rendering performance is a very hard problem and we still don't have a good solution for this. We could relatively easily build a tool to measure tile processing times broken down by layer though.

**Comment by mourner** [comment] 2015-04-02 10:06
Or, we could also output stats of generated buffer size per layer. It would roughly indicate how fast a layer will be drawn, with a warning when some values go out of the ordinary range.

**Comment by tmcw** [comment] 2015-05-26 13:48
This is a duplicate of #954

**Closed by tmcw** 2015-05-26 13:48 UTC
