### ISSUE TITLE
Distortion at low zoom level for big polygon in mapboxgl-js

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#5265] opened 2017-09-11 06:43 UTC
I found that the drawn polygon by mapboxgl-js may cause distortion at some low zoom level like this:

![](http://i.imgur.com/J1CjcD7.png)

However the origin data should be rendred like this:

![](http://i.imgur.com/nn1TpRH.png)

Once zoom to a large level, the distortion will disappear.

What's going on? 

>I am sorry but I can not upload the origin polygon data since it is private for my company. 

The polygon is a complex polygon and  contains total 200k+ vertices.

If further information is required , please let me know.

**Comment by mourner** [comment] 2017-09-11 12:32
Are you loading the polygon through a GeoJSON source? Looks like a duplicate of #3545 and #3080. We plan to fix this issue in the following months, but it's a very challenging technical problem. For now the only workaround is processing the data into tiles on the server, e.g. with Tippecanoe or through a Mapbox Studio upload.

**Comment by exotfboy** [comment] 2017-09-12 01:52
I am using the `vector tile` source at the moment.

**Comment by jfirebaugh** [comment] 2017-09-12 22:46
Are you creating the vector tiles yourself? Have you ensured that they follow the [specification](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4344-polygon-geometry-type) with regard to polygon validity (e.g. no anomalous geometric points, such as self-intersection or self-tangency)?

**Comment by exotfboy** [comment] 2017-09-14 06:33
@jfirebaugh  Yes, the vector tiles are generated by myself, and I use [this library](https://github.com/ElectronicChartCentre/java-vector-tile) 

And is there any tool can be used to check the validity for vector tile?

**Comment by exotfboy** [comment] 2017-09-19 00:55
Hi, finally I found that this maybe caused by mapbox-gl-js, since I have tried to load the same vector tile by openlayers and the features are drawn on the right way.

![image](https://user-images.githubusercontent.com/16457917/30571130-3fe530e8-9d18-11e7-84ee-2661e175cae1.png)

**Comment by exotfboy** [comment] 2017-11-06 07:21
I create a live example to verify this problem, I create the same vector tiles and load them by mapbox and openlayers, while ol render the data correctly.

[Mapbox version](https://exotfboy.github.io/mapbox-line-demo/index.html#10/76.0185/20.6732)

> The line is drawn with  no problem at first, once you zoom in  you will find the distortion,when keep zoom in , the distortion disappear.

[Openlayer version](https://exotfboy.github.io/mapbox-line-demo/ol.html)

@mourner @jfirebaugh

**Comment by exotfboy** [comment] 2017-11-09 01:37
And now I created a live example to verify this problem, I load the same vector tiles by mapbox and openlayers, while ol render the data correctly.

Mapbox([Live demo](https://exotfboy.github.io/mapbox-line-demo/index.html#10/76.0185/20.6732)):
![image](https://user-images.githubusercontent.com/16457917/32527627-f38d67dc-c469-11e7-9ce2-1963b820b6a4.png)




> The line is drawn with  no problem at first, once you zoom in  you will find the distortion,when keep zoom in , the distortion disappear.

Openlayers([Live demo](https://exotfboy.github.io/mapbox-line-demo/ol.html)) works perfectly:

![image](https://user-images.githubusercontent.com/16457917/32527834-cd0f9016-c46a-11e7-87f5-028dff2535e3.png)

**Comment by exotfboy** [comment] 2017-12-19 03:20
Hi, there has been two releases after I post this issue.

I wonder if this issue is confirmed ?

**Comment by lbud** [comment] 2017-12-19 04:24
Sorry for the delay @exotfboy. It looks like that library may not conform with the Mapnik vector tile specification @jfirebaugh mentioned in https://github.com/mapbox/mapbox-gl-js/issues/5265#issuecomment-329005541 — I took a look at tile 11/114/339 in your example (which renders with artifacts) and that tile reports invalid self-intersections (see below). The polygon triangulation library used in Mapbox GL depends on conformity to that specification, so you'll need to use a vector tile generation library that can produce spec-conformant tiles. ([Mapnik](https://github.com/mapnik/mapnik) or [node-mapnik](https://github.com/mapnik/node-mapnik) may be good options for you.) Other rendering libraries may use different triangulation libraries that handle degenerate geometries differently.

FWIW, node-mapnik has helpful [`VectorTile#reportGeometrySimplicity`](http://mapnik.org/documentation/node-mapnik/3.6/#VectorTile.reportGeometrySimplicity) / [`VectorTile#reportGeometryValidity`](http://mapnik.org/documentation/node-mapnik/3.6/#VectorTile.reportGeometryValidity) methods to check specification conformity of a vector tile. The 11/114/339 tile self-reports as such:
```
 [ { layer: 'line',
    message: 'Geometry has invalid self-intersections. A self-intersection point was found at (3244.6, 4011); method: i; operations: u/i; segment IDs {source, multi, ring, segment}: {0, -1, -1, 233}/{0, -1, 0, 1}',
    featureId: 1,
    geojson: '{"type":"FeatureCollection","features":[{"type":"Feature","id":1,"geometry":{"type":"Polygon","coordinates":[[[3589,3862],[3600,3878],[3593,3881],[3578,3887],[3568,3892],[3550,3899],[3535,3906],[3529,3908],[3521,3911],[3519,3912],[3512,3915],[3508,3917],[3503,3919],[3488,3925],[3477,3930],[3454,3940],[3452,3940],[3450,3941],[3443,3943],[3439,3945],[3434,3947],[3432,3948],[3425,3951],[3424,3951],[3423,3952],[3420,3954],[3406,3960],[3396,3964],[3383,3970],[3372,3974],[3365,3978],[3359,3980],[3341,3988],[3336,3991],[3330,3994],[3326,3996],[3324,3998],[3307,4009],[3303,4012],[3300,4014],[3292,4017],[3282,4021],[3279,4022],[3269,4024],[3216,4031],[3145,4041],[3119,4045],[3118,4045],[3114,4045],[3113,4045],[3058,4053],[2966,4066],[2821,4086],[2818,4086],[2800,4089],[2766,4093],[2747,4096],[2710,4101],[2683,4105],[2671,4106],[2630,4112],[2609,4115],[2602,4116],[2559,4122],[2547,4123],[2537,4125],[2511,4125],[2500,4125],[2492,4126],[2487,4127],[2481,4126],[2470,4124],[2460,4124],[2449,4122],[2442,4119],[2436,4117],[2433,4115],[2431,4114],[2427,4113],[2424,4112],[2420,4113],[2415,4113],[2410,4111],[2406,4111],[2402,4111],[2392,4110],[2389,4108],[2384,4106],[2380,4102],[2375,4100],[2370,4098],[2365,4096],[2360,4093],[2350,4087],[2344,4080],[2326,4055],[2313,4039],[2297,4017],[2292,4011],[2285,4002],[2278,3992],[2265,3979],[2258,3974],[2252,3970],[2241,3964],[2229,3957],[2218,3951],[2213,3949],[2199,3941],[2175,3929],[2160,3922],[2150,3917],[2146,3915],[2128,3906],[2108,3895],[2091,3887],[2087,3885],[2072,3877],[2063,3873],[2057,3869],[2050,3865],[2046,3860],[2040,3854],[2033,3845],[2026,3837],[2018,3827],[2016,3825],[2011,3818],[2003,3810],[1995,3800],[1977,3779],[1976,3777],[1967,3767],[1963,3760],[1954,3750],[1945,3739],[1930,3732],[1927,3730],[1903,3719],[1877,3707],[1860,3698],[1833,3685],[1829,3684],[1835,3673],[1842,3676],[1854,3681],[1869,3688],[1882,3694],[1898,3702],[1910,3707],[1916,3710],[1921,3712],[1926,3714],[1948,3725],[1963,3732],[1965,3733],[1969,3735],[1973,3737],[1973,3738],[1975,3739],[1977,3741],[1979,3742],[1981,3744],[1982,3747],[1983,3750],[1984,3757],[1987,3765],[1990,3769],[1994,3773],[2005,3786],[2018,3801],[2027,3812],[2031,3817],[2037,3824],[2042,3831],[2051,3842],[2058,3849],[2067,3855],[2088,3866],[2101,3873],[2106,3876],[2128,3889],[2139,3894],[2153,3898],[2168,3901],[2178,3905],[2189,3910],[2199,3916],[2200,3917],[2209,3922],[2213,3924],[2230,3931],[2231,3931],[2238,3934],[2253,3944],[2270,3957],[2280,3966],[2294,3980],[2302,3992],[2308,4001],[2317,4014],[2334,4039],[2340,4047],[2351,4062],[2363,4076],[2373,4083],[2374,4084],[2395,4094],[2400,4096],[2401,4096],[2439,4101],[2463,4104],[2489,4107],[2497,4108],[2517,4110],[2530,4110],[2532,4110],[2537,4110],[2542,4109],[2547,4109],[2563,4106],[2604,4101],[2618,4099],[2640,4096],[2682,4090],[2710,4086],[2769,4078],[2798,4074],[2815,4072],[2821,4071],[2946,4053],[3110,4030],[3115,4029],[3178,4020],[3252,4010],[3262,4007],[3270,4005],[3278,4002],[3287,3998],[3310,3985],[3322,3978],[3323,3977],[3331,3970],[3333,3968],[3335,3967],[3341,3965],[3349,3961],[3354,3959],[3380,3949],[3401,3940],[3414,3934],[3415,3934],[3417,3933],[3420,3932],[3435,3926],[3455,3917],[3456,3917],[3474,3909],[3494,3900],[3498,3899],[3502,3897],[3513,3893],[3518,3891],[3519,3890],[3538,3883],[3550,3878],[3552,3877],[3577,3866],[3578,3866],[3589,3862]],[[3245,4012],[3245,4011],[3244,4011],[3244,4012],[3245,4012]]]},"properties":{}}]}' } ]
```

**Closed by lbud** 2017-12-19 04:24 UTC
Labels: needs information

**Comment by exotfboy** [comment] 2017-12-19 05:36
@lbud Thanks, I will have a try.
