### ISSUE TITLE
return object of map.getCenter() and map.getBounds().getCenter() differ

### ISSUE THREAD

**Issue by vchrisb** [mapbox/mapbox-gl-js#10018] opened 2020-10-06 08:30 UTC
**mapbox-gl-js version**: 1.12.0

**browser**: Chrome

### Steps to Trigger Behavior

 1.Create map
 2. compare `map.getCenter()` with `map.getBounds().getCenter()`
 3.

### Link to Demonstration

https://jsfiddle.net/f0rg5ymz/

### Expected Behavior

`map.getCenter()` and `map.getBounds().getCenter()` return the same value.

### Actual Behavior

Both LngLat objects differ and especially Lat difference is not just a rounding difference.

e.g.: 
`map.getCenter()`: `LngLat {lng: -65.017, lat: -16.457}`
`map.getBounds().getCenter()`: `LngLat {lng: -65.01700000000892, lat: -16.385704037105853}`

**Comment by mourner** [comment] 2020-10-06 17:57
Looks like you accidentally submitted a duplicate of #10017.

**Closed by mourner** 2020-10-06 17:57 UTC
