### ISSUE TITLE
Not Showing Map Style

### ISSUE THREAD

**Issue by shawn220a** [mapbox/mapbox-gl-js#10368] opened 2021-02-08 18:40 UTC
**mapbox-gl-js version**: 2.1.0

**browser**: Safari, Google Chrome

### Steps to Trigger Behavior

 1. Only happens on deployed digital oceans app
 2. Go to nav bar
 3. Select Where We Reach
 4. Inspect and it shows error: ReferenceError: Can't find variable: y

### Link to Demonstration
https://southwest-education-cmlho.ondigitalocean.app/WhereWeReach

https://jsbin.com/

**Comment by mourner** [comment] 2021-02-09 13:39
There's not enough details to properly diagnose the issue, but this is likely a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/10173

**Closed by mourner** 2021-02-09 13:39 UTC

**Comment by rdvelazquez** [comment] 2021-04-14 18:36
I'm having similar behavior where layers (line and fill) with geoJSON sources show up fine in develop environment but don't show up when deployed to firebase hosting. I inserted some logging in the code to try and track down the issue and I've confirmed that on both develop and deployed version:
- the sources are being added correctly (`console.log(map.getStyle().sources)`)
- the layers are being added correctly (`console.log( map.getStyle().layers)`)

mapbox-gl-js version: 2.1.1 (also tried 2.2.0)
browser: Safari

@shawn220a it looks like the first link to demonstration now is working correctly on your site... What did you do to address the issue?

**Comment by rreusser** [comment] 2021-04-14 19:27
@rdvelazquez I think your issue is also a bundling issue (obscured slightly by minimization). Because transpilers like babel are not aware of how gl-js's web workers are set up, they don't inject the polyfills in the right place, resulting in errors like "y is not defined". You can find an explanation in #10565 and [updated documentation](https://docs.mapbox.com/mapbox-gl-js/api/#transpiling-v2) on the Mapbox website, which will hopefully help you choose the right fix for your needs.

**Comment by rdvelazquez** [comment] 2021-04-14 19:47
Thanks for the quick reply @rreusser! I tried using mapbox-gl-js version 1.13.1 (the switch from ES5 to ES6 modules was apparently implemented in the change from 1.13.1 -> 2.0.0) and it now works fine on the deployed version. 

I'll do some more digging into the issues and documentation that you linked to and see if I can find a way to make ^2.0.0 work with Firebase deployment. I'll let you know here if I find a solution.

**Comment by HudsonGri** [comment] 2022-01-27 03:13
Did you find a way to make it work in 2.0.0? I am also having this issue>
