### ISSUE TITLE
Highlight features example broken

### ISSUE THREAD

**Issue by ekelleyv** [mapbox/mapbox-gl-js#3276] opened 2016-09-29 21:05 UTC
This page:
https://www.mapbox.com/mapbox-gl-js/example/query-similar-features/

![image](https://d3vv6lp55qjaqc.cloudfront.net/items/1S0232192t3J1C1l3p33/counties.gif?v=ca27c47a)

### Steps to Trigger Behavior

 1. Load page
 2. Mouse over the example map

### Expected Behavior

Counties highlight as implemented in https://github.com/mapbox/mapbox-gl-js/pull/2404

### Actual Behavior

Counties only sometimes highlight. Lots of error messages in the console:
![image](https://cloud.githubusercontent.com/assets/1816394/18972224/53362fc2-8666-11e6-9701-73fd80e04548.png)

Browser: Updated Chrome on OSX

**Comment by jfirebaugh** [comment] 2016-09-29 22:38
Duplicate of #3167.

**Closed by jfirebaugh** 2016-09-29 22:38 UTC
