### ISSUE TITLE
Flickering when viewing certain areas (possibly hill shading?) at an angle

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-js#4482] opened 2017-03-23 13:17 UTC
**mapbox-gl-js version**: v0.34.0

### Steps to Trigger Behavior

 1. Look at the Nerang State Forest area (as an example) in Australia. Note: I am unsure if this is to do with hill shading as some other locations appear fine. It seems as though it is a hill shaded layer above another layer?
 2. Tilt the map at an angle

### Expected Behavior
Solid/smooth rendering of area

### Actual Behavior
Area will flicker with polygonal shapes appearing in different shades (see images below). Tested in Safari and Chrome

<img width="745" alt="screen shot 2017-03-23 at 13 09 12" src="https://cloud.githubusercontent.com/assets/13920398/24249221/53f25268-0fca-11e7-85aa-d21c1484dab2.png">

<img width="746" alt="screen shot 2017-03-23 at 13 09 40" src="https://cloud.githubusercontent.com/assets/13920398/24249232/5e22766e-0fca-11e7-9d4a-c59209fd7dd5.png">

**Comment by jfirebaugh** [comment] 2017-03-23 16:34
Thanks for the report! This is a duplicate of #3320, and we'll continue to track the issue over there.

**Closed by jfirebaugh** 2017-03-23 16:34 UTC
