### ISSUE TITLE
Show only the half of the icon

### ISSUE THREAD

**Issue by hanchao** [mapbox/mapbox-gl-js#1763] opened 2015-11-26 08:47 UTC
![half_icon.png](http://d.pcs.baidu.com/thumbnail/7eb0309c3acff77eb480fdbe08982868?fid=17227693-250528-29721910820605&time=1448524800&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-6TWIlZZ6NkpC6i5tRqByqcsp2rU%3D&rt=sh&expires=2h&r=862795469&sharesign=unknown&size=c710_u500&quality=100)

Safari 9.0.1
mapbox-gl-js v0.11.2

http://hanchao.github.io/vectormap/#14.59/39.9599/116.3604

**Comment by mourner** [comment] 2015-11-26 09:19
Probably a duplicate of #757, and likely to get fixed by #1727 when it is done.

**Closed by mourner** 2015-11-26 09:19 UTC
