### ISSUE TITLE
Bump geojson-vt dep version

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#1600] opened 2015-10-07 16:37 UTC
Hey,

upstream fix for #1507 was fixed a while back, but hasn't been included in gl-js. Did a test build with 2.1.6 of geojson-vt and can verify that #1507 was resolved.

**Comment by mourner** [comment] 2015-10-08 06:19
"^2.1.0" should install "2.1.6", so the next build should include the latest version. However we need to make sure to run `npm update` before publishing a version. cc @jfirebaugh @bhousel

**Comment by jfirebaugh** [comment] 2015-10-08 18:01
We do automated release builds via CI and geojson-vt 2.1.6 should have been pulled into mapbox-gl 0.11.1. The problem is that CI has caching for `node_modules`, and even a new branch will pull the previous cache from `master`. So we need to switch the install step in CI to use `npm update` instead of `npm install`.

**Comment by lucaswoj** [comment] 2015-11-07 00:14
Looks like this has cased some bugs in `v0.11.2` :scream_cat: Going to try to fix the deploy script and publish a new version tonight.

**Comment by lucaswoj** [comment] 2015-11-16 23:52
Fixed as of #1683

**Closed by lucaswoj** 2015-11-16 23:52 UTC
