### ISSUE TITLE
Fix zoom and Map#fitBounds on large maps

### ISSUE THREAD

**Issue by gmaclennan** [mapbox/mapbox-gl-js#2863] opened 2016-07-13 21:49 UTC
**mapbox-gl-js version**: 0.20.1
### Steps to Trigger Behavior
1. Create a map in a `div` larger than 2000px height or width
2. Zoom with the mouse or use `map.fitBounds()`
### Expected Behavior

Map should zoom around the mouse pointer, and zoom and pan to fit bounds
### Actual Behavior

Starting around 2000px, and definitely noticeable at 2500px width, the map 'drifts' a large amount during scroll wheel zooming, and `map.fitBounds()` no longer works correctly - instead moving to a different bounds, even though `map.getBounds()` still reports the correct bounds.

Example: http://jsbin.com/tudini/edit?html,output

**Comment by danswick** [comment] 2016-07-18 20:51
This issue appears to be related to https://github.com/mapbox/mapbox-gl-js/issues/2842.

**Comment by gmaclennan** [comment] 2016-07-19 18:07
@lucaswoj is that on a non-retina display? That would make sense because I was testing on a retina display, so that canvas size is 4500px for a 2250px container.

I don't quite how the numbers work relating to #2673. For latest chrome I get:

> Max Render Buffer Size	16384
> Max Viewport Dimensions	[16384, 16384]

**Comment by lucaswoj** [comment] 2016-07-29 22:30
I have tested this on a retina display and a non-retina display and see the same behaviour on both: when the map is larger than can be accommodated by `gl.MAX_RENDERBUFFER_SIZE`, the drift occurs. 

Can you double check your results @gmaclennan? Do you know your screen's pixel ratio?

**Comment by gmaclennan** [comment] 2016-07-30 00:28
hi @lucaswoj, yes doing some further investigation here, the drift starts to occur after a map of 2048x2000 on a 2x retina display, i.e. that's 16,348,000 pixels. Not sure where the extra factor of 10^3 comes from? but I don't understand enough of how gl buffers work.

The main reason I wanted to figure this out was for [exporting maps](https://github.com/digidem/mapbox-map-image-export) and knowing the exact dimensions it's triggered is helpful. The whole map does render fine at larger sizes e.g. 8000px x 8000px it's just that the positioning is wrong.

**Comment by andrewharvey** [comment] 2017-01-23 22:59
When I tried to replicate this on 0.20.0 I can confirm but I can't see the problem in 0.29.0.

**Comment by gmaclennan** [comment] 2017-01-23 23:23
Just tested the current behaviour with 0.31.0. The possible size is larger, up to 4096px x 4096px on a retina display (and I would guess 8192px x 8192px on non-retina?) Zooming and panning works as expected at this size e.g. no drift as observed before. Above these dimensions mapbox throws an error and does not render. It looks like this might change to a warning: https://github.com/mapbox/mapbox-gl-js/issues/3915

Note that these limits are for the maximum of either dimension e.g. it doesn't matter if you only make the map 100px tall, the max width is still 4096px.

Gregor

**Comment by andrewharvey** [comment] 2017-01-23 23:31
@gmaclennan I didn't think it was possible to test on 0.31.0. Doesn't 0.31.0 throws an error when the web gl canvas is > gl.MAX_RENDERBUFFER_SIZE / 2, which is the exact criteria for this issue to be triggered by?

**Comment by gmaclennan** [comment] 2017-01-23 23:36
It throws the error when it is larger than 8192, twice what would trigger erratic behavior before. This may be due to the latest safari having a larger render buffer? Strangely, the error is thrown when te canvas size is === gl.MAX_RENDERBUFFER_SIZE not half but maybe the error message is referring to display pixels not actual pixels? I only tested this by opening the above jsbin and typing in different numbers.

**Comment by bakedbean** [comment] 2017-01-24 14:55
I'm seeing an issue that may be related to this discussion.  I am rendering a large map (~2000px vertical x ~1300px horizontal).  It renders fine, but when I click on the zoom controls, instead of zooming in or out from the center point, it zooms AND pans north or south.  What's odd is that scrollZoom (when enabled) zooms as expected, with no panning.

**Comment by ryanhamley** [comment] 2018-09-25 06:17
I can't reproduce this in v0.49.0 even at 5000x5000 pixels in the JSBin example so I'm going to close this.

**Closed by ryanhamley** 2018-09-25 06:17 UTC
Labels: bug :beetle:
