### ISSUE TITLE
fitBounds randomly throw failed to invert matrix

### ISSUE THREAD

**Issue by nrako** [mapbox/mapbox-gl-js#3474] opened 2016-10-27 14:49 UTC
Encountered on versions 0.21.0 && 0.25.1

Sorry about the "**randomly** issue", hard to reproduce, and I believe it's a size / timing issue. Which is also why I got fed-up with trying to debug it and just have hanging breakpoints waiting for next occurrences.

I'm sharing my finding hoping someone can help pin-point the root issue.

[`Transform.latY(lat, worldSize)`](https://github.com/mapbox/mapbox-gl-js/blob/master/js/geo/transform.js#L224) Sometimes receive a `lat` of `-90` and then return `Infinity`. (Is that expected???)

``` javascript
const y = 180 / Math.PI * Math.log(Math.tan(Math.PI / 4 + lat * Math.PI / 360));
```

This results is then used (through `this.y`) to calculate the matrices:
https://github.com/mapbox/mapbox-gl-js/blob/master/js/geo/transform.js#L455

Resulting in `NaN` which end up raising the `failed to invert matrix` https://github.com/mapbox/mapbox-gl-js/blob/master/js/geo/transform.js#L467

I don't yet understand why `latY()` randomly receives `lat: -90`, but this all start with `fitBounds` with options: `linear: true`, a padding and offset.

**Comment by tmcw** [comment] 2016-10-27 15:22
Hi Nicholas,

Thanks for reporting this issue! Could you pull together a jsfiddle that shows the issue, or provide a complete code snippet of your integration code? And specify what browsers this issue appears on?

Thanks,

- Tom

**Comment by nrako** [comment] 2016-10-27 16:20
Hi Tom,

This is happening on Safari Version 10.0 (11602.1.50.0.10) and Chrome (54.0.2840.71).

Regarding a jsfiddle that show the issue, I'm afraid I can't or not easily. This is more or less random and only happens on some specific conditions. That said I'll try to get back to this and pull together a jsfiddle.

But first it would really help me build will to do that, if somebody can confirm that the following is expected for [latY()](https://github.com/mapbox/mapbox-gl-js/blob/master/js/geo/transform.js#L224). Because even with my very limited comprehension, this doesn't look right:

```javascript
let lat = -90
expect([latY(lat)]().to.be(-Infinity)
```

**Comment by mourner** [comment] 2016-10-27 22:56
@nrako next time this is triggered, can you extract the call trace (the chain of function calls that lead to `latY` with `lat = -90`)?

**Comment by nrako** [comment] 2016-10-28 07:38
@mourner thanks for your help, I wish I could isolate the root cause I'm think I'm doing something wrong but can't pint point what.

The bundle is built with mapbox-gl 0.21.0 but I have the same issue in 0.25.1.
```
(anonymous function)	@	VM20209:1
evaluate
_calcMatrices	        @	mapbox-gl.bundle.js:36736
set center	            @	mapbox-gl.bundle.js:36440
setLocationAtPoint	    @	mapbox-gl.bundle.js:36516
(anonymous function)	@	mapbox-gl.bundle.js:38957
(anonymous function)	@	mapbox-gl.bundle.js:39218
tick	                @	mapbox-gl.bundle.js:2779
requestAnimationFrame (async)		
exports.frame	        @	mapbox-gl.bundle.js:2751
tick	                @	mapbox-gl.bundle.js:2780
requestAnimationFrame (async)		
exports.frame	        @	mapbox-gl.bundle.js:2751
tick	                @	mapbox-gl.bundle.js:2780
requestAnimationFrame (async)		
exports.frame	        @	mapbox-gl.bundle.js: 2751
tick	                @	mapbox-gl.bundle.js: 2780
```

<img width="469" alt="screen shot 2016-10-28 at 09 09 31" src="https://cloud.githubusercontent.com/assets/425397/19798060/1f4e0f14-9cef-11e6-9701-d3bb447f9cd4.png">

<img width="657" alt="screen shot 2016-10-28 at 09 08 58" src="https://cloud.githubusercontent.com/assets/425397/19798080/35fcdbe6-9cef-11e6-8c81-be4a86f4958f.png">

<img width="591" alt="screen shot 2016-10-28 at 09 08 35" src="https://cloud.githubusercontent.com/assets/425397/19798069/2ab3a59e-9cef-11e6-9851-30586a8fd6a2.png">

<img width="648" alt="screen shot 2016-10-28 at 09 18 29" src="https://cloud.githubusercontent.com/assets/425397/19798171/bfc08c24-9cef-11e6-81c1-8ead824ca2bb.png">

```javascript
toLngLat = {"lng":4.394181233333313,"lat":44.01333223374033}
fromPoint = {"x":3259230.626962026,"y":-5406962.913019736}
toPoint = {"x":206.5,"y":366}
fromPoint = {"x":3259230.626962026,"y":-5406962.913019736}
```

<img width="474" alt="screen shot 2016-10-28 at 09 11 51" src="https://cloud.githubusercontent.com/assets/425397/19798086/3ee46d3c-9cef-11e6-8128-df10fe7f10e5.png">
```javascript
options = {"offset":[0,-33.5],"duration":500,"padding":41.3,"maxZoom":null,"linear":true,"center":{"lng":4.394181233333313,"lat":44.01333223374033},"zoom":5.6954682781259205,"bearing":0}"
```

**Comment by mourner** [comment] 2016-10-28 08:01
That's very helpful, thanks! I wonder if doing `_constrain` before calculating matrices would help with the issue...

**Comment by nrako** [comment] 2016-10-28 08:23
That do help! Did that change and got a breakpoint on `set center` when `center.lat` is `-90` and this time calculating matrices didn't raised.

Trying to reproduce it to understand it a bit more, but now I have a hard time reproducing it...

**Comment by prasanna-kumar** [comment] 2016-11-01 15:05
Getting this issue if `sw` and `ne` bounds of `LngLatBounds`. reproducting with following code
```
var sw = new mapboxgl.LngLat(-73.9876, 40.7661);
var ne = new mapboxgl.LngLat(-73.9397, 40.8002);
var llb = new mapboxgl.LngLatBounds(sw, ne);
map.fitBounds(llb);
```

**Comment by elishaterada** [comment] 2016-11-02 06:57
Same problem, I was using geolocation API to get geolocation of same machine open on two windows. In most cases they return same geo coordinates and that throws an error when I try to use `fitBounds` method. This might be a rare case but a device using geolocation connected under same Wi-fi could run into this issue.

![Uploading Screen Shot 2016-11-01 at 11.55.24 PM.png…]()

**Comment by mollymerp** [comment] 2016-11-02 19:51
@elishaterada @prasanna-kumar what you're describing is a duplicate of #3307 
@prasanna-kumar I cannot reproduce w the example you provided https://jsfiddle.net/4ztjmtoj/

**Closed** 2016-11-02 20:17 UTC
Labels: bug

**Comment by ArntB** [comment] 2016-11-04 09:53
This might bee an other error but the end result is the same. I modified the jsFiddle a bit so you can reproduce:

https://jsfiddle.net/4ztjmtoj/15/

I have added a zoom in and a zoom out button to help trigger the bugg.
If you click the zoom inn button. Then after it has zoomed to the bounds you zoom inn with the scroll wheel. Then click the zoom out button. This reproduces the bug 100% of the time for mee in Chrome, firefox and IOS safari.

**Comment by mourner** [comment] 2016-11-04 15:09
@ArntB the JSFiddle is using v0.21.0. Can you try the master version?

**Comment by ArntB** [comment] 2016-11-07 12:06
Updated with v0.26.0 https://jsfiddle.net/4ztjmtoj/16/

**Comment by nrako** [comment] 2016-11-07 12:52
@ArntB [v0.26.0](https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.26.0) is currently 141 commits behind master, the fix hasn't been released yet.

**Comment by ArntB** [comment] 2016-11-07 14:58
Do you have a cdn link to the master build?

**Comment by mourner** [comment] 2016-11-17 12:53
The fix is in the 0.27 release now.

**Comment by keyofj** [comment] 2017-05-25 18:36
This issue is still happening with v0.37.0 but it is not with initial fitbounds call it is happening when doing a map.flyTo() with zoom level set at 14 and the center set to [-82.6078, 39.6964].

Sometimes it works sometimes it  @doesn't.

`Uncaught Error: failed to invert matrix
    at Transform._calcMatrices (transform.js:507)
    at Transform.prototypeAccessors.zoom.set (transform.js:143)
    at e.<anonymous> (camera.js:789)
    at e.<anonymous> (camera.js:839)
    at Object.exports.timed (browser.js:43)
    at e._ease (camera.js:838)
    at e.flyTo (camera.js:785)
    at GeocoderAPI.js:133
    at Object.<anonymous> (Utilities.js:23)
    at fire (jquery-1.12.3.js:3232)`

**Comment by mollymerp** [comment] 2017-05-25 21:03
@keyofj do you have the map's `maxBounds` set? can you set up a minimal jsbin.com or similar reproducing the issue?

**Comment by santinogue** [comment] 2017-06-06 12:55
I'm still seeing this issue at v0.37.0. It doesn't happen always but after zooming in and out and calling fitBounds once and again it happens.

<img width="528" alt="screen shot 2017-06-06 at 9 48 07 am" src="https://cloud.githubusercontent.com/assets/10976299/26829884/709146f0-4a9d-11e7-97be-b877ea98e686.png">

**Comment by anandthakker** [comment] 2017-06-07 11:41
@santinogue any chance you could create a simple jsfiddle example that demonstrates this?  I haven't managed to reproduce it on the examples previously shared on this ticket.

**Comment by santinogue** [comment] 2017-06-08 20:42
@anandthakker I tried in a jsfiddle (https://jsfiddle.net/snoguera/hqp1zceL/1/) but couldn't reproduce the error. I don't know which other actors are in play here , only calling fit bounds and zoom in/out doesn't seem to be the way to trigger the issue in that map, it does in my local environment.

**Comment by rulyotano** [comment] 2018-03-23 13:15
If it helps, I also get the same error on random occasions when making zoom in/out. First is raised a `failed to invert matrix` error, and then, on every action in the map, for instance moving the mouse over, is raised this error: `Invalid LngLat object: (NaN, NaN)`. Call Stack for this last error: 
`LngLat -> lng_lat.js
Transform.coordinateLocation -> transform.js
Transform.pointLocation -> transform.ks
e.unproject`
Seems that the problem in this last error is when trying to convert the point to coordinate, in the line `return this.coordinateLocation(this.pointCoordinate(p))` the `this.pointCoordinate(p)` is returning `Coordinate {column: NaN, row: NaN, zoom: NaN}`. It is difficult to reproduce the error, because it is random, if any new detail I will update this post or create a new one.
