### ISSUE TITLE
Center and zoom options on new mapboxgl.Map are not overriding the style's center/zoom

### ISSUE THREAD

**Issue by willemarcel** [mapbox/mapbox-gl-js#9299] opened 2020-02-13 20:20 UTC
**mapbox-gl-js version**: 1.7.0

**browser**: Firefox/Chrome

### Steps to Trigger Behavior

 1. Start a map with
```
new mapboxgl.Map({
        container: mapRef.current,
        style: MAP_STYLE,
        center: [0, 0],
        zoom: 0,
      })
```
but use a style layer that has another center set.  

### Link to Demonstration

I reported it here: https://github.com/mapbox/mapbox-gl-styles/pull/342#discussion_r378946467

### Expected Behavior

The map should load with the center in 0, 0 coords and zoom level 0

### Actual Behavior

The map will load in the center of the layer, not in 0, 0. If you set zoom as 0.5 or other positive value, it works correctly. The same happens if you set zoom: 2 and minZoom: 2.

**Comment by andrewharvey** [comment] 2020-02-13 23:26
I'll close this as a duplicate of #6658, if you have any additional information please feel free to post it on the existing ticket.

**Closed by andrewharvey** 2020-02-13 23:26 UTC
