### ISSUE TITLE
attribution_control._updateAttribution causing Style Recalculation and Layout

### ISSUE THREAD

**Issue by Scarysize** [mapbox/mapbox-gl-js#4447] opened 2017-03-17 21:31 UTC
Seems the attribution control is updated every time `.setData` is called on a GeoJSON source (which makes sense). This update causes the browser to recalculate styles and layout. This is fine most of the time, because you are calling `.setData` once. Though when animating features on the map in a animation loop (`requestAnimationFrame`), this costs **valuable** milliseconds each frame. I observed between 0.5 and 4ms (!).

In my application I'm doing something similar like the example below does (actual implementation-wise pretty much exactly that).

Versions I experienced this:
- 0.32.1
- 0.34.0

### Steps to Trigger Behavior

 1. Visit https://www.mapbox.com/bites/00318/
 2. Open DevTools with Timeline and record a few seconds while points are being animated
 3. Check for purple "Recalculate Style" & "Layout" bars in the flame chart

### Expected Behavior

Don't trigger Style Recalculation and Layout every frame

### Actual Behavior

Above mentioned is happening every 

---

Some screenshots taken on a MBP 13" (mid 2015), recent Chrome

<img width="599" alt="screen shot 2017-03-17 at 22 14 01" src="https://cloud.githubusercontent.com/assets/10571630/24063785/665d510e-0b61-11e7-9021-d1aa7d29113c.png">
<img width="515" alt="screen shot 2017-03-17 at 22 14 09" src="https://cloud.githubusercontent.com/assets/10571630/24063786/665d73a0-0b61-11e7-9afd-058f37d6e703.png">
<img width="586" alt="screen shot 2017-03-17 at 22 17 43" src="https://cloud.githubusercontent.com/assets/10571630/24063784/665c3c06-0b61-11e7-90c5-e5b96ddf634e.png">

**Comment by lucaswoj** [comment] 2017-03-17 21:49
Nice catch! We're always looking for perf improvements to `setData`. I'll tackle this in the next few days.

**Comment by mollymerp** [comment] 2017-03-17 23:11
Thanks @Scarysize ! That demo you linked to is using an older version of mapbox-gl-js and I think the behavior is different now since we refactored our eventing for sourcedata #4347 . Its true that `Recalculate Style` (points to `AttributionControl#_updateEditLink` on my Timeline) was being erroneously called, and I've made a PR to correct that #4448 

I haven't been able to reproduce what you're seeing with the most recent release, so I'm cautiously optimistic that this has been resolved.

**Comment by Scarysize** [comment] 2017-03-18 07:27
Great, thanks for the fast reaction. I will give it a try as soon as the PR is through. 👌

**Comment by mollymerp** [comment] 2017-03-21 21:09
@Scarysize we just merged the fix into master! Mind letting us know if this helps with your issue?

**Comment by Scarysize** [comment] 2017-03-22 07:11
@mollymerp Thanks for the heads-up. Looks good so far, no more style recalculation or layout every frame! Glad this could be resolved so fast, I guess this can be closed now 🎉

**Comment by mollymerp** [comment] 2017-03-22 17:39
Great to hear! thanks for the followup 😸

**Closed by mollymerp** 2017-03-22 17:39 UTC
