### ISSUE TITLE
queryRenderedFeatures: Cannot read property 'feature' of undefined

### ISSUE THREAD

**Issue by Schwanksta** [mapbox/mapbox-gl-js#3256] opened 2016-09-26 22:35 UTC
**mapbox-gl-js version**: 0.24

### Steps to Trigger Behavior

 1. Use queryRenderedFeatures in a mouseover event
 2. Hover over a feature, then move.

Works on first mouse move, then breaks with "Cannot read property 'feature' of undefined"

Helpfully, this affects the existing MapBox example: https://www.mapbox.com/mapbox-gl-js/example/query-similar-features/

It works as expected in 0.23, which I've reverted back to.

**Comment by jfirebaugh** [comment] 2016-09-26 23:40
Duplicate of #3167.

**Closed by jfirebaugh** 2016-09-26 23:40 UTC
