### ISSUE TITLE
no attribution widget text when not using mapbox maps

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#3891] opened 2017-01-04 18:52 UTC
I am using mapbox-gl-js with non mapbox vector tiles. The tiles are based on OSM, so I need to attribute to OSM. It looks like current attribution widget uses its text from the mapbox sourceCaches or something, as although the compact attribution widget shows no text appears when hovering. Would it be possible to add 'your own attribution text' to the (compact) attribution widget?

**Comment by lucaswoj** [comment] 2017-01-04 20:33
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/1485

**Closed by lucaswoj** 2017-01-04 20:33 UTC

**Comment by musicformellons** [comment] 2017-01-04 20:49
Adding `attribution: 'attribution text'` to the stylesheet as mentioned in your link, worked for me!
