### ISSUE TITLE
Labels are chopped

### ISSUE THREAD

**Issue by atlefren** [mapbox/mapbox-gl-js#1223] opened 2015-05-27 07:36 UTC
The first "L" in the "Lebanon State Forest" on the "simple map" example (https://www.mapbox.com/mapbox-gl-js/examples/) is chopped off in some browsers, see screenshots:

tested on a Windows 8.1 64-bit machine. The L appears when zooming in or out.

Opera 29.0
Version:	29.0.1795.60
![image](https://cloud.githubusercontent.com/assets/1829927/7831053/35fd5b9c-0453-11e5-91fb-fa263129547a.png)

Google Chrome
Version 43.0.2357.81
![image](https://cloud.githubusercontent.com/assets/1829927/7831061/5d6ef7f8-0453-11e5-9952-0c8d1ad2d1ea.png)

Internet Explorer 11
![image](https://cloud.githubusercontent.com/assets/1829927/7831082/803370fc-0453-11e5-9530-d5ccd274e5ab.png)

But works on Firefox 38.0.1 on same machine:
![image](https://cloud.githubusercontent.com/assets/1829927/7831100/a61995d0-0453-11e5-8fe7-b3373c8a331c.png)

**Comment by peterqliu** [comment] 2015-05-27 07:49
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/757

**Comment by atlefren** [comment] 2015-05-27 08:37
Sorry, did not see that one. Should have guessed that you where aware of this

**Comment by mourner** [comment] 2015-05-27 12:35
@peterqliu is it the same issue? That one was about labels getting under other layers but here it's labels being cut off.

**Comment by peterqliu** [comment] 2015-05-27 21:23
@mourner I have a feeling it's related, but will reopen just in case. @ansis are label-slipping  in #757 and label-clipping here both due to tile-clipping?

**Comment by ansis** [comment] 2015-06-02 22:26
Yeah, this is #757.

thanks for reporting @atlefren

**Closed by ansis** 2015-06-02 22:26 UTC
