### ISSUE TITLE
feature shows odd white "gap"

### ISSUE THREAD

**Issue by mannnick24** [mapbox/mapbox-gl-js#7806] opened 2019-01-23 17:42 UTC
We are seeing a rendering error at certain zoom levels, with certain features (e.g. Myanmar ) in our new tileset, The geojson looks ok if i examine the raw source geojson at geojsonio site.

in the attached images note the odd white gap. I thought it was to do with generating our tileset with many features together but at the end I tried just turning just that single feature into the tileset and I still seeing this "gap" issue as shown.

(See attached file: PB_MM_R2018_Admin0.json)
(See attached file: GeoJsonCapture.JPG)
(See attached file: MMIssueZoomCapture.JPG)

Here is the tileset (with only country MM in this tile) showing the symptom:
(See attached file: national-181031.mbtiles)

The tippecanoe parameters used are as what suggested from mapbox (from a feedback about what mapbox last used  a while ago).

tippecanoe --output=/root/data/tiles/national-181031.mbtiles -y pk -Z 0 -z 12 -pS -pt --buffer=2 --detect-shared-borders -f -l nationalpoly /root/data/tiles/national-181031/*.json

By trial and error if i take out -pS ( --simplify-only-low-zooms  ), then the resulted tileset seems ok with this simple example with only just MM in the tileset:

(See attached file: MMAdmin0OKCapture.JPG)

![geojsoncapture](https://user-images.githubusercontent.com/36997628/51625882-3e929680-1f36-11e9-8619-25e9c1fcbef2.JPG)
[GreenlandWhiteLineAppearance.avi.gz](https://github.com/mapbox/mapbox-gl-js/files/2788466/GreenlandWhiteLineAppearance.avi.gz)
[MM issue.avi.gz](https://github.com/mapbox/mapbox-gl-js/files/2788467/MM.issue.avi.gz)
![mmadmin0okcapture](https://user-images.githubusercontent.com/36997628/51625883-3f2b2d00-1f36-11e9-805c-a37041c2e718.JPG)
![mmadmin1issecapture](https://user-images.githubusercontent.com/36997628/51625884-3f2b2d00-1f36-11e9-8ee9-c2cce5b68af8.JPG)
![mmissuezoomcapture](https://user-images.githubusercontent.com/36997628/51625885-3fc3c380-1f36-11e9-8660-a9b257bbd16f.JPG)

However, if I include all the national features to run tippercanoe again without -pS option (was hoping it would solve the problem...), but I still hit the same problem.

Can easily see in this captured video (gzipped avi):
(See attached file: MM issue.avi.gz)

**mapbox-gl-js version**:

**browser**:

### Steps to Trigger Behavior

 1.
 2.
 3.

### Link to Demonstration

https://jsbin.com/

**Comment by mourner** [comment] 2019-01-23 18:00
This is likely a duplicate of #7023.

**Comment by mourner** [comment] 2019-01-23 18:03
Hmm, if it's tippecanoe-generated tiles and not GeoJSON, this might be a different issue. Would you be able to provide a sample tile that renders incorrectly, or ideally a minimal live test case (e.g. JSFiddle)?

**Comment by ericfischer** [comment] 2019-01-23 18:13
As the Tippecanoe author, I would urge you *not* to use `--detect-shared-borders`, `-pS`, or `-pt`, unless there are specific visible discrepancies you are trying to solve with them, since these all inhibit geometric simplifications, thereby making more work for the GL renderer and increasing the odds of aggravating rendering bugs.

**Comment by mourner** [comment] 2019-01-23 18:15
@ericfischer nevertheless, the final tiles go through wagyu, meaning the tiles should contain fully valid polygons, so this might be either a bug in earcut or in wagyu.

**Comment by mannnick24** [comment] 2019-01-25 12:36
I've saved a fiddle that shows the issue (minus our account token)
https://jsfiddle.net/rqownpdg/ I will post the token on ttps://github.com/mapbox/ibm-cognos-collab/issues when I have access

**Comment by mannnick24** [comment] 2019-01-25 14:56
[MM_glitch.zip](https://github.com/mapbox/mapbox-gl-js/files/2796592/MM_glitch.zip)
Heres an html with the glitching polygon as a geojson source - also with the token removed

**Comment by mannnick24** [comment] 2019-01-30 13:44
js fiddle moved to https://jsfiddle.net/mannnick/uLa6ncf3/

**Comment by mourner** [comment] 2019-02-04 15:09
@mannnick24 some updates:

- The GeoJSON issue is definitely a duplicate of #7023.
- The vector tile issue is a bug in [earcut](https://github.com/mapbox/earcut). I managed to reduce the test case and hopefully will find a fix soon — let's track this in #https://github.com/mapbox/earcut/issues/111

**Closed by mourner** 2019-02-04 15:09 UTC
Labels: needs information :pray:
