### ISSUE TITLE
Please add marker 'click' event

### ISSUE THREAD

**Issue by mariusa** [mapbox/mapbox-gl-js#9823] opened 2020-06-24 17:00 UTC
## Motivation

Have custom action performed when one clicks on a marker. There's no `click` event, only drag-related:
https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker-events

Other people are asking this too, solutions invoke adding a custom layer or other hacks:
https://stackoverflow.com/questions/31448397/how-to-add-click-listener-on-marker-in-mapbox-gl-js

Having a `click` handler which receives the coordinates & id of clicked marker would be so much easier.

**Comment by asheemmamoowala** [comment] 2020-06-24 17:41
@mariusa Thanks for opening this issue. This is a duplicate of #7793. Let's close it here and focus the conversation on that ticket.

**Closed by asheemmamoowala** 2020-06-24 17:41 UTC

**Comment by mariusa** [comment] 2020-06-24 19:08
Thanks Asheem!
I did search for dupes, that doesn't show in the 1st page here
https://github.com/mapbox/mapbox-gl-js/issues?q=marker+click
