### ISSUE TITLE
Enable zoom & pan on mobile devices only with two fingers

### ISSUE THREAD

**Issue by onny** [mapbox/mapbox-gl-js#6465] opened 2018-04-06 12:24 UTC
**mapbox-gl-js version**: 0.44.2

### Steps to Trigger Behavior

 1. Load mapbox gl js on mobile devices with touch input
 2. It's possible to pan & zoom within the map
 3. Difficult to scroll the page down if input is handled by the map

### Expected Behavior
I would like to see the feature of pan & zoom the map only when using two fingers. Inputs with only one finger should be ignored.

### Actual Behavior
Scroll event inside the map area is always handled by mapbox gl js on mobile browsers, regardless of how many fingers are used.

**Comment by mollymerp** [comment] 2018-04-06 16:53
Thanks for the request @onny. This is a duplicate of #2618 so I'm going to close this issue to keep conversation centralized over there.

**Closed by mollymerp** 2018-04-06 16:53 UTC
