### ISSUE TITLE
Uncaught ReferenceError: _createClass is not defined (Angular 11)

### ISSUE THREAD

**Issue by tanu1208** [mapbox/mapbox-gl-js#10268] opened 2021-01-08 09:43 UTC
Hi, 

I am currently using Angular 11 in my app and I am receiving an error which states: 

Uncaught ReferenceError: _createClass is not defined
![image](https://user-images.githubusercontent.com/17740726/104000160-1ee5ee80-519e-11eb-9879-0212bf48c111.png)
![image](https://user-images.githubusercontent.com/17740726/104000305-56549b00-519e-11eb-9441-a92e593c1382.png)

Is this a known issue? and it seems that this issue does not occur in Angular 11. Is mapbox not compatible with angular 11?
Does anyone have a fix for this? or is there going to be a fix soon?

The implementation is based on this: https://docs.mapbox.com/mapbox-gl-js/example/navigation/

**Comment by mourner** [comment] 2021-01-08 12:19
This is a known issue — duplicate of #10173. The latest summary of the workarounds [can be found here](https://github.com/mapbox/mapbox-gl-js-docs/blob/6d91ce00e7e1b2495872dac969e497366befb7d7/docs/pages/api/index.md#transpiling-v2) (to be merged into the official docs shortly).

**Closed by mourner** 2021-01-08 12:19 UTC

**Comment by SourceCipher** [comment] 2021-08-05 08:31
Its not fixed and seems like there is no solution for this yet as we tried to run the example code and it worked fine, but as soon as we implemented it in our typescript project it never works no matter what configuration we pass or even if we add a very basic code
