### ISSUE TITLE
queryRenderedFeatures returning different feature array order on Chrome v70

### ISSUE THREAD

**Issue by livemixlove** [mapbox/mapbox-gl-js#7483] opened 2018-10-25 19:10 UTC
In a software product I work on, after our users upgraded from Chrome v69 to v70, the order of features returned from queryRenderedFeatures is reversed.  We made no changes to our codebase during this time.  This is only on Chrome v70.  No changes in behavior of queryRenderedFeatures can be seen in latest Firefox.  

I tried to create a minimal case here: https://jsbin.com/yomusefaxe/edit?html,console,output
The idea was that in Chrome 70 and mapboxgl 50 the returned array of features would be reversed.  However, if you watch the console, you will see the returned array is in the correct order.

I wasn't able to reproduce the behavior in the minimal case.  So, something I don't understand is going on.

Any other reported issues with Chrome 70?  I'm sorry I don't have a more comprehensive bug report, but I will update here if I can figure out why chrome 70 is behaving differently for us.

**Comment by ChrisLoer** [comment] 2018-10-25 19:31
This is the first I've heard of problems related to Chrome v70 but hey I haven't even updated yet. In your jsbin, you're looking at fill layers -- is that the layer type you're having trouble with in your actual application as well? The behavior can be quite different between different layer types.

You can see from the documentation of `queryRenderedFeatures` that there are a fair number of caveats (https://www.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures). It's complex enough that we don't have a single defined sort order, although the guiding principle is "sort by descending z-order". The sort order _has_ changed in subtle ways between different versions of GL JS (I have no idea why it would change based on browser version, that sounds pretty unexpected). How/why are you dependent on the order of the results?

**Comment by livemixlove** [comment] 2018-10-25 20:43
Thanks for the response, Chris!

The features we're dealing with are lines and points, so I should update the jsbin to reflect that and see if anything is different.  It didn't occur to me that would make a difference.  

> How/why are you dependent on the order of the results?

Assuming it works as advertised in the API, then it's a convenient way to know what feature is stacked on top, which is usually what you want to click on in a UI.  But it's clear to me now that we should guarantee ordering through another mechanism.

**Comment by ChrisLoer** [comment] 2018-10-25 20:55
> The features we're dealing with are lines and points

That sounds like the type of underlying geometry, I actually meant what type of "style layer" (the term "layer" is too ambiguous...). So, especially "symbol" layers (text and icons) behave very differently from other layer types in `queryRenderedFeatures`.

> it's a convenient way to know what feature is stacked on top

That sounds like what the results order is intended for -- that is, it's supposed to have a real correlation with the order things are shown on the map, but we're also hoping your code won't break if (for example) the sort order of two items next to a tile boundary get swapped.

Let us know if you're able to isolate a reproduction case -- we'd definitely want to check that out and get to the bottom of it.

**Comment by mourner** [comment] 2018-11-22 15:13
Unfortunately I have to close the issue because we're not able to diagnose this without a minimal reproducible test case.

**Closed by mourner** 2018-11-22 15:13 UTC
Labels: needs information :pray:
