### ISSUE TITLE
Significant flickering when panning back and forth across antimeridian

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#6315] opened 2018-03-12 15:53 UTC
When panning across the antimeridian, labels disappear and fade back in, and other layers flicker badly.

![flicker](https://user-images.githubusercontent.com/98601/37294181-78bff0cc-25d2-11e8-9fb8-f79ee5fc08e8.gif)

Raised in https://github.com/mapbox/mapbox-gl-js/issues/1834#issuecomment-372177266 where @bfrengley provided a fiddle: http://jsfiddle.net/wodvrjj0/8/.

My understanding is that viewport label placement means we can no longer share buckets across the antimeridian, but it still shouldn't flicker like this.

cc @ChrisLoer @ansis

**Comment by andrewharvey** [comment] 2018-03-13 22:57
PS. This is the issue we discussed in #4451

**Comment by ansis** [comment] 2018-03-21 18:29
This issue was actually more interesting than it seemed. WIP is in the `fix-antimeridian-flicker` branch.

- the basic panning flickering was caused by a bug in adding from the cache. (fixed)
- even with that fixed, the jsfiddle flickers because the tiles don't have time to load before being aborted. I think this behavior is fine because it wouldn't get hit in normal use and any fixes I can think of would have significant downsides. (wontfix)
- the cache only accepts one tile with a key, which isn't the core problem, but something that occasionally gets hit. The cache was changed to support multiple values with the same key. (fixed)
- there was no support for adding matching wrapped tiles from the previous frame's set of tiles. Adding wrapped tiles only worked for adding from the cache. There is a bit of complexity around preferring exact matches to avoid flickering. (mostly fixed)
- label flickering. When the viewport coords get wrapped and a tile gets assigned a new id, the actual `Tile` covering the same (similar) area on screen may change, resulting in a lack of label placement data and flickering. (todo)

**Comment by ansis** [comment] 2018-03-30 23:30
https://github.com/mapbox/mapbox-gl-js/commit/c66c5b30c23596dba7fa1be42076d79866506ad1 fixes the symbol flickering (last outstanding issue). I still need to clean it up before opening a pr.

**Comment by anandthakker** [comment] 2018-03-30 23:38
@ansis note that because of https://github.com/mapbox/mapbox-gl-js/pull/6303#issuecomment-377641568, `master` may be ahead of the 0.45 release, so when you open a PR, could you do it against `release-0.45` instead of master?

**Closed** 2018-04-18 15:46 UTC
Labels: bug :beetle:
