### ISSUE TITLE
Rollover effect with 0.45

### ISSUE THREAD

**Issue by phiphou** [mapbox/mapbox-gl-js#6278] opened 2018-03-03 16:00 UTC
Will 0.45 support the same behavior as 0.41 for a rollover effect on a POI ? 

See https://github.com/mapbox/mapbox-gl-js/issues/6163#issuecomment-370156943

**Comment by jfirebaugh** [comment] 2018-03-05 15:43
> Will 0.45 support the 0.41 behavior without setting setting `"icon-ignore-placement"` and `"text-ignore-placement"` on the markers layer to true ? 
> 
> I want this sample [https://jsfiddle.net/d8qs32pw/3/](https://jsfiddle.net/d8qs32pw/3/) to work like in the 0.41. (zoom in this sample to see the two markers). 
>
> I want the markers not to overlap and having the rollover effect.
>
> If not possible it's a regression don't you think ? 

@ChrisLoer I think this may be a duplicate of #5836. Can you take a look?

**Comment by ChrisLoer** [comment] 2018-03-05 19:03
Yeah, I'm going to close as a duplicate of #5836. Working off of #6028 I did a test where I added the "hover" layers to a "hover" collision group (to reproduce the previous collision-detection effect of them being in a different source), and I could reproduce the previous (v.41) behavior.

One further thing I had to do was to set `text/icon-allow-overlap` to `true` for the hover layers (but not the markers themselves). This is necessary to make the hover layer appear immediately instead of waiting for the next placement (up to 300ms, plus time for fade-in animation). At least in this case, that's not an issue because we're relying on the collision behavior of the original markers, and by the time we create a hover layer, we know that we want it to display.

**Closed by ChrisLoer** 2018-03-05 19:03 UTC

**Comment by phiphou** [comment] 2018-03-07 12:24
Do you mean this sample https://jsfiddle.net/d8qs32pw/11/ will work as expected ? (no `icon-ignore-placement` and `text-ignore-placement` to `true` and a blue text when hovering the either the text and the icon)

I don't understand what is a collision group ? Do you have an example ? (two  close markers, viewing one at lower zoom and two at higher zoom with the text in blue rollover effect)

**Comment by ChrisLoer** [comment] 2018-03-07 18:13
@phiphou yeah, I was able to get the sample working as it did before by setting the layout properties `text-collision-group` and `icon-collision-group` for the hover layers to "hover" (any name works, the point is just to make collision detection for those items be handled separately from collision detection for everything else).

But the "collision group" feature hasn't been implemented in `master` yet (it's on the `collision-groups` branch, and I think the branch might be stale right now). We're still trying to figure out what the right behavior is for that feature -- but we know we have to do something that works for your use case.
