### ISSUE TITLE
Custom layers: Support custom ES6 classes

### ISSUE THREAD

**Issue by shayke** [mapbox/mapbox-gl-js#8205] opened 2019-04-28 07:01 UTC
**mapbox-gl-js version**: 0.53.1

### Description
According to the documentation here: https://docs.mapbox.com/mapbox-gl-js/api/#customlayerinterface
The custom layer is just an interface and I can use whatever class implementation I want.
For Example:
```
class NullIslandLayer {
    constructor() {
        this.id = 'null-island';
        this.type = 'custom';
        this.renderingMode = '2d';
    }

    myMethod1() {
        console.log('hello');
    }

    onAdd(map, gl) {
        // Do something on map add
    }

    render(gl, matrix) {
        // Do something on render
    }
}
```

Then adding it to the map:
```
map.on('load', function() {
    map.addLayer(new NullIslandLayer());
});
```

But if I do `map.getLayer('null-island')` I'm not getting my full implementation and my `myMethod` function is missing.

**Comment by asheemmamoowala** [comment] 2019-04-29 18:28
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/3713

**Closed by asheemmamoowala** 2019-04-29 18:28 UTC
