### ISSUE TITLE
Chinese text not rendering with a font that has Chinese coverage

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#1622] opened 2015-10-14 01:50 UTC
I'm trying to use the font `Noto Sans CJK TC Regular`, which should cover the unicode ranges for the values in this style layer's `text-field`, but no labels are rendered. Not sure if this is a bug or if I'm doing something wrong:

![no-chinese-labels](https://cloud.githubusercontent.com/assets/5607844/10472480/5f6ca89c-71e6-11e5-9c81-1561eff00968.png)

Perhaps this is an issue specific to [the font](https://www.google.com/get/noto/help/cjk/)?

/cc @kkaefer

**Comment by bhousel** [comment] 2015-10-14 01:53
Do you see glyph overflow errors in the javascript console?  It could be #141

**Comment by nickidlugash** [comment] 2015-10-14 02:15
@bhousel I did see these errors, and I can see in general on the map that certain characters are not showing up, but these labels *do* render using `Arial Unicode MS Regular`. Would switching the font make a difference for these errors?

**Comment by bhousel** [comment] 2015-10-14 02:41
The issue is that font glyphs must be packed into a GL texture and asian charsets can contain more glyphs than the code can currently handle.  So triggering the error is a combination of which fonts are in use, and also how crowded with labels the map is where you are testing.

**Comment by mikemorris** [comment] 2015-12-09 20:48
Dupe of https://github.com/mapbox/mapbox-gl-js/issues/141?

**Comment by bhousel** [comment] 2015-12-09 20:51
>  I did see these errors

Yes closing as a dup - will be fixed soon.

**Closed by bhousel** 2015-12-09 20:51 UTC
Labels: bug, rendering, text rendering
