### ISSUE TITLE
Shift+Zoom only zoom 1 level by 1 level under Windows

### ISSUE THREAD

**Issue by Pipoupi** [mapbox/mapbox-gl-js#3334] opened 2016-10-10 15:00 UTC
### Steps to Trigger Behavior
1. Go to https://www.mapbox.com/mapbox-gl-js/examples/
2. Try to Shift Zoom
### Expected Behavior

Should high zoom to the selected area 
### Actual Behavior

Zoom 1 level by 1 level

EDIT : Actually the shift-zoom works the 2nd time you shift-zoom

**Comment by mourner** [comment] 2016-10-10 15:31
I can't reproduce — shift-zoom works as expected the first time and all subsequent ones.

Can you reproduce consistently? What browser/OS are you using?

**Comment by Pipoupi** [comment] 2016-10-10 15:37
Well I can't reproduce it either... I close the issue & re-open if it happens again

**Comment by blq** [comment] 2016-11-15 09:29
I can reproduce this in 0.27.0 - in the _examples_ page. In my own test with a fullscreen div it works.
Maybe it's simply something odd with the example page?
Chrome 54 & Firefox 49, Windows 10.

**Comment by lucaswoj** [comment] 2016-11-16 15:18
I am unable to reproduce this on my machine (OSX + Chrome 54)

**Comment by blq** [comment] 2016-11-29 15:22
I think I got it now!
If you hold down shift key + mouse button and drag the rectangle and *keep the shift button pressed* after releasing the mouse button it fails. Releasing shift before mouse button and it works.

**Comment by jfirebaugh** [comment] 2016-12-21 02:31
I don't see any difference between keeping shift pressed or not. Both behave as expected.

**Comment by Pipoupi** [comment] 2016-12-21 13:40
I can confirm though. Without releasing shift, I've got the bug. Sometimes nothing happens, sometimes it zooms for one level.
I'm on Windows 10 & Chrome Version 55.0.2883.87

**Comment by mourner** [comment] 2017-01-12 14:33
Got another report of this in #3961. The common theme among all reported instances here seems to be Windows, although I'm quite puzzled why this can happen. Anyone with a Windows machine that can debug this further?

**Comment by x9xjdzz9** [comment] 2017-03-27 18:58
The problem is that, when the shift key is down, the KeyboardHandler._onKeyDown() method is being called repeatedly which calls the easeTo() method each time. This interferes with the call to easeTo() by the BoxZoomHandler.

To fix this all you need to do is put a return statement in the default case in the KeyboardHandler._onKeyDown() switch statement, so that it doesn't call easeTo() unless one of the zoom/pan keys is pressed.

**Comment by lucaswoj** [comment] 2017-03-28 17:58
Thanks for the diagnosis Jason! Would you mind putting together a PR? I can make the change you describe but would be unable to verify that it fixes the problem.

**Comment by x9xjdzz9** [comment] 2017-03-28 18:17
Sure, but I'm not sure how to create a PR.

**Comment by x9xjdzz9** [comment] 2017-03-31 19:44
I made the code change and am ready to push my branch, but I don't seem to have access rights.

**Comment by mollymerp** [comment] 2017-03-31 21:04
@x9xjdzz9 I think you'll need to make a personal fork and then use that to make your PR. thanks for working on this!

**Comment by mourner** [comment] 2017-04-18 11:46
This was fixed by #4533

**Closed by mourner** 2017-04-18 11:46 UTC
Labels: bug, environment-specific bug
