### ISSUE TITLE
Line-opacity result overlap effect

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#6540] opened 2018-04-19 06:33 UTC
![image](https://user-images.githubusercontent.com/16457917/38974620-67b712be-43dd-11e8-9a9d-4cc179507067.png)

As shown, there is an unexpected effect when two line across another when the line opacity is set with less than 1.

Is it possible to avoid that?

**Comment by andrewharvey** [comment] 2018-04-19 10:30
I believe this is a duplicate of #4090.

**Closed by andrewharvey** 2018-04-19 10:30 UTC
