### ISSUE TITLE
Changing icon-data is slow (setData / Map Rotate / Bearing / Icon-Rotate) Version 1.3.0 and above.

### ISSUE THREAD

**Issue by Stefano191** [mapbox/mapbox-gl-js#8994] opened 2019-11-19 18:42 UTC
**I've recently switched from Mapbox gl js version 1.2.1 to 1.3.0 and later on to 1.5.0, i encountered a weird bug and i cant figure out why this happens:**

So i got a Android Application with a Locationmanager which sends location updates every 750ms through a webview. Then i convert these coordinates to a latlng object and center the map and a icon arround these coordinates, i also calculate the bearing with Turf.js and rotate the map + the icon and set the map pitch to 60. 

I update the icon-data with setData();

The normal(expected) behavior is shown below, the map + the icon centers around the black square which indicates the center of the map. **(Version 1.2.1):**

[Click here](https://gfycat.com/anyshamelessassassinbug)

The weird behavior is shown below, the map centers correctly including the bearing/pitch but the icon isnt "following" the coordinates that are provided to him, it has a delay or something and after some time it catches up but still isnt centered(its a bit off), eventually it falls back again and i cant see it anymore and somehow freeze's and later catches up again. **(Version 1.3.0 and above):**

[Click here](https://gfycat.com/familiarweeklyhydatidtapeworm)

The delay or the "freezing" happens less if i dont pitch the map or rotate it, but still occurs. This also happens with a line with two points (A and B), but it is more accurate than the normal icon which isnt following most of the times or with a big delay.

Is there something changed in version 1.3.0 or above(all other versions have this same problem) or is this a bug, quz i cant seem to find out what the problem is.

Thanks for reading,
_Stefano_

**Comment by ryanhamley** [comment] 2019-11-19 19:20
Are you able to reproduce this error in a minimal Javascript example that you could share (e.g. on JSBin)? I don't see anything obvious in the 1.3.0 changelog that might have changed this behavior and it's very hard to say what is happening without a reproducible case.

**Comment by Stefano191** [comment] 2019-11-19 19:43
> Are you able to reproduce this error in a minimal Javascript example that you could share (e.g. on JSBin)? I don't see anything obvious in the 1.3.0 changelog that might have changed this behavior and it's very hard to say what is happening without a reproducible case.

This is a small test:
http://historicalwartracker.com/android/dynamic-new-test-slow.php

The weird thing is: this only happens in the Android Webview, not on my computer and not on the normal internet browser on my smartphone/tablet.

**Comment by Stefano191** [comment] 2019-11-19 19:49
> > Are you able to reproduce this error in a minimal Javascript example that you could share (e.g. on JSBin)? I don't see anything obvious in the 1.3.0 changelog that might have changed this behavior and it's very hard to say what is happening without a reproducible case.
> 
> This is a small test:
> http://historicalwartracker.com/android/dynamic-new-test-slow.php
> 
> The weird thing is: It only happens in the Android Webview in the application itself, not on my computer and not on the normal internet browser on my smartphone/tablet.
> 
> Update: With the Google Internet Browser on Android Smartphone(Samsung S8) it also happens, but the delay is minimal. What can cause this, because with version 1.2.1 it doesnt happen. The small test does not contain map rotation/icon rotation/bearing/pitching etc, it will get worse.

Update: Test with version 1.2.1 shows that there is no delay or minimal:
http://historicalwartracker.com/android/dynamic-new-test-slow-old.php

Even with a computer you can see a small delay with the 1.5.0 version which is this one:
http://historicalwartracker.com/android/dynamic-new-test-slow.php

**Comment by mourner** [comment] 2019-11-20 09:05
@Stefano191 can you also please try the `master` version? There was a related fix that didn't yet get into the release. #8913 (although there are some issues with it so we might need to come up with an alternative fix)

**Comment by Stefano191** [comment] 2019-11-20 10:38
> @Stefano191 can you also please try the `master` version? There was a related fix that didn't yet get into the release. #8913 (although there are some issues with it so we might need to come up with an alternative fix)

This indeed seems to fix my problem, when will this "fix" be released? And what are the issues with it?

**Comment by ansis** [comment] 2019-11-22 20:24
> @mourner This indeed seems to fix my problem, when will this "fix" be released? And what are the issues with it?

Thanks for confirming the fix!

@Stefano191 at beta of the release is scheduled for Wednesday November 27th with the final release coming out on December 4th.

I think the issue is https://github.com/mapbox/mapbox-gl-js/issues/8998 but since that is being tracked separately I'll close this issue.

**Closed by ansis** 2019-11-22 20:24 UTC
Labels: bug :beetle:, performance :zap:
