### ISSUE TITLE
Line with `line-offtset` property rendering problem

### ISSUE THREAD

**Issue by minikarma** [mapbox/mapbox-gl-js#2882] opened 2016-07-17 07:01 UTC
Hi there, seems lines with `line-offset` property are rendering not good. Especially it is noticeable on the small zooms.

**mapbox-gl-js version**: 0.21

### Steps to Trigger Behavior

 1. Add source with lines
 2. Make few style layers with different line-offsets

### Expected Behavior
Nice parallel lines on the map like transit maps.

### Actual Behavior
Not so nice lines as expected, see the demo below:
https://jsbin.com/zepoxixeze/edit?js,output

It is reproduces on both types of sources (geojson / vector) 
and it isn't depends on the amount of data or number of vertexes.

**Comment by andrewharvey** [comment] 2016-07-18 05:03
`mapbox-gl-js v0.21.0` bumped `geojson-vt` to `2.2.0` in https://github.com/mapbox/mapbox-gl-js/commit/ea3986698c2773cad9957356da7bd403d0356f0c. https://github.com/mapbox/geojson-vt/commit/a3aa2fa80b59ff993f864b94c4d23f3bda0318ad rewound polygons for vt2 compliance.

https://www.mapbox.com/mapbox-gl-style-spec/#paint-line-offset says

>positive indicates “rightwards” (if you were moving in the direction of the line) and negative indicates “leftwards.”

Prior to `geojson-vt 2.2.0` a negative line-offset value was inside the polygon, post  `geojson-vt 2.2.0` it has reversed to negative being outside the polygon.

I'm thinking it might be helpful for designers if the mapbox-gl-style-spec was specific about the association between inside/outside and positive/negative offsets when the actual geometry is polygon, not just in relation to the direction of polylines. It's useful for doing inner/outer shadow/glow effects on polygons in that case you need to know what's going to make an inner shadow vs outer shadow.

/cc @mourner

**Comment by jfirebaugh** [comment] 2016-07-18 16:24
Duplicate of #2316.

@andrewharvey, that sounds like a different issue that what was originally reported here. Can you please open a separate ticket?

**Closed by jfirebaugh** 2016-07-18 16:24 UTC
