### ISSUE TITLE
symbol icons clipped at tile boundaries

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#1271] opened 2015-06-13 22:39 UTC
![screen shot 2015-06-13 at 6 29 49 pm](https://cloud.githubusercontent.com/assets/4974151/8146199/8989e4e2-11fa-11e5-9442-8d41f7338ffe.png)

Context:
 - mapbox-gl-js version: current `master`.
 - points are in a vector tile source generated by tippecanoe
 - using the default sprite sheet, `dot.sdf`
 - using multiple style layers, setting filter in order to color based on a property value

**Comment by mourner** [comment] 2015-06-13 22:41
What's the tile buffer when generating with tippecanoe?

**Comment by anandthakker** [comment] 2015-06-13 22:53
@mourner Unsure, but I'll ask @kamicut, who generated it.

Meanwhile, I just realized that it's also happening with a GeoJSON source.

**Comment by anandthakker** [comment] 2015-06-13 23:04
Looks like it just used the default for buffer, which according to the [tippecanoe docs](https://github.com/mapbox/tippecanoe#zoom-levels-and-resolution) is 5.   The screen shot above was ~ z6-z7 or so, and `icon-size` is on a ramp: `[4, 1], [6, 2], [8, 4], [10, 8], [12, 16]`.

**Comment by jfirebaugh** [comment] 2015-06-15 04:36
Does using a larger buffer fix the issue?

**Comment by anandthakker** [comment] 2015-06-15 15:43
@jfirebaugh Will check it out with the vector tile source.  What's a good size to use?

Meanwhile, [it looks like](https://github.com/mapbox/mapbox-gl-js/blob/a9d2c42e7b1e51f763f2ace825fc61867daaa4b9/js/source/worker.js#L104) the buffer option in `geojson-vt` isn't exposed for GeoJSON sources...

**Comment by mourner** [comment] 2015-06-15 15:47
@anandthakker good call about GeoJSON, it should. Could you hardcode it there and see if the GeoJSON issue you're seeing is gone?

**Comment by ansis** [comment] 2015-06-15 18:18
It could also be that the data thinning for low zoom levels isn't consistent between tiles. If this is the case, it doesn't matter if the buffer is big enough.

Symbols that are allowed to overlap are clipped at tile boundaries so that sorting by the y position works correctly near tile boundaries: https://github.com/mapbox/mapbox-gl-native/issues/1673

If inconsistent thinning is the problem this could be fixed by:
- making it consistent (hard)
- never clipping symbols at tile boundaries and being ok with it [looking like this](https://cloud.githubusercontent.com/assets/1421652/7939740/96799a1e-091a-11e5-8250-82dedc0d1415.png)
- add some style property to enable/disable y sorting and the clipping it needs

**Comment by anandthakker** [comment] 2015-06-15 21:51
@mourner sure thing. Will check it out when I'm back at my computer.

**Comment by ericfischer** [comment] 2015-06-15 22:02
I'm pretty sure @ansis is right and the problem is that the point-dropping isn't consistent between tiles. I'm working on some line-dropping changes now in https://github.com/mapbox/tippecanoe/issues/55 that require adjacent tiles to be consistent, so maybe I could do something similar for dots.

**Comment by anandthakker** [comment] 2015-06-16 01:54
@mourner @jfirebaugh @ansis Just tried hardcoding to `buffer: 256` and it fixed the issue.  Haven't had a chance to try upping the buffer on the vector tiles, but will try to check that out soon too.

Slightly related question: where can I go to understand how these buffers work?  (So that I can get a sense of how to choose the right size?)

**Comment by anandthakker** [comment] 2015-06-16 19:23
@mourner would you be open to a PR that exposes the `buffer` option for GeoJSON sources?

**Comment by mourner** [comment] 2015-06-16 19:52
@anandthakker sure!

**Comment by ashleyclough** [comment] 2015-06-17 12:58
I've a similar example where location names as symbols appear to be being cut off on tile boundaries. Closer inspection when zooming suggests that they are not getting cut off but are being overlaid by polygons in adjacent tiles that have what look like differing z values.

See live: http://parallel.co.uk/os-openmap-gl/#13.19/50.9028/-1.3207

Also pan westwards to see the word 'Southampton' appear and disappear behind buildings.
![tile clipping example](https://cloud.githubusercontent.com/assets/912721/8207350/decc3738-14f8-11e5-84fd-d74bb5dd275a.jpg)

**Comment by mourner** [comment] 2015-06-17 15:26
@ashleyclough yeah, that looks like #757

**Comment by jfirebaugh** [comment] 2015-06-19 00:58
Addressed by #1287.

**Closed by jfirebaugh** 2015-06-19 00:58 UTC

**Comment by anandthakker** [comment] 2015-06-19 12:18
Note: #1287 dealt with this for GeoJSON sources, but it's still happening for my (tippecanoe-generated) vector tile source.

**Comment by mourner** [comment] 2015-06-19 12:46
@anandthakker yeah, but that should probably be solved on the VT side.

**Comment by anandthakker** [comment] 2015-06-19 14:02
@mourner Agreed.  Just noted it here for any future googlers :)

**Comment by donBigote** [comment] 2016-07-17 01:32
What do you do if a tile boundary clips off the corner of a polygon when you upload it as a tileset in Mapbox Studio? 
<img width="442" alt="screen shot 2016-07-16 at 1 55 18 pm" src="https://cloud.githubusercontent.com/assets/5143443/16898231/04dec24a-4b8c-11e6-9af6-5059abdf9676.png">

**Comment by lucaswoj** [comment] 2016-07-18 18:16
@donBigote this looks like a bug in Studio. I recommend [contacting our support team](https://www.mapbox.com/contact/).
