### ISSUE TITLE
Feature with icon and no title is not rendered on symbol layer

### ISSUE THREAD

**Issue by emerciercontexeo** [mapbox/mapbox-gl-js#6357] opened 2018-03-17 17:31 UTC
**mapbox-gl-js version**: latest

### Steps to Trigger Behavior

 1. Add a geojson source with a feature that have icon but no title property (or title: ' ' or title: '    ')
 2. Add a symbol layer for that source

### Expected Behavior

Display a symbol without label

### Actual Behavior

Nothing displayed.

If I add the property 'text-optional' on the layer, the icon is displayed properly but as it effects all the data of the layer, I can't use it.

Exemples  : 
No title with 'text-optional' property
![image](https://user-images.githubusercontent.com/8739777/37558174-33b1a588-2a10-11e8-8770-7562a42f71ae.png)

No title without 'text-optional' property
![image](https://user-images.githubusercontent.com/8739777/37558182-626aa672-2a10-11e8-8b9d-e3ad79e24831.png)

'_' as title with 'text-optional' property
![image](https://user-images.githubusercontent.com/8739777/37558204-ba7bbe6e-2a10-11e8-850a-4ce6a3749032.png)

'_' as title without 'text-optional' property
![image](https://user-images.githubusercontent.com/8739777/37558235-093b924a-2a11-11e8-9d8f-2aeabda3e9ad.png)

**Comment by pathmapper** [comment] 2018-03-17 17:46
Hi @emerciercontexeo, your issue sounds like it is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/6160 which has been fixed in https://github.com/mapbox/mapbox-gl-js/pull/6164.

**Comment by emerciercontexeo** [comment] 2018-03-17 17:53
Didn't found it before, thanks for reporting, I close the issue

**Closed** 2018-03-17 17:52 UTC
