### ISSUE TITLE
Symbol icon based on URL of an external asset

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1248] opened 2015-06-03 22:29 UTC
http://peterma.de/apartmentsearcher/

In this example, an API call retrieves apartment listings along with URLs for each listing's images. I would like to do this entirely with GL, instead of DOM elements. May have to anticipate different image sizes, or have a one-size-fits-all solution

**Comment by jfirebaugh** [comment] 2015-06-03 22:33
Duplicate of #358.

**Closed by jfirebaugh** 2015-06-03 22:33 UTC
