### ISSUE TITLE
Cannot get  basic mapbox example to run in IE

### ISSUE THREAD

**Issue by davidcolley** [mapbox/mapbox-gl-js#2186] opened 2016-02-25 14:58 UTC
I've written a script that uses GL-js and cannot get it to work on Internet Explorer but does on Chrome.
As an experiment, I then tried to get just the Mapbox basic example to work on IE and that fails as well :

https://www.mapbox.com/mapbox-gl-js/example/check-for-support/

It works from their own webpage but not when I copy the example code into an html file and load it. It does work on Chrome though as does my script. 

Any ideas why it won;t run on IE?
or what needs changing in the example script to get it working?

many thanks

**Comment by lucaswoj** [comment] 2016-02-25 18:11
Thanks for getting in touch with us @davidcolley. Could you please tell us

 - what version of IE you are using
 - what version of Windows you are using
 - what kind of graphics card your machine has
 - what the "basic example" page looks like when it is "not working"

**Comment by davidcolley** [comment] 2016-02-25 18:23
Hi there,

I’m using IE11 on Win7 64bit with an NVIDIA Quadro 2000M and the basic page is just blank white and does not allow any user interaction, even right click.

Not sure if it helps but when I run my .NET script that is using the standard System.Windows.Forms.Webrowser (i.e. IE) through a debugger is fails on the line where the .js script is referenced.

Thanks,

**Comment by davidcolley** [comment] 2016-02-25 18:27
Oh and...

Context Name experimental-webgl 
Platform Win32 
Agent Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 1.1.4322; .NET4.0C; .NET4.0E; InfoPath.2; rv:11.0) like Gecko 
Vendor Microsoft 
Version WebGL 0.94 
Renderer Internet Explorer 
Shading Language Version WebGL GLSL ES 0.94 

Max Vertex Attribs 16 
Max Vertex Texture Image Units 16 
Max Varying Vectors 15 
Max Uniform Vectors 512 

RGBA Bits 8, 8, 8, 8 
Depth Bits 24 

Max Combined Texture Image Units 32 
Max Texture Size 16384 
Max Cube Map Texture Size 16384 
Num. Compressed Texture Formats null 

Max Render Buffer Size 16384 
Max Viewport Dimensions 16384, 16384 
Aliased Line Width Range 1, 1 
Aliased Point Size Range 1, 300 
Supported Extensions WEBGL_compressed_texture_s3tc
OES_texture_float
OES_texture_float_linear
EXT_texture_filter_anisotropic
OES_standard_derivatives
ANGLE_instanced_arrays
OES_element_index_uint
WEBGL_debug_renderer_info

**Comment by swen100** [comment] 2016-03-22 10:47
Hi,

had the same issue. I upgraded my graphics card in my office-PC and now it works. I had a Nvidia GT 210, replaced it with a Nvidia GT 720.

I tried it out on my **Windows-Phone with IE 11** but it does not work there :(

**Comment by mourner** [comment] 2016-05-17 20:08
This likely was fixed by #1606. Please try again on master and I'll reopen if the issue persists.

**Closed by mourner** 2016-05-17 20:08 UTC
Labels: bug, machine-dependent bug

**Comment by kachkaev** [comment] 2016-07-12 18:14
Looks like the problem is there again, at least in IE11

```
Line: 206
Error: 'Uint8ClampedArray' is undefined
```

Can't see any maps on
https://www.mapbox.com/maps/
https://www.mapbox.com/mapbox-gl-js/example/check-for-support/

The second page does not alert `Your browser does not support Mapbox GL`.

**Comment by mourner** [comment] 2016-07-12 19:01
@kachkaev run update on your Windows 7. See https://github.com/mapbox/mapbox-gl-js/issues/2444#issuecomment-210001075 for more.

**Comment by kachkaev** [comment] 2016-07-12 19:27
Thanks for your reply @mourner! Makes sense.

I'm afraid I won't be able to update IE as it is on a company-managed PC. Our client is likely to have the same env, so I'll probably have to give up gl-enabled maps in this project. Very exited about your stuff after a week of exploration though!

Is `Uint8ClampedArray` issue something that requires a lot of effort to fix? Or maybe just a couple of lines of codes can do the trick? I can help you with testing in the second case but understand that you might be not willing to your time on it.

**Comment by jfirebaugh** [comment] 2016-07-12 19:30
Our [previous investigation](https://github.com/mapbox/mapbox-gl-js/issues/2444#issuecomment-211613748) suggested that there would be additional compatibility issues beyond `Uint8ClampedArray`. Please encourage your IT department to upgrade IE -- these are [important security updates](https://support.microsoft.com/en-us/kb/2929437) we're talking about.

**Comment by kachkaev** [comment] 2016-07-12 19:41
You're right @jfirebaugh, I'll see what I can do. Would it be possible to at least get `mapboxgl.supported()` working properly in that version of IE? Requested here: https://github.com/mapbox/mapbox-gl-js/issues/2504. According to a couple of issues I discovered in your repo, it seems that some quite a few potential users can have the same unpatched version of IE. Would be good to be sure that at least a `please update` message is shown correctly in any environment.

**Comment by jfirebaugh** [comment] 2016-07-12 19:49
Yep, agreed. We have an issue tracking that: https://github.com/mapbox/mapbox-gl-supported/issues/1
