### ISSUE TITLE
Features lose IDs in queryRenderedFeatures after setData with promoteId

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#13165] opened 2024-04-29 06:39 UTC
**mapbox-gl-js version**:
3.0.0

**browser**:
Chrome

### Steps to Trigger Behavior

 1. Load the map with a GeoJSON layer that has two features and `promoteId: 'submissionID'`.
 2. Use `setData` to update the GeoJSON source with additional features.
 3. Query rendered features on a map click and check the console for feature IDs.

### Link to Demonstration

https://jsfiddle.net/iaezzy/5cphq7nd/1/

### Expected Behavior

When querying rendered features after updating the GeoJSON source, the returned features should retain their IDs specified by the `promoteId`.

### Actual Behavior

After updating the GeoJSON source using `setData`, querying rendered features returns features without their IDs, despite using `promoteId` to specify the property that should map to the feature ID.

A similar issue has been reported before which is probably still not fixed: https://github.com/mapbox/mapbox-gl-js/issues/10257

**Comment by stepankuzmin** [comment] 2024-07-25 13:38
Hey @3zzy,

At first, I considered this to be a bug, but it seems that the features in your test case are missing the `submissionID` property that you are expecting to be used with `promoteId.` If you add the `submissionID` property to the features, it seems to be working as expected. I will close this issue, but feel free to comment with an updated reproducible test case and I'll reopen if we could confirm the bug.

**Closed by stepankuzmin** 2024-07-25 13:38 UTC
Labels: bug :lady_beetle:
