### ISSUE TITLE
map.getLayer(id), and then map.addLayer(returned layer object) throws errors of undefined options

### ISSUE THREAD

**Issue by xli711** [mapbox/mapbox-gl-js#4796] opened 2017-06-06 22:03 UTC
**mapbox-gl-js version**: 0.37.0

### Steps to Trigger Behavior

 1. Layer object returned from map.getLayer("layer id"), options like maxzoom, minzoom, filter were not defined in original layer
 2. map.setStyle(), then map.addSource("source id", source)
 3. map.addLayer(layer object)

### Expected Behavior
original layer added back to new style

### Actual Behavior
throws errors: 
"<layer id>.minzoom: number expected, undefined found",
"<layer id>.maxzoom: number expected, undefined found",
"<layer id>.paint.fill-color: color expected, array found",
...

**Comment by jfirebaugh** [comment] 2017-06-06 22:34
Duplicate of #3713.

**Closed by jfirebaugh** 2017-06-06 22:34 UTC
