### ISSUE TITLE
Is `showTileBoundaries` reporting correctly?

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#8923] opened 2019-10-29 18:45 UTC
**mapbox-gl-js version**: `v1.4.0`

### Question

I might be confused over how this works but It looks like both the reported tile coordinates and boundary lines are confusing.

If I browse around `#17/35.678226/139.738022` I see a boundary reporting tile coordinates at `17/58205/25807`:

<img width="1026" alt="Screen Shot 2019-10-29 at 2 41 39 PM" src="https://user-images.githubusercontent.com/61150/67798734-734df400-fa5a-11e9-9e19-dce2019f846d.png">

But the coordinates for the tile request is actually: `17/116411/51614`. So with slight rounding, values are multiplied.

`https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/512/17/116411/51614@2x?access_token={Add token here}`

![51614@2x](https://user-images.githubusercontent.com/61150/67798314-a643b800-fa59-11e9-9b84-7decdf911227.png)

---

Should these be at parity with one another?

### Links to related documentation

Here's a quick test case: https://jsfiddle.net/tristen/6f0c9qzp/

**Comment by asheemmamoowala** [comment] 2019-10-30 06:14
@tristen this is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/5535, and is solved by https://github.com/mapbox/mapbox-gl-js/pull/7314 which looks like it is seeing some movement this week.

**Closed by asheemmamoowala** 2019-10-30 06:14 UTC
