### ISSUE TITLE
Broken links on API documentation (lowercase URL hashes)

### ISSUE THREAD

**Issue by IvanSanchez** [mapbox/mapbox-gl-js#4016] opened 2017-01-19 14:42 UTC
- Point a browser to https://www.mapbox.com/mapbox-gl-js/api/#Map#jumpTo
- Click on the `options(CameraOptions)` link 
- Notice how the link points to `#cameraoptions` instead of `#CameraOptions`

The same applies to any link of parameter types or option types, like links to `LngLatLike` or `Point`.

I cannot be sure if this is a bug in the docstrings in this repo, or if this is an upstream bug in @tmcw 's [documentationjs](https://github.com/documentationjs/documentation).

**Comment by jfirebaugh** [comment] 2017-01-19 18:56
Duplicate of #3680.

**Closed by jfirebaugh** 2017-01-19 18:56 UTC
