### ISSUE TITLE
setLayoutProperty(...,'symbol-placement', 'line') messes up text drawing

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4307] opened 2017-02-21 05:01 UTC
Not sure if this is a Studio or a GL-JS bug.

**mapbox-gl-js version**:

0.32.1 (I assume)

### Steps to Trigger Behavior

 1: Create a layer referencing a polygon dataset, of type Symbol

 2: Set text properties so it's visible (with default placement of Point)

![offleash3](https://cloud.githubusercontent.com/assets/678344/23151475/e7a9b336-f84e-11e6-8f52-af1da71d4e79.png)

 3: Switch placement to Line

### Expected Behavior

Text draws along edges of polygons.

![offleash5](https://cloud.githubusercontent.com/assets/678344/23151478/f4ec977a-f84e-11e6-8f28-8144c14c6ac6.png)

### Actual Behavior

Text draws...wrongly. Hard to describe - it's on the edges of something that is not the polygon geometry.

![offleash4](https://cloud.githubusercontent.com/assets/678344/23151479/f9f1ad5a-f84e-11e6-995d-74a431869507.png)

Refreshing fixes the problem.

**Comment by mollymerp** [comment] 2017-02-21 20:46
@stevage thanks for the report! Does this only happen in studio (i.e. not when you use `setLayoutProperty` to change [`symbol-placement`](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-symbol-placement) in gl-js?

**Comment by stevage** [comment] 2017-02-21 21:10
[Yes](https://bl.ocks.org/stevage/raw/d8041ae7d052cdc8ce9f45b9c07102f2/).

**Comment by jfirebaugh** [comment] 2017-03-02 04:39
Duplicate of #3171.

**Closed by jfirebaugh** 2017-03-02 04:39 UTC
Labels: bug
