### ISSUE TITLE
Tiles don't show up unless zoomed

### ISSUE THREAD

**Issue by divya1c** [mapbox/mapbox-gl-js#6130] opened 2018-02-11 20:55 UTC
I have a mapbox gl js map which gets tiles from my nodejs tile server (uses tippecanoe to make tiles and tilelive to load). The tiles don't show up when I refresh my page, unless I tinker with the map. 

Here's the video of the issue: There are around 10000 features in this view.

![ezgif com-optimize](https://user-images.githubusercontent.com/16343652/36078396-5a4600c8-0f2a-11e8-9f82-96bbad919b6b.gif)

**Comment by anandthakker** [comment] 2018-02-12 14:19
Thanks for reporting this issue!

Could you please provide self-contained example reproducing this issue?   Having an example to work with will make it much more likely that we can successfully diagnose and solve the problem.

**Comment by stevage** [comment] 2018-02-14 06:26
Are you running without a TileJSON endpoint by cahnce? I have run into issues like that in the past when operating without a tileJSON file. Mapbox-GL-JS really doesn't behave well when it doesn't know the exact range at which tiles are available.

**Comment by divya1c** [comment] 2018-02-20 21:36
@stevage I do have an endpoint pointing to my server that serves tiles: 
```
'tiles': ['http://localhost:7777/{z}/{x}/{y}']
```
What do you mean by it should know the exact range at which tiles are available? 

@anandthakker - i will try to make an example.

**Comment by stevage** [comment] 2018-02-21 02:54
@divya1c Mapbox-GL-JS needs to know whether tiles are available at say, zooms 8-13, so if you try to display a tile at zoom 14, it will request the tile at 13 and overzoom it. Otherwise it will try to request 14 and fail.

**Comment by jfirebaugh** [comment] 2018-02-26 16:33
@divya1c If you find time to create an example, let us know. Closing for now since without that, this isn't something we can diagnose.

**Closed by jfirebaugh** 2018-02-26 16:33 UTC
Labels: needs information
