### ISSUE TITLE
Unrotated one-way arrows along tile boundaries

### ISSUE THREAD

**Issue by bhousel** [mapbox/mapbox-gl-js#1461] opened 2015-09-04 01:19 UTC
Sometimes vertical or horizontal oneway markers appear where they shouldn't.

<img width="889" alt="screenshot 2015-09-03 21 15 21" src="https://cloud.githubusercontent.com/assets/38784/9674641/2f74cfae-5281-11e5-9395-0d9ab83516b1.png">

<img width="884" alt="screenshot 2015-09-03 21 18 26" src="https://cloud.githubusercontent.com/assets/38784/9674656/5c50325c-5281-11e5-8ad6-1552252b60bd.png">

**Comment by 1ec5** [comment] 2015-09-04 01:53
This isn’t limited to gl-js; it’s coming out of the vector tiles somehow. We’ve been tracking this regression internally. We suspect mapbox/mapnik-vector-tile but haven’t had the bandwidth to verify that that’s where the issue lies.

**Comment by 1ec5** [comment] 2015-09-30 22:26
Although the issue also affects gl-native, mapbox/mapbox-gl-native#2474 shows that this is a regression in both projects, not an issue with the vector tiles.

**Comment by 1ec5** [comment] 2015-09-30 22:29
This is a very common issue, impacting maybe half of all one-way streets in urban areas I’ve spot-checked. This isn’t only about one-way markers, either: if you go to 37.35302°, -121.90429° at z20, you’ll find a street that takes an abrupt jog at a tile boundary.

**Comment by 1ec5** [comment] 2015-10-01 19:45
This regression is caused by #1283.

**Comment by 1ec5** [comment] 2015-10-07 19:54
#1575 exacerbates this bug, because the roads really are going the wrong direction.

**Comment by 1ec5** [comment] 2015-11-11 22:09
Closing in favor of #1575, now that #1604 has been merged.

**Closed by 1ec5** 2015-11-11 22:09 UTC
Labels: bug, rendering
