### ISSUE TITLE
Hover effect is space delayed when circle radius is a function 

### ISSUE THREAD

**Issue by PBrockmann** [mapbox/mapbox-gl-js#5470] opened 2017-10-16 16:56 UTC
A simple example to produce an hover effect when mouse is over a circle would be welcomed. 
Following https://www.mapbox.com/mapbox-gl-js/example/hover-styles/ helps to produce a map with an
over effect but only when the mouse is over the center of the circle. Not over the all disk.

**Comment by PBrockmann** [comment] 2017-10-17 12:00
I have prepared a jsfiddle and it seems that the problem occurs when a zoom function is used.
When the circle radius is set as a constant, the hover effect runs as soon as the mouse is inside the disk.
This is not the case when a zoom function is used. In this case, you have to move close to the center of the disk to get the hover effect. I would like to get rid off the behaviour.

The jsfiddle is avaible from: https://jsfiddle.net/PBrockmann/xwp7ns7h/

When radius is a constant ---> hover effect is ok as soon as mouse is inside the disk
![m1](https://user-images.githubusercontent.com/5402758/31663705-4cbca8c8-b343-11e7-93c7-b61a2ba0c003.gif)

When radius is a function ---> hover effect is delayed and you need to move the cursor close the center of the disk to trigger it
![m2](https://user-images.githubusercontent.com/5402758/31663706-4cddaec4-b343-11e7-91e5-9c921dd39dc7.gif)

**Comment by jfirebaugh** [comment] 2017-10-17 16:27
Duplicate of #5016.

**Closed by jfirebaugh** 2017-10-17 16:27 UTC

**Comment by PBrockmann** [comment] 2017-10-17 20:26
Ok for the duplicate issue. 
But sorry I do not understand if there is a workaround.
