### ISSUE TITLE
Feature-state: 0/false values are translated to null

### ISSUE THREAD

**Issue by feinblat** [mapbox/mapbox-gl-js#8893] opened 2019-10-23 17:23 UTC
In 
https://github.com/mapbox/mapbox-gl-js/blob/master/src/source/source_state.js
line 46

                for (const prop in this.state[sourceLayer][feature]) {
                    **if (!newState[prop]) this.deletedStates[sourceLayer][feature][prop] = null;**
                }

if prop value is zero/false the assigned value is null.

**Comment by arindam1993** [comment] 2019-10-23 21:37
Hi @feinblat , could you please elaborate on how this causes undefined behavior in your use case?

**Comment by feinblat** [comment] 2019-10-24 11:12
I set certain feature state property to certain value and write the
layer paint property according to it but the actual value is different.

for example:
if set feature-state - my-state prop to 0
the layer filter looks like:
'line-color': {
    'case',  
    ['==', ['feature-state', 'my-state'], 0], #0000ff,
    #ff0000 . 
}

but feature-state my-state property is not 0 but null due to the bug and the line color is red and not blue in this case.

**Comment by arindam1993** [comment] 2019-10-24 19:36
Thanks @feinblat , I tried using an expression similar to your's withe the hover on states example but I was unable to reproduce the issue.

https://jsfiddle.net/y9conjr6/2/

**Comment by mourner** [comment] 2019-11-04 09:30
Closing since a reproducible test case wasn't provided.

**Closed by mourner** 2019-11-04 09:30 UTC
Labels: needs information :pray:
