### ISSUE TITLE
Performance issue when I try to animate multiple points

### ISSUE THREAD

**Issue by Cmaxd** [mapbox/mapbox-gl-js#5618] opened 2017-11-08 12:51 UTC
I try to animate the position of multiple points (100,000 or more)，follow the official example, by updating a GeoJSON source.
The actual performance is bad (FPS is very low), so I want to know the bottleneck of animate multiple points or  get some suggestions for optimization.

Here is my test code on JSFiddle:
[https://jsfiddle.net/Cmaxd/w2frv0ns/5/](https://jsfiddle.net/Cmaxd/w2frv0ns/5/)

**Comment by jfirebaugh** [comment] 2017-11-08 20:23
Hi @Cmaxd -- unfortunately, I don't know of a current way to get fast performance animating that many points. We have a number of issues tracking performance improvements to `setData` -- #2275, #3692, #4271, #3812. Closing as a duplicate of those issues.

**Closed by jfirebaugh** 2017-11-08 20:23 UTC
