### ISSUE TITLE
Touch panning and pinch zoom doesn't work on Edge browser

### ISSUE THREAD

**Issue by hellkama** [mapbox/mapbox-gl-js#4732] opened 2017-05-22 09:00 UTC
**mapbox-gl-js version**: v0.37.0

Tested on two tablet devices with Windows 10 (Surface Pro 2 and random Acer). Latest Edge browser version 40.15063.0.0 (Windows Creators update).

### Steps to Trigger Behavior

 1. Try panning map with touch
 2. Try zooming map with two finger pinch

### Expected Behavior
Map pans and zooms per user input

### Actual Behavior
When panning page scrolls or triggers browser's back/forward behavior.  When zooming the page zooms but the map doesn't.

**Comment by anandthakker** [comment] 2017-05-26 05:10
Thanks for reporting this issue @hellkama.  Could you confirm whether you see this problem on [this example page](https://www.mapbox.com/mapbox-gl-js/examples/)?

**Comment by hellkama** [comment] 2017-05-26 08:42
@anandthakker I can confirm the same problem exists on the example page.

**Comment by anandthakker** [comment] 2017-05-26 12:48
Thanks @hellkama!

**Comment by jfirebaugh** [comment] 2017-09-30 00:47
Duplicate of #1928.

**Closed by jfirebaugh** 2017-09-30 00:47 UTC
Labels: environment-specific
