### ISSUE TITLE
Map does not render on one certain computer in Chrome

### ISSUE THREAD

**Issue by peterbodo** [mapbox/mapbox-gl-js#2178] opened 2016-02-24 10:52 UTC
### Context

* **mapbox-gl-js version**:  
all

### Report

**Expected behavior**: 
map renders

**Actual behavior**: 
map UI: **gray background**, 
grabbing, Hash, Controls work as expected.
IE works fine.
Chrome with factory settings or even newly installed Chrome does not work.
This happens only in one computer (as we know) and happens with any mapboxgl map (even examples on the Mapboxgl website)
No error messages in console.

**Steps to reproduce the behavior**:

_Need help here..._

* **link to example**:
e.g. https://www.mapbox.com/mapbox-gl-js/examples/

**Comment by averas** [comment] 2016-02-24 12:01
Are you sure this computer supports accelerated 3D graphics and webgl?

http://webglreport.com/

**Comment by peterbodo** [comment] 2016-02-24 12:16
The same computer works fine with IE.

No webgl error is displayed.
Not even the alert on mapbox examples page.

**Comment by peterbodo** [comment] 2016-02-24 12:41
@averas 

WebGlReport test from the same browser/computer

![pasted image at 2016_02_24 01_28 pm](https://cloud.githubusercontent.com/assets/14811093/13285699/466e8db8-dafc-11e5-8abb-7acfcc8a58d9.png)

**Comment by peterbodo** [comment] 2016-02-24 15:29
![pasted image at 2016_02_24 12_22 pm](https://cloud.githubusercontent.com/assets/14811093/13290403/bbf713b8-db13-11e5-8579-a70e8bd27a34.png)

**Comment by akshaykapadia** [comment] 2016-03-01 04:20
I'm having same problem. Maps are not getting rendered only on my machine, it works fine everywhere else. what could be the possible issues?

**Comment by bhousel** [comment] 2016-03-01 04:28
@akshaykapadia, @peterbodo, can you try the troubleshooting steps listed here?
http://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser

**Comment by akshaykapadia** [comment] 2016-03-02 00:30
Thanks @bhousel .

I tried that solution, all looking good but still not working.

thanks and really appreciate your help.

**Comment by bhousel** [comment] 2016-03-02 03:17
What does it say when you browse to `chrome://gpu/`
Any issues there?

**Comment by akshaykapadia** [comment] 2016-03-02 03:42
For webgl it shows, hardware accelerated. 
So i think no problem there.

Webgl is enable and wired thing is that, it does work in IE 11 and safari too.

Just not working on chrome or firefox.

**Comment by peterbodo** [comment] 2016-03-04 11:03
same story here. hardware accelerated. IE works, Chrome doesn't.
I guess it is not a webgl issue, because there is no related error in the console.

**Comment by indus** [comment] 2016-03-10 08:21
I had the same issue, until I updated the driver of my graphics card. Other WebGL stuff was working normal in chrome, but not the rendering of mapbox-gl-js maps. Now it works fine.

**Comment by lucaswoj** [comment] 2016-03-10 18:54
Sounds like this behavior is being caused by some system-specific problems. I don't see anything actionable for us other than documenting some troubleshooting steps (like updating graphics card drivers).

**Comment by peterbodo** [comment] 2016-03-10 19:31
@lucaswoj 
I guess the problem is too frequent to omit and it is not about webgl support in general, only Mapbox gl.
With my friend it was with an up to date NVidia Geforce 310M that Mapbox gl did not work (but webgl tests were fine). When he disabled it and worked with the less adnvanced motherboard chip (Intel (r) hd), it has worked.

**Comment by MichaelMarkieta** [comment] 2016-03-16 10:49
@ansis we have been finding similar issues to this on our machines at Arup. Seems to be hardware related. What can I give you to troubleshoot? I can test this on maybe 10 different machine configurations.

**Comment by ckc11** [comment] 2016-03-18 22:16
It looks like the latest version of Chrome, 49.0.2623.87 m, broke mapbox-gl maps for me.  None of the maps even on the example pages work properly anymore.

**Comment by ansis** [comment] 2016-03-18 22:46
When you open https://jsbin.com/resupaxepi/edit?html,output it should log something like this to the javascript console:
```js
contextAttributes Object {alpha: true, antialias: false, depth: true, failIfMajorPerformanceCaveat: false, premultipliedAlpha: true…}`
```
Can you paste what it prints for you?

----

@MichaelMarkieta @ckc11 it would also be helpful if you could open http://webglreport.com/ on a machine it doesn't work on and copy the contents to a [gist](http://gist.github.com). Thanks!

**Comment by ckc11** [comment] 2016-03-18 22:55
```
alpha: true
antialias: false
depth: true
failIfMajorPerformanceCaveat: false
premultipliedAlpha: true
preserveDrawingBuffer: false
stencil: true
```

**Comment by ckc11** [comment] 2016-03-18 22:58
![image](https://cloud.githubusercontent.com/assets/7947207/13894149/2f572116-ed22-11e5-86e3-4b83fe951520.png)

**Comment by ckc11** [comment] 2016-03-23 20:32
Are we getting any closer to figure out what is the issue and what the solution may be?

**Comment by lucaswoj** [comment] 2016-03-28 16:52
I’m not sure there’s much we can do here. Even if we figure out ​_why_​ rendering is broken, there’s a low chance we can fix it.

The problem is likely caused by either a bug in the graphics drivers OR a missing capability on the graphics card.

Anything to add @ansis @mourner @jfirebaugh @bhousel?

**Comment by mourner** [comment] 2016-03-28 16:57
Totally random thought but there's a chance the bug could trigger by the way we render polygons — can someone check whether `earcut-final` branch has the same symptoms on affected machines?

**Comment by ansis** [comment] 2016-03-28 17:39
> The problem is likely caused by either a bug in the graphics drivers OR a missing capability on the graphics card.

It could be this, or we could be relying on something that is undefined or not guaranteed. It's hard to tell.

@ckc11 can you run https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html and let us know if any of them fail for you?

**Comment by ckc11** [comment] 2016-03-28 17:49
Attached are the results, thanks for looking into this.  I have several other users in the office who have similar issues (hardware+chrome issue) if you need me to run tests on other computers (with diff hardware).

[WebGL Conformance Tests.zip](https://github.com/mapbox/mapbox-gl-js/files/192205/WebGL.Conformance.Tests.zip)

**Comment by ansis** [comment] 2016-03-28 18:03
> if you need me to run tests on other computers (with diff hardware).

This would be helpful!

**Comment by ckc11** [comment] 2016-03-28 18:58
Here is another output of the khronos webgl conformance tests run on a different computer.

Interestingly, on this computer, the main www.mapbox.com/maps page works, but none of the examples in https://www.mapbox.com/mapbox-gl-js/examples/ work (all the maps are blank).  Possibly different versions of mapbox-gl-js between the main page and the examples?

[webgl-test-machine2.zip](https://github.com/mapbox/mapbox-gl-js/files/192294/webgl-test-machine2.zip)

**Comment by peterbodo** [comment] 2016-04-06 20:02
Now we just have another computer in the team, which supports webgl but cannot render Mapboxgl

The results:
[webgl-tests-dell.zip](https://github.com/mapbox/mapbox-gl-js/files/207242/webgl-tests-dell.zip)

**Comment by akshaykapadia** [comment] 2016-04-07 02:25
![glresult](https://cloud.githubusercontent.com/assets/17561109/14338618/a2f63d2a-fcbb-11e5-80fc-3ce43bd1d163.PNG)

I've attached test result of https://jsbin.com/resupaxepi/edit?html, everything looks alright still not working.

**Comment by peterbodo** [comment] 2016-04-20 14:08
So our problem is solved in both computer, which we had problem with.
We have found this issue:
[https://github.com/mapbox/mapbox-gl-js/issues/2270](https://github.com/mapbox/mapbox-gl-js/issues/2270)

And pitching the map really solved the problem.
Now, we go with this ugly workaround:
		map.setPitch(1);
		map.setBearing(-1);

**Comment by mourner** [comment] 2016-04-20 14:45
@peterbodo have you also tried the `earcut-final` branch by chance?

**Comment by peterbodo** [comment] 2016-04-20 14:51
@mourner :) I have no idea what is that....

**Comment by ckc11** [comment] 2016-04-20 16:58
@peterbodo i was hopeful that your workaround would work for me but sadly setting the pitch/bearing didn't have any affect for any of my machines.

**Comment by ckc11** [comment] 2016-04-20 18:31
@mourner The earcut-final branch did not work for me either (on the dev channel version of chrome 51.0.2687.0 dev-m (64-bit), but it DOES work on the Canary channel).  This is what the earcut-final branch looks like for me on the dev channel of chrome:

![image](https://cloud.githubusercontent.com/assets/7947207/14685887/513783f6-06eb-11e6-9397-4098ce55c91b.png)

I will test it on the stable channel of chrome later today.

**Comment by ckc11** [comment] 2016-04-20 18:36
@peterbodo you can try these files (I just did a build of the earcut-final branch).

[mapbox-gl-earcut-final.zip](https://github.com/mapbox/mapbox-gl-js/files/228584/mapbox-gl-earcut-final.zip)

**Comment by peterbodo** [comment] 2016-04-20 20:11
@ckc11 Can you see the example rendering on this page?
[https://www.mapbox.com/mapbox-gl-js/example/set-perspective/](https://www.mapbox.com/mapbox-gl-js/example/set-perspective/)

**Comment by ckc11** [comment] 2016-04-20 20:40
@peterbodo only with the canary build of chrome, I cannot see it with any other version of chrome.

**Comment by akshaykapadia** [comment] 2016-04-20 23:32
@peterbodo   awesome.... thanks a lot... setting up pitch and bearing worked for me...now all maps are running....
and even @ckc11 , that example is also working! That's really interesting and weird!!!
thanks

**Comment by af7** [comment] 2016-05-05 15:14
Same problems in my (latest) Chrome too. 

See what I see on the "Set pitch and bearing" example:

![image](https://cloud.githubusercontent.com/assets/7850073/15047128/02706d84-12ec-11e6-859c-827074b89b91.png)

This does *not* happen on 3 other PCs in our company (with latest Chrome too). But it is happening to my PC (with latest GPU drivers installed) and this should not be taken lightly, as i am an end user too. I am in charge of evaluating a possible migration of our map solution of 400K unique visitors per day from Google Maps to MapBox GL and it is kind of discouraging to realize that vector maps may not be prime for many PCs.

I love your GL implementation and would like to be positive on the migration but I cannot do that unless this problem is solved. Please take the extra effort to make any necessary changes on how you render your vectors (I hope this to be possible). Nobody would like to tell their management that "some of the 400K unique visitors per day will not be able to see our maps and we cannot do anything about it". It is a *no go* if this problem is not solved, do not take this lightly please.

Thank you for your understanding and consideration.

**Comment by af7** [comment] 2016-05-05 15:59
If this is of any help, I have 2 graphic cards in use (simultaneously through a BIOS option to also use the motherboard's GPU for a 3rd monitor):

![image](https://cloud.githubusercontent.com/assets/7850073/15048598/e63c7a0c-12f2-11e6-8127-c43b2c9387d7.png)

The Radeon HD 6450 was already updated. The Intel one (on the motherboard) had to be updated as it did not have the latest driver. I did the update, but this did not have any effect on the problem.

Note that on my IE Edge browser your examples work OK.

**Comment by ckc11** [comment] 2016-05-05 16:06
Yes this is definitely a deal breaker if this cannot be solved for us as well.  

As an update, the earcut final build that I had posted before is working 100% with Chrome 51 (dev channel) but strangely Chrome 52 (canary) has webgl disabled entirely.  Version 0.18.0 of mapbox-gl is not working however on Chrome 51.  This is what even the basic 0.18.0 map looks like in Chrome 51.

![image](https://cloud.githubusercontent.com/assets/7947207/15048718/7e44a922-129f-11e6-8bb0-d8fd55f465c9.png)

I am also on 2 graphics cards, Radeon 5450 and the onboard Intel.  I've tried at least 6 versions of the Radeon driver (from old to latest), and it's the same issue with all.

**Comment by lucaswoj** [comment] 2016-05-17 16:26
Earcut has merged now! 🎉 Let's ticket out any remaining rendering issues seprately.

**Closed by lucaswoj** 2016-05-17 16:26 UTC
Labels: bug, machine-dependent bug

**Comment by pwilczynski** [comment] 2016-05-17 17:47
For anyone who's trying to find the Earcut PR, it's here (https://github.com/mapbox/mapbox-gl-js/pull/1606).

**Comment by swanstation** [comment] 2016-09-28 17:32
I had the same issue even to the point where certain maps wouldn't render in the same browser. Some maps rendered grey, some checkered, some not at all, and some worked perfectly. I knew it couldn't be the VPU.

POSSIBLE FIX: I then noticed that the maps that weren't rendering had no map position; all of the values were 0 (bug). Try this: when viewing a map in style-edit mode, click "map position" in the upper right and enter values in the zoom, bearing, pitch, longitude, and latitude fields. Once you've entered values in these fields, the map should appear and you can zoom and pan normally. For some reason, you cannot zoom and pan out of the 0 values without manually entering them in with your keyboard first.

**Comment by zirexba** [comment] 2017-11-15 09:37
I had a problem on Ubuntu 16.04, Chrome Version 62.0.3202.89 (Official Build) (64-bit)
This steps helped me [](https://support.google.com/chrome/forum/AAAAP1KN0B0QFlEg2hyqdk?hl=en)

Ensure you’ve signed into your Chrome profile.
Try clearing your cache and cookies. Start by clearing from the time period you started facing the issue, then expand to “beginning of time”.
Use the incognito mode. If it works well, I'd suggest you disable the extensions temporarily (you could use chrome://extensions/ on the Chrome address bar) and re-enable them one at a time to determine which extension is misbehaving.
_
