### ISSUE TITLE
Support contains, begins with, and ends with filter option for strings

### ISSUE THREAD

**Issue by afischer** [mapbox/mapbox-gl-js#4820] opened 2017-06-10 21:18 UTC
## Motivation
Often, layers will be filtered on a specific attribute. This attribute could be a string, for example, a restaurant name. The current filter API allows for extensive filtering of numerical values, but the ability to filter strings is limited to searching string equality and inequality.

## Design
Maintaining the current `filter` API design, a few new selectors could be added. I would recommend following the [CSS selector design](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors), as it is widely known by web designers.

### Mock-Up

To begin, the API could support the `^=`, `$=`, and `*=` operators. This would give the ability to do the following:

```javascript

// Filter showing only features with the property `cuisine` beginning with 'Asian'
map.setFilter('restaurants', ['^=', 'cuisine', 'Asian']);
// matches 'Asian', 'Asian-Fusion'

// Filter showing only features with the property `cuisine` ending with 'ian'
map.setFilter('restaurants', ['$=', 'cuisine', 'ian']);
// matches 'Italian, 'Asian', 'American'

// Filter showing only features with the property `cuisine` containing the substring 'pan'
map.setFilter('restaurants', ['*=', 'cuisine', 'pan']);
// matches 'Japanese', 'Spanish'
```

### Concepts
The design is familiar to web designers already, and is in alignment with the current  filter API design. Adding these features would not be breaking, and would be highly discoverable. The same terminology could be used to discuss these filters, and they would easily fit in with the filters already in place.

### Implementation

Implementation would follow the precedent set for filters in the JS/C++ mapbox repos. 

Further discussion would be needed regarding how/if these operators would support other types, such as numerics. Would numbers be treated as strings?

**Comment by anandthakker** [comment] 2017-08-07 16:24
Thanks for this proposal @afischer -- this type of functionality will be covered by the work that's currently underway (#4777) to add a general expression syntax.

Duplicate of #4077

**Closed by anandthakker** 2017-08-07 16:24 UTC

**Comment by gabrielmoncea** [comment] 2018-07-13 08:38
@anandthakker I read the Project Arbex but could not see this particular example. Can you please reference the syntax where this example is applied?

**Comment by gabrielmoncea** [comment] 2018-07-13 08:57
@afischer did you manage to sort it out?

**Comment by anandthakker** [comment] 2018-07-13 13:09
See #6484, which tracks expression operators that aren't yet implemented.

**Comment by gabrielmoncea** [comment] 2018-07-13 14:14
@anandthakker I don't understand. Is this feature implemented or not yet? I thought it is as Project Arbex is merged into master and you referenced it for this issue.

**Comment by anandthakker** [comment] 2018-07-13 14:21
It is not implemented yet. #6484 tracks expression features that are not yet implemented, but will be in the future
