### ISSUE TITLE
Complex geometry with holes is displayed wrong (with extra polygons) on some zoom layers

### ISSUE THREAD

**Issue by mathildor** [mapbox/mapbox-gl-js#10603] opened 2021-04-21 15:01 UTC
#### Related issue:
This issue seems to similar to a previous reported and solved [issue](https://github.com/mapbox/mapbox-gl-js/issues/9180).

**mapbox-gl-js version**:
[v2.2.0](https://api.mapbox.com/mapbox-gl-js/v2.2.0/mapbox-gl.js)

**browser**:
edge, chrome (probably browser independent)

### Steps to Trigger Behavior

 When adding some complex geometries (see fiddle) to the map, the layer is displayed with an extra polygon on some zoom layers.

Correct display:
![image](https://user-images.githubusercontent.com/6861456/115575186-9ad5f380-a2c2-11eb-8c61-faf74b47e6d7.png)

Zooming in a bit ruins the layer rendering because an extra polygon is displayed.
![image](https://user-images.githubusercontent.com/6861456/115575229-a4f7f200-a2c2-11eb-9c04-ec52aa98cacf.png)

### Link to Demonstration

[jsfiddle](https://jsfiddle.net/simhas/pm0w1azy/6/)

### Expected Behavior

Added layer is displayed similarly on all zoom levels

### Actual Behavior

Layer changes dependent on zoom level

**Comment by mourner** [comment] 2021-04-21 16:23
Yeah, this might be either #7023 or another triangulation issue (similar to #9180) — will need investigation to determine which. The second would be easier to address.

**Comment by mathildor** [comment] 2021-06-30 11:48
Any progress on this issue?

Here is another example of a polygon that renders differently on different zoom levels.
https://jsfiddle.net/simhas/9fudk4ce/1/

**Comment by WendyCarpenter** [comment] 2021-07-28 20:35
I think my problem falls within the parameters of this topic.  The geojson renders correctly in Mapbox js, but not Mapbox GL, as you can see.  Can someone suggest a way to correct this issue?

I'm using https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js

![MapboxJs](https://user-images.githubusercontent.com/11559333/127392044-fa0d3292-9cd8-458f-8873-98096b6fd0fd.PNG)
![MapboxGL](https://user-images.githubusercontent.com/11559333/127392111-352296ae-432e-41d3-9110-ffc5f917382d.PNG)

**Comment by WebHero0544** [comment] 2023-10-13 10:29
@mourner Hello, I do not know if this problem has been solved, I also encountered the same problem in the development project, I really hope it can be solved as soon as possible

**Comment by mourner** [comment] 2024-06-28 17:30
Closing as a duplicate of #7023.

**Closed by mourner** 2024-06-28 17:30 UTC
Labels: bug :lady_beetle:
