### ISSUE TITLE
Areas covered by "n % 8 == 0" polygons are not drawn

### ISSUE THREAD

**Issue by nsamala** [mapbox/mapbox-gl-js#2269] opened 2016-03-15 18:07 UTC
On 0.15.0, we have some weird artifacts when multiple geometries on the same layer are rendered and happen to overlap each other. 

<img width="1357" alt="screen shot 2016-03-14 at 11 04 42 pm" src="https://cloud.githubusercontent.com/assets/1831746/13788615/bb8cce9c-ea9d-11e5-8b09-2e10b6189247.png">

<img width="1467" alt="screen shot 2016-03-14 at 11 06 08 pm" src="https://cloud.githubusercontent.com/assets/1831746/13788628/c010f7cc-ea9d-11e5-85fa-68bd0a2c94b3.png">

You can also view it live at https://app.airmap.io and searching for **Anchorage** with **Recreational - 5 mile radius** airports turned on.

Any ideas?

**Comment by lucaswoj** [comment] 2016-03-16 18:40
Thanks for the report @nsamala. I can confirm the bug and will investigate as soon as I can.

**Comment by ansis** [comment] 2016-03-17 03:25
Any spot covered by 0, 8, 16, 24, etc polygons doesn't correctly. This will be fixed by the switch to earcut https://github.com/mapbox/mapbox-gl-js/pull/1606 . I don't think we can do anything before that to fix this.

---

We currently draw polygons by creating a stencil using the stencil buffer and then. We only use [3 of the bits](https://github.com/mapbox/mapbox-gl-js/blob/1466b3bdc827b2bda4e267c27353ba93ff6185fa/js/render/draw_fill.js#L75) of the stencil mask for polygon rendering because we use the rest for tile clipping masks. This means that if the number of polygons overlapping a pixels is a multiple of 8 then it will treat it as zero.

Removing the [wrap from here](
https://github.com/mapbox/mapbox-gl-js/blob/1466b3bdc827b2bda4e267c27353ba93ff6185fa/js/render/draw_fill.js#L87-L88) doesn't fix the problem because the clamping is applied before the mask.

**Comment by ansis** [comment] 2016-03-17 03:30
It looks like the second image may be of a different bug that we can fix pretty easily: https://github.com/mapbox/mapbox-gl-js/issues/2089

**Comment by nsamala** [comment] 2016-03-17 15:21
Thanks for the quick response! It does look like that `earcut` branch will solve both of these problems. For that second picture, would it work to ensure our polygons follow the proper winding order for their linear rings as a short term fix?

**Comment by ansis** [comment] 2016-03-17 23:47
@nsamala yes, ensuring all your polygons follow the same winding order should fix it. This should be fixed in the next release: https://github.com/mapbox/mapbox-gl-js/pull/2285

**Closed** 2016-05-17 16:17 UTC
Labels: bug, in progress
