### ISSUE TITLE
Renderer can't keep up with fast zooming, when using minzoom

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1161] opened 2015-04-16 15:26 UTC
While optimizing GL styles, @mourner suggested setting higher minzooms for layers that aren't yet visible. However, there's a significant lag when crossing this minzoom threshold too swiftly:

![fastzoom](https://cloud.githubusercontent.com/assets/4551508/7184436/326e7ada-e42b-11e4-8076-8dd4053952ee.gif)

In this example, the dark road casing appears whenever the tile data is available, but the white road is delayed til a higher zoom. 

cc/ @jfirebaugh

**Comment by peterqliu** [comment] 2015-04-16 15:28
Test case: https://www.mapbox.com/bites/00116/?style=peterqliu.bf9a8d40&access_token=pk.eyJ1IjoicGV0ZXJxbGl1IiwiYSI6ImpvZmV0UEEifQ._D4bRmVcGfJvo1wjuOpA1g#11.46/35.6880/-220.2072

most significant in Tokyo with its sheer volume of roads

**Comment by mourner** [comment] 2015-04-16 16:39
This is not a bug, just a consequence of the fact that refs are not used, so the main road layer over casings layer (that was present before) takes time to be processed and appear. Maybe a different layer organization would fix this somehow but using refs is a much better approach.

**Comment by ansis** [comment] 2015-04-28 21:58
Closing. @peterqliu open a new issue in gl-styles if you have questions about how minzoom should be used.

**Closed by ansis** 2015-04-28 21:58 UTC
Labels: bug
