### ISSUE TITLE
Polygon marker blocked by calculation box

### ISSUE THREAD

**Issue by elchingurban** [mapbox/mapbox-gl-js#11059] opened 2021-09-24 11:22 UTC
**mapbox-gl-js version: 2.4.1 (CDN)**

Hi everyone, 

I am having a problem with the example given in example here for drawing a polygon with mapbox-gl-js:

### Link to demostration:
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/

The calculation area div is blocking the marker when drawing a polygon and restricts drawing it everywhere on the map

![draw-polygon](https://user-images.githubusercontent.com/31244917/134665652-0bf2cacd-0f3a-43b4-a61a-c8dc3d557d24.gif)

**Comment by avpeery** [comment] 2021-09-24 17:16
Hi @elchingurban this is an example doc to test out the draw feature. You can remove the calculation box in this example in jsfiddle to test without it, or test with adding pointer-event: none; to the calculation-box css. Since this is not a bug report or feature request, I will close this issue. Thanks!

**Closed by avpeery** 2021-09-24 17:16 UTC
