### ISSUE TITLE
`fill-pattern` ignores image's `pixelRatio`

### ISSUE THREAD

**Issue by flawyte** [mapbox/mapbox-gl-js#8020] opened 2019-03-11 19:32 UTC
**mapbox-gl-js version**: 0.53.1
**browser**: Chrome 72.0.3626.121

### Steps to Trigger Behavior

 1. Load an image using `loadImage()`
 2. Declare it using `addImage()`, passing `{ pixelRatio: 4 }` as the [3rd parameter](https://docs.mapbox.com/mapbox-gl-js/api/#map#addimage)
 3. Use this image in a `fill-pattern` property

### Link to Demonstration

https://jsbin.com/vevosisuyo/edit?html,js,output

### Expected Behavior

Pattern should be "scaled down" `pixelRatio` times.

### Actual Behavior

`pixelRatio` is ignored and the pattern is never scaled when repeated.

> I don't know if it's expected behavior or not, but the documentation says nothing about this specific case intentionally not being supported so I thought it might be a bug.

**Comment by ansis** [comment] 2019-03-12 14:35
Yep, this looks like a bug! Thanks for reporting and supplying the example

**Comment by julians** [comment] 2019-11-14 13:55
Is there any news on this?

**Comment by karimnaaji** [comment] 2020-02-07 15:03
I think this might also affect `line-pattern`, I discovered this issue while working on https://github.com/mapbox/mapbox-gl-js/pull/9266 and trying to use a pattern added with `addImage` with different pixel ratios.

**Comment by karimnaaji** [comment] 2020-02-28 16:38
Hey @julians @flawyte! Some updates on this; I found the root cause and will polish and send it out for review.
In the meantime, if you want to try it out and ensure that it fixes your use cases you can see it in this branch https://github.com/mapbox/mapbox-gl-js/tree/fix-8020

**Comment by karimnaaji** [comment] 2020-03-11 18:24
Closing as fixed by #9372 , available in next release.

**Closed by karimnaaji** 2020-03-11 18:24 UTC
Labels: bug :beetle:
