### ISSUE TITLE
Map pitch not accounted for in text orientation

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#4376] opened 2017-03-07 09:42 UTC
From @ajashton https://github.com/mapbox/mapbox-gl-js/issues/3057#issuecomment-278766953:

> Noting that one specific aspect of this is that perspective is not accounted for in text orientation. If you look at [this JSFiddle](https://jsfiddle.net/ajashton/25peL7y2/1/) First, 2nd, & 3rd Streets should be rotated 180° to be closer to "upright", but if you change the pitch to 0 the same orientation is correct.

**Comment by nickidlugash** [comment] 2017-03-27 19:09
@ChrisLoer We haven't yet discussed this issue, but this may (or may not) be something worth thinking about in conjunction with other pitched label rendering refactors. 

Right now if text is kept upright, we [calculate which orientation of glyphs we should *not* add to symbol arrays](https://github.com/mapbox/mapbox-gl-js/blob/master/src/data/bucket/symbol_bucket.js#L576-L578) based on the angle of the glyph, but this doesn't account for how the final angle may change based on pitch.

I'm not sure how vertical text is affected – this issue is not as evident in vertical-enabled line labels, but that may just be because there are four possible orientations so the flip between orientations is more subtle and an "incorrect" orientation is not as suboptimal.

**Comment by ChrisLoer** [comment] 2017-03-27 19:24
Hmm, interesting -- yeah, this is something we could tackle at the same time.

This is another case where doing the fully correct solution at high speed requires sending a lot more information down to the GPU. Consider these two views of 15 St NW:

_Panned to lower left_
![screenshot 2017-03-27 12 15 43](https://cloud.githubusercontent.com/assets/375121/24373734/24b4e36a-12e7-11e7-90de-f5ee553f9267.png)

_Panned to lower right_
![screenshot 2017-03-27 12 15 31](https://cloud.githubusercontent.com/assets/375121/24373735/24bbc360-12e7-11e7-829f-f94b2b00a70f.png)

Both views came from a map at the same pitch/angle/zoom: the only difference was panning left and right.

We could calculate the right glyph to show in the SDF vertex shader, but we'd have to send down two copies of each glyph (one "upside down" copy). Alternatively, we can try to do this calculation at placement time and re-trigger placement whenever there's a pan operation. It would take a little longer for labels to flip to the right orientation, and it would add CPU intensity.

**Comment by lucaswoj** [comment] 2017-03-28 18:01
As best I understand this is already supported via the [`text-pitch-alignment`](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-pitch-alignment) property. 

Helpful illustration by @yhahn:

![](https://cloud.githubusercontent.com/assets/83384/15935723/4a942190-2e36-11e6-94ab-eba36b62e1b7.png)

**Comment by lucaswoj** [comment] 2017-03-28 18:04
Please re-open if I'm misunderstanding 🙇

**Comment by ChrisLoer** [comment] 2017-03-28 18:12
From discussion with @lucaswoj , there are two issues here that aren't accounted for by `text-pitch-alignment`:

* We calculate glyph angle without taking account of perspective, so we can get the calculation wrong.
* Even if we were getting the perspective calculation correct, we would only be doing it at placement time, but the perspective can change without re-triggering placement, so we'd need to handle that case.

**Comment by ChrisLoer** [comment] 2017-04-25 20:39
There's a closely related problem: collision tiles also don't account for the parallax effect, with the result that you can start to get collisions near the right and left sides of the screen. Check out "Riviera Country Club" in this screenshot: 

<img width="592" alt="screenshot 2017-04-25 13 34 22" src="https://cloud.githubusercontent.com/assets/375121/25406591/0dbce432-29bc-11e7-9a2c-d2e9444a215c.png">

The collision logic is separate from the text orientation logic, but the shape of the problem is the same: we need to (1) account for perspective at placement time, and (2) periodically re-do placement to account for perspective changes.

**Comment by ChrisLoer** [comment] 2017-06-03 00:38
https://github.com/mapbox/mapbox-gl-js/pull/4781 should address this!

**Comment by ChrisLoer** [comment] 2017-06-19 16:05
Fixed with #4781 (although not the collision issue mentioned in https://github.com/mapbox/mapbox-gl-js/issues/4376#issuecomment-297157900)

**Closed by ChrisLoer** 2017-06-19 16:05 UTC
