### ISSUE TITLE
Placelabel overlapped by lower layers

### ISSUE THREAD

**Issue by manuelroth** [mapbox/mapbox-gl-js#1729] opened 2015-11-16 15:12 UTC
![bildschirmfoto 2015-11-16 um 16 09 34](https://cloud.githubusercontent.com/assets/1810384/11185336/98834ba8-8c7c-11e5-8316-acd3eaa900ee.png)

What could be the cause of this? - It is wired that only the upper part of the label is overlapped by the road.

**Comment by jfirebaugh** [comment] 2015-11-16 17:35
This is a duplicate of #757. A fix is in progress.

**Closed by jfirebaugh** 2015-11-16 17:35 UTC

**Comment by manuelroth** [comment] 2015-11-16 17:41
@jfirebaugh Thanks for the fast response, keep up the good work.
