### ISSUE TITLE
Add image overlay

### ISSUE THREAD

**Issue by duncangraham** [mapbox/mapbox-gl-js#919] opened 2015-01-07 23:33 UTC
[Someone came through Helpscout](https://secure.helpscout.net/conversation/64086166/13580/) looking to add an image overlay to a map at a 45° angle.

I know we can do this with video, would it be difficult to add an image source counterpart?

![screen shot 2015-01-07 at 3 28 51 pm](https://cloud.githubusercontent.com/assets/865298/5655352/f1c3385a-9681-11e4-8359-b36f50dd3f9d.png)

**Comment by jfirebaugh** [comment] 2015-01-07 23:34
Duplicate of #700.

**Closed by jfirebaugh** 2015-01-07 23:34 UTC
