### ISSUE TITLE
How can I set up a filter to hide specific OSM buildings in Mapbox GL JS version 3.0.0 and standard style

### ISSUE THREAD

**Issue by cuongnc5** [mapbox/mapbox-gl-js#13010] opened 2023-12-14 02:06 UTC
**mapbox-gl-js version 3.0.0**:
### Question
How can I set up a filter to hide specific OSM buildings in Mapbox GL JS version 3.0.0 with the standard style? Previously, using version 2.9 and the Style Street, we successfully hid certain buildings using map.setFilter() and replacing them with our custom GLB buildings. However, after upgrading to version 3.0.0 and switching to the standard style, map.setFilter() seems to no longer work. Could you please guide me on how to hide the default Mapbox buildings and replace them with our custom buildings?
![image](https://github.com/mapbox/mapbox-gl-js/assets/9640740/7cb48ff4-5dc7-4e0f-afc0-f903c44cc127)

**Comment by WataruTsuchida** [comment] 2023-12-14 04:14
Currently, we cannot modify them.
https://docs.mapbox.com/api/maps/styles/#mapbox-standard

"The underlying paradigm to the Standard style is different from other Mapbox styles. Layers in Standard are not modifiable asides from the predefined configuration options. Mapbox manages the basemap experience and only surfaces key global styling configurations - in return, you get a carefully designed, cohesive visual experience and an evergreen map, always featuring the latest data, styling and rendering features compatible with your SDK."

**Comment by MeltonEngServ** [comment] 2023-12-17 22:53
I think you can modify the standard style by modifying the style object. In this way you can modify the filter, layout and paint properties of any layer. However, I am not sure if this is the "right" way of doing it. e.g.

map.getStyle().imports[0].data.layers[BUILDINGS_LAYER_IDX].filter = YOUR_FILTER_EXPRESSION

**Comment by WataruTsuchida** [comment] 2023-12-19 00:02
@MeltonEngServ  We can get styles but there is no way to apply it to imported layers. Official docs and discussion here say impossible.

**Comment by cuongnc5** [comment] 2023-12-19 02:20
> @MeltonEngServ We can get styles but there is no way to apply it to imported layers. Official docs and discussion here say impossible.

If customization is not possible, it's truly regrettable. The standard style is a good experience; my customers really like it. However, if customization is not possible, we are forced to revert to the old version.

**Comment by llebocq** [comment] 2023-12-21 16:08
I agree with @cuongnc5. It would be great to keep some customization with the standard style. In my case, I implemented a layer system to activate/deactivate buildings on previous styles. I would like to keep this functionality with the new style.

**Comment by WataruTsuchida** [comment] 2023-12-24 23:16
@cuongnc5 In your case, you just add 3D buildings and lights, then you can get 3D experience. If you need rich map data or specific 3D models from mapbox, this does not satisfy the needs.

**Comment by cuongnc5** [comment] 2023-12-28 01:36
I just want to overlay some buildings requested by the customer onto the Mapbox tileset. Before I upload my buildings, I need to hide the Mapbox buildings. I have done this with the classic versions. I want to do the same with the standard version because it provides a better real-time experience than the classic versions

**Comment by WataruTsuchida** [comment] 2023-12-28 06:05
"time-based effects" mean ambient lights?
Standard use setLights, new api in V3, to change the lights.
I am using it with street style to cast shadow and adjust the ambient light color.

**Comment by rivindubandara** [comment] 2024-01-08 01:26
@cuongnc5 Hi there, I had a similar issue where I wanted to hide the 3D building layer. Apparently in V3, they don't have this optionality, the buildings seem to be embedded and not modifiable. This is a big disadvantage in my opinion compared to V2 because it makes it impossible to overlay layers and not have the 3D buildings obstruct the view.

**Comment by stepankuzmin** [comment] 2024-01-16 15:15
Hi all,

Unfortunately, turning off 3D Buildings and trees in the Standard Style is not currently supported. Closing this issue as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/13009 so we can track it in one place.

**Closed by stepankuzmin** 2024-01-16 15:15 UTC
Labels: feature :green_apple:
