### ISSUE TITLE
Custom dynamic markers

### ISSUE THREAD

**Issue by normanrz** [mapbox/mapbox-gl-js#2260] opened 2016-03-13 13:55 UTC
For my project I need to create custom markers dynamically. Currently, I am using the 2D Canvas API to draw icons on a custom layer in Google Maps. For performance reasons I'm interested in switching to Mapbox GL.
I understand that WebGL works with textures that have to be loaded into the graphics context. Afaik Mapbox GL currently only allows spritesheets that have been built through Mapbox studio. 
Would it be possible to add support for dynamically created spritesheets (ie. the spritesheets are drawn at runtime using the Canvas API)?

Related issues: #358, #1760, #656.
Demo of my project: http://racemap.de/player/haj-hannover-marathon-42km_2015-04-19/

**Comment by lucaswoj** [comment] 2016-03-14 18:44
For all intents and purposes, this is a duplicate of #358.

Having taken a quick glance at your application, I recommend using the same approach we use for [highway labels in Mapbox streets](https://github.com/mapbox/mapbox-gl-styles/blob/master/styles/streets-v8.json#L7878):

 - pre-generate a number of label backgrounds at different widths
 - add a `{width}` property to your data
 - select the background at runtime using tokens in the `icon-image` property

**Closed by lucaswoj** 2016-03-14 18:44 UTC

**Comment by normanrz** [comment] 2016-03-15 12:40
Thanks! Really appreciate you taking the time to look into my problem.
