### ISSUE TITLE
Some layers no longer rendering in Safari.

### ISSUE THREAD

**Issue by ajfickas** [mapbox/mapbox-gl-js#5733] opened 2017-11-21 20:07 UTC
**mapbox-gl-js version**: 0.42.1

### Steps to Trigger Behavior

 1. Visit https://www.mapbox.com/mapbox-gl-js/example/simple-map/ in Safari.

### Expected Behavior
All layers should be rendered.

### Actual Behavior
Only symbol layers appear to be rendering.

Reproduction is consistent. I am using Safari Version 11.0.1 (13604.3.5) on a 13-inch 2016 Macbook Pro with OS High Sierra, Intel Iris Graphics 550 1536 MB.

I ran into the behavior after upgrading a project from Mapbox GL JS 0.40.1 to 0.42.1.

<img width="1259" alt="screen shot 2017-11-21 at 2 51 12 pm" src="https://user-images.githubusercontent.com/1221515/33094259-8d7621aa-cecd-11e7-948e-90a02bf56c1e.png">

**Comment by jfirebaugh** [comment] 2017-11-21 20:18
Duplicate of #5712.

**Closed by jfirebaugh** 2017-11-21 20:18 UTC
