### ISSUE TITLE
Wrong resize on iOS rotate

### ISSUE THREAD

**Issue by ImanMh** [mapbox/mapbox-gl-js#9796] opened 2020-06-16 16:35 UTC
**mapbox-gl-js version**: 1.11.0

**browser**: Safari iOS

### Steps to Trigger Behavior

 1. Open the link in Safari iOS, and add to home screen
 2. Open home screen link and rotate the phone to landscape
 3. Rotate the phone back to portrait and the Mapbox container is messed up. 

### Link to Demonstration

https://jsbin.com/zajeyutuwo/1/edit?html,output

This is very important to add to home screen or the bug wont reproduce so create a manifest.json file side by side with the index.html and fill it's content like this:

```
{
  "short_name": "mapbox",
  "name": "mapbox",
  "display": "standalone"
}
```

### Expected Behavior
When you rotate back you shall see a full screen map

### Actual Behavior
You see a half loaded map container

### Screen shots
Good
<img src="https://user-images.githubusercontent.com/4482199/84802135-6431ab80-b015-11ea-95d5-a55738cdd6c0.PNG" width="200">

Bad
<img src="https://user-images.githubusercontent.com/4482199/84802158-70b60400-b015-11ea-8f86-b04c0631de57.PNG" width="200">

Bad
<img src="https://user-images.githubusercontent.com/4482199/84802204-7e6b8980-b015-11ea-8daa-e9bb78adcb04.PNG" width="200">

**Comment by ImanMh** [comment] 2020-06-16 17:34
If somebody from mapbox can tell me where to look for the issue I can work on a PR to fix this.

**Comment by ryanhamley** [comment] 2020-06-16 20:48
This appears to be a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/9010 so I'm going to close to concentrate discussion there.

**Closed by ryanhamley** 2020-06-16 20:48 UTC

**Comment by ImanMh** [comment] 2020-06-17 06:48
This will fix this issue, I tested it by building a local version of mapbox
https://github.com/mapbox/mapbox-gl-js/commit/d6dddef47351dabf4489fa21bb7d0fe0d1d68115
