### ISSUE TITLE
Given a particular HTML/CSS setup, MapBox doesn't respond to touch events on the iPhone in portrait mode for either Safari or Chrome

### ISSUE THREAD

**Issue by icylace** [mapbox/mapbox-gl-js#4898] opened 2017-06-27 07:58 UTC
**mapbox-gl-js 0.38.0**:

### Steps to Trigger Behavior

1.  Using either Safari or Chrome on the iPhone, go to [the test page](https://mapbox-touch-test.netlify.com/)
2.  Make sure the iPhone's orientation is portrait mode.
3.  Try to move or scale the map.

For contrast, try instead using the iPhone in landscape mode or an iPad or a MacBook to see the normal behavior.

Specific versions that I've tested:
- Safari for iOS 10.3.2 on iPhone 6
- Chrome for iOS 10.3.2 on iPhone 6

Also, check out [the repo for the test page](https://github.com/icylace/mapbox-touch-test).

### Expected Behavior

The map should pan and zoom according to your finger gestures as you would expect.

### Actual Behavior

The map is unaffected by your finger gestures.

**Comment by mollymerp** [comment] 2017-06-27 22:42
@icylace Thanks for the report and test case! I was able to reproduce this on my iPhone.

**Comment by jfirebaugh** [comment] 2018-01-12 00:44
Reduced test case:

```html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="initial-scale=1">
    <style>
        main {
            display: flex;
        }
        .foo {
            flex-basis: 0;
        }
        .map {
            flex-grow: 2;
            overflow: hidden;
            position: relative;
        }
        .canvas {
            background-color: blue;
        }
    </style>
</head>
<body>
<main>
    <div class="foo">
        <h1>Test</h1>
    </div>
    <div class="map">
        <div class="container">
            <div class="canvas" style="position: absolute; width: 100px; height: 800px;"></div>
        </div>
    </div>
</main>
<script>
    document.querySelector('.container').addEventListener('touchstart', () => console.log('touch'));
</script>
</body>
</html>
```

This should log `touchstart` events, but doesn't. Looks like a WebKit bug.

**Comment by jfirebaugh** [comment] 2018-01-12 01:02
https://bugs.webkit.org/show_bug.cgi?id=181566

**Comment by jfirebaugh** [comment] 2018-02-28 01:49
Confirmed to be a browser bug. Presumably the fix will roll out at some point this year. 🎉  Closing here.

**Closed by jfirebaugh** 2018-02-28 01:49 UTC
Labels: bug, environment-specific
