### ISSUE TITLE
When the parent element is scaled, the canvas width and height calculation is not full screen

### ISSUE THREAD

**Issue by yueyanshaosun** [mapbox/mapbox-gl-js#11265] opened 2021-11-10 03:25 UTC
**mapbox-gl-js version**: 2.6.0

**browser**: chrome 95.0.4638.69

### Steps to Trigger Behavior

 1. set the map dom scale

### Link to Demonstration

https://codesandbox.io/s/cocky-dirac-7fsbi?file=/index.html

### Expected Behavior

width and height of map canvas   ===  map dom's

**Comment by avpeery** [comment] 2021-11-10 15:34
Hi @yueyanshaosun, there is another issue opened #11085 similar to your issue. We have a known bug with using the css transform property. If you remove css transform property from your code, the canvas will be full screen. We are working on a solution to solve this bug.

**Comment by avpeery** [comment] 2021-11-10 15:36
I am going to close this issue since it is a duplicate of #11085, thanks @yueyanshaosun for reporting this bug!

**Closed by avpeery** 2021-11-10 15:36 UTC
