### ISSUE TITLE
Flaky query tests: master ticket

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/mapbox-gl-js#11736] opened 2022-04-12 11:34 UTC
This ticket consolidates reports of flaky query tests in one place.

- [ ] https://github.com/mapbox/mapbox-gl-js/issues/11726
- [ ] https://github.com/mapbox/mapbox-gl-js/issues/11727
- [ ] https://github.com/mapbox/mapbox-gl-js/issues/11728
- [x] https://github.com/mapbox/mapbox-gl-js/issues/11735

**Comment by SnailBones** [comment] 2022-07-12 22:17
Closing as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/11732, I added these tests there

**Closed by SnailBones** 2022-07-12 22:17 UTC
Labels: testing :100:
