### ISSUE TITLE
Why is the direction reversed?

### ISSUE THREAD

**Issue by kt7456** [mapbox/mapbox-gl-js#12225] opened 2022-09-08 09:07 UTC
thanks ,this is demo address
https://plnkr.co/edit/zdKhXxpkDkgIThfm?preview
![1662605696995](https://user-images.githubusercontent.com/35618730/189047656-ab812806-a484-430b-a3f8-75bafdf2d696.jpg)
<img width="371" alt="1662605680100" src="https://user-images.githubusercontent.com/35618730/189047955-f6ed3487-0766-45cb-9d7d-54c51b29f2c4.png">

first picture is incorrect direction
second picture is correct direction

this is previous address https://github.com/mapbox/mapbox-gl-js/issues/12221

**Comment by mourner** [comment] 2022-09-08 11:20
@kt7456 the demo by that URL doesn't appear to be working — I don't see the custom layer and there are a bunch of errors in the console. Perhaps you forgot to save some code updates?

**Comment by kt7456** [comment] 2022-09-09 00:16
> @kt7456该 URL 的演示似乎无法正常工作 - 我没有看到自定义层，并且控制台中有一堆错误。也许您忘记保存一些代码更新？

It takes 1 minute to display when loading data

**Comment by kt7456** [comment] 2022-09-09 00:29
My guess is that mapboxgl is applying some y-flip the image, which you need to apply to the volume as well either when you render it or when you display the volume rendering above the map (if you're rendering to a texture and compositing that on top of the map)

This is the author's reply

**Comment by stepankuzmin** [comment] 2022-09-12 11:29
Hey @kt7456,

I wasn't able to reproduce this either. Could you please check that the example you provided is working?

**Comment by kt7456** [comment] 2022-09-13 01:54
> 嘿@kt7456,
> 
> 我也无法重现这一点。您能否检查一下您提供的示例是否有效？
this is other demo address
Requires google browser to open

**Comment by avpeery** [comment] 2022-09-30 17:33
Hi @kt7456, Unfortunately the custom layer does not load on any of the examples provided still. Can you provide information about the browser and operating system you are using? Thanks

**Comment by avpeery** [comment] 2022-11-08 16:34
Since we are unable to reproduce this issue with the example provided, I am going to close this issue. Please feel free to open again with a different example and include relevant information (e.g. browser/operating system). Thanks!

**Closed by avpeery** 2022-11-08 16:34 UTC
Labels: needs information :pray:

**Comment by kt7456** [comment] 2022-11-13 01:31
ok，thanks！
