### ISSUE TITLE
Pinch Zoom resizes page in Chrome on Windows touch devices

### ISSUE THREAD

**Issue by bogdancirlugea** [mapbox/mapbox-gl-js#4349] opened 2017-03-01 11:23 UTC
### Steps to Trigger Behavior

Use Mapbox-gl-js In Chrome on a Windows touch device. Do pinch-in to zoom into the map.
Tested on Windows 10 on Microsoft Surface Pro 4.

### Expected Behavior

Pinch action should Zoom into the map.

### Actual Behavior

Pinch-In enlarges the page. The Zoom level of the browser does not change. Pinch-out restores the page to the initial size and seems to work correctly within the map.
 
Here is video that shows the behavior I encounter: https://www.dropbox.com/s/igrf8b76ay4nkna/mapbox_pinch.webm?dl=0

Here is the fiddle I used: https://jsfiddle.net/1gkaaxpw/1/

**Comment by indus** [comment] 2017-03-02 06:44
Sounds like #4259

**Comment by jfirebaugh** [comment] 2017-03-23 00:42
Closing as duplicate of #4259.

**Closed by jfirebaugh** 2017-03-23 00:42 UTC
