### ISSUE TITLE
icon-overlap-amount

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#8340] opened 2019-06-12 00:05 UTC
## Motivation

At the moment, icons can either:

- not overlap at all, not even the transparent spaces around the visible part of a symbol

<img width="527" alt="Screen Shot 2019-06-12 at 9 58 47 am" src="https://user-images.githubusercontent.com/678344/59314475-edbee700-8cf8-11e9-8eff-ec86e2dc475b.png">

(black dots are where icons should be drawn, but aren't)

- overlap completely, without restriction, looking very ugly:

<img width="173" alt="Screen Shot 2019-06-12 at 9 59 27 am" src="https://user-images.githubusercontent.com/678344/59314521-03cca780-8cf9-11e9-8193-b68bb2876c1e.png">

What I would like is the ability to set how much overlap is tolerated, in pixels (or percentage), allowing denser packing without being over the top:

<img width="542" alt="Screen Shot 2019-06-12 at 9 59 19 am" src="https://user-images.githubusercontent.com/678344/59314551-1e9f1c00-8cf9-11e9-93c7-32931e93995d.png">

(This image was made just by turning `icon-allow-overlap` on, at a zoom level where that doesn't look too bad). 

Related: #8327 

## Design Alternatives

I can't think of any workarounds currently. The reason I'm using the black dots in this image is to try to communicate to the user that sites do exist in that area, they just don't have pins drawn.

No other designs spring to mind.

In theory I guess the overlap mechanism could use the transparent parts of the image to make some guess about how much overlap is ok, but that seems very complicated and error prone.

### Mock-Up

Suggestion:

```
"icon-allow-overlap": true,
"icon-overlap-amount": 5
```

**Comment by andrewharvey** [comment] 2019-06-12 01:38
Would clustering be an option?

**Comment by samanpwbb** [comment] 2019-06-12 02:31
Same as https://github.com/mapbox/mapbox-gl-js/issues/6370 ?

**Comment by stevage** [comment] 2019-06-12 02:52
>Would clustering be an option?

Personally, I really don't like clustering. I feel like it was a bit of a hacky workaround to solve the performance limitations of Leaflet, and it's a clunky UX that deprives the user of useful information like the actual locations of points, and forces them to zoom in further than they probably want before they can actually interact with an individual pin. The extra abstraction of the "cluster" vs the individual pin seems really unnecessary.

So I'd generally pick dropping over clustering, but I'd rather slight overlapping still.

**Comment by stevage** [comment] 2019-06-12 02:54
>Same as #6370

Yeah, thanks. This is a good statement of it:

> This would be useful to create higher density maps where a little overlap helps in order to communicate that density, but a lot of overlap would look sloppy and unintentional.

**Comment by mourner** [comment] 2019-06-12 10:43
Yep, closing as duplicate of #6370.

**Closed by mourner** 2019-06-12 10:43 UTC
