### ISSUE TITLE
Incorrect rendering of geojson multipolygon.

### ISSUE THREAD

**Issue by korria** [mapbox/mapbox-gl-js#10768] opened 2021-06-14 03:43 UTC
Hello,

Geojson multipolygons still do not render correctly, I've even simplified the polygons using turf.js.  Interestingly enough however, mouse overs are detected correctly in the geojson, its just a rendering issue.  Is there any plans to fix this?  Its been an issue for a long time.

**mapbox-gl-js version**: 2.3.0 

**browser**: Chrome 91

### Steps to Trigger Behavior

 1. I use this geojson from Avalanche.org [https://avalanche.org/wp-admin/admin-ajax.php?action=map_layer]

### Expected Behavior
<a href="https://ibb.co/BtrqZ2b"><img src="https://i.ibb.co/47YPTRz/Capture.png" alt="Capture" border="0"></a>

### Actual Behavior
<a href="https://ibb.co/Tm9D556"><img src="https://i.ibb.co/hD3xvvb/Capture2.png" alt="Capture2" border="0"></a>

**Comment by ryanhamley** [comment] 2021-06-14 22:49
This is likely a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/7023 so I'm going to close to concentrate discussion in one ticket. Thanks for the report.

**Closed by ryanhamley** 2021-06-14 22:49 UTC
