### ISSUE TITLE
Markers positions are not updated correctly on mobile? 

### ISSUE THREAD

**Issue by cglacet** [mapbox/mapbox-gl-js#5419] opened 2017-10-06 15:24 UTC
**mapbox-gl-js version**: 0.40.0 and 0.38.0
**mobile**: iphone 6
**OS**: ios 10.3.3

### Steps to Trigger Behavior

This example shows the problem (v0.40.0):
https://www.mapbox.com/help/custom-markers-gl-js/

I can do the same on version 0.38.0.

### Expected Behavior

Markers stays at the same location (coordinates) while moving the map.

### Actual Behavior

If you slide horizontally, markers slide from right to left while moving (looks like vibrations at something like 5-10 moves/sec). If you you slide vertically it does the same but markers slides from top to bottom. 

It feels like the more markers I have to more I can observe this bug.
I also do not have this bug when I have a geojson/polyline, even a large one. 
It also looks like this one is working correctly: https://www.mapbox.com/mapbox-gl-js/example/add-image/

### Solution I use for now

In order to avoid these lag issue, I use a layer where I put all my markers (circles representing geojson points) and I detect clicks on the map to eventually display popup when markers are clicked.

**Comment by mollymerp** [comment] 2017-10-06 23:48
Hi @cglacet thanks for reporting this issue. I believe this is a duplicate of #4670. If you disagree, please reopen this issue. I'm going to close for now so we can keep the discussion in centralized in #4670.

**Closed by mollymerp** 2017-10-06 23:48 UTC
