### ISSUE TITLE
Artifacts of GeoJSON polygon on zoom in/out

### ISSUE THREAD

**Issue by tyfoan** [mapbox/mapbox-gl-js#9761] opened 2020-06-05 10:42 UTC
Artifacts appear generally between zoom 11-12, and between zoom 9-10

**mapbox-gl-js version**: 1.10

**browser**
- chrome: 83.0.4103.61
- safari: 13.1
- firefox 77.0.1 

### Steps to Trigger Behavior

See Demo for an example

### Link to Demonstration

https://jsfiddle.net/tyfoan/1nys6fuc/76/

### Expected behaviour
![image](https://user-images.githubusercontent.com/12032004/83868565-c6e09880-a733-11ea-85cc-146ba2baed3d.png)

**Comment by mourner** [comment] 2020-06-05 14:15
This is likely a duplicate of #7023.

**Closed by mourner** 2020-06-05 14:15 UTC
