### ISSUE TITLE
Raster tiles flash when zooming

### ISSUE THREAD

**Issue by chrisvoll** [mapbox/mapbox-gl-js#3898] opened 2017-01-05 20:42 UTC
**mapbox-gl-js version**: v0.22.0 and later

### Steps to Trigger Behavior

 1. Load a map with raster tiles, such as [this jsbin](http://jsbin.com/herobuxeso/edit?html,output) copied from the mapbox examples
 2. Zoom in several zoom levels
 3. Slowly zoom back out to observe the flashing

The behavior is visible in [this video](https://www.dropbox.com/s/kj29xuow5arfimu/mapbox-raster-flash-zooming.mov?dl=0)

I've seen this in the latest versions of Chrome, Safari and Firefox on OS X 10.12.2 with a dedicated GPU.

### Expected Behavior

The transition when zooming should be fluid with new tiles fading in over old ones. In v0.21.0, the zooming is much smoother, as seen in [this jsbin](http://jsbin.com/sasejiqehe/edit?html,output)

### Actual Behavior

New tiles are fading in from white, instead of from `0` opacity.

Thanks guys! Let me know if there's any other information I can provide.

**Comment by lucaswoj** [comment] 2017-01-05 23:24
Thanks @andrewharvey. This is indeed a dupe of https://github.com/mapbox/mapbox-gl-js/issues/2467.

**Closed by lucaswoj** 2017-01-05 23:24 UTC
