### ISSUE TITLE
Getting error on interpolation function

### ISSUE THREAD

**Issue by yoursweater** [mapbox/mapbox-gl-js#5737] opened 2017-11-21 22:29 UTC
I'm trying to change the fill-color of my layer based on two properties, and I'm getting an odd error:

Error: layers.fullcitylayer.paint.fill-color: color expected, array found

The Documentation is very clear that interpolation expressions can validly be used in place of a color.

Here's the code I'm attempting to enter in: 

`map.setPaintProperty('fullcitylayer', 'fill-color', ['interpolate',['linear'],['/', ['get', 'B19001_017'], ['/', ['get', 'ALAND'], 1000000]],10,'#00adef',100,'#212529',1000,'#ea950b',5000,'#e94e34'] )`

Is this just a bug?

**Comment by jfirebaugh** [comment] 2017-11-21 22:33
Hi @yoursweater. I'm not able to reproduce that error running that code. Could you provide a self-contained JSFiddle that demonstrates the issue?

**Comment by yoursweater** [comment] 2017-11-21 22:55
This is embarrassing, but for some reason I'm having difficulty getting that set up as well. I can add a layer or load in a map without any difficulty locally, but my jsfiddle is refusing to work. Even using someone else's map, just doing this causes the map to fail to load:

```
    map.addLayer({
        "id": "pop-data",
        "type": "fill",
        "source": {
            type: 'vector',
            url: 'mapbox://yoursweater.6h1mo1cs'
        },
        "source-layer": "fullCityLayer",
        "paint": {
            "fill-color": "#ff69b4"
        }
    });
```

**Comment by anandthakker** [comment] 2017-11-27 17:10
Thanks @yoursweater.  I was able to reproduce this issue locally using the expression you provided in the original post.  It looks like the issue is that, for one of the features, `ALAND` is 0, and we're failing to handle the resulting `NaN` properly.   I'll retitle this issue to reflect that bug.

Meanwhile, a temporary workaround would be to replace `["get", "ALAND"]` with `["max", ["get", "ALAND"], 1]` (or some other suitable placeholder value besides `1`)

**Comment by anandthakker** [comment] 2017-11-27 17:10
Actually looks like we have an issue for this for functions already -- let's use that to track.

Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/4172

**Closed by anandthakker** 2017-11-27 17:10 UTC
Labels: needs information
