### ISSUE TITLE
Label under water

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1495] opened 2015-09-17 18:05 UTC
Symbol label is in stylesheet after the water layer, but does not show:
![image](https://cloud.githubusercontent.com/assets/10334123/9941681/3d3d5e2a-5d77-11e5-8431-ca7cf11cd035.png)

**Comment by jfirebaugh** [comment] 2015-09-17 18:07
Thanks for the report. This looks like a duplicate of #757.

**Closed by jfirebaugh** 2015-09-17 18:07 UTC
