### ISSUE TITLE
Heatmap layer on high pitch

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#10183] opened 2020-12-10 20:02 UTC
**mapbox-gl-js version**: 2.0.0

High pitch maps (>60 degrees) using heatmap layers may currently result in flickering due to a loss of texture sampling precision at grazing angles. A few ideas to address this issue:

- Increase offscreen framebuffer resolution size to improve quality (currently defaulting to 1/4th of original viewport resolution). The current 1/4th resolution works well for top down and reduces fragment processing resulting in better performance. We should also check whether this increase of resolution should be configurable based on max pitch.
- Use a different texture filtering (try using anisotropic filtering as we do for draped terrain) and check whether it is a quality win.

These changes would have to be profiled carefully to determine whether it justifies the potential quality improvement.

**Comment by mourner** [comment] 2020-12-10 22:06
Let's close this as a duplicate of #5563.

**Closed by mourner** 2020-12-10 22:06 UTC
