### ISSUE TITLE
Popup dynamic anchor left and bottom

### ISSUE THREAD

**Issue by kodermax** [mapbox/mapbox-gl-js#7774] opened 2019-01-15 06:40 UTC
**mapbox-gl-js version**: 0.52

### Question
Can you configure the anchor to automatically appear to the right of the marker if the popup falls within the map container with a preference for 'bottom'?

### Links to related documentation
https://www.mapbox.com/mapbox-gl-js/api/#popup

**Comment by mourner** [comment] 2019-01-16 18:09
If I understood your question correctly, looks like currently there's no way to do that — you either have to pick a fixed anchor or a fully automatic one with `bottom` by default.

**Comment by kodermax** [comment] 2019-01-17 10:39
Can you add a property here that can be set in the options?

https://github.com/mapbox/mapbox-gl-js/blob/9e07aecf4e94f47c944de035794fd3ad4bf0a83e/src/ui/popup.js#L300

**Comment by kodermax** [comment] 2019-01-23 06:45
> @kodermax Are you asking for #6965 ? Or is this a different issue?

Yes, same.

**Comment by andrewharvey** [comment] 2019-01-23 06:57
Okay I'll close this ticket as a duplicate of #6965 to avoid fragmenting the issue.

**Closed by andrewharvey** 2019-01-23 06:57 UTC
Labels: feature :green_apple:
