### ISSUE TITLE
NPM throws ENOENT error when trying to install

### ISSUE THREAD

**Issue by mhorne89** [mapbox/mapbox-gl-js#5032] opened 2017-07-24 15:10 UTC
The documentation found here tells me to run `npm install --save mapbox-gl` but when I try this I receive the following error.

```
npm ERR! addLocal Could not install /Users/marchorne/conichi/cmc/node_modules/mapbox-gl/src/style-spec
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "mapbox-gl"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path /Users/marchorne/conichi/cmc/node_modules/mapbox-gl/src/style-spec
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/marchorne/conichi/cmc/node_modules/mapbox-gl/src/style-spec'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/marchorne/conichi/cmc/node_modules/mapbox-gl/src/style-spec'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marchorne/conichi/cmc/npm-debug.log
```

My system is MacOS Sierra 10.12.5
Node version: v6.10.0
NPM version: v3.10.10

**Comment by mourner** [comment] 2017-07-24 15:45
Confirmed. Investigating.

**Comment by jfirebaugh** [comment] 2017-07-24 15:48
Duplicate of #5025.

**Closed by jfirebaugh** 2017-07-24 15:48 UTC
Labels: bug, release blocker
