### ISSUE TITLE
Feature Request: Change image in source

### ISSUE THREAD

**Issue by jordandalley** [mapbox/mapbox-gl-js#5794] opened 2017-12-03 12:30 UTC
Hi there,

I have a feature request to be able to change an image url in real time in a source.

For example, if I were to add an image source like the following..

map.addSource('radarimg',{
    type: 'image',
    url: 'https://someserver.com/image1.png',
    coordinates: [
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]
    ]       
});
 map.addLayer({
     id: 'radarimg',
     source: 'radarimg',
     type: 'raster'
});

Now, say I have an array of images that I would like to change on the fly using a setTimeout, something like this:

map.getSource('radarimg').setUrl('https://someserver.com/image2.png');

I have tried setting each individual image as its own layer and source, and turning the layers on and off like in the example here: https://www.mapbox.com/mapbox-gl-js/example/animate-images/

However, in large volumes of images, this is highly inefficient.

If I've missed something here, I apologise. I am a bit of a noob.. :)

**Comment by jfirebaugh** [comment] 2017-12-03 20:31
Thanks for the suggestion @jordandalley. This was previously requested; closing as duplicate of #4050.

**Closed by jfirebaugh** 2017-12-03 20:31 UTC
