### ISSUE TITLE
How can I find the color of a raster layer at a given location?

### ISSUE THREAD

**Issue by jbeuckm** [mapbox/mapbox-gl-js#11641] opened 2022-03-25 19:25 UTC
**mapbox-gl-js version**: latest

### Question

We add a raster layer from a set of png files like `http://server/{z}/{y}/{x}.png`. I need to find the raster color at a particular lat/lon/z.

### Links to related documentation

This seems like a function that could be exposed relative to a Source: https://docs.mapbox.com/mapbox-gl-js/api/sources/

Effectively, the rendering function has to find the color at each pixel that will be displayed. I want to expose that functionality so that, given any displayed position on the map, I could ask for what color the raster source ended up with for that pixel.

**Comment by asheemmamoowala** [comment] 2022-04-04 19:23
Thank you for opening this issue. It looks like it is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/1404. If you feel the issue reported here is different, please share more details and we can reopen it.

**Closed by asheemmamoowala** 2022-04-04 19:23 UTC
