### ISSUE TITLE
What is the proper way to do filtering for a cluster layer?

### ISSUE THREAD

**Issue by emakarov** [mapbox/mapbox-gl-js#2626] opened 2016-05-26 04:55 UTC
Could you share the best recommended way how to do filtering of Features for a cluster layer?
The most preferred way is to filter Feature by property.
But, as I understand, filtering for cluster cannot orient to properties. Is it correct or no?
Details of the task:
- I have list of features, they are clustered
- Then, some property is changing
- I want to filter Features based on changed property, so they will not be inside clusters (disappear from map)

**Comment by mourner** [comment] 2016-05-26 08:23
Closing as a duplicate of #2613 — currently you'll have to filter manually and run `setData` to reset the whole dataset, but we'll look into implementing such a feature in GL JS.

**Closed by mourner** 2016-05-26 08:23 UTC
