### ISSUE TITLE
Issue with japanese symbols in 0.7.0. Getting "glyph bitmap overflow" warning and Uncaught TypeError

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#1138] opened 2015-04-01 18:01 UTC
Hello,

I have found an issue in mapbox-gl-js, that I can reproduce both in 0.7.0 and master.
If you try this page which uses mapbox-gl-dev.js from the CDN, you can reproduce it:
https://www.mapbox.com/mapbox-gl-styles/#15.77/35.6733/139.7795
Just switch to bright and zoom in and out a little.

I can also reproduce it in 0.7.0 on:
https://www.mapbox.com/mapbox-gl-js/examples/
in Chrome and IE.

To reproduce the issue, pretty simple! You only have to zoom in on Tokyo, until you reach street level. You will get many warning in console (about 200) "glyph bitmap overflow" and then, an exeception:

```
Uncaught TypeError: Cannot read property 'leaf' of undefined
```
or sometimes, an error in the bboxArea function, "can't find property "2" of a null or undefined reference.
```
The stack trace is actually for the warning:
>	GlyphAtlas.prototype.addGlyph [mapbox-gl-dev.js] Line 6282	Script
 	GlyphSource.prototype.getRects [mapbox-gl-dev.js] Line 6420	Script
 	get glyphs [mapbox-gl-dev.js] Line 5216	Script
 	Actor.prototype.receive [mapbox-gl-dev.js] Line 9159	Script
```
For the error:
```
>	bboxArea [mapbox-gl-dev.js] Line 17653	Script
 	rbush.prototype._chooseSubtree [mapbox-gl-dev.js] Line 17431	Script
 	rbush.prototype._insert [mapbox-gl-dev.js] Line 17462	Script
 	rbush.prototype.insert [mapbox-gl-dev.js] Line 17270	Script
 	rbush.prototype.load [mapbox-gl-dev.js] Line 17238	Script
 	Collision.prototype.insert [mapbox-gl-dev.js] Line 6132	Script
 	SymbolBucket.prototype.addFeature [mapbox-gl-dev.js] Line 1142	Script
 	SymbolBucket.prototype.addFeatures [mapbox-gl-dev.js] Line 1034	Script
 	parseBucket [mapbox-gl-dev.js] Line 4655	Script
 	Anonymous function [mapbox-gl-dev.js] Line 4645	Script
 	done [mapbox-gl-dev.js] Line 1200	Script
 	Anonymous function [mapbox-gl-dev.js] Line 1260	Script
 	Actor.prototype.receive [mapbox-gl-dev.js] Line 9156	Script
```

Sometimes, it just crashed in _chooseSubtree, sometimes it goes further and crashes in bboxArea, depending on the path.length in _chooseSubtree

I am going to investigate further but this part of the code is just looks complicated and it looks like the code changed in master: you only get the warning but not the error anymore. Maybe some changes @ansis made to the labelling system?

I can't properly test in master because there are other issues at the moment which make the majority of labels disappear for some reason

Fabien

**Comment by jfirebaugh** [comment] 2015-04-01 18:35
Duplicate of #141.

**Closed by jfirebaugh** 2015-04-01 18:35 UTC

**Comment by fnicollet** [comment] 2015-04-01 18:36
Thanks @jfirebaugh , sorry didn't find that duplicate
