### ISSUE TITLE
`Add an icon to the map` documentation not working on  Chrome CentOS7

### ISSUE THREAD

**Issue by uptonking** [mapbox/mapbox-gl-js#4991] opened 2017-07-18 02:14 UTC
**mapbox-gl-js version**: current
chrome: 58.0.3

### Steps to Trigger Behavior

 1. open your official tutorial [add an icon to the map](https://www.mapbox.com/mapbox-gl-js/example/add-image/) in Chrome on CentOS 7.2

### Expected Behavior
        image shows on map
### Actual Behavior
       image not showing on Chrome

note: 
- image shows on firefox 52.1.0. 
- image not showing on opera 45.0.2  

I also found several other examples relating to the image icons not working on Chrome in Linux.
I love your mapbox-gl-js, please do reply to me whether it's the problem of your mapbox-gl-js library's bug or the bug from chrome browser itself

the comparison between chrome(left) and firefox(right) is shown below: 
![mapbox-gl-js-add-image-bug](https://uptonking.github.io/assets/issues/mapbox/mapbox-gl-js-add-image.png)

**Comment by jfirebaugh** [comment] 2017-07-18 02:51
Duplicate of #4928.

**Closed by jfirebaugh** 2017-07-18 02:51 UTC
