### ISSUE TITLE
mapbox-gl.css:1:21755: Can't resolve '%23clip' 

### ISSUE THREAD

**Issue by hmendezm** [mapbox/mapbox-gl-js#12184] opened 2022-08-23 12:44 UTC
In the last version of Mapbox-gl.css, I notice that the file comes %23 instead of #. This is making the CI breaks. is it a way you can use #? I was not like that before.

./node_modules/mapbox-gl/dist/mapbox-gl.css - Error: Module Error (from ./node_modules/@angular-devkit/build-angular/node_modules/postcss-loader/dist/cjs.js):
/home/vsts/work/1/s/node_modules/mapbox-gl/dist/mapbox-gl.css:1:21755: Can't resolve '%23clip' in '/home/vsts/work/1/s/node_modules/mapbox-gl/dist'

Best

**Comment by mourner** [comment] 2022-08-23 14:37
Duplicate of #12164

**Closed by mourner** 2022-08-23 14:37 UTC
