### ISSUE TITLE
Slivers appear between adjacent non-opaque polygon-fills as pitch increases

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2060] opened 2016-02-04 18:58 UTC
Experienced on OS.X, Chrome.

mapbox-gl-js 0.12.2:

![0 12 2](https://cloud.githubusercontent.com/assets/1205805/12826006/4bb4bfa0-cb79-11e5-8498-7fb0d53979a9.gif)

mapbox-gl-js 0.12.3-0.13.1:

![0 12 3](https://cloud.githubusercontent.com/assets/1205805/12826014/525ed278-cb79-11e5-9f2d-2c1b1b1b7e14.gif)

Please note that this only happens when fill-opacity is set below 1.

**Comment by averas** [comment] 2016-02-04 22:47
If you want to reproduce this you can generate a hexgrid with turf.js:

<img width="925" alt="screen shot 2016-02-04 at 23 45 50" src="https://cloud.githubusercontent.com/assets/1205805/12832330/90190dde-cb99-11e5-8130-03bda368d72b.png">

This example also indicates that the problem occurs when the adjacent polygons have different color.

**Comment by danswick** [comment] 2016-02-16 21:19
@averas Great bug report. I am able to reproduce on my end using GeoJSON neighborhood boundaries. Regarding your second post, I am wondering if this has more to do with the fact that the hexes are in different layers than the fact that they're different colors.

**Comment by lucaswoj** [comment] 2016-02-17 18:40
This is most likely under the umbrella of #2096

**Comment by ansis** [comment] 2016-02-25 21:18
@averas is this fixed in master (by https://github.com/mapbox/mapbox-gl-js/issues/2096)?

**Comment by averas** [comment] 2016-02-25 21:43
Unfortunately it doesn't appear so. I'll fix a codepen for you so that you can investigate the behaviour.

**Comment by ansis** [comment] 2016-02-25 21:55
Thanks!

**Comment by averas** [comment] 2016-02-25 22:17
http://codepen.io/anon/pen/jqNpNB

You will have to change the script-reference to a master-build.

Another observation from that codepen.. Why the heck do the labels render on top of the polygons? And why does it only happen when opacity is set to 1?

**Comment by ansis** [comment] 2016-02-25 22:23
> Another observation from that codepen.. Why the heck do the labels render on top of the polygons? And why does it only happen when opacity is set to 1?

It's a bug caused by how we use depth clipping: https://github.com/mapbox/mapbox-gl-js/issues/2074

**Comment by averas** [comment] 2016-02-25 22:24
Ah, alright.

**Comment by averas** [comment] 2016-02-26 10:30
Another observation...

If you open http://codepen.io/anon/pen/NNKLeJ and click back and forth on the opaque/transparent buttons you will notice that generally when you click on the opaque button, all polygons become opaque, the slivers disappear and the depth clipping bug mentioned above comes into play...

Sometimes when you click the opaque button, however, the polygons do become opaque, but the slivers do _not_ disappear and the depth clipping bug does _not_ come into play. Not sure if this is at all related to any of the mentioned bugs or whether it is some other phenomena showing. If you drag around the map at this point you will reach the point where slivers disappear and labels pop over the polygons again.

**Comment by averas** [comment] 2016-03-23 14:16
@ansis Did you pin down the root cause of this problem?

**Closed** 2016-03-23 20:11 UTC

**Comment by averas** [comment] 2016-03-23 22:37
... I take that as a yes. :-) Great work @ansis!
