### ISSUE TITLE
Aspect ratio is off when window is resized in Safari

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#5691] opened 2017-11-16 12:04 UTC
When I had a map displaying in Safari 11.0.1 on the built-in screen of my notebook, then connected an external monitor, the Safari window moved to the external monitor. In that process, the window got resized, but now the aspect ratio is off:

![mapbox streets mapbox 2017-11-16 12-59-31](https://user-images.githubusercontent.com/52399/32890334-a5349ea0-cace-11e7-9c67-4f81aa17257a.png)

I couldn't reproduce this issue with Google Chrome.

**Comment by jfirebaugh** [comment] 2017-11-16 23:12
Does it correct itself if you resize the window after it moves to the external monitor? Or is it always distorted on the external monitor? If the latter, this is probably a duplicate of #5273 / #2673.

**Comment by mourner** [comment] 2018-07-25 12:41
Closing as a browser bug that we are unable to address on the GL JS side.

**Closed by mourner** 2018-07-25 12:41 UTC
Labels: bug :beetle:, environment-specific :desktop_computer:
