### ISSUE TITLE
`div` markers shift position near map edge on drag

### ISSUE THREAD

**Issue by mrlubos** [mapbox/mapbox-gl-js#9768] opened 2020-06-08 16:32 UTC
**mapbox-gl-js version**:
1.10.1

**browser**:
Chrome 83.0.4103.97

### Steps to Trigger Behavior

 1. Create HTML marker using `div` element as a wrapper
 2. Drag the map until the marker approaches the map edge
 3. Observe the marker shifts position.

### Link to Demonstration

See [react-mapbox-gl demo](http://alex3165.github.io/react-mapbox-gl/demos).

1. Choose the `html-marker` demo.
2. Search for "London Heathrow Airport."
3. Click the result to display a marker.
4. Follow steps to reproduce the issue above.

### Expected Behavior

Marker does not shift its position. In fact, I am unable to reproduce this issue when using plain `svg` icons. It only happens when I wrap the icon inside `div` element.

### Actual Behavior

Marker shifts its position.

![Screen Recording 2020-06-09 at 12 14 43 am](https://user-images.githubusercontent.com/12529395/84056267-8fe6dd00-a9e8-11ea-8624-9187292a3436.gif)

**Comment by ansis** [comment] 2020-06-08 20:16
Could you try to create an example that reproduces this without the react wrapper?

**Comment by andrewharvey** [comment] 2020-06-09 02:43
This looks like the default auto-anchoring behaviour of a Marker. If you don't want auto-anchoring you can set `anchor` to `bottom` and it won't change https://docs.mapbox.com/mapbox-gl-js/api/markers/#popup. Is that the issue here?

**Comment by mrlubos** [comment] 2020-06-10 07:47
Hi @ansis @andrewharvey, thanks for looking into this! Indeed, I have been unable to reproduce this issue using just Mapbox, so I am inclined to believe this is an issue with `react-mapbox-gl`

**Comment by andrewharvey** [comment] 2020-06-10 08:04
I'll close this issue here then as it most likely relates to react-mapbox-gl.

**Closed by andrewharvey** 2020-06-10 08:04 UTC
Labels: needs information :pray:
