### ISSUE TITLE
Draw the route animation with Caton's rollback problem

### ISSUE THREAD

**Issue by JunYanchan** [mapbox/mapbox-gl-js#4943] opened 2017-07-06 02:46 UTC
1.I through the requestAnimationframe, each loop 3 lines to push a route array, and then through the setData set this array on the lineString on the coordinates, but there will be the following picture of the situation, there is Caton back off the problem. Seek help to solve, extremely grateful!

![image](https://joyrun-activity.b0.upaiyun.com/h5_demo/demo.gif)

mapbox-gl-js version:0.38

 Expected Behavior：
     There is no problem with Caton's rollback
 Actual Behavior：
     Occasionally there will be Caton back off the problem, and very frequent

**Comment by mollymerp** [comment] 2017-07-06 23:20
Hi @JunYanchan
Thank you for submitting your issue. I'm not sure what the issue you're describing is. Can you please provide a minimal jsfiddle that reproduces the problem? 

Thanks!

**Comment by JunYanchan** [comment] 2017-07-07 04:05
@mollymerp Thank you for your reply and help, I have put the demo on jsfiddle, [and](https://jsfiddle.net/tj8m3k4q/6/) I have generated 1000 points is a straight line, you observe the next animation, you will find occasional flicker, roll back, Caton phenomenon, I do not Know why this is the reason I began to think that the data points caused by latitude and longitude will be back, but I will generate the line will be very strange.

**Comment by JunYanchan** [comment] 2017-07-07 04:06
@mollymerp Thank you for your reply and help, I have put the demo on [jsfiddle](https://jsfiddle.net/tj8m3k4q/6/), and I have generated 1000 points is a straight line, you observe the next animation, you will find occasional flicker, roll back, Caton phenomenon, I do not Know why this is the reason I began to think that the data points caused by latitude and longitude will be back, but I will generate the line will be very strange.

**Comment by JunYanchan** [comment] 2017-07-10 02:29
@mollymerp Is there any new progress? Thank you

**Comment by mollymerp** [comment] 2017-07-10 06:36
@JunYanchan I can see a flicker, which I believe is because new tiles are sometimes loading when the map's center is changed ( which is happening on every frame). 

I am not able to reproduce the jumping behavior in the original gif you posted, but I imagine it might be that the `setData` call (which is asynchronous) isn't finishing in time for the `setCenter` call so the line appears to jump off center briefly. You could try to solve this by waiting for the `sourcedata` event for your source to fire before updating the map's center. (ex: https://jsfiddle.net/tj8m3k4q/8/)

When I remove the `map.setCenter` call or change the map's zoom to a lower number I no longer see the occasional flickering. 

I don't think this is actionable for us to fix, so I'm going to close this issue.

**Closed by mollymerp** 2017-07-10 06:36 UTC
Labels: needs information

**Comment by JunYanchan** [comment] 2017-07-10 07:27
@mollymerp Thank you for your reply, but I found that although the sourcedata event in your sourcedata event as you call the set map midpoint, or there will be **Marker** back phenomenon, and I cited to my actual project, through the soucedata event call, **Marker** back more serious, I think this is not feasible. Can you help me again?
