### ISSUE TITLE
Using layer as style / basemap

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#8590] opened 2019-08-02 17:13 UTC
Since changing a style removes all layers, I wanted to see if setting the basemap (or "style") as the first layer would work. However, I can't seem to figure how to do that. 

I can add a vector source, eg:

    map.addSource("basemap", {
        "mapbox-streets": {
            type: "vector",
            url: "mapbox://mapbox.mapbox-streets-v6"
        }
    });

.. but then `map.addLayer()` only has a `raster` type, no `vector`. 

How do I add this vector source as a basemap layer?

Thanks

**Comment by andrewharvey** [comment] 2019-08-02 22:20
cross posted at https://stackoverflow.com/questions/57306917/using-layer-as-style-basemap

**Comment by asheemmamoowala** [comment] 2019-08-07 06:30
@3zzy thank you for using mapbox-gl-js. The library does not have a concept of a basemap. A map can be intitialized with a preset style, which can be modified at runtime by adding/removing/modifiying sources and layers. 

If you have raster tiles representing your basemap, you can add that as a single source and `raster` layer. Another option is to keep track of the layers and sources added by your code at runtime, and re-apply them when changing a style.

Closing this as duplicate of #4006

**Closed by asheemmamoowala** 2019-08-07 06:30 UTC
