### ISSUE TITLE
Animating markers

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1207] opened 2015-05-16 21:05 UTC
Piggybacking off of https://github.com/mapbox/mapbox-gl-js/issues/1203: I'm interested in doing [this](https://www.mapbox.com/bites/00115/) sort of thing in GL.

I would supply a geoJSON path, duration, and easing to move a marker. Two requirements:

- 30-60 fps
- Animation keeps up with map movement

I suppose we can `source.setData(geojson)` over and over, at a very high frequency to simulate a moving animation, but there might be a better way.

**Comment by tmcw** [comment] 2015-05-17 14:05
Duplicate of #1180

**Closed by tmcw** 2015-05-17 14:05 UTC

**Comment by misterfresh** [comment] 2016-04-13 08:19
probably late for @peterqliu , but other users facing this issue can take a look at [mapbox-animation](https://github.com/misterfresh/mapbox-animation)
