### ISSUE TITLE
Enable panning with multiple touch points

### ISSUE THREAD

**Issue by danielmorgan** [mapbox/mapbox-gl-js#2719] opened 2016-06-11 18:13 UTC
I've made a modification to the DragPanHandler to enable a feature I wanted in my implementation: Being able to pan the map with more than one finger. This hacky way I've done it probably wouldn't be suitable for merging back in, as evidenced by the fact that there is an explicit check to prevent this behaviour in `DragPanHandler::_ignoreEvent` that I have disabled.

Just wondering if multi-finger panning is something that could become a supported option, and if so what considerations are there for a robust implementation? Or is this something that can even be done in the user's implementation?

```patch
diff --git a/js/ui/handler/drag_pan.js b/js/ui/handler/drag_pan.js
index f0951d4..56128e5 100644
--- a/js/ui/handler/drag_pan.js
+++ b/js/ui/handler/drag_pan.js
@@ -94,8 +94,12 @@ DragPanHandler.prototype = {
             this._fireEvent('movestart', e);
         }
 
-        var pos = DOM.mousePos(this._el, e),
-            map = this._map;
+        var pos = (function(el, e) {
+            if (e.touches) return DOM.touchPos(el, e)[0];
+            return DOM.mousePos(el, e);
+        })(this._el, e);
+
+        var map = this._map;
 
         map.stop();
         this._drainInertiaBuffer();
@@ -180,9 +184,7 @@ DragPanHandler.prototype = {
 
         if (map.boxZoom && map.boxZoom.isActive()) return true;
         if (map.dragRotate && map.dragRotate.isActive()) return true;
-        if (e.touches) {
-            return (e.touches.length > 1);
-        } else {
+        if (!e.touches) {
             if (e.ctrlKey) return true;
             var buttons = 1,  // left button
                 button = 0;   // left button
```

**Comment by lucaswoj** [comment] 2016-06-13 16:26
Thanks for working on this feature @danielmorgan! I am supportive of adding this feature. Cut a PR with this diff and we'll talk about implementation details 😄

**Comment by lucaswoj** [comment] 2016-07-29 20:28
Closing as a duplicate of #2618

**Closed by lucaswoj** 2016-07-29 20:28 UTC
Labels: enhancement

**Comment by rantiev** [comment] 2018-06-28 11:11
@lucaswoj I hope #2618 won't be closed as a duplicate of this one )
