### ISSUE TITLE
[Mapbox China] Error: Source layer "china_island" does not exist on source "composite"

### ISSUE THREAD

**Issue by tomacadi** [mapbox/mapbox-gl-js#6760] opened 2018-05-30 09:28 UTC
**mapbox-gl-js version**: v0.44.2

I am using mapbox-gl-js with API_URL: 'https://api.mapbox.cn'
https://github.com/mapbox/mapbox-gl-js/issues/6620

The map is intended for users in mainland China. The map loads and seems to work fine.
The map error event is triggering with the following erros:

```
{error: Error: Source layer "china_island" does not exist on source "composite" as specified by style layer …, type: "error", target: e, style: r}
{error: Error: Source layer "china_boundary_global" does not exist on source "composite" as specified by sty…, type: "error", target: e, style: r}
{error: Error: Source layer "china_place_global" does not exist on source "composite" as specified by style …, type: "error", target: e, style: r}
{error: Error: Source layer "china_country_label" does not exist on source "composite" as specified by style…, type: "error", target: e, style: r}

Error: Source layer "china_island" does not exist on source "composite" as specified by style layer "china-boundary-island-fill" at r._validateLayer (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:381:4120) at r.<anonymous> (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:381:2375) at r.Evented.fire (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:521:844) at t.Evented.fire (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:521:1086) at t.Evented.fire (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:521:1086) at https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:231:1153 at u (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:207:441) at XMLHttpRequest.r.onload (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:503:1103)
message
:
"Source layer "china_island" does not exist on source "composite" as specified by style layer "china-boundary-island-fill""
stack
:
"Error: Source layer "china_island" does not exist on source "composite" as specified by style layer "china-boundary-island-fill"↵    at r._validateLayer (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:381:4120)↵    at r.<anonymous> (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:381:2375)↵    at r.Evented.fire (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:521:844)↵    at t.Evented.fire (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:521:1086)↵    at t.Evented.fire (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:521:1086)↵    at https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:231:1153↵    at u (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:207:441)↵    at XMLHttpRequest.r.onload (https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.js:503:1103)"
__proto__
:
Object

```

###Question
Is this intended behaviour given the China mainland traffic limitations?

**Comment by jfirebaugh** [comment] 2018-06-01 17:41
cc @chriswu42

**Comment by chriswu42** [comment] 2018-06-04 18:06
This is caused by gl js trying to find the names of features but returns errors because the names don't match up (new china features vs existing global features). Note that this does not affect how the map is rendered.

@zmofei is working on a fix to eliminate these debugging errors.

**Comment by tomacadi** [comment] 2018-06-05 06:47
Thank you for the reply. Is there a specific place where progress on this fix is being tracked?

**Comment by chriswu42** [comment] 2018-06-08 17:00
> Is there a specific place where progress on this fix is being tracked?

After further investigation this might be an issue on our api side - we're currently blocked on this due to a few technical dependencies, once we have a fix we'll post back.

**Comment by mourner** [comment] 2018-07-25 07:19
Meanwhile I'll close this as something that's not actionable on the GL JS side.

**Closed by mourner** 2018-07-25 07:19 UTC

**Comment by q869939686** [comment] 2018-08-16 06:05
How can I solve these mistakes?

**Comment by PhilipBrodovsky** [comment] 2019-03-15 13:29
k

**Comment by PhilipBrodovsky** [comment] 2019-03-15 13:30
Duplicate the style and use the new style id
To me that solved the problem
