### ISSUE TITLE
Long text wrapping issue

### ISSUE THREAD

**Issue by ramunasd** [mapbox/mapbox-gl-js#2368] opened 2016-03-30 14:31 UTC
**mapbox-gl-js version**: all tested from 0.12.3 to 0.16.0 has same issue

### Style
```javascript
               {
                        id: "lines-ref",
                        minzoom: 14,
                        type: "symbol",
                        source: "pt-vector",
                        "source-layer": "lines_high",
                        layout: {
                                "symbol-placement": "line",
                                "text-field": "{train_ref}",
                                "text-size": 10,
                                "text-max-angle": 60
                        },
                        paint: {
                                "text-color": "#000",
                                "text-halo-color": "#fff",
                                "text-halo-width": 2,
                                "text-halo-blur": 1
                        }
                }
```

### Expected Behavior
Smoothly wrapped text into second line without strange artefacts.

### Actual Behavior
![selection_011](https://cloud.githubusercontent.com/assets/150403/14145459/a52de612-f69c-11e5-8bfa-660b96fa0a52.png)
![selection_012](https://cloud.githubusercontent.com/assets/150403/14145468/ad71f1ec-f69c-11e5-9f10-677bfb0a2af2.png)

**Comment by lucaswoj** [comment] 2016-03-30 16:54
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/1531. 

cc @ansis

**Closed by lucaswoj** 2016-03-30 16:54 UTC
