### ISSUE TITLE
Additional "artifact" circles when using data-driven-styling by zoom on 'circle-radius'

### ISSUE THREAD

**Issue by kdanaher** [mapbox/mapbox-gl-js#6386] opened 2018-03-23 15:42 UTC
**mapbox-gl-js version**: 0.44.1

### Steps to Trigger Behavior

 1.  Add layer of `'type': 'circle'` and style `circle-radius` with data driven styling factoring zoom level
 2. Tested using both older `stops` method as well as newer expressions method. 

### Expected Behavior
In a previous API version **(0.32.1)** 
![v32dds](https://user-images.githubusercontent.com/17933661/37838282-e1fb9fb4-2e8d-11e8-9d99-c4fc2826da54.gif)

### Actual Behavior

![v44dds](https://user-images.githubusercontent.com/17933661/37838375-1c89dad8-2e8e-11e8-8e4a-cfcc05a5e94e.gif)

As stated above, I've styled `circle-radius` using the older and newer methods:

Older "stops" method
```
'circle-radius': {
    property: property_id,
    type: 'exponential',
    stops: [[{"zoom": 4,"value": circle_sizes[0]}, 1],
            [{"zoom": 4,"value": circle_sizes[2]}, 9],
            [{"zoom": 5,"value": circle_sizes[0]}, 2],
            [{"zoom": 5,"value": circle_sizes[2]}, 18],
            [{"zoom": 6,"value": circle_sizes[0]}, 4],
            [{"zoom": 6,"value": circle_sizes[2]}, 36],
            [{"zoom": 7,"value": circle_sizes[0]}, 8],
            [{"zoom": 7,"value": circle_sizes[2]}, 72],
            [{"zoom": 8,"value": circle_sizes[0]}, 16],
            [{"zoom": 8,"value": circle_sizes[2]}, 144]]
}
```

Newer expressions method
```
'circle-radius': [
    "interpolate",
    ["exponential", 1],
    ["zoom"],
    4, ["sqrt", ["*", ["get", property_id], 5]],
    8, ["sqrt", ["*", ["get", property_id], 160]]
]
```

**Comment by jfirebaugh** [comment] 2018-03-23 16:08
Thanks for the report @kdanaher. Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?

**Comment by kdanaher** [comment] 2018-03-23 16:59
Surely -- http://jsbin.com/yobagowica/edit?html,output

The "artifact" circles seem to appear on exact zoom levels. In the linked jsbin, it can be noticeably triggered at z6. Depending on how I write the expression/stops it seems to get better/worse.

**Comment by jfirebaugh** [comment] 2018-03-23 23:27
Thanks! This is a duplicate of #5829 / #4691.

**Closed by jfirebaugh** 2018-03-23 23:27 UTC

**Comment by jfirebaugh** [comment] 2018-05-31 17:57
→ #6768
