### ISSUE TITLE
addLayer: layout.icon-allow-overlap is ignored

### ISSUE THREAD

**Issue by rolandoldengarm** [mapbox/mapbox-gl-js#3799] opened 2016-12-14 07:28 UTC
I'm adding a layer of hotel icons, like this:
````
 this.map.addLayer({
        'id': 'hotels',
        'type': 'symbol',
        'source': 'hotels',
        'layout': {
            'icon-image': "icon-hotel",
            'icon-size': 0.2,
            'icon-allow-overlap': true
        },
      
    });
````
**mapbox-gl-js version**: 0.28.0

However, when I zoom out, I only see one marker. When I zoom in, I see more and more icons.
I want to see all icons, no matter what the zoom level is. 

I don't see any difference between icon-allow-overlap true or false.
### Expected Behavior
When zooming out, I expect to see all markers
### Actual Behavior
Only when I zoom in, I see all markers.

**Comment by peterqliu** [comment] 2016-12-14 07:35
@rolandoldengarm can you provide a test case?

**Comment by rolandoldengarm** [comment] 2016-12-14 08:13
Yes, I've got a Fiddle. However, it contains our custom style plus our API key... Can I share this privately somehow? @peterqliu

**Comment by peterqliu** [comment] 2016-12-14 18:14
ah, this isn't obvious from the documentation, but each symbol consists of an optional `icon` (the graphical sprite) and an optional `text` (the label). To disable collision behavior for symbols, we must allow overlap of both text and icons ([documentation](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-text-allow-overlap)). 

Add `text-allow-overlap:true` to your fiddle,  and voila:

⭐️ 🌠 🚀 
<img width="650" alt="screen shot 2016-12-14 at 10 08 50 am" src="https://cloud.githubusercontent.com/assets/4551508/21194768/00fadb2a-c1e6-11e6-9a60-85d00098632b.png">

**Comment by jfirebaugh** [comment] 2016-12-14 18:40
Thanks for digging in @peterqliu. Closing here since this is expected behavior, but I'll make a note in https://github.com/mapbox/mapbox-gl-style-spec/issues/405.

**Closed by jfirebaugh** 2016-12-14 18:40 UTC

**Comment by rolandoldengarm** [comment] 2016-12-14 20:00
Thanks @peterqliu this works :)

**Comment by cyrilchapon** [comment] 2018-07-06 09:02
This doesn't work anymore. How to have this behavior again ?
