### ISSUE TITLE
North/South values of the LngLatBounds members are swapped

### ISSUE THREAD

**Issue by davecranwell** [mapbox/mapbox-gl-js#3127] opened 2016-09-01 13:58 UTC
Mapbox 0.23.0

Here's a reduced case:

http://jsbin.com/wisajipibe/edit?html,js,output

It seems requesting `getNorthWest()` actually gets South West.

**Comment by jfirebaugh** [comment] 2016-09-01 14:59
Duplicate of #3081.

**Closed by jfirebaugh** 2016-09-01 14:59 UTC
