### ISSUE TITLE
Add hooks into the render pipeline

### ISSUE THREAD

**Issue by vicapow** [mapbox/mapbox-gl-js#1742] opened 2015-11-20 22:40 UTC
Would love to be able to add our own custom webGL overlays between existing layers. something like this maybe?

````js
map.renderHookAfterLayer('before-this-layer', function renderCallback(gl) {
  // gl calls.
});
````

Specifically, this would allow us to add custom overlays like heatmaps, etc. with labels on top and geo below.

**Comment by vicapow** [comment] 2015-12-04 03:39
very similar to: https://github.com/mapbox/mapbox-gl-js/issues/281 maybe a duplicate?

**Comment by enjalot** [comment] 2016-01-20 22:37
+1
don' think this is a duplicate, overlay would be different from something like being able to run a desaturation filter on a raster layer which needs #281 I believe.

**Comment by lucaswoj** [comment] 2016-01-20 22:49
**IF** we consider this feature, it'll be after we have a bulletproof solution for https://github.com/mapbox/mapbox-gl-js/issues/145.

**Comment by lucaswoj** [comment] 2016-01-21 20:10
I'm going to call this a duplicate of #281 and re-ope that issue.

**Closed by lucaswoj** 2016-01-21 20:10 UTC
