### ISSUE TITLE
An error occurred while parsing the WebWorker bundle

### ISSUE THREAD

**Issue by Looxor** [mapbox/mapbox-gl-js#11142] opened 2021-10-20 13:55 UTC
Hi Everybody👋 !

I have an issue on building react-map-gl using Webpack

I've created an application using **_create-React-App_** and **_React-MAP-GL_**.

When I try to build and run this app in production mode, it gives me this error.

An error occurred while parsing the WebWorker bundle. 
This is most likely due to improper transpilation by Babel; please see 
https://docs.mapbox.com/mapbox-gl-js/api/#transpiling-v2

**Screenshot :**
<img width="1230" alt="Screen Shot 2021-10-20 at 3 49 07 PM" src="https://user-images.githubusercontent.com/1319853/138106429-72546e2f-7875-4ee0-8617-0b5483040280.png">

I've read the articles and tried but not fixed.

I think that the main problem is that I am using **_React-map-gl_** not **_Mapbox-gl-js_**.

Can you please let me know how to fix this problem?

**Comment by arindam1993** [comment] 2021-11-01 19:28
Hey @Looxor , your problem is a duplicate of whats being discussed in https://github.com/mapbox/mapbox-gl-js/issues/10565#issuecomment-881101108.

**Closed by arindam1993** 2021-11-01 19:28 UTC
