### ISSUE TITLE
Add ability to style circle border

### ISSUE THREAD

**Issue by kiRach** [mapbox/mapbox-gl-js#2411] opened 2016-04-08 15:15 UTC
Hey guys, thank you for your awesome work.

Feature request for me: it would be helpful to add ability to style circle borders. Something like:

```
'circle-border': 1,
'circle-border-color': '#ffffff'
```

**Comment by mourner** [comment] 2016-04-08 15:38
The way to do that currently is to create another layers with bigger circle of a different color underneath the first one.

**Comment by kiRach** [comment] 2016-04-08 15:59
@mourner Thanks for quick reply!

Yeah, I've already considered this solution but there is one minor issue here.

So, what here is how it should like in ideal:
<img width="341" alt="compstak_search_old" src="https://cloud.githubusercontent.com/assets/1084659/14389482/d80fbade-fd80-11e5-8931-f94f847b92c9.png">

And here how it looks like with proposed solution:
<img width="428" alt="compstak_dashboard_nextgen" src="https://cloud.githubusercontent.com/assets/1084659/14389506/e9a15c3a-fd80-11e5-95cd-6752f0bac416.png">

So the problem is when it comes to overlapping. If border would be part of the circle - it would look more attractively.

**Comment by mourner** [comment] 2016-04-08 16:04
@kiRach oh, right. I think the current workaround for that, if you use circles of the same radius, to just use an icon instead, with the circle rendered in the style sprite.

**Comment by mcwhittemore** [comment] 2016-04-08 16:56
I've found myself doing the two layer solution for this a lot, so I see this as helpful.

**Comment by vicapow** [comment] 2016-04-14 17:39
I think this is a duplicate of #1713 which was moved to the style repo at https://github.com/mapbox/mapbox-gl-style-spec/issues/379

**Comment by benj-d** [comment] 2016-04-21 17:04
Also interested in this. In my case i only want the border to show. kiRach suggestion should allow me to  make the fill transparent leaving on the border visible. In my case the circle radius is also adjustable by the user, though i guess this could also be done with an icon..?

(To be fair wouldn't be necessary if turf.buffer was geodetic or "turf.circle" implemented (https://github.com/Turfjs/turf/issues/301) not that i know enough to weight up performance hits..)

**Comment by planemad** [comment] 2016-05-30 12:52
👍 for this. Circular rings can be a very powerful visualization element to bring focus to certain parts of the map. There is no way to currently do this in GL.

![screenshot 2016-05-30 18 20 56](https://cloud.githubusercontent.com/assets/126868/15650031/554d3e6e-2693-11e6-91b0-244d177b46c3.png)

**Comment by aakim26** [comment] 2016-06-10 17:22
Agreed, I would love to see this implemented. Currently working with earthquakes and the overlap is a big issue. 
![screenshot 2016-06-10 10 17 55](https://cloud.githubusercontent.com/assets/13665982/15972789/3a97a874-2ef5-11e6-8a53-b7b4f1c09214.png)

**Comment by jplante** [comment] 2016-10-04 14:32
Yes, and having translucent circles makes this solution problematic for proper visualization

**Comment by princeofnaxos** [comment] 2016-10-21 09:41
+1

**Comment by jfirebaugh** [comment] 2016-12-02 01:53
Implemented in #3672.

**Closed by jfirebaugh** 2016-12-02 01:53 UTC
Labels: enhancement
