### ISSUE TITLE
symbol-spacing is buggy

### ISSUE THREAD

**Issue by usb248** [mapbox/mapbox-gl-js#9866] opened 2020-07-10 09:12 UTC
**mapbox-gl-js version**: 1.11.1

**browser**: Last version of FF

### Steps to Trigger Behavior

draw a symbol on a linestring with this options:
```javascript
                        layout: {
                            'symbol-placement': 'line',
                            'symbol-spacing': 140,
                            'text-offset': [0, .2],
                            'icon-optional': true,
                            'text-font': ['my_pbf_font'],
                            'text-allow-overlap': true,
                            'text-ignore-placement': true,
                            'text-keep-upright': false,
                            'text-line-height': 1,
                            'text-field': String.fromCharCode("0xe900"),
                            'text-padding': 0,
                            'text-size': 12.5
                        },
```

### Link to Demonstration
![image](https://user-images.githubusercontent.com/7659927/87138041-25061b80-c29e-11ea-821b-5bf8ec095f2c.png)

### Expected Behavior
Spacing must be the same everywhere
### Actual Behavior
Spacing is random/not regular

Certainly related to : https://github.com/mapbox/mapbox-gl-js/issues/5259
Which has never been resolved since 2017.........
The bug occurs with `icon-image` too
```javascript
                                'layout': {
                                    'symbol-placement': 'line',
                                    'symbol-spacing': 80,
                                    'icon-allow-overlap': true,
                                    'icon-image': 'direction',
                                    'icon-size': .1
                                }
```
![image](https://user-images.githubusercontent.com/7659927/87140761-4bc65100-c2a2-11ea-9273-4ce15db57db4.png)

**Comment by mourner** [comment] 2020-07-10 11:06
I can't say for sure because you haven't provided a live test case prompted by the issue template, but I'll take a guess that if you put `map.showTileBoundaries = true`, you'll see that the wider gap is going across a tile boundary. Since tiles are processed independently of one another, there's technically no way to know how to offset the spacing in one tile according to how much of it left in the adjacent one. This is a known limitation of GL JS, so I'm going to close the issue.

**Closed by mourner** 2020-07-10 11:06 UTC

**Comment by usb248** [comment] 2020-07-10 11:27
![image](https://user-images.githubusercontent.com/7659927/87149628-e7f75480-c2b0-11ea-90b8-c3dd4412f297.png)
Not exactly what you said :/

**Comment by mourner** [comment] 2020-07-10 11:41
@usb248 there's still no live test case, so I can't tell 🤷

**Comment by usb248** [comment] 2020-07-10 12:40
Sorry i'm not friendly with test case yet. So i can't tell too 🤷.
let's keep living with this bug 🎉

**Comment by mourner** [comment] 2020-07-10 14:12
@usb248 by test case, I mean a minimal page on JSFiddle or JSBin where we can reproduce the issue. It's impossible to fix something based on a screenshot.

**Comment by usb248** [comment] 2020-07-10 14:18
I will try to do a jsfiddle in the next few days. I not easy because i'm coding a complex drawing app with mapbox gl (connected with a database moreover) and not public (proxy) url ...

**Comment by usb248** [comment] 2020-07-15 16:33
I switched to icon-* (with spf: true for dynamic color) which is no buggy.
