### ISSUE TITLE
Opacity multiplication when offsetting polygons

### ISSUE THREAD

**Issue by isimonescu** [mapbox/mapbox-gl-js#3157] opened 2016-09-07 11:12 UTC
When offsetting polygons to the inner side and using transparency, you get line overlapping.

![image](https://cloud.githubusercontent.com/assets/5670067/18309908/f5b85b34-74fb-11e6-943e-757f090fa6b1.png)

Not sure is this is an incorrect line joining issue or just an incorrect use of the stencil buffer.

I managed to overcome this on GL native by using a custom layer and rendering the polygons on my own. But I would like to see this done also in JS, where AFAIK there is no support for custom layers.

The easy fix here would be to fill the polygon into the stencil buffer and then make another pass with the offset, using the stencil buffer to figure out where to draw.

This would be a killer feature for borders, indicating which side you are on.

**Comment by jfirebaugh** [comment] 2016-09-07 14:21
Duplicate of #794.

**Closed by jfirebaugh** 2016-09-07 14:21 UTC
