### ISSUE TITLE
featuresAt behaviour changed in 0.14.0

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2100] opened 2016-02-10 10:04 UTC
I noticed a bug in mapbox-gl-draw (https://github.com/mapbox/mapbox-gl-draw/issues/225) which is only present when using mapbox-gl-js 0.14.0 and not 0.13.1. It seems as if when running featuresAt on a layer with features that are close to each other (geographically) they start to interfere.

If you bring up http://codepen.io/anon/pen/wMRBgr and click on features you will see that it is working as expected. If you however change the mapbox-gl-js version from 0.13.1 to 0.14.0 you will see that when you click on a marker, another marker will be selected. You can even click far out on the background, and still markers will be selected, even though radius is set to 5.

**Comment by mcwhittemore** [comment] 2016-02-10 14:35
@averas we might be able to patch this fix in mapbox-gl-draw by sorting the features returned by closet to the click point.

**Comment by averas** [comment] 2016-02-10 15:10
@mcwhittemore Alright, but there must also be some kind of bug involved.. even with a featuresAt radius set to 5 in the example I posted you get hits much further away than that.

**Comment by mcwhittemore** [comment] 2016-02-10 15:25
@averas spent some time debugging this on the gl-draw side and I agree, this is best handled in gl-js. Looking for the commit that caused the regression now

**Comment by mcwhittemore** [comment] 2016-02-10 16:02
@ansis it looks like 1da1e5ab2bd10ea4d427d4f8dacd77e54f47e0b9 is the culprit here

**Comment by ansis** [comment] 2016-02-10 23:40
@mcwhittemore thanks for tracking it down

https://github.com/mapbox/mapbox-gl-js/pull/2104 should fix this

**Comment by ansis** [comment] 2016-02-11 21:59
fixed by https://github.com/mapbox/mapbox-gl-js/pull/2104

**Closed by ansis** 2016-02-11 21:59 UTC
