### ISSUE TITLE
Symbol rendering issue 40.1

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#5335] opened 2017-09-20 13:46 UTC
Symbols flicker when using scroll zoom. After a single drag-pan, symbols stop flickering during scroll zooms. See attached gif.

![ezgif-1-226e445458](https://user-images.githubusercontent.com/5638107/30647000-cc09772a-9e1a-11e7-99bf-9b7b8c791ba6.gif)

Environment:

OS X El Capitan
Chrome 61.0.3163.91 64 bit

**mapbox-gl-js version**: 40.1

### Steps to Trigger Behavior

 1. Load the map
 2. Start scroll zoom
 3. Labels flickers

**Comment by ChrisLoer** [comment] 2017-09-20 18:18
We can reproduce the similar (probably duplicate?) behavior described in #5333 -- it appears to be tied to the latest update to Chrome, and reproduces in older version of mapbox-gl-js as well. We're investigating.

**Comment by ChrisLoer** [comment] 2017-09-21 19:29
I believe this is a duplicate of #5333. Please re-open if you can reproduce outside of our examples page. We plan to publish a workaround to the examples page soon.

**Closed by ChrisLoer** 2017-09-21 19:29 UTC
