### ISSUE TITLE
multiple points with exactly the same location

### ISSUE THREAD

**Issue by EgbertBleyenburg** [mapbox/mapbox-gl-js#7607] opened 2018-11-21 16:22 UTC
**mapbox-gl-js version**:
https://api.mapbox.com/mapbox-gl-js/v0.42.0/mapbox-gl.js

### Question
I load a geojson into a map and display all points with symbols, but a lot of points have the exact same geolocation. So then my cluster shows f.i. 10 points, but zooming in it only shows one symbol (marker)

Ive added two cluster layers 

 map.addLayer({
    	                id: 'clusters',
    	                type: 'circle',
    	                source: 'airports',
    	                paint: {
	                    'circle-opacity': 0.4,
	                 //   'circle-blur': 0.3,
    	                    'circle-color': {
    	                        property: 'point_count',
    	                        type: 'interval',
    	                        stops: [
    	                            [1, '#111111'],
    	                            [3, '#111111'],
    	                            [5, '#111111'],
    	                        ]
    	                    },
    	                    'circle-radius': {
    	                        property: 'point_count',
    	                        type: 'interval',
    	                        stops: [
    	                            [1, 17],
    	                            [3, 17],
    	                            [5, 17]
    	                        ]
    	                    }
    	                }
    	            });

  map.addLayer({
    	                id: 'cluster-count',
    	                type: 'symbol',
    	                source: 'airports',
    	                filter: ['has', 'point_count'],
    	                layout: {
    	                    'text-field': '{point_count}',
   	                    'text-font': ["Bariol Bold", "Arial Unicode MS Bold"],
    	                    'text-size': 14,
    	                    'text-offset': [0, 0.2],
    	                },
    	                paint: {
    	                    "text-color": "#ffffff"
    	                }
    	            });

and a 'marker' layer

    	            map.addLayer({
    	                id: 'airport',
    	                type: 'symbol',
    	                source: 'airports',
    	                filter: ['!has', 'point_count'],
    	                layout: {
    	                   	'icon-image': loadthemarker,
    	                    'icon-size': 1,
    	                    'icon-allow-overlap': true,
    	                    'text-allow-overlap': false,
    	                    'text-field': "{name}",
   	                    'text-font': ["Bariol Bold", "Arial Unicode MS Bold"],
    	                    'text-size': 11,
    	                    'text-offset': [0, 1.8],
    	                    'text-anchor': "top"
    	                }
    	            });

How to show the multiple points (symbols) that have the same location

**Comment by mourner** [comment] 2018-11-21 18:16
- You didn't provide us with a link to a minimal reproducible test case.
- This is a pretty old version of GL JS.

So unfortunately I'll have to close the issue.

**Closed by mourner** 2018-11-21 18:16 UTC

**Comment by vyankat70war** [comment] 2019-02-22 08:59
@mourner I am able to reproduce the mentioned issue with mapbox-gl v0.53. i have attacked geojson which i want to plot on map.  At max zoom level only single icon is visible.

`cluster = supercluster({
			radius: 10,
            maxZoom: 19,
            minZoom: 15
        });`
Please help

[geojson.txt](https://github.com/mapbox/mapbox-gl-js/files/2893117/geojson.txt)

**Comment by abozhang** [comment] 2019-04-10 13:00
I got the same issue.

**Comment by Bernoulli-IT** [comment] 2020-10-13 12:41
But this is by design. Clustering only has its functionality if points differ in location and when zooming out nearby points are clustered into one. Zooming in will show the individual points. But clustering points laying exactly "on top of each other" has no meaning.
