### ISSUE TITLE
Map shoots big distance when panning a small one

### ISSUE THREAD

**Issue by wvffle** [mapbox/mapbox-gl-js#9744] opened 2020-05-30 11:51 UTC
**mapbox-gl-js version**: 1.10.1
 
**browser**: Firefox 76.0 (64-bit)

### Steps to Trigger Behavior

 1. Set up any map or go to [example in docs](https://docs.mapbox.com/help/tutorials/markers/#add-markers-in-mapbox-gl-js)
 2. Pan the map a short distance

### Link to Demonstration

https://streamable.com/rb1a78

### Expected Behavior
A small pan movement

### Actual Behavior
The map shoots a great distance making the map unusable in production

**Comment by mourner** [comment] 2020-06-01 15:58
I can't seem to reproduce this on Firefox 76, so perhaps this is specific to some other aspects of your environment — can add more details like operating system and what kind of input you use (e.g. mouse, trackpad, etc.), and whether this is reproducible in other browsers or on a different machine with the same browser/OS?

**Comment by wvffle** [comment] 2020-06-01 19:08
Same thing happens whether I use mouse or touchpad. 

Seems that it works well in chromium browser as well as on another machine. The main difference between the machines is that I use XFCE and hardened kernel and my friend uses KDE but both on X11.

Tomorrow I can test if the bug is still available on Wayland. I'm prettu sure it'll work there.

**Comment by wvffle** [comment] 2020-06-01 19:08
i use arch btw.

**Comment by mourner** [comment] 2020-08-06 10:34
Looks like this is an OS-level bug that we have no way of reproducing and addressing on the GL JS side, so closing for now.

**Closed by mourner** 2020-08-06 10:34 UTC
Labels: needs information :pray:
