### ISSUE TITLE
Return "in" operator to filter expressions

### ISSUE THREAD

**Issue by rouen-sk** [mapbox/mapbox-gl-js#7077] opened 2018-08-03 12:09 UTC
In the old deprecated filter syntax, there is very useful operator `in`, which can be easily used to test property value against number of possible values. It does not work with expressions, so I guess my only option is to use combination or `any` and `==` (and possibly `number`). 
So this clear statement:
`[ "in", "country", "BGR", "BIH", "GBR", "ROU", "SVN" ]`
become this:
`[ "any",["==", ["get", "country"], "BGR"], ["==", ["get", "country"], "BIH"], ["==", ["get", "country"], "GBR"], ["==", ["get", "country"], "ROU"], ["==", ["get", "country"], "SVN"]]`
(or even worse with numbers). 
Is there any good reason not to have `in` operator in expressions syntax? I believe it can maybe even provide better performance (since JS have functions to test for elements in arrays)

**Comment by anandthakker** [comment] 2018-08-03 13:21
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/4698

**Closed by anandthakker** 2018-08-03 13:21 UTC
