### ISSUE TITLE
error with api.mapbox.cn that Source layer "china_island" does not exist on source "composite" as specified b

### ISSUE THREAD

**Issue by q869939686** [mapbox/mapbox-gl-js#7137] opened 2018-08-16 09:39 UTC
**mapbox-gl-js version**:

**browser**:

### Steps to Trigger Behavior

![image](https://user-images.githubusercontent.com/29123332/44201213-4ece6a80-a17b-11e8-9d14-8fe0572fdb31.png)

**Comment by jfirebaugh** [comment] 2018-08-16 14:07
Duplicate of #6760.

**Closed by jfirebaugh** 2018-08-16 14:07 UTC

**Comment by q869939686** [comment] 2018-08-16 14:17
So no solution for this error now?
