### ISSUE TITLE
use projected angle for determining whether to use vertical writing

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#4951] opened 2017-07-06 19:47 UTC
from https://github.com/mapbox/mapbox-gl-native/pull/9009#discussion_r125731077

[We currently use the angle of the untilted line when determining whether to use vertical text.](https://github.com/mapbox/mapbox-gl-js/blob/4fa52b9e3a0732c9a63f7d4221661a300c15c98f/src/data/bucket/symbol_bucket.js#L774-L776) This can result in the wrong writing mode being used for labels near the edge of the viewport where their angle is affected by the perspective transformation. We should probably do something similar to https://github.com/mapbox/mapbox-gl-js/pull/4853 instead.

@ChrisLoer

**Comment by ChrisLoer** [comment] 2017-07-06 19:58
Duplicate of #4897.

**Closed by ChrisLoer** 2017-07-06 19:58 UTC
