### ISSUE TITLE
Line dashes stretch as map.getZoom()%1 goes from 0 -> 0.99

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#2351] opened 2016-03-28 20:26 UTC
**mapbox-gl-js version**: 0.16.0

### Steps to Trigger Behavior

https://jsfiddle.net/s6nve0sr/ Essentially, add dash-array to paint property.

### Expected Behavior

Dashes and gaps should stay the specified distance at all zoom levels, not just integer level zooms.

### Actual Behavior

Dashes appear correct at `zoom%1 ===0` but are twice as long at `zoom%1 === 0.99`

**Comment by mourner** [comment] 2016-03-28 20:33
Isn't this the expected behavior? We can't have constant distance, because line length changes as you zoom in and the dash will start moving along the line with a very unpleasant flashing effect. It used to be like this but was fixed by @ansis.

**Comment by ansis** [comment] 2016-03-28 20:52
Yep, if they stay the same length they look like they are sliding along the line.

An alternative would be to scale/stretch dashes while zooming but then transition to exact sizes afterwards. So far we've tried to avoid these kinds of transitions. I think this could look weird in some cases too because it's impossible to perfectly predict when someone has stopped zooming.

There's always going to be something that doesn't look right with dashed lines and patterns. We just need to pick the one that is the least bad.

**Comment by peterqliu** [comment] 2016-03-28 21:06
>it's impossible to perfectly predict when someone has stopped zooming

@ansis say more? seems like `zoomend` would be the relevant event, and "stretch until the zooming is done, then transition to exact size" sounds like a decent solution.

**Comment by ansis** [comment] 2016-03-28 21:15
After a zoomend we could either:
- switch instantly to the correct size and have a potentially jarring shift
- transition to the correct size. But what happens when you are in the middle of this transition and start zooming again? We'd need to either abruptly skip to the end of the transition or somehow delay the scaling.

It might be worth experimenting with this. It's hard to know how this would look without trying.
It's hard to know how this would look without trying.

I'm wondering whether dotted lines could be better accomplished with a symbol layer and `-allow-overlap: true`.

**Comment by jfirebaugh** [comment] 2016-03-28 21:25
Let's hit pause here please. The current behavior is already the result of several iterations and refinements, and we have much more pressing issues to attend to.

**Closed by jfirebaugh** 2016-03-28 21:25 UTC
