### ISSUE TITLE
could line-dasharray support Function

### ISSUE THREAD

**Issue by wxqqq** [mapbox/mapbox-gl-js#6053] opened 2018-01-25 03:51 UTC
i want to add a line layer with different  line-dash style.
but the line-dasharray didn't support property functions.

it means i have to  add mulitylayer to show the effect. 

could fix it ?

**Comment by lbud** [comment] 2018-01-25 04:03
Closing as duplicate of https://github.com/mapbox/mapbox-gl-js/issues/3045 — we haven't implemented this yet for technical reasons; see ticket for details.

**Closed by lbud** 2018-01-25 04:03 UTC
