### ISSUE TITLE
mapbox.langtat() is giving wrong output on correct parameter order (long,lat) and vice versa

### ISSUE THREAD

**Issue by knightMash** [mapbox/mapbox-gl-js#9698] opened 2020-05-17 15:17 UTC
Using mapbox-gl-js-v1.8.1.
I have this function for calculating the angle between two cordinates for short distances as follows:

```
function fn(startLat, startLng, destLat, destLng){
  const y = destLat - startLat;
  const x = destLng - startLng;
  return toDegrees(Math.atan2(y, x));

}
```

I then wanted to calculate the new coordinates based on the angle,distance and first coordinate as done in following code :

```
function findpos(){
    var ptt = new mapboxgl.LngLat(latitude,longitude);
    var ptt2 = destinationPoint(179.85, 0.226, ptt);
    return ptt2;
}

function destinationPoint(brng, dist, pointA) {
   dist = dist / 6378.1;
   brng = brng.toRad();

   var lat1 = pointA.lat.toRad(), lon1 = pointA.lng.toRad();

   var lat2 = Math.asin(Math.sin(lat1) * Math.cos(dist) +
                        Math.cos(lat1) * Math.sin(dist) * Math.cos(brng));

   var lon2 = lon1 + Math.atan2(Math.sin(brng) * Math.sin(dist) *
                                Math.cos(lat1),
                                Math.cos(dist) - Math.sin(lat1) *
                                Math.sin(lat2));

   if (isNaN(lat2) || isNaN(lon2)) return null;
   console.log("des ",lon2,lat2);
   return new mapboxgl.LngLat(lat2.toDeg(),lon2.toDeg());
}
```

So my problem is the following. By using the first `fn` funstion above I have two cordinates that I know fall on 179 degrees to one another at a distance of 200mt from each other.

Now On taking one of the two cordinates (the first one on whose 179 degrees falls the second coordinate), 179 degree as the angle,and 200mt as the distance when I use the above two functions namely `findpos()` and `destinationPoint()` I get the correct result of second cordinate when i use `new mapboxgl.LngLat(lat2.toDeg(),lon2.toDeg());` and `var ptt = new mapboxgl.LngLat(latitude,longitude);` that is the lattitude as first argument and longitude as the second argument in the mapbox.Lnglat() function, but I as I I have read in the documentation that the correct order of parameters is longitude and latitudes.So on using longitude as first parameter and latitude as second parameter I get the wrong value of the second coordinate.

I am unable to understand this behaiviour. Can someone please help me out here please?

The coordinates that you can use to verify this are as follows:

```
latitude = startLat =  28.7054826 
longitude = startLng = 77.122322
destLat =  28.7153689
destLng =  77.1067706
```

so {destLng , destLat} is at 179degrees and 200 mt away from {latitude, longitude}. Rest is as explained above.

**Comment by andrewharvey** [comment] 2020-05-18 01:22
>  new mapboxgl.LngLat(latitude,longitude);

LngLat takes arguments in the order (longitude, latitude)

**Comment by knightMash** [comment] 2020-05-18 04:30
I have read that and That is the whole problem. When using LngLat(longitude,latitude) the result I am getting is incorrect.but on reversing the order of parameters the answer is correct.Which should not happen.

**Comment by andrewharvey** [comment] 2020-05-18 04:44
Could you provide a minimal reproducible example of the issue?

**Comment by knightMash** [comment] 2020-05-18 07:12
[Here](https://codepen.io/MusketeerHo/pen/LYpJJKL) it is. I have put the logs in accordance to the logs above.
First i have used `fn()` to shaw that the first latlong is at 179 deg from second latlong.

Then I have called `findpos()` with wrong order of latlong in the parameter list which is giving the set of latlong which on putting back in `fn()` confirms the 179 degrees angle between them.

But as soon as you will change the order of lnglat() function's parameters in both `findpos()` and  `destinationPoint()` you will get a set of langlat which will not agree with the results of `fn()` function called before `findpos()`.

Kindly have a look.

**Comment by andrewharvey** [comment] 2020-05-18 07:18
I'll re-open so someone else can decide on this ticket, but an even more minimal example would make it easier to debug. It's still much more likely there is a bug in your code somewhere.

**Comment by knightMash** [comment] 2020-05-18 07:27
okay, I have removed the part containing three.js now from the codepen link .

**Comment by mourner** [comment] 2020-05-25 08:20
Unfortunately our team doesn't have capacity to debug generic JavaScript/math problems. Since so far there's no indication that this is a GL JS issue, I'm going close it for now.

**Closed by mourner** 2020-05-25 08:20 UTC

**Comment by knightMash** [comment] 2020-05-27 16:08
@mourner how did you reach the conclusion that this is a Javascript/math problem. I have clearly  stated that the problem is with parameter's order.

**Comment by mourner** [comment] 2020-05-27 16:17
@knightMash `mapboxgl.LngLat` expects the order of the arguments to be `longitude, latitude`, and then exposes the given values as `lnglat.lng` and `lnglat.lat`. That's all GL JS does in relation to the code above, and and it does so as designed. You can replace `new mapboxgl.LngLat(longitude, latitude)` with `{lng: longitude, lat: latitude}` and the result will be the same. The rest is your own code. If you get a correct result by swapping coordinate order, perhaps that order is mixed up somewhere in that code.
