### ISSUE TITLE
Draggable symbol flickers when dragging

### ISSUE THREAD

**Issue by tubatoothpaste** [mapbox/mapbox-gl-js#5819] opened 2017-12-06 18:55 UTC
When I copy the example for a draggable circle from the mapbox-gl examples ([seen here](https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/)) and replace it with a symbol, the symbol flickers when dragging in 0.42.2. 

It seems to work fine in 0.41.0 however.

v0.42.2 
[https://jsbin.com/quvoduj/edit?html,output](https://jsbin.com/quvoduj/edit?html,output)

v0.41.0
[https://jsbin.com/hoxukav/edit?html,output](https://jsbin.com/hoxukav/edit?html,output)

Using a Macbook Pro OS 10.13.1
Latest versions of Chrome, Safari and Firefox

**Comment by jfirebaugh** [comment] 2017-12-06 21:12
Duplicate of #5716.

**Closed by jfirebaugh** 2017-12-06 21:12 UTC
