### ISSUE TITLE
Zooming past anti meridian, the map jumps somewhere else

### ISSUE THREAD

**Issue by metdockal** [mapbox/mapbox-gl-js#11866] opened 2022-05-09 07:54 UTC
**mapbox-gl-js version**: 2.8.0 and later

**browser**: 101.0.4951.41 Chrome

### Steps to Trigger Behavior
 1. Initialize map at `center: [175, -40],  zoom: 1`
 2. Zoom to Chatham Island (East of NZ)
 3. Maps jumps somewhere to south America

### Link to Demonstration

https://jsbin.com/yunawos/edit?html,output

### Expected Behavior

The map zooms into the location where the cursor is

### Actual Behavior

The map jumps 180 deg East
![CPT2205090952-932x913](https://user-images.githubusercontent.com/49377387/167365119-de41ba2c-1ec0-4941-acd9-a95fb6afe6de.gif)

**Comment by avpeery** [comment] 2022-05-12 20:38
Hi @metdockal I'm unable to reproduce this issue with the jsbin you've provided. To clarify are you only seeing this issue in 2.8.0, or also in previous or later gl-js versions? I also wonder if it's environment specific - Are you seeing this issue when using a trackpack or mouse or both? Thanks for reporting!

**Comment by avpeery** [comment] 2022-05-19 16:21
Hi @metdockal I'm going to close this issue as it is a duplicate of #11910. Thanks!

**Closed by avpeery** 2022-05-19 16:21 UTC
Labels: needs information :pray:

**Comment by metdockal** [comment] 2022-05-19 18:39
Hello @avpeery. Thank you 🙏
