### ISSUE TITLE
The line-blur configuration blur effect produces an acute angle problem at the inflection point

### ISSUE THREAD

**Issue by liulianfan** [mapbox/mapbox-gl-js#10512] opened 2021-03-26 08:38 UTC
**mapbox-gl-js version**:
v2.1.1
**browser**:
chrome
### Steps to Trigger Behavior

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>map</title>
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" rel="stylesheet" />
    <style>
        body {
            margin: 0;
            padding: 0;
        }

        #map {
            position: absolute;
            top: 0;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>

<body>

    <div id="map"></div>

    <script>
        mapboxgl.accessToken = "*"
        const map = new mapboxgl.Map({
            container: 'map',
            zoom: 9,
            antialias: true,
            center: [121.613846, 31.205494],
            style: 'mapbox://styles/mapbox/streets-v11'
        });

        map.on('load', ()=> {
            map.addLayer({
                id: 'test',
                type: 'line',
                source: {
                    type: "geojson",
                    data: {
                        "type": "FeatureCollection",
                        "features": [{
                            "type": "Feature",
                            "properties": {},
                            "geometry": {
                                "type": "LineString",
                                "coordinates": [
                                    [
                                        121.497802734375,
                                        31.23687574659226
                                    ],
                                    [
                                        121.51153564453125,
                                        31.22748163198711
                                    ],
                                    [
                                        121.50947570800781,
                                        31.20692875060323
                                    ],
                                    [
                                        121.49848937988281,
                                        31.18930843952816
                                    ],
                                    [
                                        121.48544311523436,
                                        31.185196561475053
                                    ],
                                    [
                                        121.47583007812501,
                                        31.18343427334403
                                    ],
                                    [
                                        121.46690368652344,
                                        31.17755974264551
                                    ],
                                    [
                                        121.4710235595703,
                                        31.16110911780645
                                    ],
                                    [
                                        121.46553039550781,
                                        31.1481816228079
                                    ],
                                    [
                                        121.46072387695314,
                                        31.141717214115644
                                    ],
                                    [
                                        121.47033691406249,
                                        31.134076890184236
                                    ],
                                    [
                                        121.49436950683594,
                                        31.131725897455333
                                    ],
                                    [
                                        121.56921386718751,
                                        31.143480278378625
                                    ],
                                    [
                                        121.64611816406249,
                                        31.15464559072225
                                    ],
                                    [
                                        121.75804138183594,
                                        31.18637140200282
                                    ],
                                    [
                                        121.72096252441405,
                                        31.243920719573723
                                    ],
                                    [
                                        121.67633056640624,
                                        31.3037817668869
                                    ],
                                    [
                                        121.64268493652342,
                                        31.305541810759557
                                    ],
                                    [
                                        121.56509399414061,
                                        31.303195078289708
                                    ],
                                    [
                                        121.56852722167967,
                                        31.287939892641734
                                    ],
                                    [
                                        121.56990051269533,
                                        31.26563941133798
                                    ],
                                    [
                                        121.54998779296874,
                                        31.255661173443542
                                    ],
                                    [
                                        121.53144836425781,
                                        31.24626892713094
                                    ],
                                    [
                                        121.51634216308594,
                                        31.244507776936892
                                    ],
                                    [
                                        121.50672912597658,
                                        31.24333365856142
                                    ]
                                ]
                            }
                        }]
                    }
                },
                paint: {
                    // "line-cap": "round",
                    // "line-join": "round",
                    "line-blur": 20,
                    "line-width": 40,
                    "line-color": "#FF0000",
                },

            });
        });
    </script>

</body>

</html>
### Expected Behavior
I want to configure this similar effect to add gradient color to the border

![image](https://user-images.githubusercontent.com/20163701/112604881-a3691480-8e51-11eb-92bc-6219b87205dd.png)

### Actual Behavior
I found that the sharp corners at the inflection points are very prominent, and the effect is only good on smooth lines.
![image](https://user-images.githubusercontent.com/20163701/112604142-ccd57080-8e50-11eb-9813-a13607a3b81b.png)

**Comment by rreusser** [comment] 2021-03-26 17:20
Thanks for the report and the clear example, @liulianfan! If it's alright, I'll close this as a duplicate of #10000, which presents a workaround via zoom-dependent styles though not yet a fix.

**Closed by rreusser** 2021-03-26 17:20 UTC
