### ISSUE TITLE
Heatmap with a large number of small clusters "flickers" when the map position is changed 

### ISSUE THREAD

**Issue by moneyatbo** [mapbox/mapbox-gl-js#9952] opened 2020-08-25 15:05 UTC
**mapbox-gl-js version**: 1.12.0

**browser**:  Chrome 84.0.4147.135 (Official Build) (64-bit) (Mac, Linux, Windows)
                      Edge 84.0.522.63 (Official build) (64-bit)
                      IE 11.450
                      Safari Version 13.1.2 (15609.3.5.1.3)
### Steps to Trigger Behavior

 1. Load page in the jsbin
 2. see the heatmap rendered over San Francisco
 3. with your mouse click and hold on the map
 4. now move the mouse to the left, right, up or down
 5. Notice that the heatmap does not render in the same locations as you pan. 

### Link to Demonstration

https://jsbin.com/zodewehiwa/edit?html,output

![flicker](https://user-images.githubusercontent.com/48034828/91190583-bcde8e00-e6c1-11ea-9eb5-f942ab7c591d.gif)

### Expected Behavior
Consistent position of the heatmap clusters when panning over the map 

### Actual Behavior
Heatmap clusters migrate on the map as you pan. 

I converted the Data Driven Circles example to be a heatmap to illustrate the problem we are seeing on our maps. https://docs.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/

**Comment by mourner** [comment] 2020-08-25 15:59
Yeah, duplicate of #5563. Heatmaps are rendered through a 16x downscaled framebuffer for performance, which probably causes the flickering due to lost information, but there may be a way to fix this without compromising performance — needs investigation.

**Closed by mourner** 2020-08-25 15:59 UTC
Labels: bug :beetle:

**Comment by moneyatbo** [comment] 2020-08-25 16:15
@mourner How easy is it to adjust the framebuffer if we forked the lib?

**Comment by mourner** [comment] 2020-08-25 16:16
@moneyatbo I don't know. But if you do find a fix, we'll welcome a pull request!
