### ISSUE TITLE
when zooming out, map flashes blank

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#1570] opened 2015-09-28 20:46 UTC
This doesn't happen when zooming in, only when zooming out:

![2015-09-28 16_47_18](https://cloud.githubusercontent.com/assets/108094/10148256/6f735ae8-6600-11e5-9b25-e2d206e2df5f.gif)

Might be the same as https://github.com/mapbox/mapbox-gl-js/issues/934

**Comment by lucaswoj** [comment] 2015-09-28 21:46
I'm guessing this is, at least partly, because we're waiting for the vector tile data for higher zoom levels to load. It would be great to prefetch all tiles needed to zoom from wherever you are to z0.

**Comment by samanpwbb** [comment] 2015-09-29 15:26
@lucaswoj i am sure I had already loaded these tiles. I zoomed in and then zoomed back out.

**Comment by lucaswoj** [comment] 2015-09-29 17:24
Interesting. This is very relevant to what I'm doing in #1526. I'll try to some time instrumenting GL JS to discern where the bottlenecks are.

**Comment by lucaswoj** [comment] 2015-10-01 19:52
The "flash" occurs because it takes time to load vector tiles, parse vector tiles, turn them into buffers, and render them. We're working on making this faster, see #1579 #1560 #1573. We're also thinking about how to reduce the _perceived_ loading time and use prefetching in #934. 

I'm going to close this issue because I'm not sure what's actionable here -- there are lots of different things we can do and we are doing many of them.

**Comment by mourner** [comment] 2015-10-01 20:09
Can we just retain the already rendered tiles no matter how far we zoomed out? This would improve the perceived performance because nothing would flash, just become tiny as we zoom out. No need to do any more collision detection etc. beyond what we already do, just do not prune tiles on zoom out. cc @jfirebaugh

**Comment by jfirebaugh** [comment] 2015-10-01 20:13
We currently ptry to use parent tiles up to 10 zoom levels up](https://github.com/mapbox/mapbox-gl-js/blob/1ccca83630a545730c37f94029cd10c6c1cfcb00/js/source/tile_pyramid.js#L198). We could try increasing that and seeing if the problem goes away, or if the cause is something else.

**Comment by mourner** [comment] 2015-10-01 20:19
@jfirebaugh the gif above shows it's definitely triggered with less than 10 zooms out. So it might be some kind of a bug.

**Comment by mourner** [comment] 2015-10-07 13:48
@jfirebaugh found out that this is actually about retaining children, which we do only [up to 1 zoom level up](https://github.com/mapbox/mapbox-gl-js/blob/1ccca83630a545730c37f94029cd10c6c1cfcb00/js/source/tile_pyramid.js#L199). To fix this issue, I suggest bumping this to +2 or +3. It makes the issue much less noticeable. We can't afford bumping this too much because zoom out performance suffers, but +2 or +3 seems OK.

**Comment by bhousel** [comment] 2015-10-07 15:47
Related, but while profiling today I realized that `removeTile` (and whatever event cascade it kicks off) is causing significant slowdowns on the main thread.  We should really find a way to mark tiles for lazy removal.

![screenshot 2015-10-07 11 45 07](https://cloud.githubusercontent.com/assets/38784/10342850/10bff6ce-6ce9-11e5-9032-69bcb9bd4949.png)

**Comment by mourner** [comment] 2015-10-07 16:30
@bhousel interesting, how do you trigger this? Can't find anything like this in my timeline results.

**Comment by jfirebaugh** [comment] 2015-10-07 18:03
@mourner Good point, I had it backwards.

We could probably retain to an infinite descendant depth if we had the right datastructure. Right now we have to do O(n^4) checks to see if any descendant tiles exist at depth _n_. If we had a datastructure that actually tracked tile parent-child relationships, this would probably be linear or constant time instead.

**Comment by mourner** [comment] 2015-10-07 18:28
@jfirebaugh I think there's no need for a different data structure — could we just iterate over `this._tiles` instead of `coord.children(this.maxzoom)`? The number of loaded tiles at any given time is usually pretty low.

**Comment by jfirebaugh** [comment] 2015-10-07 18:35
I thought about that, but wouldn't it still be quadratic? For each tile, check if any of the other tiles are descendants?

**Comment by mourner** [comment] 2015-10-07 18:39
@jfirebaugh yes, but quadratic is at least much better than O(n * 4^z), and not dependent on depth.

**Comment by bhousel** [comment] 2015-10-07 18:47
@mourner:
> interesting, how do you trigger this? Can't find anything like this in my timeline results.

Nothing special, maybe just 5 seconds of panning and rotating DC at z12 and watching for where the bars show poor fps.

@jfirebaugh:
TilePyramid really should just have a proper quadtree under the hood.. This is what you mean?

**Comment by lyzidiamond** [comment] 2015-10-12 19:28
tagging @mapbox/support for known issue

**Closed** 2015-10-15 18:19 UTC
Labels: bug, in progress
