### ISSUE TITLE
GeoJSON features identifier and structured properties are losts

### ISSUE THREAD

**Issue by noirbizarre** [mapbox/mapbox-gl-js#7464] opened 2018-10-22 15:59 UTC
**mapbox-gl-js version**: 0.50.0

**browser**: Any

### Steps to Trigger Behavior

 1. Load any GeoJSON with string `id` on features and `Array` or `Object` as properties
 2. Catch any mouse event with a `features` property or use any `query*Features` helper
 3. Look at the missing `id` and the stringified `properties` on features

### Link to Demonstration

https://jsfiddle.net/dcwp7xu4/1/

### Expected Behavior

The feature string `id` is present on the feature object and `properties` are restitued as provided (same type, same content) by the source GeoJSON (and as [specified in the GeoJSON specifications](http://geojson.org/geojson-spec.html#feature-objects))

### Actual Behavior
- String identifier (`id`) is missing on the features
- Arrays and objects are stringified

### Related issues

It seems to be a recurring issue on different levels:
- #2434
- #7194
- #4380
- #2716
- #3210
- ...

Most of them didn't had advancement for months or years.
There is even a merged pull request hardening this behavior #7106 (String identifier is a really common use case so why force number ID instead of ensuring string are properly handled)

**Comment by ChrisLoer** [comment] 2018-10-22 21:45
Hi @noirbizarre, thanks for the report. This is definitely an issue we want to work on, but I don't understand if there's something new you're reporting here? This looks like a duplicate of #2434 and #2716. Feel free to re-open if I've missed something.

**Closed by ChrisLoer** 2018-10-22 21:45 UTC
