### ISSUE TITLE
CORS error when trying to load 3D terrain

### ISSUE THREAD

**Issue by gtnbssn** [mapbox/mapbox-gl-js#11270] opened 2021-11-11 11:24 UTC
Trying to add 3D terrain, i am looking at a page i created last week and which was working, but now I am getting CORS errors.

To reproduce, simply click on the "edit in JSFiddle" button on https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/ and open the console.

This could be similar to this: https://github.com/mapbox/mapbox-gl-js/issues/10421

(I note that the sky also looks a lot more plain on JSFiddle so it's not just the 3D terrain that isn't loading.)

**Comment by gtnbssn** [comment] 2021-11-11 11:28
Ok i solved my error: my adblocker uBlock origin is blocking events.mapbox.com.

I am leaving this open for the mapbox team to decide whether this is a bug or not. But as it stands, it looks like people using ad blockers might not be able to see 3D terrains on our maps.

**Comment by mourner** [comment] 2021-11-11 12:33
@gtnbssn I also use uBlock Origin and `events.mapbox.com/*` requests get blocked, but it should not affect terrain rendering since these are just telemetry events for user stats — I see terrain both in the example and in a derived JSFiddle. Can you share more details — e.g. a screenshot, browser details, etc.?

**Comment by gtnbssn** [comment] 2021-11-11 14:33
I'm seeing this with Firefox 94.0, uBlock origin 1.38.6.

The JSFiddle loads properly if i disable uBlock origin.

![image](https://user-images.githubusercontent.com/10359074/141313123-414798fa-f630-4467-b385-1e981442185e.png)

In Chromium 95 with uBlock origin 1.38.6, i also get errors, but different ones.

It also works if i disable uBlock origin.

![image](https://user-images.githubusercontent.com/10359074/141313691-787290d7-2775-4dbe-8118-408eced052b1.png)

**Comment by ryanhamley** [comment] 2021-11-16 01:17
I get the same CORS errors with the same Chrome and uBlock versions. I'm not sure off-hand why uBlock is interfering in this way, but it definitely is the cause.

**Comment by ryanhamley** [comment] 2021-11-19 19:50
I'm going to close this since it seems like the issue is uBlock

**Closed by ryanhamley** 2021-11-19 19:50 UTC
Labels: needs information :pray:
