### ISSUE TITLE
Can't zoom out enough to show full earth in a small window

### ISSUE THREAD

**Issue by jpilet** [mapbox/mapbox-gl-js#7804] opened 2019-01-23 16:02 UTC
## Motivation

I want to show a map of the earth in a relatively small window, let's say 400x400.
However, negative zoom are not supported, so at the minimum zoom 0, the world is not completely visible (because tileSize  is larger than 400).

To reproduce:
- navigate to https://docs.mapbox.com/mapbox-gl-js/example/simple-map/
- resize your window so that it becomes thin
- try to zoom out as much as possible
- you can't see all the world

## Design Alternatives

Option 1: do not support zooming out beyond level 0.

Option 2: support negative zooms.

Option 3: add an API to change tileSize

## Design

# For the negative zoom:
A zoom of -1 would mean: show zoom level 0 at half its size.

For the API consumer, there's no significant change.

For designers, they would have to deal with the current implicit minZoom: 0 for all layers.

# Changing tileSize

instead of dealing with negative zoom, the user could divide tileSize by 2, thus resulting in a much denser map. This option would give the user some control over the density of displayed information, too.

### Concepts

How will we teach negative zooms ?
By explaining that level -1 corresponds to a world map rendered at half the size of similar map of level 0.

### Implementation

For negative zooms:
The code would not be very hard to write. Remove assert(z >= 0), and make sure all the math makes sense.

**Comment by andrewharvey** [comment] 2019-01-24 04:53
hey @jpilet I'll go ahead and close this issue as a duplicate of #3055 to avoid fragmentation. Please add your comments to #3055.

**Closed by andrewharvey** 2019-01-24 04:53 UTC
