### ISSUE TITLE
MapTiles stuttering while changing center via flyTo()

### ISSUE THREAD

**Issue by haeckmaenn** [mapbox/mapbox-gl-js#6709] opened 2018-05-22 12:28 UTC
Hi,
for a small indoor navigation project we are using raster tiles. When using MapboxGL Version 45.0 we have the problem that tiles are stuttering/shaking when we are changing maps' center via flyTo(). Version 43.0 works fine. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12595969/40362234-35d3e26e-5dcc-11e8-9728-da43281ee993.gif)

**mapbox-gl-js version**: 45

**browser**: Safari, Chrome

**Comment by jfirebaugh** [comment] 2018-05-23 19:15
Duplicate of #6150.

**Closed by jfirebaugh** 2018-05-23 19:15 UTC
