### ISSUE TITLE
Labels Not Rendering Consistently in Safari

### ISSUE THREAD

**Issue by caneroj1** [mapbox/mapbox-gl-js#4722] opened 2017-05-19 03:20 UTC
**mapbox-gl-js version**: 3.0.1

### Steps to Trigger Behavior

 1. Use mapbox-gl-js to render a map.
 2. Open that map in safari (Version 10.1)
 2. See that labels on the map do not appear, or disappear when sometimes when refreshing the page

### Expected Behavior
I would expect what I see in Safari to match this image from Chrome:
<img width="1050" alt="screen shot 2017-05-18 at 11 15 25 pm" src="https://cloud.githubusercontent.com/assets/3110602/26231919/5bb740a8-3c20-11e7-8ae7-d42ecd148305.png">

### Actual Behavior
This is what Safari renders:
<img width="1278" alt="screen shot 2017-05-18 at 11 15 58 pm" src="https://cloud.githubusercontent.com/assets/3110602/26231924/63285a98-3c20-11e7-9e7e-ad45022607b4.png">

There aren't any console errors at all. All requests to the server are coming back with successful responses, and it doesn't _look_ like there are any issues on that end. Is Safari just not supported or something?

**Comment by jaapster** [comment] 2017-05-19 07:00
Is this a duplicate of #4607?

**Comment by mourner** [comment] 2017-05-19 12:35
Yes, duplicate of #4607. Check out if https://github.com/mapbox/mapbox-gl-js/pull/4688 fixes your problem.

**Closed by mourner** 2017-05-19 12:35 UTC

**Comment by caneroj1** [comment] 2017-05-19 12:47
Yes, looks to be a duplicate. I'll check out the linked issues. Thanks!
