### ISSUE TITLE
Labels Not On Top of Streets

### ISSUE THREAD

**Issue by hallahan** [mapbox/mapbox-gl-js#1360] opened 2015-07-06 15:59 UTC
I'm noticing that the label for Roseville, CA is not on top of some residential streets.

This is at zoom 12 an above.

<img width="565" alt="screenshot 2015-07-06 08 52 35" src="https://cloud.githubusercontent.com/assets/556367/8526712/1f8b0f88-23bd-11e5-8f7e-5cfb2d573632.png">

Using: https://www.mapbox.com/mapbox-gl-styles/styles/outdoors-v7.json

**Comment by mourner** [comment] 2015-07-06 16:01
Duplicate of #757

**Closed by mourner** 2015-07-06 16:01 UTC
