### ISSUE TITLE
Fix bug preventing map interactions near two controls in the same corner

### ISSUE THREAD

**Issue by yunluyl** [mapbox/mapbox-gl-js#2924] opened 2016-07-31 21:20 UTC
The navigation controller layer is above the map, which stops the mouse event going to the map layer.

Here is the JSFiddle. You can try hovering your mouse at the bottom right corner of the map.

https://jsfiddle.net/6wrqz1ru/

**Comment by mollymerp** [comment] 2016-08-01 05:22
Hi @yunluyl,

Thank you for reporting your issue. I'm not sure there is a bug is in this case, because when I opened the jsfiddle I did not experience any unexpected behavior. Any DOM element above the GL canvas will usually prevent user interaction with the map. When you have navigation control in the bottom right, it gets put in the same `div` as the map attribution (`.mapboxgl-ctrl-bottom-right`). this causes the div to grow to fit both controls and covers more map area than you might expect. 

<img width="622" alt="screen shot 2016-07-31 at 10 18 47 pm" src="https://cloud.githubusercontent.com/assets/2425307/17284132/d4ee0752-576c-11e6-9e0b-4d1b9585e03a.png">

I suggest putting the navigation control in another corner to avoid this behavior.

<img width="473" alt="screen shot 2016-07-31 at 10 20 48 pm" src="https://cloud.githubusercontent.com/assets/2425307/17284153/12b8321a-576d-11e6-9be4-405fb9e6d6c4.png">

Thanks!
Molly

**Comment by lucaswoj** [comment] 2016-08-01 17:09
We should be able to support multiple controls in the same corner. This is a bug.

**Comment by mourner** [comment] 2016-08-02 15:32
This should be an easy task to tackle — the trick is to update CSS to have `pointer-events: none` on the corner elements but reset to `auto` on its descendants. Here are the [relevant lines from Leaflet](https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css#L106-L117). A PR would be welcome!

**Comment by yunluyl** [comment] 2016-08-02 20:27
PR created

**Comment by mollymerp** [comment] 2016-08-08 21:42
This was fixed in #2932 thank you @yunluyl!

**Closed by mollymerp** 2016-08-08 21:42 UTC
Labels: bug, seeking external contributions, starter task
