### ISSUE TITLE
v1.9.0 add "fill-extrusion-pattern" webgl is not working properly

### ISSUE THREAD

**Issue by nuancheng** [mapbox/mapbox-gl-js#9479] opened 2020-03-30 11:19 UTC
The latest version adds 3D architectural texture, and the webgl is not working properly
V1.8.0 is normal

**mapbox-gl-js version**: v1.9.0

**browser**: Google Chrome  80.0.3987.149

### Steps to Trigger Behavior

 1. v1.9.0 "vector" layer add "fill-extrusion-pattern" img

### Link to Demonstration
`"fill-extrusion-pattern": {
                property: "height",
                type: "interval",
                stops: [[40, "catcat"]]
              },`

wrong：https://jsbin.com/yazutumoxa/edit?html,output
Expectant：https://jsbin.com/yazutumoxa/3/edit?html,output

**Comment by nuancheng** [comment] 2020-03-30 11:22
wrong url：https://jsbin.com/kiyarubuji/edit?html,output

**Comment by mourner** [comment] 2020-03-30 11:44
@karimnaaji might be related to the change in #9372?

**Comment by karimnaaji** [comment] 2020-03-30 23:35
I checked the sanity of #9372 to see if it introduced a regression. There are no regression introduced by this specific PR, though, while looking at that I found another bug, which is in the vertex layout of pattern attributes. 

Explicitly setting [this offset to 0](https://github.com/mapbox/mapbox-gl-js/blob/master/src/data/program_configuration.js#L326) assumes that all vertices within this layout start at the same byte in the vertex format. This is incorrect since [this layout](https://github.com/mapbox/mapbox-gl-js/blob/master/src/data/bucket/pattern_attributes.js) has 4 different components, each of which starts at byte offsets 0, 8, 16 and 17. This may have been silently broken for some time and adding new attributes in this layout did not take effect for DDS.

For this particular issue, @nuancheng , you need to use `addImage` with `{pixelRatio: 2}` option since  you are loading a `@2x` image manually, the difference is that in v1.8.0 we were using the device pixel ratio, which happened to match this 2x on a 2x screen. So this example will actually _accidentally_ works under a 2x screen in v1.8.0. But, on my 1x screen this image pixel ratio is downgraded to a 1x incorrectly in v1.8.0:

![Screen Shot 2020-03-30 at 4 28 46 PM](https://user-images.githubusercontent.com/7061573/77971501-afa0ad00-72a3-11ea-9448-b12746a2fae7.png)
 
Using addImage with `{pixelRatio: 2}` will work as long as you are not using data driven expressions in `fill-extrusion-pattern`; for DDS that's a good thing you brought this issue up, I'll be submitting a PR very soon with a fix and render test coverage around it.

**Comment by nuancheng** [comment] 2020-03-31 02:35
As if we are not talking about the same problem, I mean the error of v1.9.0 shown here
![1585621972664](https://user-images.githubusercontent.com/21274039/77980892-1de47e80-733b-11ea-97aa-35dd677f0050.jpg)
But it only appears on Mac OS. It looks normal on windows
![11230](https://user-images.githubusercontent.com/21274039/77980980-52f0d100-733b-11ea-8ff1-be7a629a4a50.jpg)

**Comment by karimnaaji** [comment] 2020-03-31 18:13
We are talking about the same problem and I understand what you are trying to show, I tried to give you  details so you can follow us there. The path forward would be taken from https://github.com/mapbox/mapbox-gl-js/pull/9482.

Can you give more information on these new screenshots? The code is truncated and I'm wondering whether you used the same as the initial examples as I can't repro the first screenshot; it makes it hard to make any assumption about how it's being used.

**Comment by Plantain** [comment] 2020-03-31 21:48
Possibly related as suggested in #9394 , previously zooming would keep scaling of fill-patterns relatively constant, now it gives visually distorted/broken behaviour, see an example of zooming below with:
  'fill-pattern': ["concat", "bs_", ["to-string",["get", "idx"]]],
where idx varies across a few different patterns (the area shown is one pattern though).
![77984167-52712e00-736d-11ea-927e-e3fb02281290](https://user-images.githubusercontent.com/319895/78078062-fdcdc180-7405-11ea-8820-aef6e9edae2b.png)
![77984162-51400100-736d-11ea-9361-b047e5405bc7](https://user-images.githubusercontent.com/319895/78078065-fefeee80-7405-11ea-9acf-1a362fb8eab0.png)
![77984375-e17e4600-736d-11ea-9830-7acf9352729e](https://user-images.githubusercontent.com/319895/78078068-00301b80-7406-11ea-809d-67bbf958262b.png)
![77984373-dfb48280-736d-11ea-9080-620932ef329c](https://user-images.githubusercontent.com/319895/78078070-00c8b200-7406-11ea-82b7-ff4faea2ae89.png)

**Comment by nuancheng** [comment] 2020-04-01 03:14
https://jsbin.com/dagixugazi/edit?html,output
The problem has been solved in this version. Thank you.


In addition, I want to ask you a question. Now after the building is pasted with texture, the magnified texture of the field of vision will be recalculated. Is there any way to prohibit recalculation?

15 <zoom< 16 :
![image](https://user-images.githubusercontent.com/21274039/78095442-8d28a400-7409-11ea-998f-5fffb1eca401.png)

16< zoom < 17 :
![image](https://user-images.githubusercontent.com/21274039/78095498-b77a6180-7409-11ea-876c-8ea0f232bdb7.png)

The texture effect varies greatly under different zoom, which makes people feel a little strange.

**Comment by karimnaaji** [comment] 2020-04-01 18:05
@Plantain Thanks for the details, using `'fill-pattern': ["concat", "bs_", ["to-string",["get", "idx"]]]` will lead to the same code path and should be fixed by #9482.

@nuancheng I think we will need a better example, using the full atlas of icons was ok to exemplify the issue you initially opened but does not give an appropriate representation for what you are suggesting. Can you open another issue applying a texture that would seamlessly repeat to better express your suggestion?

**Closed by karimnaaji** 2020-04-01 18:05 UTC
Labels: bug :beetle:
