### ISSUE TITLE
How to combine case expression and property in styling line-color?

### ISSUE THREAD

**Issue by kldziwon** [mapbox/mapbox-gl-js#10760] opened 2021-06-10 13:17 UTC
Hi,
I'm stuck with styling `line-color`. I want to achieve something like this below, but I don't know how to get color combining colorId and stops in case expression

```
    'line-color': ['case',
      ['==', ['get', 'isOpen'], true], *use color based on property colorId and stops*, '#878787',
    ],
```

I've tried, but it didn't worked

```
    'line-color': ['case',
  ['==', ['get', 'isOpen'], true], {stops, property: 'colorId'}, '#878787',
],
```

**Comment by karimnaaji** [comment] 2021-06-23 22:59
I believe what you looking for might be [line gradients](https://docs.mapbox.com/mapbox-gl-js/example/line-gradient/). Which generally achieve these stop-based rendering of colors on lines. But unfortunately, you're trying to get the color stops inferred from the data, and we currently do not support data driven line gradients.

I'll close as duplicate of https://github.com/mapbox/mapbox-gl-js/issues/8977, but feel free to reopen if I misunderstood your use case.

**Closed by karimnaaji** 2021-06-23 22:59 UTC
