### ISSUE TITLE
Setting fill-outline-color results in "Cannot read property 'constantOr' of undefined" error

### ISSUE THREAD

**Issue by danvk** [mapbox/mapbox-gl-js#6589] opened 2018-05-01 23:26 UTC
When I set `paint` on my layer to

```
{ 'fill-color': expr }
```

everything works great. But when I set it to this instead:

```
{
  'fill-color': expr,
  'fill-outline-color': 'rgba(0, 0, 0, 0)'
}
```

I get the following error:

```
Uncaught TypeError: Cannot read property 'constantOr' of undefined
    at ConstantBinder.setUniforms (program_configuration.js:5)
    at ProgramConfiguration.setUniforms (program_configuration.js:5)
    at setFillProgram (draw_fill.js:3)
    at drawFillTile (draw_fill.js:3)
    at drawFillTiles (draw_fill.js:3)
    at Object.drawFill [as fill] (draw_fill.js:3)
    at Painter.renderLayer (painter.js:3)
    at Painter.render (painter.js:3)
    at e._render (map.js:3)
    at map.js:3
```
![image](https://user-images.githubusercontent.com/98301/39498321-76ae53a8-4d75-11e8-8dd9-ac9f9ef6c2cb.png)

I'll see if I can get a more complete repro. See https://stackoverflow.com/questions/49656370/render-geojson-fill-layer-in-mapbox-gl-js-without-outlines

**mapbox-gl-js version**: v0.44.1

### Steps to Trigger Behavior

 1.
 2.
 3.

**Comment by jfirebaugh** [comment] 2018-05-01 23:41
Duplicate of #6238 -- will be fixed in v0.45.0.

**Closed by jfirebaugh** 2018-05-01 23:41 UTC
