### ISSUE TITLE
Outline drawing doesn't work in headless tests

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#4601] opened 2017-04-18 14:02 UTC
While investigating https://github.com/mapbox/mapbox-gl-js/issues/4600, I discovered that drawing polygon outlines (antialiasing) isn't working correctly in headless tests. It does, however, work correctly when rendering in the browser.

Cf.:

JS headless:

![unknown](https://cloud.githubusercontent.com/assets/52399/25134260/6e8028b4-244f-11e7-90dc-7a7c12e88561.png)

Native headless:

![unknown-1](https://cloud.githubusercontent.com/assets/52399/25134340/9734c792-244f-11e7-8759-728e766b10cb.png)

This example is `zoomed-fill/default` from our [render tests](https://7602-8629417-gh.circle-artifacts.com/0/Users/distiller/mapbox-gl-js/test/integration/render-tests/index.html). Other examples in the render tests include `tms/tms`, `extent/1024-fill`, and any other tests that render fill polygons.

**Comment by kkaefer** [comment] 2017-04-18 14:28
See https://github.com/mapbox/mapbox-gl-native/issues/6927#issuecomment-266606578 for a possible cause.

**Comment by jfirebaugh** [comment] 2017-04-18 15:48
I think I saw it wasn't working 100% in the browser either -- it looked like `glLineWidth` didn't support  any values other than 1.

http://webglstats.com/webgl/parameter/ALIASED_LINE_WIDTH_RANGE

**Comment by ansis** [comment] 2017-05-08 16:20
ref #2080

> I think I saw it wasn't working 100% in the browser either

Since I *think* ANGLE doesn't support anything > 1 I *think* it's broken on windows in firefox and chrome.

**Comment by jfirebaugh** [comment] 2017-10-27 20:36
Duplicate of #2080.

**Closed by jfirebaugh** 2017-10-27 20:36 UTC
Labels: testing
